import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {chromium} from '@playwright/test';
import {createGameServer} from '../../tools/coze-web-server.mjs';
import {World} from '../../src/simulation/world';import {campaignTerrain} from '../../src/data/campaign-map';
import {PermanentProfile} from '../../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../../src/data/mvp-talents';import {HERO_IDS_BY_RACE} from '../../src/data/heroes';
import {writeArchive} from '../../src/persistence/archive';import {stats,validity} from './measurement';
const arg=(key:string,fallback:string)=>{const i=process.argv.indexOf(key);return i<0?fallback:process.argv[i+1];};
const label=arg('--label','hud-r1'),seconds=Number(arg('--seconds','60')),repeat=Number(arg('--repeat','3'));
assert.match(label,/^[a-z0-9-]+$/);assert.ok([10,60,180].includes(seconds));assert.ok(repeat>=1&&repeat<=3);
const out='reports/local/visual-baseline-20261010/'+label;await fs.mkdir(out,{recursive:true});
try{await fs.access(out+'/results.json');throw Error('Use a new label; existing evidence is immutable');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}
const races=['terran','zerg','protoss'] as const,fixtures:Record<string,string>={};
for(const race of races){
 const profile=new PermanentProfile();profile.award('visual-baseline-diagnostic',1000,race);profile.selectRace(race);const allocation=Object.fromEntries(MVP_TALENTS.filter(n=>n.race===race&&n.line==='army').map(n=>[n.id,n.maxRank]));assert.ok(profile.savePresetBlueprint(race,0,allocation));
 const terrain=campaignTerrain({version:3,seed:529,theme:'industrial'}),w=new World({race,seed:529,waves:false,terrain,permanentProfile:profile});assert.ok(w.start());for(const p of Object.values(w.expedition.production))p.enabled={};
 const families=({terran:['marine','marauder','tank','medivac','banshee'],zerg:['zergling','roach','hydralisk','ultralisk','lurker'],protoss:['zealot','stalker','immortal','colossus','sentry']} as const)[race];w.expedition.familySlots=[...families];w.entities.clear();w.expedition.zerglingPairs=[];w.stage=12;terrain.setStage(12);w.stageStartedAt=w.time;w.stageElapsed=0;
 let placement=0;for(const family of families){w.expedition.tech['unlock.'+family]=1;for(let i=0;i<7;i++){const slot=placement++,near={x:(slot%7-3)*4,z:(Math.floor(slot/7)-2)*4},point=w.freePosition(family,near,0,12);assert.ok(point,'Legal full-roster placement');assert.ok(w.addFamilyMember(family,point,i%3+1));}}
 for(const hero of HERO_IDS_BY_RACE[race].slice(0,3))assert.ok(w.acquireHero(hero));
 // Explicit high-health stationary diagnostic targets. These are not natural enemy waves.
 const allied=[...w.entities.values()];for(const u of allied){const near={x:u.x+3,z:u.z-3},type=u.flying?'mutalisk':'roach',point=w.freePosition(type,near,0,3)??near,t=w.addUnit(type,'zerg',point.x,point.z,3);t.hp=t.maxHp=2e6;t.moveSpeed=0;t.nextShotAt=t.specialReady=t.stoppedUntil=1e9;}
 w.hash.rebuild(w.entities.values());w.paused=true;w.restoreRun(w.captureRun(),true);fixtures[race]=path.resolve(out,race+'-fixture.json');await fs.writeFile(fixtures[race],writeArchive({profile:profile.exportJSON(),run:w.captureRun()}));
}
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const report:any={label,seconds,repeat,build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Exact released Web and current native HUD. Public current-schema import and resume. Synthetic full-roster plus 3 heroes and stationary high-health targets, no natural campaign acceptance. Headed window, screenshots and public report serialization outside sample. No production debug API or renderer instrumentation.',records:[],errors:[]};
const runner=await fs.readFile(new URL(import.meta.url));report.runnerSha256=createHash('sha256').update(runner).digest('hex');await fs.writeFile(out+'/runner.mts',runner);
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:false,args:['--enable-precise-memory-info','--window-position=0,0','--window-size=1460,1000']});report.browser=browser.version();
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
try{for(const race of races)for(let trial=1;trial<=repeat;trial++){
 const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1}),page=await context.newPage(),errors:string[]=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});const name=race+'-'+trial;
 try{
  await context.addInitScript('window.__name=(value)=>value;');await page.goto(url,{timeout:300000});await page.bringToFront();await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:300000});assert.equal(await page.evaluate(()=>!!window.__SC2_DEBUG__),false);
  await page.locator('.main-actions [data-action=menu-load]').click();const file=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await file).setFiles(fixtures[race]);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:300000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();
  const before=await page.evaluate(()=>window.__SC2_REPORT__());await page.screenshot({path:out+'/'+name+'-paused.png'});
  await page.evaluate(({seconds})=>{
   const w=window as any,p=w.__visualBaselineHUD={active:false,done:false,start:0,last:0,frames:[],frameOffsets:[],visibility:[],focused:[],longTasks:[],before:null,after:null,startHeap:null,endHeap:null};
   new PerformanceObserver(list=>{if(p.active)for(const e of list.getEntries())if(e.startTime>=p.start)p.longTasks.push({at:e.startTime-p.start,ms:e.duration});}).observe({entryTypes:['longtask']});
   document.addEventListener('click',e=>{const target=(e.target as HTMLElement).closest('.pause-actions [data-action=pause]');if(target&&!p.active&&!p.done){p.before=w.__SC2_REPORT__();p.startHeap=(performance as any).memory?.usedJSHeapSize??null;p.start=performance.now();p.active=true;}},true);
   const observe=(now:number)=>{if(p.active){if(p.last){p.frames.push(now-p.last);p.frameOffsets.push(now-p.start);}p.last=now;p.visibility.push(document.visibilityState);p.focused.push(document.hasFocus());if(now-p.start>=seconds*1000){p.active=false;p.done=true;p.seconds=(now-p.start)/1000;p.after=w.__SC2_REPORT__();p.endHeap=(performance as any).memory?.usedJSHeapSize??null;}}if(!p.done)requestAnimationFrame(observe);};requestAnimationFrame(observe);
  },{seconds});
  await page.locator('.pause-actions [data-action=pause]').click();console.log(JSON.stringify({measuring:name,seconds}));await wait(seconds*1000+1000);await page.waitForFunction(()=>(window as any).__visualBaselineHUD.done,null,{timeout:30000});const raw=await page.evaluate(()=>(window as any).__visualBaselineHUD);await fs.writeFile(out+'/'+name+'-raw.json',JSON.stringify(raw));await page.screenshot({path:out+'/'+name+'-battle.png'});
  const gpu=await page.evaluate(()=>{const gl=(document.querySelector('#battle')as HTMLCanvasElement).getContext('webgl2')!,ext=gl.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),contextLost:gl.isContextLost()};});
  const frame=stats(raw.frames),assessment=validity({seconds:raw.seconds,targetSeconds:seconds,frames:raw.frames,frameOffsets:raw.frameOffsets,longTasks:raw.longTasks,cpuWork:[],visibility:raw.visibility,focused:raw.focused,contextLost:gpu.contextLost,errors:errors.length,gpuSupported:false,gpuDisjoint:0,gpuSamples:0,pendingAssets:raw.after.assetsPending,live:true,unchanged:true,phaseComplete:raw.after.phase==='battle'}),reasons=assessment.reasons;
  const record={name,race,trial,before,after:raw.after,seconds:raw.seconds,frame,gpu,combatSeconds:raw.after.time-raw.before.time,discardedDelta:raw.after.discardedSimulationBacklogSeconds-raw.before.discardedSimulationBacklogSeconds,debt:raw.after.simulationBacklogSeconds,heap:{start:raw.startHeap,end:raw.endHeap},longTasks:raw.longTasks,validity:{timingValid:reasons.length===0,reasons,naturalAcceptance:false},errors};report.records.push(record);console.log(JSON.stringify({name,p95:frame.p95,mean:frame.mean,ticksSeconds:record.combatSeconds,reasons}));
  if(trial===1){await page.locator('#topbar [data-action=pause]').click();await page.locator('.pause-actions [data-action=pause]').click();for(const [width,height]of [[844,390],[390,844]]){await page.setViewportSize({width,height});await page.waitForTimeout(350);await page.screenshot({path:out+'/'+name+'-'+width+'x'+height+'.png'});const q=await page.evaluate(()=>window.__SC2_REPORT__());await fs.writeFile(out+'/'+name+'-'+width+'x'+height+'.json',JSON.stringify(q,null,2));}}
 }catch(e){report.errors.push({name,error:String((e as Error).stack??e)});await page.screenshot({path:out+'/'+name+'-failure.png'}).catch(()=>{});throw e;}
 finally{await context.close();await fs.writeFile(out+'/results.json',JSON.stringify(report,null,2));}
}
 report.finishedAt=new Date().toISOString();report.valid=report.records.every((r:any)=>r.validity.timingValid);await fs.writeFile(out+'/results.json',JSON.stringify(report,null,2));
}catch(e){report.failure=String((e as Error).stack??e);await fs.writeFile(out+'/results.json',JSON.stringify(report,null,2));process.exitCode=1;}
finally{await browser.close();await new Promise<void>(r=>server.close(r));}
