import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';
const root='reports/local/visual-baseline-20261010',read=async file=>JSON.parse(await fs.readFile(file,'utf8')),sha=b=>createHash('sha256').update(b).digest('hex');
const inventory=await read(root+'/audit/inventory.json'),previous=await read('reports/local/visual-plan-validation-20261009/inventory.json'),source=await read('reports/local/visual-plan-validation-20261009/source-summary.json');
const oldModels=new Map(previous.models.map(m=>[m.id,m])),oldFiles=new Map(previous.files.map(f=>[f.id,f])),sourceModels=new Map(source.models.map(m=>[m.model,m]));
const changedModels=inventory.models.filter(m=>m.sha256!==oldModels.get(m.id)?.sha256).map(m=>m.id);
const addedResources=inventory.files.filter(f=>!oldFiles.has(f.id)),changedResources=inventory.files.filter(f=>oldFiles.has(f.id)&&oldFiles.get(f.id).sha256!==f.sha256);
const removedResources=previous.files.filter(f=>!inventory.files.some(n=>n.id===f.id)).map(f=>f.id);
const modelStatus=inventory.models.map(m=>{const inherited=oldModels.get(m.id)?.sha256===m.sha256,src=inherited?sourceModels.get(m.id):null;return {model:m.id,runtimeSha256:m.sha256,unchangedFromPrevious:inherited,sourceInterpretation:src??null,sourceStatus:src?'Inherited source interpretation, runtime hash matches; original M3 not reparsed in this stage.':'Source interpretation unavailable; remains open.',materials:m.materials.map(a=>({name:a.name,role:a.role??null,blend:a.blend??null,runtimeClass:a.unlit?'unlit':a.blend===2||a.blend===3?'additive':'lit-or-alpha',hasDiffuse:a.diffuse,hasNormal:a.normal,hasEmissive:a.emissive,hasSpecular:a.specular,risks:[...(a.unlit&&!a.diffuse&&a.emissive?['emissive-only-unlit-review']:[]),...(a.unlit&&a.specular?['unlit-specular-combination']:[])],visualDisposition:'No repair in stage 1; inspect before changing source semantics.'}))};});
const identities=inventory.catalog.map(i=>({id:i.id,kind:i.kind,race:i.race,family:i.family,model:i.model,death:i.death,sharedWith:i.sharedWith,riskModels:[i.model,i.death].filter(Boolean).map(x=>'model.'+x).filter(x=>inventory.risks.some(r=>r.model===x)),nativeReplay:inventory.replays.some(r=>r.subjects.some(s=>s.id===i.id)),historicalVisualRecord:'VISUAL_ALL_UNIT_MATRIX_20261009.md; retains original ae4c2ac build identity; not relabelled.'}));
await fs.writeFile(root+'/model-risk-register.json',JSON.stringify({baseline:inventory.head,counts:inventory.counts,models:modelStatus,identities},null,2));
const labels=(await fs.readdir(root,{withFileTypes:true})).filter(d=>d.isDirectory()&&/^(pilot|baseline|candidate|stability|hud|visual)-/.test(d.name)).map(d=>d.name).sort(),suites=[];
for(const label of labels){try{const r=await read(root+'/'+label+'/results.json');suites.push({label,suite:r.suite??'hud',finishedAt:r.finishedAt??null,failure:r.failure??null,errors:r.errors,records:r.records,build:r.build,chrome:r.chrome??r.browser,host:r.host});}catch(e){if(e.code!=='ENOENT')throw e;}}
const median=a=>{const b=[...a].sort((a,b)=>a-b);return b.length?b[Math.floor(b.length/2)]:null;};
const baselineRows=suites.filter(s=>s.suite==='baseline'&&s.build.revision==='visual-baseline-r2').flatMap(s=>s.records.map(r=>({...r,suite:s.label}))),groups=new Map();for(const r of baselineRows){const key=r.group+'|'+r.theme;const rows=groups.get(key)??[];rows.push(r);groups.set(key,rows);}
const baselineMatrix=[...groups].map(([key,rows])=>({key,samples:rows.length,valid:rows.filter(r=>r.validity.timingValid).length,gpuValid:rows.filter(r=>r.validity.gpuValid).length,initialStates:[...new Set(rows.map(r=>r.initialState))],frameMeanMedian:median(rows.map(r=>r.frame.mean)),p95Range:[Math.min(...rows.map(r=>r.frame.p95)),Math.max(...rows.map(r=>r.frame.p95))],gpuMeanMedian:median(rows.filter(r=>r.validity.gpuValid).map(r=>r.gpu.mean)),simulationMeanMedian:median(rows.map(r=>r.simulation.mean)),submitMeanMedian:median(rows.map(r=>r.submit.mean)),maxDiscarded:Math.max(...rows.map(r=>r.discarded)),references:rows.map(r=>r.suite+'/'+r.name+'.json')}));
const protection=await read(root+'/audit/protected-baseline.json'),changed=[],missing=[];let same=0;for(const f of protection.files){try{const bytes=await fs.readFile(f.file);if(sha(bytes)===f.sha256)same++;else changed.push(f.file);}catch{missing.push(f.file);}}
const hardware=[...new Set(suites.flatMap(s=>s.records.map(r=>r.hardware?.renderer??r.gpu?.renderer).filter(Boolean)))];
const result={baseline:inventory.head,scope:'Stage 1 baseline and diagnostic tools only; no production rendering/gameplay/UI/resource changes.',release:inventory.release,counts:inventory.counts,runtimeModelChanges:changedModels,resources:{retained:previous.files.length,added:addedResources.map(f=>({id:f.id,bytes:f.bytes,sha256:f.sha256})),changed:changedResources.map(f=>f.id),removed:removedResources},riskCounts:{candidates:inventory.models.flatMap(m=>m.materials.filter(x=>x.unlit&&!x.diffuse&&x.emissive)).length,candidateModels:inventory.models.filter(m=>m.materials.some(x=>x.unlit&&!x.diffuse&&x.emissive)).length,invalidCombinations:inventory.models.flatMap(m=>m.materials.filter(x=>x.unlit&&x.specular)).length},source:{inheritedParsedModels:source.counts.parsedModels,activeGapReferences:source.activeSourceGapReferences,inactiveGapReferences:source.inactiveSourceGapReferences,reparsed:false,scienceVesselGate:'OPEN'},baselineMatrix,suites,hardware,protection:{total:protection.files.length,same,changed,missing},sourceDeltaFromPrevious:execFileSync('git',['diff','--stat',previous.head,inventory.head,'--','src','tools/m3-materials.mjs','tools/m3-scene.mjs','tools/import-m3-pack.mjs'],{encoding:'utf8'}),gates:{naturalPerformance:'OPEN',physicalDevices:'OPEN',humanArtReview:'OPEN',P6V01:'OPEN',sourceReferenceClientMatch:'OPEN',productionBackend:'OUT_OF_SCOPE'},interpretation:'Valid measurements can be slow. Synthetic fixtures and short windows do not satisfy the existing 3x180s natural performance contract.'};
await fs.writeFile(root+'/delivery.json',JSON.stringify(result,null,2));
assert.equal(changedModels.length,0);assert.equal(changedResources.length,0);assert.equal(removedResources.length,0);assert.equal(missing.length,0);assert.equal(changed.length,0);assert.equal(identities.length,138);assert.ok(identities.every(i=>i.nativeReplay));
console.log(JSON.stringify({counts:result.counts,risks:result.riskCounts,baselineCases:baselineMatrix.length,baselineSamples:baselineRows.length,baselineValid:baselineRows.filter(r=>r.validity.timingValid).length,protection:result.protection,suites:suites.map(s=>({label:s.label,records:s.records.length,finished:!!s.finishedAt,failure:s.failure}))}));
if(process.argv.includes('--final')){
 assert.equal(baselineMatrix.length,45);assert.equal(baselineRows.length,135);
 assert.ok(baselineMatrix.every(r=>r.samples===3&&r.valid===3&&r.gpuValid===3&&r.initialStates.length===1));
 const hud=suites.find(s=>s.label==='hud-r1'),visual=suites.filter(s=>s.suite==='visual');
 assert.equal(hud.records.length,3);assert.ok(hud.records.every(r=>r.validity.timingValid));
 assert.equal(visual.reduce((n,s)=>n+s.records.length,0),30);assert.ok(visual.every(s=>s.finishedAt&&!s.failure&&!s.errors.length));
 const compiled=await read(root+'/lab/build.json');
 for(const input of compiled.inputs)assert.equal(sha(await fs.readFile(input.file)),input.sha256,'Compiled input changed: '+input.file);
 const checks=await read(root+'/checks-final.json'),regression=await fs.readFile(root+'/regression-final.log','utf8');
 assert.match(regression,/pass 1286/);assert.match(regression,/fail 0/);assert.equal(checks.exitCode,0);
 const publicReport={baseline:result.baseline,scope:result.scope,release:result.release,counts:result.counts,
  lab:{revision:compiled.revision,sourceDigest:compiled.sourceDigest,jsSha256:compiled.jsSha256,checkedInputs:compiled.inputs.length},
  hardware,resources:{thisStageAdded:0,thisStageChanged:0,thisStageRemoved:0,unchangedRuntimeModels:inventory.models.length,retainedFromPrevious:previous.files.length,preexistingHUDAdditions:addedResources.length},
  source:result.source,riskCounts:result.riskCounts,materialRisks:inventory.risks,identities,
  baselineMatrix,baselineSamples:baselineRows.length,baselineValid:baselineRows.filter(r=>r.validity.timingValid).length,
  hud:{samples:hud.records.map(r=>({race:r.race,frame:r.frame,seconds:r.seconds,combatSeconds:r.combatSeconds,discardedDelta:r.discardedDelta,debt:r.debt,validity:r.validity,errors:r.errors})),method:'Exact production Web; synthetic full roster and three heroes, 1440x900 DPR1. One 60-second sample per race. Not comparable by subtraction to scene-only matrix; no private GPU hook.',captures:12},
  visual:{groups:10,captures:30,suites:visual.map(s=>({label:s.label,build:s.build.sourceDigest,records:s.records.map(r=>({name:r.name,state:r.state,screen:s.label+'/'+r.screen}))})),method:'Paused same-state output comparisons; not death-animation, temporal shimmer or reference-client acceptance.'},
  r1Reassessment:await read(root+'/r1-reassessment.json'),checks,protection:result.protection,gates:result.gates,interpretation:result.interpretation,
  deferred:'Candidate lighting/shadow/contact/AA cost matrix, material changes and release defaults remain for later approved stages; no old result relabelled.',
  evidenceRoot:root};
 await fs.mkdir('reports/qa',{recursive:true});await fs.writeFile('reports/qa/visual-baseline-stage1-20261010.json',JSON.stringify(publicReport,null,2));
}
