import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world.ts';
import {distance} from '../src/simulation/movement/steering.ts';
const setup=(initial:any=['marine'])=>{const w=new World({sandbox:true,waves:false,obstacles:[],initial});w.start();return w;};
const enemy=(w:World,x:number,z:number)=>{const e=w.addUnit('roach','zerg',x,z);e.hp=e.maxHp=10000;e.weaponDamage=0;e.moveSpeed=0;return e;};

test('ground orders engage nearby enemies before the anchor reaches its destination',()=>{for(const type of ['marine','hellion','tank'] as const){const w=setup([type]),e=enemy(w,3,1);w.issueMove({x:18,z:0});w.advance(.8);assert.ok(e.hp<e.maxHp,type);assert.ok(w.order?.kind==='move'&&!w.order.arrived);assert.ok(w.allies()[0].distanceWalked>0,type);}});
test('an obstructed formation slot cannot disable a stationary soldiers weapon',()=>{const w=setup(),m=w.allies()[0],e=enemy(w,3,0);m.moveSpeed=0;m.x=-2;w.issueMove({x:0,z:0});w.advance(1);assert.ok(distance(m,w.moveGoal(m))>1);assert.ok(e.hp<e.maxHp);});
test('repeated ground clicks preserve the committed shot and never accelerate cooldowns',()=>{const w=setup(),m=w.allies()[0],e=enemy(w,3,1);for(let i=0;i<90;i++){w.issueMove({x:8,z:0});w.step();}assert.ok(e.hp<e.maxHp);const shots=w.visualEvents.filter(e=>e.kind==='attack'&&e.entityId===m.id);assert.ok(shots.length>=2);assert.ok(shots.length<=Math.floor(1.5/m.attackPeriod)+1);for(let i=1;i<shots.length;i++)assert.ok(shots[i].time-shots[i-1].time>=m.attackPeriod-1/60);});
test('focus travels into weapon range while preserving the players chosen target',()=>{const w=setup(),m=w.allies()[0],near=enemy(w,0,-3),chosen=enemy(w,12,0);w.issueFocus(chosen.id);const start={...m};w.advance(5);assert.ok(distance(m,start)>3);assert.ok(w.anchor.x>5);assert.equal(m.attackTarget,chosen.id);assert.ok(chosen.hp<chosen.maxHp);assert.ok(near.hp<near.maxHp);});
test('an out-of-range focus keeps pursuing after the target moves again',()=>{const w=setup(),m=w.allies()[0],chosen=enemy(w,10,0);w.issueFocus(chosen.id);w.advance(4);const before={...m},hp=chosen.hp;chosen.x=20;w.advance(5);assert.ok(m.x>before.x+3);assert.equal(m.attackTarget,chosen.id);assert.ok(chosen.hp<hp);});
test('focus death immediately restores available automatic threats',()=>{const w=setup(),chosen=enemy(w,3,0),other=enemy(w,0,4);w.issueFocus(chosen.id);w.advance(.3);w.hit(chosen,20000);w.advance(1);assert.equal(w.order,null);assert.ok(other.hp<other.maxHp);});
test('sieged tanks ignore dead-zone bait and can defend while a selected target is unreachable',()=>{const w=setup(['tank']),u=w.allies()[0];u.mode=u.desiredMode='siege';w.refreshStats(u);enemy(w,2,0);const available=enemy(w,8,0),far=enemy(w,30,0),position={...u};w.issueFocus(far.id);w.advance(3.5);assert.ok(available.hp<available.maxHp);assert.ok(distance(u,position)<.01);assert.equal(u.mode,'siege');assert.equal(w.order?.kind,'focus');});
test('automatic acquisition prefers a shootable threat over a wounded threat outside range',()=>{const w=setup(),m=w.allies()[0];m.moveSpeed=0;const close=enemy(w,5,1),far=enemy(w,7,0);far.hp=1;w.issueMove({x:0,z:0});w.advance(.5);assert.ok(close.hp<close.maxHp);});
test('a new manual target receives a pending shot without resetting its weapon cycle',()=>{const w=setup(),m=w.allies()[0],old=enemy(w,3,0),chosen=enemy(w,4,1);w.issueFocus(old.id);w.step();assert.ok(m.windup>0);const cooldown=m.weaponCooldown;w.issueFocus(chosen.id);assert.equal(m.weaponCooldown,cooldown);w.advance(.1);assert.equal(old.hp,old.maxHp);assert.ok(chosen.hp<chosen.maxHp);assert.equal(w.stats.shots,1);});
test('focus routes through ramps toward an enemy beyond a cliff',()=>{const w=new World({sandbox:true,waves:false,obstacles:[],terrain:true});w.start();const m=w.allies()[0],chosen=enemy(w,34,8);assert.ok(w.issueFocus(chosen.id));for(let i=0;i<2400;i++){const old={...m};w.step();assert.ok(w.terrain!.canStep(old,m,m.unitRadius));assert.ok(distance(old,m)<.13);}assert.ok(chosen.hp<chosen.maxHp);assert.equal(m.attackTarget,chosen.id);assert.equal(w.terrain!.height(m),3);});
test('Medivac keeps healing through a ground command and focus has no offensive target',()=>{const w=setup(['marine','medivac']),m=w.allies()[0],med=w.allies()[1],e=enemy(w,3,0);m.hp=1;w.issueMove({x:10,z:0});w.advance(.3);assert.ok(w.stats.healed>0);w.issueFocus(e.id);w.advance(.5);assert.equal(med.attackTarget,null);assert.equal(med.lastShotAt,-100);});
