import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world.ts';
import {distance,blocked} from '../src/simulation/movement/steering.ts';
import {SIEGE} from '../src/data/sc2-units.ts';
const world=(initial:any=['marine'])=>{const w=new World({sandbox:true,waves:false,obstacles:[],initial});w.start();return w;};
const dummy=(w:World,x:number,z:number)=>{const e=w.addUnit('roach','zerg',x,z);e.hp=e.maxHp=10000;e.weaponDamage=0;e.moveSpeed=0;return e;};
test('point commands require battle, a finite open destination',()=>{const w=new World({sandbox:true,waves:false,obstacles:[]});assert.equal(w.issueMove({x:8,z:0}),false);w.start();assert.equal(w.issueMove({x:NaN,z:0}),false);assert.equal(w.issueMove({x:999,z:0}),false);assert.ok(w.issueMove({x:8,z:0}));const old=w.order;w.paused=true;assert.equal(w.issueMove({x:0,z:8}),false);assert.equal(w.order,old);});
test('a point move routes independent units while engaging before and after arrival',()=>{const w=world(),m=w.allies()[0],e=dummy(w,5,3);assert.ok(w.issueMove({x:8,z:0}));let arrived=false,firedEnRoute=false;for(let i=0;i<420;i++){const old={x:m.x,z:m.z};w.step();assert.ok(distance(m,old)<.13);if(w.order?.kind==='move'&&!w.order.arrived&&m.lastShotAt>0)firedEnRoute=true;if(distance(w.anchor,{x:8,z:0})<.13)arrived=true;}assert.ok(arrived);assert.ok(firedEnRoute);assert.ok(distance(w.anchor,{x:8,z:0})<.13);assert.ok(e.hp<e.maxHp);assert.equal(w.order,null);});
test('keyboard and joystick direction take over a point command, pause freezes it, reward clears it',()=>{const w=world();w.issueMove({x:14,z:4});w.advance(.2);const before={...w.anchor},order=w.order;w.paused=true;w.advance(4);assert.deepEqual(w.anchor,before);assert.equal(w.order,order);w.paused=false;w.input={x:-1,z:0};w.step();assert.equal(w.order,null);assert.ok(w.anchor.x<before.x);w.input={x:0,z:0};w.issueMove({x:4,z:0});w.endStage();assert.equal(w.order,null);});
test('newly rescued troops follow a pending move order and can defend while catching up',()=>{const w=world();w.issueMove({x:14,z:0});w.advance(.3);const m=w.addUnit('marine','terran',0,0),e=dummy(w,2,2);w.advance(.6);assert.ok(m.lastShotAt>0);assert.ok(m.distanceWalked>0);assert.ok(e.hp<e.maxHp);});
test('Medivac heals during a movement order and never acquires a damaging target',()=>{const w=world(['marine','medivac']),m=w.allies()[0],med=w.allies()[1],e=dummy(w,3,0);m.hp=1;w.issueMove({x:e.x,z:e.z});w.advance(1);assert.ok(m.hp>1);assert.ok(w.stats.healed>0);assert.equal(med.attackTarget,null);});
test('deployed Tanks stay put under point orders and execute them only after manual unsiege',()=>{const w=world(['tank']),u=w.allies()[0];w.toggleTanks();w.advance(SIEGE.deploySeconds+.1);const old={x:u.x,z:u.z};w.issueMove({x:14,z:0});w.advance(4);assert.deepEqual({x:u.x,z:u.z},old);assert.equal(u.mode,'siege');w.toggleTanks();w.advance(SIEGE.undeploySeconds+10);assert.equal(u.mode,'tank');assert.ok(u.x>5);});
test('pointer movement uses obstacle routes instead of walking into the clicked wall',()=>{const w=new World({sandbox:true,waves:false,obstacles:[{x:3,z:0,w:2,h:12}]});w.start();assert.ok(w.issueMove({x:3,z:0}));assert.equal(w.order?.kind,'move');const goal=w.order!.kind==='move'?w.order!.point:{x:0,z:0};assert.equal(blocked(goal,.9,w.obstacles),false);w.advance(25);assert.ok(distance(w.anchor,goal)<.13);assert.ok(distance(w.allies()[0],w.moveGoal(w.allies()[0]))<1);});
test('point-command anchor and vehicles cross cliffs only through the shared ramps',()=>{const w=new World({sandbox:true,waves:false,obstacles:[],initial:['tank'],terrain:true});w.start();assert.ok(w.issueMove({x:34,z:8}));for(let i=0;i<2400;i++){const old={...w.anchor};w.step();assert.ok(w.terrain!.canStep(old,w.anchor,.8));}assert.ok(distance(w.anchor,{x:34,z:8})<.13);assert.equal(w.terrain!.height(w.allies()[0]),3);});

test('mixed fighters enter their own ranges and all fire at a local enemy after moving nearby',()=>{const w=world(['marine','hellion','tank','medivac']),e=dummy(w,14,0);assert.ok(w.issueMove({x:e.x,z:e.z}));w.advance(12);for(const u of w.allies().filter(u=>u.unitType!=='medivac')){assert.equal(u.attackTarget,e.id,u.unitType);assert.ok(u.lastShotAt>0,u.unitType);assert.ok(w.edgeDistance(u,e)<=u.attackRange+.1,u.unitType);}assert.equal(w.allies().find(u=>u.unitType==='medivac')!.attackTarget,null);});
