import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {THREE_RACE_RULES} from '../src/data/races';
import {updateExpeditionProduction,receiptNeeded,releasePaidPassenger} from '../src/simulation/expedition-production';
const world=(race:'terran'|'zerg'|'protoss'='terran')=>new World({rulesVersion:THREE_RACE_RULES,race,sandbox:true,waves:false,terrain:false,obstacles:[]});
function readyReplacement(){const w=world();w.start();const s=w.expedition!;s.familySlots=['marine','marauder','reaper','hellion','tank'];s.tech.starport=1;s.tech.factory=1;s.tech.starport_lab=1;w.entities.clear();for(let i=0;i<5;i++)w.addUnit('marine','terran',-8,i*2,5);w.addUnit('marauder','terran',-6,0,3);const pod=w.spawnPod('viking',{x:8,z:0},99,1);pod.status='opening';pod.resolvedAt=0;pod.guardianIds.clear();s.ledger.push({id:99,family:'viking',line:'starport',facilityIds:[1],remaining:0,state:'risk',podId:pod.id,passengers:[{paid:{minerals:125,gas:75},status:'waiting',entityId:null,purpose:'body'}]});receiptNeeded(w,pod,0);return {w,s,pod};}
test('three races deploy equal 100 mineral starting budgets and distinct identity',()=>{for(const race of ['terran','zerg','protoss'] as const){const w=world(race);assert.equal(w.expedition!.familySlots.length,1);assert.ok(w.allies().every(u=>u.team==='player'&&u.race===race));assert.equal(w.allies().length,race==='zerg'?2:1);assert.equal(w.wallet.minerals,race==='protoss'?0:50);}});
test('a prepaid batch survives output disabling with exact per-body payment',()=>{const w=world();w.start();w.wallet={minerals:1000,gas:1000};updateExpeditionProduction(w,0);const job=w.expedition!.ledger[0];assert.equal(job.passengers.length,1);assert.deepEqual(job.passengers[0].paid,{minerals:50,gas:0});const paid={...w.wallet};assert.ok(w.setProductionEnabled('marine',false));updateExpeditionProduction(w,100);assert.equal(job.state,'risk');assert.deepEqual(w.wallet,paid);assert.equal(w.expedition!.ledger.length,1);});
test('two outputs alternate and a third is rejected without mutating production',()=>{const w=world();w.expedition!.tech.barracks_lab=1;w.expedition!.facilities[0].techLab=true;assert.ok(w.setProductionOutputs('barracks',['marine','reaper']));assert.equal(w.setProductionOutputs('barracks',['marine','reaper','marauder']),false);w.start();w.wallet={minerals:5000,gas:5000};updateExpeditionProduction(w,0);const a=w.expedition!.ledger[0];assert.equal(a.family,'marine');a.state='settled';a.passengers.forEach(c=>c.status='lost');updateExpeditionProduction(w,0);assert.equal(w.expedition!.ledger[1].family,'reaper');});
test('five rank5 bodies yield five rank3 credits; current passenger never pays twice',()=>{const {w,s,pod}=readyReplacement(),request=s.pendingReceipt!,wallet={...w.wallet},other=structuredClone(w.familyUnits('marauder'));const preview=w.previewFamilyReplacement(request.id,'marine')!;assert.deepEqual(preview.credits.map(c=>c.rank),[3,3,3,3,3]);assert.ok(w.commitFamilyReplacement(request.id,'marine',preview.revision));assert.deepEqual(w.wallet,wallet);assert.equal(w.familyUnits('viking')[0].rank,3);assert.equal(s.credits.viking!.length,4);assert.deepEqual(w.familyUnits('marauder'),other);assert.equal(pod.passengers[0].status,'released');assert.equal(w.commitFamilyReplacement(request.id,'marine',w.revision),false);assert.equal(w.familyUnits('viking').length,1);});
test('decision freezes simulation and round-trips without reroll or resource changes',()=>{const {w,s}=readyReplacement(),before=w.time;w.step();assert.equal(w.time,before);const saved=w.captureRun(),restored=world();restored.restoreRun(saved);assert.deepEqual(restored.expedition!.pendingReceipt,s.pendingReceipt);assert.deepEqual(restored.wallet,w.wallet);assert.ok(restored.requiresPlayerDecision);});
test('replacement refunds only unlaunched paid passengers and retires without rewards',()=>{const {w,s}=readyReplacement(),before={...w.wallet},stats={...w.stats};s.ledger.push({id:100,family:'marine',line:'barracks',facilityIds:[1],remaining:5,state:'training',podId:null,passengers:[{paid:{minerals:37,gas:2},status:'waiting',entityId:null,purpose:'body'},{paid:{minerals:38,gas:3},status:'waiting',entityId:null,purpose:'body'}]});const p=w.spawnPod('marine',{x:20,z:0},101,1);s.ledger.push({id:101,family:'marine',line:'barracks',facilityIds:[],remaining:0,state:'risk',podId:p.id,passengers:[{paid:{minerals:50,gas:0},status:'waiting',entityId:null,purpose:'body'}]});const request=s.pendingReceipt!,preview=w.previewFamilyReplacement(request.id,'marine')!;assert.deepEqual(preview.refund,{minerals:75,gas:5});assert.equal(preview.lostPassengers,1);assert.ok(w.commitFamilyReplacement(request.id,'marine',preview.revision));assert.equal(w.wallet.minerals,before.minerals+75);assert.equal(w.wallet.gas,before.gas+5);assert.equal(p.passengers[0].status,'lost');assert.equal(w.stats.kills,stats.kills);assert.equal(w.stats.damage,stats.damage);});
test('blocked exits preserve old army, request and wallet',()=>{const {w,s}=readyReplacement();w.freePosition=()=>null;const before=w.captureRun();assert.equal(w.previewFamilyReplacement(s.pendingReceipt!.id,'marine'),null);assert.equal(w.commitFamilyReplacement(s.pendingReceipt!.id,'marine',w.revision),false);assert.deepEqual(w.captureRun(),before);});
test('remaining cultivation credits attach only to distinct paid new bodies',()=>{const {w,s}=readyReplacement();const r=s.pendingReceipt!;assert.ok(w.commitFamilyReplacement(r.id,'marine',w.revision));const p=w.spawnPod('viking',{x:10,z:8},103,1);s.ledger.push({id:103,family:'viking',line:'starport',facilityIds:[],remaining:0,state:'risk',podId:p.id,passengers:[{paid:{minerals:125,gas:75},status:'waiting',entityId:null,purpose:'body'}]});assert.ok(releasePaidPassenger(w,p,0,{x:10,z:8}));assert.equal(releasePaidPassenger(w,p,0,{x:10,z:8}),null);assert.equal(s.credits.viking!.length,3);assert.deepEqual(w.familyUnits('viking').map(u=>u.rank),[3,3]);});
test('heavy families can be selected after stage 9 but only start production in stage 10',()=>{
 for(const [race,family,line,requirements] of [['terran','thor','factory',['factory','factory_lab','armory']],['zerg','ultralisk','zerg.evolution',['ultralisk_cavern']],['protoss','carrier','stargate',['fleet_beacon']]] as const){
  const w=world(race);w.start();const s=w.expedition!;for(const id of requirements)s.tech[id]=1;s.facilities.push({id:s.nextFacility++,kind:race==='zerg'?'hatchery':line,line,techLab:true});w.wallet={minerals:1000,gas:1000};
  w.stage=8;w.phase='reward';assert.equal(w.isFamilyAvailable(family),false);assert.equal(w.setProductionOutputs(line,[family]),false);
  w.stage=9;w.phase='battle';assert.equal(w.isFamilyAvailable(family),false);w.phase='reward';assert.equal(w.isFamilyAvailable(family),true);assert.equal(w.setProductionOutputs(line,[family]),true);updateExpeditionProduction(w,0);assert.equal(s.ledger.length,0);
  w.phase='battle';updateExpeditionProduction(w,0);assert.ok(!s.ledger.some(j=>j.family===family));w.stage=10;updateExpeditionProduction(w,0);assert.ok(s.ledger.some(j=>j.family===family));
 }
});
