import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
const make=()=>{const w=new World({sandbox:true,terrain:false,obstacles:[],waves:false,seed:73});w.start();w.random=()=>.5;return w;};
const kill=(w:World)=>{const boss=w.spawnSpecial('zergling','boss',{x:10,z:0})!;w.hit(boss,1e9,[],1,'terran');return boss;};

test('opening, deferring and claiming Boss rewards preserves the explicit pause state',()=>{
 for(const paused of [false,true]){
  const w=make();kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);
  const receipt=w.expedition.bossLootQueue[0].receipt;w.paused=paused;
  assert.equal(w.closeBossLoot(),true);assert.equal(w.paused,paused);
  assert.equal(w.openBossLoot(),true);assert.equal(w.paused,paused);
  assert.equal(w.claimBossLoot(receipt,'marine.1'),true);assert.equal(w.paused,paused);
  assert.equal(w.expedition.bossLootQueue.length,0);
 }
});
test('Boss death drops exactly one physical free elite reward, independently of map cards and repeated hits',()=>{const w=make();const boss=kill(w);const drops=w.rewardDrops.filter(d=>d.bossLootReceipt);assert.equal(drops.length,1);assert.equal(drops[0].reward.rarity,'purple');assert.equal(drops[0].reward.minerals,0);assert.equal(drops[0].reward.gas,0);assert.equal(w.expedition.bossLootQueue.length,0);w.hit(boss,1e9,[],1,'terran');assert.equal(w.rewardDrops.filter(d=>d.bossLootReceipt).length,1);assert.deepEqual(w.expedition.mapCardsByChapter,{});});
test('Boss drop pickup freezes simulation; dismiss/reopen/save preserves exact reward and charges nothing',()=>{const w=make();kill(w);const drop=w.rewardDrops.find(d=>d.bossLootReceipt)!;const wallet={...w.wallet};assert.equal(w.collectRewardDrop(drop.id),true);assert.equal(w.requiresPlayerDecision,true);const before=w.time;w.step();assert.equal(w.time,before);const reward=structuredClone(w.expedition.bossLootQueue[0]);assert.equal(w.closeBossLoot(),true);assert.equal(w.requiresPlayerDecision,false);assert.deepEqual(w.wallet,wallet);const copy=make();copy.restoreRun(w.captureRun());assert.deepEqual(copy.expedition.bossLootQueue[0],reward);assert.equal(copy.openBossLoot(),true);const chosen=copy.expedition.bossLootQueue[0];assert.equal(copy.claimBossLoot(chosen.receipt,'marine.2'),true);assert.equal(copy.eliteOwned('marine.2')?.rank,1);assert.deepEqual(copy.wallet,wallet);assert.equal(copy.claimBossLoot(chosen.receipt,'marine.2'),false);});
test('full family Boss elite selection can be canceled without consuming reward or removing an ordinary body',()=>{const w=make();for(let i=1;i<5;i++)w.addUnit('marine','terran',i,0);kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);const entry=w.expedition.bossLootQueue[0],wallet={...w.wallet};assert.equal(w.claimBossLoot(entry.receipt,'marine.3'),false);assert.equal(w.selectBossLootVariant(entry.receipt,'marine.3'),true);assert.equal(w.closeBossLoot(),true);assert.equal(w.familyUnits('marine').length,5);assert.equal(w.pendingElites.length,0);w.openBossLoot();const target=w.ordinaryUnits('marine')[0];assert.equal(w.claimBossLoot(entry.receipt,'marine.3',target.id),true);assert.equal(w.familyUnits('marine').length,5);assert.equal(w.entities.get(target.id)?.eliteId,'marine.3');assert.deepEqual(w.wallet,wallet);});
test('final-stage clear preserves uncollected physical Boss reward in the persistent queue',()=>{const w=make();w.stage=18;w.prepareStage();const boss=(w as any).spawnCampaignSpecial((w as any).specialPlan[0]);w.hit(boss,1e9,[],1,'terran');const receipt=w.rewardDrops.find(d=>d.bossLootReceipt)!.bossLootReceipt;w.hive!.hp=0;w.stageElapsed=150;w.endStage();assert.equal(w.phase,'won');assert.equal(w.expedition.bossLootQueue[0].receipt,receipt);assert.equal(w.expedition.bossLootOpen,true);assert.equal(w.claimBossLoot(receipt!,'marine.1'),true);assert.equal(w.expedition.bossLootQueue.length,0);});
test('orange Boss reward claims an actual hero once without using shop receipts',()=>{const w=make();w.random=()=>.1;kill(w);const drop=w.rewardDrops.find(d=>d.bossLootReceipt)!;assert.equal(drop.reward.rarity,'orange');assert.equal(drop.reward.kind,'hero');w.collectRewardDrop(drop.id);const entry=w.expedition.bossLootQueue[0];assert.equal(w.claimBossLoot(entry.receipt),true);assert.equal(w.heroes.size,1);assert.equal(w.expedition.draftClaims.length,0);assert.equal(w.expedition.talentLootReceipts.length,0);});
test('physical Boss receipt survives save before pickup and cannot be issued twice',()=>{const w=make();const boss=kill(w);const copy=make();copy.restoreRun(w.captureRun());const drop=copy.rewardDrops.find(d=>d.bossLootReceipt)!;copy.tryRewardDrop(copy.entities.get(boss.id)!,false,'boss');assert.equal(copy.rewardDrops.filter(d=>d.bossLootReceipt).length,1);assert.equal(copy.collectRewardDrop(drop.id),true);assert.equal(copy.collectRewardDrop(drop.id),false);assert.equal(copy.expedition.bossLootQueue.length,1);});
test('Boss loot renderer keeps three free variants, cancel and replacement confirmation separate',async()=>{const {renderBossLoot}=await import('../src/ui/hud/boss-loot-panel');const w=make();for(let i=1;i<5;i++)w.addUnit('marine','terran',i,0);kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);const entry=w.expedition.bossLootQueue[0];const choice=renderBossLoot(w,()=>true);assert.equal((choice.match(/data-action="boss-loot-variant"/g)??[]).length,3);assert.match(choice,/boss-loot-close/);w.selectBossLootVariant(entry.receipt,'marine.2');const confirmation=renderBossLoot(w,()=>true);assert.equal((confirmation.match(/data-target=/g)??[]).length,5);assert.match(confirmation,/boss-loot-variant-back/);assert.equal(w.eliteOwned('marine.2'),undefined);});
test('a Boss hero reward that reaches max rank while deferred falls back to a legal unit for free',()=>{const w=make();w.random=()=>.1;kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);const entry=w.expedition.bossLootQueue[0],effect=entry.reward.expeditionEffect;assert.equal(effect.kind,'hero');if(effect.kind!=='hero')return;w.closeBossLoot();for(let i=0;i<5;i++)assert.equal(w.acquireHero(effect.heroId as any),true);const wallet={...w.wallet};assert.equal(w.openBossLoot(),true);assert.notEqual(w.expedition.bossLootQueue[0].reward.value,effect.heroId);assert.equal(w.expedition.bossLootQueue[0].receipt,entry.receipt);assert.equal(w.claimBossLoot(entry.receipt),true);assert.deepEqual(w.wallet,wallet);assert.equal(w.expedition.talentLootReceipts.length,0);});
test('deferred elite loot follows the legal locked variant instead of losing the reward',()=>{const w=make();kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);const entry=w.expedition.bossLootQueue[0];w.selectBossLootVariant(entry.receipt,'marine.2');w.closeBossLoot();assert.equal(w.acquireElite('marine.1'),true);w.openBossLoot();assert.equal(w.expedition.bossLootQueue[0].variant,null);assert.equal(w.claimBossLoot(entry.receipt,'marine.1'),true);assert.equal(w.eliteOwned('marine.1')?.rank,2);});
test('all permanently exhausted Boss unit targets convert once to 250 minerals and 100 gas',()=>{const w=make();w.random=()=>.1;kill(w);w.collectRewardDrop(w.rewardDrops.find(d=>d.bossLootReceipt)!.id);const receipt=w.expedition.bossLootQueue[0].receipt;w.closeBossLoot();for(const hero of ['raynor','swann','nova'] as const)for(let i=0;i<5;i++)assert.equal(w.acquireHero(hero),true);for(let i=0;i<5;i++)assert.equal(w.acquireElite('marine.1'),true);const before={...w.wallet};w.openBossLoot();assert.equal(w.expedition.bossLootQueue[0].reward.expeditionEffect.kind,'resource');assert.equal(w.claimBossLoot(receipt),true);assert.deepEqual(w.wallet,{minerals:before.minerals+250,gas:before.gas+100});assert.equal(w.claimBossLoot(receipt),false);});
