import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {takeUnitArrivals} from '../src/simulation/boss-loot';
const make=()=>{const w=new World({sandbox:true,terrain:false,obstacles:[],waves:false,seed:73});w.start();w.random=()=>.5;return w;};
const kill=(w:World,tier:'boss'|'lord'='boss')=>{const boss=w.spawnSpecial('zergling',tier,{x:10,z:0})!;w.hit(boss,1e9,[],1,'terran');return boss;};
const drop=(w:World)=>w.rewardDrops.find(d=>d.bossLootReceipt)!;

test('Boss/lord death rolls one free physical drop, freezes identity, and repeated hits do not duplicate it',()=>{for(const tier of ['boss','lord'] as const){const w=make(),boss=kill(w,tier),d=drop(w);assert.equal(d.reward.rarity,'purple');assert.equal(d.reward.minerals,0);assert.ok(d.bossLootVariant);assert.equal(w.eliteOwned(d.bossLootVariant!),undefined);w.hit(boss,1e9,[],1,'terran');assert.equal(w.rewardDrops.filter(d=>d.bossLootReceipt).length,1);assert.equal(w.expedition.mapLootStats.regular.attempts,0);}});
test('pickup immediately joins the frozen identity once, without wallet, shop, pause or decision changes',()=>{for(const paused of [true,false]){const w=make();kill(w);const d=drop(w),money={...w.wallet};w.paused=paused;assert.ok(w.collectRewardDrop(d.id));assert.equal(w.eliteOwned(d.bossLootVariant!)?.rank,1);assert.equal(w.paused,paused);assert.equal(w.requiresPlayerDecision,false);assert.equal(w.expedition.bossLootQueue.length,0);assert.equal(w.expedition.bossLootOpen,false);assert.deepEqual(w.wallet,money);assert.equal(w.collectRewardDrop(d.id),false);const notice=takeUnitArrivals(w);assert.equal(notice.length,1);assert.equal(notice[0].identity,d.bossLootVariant);assert.equal(notice[0].promoted,false);assert.equal(takeUnitArrivals(w).length,0);w.paused=false;const before=w.time;w.step();assert.ok(w.time>before);}});
test('same identity promotes; presentation says promotion and rank II',()=>{const w=make();kill(w);const d=drop(w);assert.ok(w.acquireElite(d.bossLootVariant!));assert.ok(w.collectRewardDrop(d.id));assert.equal(w.eliteOwned(d.bossLootVariant!)?.rank,2);assert.equal(takeUnitArrivals(w)[0].promoted,true);});
test('full family replaces lowest legal ordinary rank, stable ID tie break, and keeps elites',()=>{const w=make();for(let i=1;i<5;i++)w.addUnit('marine','terran',i,0,i===1?3:1);kill(w);const d=drop(w),target=w.eliteCandidates(d.bossLootVariant!).sort((a,b)=>a.rank-b.rank||a.id-b.id)[0];assert.ok(w.collectRewardDrop(d.id));assert.equal(w.familyUnits('marine').length,5);assert.equal(w.eliteOwned(d.bossLootVariant!)?.id,target.id);assert.equal(w.pendingElites.length,0);});
test('paid training reservations and existing elite bodies survive automatic replacement',()=>{const w=make();for(let i=1;i<5;i++)w.addUnit('marine','terran',i,0,i===1?5:1);w.expedition.ledger.push({id:99,family:'marine',line:'barracks',facilityIds:[1],remaining:5,state:'training',podId:null,passengers:Array.from({length:14},()=>({paid:{minerals:50,gas:0},status:'waiting' as const,entityId:null,purpose:'body' as const}))});const ledger=structuredClone(w.expedition.ledger),reservedTarget=w.ordinaryUnits('marine').find(u=>u.rank===5)!.id;kill(w);const d=drop(w);assert.ok(w.collectRewardDrop(d.id));assert.deepEqual(w.expedition.ledger,ledger);assert.equal(w.eliteOwned(d.bossLootVariant!)?.id,reservedTarget);assert.equal(w.pendingElites.length,0);});
test('save before pickup retains identity; save after pickup cannot replay acquisition or reveal',()=>{const w=make();kill(w);const d=drop(w),copy=make();copy.restoreRun(w.captureRun());assert.equal(drop(copy).bossLootVariant,d.bossLootVariant);assert.ok(copy.collectRewardDrop(d.id));const done=make();done.restoreRun(copy.captureRun());assert.equal(done.eliteOwned(d.bossLootVariant!)?.rank,1);assert.equal(done.collectRewardDrop(d.id),false);assert.equal(takeUnitArrivals(done).length,0);});
test('existing schema-26 pending receipt settles on restore exactly once, retaining selected variant',()=>{const w=make();kill(w);const d=drop(w);w.rewardDrops=[];w.expedition.bossLootQueue.push({receipt:d.bossLootReceipt!,reward:d.reward as any,variant:'marine.2'});w.expedition.bossLootOpen=true;const copy=make();copy.restoreRun(w.captureRun());assert.equal(copy.eliteOwned('marine.2')?.rank,1);assert.equal(copy.expedition.bossLootQueue.length,0);assert.equal(copy.requiresPlayerDecision,false);const done=make();done.restoreRun(copy.captureRun());assert.equal(done.eliteOwned('marine.2')?.rank,1);assert.equal(takeUnitArrivals(done).length,0);});
test('stage transition automatically collects the final Boss drop',()=>{const w=make();w.stage=18;w.prepareStage();const boss=(w as any).spawnCampaignSpecial((w as any).specialPlan[0]);w.hit(boss,1e9,[],1,'terran');const receipt=drop(w).bossLootReceipt;w.hive!.hp=0;w.stageElapsed=150;w.endStage();assert.equal(w.phase,'won');assert.ok(w.expedition.bossLootClaimed.includes(receipt!));assert.equal(w.expedition.bossLootQueue.length,0);assert.equal(w.requiresPlayerDecision,false);});
test('orange drop joins a hero once without shop/talent receipts; capacity changes use native fallback',()=>{const w=make();w.random=()=>.1;kill(w);const d=drop(w);assert.equal(d.reward.rarity,'orange');assert.ok(w.collectRewardDrop(d.id));assert.equal(w.heroes.size,1);assert.equal(w.expedition.draftClaims.length,0);assert.equal(w.expedition.talentLootReceipts.length,0);assert.equal(takeUnitArrivals(w)[0].kind,'hero');});
test('exhausted unit pool recycles once to the existing 250 minerals/100 gas',()=>{const w=make();w.random=()=>.1;kill(w);const d=drop(w);for(const id of ['raynor','swann','nova'] as const)for(let i=0;i<5;i++)assert.ok(w.acquireHero(id));for(const id of ['marine.1','marine.2','marine.3'] as const)for(let i=0;i<5;i++)assert.ok(w.acquireElite(id));const before={...w.wallet};assert.ok(w.collectRewardDrop(d.id));assert.deepEqual(w.wallet,{minerals:before.minerals+250,gas:before.gas+100});assert.equal(takeUnitArrivals(w).length,0);assert.equal(w.collectRewardDrop(d.id),false);});
test('blocked spawn retains its saved physical receipt and retries without reroll',()=>{const w=make();kill(w);const d=drop(w),position=w.freePosition;w.freePosition=()=>null;assert.equal(w.collectRewardDrop(d.id),false);assert.ok(w.rewardDrops.includes(d));assert.equal(w.expedition.bossLootClaimed.length,0);w.freePosition=position;assert.ok(w.collectRewardDrop(d.id));assert.equal(w.eliteOwned(d.bossLootVariant!)?.rank,1);});

test('all three races automatically receive and promote their own elite identities, including paired Zerglings',()=>{for(const race of ['terran','zerg','protoss'] as const){const w=new World({race,sandbox:true,terrain:false,obstacles:[],waves:false,seed:73});w.start();w.random=()=>.5;kill(w);const d=drop(w);assert.ok(d.bossLootVariant);assert.ok(w.acquireElite(d.bossLootVariant!));assert.ok(w.collectRewardDrop(d.id));assert.equal(w.eliteOwned(d.bossLootVariant!)?.rank,2);assert.equal(w.requiresPlayerDecision,false);if(race==='zerg')assert.equal(w.familyBodies('zergling').filter(u=>u.eliteId===d.bossLootVariant).length,2);}});
test('transition with a blocked landing retains an automatic receipt until an unpaused step can place it',()=>{const w=make();kill(w);const receipt=drop(w).bossLootReceipt!,position=w.freePosition;w.freePosition=()=>null;w.endStage();assert.equal(w.expedition.bossLootQueue.length,1);assert.equal(w.requiresPlayerDecision,false);const snapshot=w.captureRun();const copy=make();copy.restoreRun(snapshot);assert.ok(copy.expedition.bossLootClaimed.includes(receipt));assert.equal(copy.expedition.bossLootQueue.length,0);w.freePosition=position;w.phase='battle';w.paused=true;w.step();assert.equal(w.expedition.bossLootQueue.length,1);w.paused=false;w.step();assert.equal(w.expedition.bossLootQueue.length,0);assert.equal(w.expedition.bossLootClaimed.filter(r=>r===receipt).length,1);});
test('a hero becoming max rank before pickup uses the existing legal fallback without changing combat RNG',()=>{const w=make();w.random=()=>.1;kill(w);const d=drop(w),effect=(d.reward as any).expeditionEffect;for(let i=0;i<5;i++)assert.ok(w.acquireHero(effect.heroId));let calls=0;w.random=()=>{calls++;return .9;};assert.ok(w.collectRewardDrop(d.id));assert.equal(w.heroes.get(effect.heroId)!.rank,5);assert.ok(takeUnitArrivals(w).length);assert.equal(calls,0);assert.equal(w.expedition.bossLootQueue.length,0);});
test('frozen foreign elite identity in a drop is rejected before mutating the live world',()=>{const w=make();kill(w);const snap=structuredClone(w.captureRun());snap.state.rewardDrops.find(d=>d.bossLootReceipt)!.bossLootVariant='zergling.1';const copy=make(),before=copy.captureRun();assert.throws(()=>copy.restoreRun(snap),/掉落精英身份无效/);assert.deepEqual(copy.captureRun(),before);});
