import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {campaign18StageConfig,campaign18Schedule,campaign18EnemyPressure} from '../src/data/campaign18';
import {ENDLESS} from '../src/data/endless';
import {SC2_UNITS} from '../src/data/sc2-units';
const make=()=>{const w=new World({sandbox:true,terrain:false,obstacles:[],waves:false,seed:421});w.start();return w;};
const enter=(w:World,stage:number)=>{w.stage=stage;w.stageElapsed=0;w.stageStartedAt=w.time;w.prepareStage();};
const setup=(type:any)=>{const w=make();const u=w.spawnSpecial(type,'boss',{x:0,z:0})!;u.specialReady=0;u.specialDamageMultiplier=1;const a=w.allies()[0];a.x=0;a.z=5;a.hp=a.maxHp=5000;a.armor=0;w.hash.rebuild(w.entities.values());return {w,u,a};};
test('six campaign bosses replace captains without increasing total stage budgets',()=>{
 const expected=[[3,'zergling',30,900],[6,'roach',46.875,4000],[9,'hydralisk',60,9000],[12,'ravager',65.625,18000],[15,'lurker',72,24000],[18,'ultralisk',45,32000]] as const;
 for(const [stage,type,at,hp] of expected){const config=campaign18StageConfig(stage,'normal'),plan=campaign18Schedule(config,1);assert.equal(config.reserves.captain,0);assert.equal(config.reserves.boss,Math.floor(config.budget*.2));assert.equal(plan.specials.length,1);assert.deepEqual([plan.specials[0].type,plan.specials[0].tier,plan.specials[0].at],[type,'boss',at]);assert.equal(Object.entries(plan.accounting).filter(([k])=>k!=='budget').reduce((n,[,v])=>n+v,0),config.budget);const w=make();enter(w,stage);const boss=(w as any).spawnCampaignSpecial(plan.specials[0]);assert.equal(boss.maxHp,hp*.9*campaign18EnemyPressure('normal',stage).health);if(stage===3)assert.equal(boss.weaponDamage,SC2_UNITS.zergling.attackDamage*2);}
});
test('endless includes nine bosses in approved order',()=>{assert.deepEqual(ENDLESS.bossTypes,['queen','lurker','mutalisk','corruptor','ultralisk','zergling','roach','hydralisk','ravager']);});
test('lurker warning locks three lines and hits an overlapping ground target once',()=>{const {w,u,a}=setup('lurker');w.enemySpecials.act(u,1/60);const cast=w.enemySpecials.casts[0];assert.equal(cast.kind,'spikes');assert.equal(cast.at,1.2);assert.equal(cast.count,3);assert.equal(cast.range,14);w.time=1.2;w.enemySpecials.update(1/60);assert.equal(a.hp,4900);});
test('new boss abilities do not target invisible player units',()=>{for(const type of ['lurker','mutalisk','corruptor','ultralisk']){const {w,u,a}=setup(type);a.cloaked=true;w.enemySpecials.act(u,1/60);assert.equal(w.enemySpecials.casts.length,0,type);}});
test('queen heals weakest eligible ally only with no boss or self healing',()=>{const {w,u}=setup('queen');u.hp=1;const other=w.spawnSpecial('zergling','boss',{x:1,z:0})!;other.hp=1;const ally=w.addUnit('roach','zerg',2,0);ally.hp=100;ally.maxHp=2000;w.hash.rebuild(w.entities.values());w.enemySpecials.act(u,1/60);assert.equal(ally.hp,260);assert.equal(u.hp,1);assert.equal(other.hp,1);assert.equal(u.specialReady,8);});
test('corruptor ground acid warns then impacts and ticks four times; pending zones survive save',()=>{const {w,u,a}=setup('corruptor');w.enemySpecials.act(u,1/60);assert.equal(w.enemySpecials.casts[0].kind,'acid');w.time=1.5;w.enemySpecials.update(1/60);assert.equal(a.hp,4910);const copy=make();copy.restoreRun(w.captureRun());for(let i=1;i<=4;i++){copy.time=1.5+i;copy.enemySpecials.update(1/60);}assert.equal(copy.entities.get(a.id)!.hp,4850);});
test('final victory requires an actual saved ultralisk kill receipt',()=>{const w=make();enter(w,18);w.hive!.hp=0;w.stageElapsed=150;w.endStage();assert.equal(w.phase,'lost');const live=make();enter(live,18);const plan=campaign18Schedule(campaign18StageConfig(18,'normal'),1);const boss=(live as any).spawnCampaignSpecial(plan.specials[0]);live.hit(boss,1e9,[],1,'terran');assert.equal(live.campaign18Runtime!.finalBossKilled,true);const copy=make();copy.restoreRun(live.captureRun());assert.equal(copy.campaign18Runtime!.finalBossKilled,true);copy.phase='battle';copy.hive!.hp=0;copy.stageElapsed=150;copy.endStage();assert.equal(copy.phase,'won');});
test('lurker burrow cycle preserves Boss HP and cloak, and exposes during the six-second surface phase',()=>{const {w,u}=setup('lurker');u.specialReady=Infinity;const hp=u.hp;w.updateUnit(u,1/60);w.time=3;w.updateUnit(u,1/60);assert.equal(u.nativeMode,'lurker_burrowed');assert.equal(u.cloaked,true);assert.equal(u.hp,hp);assert.ok(u.weaponDamage>=SC2_UNITS.hydralisk.attackDamage*2);w.time=8;w.updateUnit(u,1/60);w.time=10;w.updateUnit(u,1/60);assert.equal(u.nativeMode,'lurker');assert.equal(u.cloaked,false);w.time=14;w.updateUnit(u,1/60);w.time=17;w.updateUnit(u,1/60);assert.equal(u.nativeMode,'lurker_burrowed');assert.equal(u.hp,hp);});
test('mutalisk fan shares one hit set across its three missiles after save',()=>{const {w,u,a}=setup('mutalisk');a.z=2;a.unitRadius=2;w.hash.rebuild(w.entities.values());w.enemySpecials.act(u,1/60);assert.equal(w.enemySpecials.casts[0].count,3);w.time=1;w.enemySpecials.update(1/60);const copy=make();copy.restoreRun(w.captureRun());assert.equal(copy.enemySpecials.missiles[0].hits,copy.enemySpecials.missiles[1].hits);for(let i=0;i<20;i++)copy.enemySpecials.update(1/60);assert.equal(copy.entities.get(a.id)!.hp,4940);});
test('ultralisk charge hits ground target once and a solid wall stops the charge',()=>{const {w,u,a}=setup('ultralisk');a.z=3;w.hash.rebuild(w.entities.values());w.enemySpecials.act(u,1/60);assert.equal(w.enemySpecials.casts[0].at,1.5);w.time=1.5;w.enemySpecials.update(1/60);for(let i=0;i<60;i++)w.enemySpecials.act(u,1/60);assert.equal(a.hp,4880);assert.ok(Math.abs(u.z-10)<.01);const stopped=setup('ultralisk');stopped.w.enemySpecials.act(stopped.u,1/60);stopped.w.time=1.5;stopped.w.enemySpecials.update(1/60);stopped.w.obstacles.push({x:0,z:4,w:20,h:2} as any);for(let i=0;i<60;i++)stopped.w.enemySpecials.act(stopped.u,1/60);assert.ok(stopped.u.z<4);assert.equal(stopped.a.hp,5000);});
test('ultralisk diagonal charge stops at a wall instead of sliding along it',()=>{const {w,u,a}=setup('ultralisk');a.x=5;a.z=5;w.hash.rebuild(w.entities.values());w.enemySpecials.act(u,1/60);w.time=1.5;w.enemySpecials.update(1/60);w.obstacles.push({x:4,z:0,w:1,h:30});for(let i=0;i<60;i++)w.enemySpecials.act(u,1/60);assert.ok(Math.abs(u.x-u.z)<1e-6);assert.ok(u.x<4);});
test('lurker switches cloak at exactly 8 and 14 seconds using its saved birth clock',()=>{const {w,u}=setup('lurker');u.specialReady=Infinity;w.time=7.99;w.updateUnit(u,1/60);assert.equal(u.cloaked,true);w.time=8;w.updateUnit(u,1/60);assert.equal(u.cloaked,false);w.time=14;w.updateUnit(u,1/60);assert.equal(u.cloaked,true);});
test('campaign Boss difficulty health and weapon pressure are applied once',()=>{for(const difficulty of ['easy','normal','hard','hell'] as const){const w=new World({sandbox:true,terrain:false,obstacles:[],waves:false,difficulty});w.start();enter(w,6);const boss=(w as any).spawnCampaignSpecial(campaign18Schedule(campaign18StageConfig(6,difficulty),1).specials[0]);const pressure=campaign18EnemyPressure(difficulty,6);assert.equal(boss.maxHp,4000*(difficulty==='easy'?.5:.9)*pressure.health);assert.equal(boss.weaponDamage,SC2_UNITS.roach.attackDamage*2*(difficulty==='easy'?1:1.2)*pressure.damage);assert.equal(boss.attackPeriod,SC2_UNITS.roach.attackPeriod/((difficulty==='easy'?1:1.05)*pressure.attackSpeed));}});
test('pending spike warning and cooldown survive save without retargeting',()=>{const {w,u,a}=setup('lurker');w.enemySpecials.act(u,1/60);const copy=make();copy.restoreRun(w.captureRun());assert.equal(copy.entities.get(u.id)!.specialReady,10);assert.deepEqual(copy.enemySpecials.casts,w.enemySpecials.casts);const b=copy.entities.get(a.id)!;b.x=20;copy.hash.rebuild(copy.entities.values());copy.time=1.2;copy.enemySpecials.update(1/60);assert.equal(b.hp,5000);assert.equal(copy.enemySpecials.casts.length,0);});
test('deleting the spawned final Boss does not count as a kill',()=>{const w=make();enter(w,18);const boss=(w as any).spawnCampaignSpecial(campaign18Schedule(campaign18StageConfig(18,'normal'),1).specials[0]);w.entities.delete(boss.id);w.hive!.hp=0;w.stageElapsed=150;w.endStage();assert.equal(w.phase,'lost');assert.equal(w.campaign18Runtime!.finalBossKilled,false);});
test('player G detection reveals the buried Boss and expiry hides it again',()=>{const {w,u}=setup('lurker');assert.equal(w.visibleTo(u,'terran'),false);assert.equal(w.castDetection(),true);assert.equal(w.visibleTo(u,'terran'),true);w.time=14;w.updateUnit(u,1/60);assert.equal(u.cloaked,true);assert.equal(w.visibleTo(u,'terran'),false);});
