import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {createFlameFanGeometry} from '../src/render/effects/terran-flame-fan';

function setup(mode='hellion',rank=1){const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10530});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();for(const c of Object.values(w.expedition.production))c.enabled={};const u=w.addUnit('hellion','terran',0,0,rank);u.eliteId='hellion.2';u.nativeMode=mode;w.refreshStats(u,true);return {w,u};}
function foe(w:World,x:number,z=0,air=false){const e=w.addUnit(air?'mutalisk':'roach','zerg',x,z);e.hp=e.maxHp=100000;e.armor=0;e.shield=0;e.weaponDamage=0;e.stoppedUntil=e.nextShotAt=e.specialReady=1e9;return e;}
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`);

test('knight uses two-thirds of corresponding ordinary reach at I III V in both modes; no doubled range',()=>{for(const mode of ['hellion','hellbat'])for(const rank of [1,3,5]){const {w,u}=setup(mode,rank),expected=(mode==='hellion'?5:2)*2/3,t=foe(w,expected*.7);near(u.attackRange,expected);w.fire(u,t);const f=w.effects.find(f=>f.kind==='flame')!;near(f.radius,expected);near(Math.hypot(f.end.x-f.x,f.end.z-f.z),expected);near(f.x,u.unitRadius);near(f.z,0);assert.ok(t.hp<100000);}});
test('legal primary at actual body-edge reach hits once, but old overlong area does not hurt distant targets',()=>{for(const mode of ['hellion','hellbat']){const {w,u}=setup(mode),r=u.attackRange,t=foe(w,r+u.unitRadius+.3),outside=foe(w,r+u.unitRadius+1.6);t.unitRadius=.4;outside.unitRadius=.1;assert.ok(w.edgeDistance(u,t)<r);w.fire(u,t);near(100000-t.hp,u.weaponDamage);near(outside.hp,100000);}});
test('filled fan hits forward off-axis targets; rear, air and targets beyond 150 degrees stay untouched',()=>{const {w,u}=setup(),t=foe(w,2),origin={x:u.unitRadius,z:0};const polar=(r:number,degrees:number,air=false)=>foe(w,origin.x+Math.cos(degrees*Math.PI/180)*r,Math.sin(degrees*Math.PI/180)*r,air);const left=polar(2,70),right=polar(2,-70),out=polar(2,85),rear=polar(2,180),air=polar(2,0,true);for(const e of [left,right,out,rear,air])e.unitRadius=.1;w.fire(u,t);for(const e of [left,right])assert.ok(e.hp<100000);for(const e of [out,rear,air])near(e.hp,100000);});
test('knight fan respects actual walls rather than treating the filled graphic as extra damage',()=>{const {w,u}=setup(),t=foe(w,2),side=foe(w,2.8,1.6);w.obstacles=[{x:1.5,z:.9,w:.6,h:.7}];w.fire(u,t);assert.ok(t.hp<100000);near(side.hp,100000);});
test('fire origin and radius are frozen through caster movement/mode changes and formal schema21 restore',()=>{const {w,u}=setup(),t=foe(w,2);w.fire(u,t);const frozen=structuredClone(w.effects.find(f=>f.kind==='flame')!);u.x=-3;u.z=2;u.nativeMode='hellbat';w.refreshStats(u);assert.deepEqual(w.effects.find(f=>f.kind==='flame'),frozen);const copy=setup().w;copy.restoreRun(w.captureRun());assert.deepEqual(copy.effects.find(f=>f.kind==='flame'),frozen);near(copy.entities.get(u.id)!.attackRange,2*2/3);});
test('sector triangles cover interior between former streaks without any vertex beyond the saved radius or arc',()=>{const g=createFlameFanGeometry(),p=g.getAttribute('position'),index=g.index!;const points=Array.from({length:p.count},(_,i)=>({x:p.getX(i),z:p.getZ(i)}));for(const q of points){assert.ok(Math.hypot(q.x,q.z)<=1+1e-6);if(Math.hypot(q.x,q.z)>.01)assert.ok(Math.abs(Math.atan2(q.x,q.z))<=75*Math.PI/180+1e-6);}const contains=(q:{x:number;z:number},a:{x:number;z:number},b:{x:number;z:number},c:{x:number;z:number})=>{const area=(b.x-a.x)*(c.z-a.z)-(b.z-a.z)*(c.x-a.x);if(Math.abs(area)<1e-10)return false;const x=((b.x-q.x)*(c.z-q.z)-(b.z-q.z)*(c.x-q.x))/area,y=((c.x-q.x)*(a.z-q.z)-(c.z-q.z)*(a.x-q.x))/area;return x>=-1e-7&&y>=-1e-7&&x+y<=1+1e-7;};for(let a=-73;a<=73;a+=7)for(const r of [.04,.2,.45,.7,.94]){const q={x:Math.sin(a*Math.PI/180)*r,z:Math.cos(a*Math.PI/180)*r};let covered=false;for(let i=0;i<index.count;i+=3)if(contains(q,points[index.getX(i)],points[index.getX(i+1)],points[index.getX(i+2)])){covered=true;break;}assert.ok(covered,`gap at angle ${a}, radius ${r}`);}g.dispose();});
