import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {World} from '../src/simulation/world';
import {HEROES,type HeroId} from '../src/data/heroes';
import {tickHeroAttacks} from '../src/simulation/combat/hero-attack-upgrades';
import {heroState} from '../src/simulation/combat/terran-hero-passives';
import {initializeCarrierSubsystem,ownedInterceptors,refreshInterceptorStats} from '../src/simulation/combat/carriers';
import {refreshGroundHeroBuffs,heroGroundSlow,heroGroundSuppression,heroWeaponVulnerability} from '../src/simulation/combat/hero-ground-auras';
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function setup(hero:HeroId,rank=5){const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10505});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.acquireHero(hero);const u=w.heroEntity(hero)!;u.x=u.z=0;u.rank=rank;w.heroes.get(hero)!.rank=rank;w.refreshStats(u,true);return {w,u};}
function target(w:World,x=3,z=0,air=false){const e=w.addUnit(air?'mutalisk':'roach','zerg',x,z);e.armor=0;e.hp=e.maxHp=1e7;e.moveSpeed=0;e.stoppedUntil=1e9;w.hash.rebuild(w.entities.values());return e;}
function advance(w:World,seconds:number){for(let i=0;i<Math.ceil(seconds*60);i++){w.time+=1/60;tickHeroAttacks(w);}}
for(const rank of [1,3,5])test(`confirmed Raynor rank ${rank}: physical arrival; yellow packets attack different targets for 30%`,()=>{const {w,u}=setup('raynor',rank),a=target(w),b=target(w,3,1),c=target(w,3,-1);w.fire(u,a);assert.equal(a.hp,1e7);const sides=w.heroAttacks.packets.filter(p=>p.kind==='side');assert.equal(sides.length,rank<3?0:rank===3?1:2);assert.ok(sides.every(p=>p.target!==a.id));assert.equal(new Set(sides.map(p=>p.target)).size,sides.length);advance(w,1);near(1e7-a.hp,u.weaponDamage);for(const p of sides)near(1e7-w.entities.get(p.target)!.hp,u.weaponDamage*.3);assert.equal(heroState(u).cycles,1);assert.equal(w.heroAttacks.chains.length,0);});
for(const rank of [3,5])test(`confirmed Nova rank ${rank}: all along-line targets get independent DOT; off-line target excluded`,()=>{const {w,u}=setup('nova',rank),a=target(w),b=target(w,6,0),off=target(w,4,3);w.fire(u,a);advance(w,.6);assert.deepEqual(w.heroAttacks.dots.map(d=>d.target).sort(),[a.id,b.id].sort());assert.equal(off.hp,1e7);const hp=b.hp;advance(w,5);near(hp-b.hp,u.weaponDamage*(rank===3?.2*3:.3*4)*1.4);assert.equal(w.heroAttacks.dots.length,0);assert.equal(heroState(u).cycles,1);});
for(const hero of ['tychus','yamato_battlecruiser'] as const)for(const rank of [3,5])test(`confirmed ${hero} rank ${rank}: fifth cycle missiles use random other targets and frozen full-cycle budget`,()=>{const {w,u}=setup(hero,rank),a=target(w),others=[target(w,3,1),target(w,3,-1),target(w,4,2)];heroState(u).cycles=4;w.fire(u,a);const missiles=w.heroAttacks.packets.filter(p=>p.kind==='missile');assert.equal(missiles.length,rank===3?1:3);assert.ok(missiles.every(p=>p.target!==a.id));assert.equal(new Set(missiles.map(p=>p.target)).size,missiles.length);for(const p of missiles)near(p.damage,u.weaponDamage*HEROES[hero].attacks*1.5);u.rank=1;u.weaponDamage=1;advance(w,2);assert.ok(missiles.every(p=>w.entities.get(p.target)!.hp<1e7));assert.equal(heroState(u).cycles,5);});
for(const rank of [3,5])test(`confirmed Swann rank ${rank}: two physical bounce generations decay 40%, branches share identity receipts`,()=>{const {w,u}=setup('swann',rank),a=target(w);for(let i=0;i<8;i++)target(w,3+(i+1)*.3,(i%2)*.5);w.fire(u,a);advance(w,2);const impacts=w.heroAttackEvents.filter(e=>e.kind==='impact');assert.equal(impacts.filter(e=>e.packet.kind==='bounce').length,rank===3?2:6);assert.equal(new Set(impacts.map(e=>e.packet.target)).size,impacts.length);for(const e of impacts)near(1e7-w.entities.get(e.packet.target)!.hp,u.weaponDamage*.6**e.packet.hop);assert.equal(w.heroAttacks.chains.length,0);});
for(const rank of [3,5])test(`confirmed Tosh rank ${rank}: fireworks correspond to one real splash, no recursive main proc`,()=>{const {w,u}=setup('tosh',rank),a=target(w),b=target(w,3,1),far=target(w,10,0);w.fire(u,a);advance(w,1);near(1e7-b.hp,u.weaponDamage*(rank===3?.35:.6));assert.equal(far.hp,1e7);const event=w.heroAttackEvents.find(e=>e.kind==='splash')!;assert.deepEqual(event.targets,[b.id]);assert.equal(heroState(u).cycles,1);});
test('confirmed Yamato split ground/air missiles retain a single two-gun cycle and one primary receipt',()=>{const {w,u}=setup('yamato_battlecruiser',1),a=target(w),b=target(w,3,1,true);w.fire(u,a);assert.equal(w.heroAttacks.packets.length,2);near(w.heroAttacks.packets.reduce((v,p)=>v+p.damage*p.hits,0),u.weaponDamage*2);assert.equal(w.heroAttacks.packets.filter(p=>p.primary).length,1);assert.deepEqual(w.heroAttacks.packets.map(p=>p.mountSide),['Right','Left']);advance(w,1);near(1e7-a.hp,u.weaponDamage);near(1e7-b.hp,u.weaponDamage);assert.equal(heroState(u).cycles,1);});
test('confirmed flights cannot reacquire a cloak-lost target; committed launched shots survive source death',()=>{const {w,u}=setup('raynor',1),a=target(w);w.fire(u,a);a.cloaked=true;advance(w,.05);a.cloaked=false;advance(w,1);assert.equal(a.hp,1e7);w.fire(u,a);u.hp=0;advance(w,1);assert.ok(a.hp<1e7);});
for(const hero of ['raynor','nova','swann'] as const)test(`schema 17 ${hero}: halfway attacks/DOT/branch receipts reload paused and finish once`,()=>{const {w,u}=setup(hero),a=target(w);for(let i=0;i<7;i++)target(w,4+i*.4,0);w.fire(u,a);advance(w,.05);const snapshot=w.captureRun(),copy=setup(hero).w;copy.restoreRun(snapshot);assert.equal(copy.paused,true);const saved=structuredClone(copy.heroAttacks);copy.step();assert.deepEqual(copy.heroAttacks,saved);advance(w,6);copy.paused=false;advance(copy,6);near(copy.stats.damage,w.stats.damage);assert.deepEqual(copy.heroAttacks,w.heroAttacks);const hp=copy.entities.get(a.id)!.hp;advance(copy,2);near(copy.entities.get(a.id)!.hp,hp);assert.equal(copy.heroAttackEvents.filter(e=>e.kind==='launch'&&e.packet.kind==='main').length,0);});
test('schema 17 rejects corrupt hero packets/branch identities before changing the live World',()=>{const {w,u}=setup('swann'),a=target(w);w.fire(u,a);const snapshot=structuredClone(w.captureRun());snapshot.state.heroAttacks.packets[0].arrival=NaN;const before=structuredClone(w.captureRun());assert.throws(()=>w.restoreRun(snapshot),/确认版英雄攻击/);assert.deepEqual(w.captureRun(),before);const bad=structuredClone(before);bad.state.heroAttacks.chains[0].seen.push(a.id);assert.throws(()=>w.restoreRun(bad),/确认版英雄攻击/);});
test('Raynor foot buff is fixed at all ranks; enters/leaves immediately; HP loss and committed shot clocks persist',()=>{const {w,u}=setup('raynor',1),a=w.addUnit('tank','terran',2,0);refreshGroundHeroBuffs(w);const damage=a.weaponDamage;a.hp-=40;a.weaponCooldown=.27;a.nextShotAt=10;u.x=30;refreshGroundHeroBuffs(w);near(damage/a.weaponDamage,1.35);near(a.maxHp-a.hp,40);near(a.weaponCooldown,.27);near(a.nextShotAt,10);u.x=0;u.rank=5;refreshGroundHeroBuffs(w);near(a.weaponDamage,damage);u.hp=0;refreshGroundHeroBuffs(w);near(damage/a.weaponDamage,1.35);});
test('Swann foot armor stacks once with original +4; excludes temporary bodies; no free HP when leaving',()=>{const {w,u}=setup('swann'),a=w.addUnit('tank','terran',2,0),temporary=w.addUnit('tank','terran',2,1);temporary.temporary=true;w.refreshStats(temporary);refreshGroundHeroBuffs(w);const armor=a.armor,base=temporary.armor;a.hp-=20;assert.ok(armor>=base+10);u.x=30;refreshGroundHeroBuffs(w);near(a.armor,armor-6);near(a.maxHp-a.hp,20);});
test('Yamato foot attack-speed aura stacks additively with Raynor passive and does not reset ongoing cooldown',()=>{const {w,u}=setup('yamato_battlecruiser'),a=w.addUnit('tank','terran',2,0);refreshGroundHeroBuffs(w);const period=a.attackPeriod;a.weaponCooldown=.2;u.x=30;refreshGroundHeroBuffs(w);near(a.attackPeriod/period,1.4);near(a.weaponCooldown,.2);u.x=0;refreshGroundHeroBuffs(w);for(let i=0;i<10;i++)w.refreshStats(a);near(a.attackPeriod,period);});
for(const hero of ['tychus','nova','tosh'] as const)test(`${hero} foot debuff affects real Boss weapon only; leave/death excludes buildings`,()=>{const {w,u}=setup(hero),a=target(w);a.enemyTier='boss';if(hero==='tychus'){near(w.enemyAttackSpeedFactor(a),.65);u.x=30;near(w.enemyAttackSpeedFactor(a),1);}else if(hero==='nova'){near(heroWeaponVulnerability(w,a),1.4);const hp=a.hp;w.hit(a,100,[],1,'terran',0,1,u.id,false,false,0,true);near(hp-a.hp,140);const hp2=a.hp;w.hit(a,100,[],1,'terran',0,1,u.id);near(hp2-a.hp,100);}else{const ally=w.addUnit('tank','terran',0,0);ally.armor=0;const hp=ally.hp;w.attackHit(a,ally,100,[],1);near(hp-ally.hp,65);near(heroGroundSuppression(w,a),.35);}a.attributes.push('Structure');near(heroGroundSlow(w,a),0);near(heroGroundSuppression(w,a),0);near(heroWeaponVulnerability(w,a),1);u.hp=0;near(w.enemyAttackSpeedFactor(a),1);});
test('confirmed shaders, gun geometry, skill geometry and first Swann block match frozen approval source',()=>{
 const frozen='test/fixtures/confirmed-hero-20261005/';
 const read=(file:string)=>fs.readFileSync(file,'utf8').replace(/\r\n/g,'\n');
 const original=(name:string)=>read(frozen+name),production=(name:string)=>read('src/render/effects/confirmed-hero/'+name);
 for(const name of ['approved-gun-effects.ts','upgrade-materials.ts']){const clean=(s:string)=>s.replace(/^import .*$/gm,'').replace(/Preview adapter/g,'Preview adapter');assert.equal(clean(original(name)),clean(production(name)));}
 const a=original('skill-effects.ts'),b=production('skill-effects.ts');for(const start of ['  const geometries:',' private draw(',' private beam(',' private ring(',' private orb(',' private charge(']){const block=(s:string)=>s.slice(s.indexOf(start),s.indexOf('\n',s.indexOf(start)));assert.equal(block(a),block(b));}const swann=(s:string)=>s.slice(s.indexOf("   if(c.hero==='swann'&&age<5)"),s.indexOf('  this.echoes=this.echoes.filter'));assert.equal(swann(a),swann(b));
 const shaders=(s:string)=>[...s.matchAll(/(?:vertexShader|fragmentShader):(?:`([^`]+)`|'([^']+)')/g)].map(m=>m[1]??m[2]);assert.deepEqual(shaders(a),shaders(b));
});
test('owned interceptor inherits aura from permanent mother exactly once, even while child is outside the ring',()=>{const {w,u}=setup('yamato_battlecruiser'),carrier=w.addUnit('carrier','terran',2,0);initializeCarrierSubsystem(w);const child=ownedInterceptors(w,carrier.id)[0];child.x=40;refreshInterceptorStats(w,child);const fast=child.attackPeriod;u.x=30;refreshInterceptorStats(w,child);near(child.attackPeriod/fast,1.4);u.x=0;for(let i=0;i<10;i++)refreshInterceptorStats(w,child);near(child.attackPeriod,fast);assert.ok(w.acquireHero('swann'));const swann=w.heroEntity('swann')!;swann.x=swann.z=0;refreshInterceptorStats(w,child);const armor=child.armor;swann.x=30;refreshInterceptorStats(w,child);near(armor-child.armor,6);});
test('regular non-hero worlds do not gain any new aura-stat refresh or save-time health refill',()=>{const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[]});w.start();w.entities.clear();const a=w.addUnit('marine','terran',0,0);a.hp=a.maxHp=10000;a.weaponCooldown=.4;refreshGroundHeroBuffs(w);assert.equal(a.maxHp,10000);assert.equal(a.weaponCooldown,.4);assert.equal(w.heroAuraMembership.size,0);});
