import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {MapTerrain} from '../src/simulation/movement/map-terrain';import type {MapDefinition} from '../src/data/map-definition';
function fixture():MapDefinition {const width=21,height=21,walkWidth=40,walkHeight=40,N=1600;return {version:1,source:{name:'synthetic traversal fixture',sha256:'fixture',worldUnitsPerSc2Unit:1},width,height,bounds:[0,0,20,20],origin:[0,20,0],start:{x:3,z:14},hive:{x:15,z:14},heights:Array(441).fill(0),syncHeights:Array(441).fill(0),levels:Array(441).fill(1),walkWidth,walkHeight,cellSize:.5,walk:Array.from({length:N},(_,i)=>i%40===16&&Math.floor(i/40)<26?0:1),opening:Array(N).fill(1),reveal:Array(N).fill(1),clearance:Array.from({length:N},(_,i)=>i%40===16&&Math.floor(i/40)<26?0:Math.min(Math.abs(i%40-16)*.5+.25,Math.max(0,Math.floor(i/40)-25)*.5+.25)+1),placements:[],ramps:[],stageAreas:Array.from({length:12},(_,i)=>(i+1)*20)};}
test('map scale is explicit and bilinear original heights have shared world coordinates',()=>{const d=fixture();d.heights=d.heights.map((_,i)=>i%d.width*.1);const t=new MapTerrain(d);assert.ok(Math.abs(t.height({x:3.25,z:14})-.325)<1e-6);assert.throws(()=>new MapTerrain({...d,source:{...d.source,worldUnitsPerSc2Unit:2}}),/scale/);});
test('map routes go around blocked cells and cache without mutating positions',()=>{const d=fixture(),t=new MapTerrain(d),a={...d.start},b=d.hive;assert.equal(t.walkLine(a,b,.2),false);const next=t.routeGoal(a,b,.2,50);assert.ok(Math.hypot(next.x-a.x,next.z-a.z)>1);assert.ok(t.walkLine(a,next,.2));assert.deepEqual(a,d.start);const count=t.routes.size;assert.deepEqual(t.routeGoal(a,b,.2,50),next);assert.equal(t.routes.size,count);});
test('locked sectors exclude complete body radius and expansion only opens cells',()=>{const d=fixture();d.opening=d.opening.map((_,i)=>i%40>=24?2:1);const t=new MapTerrain(d);assert.equal(t.canOccupy({x:13,z:10},.5),false);assert.equal(t.canOccupy({x:11.8,z:10},.5),false);t.setStage(2);assert.equal(t.canOccupy({x:13,z:10},.5),true);assert.equal(t.canOccupy({x:3,z:10},.5),true);});
test('original map dependency list locks content and never substitutes HTML or unknown remote paths',()=>{const lock=JSON.parse(fs.readFileSync('tools/map-lock.json','utf8')),deps=JSON.parse(fs.readFileSync('tools/map-dependencies.json','utf8'));assert.equal(lock.worldUnitsPerSc2Unit,1);assert.match(lock.sha256,/^[0-9a-f]{64}$/);assert.ok(deps.length>400);for(const d of deps){assert.match(d.sha256,/^[0-9a-f]{64}$/);assert.ok(d.bytes>24);assert.match(d.installFile,/^assets\/private\/(m3|dds)\/[^/]+\.(m3|dds)$/);}});

test('anchor paths use their actual .9 radius instead of sealing a valid narrow corridor at 1.0',()=>{
 const d=fixture();d.clearance=d.walk.map(v=>v?1.05:0);const t=new MapTerrain(d),a={...d.start},b=d.hive;
 const next=t.routeGoal(a,b,.9,50);assert.ok(Math.hypot(next.x-a.x,next.z-a.z)>.1);assert.ok(t.walkLine(a,next,.9));
});
