import {terranMedical} from '../src/simulation/combat/terran-elite-runtime';
import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {newEliteSupportState,tickEliteSupport,validateEliteSupport,type LargeMine} from '../src/simulation/combat/elite-support';
import {newSupportMine} from '../src/simulation/combat/tracking-mines';
import {tickShopSupport} from '../src/simulation/combat/shop-support';
import {ELITES,type EliteId} from '../src/data/elites';
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function make(){const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10511});w.start();w.entities.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();for(const c of Object.values(w.expedition.production))c.enabled={};return w;}
function caster(w:World,id:EliteId,rank=1){const u=w.addUnit(ELITES[id].family,'terran',0,0,rank);u.eliteId=id;u.modelKey=ELITES[id].model;w.refreshStats(u,true);u.energy=u.maxEnergy;u.nextShotAt=1e9;return u;}
function foe(w:World,x=1.5,z=0,air=false){const e=w.addUnit(air?'mutalisk':'roach','zerg',x,z);e.hp=e.maxHp=100000;e.armor=0;e.moveSpeed=0;e.nextShotAt=1e9;e.specialReady=1e9;return e;}
function mine(w:World,source:number,rank=1,x=0,z=0):LargeMine{const g=1+.35*(rank-1);return {...newSupportMine(w.nextId++,{x,z}),source,rank,damage:1200*g,fire:180*g};}

test('Elite support uses the sole current elite body; approved I-V medical rates apply once',()=>{for(const rank of [1,2,3,4,5]){const w=make(),u=caster(w,'science_vessel.1',rank),ordinary=w.addUnit('science_vessel','terran',6,0,5),g=1+.35*(rank-1);near(u.healRate,189*g);near(u.maxHp,ordinary.maxHp*2.4*(1+.3*(rank-1)));const unchanged=make();const old=caster(unchanged,'science_vessel.1',rank);assert.equal(old.healRate,u.healRate);} });
test('large mines deploy first at twelve seconds, two at a time with an eight-mine cap and one pending batch',()=>{const w=make(),u=caster(w,'hellion.3');tickEliteSupport(w);assert.equal(w.eliteSupport.mines.length,0);for(const t of [12,24,36,48]){w.time=t;tickEliteSupport(w);}assert.equal(w.eliteSupport.mines.length,8);w.time=60;tickEliteSupport(w);assert.equal(w.eliteSupport.deploy[u.id].pending,2);w.time=300;tickEliteSupport(w);assert.equal(w.eliteSupport.deploy[u.id].pending,2);assert.equal(w.eliteSupport.mines.length,8);});
test('blocked deployment retains rights and source death cancels only undeployed rights',()=>{const w=make(),u=caster(w,'hellion.3');w.obstacles=[{x:0,z:0,w:20,h:20}];w.time=12;tickEliteSupport(w);assert.equal(w.eliteSupport.deploy[u.id].pending,2);assert.equal(w.eliteSupport.mines.length,0);w.obstacles=[];w.time=13;tickEliteSupport(w);assert.equal(w.eliteSupport.mines.length,2);u.hp=0;tickEliteSupport(w);assert.equal(w.eliteSupport.mines.length,2);assert.equal(w.eliteSupport.deploy[u.id],undefined);});
test('I III V large mines have one actual explosion and two actual burn pulses; airborne targets untouched',()=>{for(const rank of [1,3,5]){const w=make(),u=caster(w,'hellion.3',rank),e=foe(w,.5),air=foe(w,.5,0,true);w.eliteSupport.mines=[mine(w,u.id,rank)];tickEliteSupport(w);near(e.hp,100000);w.time=.25;tickEliteSupport(w);near(100000-e.hp,1200*(1+.35*(rank-1)));w.time=1.25;tickEliteSupport(w);w.time=2.25;tickEliteSupport(w);near(100000-e.hp,1560*(1+.35*(rank-1)));near(air.hp,100000);w.time=2.5;tickEliteSupport(w);assert.equal(w.eliteSupport.mines.length,0);assert.equal(w.eliteSupport.fires.length,0);}});
test('same-owner same-tick overlap consumes two explosions but one burn stream',()=>{const w=make(),u=caster(w,'hellion.3'),e=foe(w,.5);w.eliteSupport.mines=[mine(w,u.id),mine(w,u.id,1,.1)];tickEliteSupport(w);for(const t of [.25,1.25,2.25]){w.time=t;tickEliteSupport(w);}near(100000-e.hp,2760);});
test('staggered burns cannot phase-offset stack and strongest simultaneous due packet wins',()=>{const w=make(),u=caster(w,'hellion.3'),e=foe(w,1);w.eliteSupport.fires=[{id:w.nextId++,source:u.id,point:{x:1,z:0},damage:180,next:1,until:2},{id:w.nextId++,source:u.id,point:{x:1,z:0},damage:306,next:1,until:2},{id:w.nextId++,source:u.id,point:{x:1,z:0},damage:180,next:1.5,until:2.5}];for(const t of [1,1.5,2,2.5]){w.time=t;tickEliteSupport(w);}near(100000-e.hp,612);});
test('large mines lose invisible/air targets and cannot explode through a wall',()=>{const w=make(),u=caster(w,'hellion.3'),e=foe(w,2),m=mine(w,u.id);w.eliteSupport.mines=[m];tickEliteSupport(w);assert.equal(m.targetId,e.id);e.cloaked=true;w.time=.25;tickEliteSupport(w);assert.equal(m.targetId,null);e.cloaked=false;w.obstacles=[{x:1,z:0,w:.4,h:200}];for(let i=0;i<60;i++){w.time+=1/60;tickEliteSupport(w);}near(e.hp,100000);assert.ok(m.point.x<.8);});
test('medical cap, actual gain, energy cost and biological/mechanical one-third ratio',()=>{for(const id of ['medivac.2','science_vessel.1'] as const){const w=make(),u=caster(w,id);const mech=id==='science_vessel.1';for(let i=0;i<7;i++){const p=w.addUnit(mech?(i<4?'tank':'hellion'):(i<4?'marauder':'marine'),'terran',2+i*.1,0,5);p.hp=1;}const before=u.energy;const patients=[...w.entities.values()].filter(p=>p.id!==u.id).reduce((a,p)=>a+p.hp,0);terranMedical(w,u,.1);assert.equal(u.healTargets!.length,mech?3:5);near(w.stats.healed,189*.1*(mech?3:5));near(before-u.energy,w.stats.healed*.33);near([...w.entities.values()].filter(p=>p.id!==u.id).reduce((a,p)=>a+p.hp,0)-patients,w.stats.healed);const cross=make(),c=caster(cross,id),p=cross.addUnit(mech?'marauder':'tank','terran',2,0,5);p.hp=1;terranMedical(cross,c,.1);near(cross.stats.healed,6.3);}});
test('empty/full/out-of-range medical targets do not consume energy or gain barriers; tiny energy is conserved',()=>{const w=make(),u=caster(w,'science_vessel.1'),p=w.addUnit('tank','terran',2,0,5);const before=u.energy;terranMedical(w,u,1);near(u.energy,before);assert.equal(w.eliteSupport.barriers.length,0);p.hp=1;u.energy=0;terranMedical(w,u,1);near(p.hp,1);u.energy=.33;terranMedical(w,u,1);near(p.hp,2);near(u.energy,0);near(w.eliteSupport.barriers[0].amount,1.5);p.x=100;u.energy=1;terranMedical(w,u,1);near(u.energy,1);});
test('repair matrix absorbs real hostile damage before HP; persists source death and expires after seven seconds',()=>{const w=make(),u=caster(w,'science_vessel.1'),p=w.addUnit('tank','terran',2,0,5);p.hp=1;p.armor=0;terranMedical(w,u,.5);const hp=p.hp,b=w.eliteSupport.barriers[0];near(b.amount,141.75);w.hit(p,40,[],1,'zerg',0);near(p.hp,hp);near(b.amount,101.75);u.hp=0;w.time=6;tickEliteSupport(w);assert.equal(w.eliteSupport.barriers.length,1);w.time=7;tickEliteSupport(w);assert.equal(w.eliteSupport.barriers.length,0);w.hit(p,20,[],1,'zerg',0);near(p.hp,hp-20);});
test('pause stops deployment; existing fun mines retain 120 damage and their smaller tracking rules',()=>{const w=make(),u=caster(w,'hellion.3');w.paused=true;w.time=12;tickEliteSupport(w);assert.equal(w.eliteSupport.mines.length,0);w.paused=false;w.expedition.support.stageReceipt=`${w.runId}:${w.stage}`;w.expedition.support.mines=[newSupportMine(w.nextId++,{x:10,z:0})];const e=foe(w,10.5);tickShopSupport(w);w.time+=.25;tickShopSupport(w);near(100000-e.hp,120);assert.equal(w.eliteSupport.mines.length,0);});
test('current support DTO resumes paused with exact mines/rights/barriers; malformed states reject before mutation',()=>{const w=make(),u=caster(w,'hellion.3');w.time=12;tickEliteSupport(w);const saved=w.captureRun(),copy=make();copy.restoreRun(saved);assert.equal(copy.paused,true);assert.deepEqual(copy.eliteSupport,w.eliteSupport);const stable=copy.captureRun();for(const change of [(s:any)=>s.mines[0].damage=Infinity,(s:any)=>s.mines.push({...s.mines[0]}),(s:any)=>s.deploy[u.id].pending=3,(s:any)=>s.fireGate['bad']=1]){const bad=structuredClone(saved);change(bad.state.eliteSupport);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}assert.doesNotThrow(()=>validateEliteSupport({...newEliteSupportState(),mines:[mine(w,u.id)]}));});
