import {initializeCarrierSubsystem,ownedInterceptors} from '../src/simulation/combat/carriers';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {World} from '../src/simulation/world';
import {ELITES} from '../src/data/elites';
import {TERRAN_ELITE_IDS,TERRAN_ELITE_RULES,TERRAN_ELITE_BODIES,type TerranEliteId} from '../src/data/terran-elites';
import {SIEGE} from '../src/data/sc2-units';
import {tickAutoAbilities,unitData,healExpedition,tickNativeMode,selectWeapon,expeditionWeaponBonuses} from '../src/simulation/combat/expedition-combat';
import {eliteDebuffValue,eliteFriendlyAura,eliteCombat,eliteMainFactor,eliteStatModifiers,eliteAfterHit,eliteModeCompleted,tickTerranElite,tickTerranEliteState,terranMedical,absorbReaper,absorbCurrentReapers,eliteDefenseReduction} from '../src/simulation/combat/terran-elite-runtime';
import {tickWeaponFlights} from '../src/simulation/combat/weapon-flight';
import {familyModeState} from '../src/simulation/combat/family-actions';
import {releasePaidPassenger,retireFamily} from '../src/simulation/expedition-production';
import {tickP4Samples} from '../src/simulation/combat/p4-samples';
import {settleWeaponFlights} from './helpers/weapon-flight';
import type {Entity} from '../src/simulation/types';
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
export function fixture(){const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10530});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();for(const c of Object.values(w.expedition.production))c.enabled={};return w;}
export function elite(w:World,id:TerranEliteId,rank=1){const u=w.addUnit(ELITES[id].family,'terran',0,0,rank);u.eliteId=id;u.modelKey=ELITES[id].model;w.refreshStats(u,true);return u;}
export function enemy(w:World,x=5,z=0,air=false){const u=w.addUnit(air?'mutalisk':'roach','zerg',x,z);u.hp=u.maxHp=1e8;u.armor=0;u.shield=0;u.weaponDamage=0;u.stoppedUntil=u.nextShotAt=u.specialReady=1e9;return u;}
function shoot(w:World,u:Entity,t:Entity){selectWeapon(w,u,t);w.refreshStats(u);w.hash.rebuild(w.entities.values());w.fire(u,t);settleWeaponFlights(w);}

test('P4 runtime rules exactly cover the thirty approved Terran entries without importing proposal JSON',()=>{
 const spec=JSON.parse(fs.readFileSync('docs/project/NEXT_ITERATION_P4_VALUES_20261005.json','utf8')).approved.elites.filter((r:any)=>TERRAN_ELITE_IDS.includes(r.id));
 assert.equal(spec.length,30);for(const row of spec){assert.deepEqual(TERRAN_ELITE_RULES[row.id as TerranEliteId].parameters,row.parameters);assert.equal(TERRAN_ELITE_RULES[row.id as TerranEliteId].name,row.name);}
 assert.ok(!fs.readFileSync('src/data/terran-elites.ts','utf8').includes('NEXT_ITERATION_P'));
});
for(const id of TERRAN_ELITE_IDS)test(`P4 ${id}: all five ranks use the approved ordinary-V body, preserve wounds and clocks`,()=>{
 for(let rank=1;rank<=5;rank++){const w=fixture(),u=w.addUnit(ELITES[id].family,'terran',0,0,5);if(id.startsWith('tank.'))u.mode='siege';w.refreshStats(u,true);const base={hp:u.maxHp,damage:u.weaponDamage,period:u.attackPeriod,move:u.moveSpeed,heal:u.healRate,armor:u.armor};u.rank=rank;u.eliteId=id;const body=TERRAN_ELITE_BODIES[TERRAN_ELITE_RULES[id].body],family=id==='marine.3'?1.2:1,hpAura=id==='medivac.1'?1.35:1,phase=id==='tank.2'?2:1;
 w.refreshStats(u,true);near(u.maxHp,base.hp*body.hp*(1+.3*(rank-1))*family*hpAura);near(u.weaponDamage,base.damage*body.dps*(1+.35*(rank-1))*family*phase);near(u.attackPeriod,base.period/family/phase);near(u.healRate,base.heal*body.heal*(1+.35*(rank-1)));near(u.armor,(base.armor+body.armor+.5*(rank-1)+(id==='thor.1'?4:id==='medivac.1'?5:0))*family);
 u.hp-=37;u.nextShotAt=49;eliteCombat(u).ready=62;const before={hp:u.hp,shield:u.shield,energy:u.energy};for(let n=0;n<6;n++)w.refreshStats(u);near(u.hp,before.hp);near(u.energy,before.energy);assert.equal(u.nextShotAt,49);assert.equal(eliteCombat(u).ready,62);assert.equal(w.weaponFlights.length,0);
 }
});
test('metal storm warms for five seconds, runs ten, enforces two seconds of cooling through save and restart',()=>{
 const w=fixture(),u=elite(w,'marine.1'),t=enemy(w);shoot(w,u,t);const s=eliteCombat(u),start=s.started!;w.time=start+2.5;near(eliteStatModifiers(w,u).speed,2.5);w.time=start+5;near(eliteStatModifiers(w,u).speed,4);s.lastFire=start+14.9;w.time=start+15;tickTerranElite(w,u,1/60);assert.equal(s.started,null);const shots=w.stats.shots;w.fire(u,t);assert.equal(w.stats.shots,shots);
 const copy=fixture();copy.restoreRun(w.captureRun());copy.paused=false;const v=copy.entities.get(u.id)!;copy.time=start+16.99;copy.fire(v,copy.entities.get(t.id)!);assert.equal(copy.stats.shots,shots);copy.time=start+17;copy.fire(v,copy.entities.get(t.id)!);assert.equal(copy.stats.shots,shots+1);near(eliteStatModifiers(copy,v).speed,1);
});
test('metal storm target switch preserves heat, two seconds out of combat clears it',()=>{const w=fixture(),u=elite(w,'marine.1'),a=enemy(w),b=enemy(w,5,2);shoot(w,u,a);w.time=3;eliteCombat(u).lastFire=2.9;shoot(w,u,b);near(eliteCombat(u).started!,0);w.time=7;shoot(w,u,a);assert.ok(eliteCombat(u).started!>=7);});
test('elite killer uses exclusive identity factors and only dodges direct enemy weapon damage',()=>{
 const w=fixture(),u=elite(w,'marine.2'),t=enemy(w);assert.equal(eliteMainFactor(u,t),1);t.enemyTier='elite';assert.equal(eliteMainFactor(u,t),3);t.enemyTier='boss';assert.equal(eliteMainFactor(u,t),5);w.random=()=>0;const before=u.hp;w.hit(u,100,[],1,'zerg',0,1,t.id,false,false,0,true);near(u.hp,before);w.hit(u,100,[],1,'zerg',0,1,t.id);near(u.hp,before-100);
});
test('commander buffs ordinary and elite Marines once; unrelated families and heroes stay excluded',()=>{const w=fixture(),u=elite(w,'marine.3'),a=w.addUnit('marine','terran',20,0),b=w.addUnit('marauder','terran',20,1);const damage=a.weaponDamage;w.refreshStats(a);near(a.weaponDamage,damage);near(u.maxHp,45*4.2*3*1.15*1.2);const before=b.weaponDamage;w.refreshStats(b);near(b.weaponDamage,before);});
test('concussion contact applies independent outgoing/attack/move debuffs with half Boss control and expiry',()=>{
 const w=fixture(),u=elite(w,'marauder.1'),t=enemy(w),n=enemy(w,6,0);n.enemyTier='boss';shoot(w,u,t);const a=w.terranElites.debuffs.find(d=>d.target===t.id)!,b=w.terranElites.debuffs.find(d=>d.target===n.id)!;near(a.speed,.35);near(a.move,.45);near(a.damage,.3);near(b.speed,.175);near(b.damage,.15);const soldier=w.addUnit('marine','terran',8,0);soldier.armor=0;soldier.hp=soldier.maxHp=1000;w.hit(soldier,100,[],1,'zerg',0,0,t.id,false,false,0,true);near(soldier.maxHp-soldier.hp,70);w.time=a.until;tickTerranEliteState(w);assert.equal(w.terranElites.debuffs.length,0);
});
test('armor breaker reduces positive life and native-shield armor without making it negative',()=>{const w=fixture(),u=elite(w,'marauder.2',5),t=enemy(w);t.armor=10;t.shield=10000;t.shieldArmor=10;shoot(w,u,t);const before=t.shield!;w.hit(t,100,[],1,'terran',0);near(before-t.shield!,96);t.shield=0;const hp=t.hp;w.hit(t,100,[],1,'terran',0);near(hp-t.hp,96);t.armor=-2;const h=t.hp;w.hit(t,100,[],1,'terran',0);near(h-t.hp,100);});
test('refuser launches three individually delayed original grenades, preserves payloads during save, splashes once each',()=>{const w=fixture(),u=elite(w,'marauder.3'),t=enemy(w),n=enemy(w,6,0);t.attributes=n.attributes=[];w.random=()=>1;w.fire(u,t);assert.equal(w.weaponFlights.length,3);assert.equal(new Set(w.weaponFlights.map(p=>p.attackId)).size,1);assert.equal(w.weaponFlights.filter(p=>p.primary).length,1);const copy=fixture();copy.restoreRun(w.captureRun());assert.deepEqual(copy.weaponFlights,w.weaponFlights);settleWeaponFlights(copy);near(1e8-copy.entities.get(t.id)!.hp,u.weaponDamage*1.95);near(1e8-copy.entities.get(n.id)!.hp,u.weaponDamage*1.95);});
test('refuser knockback stops at walls/bodies and Bosses receive slow without displacement',()=>{const w=fixture(),u=elite(w,'marauder.3'),t=enemy(w,2);w.random=()=>0;w.obstacles=[{x:4,z:0,w:.2,h:4}];eliteAfterHit(w,u,t,0,1,true);assert.ok(t.x<=4-.1-t.unitRadius+1e-8);const x=t.x;eliteAfterHit(w,u,t,0,1,true);near(t.x,x);w.time=2;t.enemyTier='boss';eliteAfterHit(w,u,t,0,1,true);near(t.x,x);assert.equal(w.terranElites.debuffs[0].move,.2);});
test('midnight Reaper fires exactly six ground packets; delayed shots do not move before launch and cannot hit air',()=>{const w=fixture(),u=elite(w,'reaper.1'),t=enemy(w),a=enemy(w,4,1,true);w.fire(u,a);assert.equal(w.weaponFlights.length,0);w.fire(u,t);assert.equal(w.weaponFlights.length,6);tickWeaponFlights(w,1/60);near(w.weaponFlights[5].point.x,0);settleWeaponFlights(w);near(1e8-t.hp,u.weaponDamage*6);near(a.hp,1e8);assert.equal(eliteCombat(u).cycles,1);});
test('big barrel opening counts ten cycles, scales both guns/bonuses and excludes primary from its splash',()=>{const w=fixture(),u=elite(w,'reaper.2'),t=enemy(w),n=enemy(w,6,0);const packets=[];for(let i=0;i<11;i++){w.time=i*.8;w.fire(u,t);packets.push(w.weaponFlights.at(-1)!.damage);settleWeaponFlights(w);}near(packets[0],u.weaponDamage*3);near(packets[9],u.weaponDamage*3);near(packets[10],u.weaponDamage);near(1e8-t.hp,u.weaponDamage*31*2*1.5);near(1e8-n.hp,u.weaponDamage*31*2*1.5*.5);w.time=13;w.fire(u,t);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*3);});
test('lone hunter absorbs only real Reapers, retires consumed identity once and preserves other heroes/families',()=>{const w=fixture(),h=elite(w,'reaper.3'),a=elite(w,'reaper.1',5),b=w.addUnit('reaper','terran',2,1,3),other=w.addUnit('marine','terran',2,2);const hp=h.hp;absorbCurrentReapers(w,h);assert.equal(w.familyUnits('reaper').length,1);assert.ok(w.entities.has(other.id));assert.ok(h.hp>hp);const n=eliteCombat(h).absorbed;assert.ok(n>3);assert.equal(absorbReaper(w,h,b),false);assert.equal(w.canAcquireElite('reaper.1'),false);near(eliteStatModifiers(w,h).damage,1+3*n/(n+20));near(eliteStatModifiers(w,h).hp,1+4*n/(n+20));assert.ok(eliteStatModifiers(w,h).damage<4);});
test('paid Reaper delivery is consumed exactly once; original paid receipt survives restore and hunter death releases later orders',()=>{const w=fixture(),h=elite(w,'reaper.3');w.expedition.familySlots=['reaper'];const p=w.spawnPod('reaper',{x:5,z:0},103,1);w.expedition.ledger.push({id:103,family:'reaper',line:'barracks',facilityIds:[],remaining:0,state:'risk',podId:p.id,passengers:[{paid:{minerals:50,gas:50},status:'waiting',entityId:null,purpose:'body'}]});assert.equal(releasePaidPassenger(w,p,0,{x:5,z:1})!.id,h.id);assert.equal(releasePaidPassenger(w,p,0,{x:5,z:1}),null);const r=w.terranElites.absorptions[0];assert.deepEqual(r.paid,{minerals:50,gas:50});assert.equal(r.job,103);assert.equal(r.id,p.passengers[0].entityId);const copy=fixture();copy.restoreRun(w.captureRun());assert.deepEqual(copy.terranElites.absorptions,w.terranElites.absorptions);h.hp=0;const q=w.spawnPod('reaper',{x:6,z:0},104,1);w.expedition.ledger.push({id:104,family:'reaper',line:'barracks',facilityIds:[],remaining:0,state:'risk',podId:q.id,passengers:[{paid:{minerals:51,gas:50},status:'waiting',entityId:null,purpose:'body'}]});const survivor=releasePaidPassenger(w,q,0,{x:6,z:1})!;assert.ok(w.entities.has(survivor.id));assert.notEqual(survivor.id,h.id);});
test('long flame is a narrow fourfold channel; knight is a forward 150-degree fan with unchanged width semantics',()=>{for(const id of ['hellion.1','hellion.2'] as const){const w=fixture(),u=elite(w,id),a=enemy(w,10,0),side=enemy(w,5,4),rear=enemy(w,-2,0),air=enemy(w,3,0,true);a.attributes=['Light'];w.fire(u,a);assert.ok(a.hp<1e8);assert.equal(side.hp<1e8,id==='hellion.2');near(rear.hp,1e8);near(air.hp,1e8);assert.equal(w.effects.filter(e=>e.kind==='flame').length,1);}});
test('formal mine layer deploys twelve-second two-mine batches with the old opt-in flag disabled',()=>{const w=fixture(),u=elite(w,'hellion.3');assert.equal(w.p4Samples.enabled,false);w.time=12;tickP4Samples(w);assert.equal(w.p4Samples.mines.length,2);assert.equal(w.p4Samples.mines[0].damage,1200);assert.equal(w.p4Samples.deploy[u.id].next,24);});
test('leopard stone keeps the siege weapon while moving and removes only its own siege toggle',()=>{const w=fixture(),u=elite(w,'tank.1'),t=enemy(w,6);u.velocity={x:1,z:0};assert.equal(unitData(u).attackRange,SIEGE.range);assert.equal(familyModeState(w,'tank').enabled,false);shoot(w,u,t);assert.ok(t.hp<1e8);w.addUnit('tank','terran',-3,0);assert.equal(familyModeState(w,'tank').enabled,true);near(u.attackRange,SIEGE.range);});
test('Tiger fires only after completed stationary siege and doubles damage/speed with threefold range and scaled bonuses',()=>{const w=fixture(),u=elite(w,'tank.2'),t=enemy(w,8);w.fire(u,t);near(t.hp,1e8);assert.equal(w.weaponFlights.length,0);u.mode='siege';w.refreshStats(u);const bonus=expeditionWeaponBonuses(w,u).bonuses[0].amount;near(u.attackRange,SIEGE.range*3);near(bonus,SIEGE.bonus[0].amount*w.growth(u).damage*1.15*2);u.velocity={x:1,z:0};w.fire(u,t);assert.equal(w.weaponFlights.length,0);u.velocity={x:0,z:0};shoot(w,u,t);assert.ok(t.hp<1e8);});
test('Destroyer scales all native blast bands by sqrt(5), retains band damage and emits one fifty-percent fire pulse',()=>{const w=fixture(),u=elite(w,'tank.3'),t=enemy(w,8),edge=enemy(w,8+SIEGE.splash.at(-1)!.radius*2,0),air=enemy(w,8,0,true);u.mode='siege';w.refreshStats(u);shoot(w,u,t);assert.ok(edge.hp<1e8);near(air.hp,1e8);const a=w.terranElites.areas[0];near(a.radius,Math.max(...SIEGE.splash.map(s=>s.radius))*Math.sqrt(5));near(a.damage,u.weaponDamage*.5);const hp=t.hp;w.time=a.next;tickTerranEliteState(w);assert.ok(t.hp<hp);assert.equal(w.terranElites.areas.length,0);});
test('Destroyer overlapping and offset fire patches share a one-second source/target gate',()=>{const w=fixture(),u=elite(w,'tank.3'),t=enemy(w,5);for(const [next,damage]of [[1,100],[1,200],[1.5,100],[2,150]])w.terranElites.areas.push({id:w.nextId++,source:structuredClone(u),point:{x:5,z:0},radius:3,damage,next,until:next,kind:'fire',target:null});for(const time of [1,1.5,2]){w.time=time;tickTerranEliteState(w);}near(1e8-t.hp,350);});
test('Thunder quake counts only ground cycles, damages only ground and grants a separate mechanical armor aura',()=>{const w=fixture(),u=elite(w,'thor.1'),t=enemy(w),a=enemy(w,5,1,true),base=u.weaponDamage;shoot(w,u,t);shoot(w,u,a);shoot(w,u,t);const hp=t.hp;shoot(w,u,t);assert.ok(hp-t.hp>base*2);assert.equal(eliteCombat(u).groundCycles,3);assert.equal(eliteCombat(u).airCycles,1);assert.ok(w.terranElites.debuffs.some(d=>d.target===t.id&&d.move===.4));assert.ok(!w.terranElites.debuffs.some(d=>d.target===a.id));});
test('Heaven artillery applies armored-air factor only in the air, resets lock on switching and splashes legal air neighbors',()=>{const w=fixture(),u=elite(w,'thor.2'),a=enemy(w,5,0,true),n=enemy(w,6,0,true),g=enemy(w,5,1);a.attributes=n.attributes=['Armored'];assert.equal(eliteMainFactor(u,g),1);assert.equal(eliteMainFactor(u,a),3);shoot(w,u,a);w.time=3.5;w.refreshStats(u);near(eliteStatModifiers(w,u).speed,2);shoot(w,u,n);near(eliteStatModifiers(w,u).speed,1);near(g.hp,1e8);assert.ok(n.hp<1e8);});
test('Doom overdrive is one threefold DPS multiplier across charge/overdrive/cooling; switching preserves cycle',()=>{const w=fixture(),u=elite(w,'thor.3'),t=enemy(w);shoot(w,u,t);const s=eliteCombat(u),start=s.started!;for(const [elapsed,factor]of [[3.99,1],[4,3],[11.99,3],[12,1],[15.99,1],[16,1]]){w.time=start+elapsed;near(eliteStatModifiers(w,u).damage,factor);}s.lastFire=w.time-.1;const n=enemy(w,6,0);shoot(w,u,n);near(s.started!,start);});
test('Sky hawk launches a real opening pair, stacks five real air cycles and clears on retarget',()=>{const w=fixture(),u=elite(w,'viking.1'),a=enemy(w,5,0,true),b=enemy(w,5,2,true);w.fire(u,a);assert.equal(w.weaponFlights.length,3);near(w.weaponFlights.slice(0,2).reduce((n,p)=>n+p.damage*p.hits,0),u.weaponDamage*1.5);settleWeaponFlights(w);for(let i=1;i<=5;i++){w.time=i*.7;w.fire(u,a);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*(1+.35*Math.min(i,5)));settleWeaponFlights(w);}w.fire(u,b);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage);assert.equal(eliteCombat(u).stacks,1);});
test('landing hammer waits behind collision and triggers exactly once after the original native transition completes',()=>{const w=fixture(),u=elite(w,'viking.2'),t=enemy(w,3);u.desiredNativeMode='viking_assault';tickNativeMode(w,u);const until=u.nativeModeUntil!;w.obstacles=[{x:0,z:0,w:2,h:2}];w.time=until;tickNativeMode(w,u);near(t.hp,1e8);assert.equal(u.nativeMode??u.unitType,'viking');w.obstacles=[];tickNativeMode(w,u);near(1e8-t.hp,1600);near(eliteStatModifiers(w,u).damage,2);near(eliteStatModifiers(w,u).armor,12);tickNativeMode(w,u);near(1e8-t.hp,1600);});
test('dual ace consumes exactly ten empowered cycles; shared transition cooldown prevents shield refills',()=>{const w=fixture(),u=elite(w,'viking.3'),t=enemy(w,4);u.nativeMode='viking_assault';w.refreshStats(u);eliteModeCompleted(w,u,'viking');const s=eliteCombat(u),barrier=s.barrier;assert.equal(s.boosted,10);for(let i=0;i<10;i++){w.time=i*.6;w.refreshStats(u);near(eliteStatModifiers(w,u).damage,2.5);shoot(w,u,t);}assert.equal(s.boosted,0);near(eliteStatModifiers(w,u).damage,1);s.barrier=0;u.nativeMode='viking';eliteModeCompleted(w,u,'viking_assault');assert.equal(s.barrier,0);assert.ok(barrier>0);});
test('banshee mourner reduces positive armor and existing percentage defense relatively without piercing immunity',()=>{const w=fixture(),u=elite(w,'banshee.1'),t=enemy(w);t.damageReduction=.4;t.armor=10;near(eliteDefenseReduction(w,t),.3);const hp=t.hp;w.hit(t,100,[],1,'terran',0);near(hp-t.hp,64);u.hp=0;near(eliteDefenseReduction(w,t),.4);});
test('plague snapshots max HP on entry, pulses only enemy bodies and applies ordinary/elite/Boss fractions',()=>{for(const [tier,factor]of [[undefined,1],['elite',.5],['boss',.2]] as const){const w=fixture(),u=elite(w,'banshee.2',5),t=enemy(w);t.enemyTier=tier;t.maxHp=10000;tickTerranEliteState(w);t.maxHp=20000;w.time=1;tickTerranEliteState(w);near(1e8-t.hp,500*factor);t.x=20;tickTerranEliteState(w);assert.deepEqual(w.terranElites.plague,{});}});
test('uplifting Banshee stores one bounded charge out of combat and consumes it once entering combat',()=>{const w=fixture(),u=elite(w,'banshee.3'),t=enemy(w);w.time=3;for(let i=0;i<600;i++)tickTerranElite(w,u,1/60);near(eliteCombat(u).charge,2600);w.fire(u,t);near(1e8-t.hp,2600);assert.equal(eliteCombat(u).charge,0);settleWeaponFlights(w);const hp=t.hp;w.fire(u,t);near(t.hp,hp);});
test('medical commander aura keeps wound proportion on entry/exit, does not accumulate or regenerate',()=>{const w=fixture(),p=w.addUnit('marauder','terran',3,0),hp=p.maxHp;p.hp=hp*.4;const u=elite(w,'medivac.1');w.refreshStats(p);near(p.maxHp,hp*1.35);near(p.hp/p.maxHp,.4);u.x=40;w.refreshStats(p);near(p.maxHp,hp);near(p.hp,hp*.4);});
for(const [id,cap,primary]of [['medivac.1',1,'marauder'],['medivac.2',5,'marauder'],['medivac.3',1,'marauder'],['science_vessel.1',3,'tank'],['science_vessel.2',2,'tank'],['science_vessel.3',3,'tank']] as const)test(`P4 ${id}: actual missing HP, target cap ${cap}, energy and crossed recipient type`,()=>{const w=fixture(),u=elite(w,id);for(let i=0;i<7;i++){const p=w.addUnit(primary,'terran',2+i*.2,0,5);p.hp=1;p.lastShotAt=w.time;}const energy=u.energy;healExpedition(w,u,.1);assert.equal(u.healTargets?.length,cap);near(w.stats.healed,u.healRate*.1*cap);near(energy-u.energy,w.stats.healed*.33);const c=fixture(),v=elite(c,id),p=c.addUnit(primary==='tank'?'marauder':'tank','terran',2,0,5);p.hp=1;terranMedical(c,v,.1);near(c.stats.healed,v.healRate*.1/3);});
test('glimmer produces finite shields only from effective healing a recently fighting/damaged recipient, then expires',()=>{const w=fixture(),u=elite(w,'medivac.3'),p=w.addUnit('marauder','terran',2,0,5);p.hp=1;terranMedical(w,u,.1);assert.equal(w.p4Samples.barriers.length,0);p.lastShotAt=0;terranMedical(w,u,.1);near(w.p4Samples.barriers[0].amount,22.68);p.hp=p.maxHp;const before=w.p4Samples.barriers[0].amount;terranMedical(w,u,1);near(w.p4Samples.barriers[0].amount,before);w.time=6;tickP4Samples(w);assert.equal(w.p4Samples.barriers.length,0);});
test('radiation follows its biological enemy host, excludes mechanical/friendly recipients and stops on host death',()=>{const w=fixture(),u=elite(w,'science_vessel.2'),t=enemy(w),m=enemy(w,5,1);m.attributes=['Mechanical'];const friend=w.addUnit('marine','terran',5,1);tickTerranElite(w,u,1/60);assert.equal(w.terranElites.areas.length,1);const host=w.terranElites.areas[0].target!;t.x=7;w.time=1;tickTerranEliteState(w);near(1e8-t.hp,380);near(m.hp,1e8);near(friend.hp,friend.maxHp);w.entities.get(host)!.hp=0;w.time=2;tickTerranEliteState(w);assert.equal(w.terranElites.areas.length,0);});
test('EMP uses formal finite-barrier/native-shield pipeline, discards overflow, drains energy and halves Boss attack slow',()=>{const w=fixture(),u=elite(w,'science_vessel.3'),t=enemy(w);t.shield=1000;t.shieldArmor=0;t.energy=100;t.enemyTier='boss';t.barrier=500;tickTerranElite(w,u,1/60);near(t.shield!,0);near(t.barrier!,0);near(t.hp,1e8);near(t.energy,40);near(w.enemyAttackSpeedFactor(t),.85);const noShield=enemy(w,6);noShield.energy=0;w.time=14;tickTerranElite(w,u,1/60);near(noShield.hp,1e8);near(noShield.energy,0);});
test('schema21 atomically persists flights, counters, areas, fire gates, receipts, barriers and refuses malformed DTOs',()=>{const w=fixture(),u=elite(w,'marauder.3'),t=enemy(w);w.fire(u,t);const save=w.captureRun();assert.equal(save.schema,23);const copy=fixture();copy.restoreRun(save);assert.equal(copy.paused,true);assert.deepEqual(copy.weaponFlights,w.weaponFlights);assert.deepEqual(copy.terranElites,w.terranElites);const stable=copy.captureRun();for(const change of [(s:any)=>s.entities.get(u.id).eliteCombat.cycles=-1,(s:any)=>s.entities.get(u.id).eliteCombat.boosted=11,(s:any)=>s.terranElites.fireGate.bad=1,(s:any)=>s.terranElites.debuffs.push({source:u.id,target:t.id,until:1,armor:2,speed:0,move:0,damage:0})]){const bad=structuredClone(save);change(bad.state);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}});


test('schema21 refuses replayed absorption growth, wrong original payment and retained absorbed bodies atomically',()=>{
 const w=fixture(),h=elite(w,'reaper.3'),p=w.spawnPod('reaper',{x:5,z:0},103,1);w.expedition.ledger.push({id:103,family:'reaper',line:'barracks',facilityIds:[],remaining:0,state:'risk',podId:p.id,passengers:[{paid:{minerals:50,gas:50},status:'waiting',entityId:null,purpose:'body'}]});releasePaidPassenger(w,p,0,{x:5,z:1});const save=w.captureRun(),copy=fixture();copy.restoreRun(save);const stable=copy.captureRun();
 for(const change of [(s:any)=>s.entities.get(h.id).eliteCombat.absorbed+=1,(s:any)=>s.terranElites.absorptions[0].contribution+=1,(s:any)=>s.terranElites.absorptions[0].paid.gas+=1,(s:any)=>s.entities.set(s.terranElites.absorptions[0].id,{...s.entities.get(h.id),id:s.terranElites.absorptions[0].id,eliteId:null,eliteCombat:undefined})]){const bad=structuredClone(save);change(bad.state);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}
});
test('schema21 validates finite area bonuses, frozen launch counters and future identity bounds',()=>{
 const w=fixture(),u=elite(w,'tank.3'),t=enemy(w,8);u.mode='siege';w.refreshStats(u);shoot(w,u,t);w.fire(u,t);const save=w.captureRun(),copy=fixture();copy.restoreRun(save);const stable=copy.captureRun();
 for(const change of [(s:any)=>s.terranElites.areas[0].bonuses=[{attribute:'Light',amount:NaN}],(s:any)=>s.weaponFlights[0].source.eliteCombat.boosted=11,(s:any)=>s.nextId=s.weaponFlights[0].id,(s:any)=>s.entities.get(t.id).damageReduction=2,(s:any)=>s.entities.get(u.id).eliteHpAuraFactor=0]){const bad=structuredClone(save);change(bad.state);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}
});

test('Mourner reduces the existing native guardian flat defense relatively, while finite shields remain authoritative',()=>{
 const w=fixture(),u=elite(w,'banshee.1'),t=enemy(w,4),s=w.addUnit('sentry','zerg',4,1);s.energy=s.maxEnergy;w.hash.rebuild(w.entities.values());tickAutoAbilities(w,s);assert.ok(w.expedition.spells.some(s=>s.kind==='guardian'));const hp=t.hp;w.hit(t,100,[],1,'terran',0,0,u.id);near(hp-t.hp,98.5);u.hp=0;const before=t.hp;w.hit(t,100,[],1,'terran',0,0,u.id);near(before-t.hp,98);
});

test('elite auras benefit actual heroes, preserve wounds and exclude enemy/temporary bodies',()=>{
 const w=fixture();assert.ok(w.acquireHero('yamato_battlecruiser'));const h=w.heroEntity('yamato_battlecruiser')!;h.x=h.z=0;w.refreshStats(h,true);const base={hp:h.maxHp,armor:h.armor,move:h.moveSpeed};h.hp=h.maxHp*.4;const med=elite(w,'medivac.1'),thor=elite(w,'thor.1'),banshee=elite(w,'banshee.3');w.time=3;w.refreshStats(h);near(h.maxHp,base.hp*1.35);near(h.hp/h.maxHp,.4);near(h.armor,base.armor+9);near(h.moveSpeed,base.move*1.3);for(let i=0;i<10;i++)w.refreshStats(h);near(h.hp/h.maxHp,.4);const e=enemy(w);assert.deepEqual(eliteFriendlyAura(w,e),{family:1,hp:1,armor:0,move:1});med.x=thor.x=banshee.x=50;w.refreshStats(h);near(h.maxHp,base.hp);near(h.hp/h.maxHp,.4);near(h.armor,base.armor);med.x=0;const temp=w.addUnit('marine','terran',0,0);temp.temporary=true;near(eliteFriendlyAura(w,temp).hp,1);
});
test('Mourner never reduces friendly armor; actual owned interceptors inherit medical command once through their mother',()=>{
 const w=fixture(),mourner=elite(w,'banshee.1'),friend=w.addUnit('tank','terran',1,0),e=enemy(w,2);near(eliteDebuffValue(w,mourner,'armor'),0);near(eliteDebuffValue(w,friend,'armor'),0);near(eliteDebuffValue(w,e,'armor'),.4);
 const p=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[]});p.start();p.entities.clear();p.heroes.clear();p.pods=[];p.hive=null;assert.ok(p.acquireHero('purifier_flagship'));const mother=p.heroEntity('purifier_flagship')!;mother.x=mother.z=0;initializeCarrierSubsystem(p);const children=ownedInterceptors(p,mother.id),child=children[0],base={hp:child.maxHp,armor:child.armor};child.hp=child.maxHp*.4;elite(p,'medivac.1');elite(p,'thor.1');for(let i=0;i<10;i++){p.refreshStats(mother);p.refreshStats(child);}near(child.maxHp,base.hp*1.35);near(child.hp/child.maxHp,.4);near(child.armor,base.armor+9*1.3);near(mother.eliteHpAuraFactor!,1.35);assert.equal(ownedInterceptors(p,mother.id).length,12);
});
