import {tickTeamAuras} from '../src/simulation/combat/team-auras';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {World} from '../src/simulation/world';
import {ELITES} from '../src/data/elites';
import {ZERG_ELITE_IDS,ZERG_ELITE_RULES,type ZergEliteId} from '../src/data/zerg-elites';
import {TERRAN_ELITE_BODIES} from '../src/data/terran-elites';
import {RUN_SCHEMA} from '../src/simulation/persistence/run-snapshot';
import {createPair,pairFor,pairBodies,tickBroods} from '../src/simulation/zerg-brood';
import {zergEliteCombat,zergEliteStatModifiers,zergEliteDebuff,zergEliteQueenAbility,zergEliteBile,tickZergElite,tickZergEliteState,zergEliteModeCompleted,pruneZergEliteState} from '../src/simulation/combat/zerg-elite-runtime';
import {tickWeaponFlights} from '../src/simulation/combat/weapon-flight';
import {tickNativeMode,selectWeapon,unitData,expeditionWeaponScale,expeditionWeaponUpgrade} from '../src/simulation/combat/expedition-combat';
import type {Entity} from '../src/simulation/types';
const near=(a:number,b:number,tolerance=1e-5)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
export function zergFixture(){const w=new World({race:'zerg',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10531});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.expedition.zerglingPairs=[];for(const c of Object.values(w.expedition.production))c.enabled={};w.expedition.tech.bile=1;return w;}
export function zergElite(w:World,id:ZergEliteId,rank=1,x=0,z=0){const u=id.startsWith('zergling.')?createPair(w,{x,z},rank):w.addUnit(ELITES[id].family,'terran',x,z,rank);u.eliteId=id;u.modelKey=ELITES[id].model;if(u.unitType==='lurker')u.nativeMode=u.desiredNativeMode='lurker_burrowed';w.refreshStats(u,true);if(u.unitType==='ravager')u.bileCooldown=0;for(const b of u.pairId?pairBodies(w,pairFor(w,u)!):[])w.refreshStats(b,true);return u;}
export function zergEnemy(w:World,x=2,z=0,air=false){const t=w.addUnit(air?'mutalisk':'roach','zerg',x,z);t.hp=t.maxHp=1e7;t.armor=t.shield=0;t.attributes=[];t.weaponDamage=0;t.stoppedUntil=t.nextShotAt=t.specialReady=1e9;return t;}
function settle(w:World,seconds=2){for(let i=0;i<Math.ceil(seconds*60);i++){w.time+=1/60;w.hash.rebuild(w.entities.values());tickWeaponFlights(w,1/60);tickZergEliteState(w);}}
function shoot(w:World,u:Entity,t:Entity){selectWeapon(w,u,t);w.refreshStats(u);w.hash.rebuild(w.entities.values());w.fire(u,t);settle(w,.75);}

test('P4-B runtime copies all thirty approved identities and parameters; no runtime proposal import',()=>{const rows=JSON.parse(fs.readFileSync('docs/project/NEXT_ITERATION_P4_VALUES_20261005.json','utf8')).approved.elites.filter((r:any)=>r.race==='zerg');assert.equal(rows.length,30);assert.equal(ZERG_ELITE_IDS.length,30);for(const r of rows){assert.deepEqual(ZERG_ELITE_RULES[r.id as ZergEliteId].parameters,r.parameters);assert.equal(ELITES[r.id as ZergEliteId].name,r.name);}assert.ok(!fs.readFileSync('src/data/zerg-elites.ts','utf8').includes('NEXT_ITERATION_P'));});
for(const id of ZERG_ELITE_IDS)test(`P4-B ${id}: all five ranks retain ordinary-V period and approved growth, wounds, energy and clocks`,()=>{for(let rank=1;rank<=5;rank++){const w=zergFixture(),u=w.addUnit(ELITES[id].family,'terran',0,0,5);if(u.unitType==='lurker')u.nativeMode='lurker_burrowed';w.refreshStats(u,true);const base={hp:u.maxHp,damage:u.weaponDamage,period:u.attackPeriod,armor:u.armor,move:u.moveSpeed,heal:u.healRate};u.eliteId=id;u.rank=rank;w.refreshStats(u,true);const b=TERRAN_ELITE_BODIES[ZERG_ELITE_RULES[id].body],aura=id==='queen.1'?1.45:id==='corruptor.2'?1.35:id==='zergling.3'?1.2:1,command=id==='zergling.3'?1.2:1;near(u.maxHp,base.hp*b.hp*(1+.3*(rank-1))*aura);near(u.weaponDamage,base.damage*b.dps*(1+.35*(rank-1))*command);near(u.attackPeriod,base.period/command/(id==='corruptor.2'?1.25:1));near(u.armor,(base.armor+b.armor+.5*(rank-1))*command+(['queen.1','corruptor.2'].includes(id)?6:0));near(u.moveSpeed,base.move*b.move*command);near(u.healRate,base.heal*b.heal*(1+.35*(rank-1)));u.hp-=37;u.nextShotAt=41;u.energy=17;zergEliteCombat(u).ready=62;for(let n=0;n<4;n++)w.refreshStats(u);near(u.maxHp-u.hp,37);near(u.energy,Math.min(17,u.maxEnergy));near(u.nextShotAt,41);near(zergEliteCombat(u).ready,62);}});
test('twins share at most eight frenzy layers without extra bodies, separate cycles and two-second expiration',()=>{const w=zergFixture(),a=zergElite(w,'zergling.1'),b=pairBodies(w,pairFor(w,a)!).find(b=>b.id!==a.id)!,t=zergEnemy(w);for(let i=0;i<10;i++)w.fire(i%2?a:b,t);assert.equal(w.allies().length,2);near(zergEliteStatModifiers(w,a).speed,3.4);near(zergEliteStatModifiers(w,b).speed,3.4);assert.equal(zergEliteCombat(a).cycles,5);assert.equal(zergEliteCombat(b).cycles,5);const c=zergFixture();c.restoreRun(w.captureRun());near(zergEliteStatModifiers(c,c.entities.get(a.id)!).speed,3.4);w.time=2;tickZergEliteState(w);near(zergEliteStatModifiers(w,a).speed,1);});
test('fangs replace each third cycle with fourfold damage and reduce positive life/native shield armor',()=>{const w=zergFixture(),u=zergElite(w,'zergling.2'),t=zergEnemy(w);t.attributes=['Armored'];const base=u.weaponDamage;for(let i=0;i<3;i++)w.fire(u,t);near(1e7-t.hp,base*6*1.6);near(zergEliteDebuff(w,t,'armor'),.5);t.armor=t.shieldArmor=10;t.shield=1000;w.hit(t,100,[],1,'terran',0);near(t.shield,905);t.shield=0;const hp=t.hp;w.hit(t,100,[],1,'terran',0);near(hp-t.hp,95);});
test('symbiotic twins share actual life loss once, leech life only, and regrow once at 900 steps with sixty-percent HP',()=>{const w=zergFixture(),a=zergElite(w,'zergling.3'),p=pairFor(w,a)!,b=pairBodies(w,p).find(b=>b.id!==a.id)!,t=zergEnemy(w);a.armor=b.armor=0;w.hit(a,100,[],1,'zerg',0,1,t.id);near(a.maxHp-a.hp,50);near(b.maxHp-b.hp,50);a.hp-=100;t.shield=1000;const hp=a.hp;w.fire(a,t);near(a.hp,hp);t.shield=0;w.fire(a,t);near(a.hp-hp,uDamage(a)*.25);w.hit(b,b.hp+100,[],1,'zerg',0,1,t.id,false,true);w.entities.delete(b.id);assert.equal(p.regrowAt,900);w.tick=899;tickBroods(w);assert.equal(pairBodies(w,p).length,1);w.tick=900;tickBroods(w);const grown=pairBodies(w,p).find(t=>t.id!==a.id)!;near(grown.hp/grown.maxHp,.6);tickBroods(w);assert.equal(pairBodies(w,p).length,2);});
const uDamage=(u:Entity)=>u.weaponDamage;
for(const id of ['baneling.1','baneling.2','baneling.3'] as const)test(`${id}: permanent true body survives exactly one explosion and five-second stop through save/rank`,()=>{const w=zergFixture(),u=zergElite(w,id),t=zergEnemy(w,1);w.hash.rebuild(w.entities.values());w.fire(u,t);assert.ok(u.hp>0);near(u.recoveryUntil!,5);const hp=t.hp,shots=w.stats.shots;u.rank=5;w.refreshStats(u);w.fire(u,t);near(t.hp,hp);assert.equal(w.stats.shots,shots);const c=zergFixture();c.restoreRun(w.captureRun());c.paused=false;c.time=4.99;c.fire(c.entities.get(u.id)!,c.entities.get(t.id)!);near(c.entities.get(t.id)!.hp,hp);c.time=5;c.fire(c.entities.get(u.id)!,c.entities.get(t.id)!);assert.equal(c.entities.get(u.id)!.recoveryUntil,10);});
test('seeded acid makes five ground-only fixed pulses, strongest same-source overlaps and no armor scaling',()=>{const w=zergFixture(),u=zergElite(w,'baneling.2'),t=zergEnemy(w,1),air=zergEnemy(w,1,0,true);w.fire(u,t);const before=t.hp;const area=w.zergElites.areas[0];w.zergElites.areas.push({...structuredClone(area),id:w.nextId++});settle(w,5.01);near(before-t.hp,420*5);near(air.hp,1e7);assert.equal(w.zergElites.areas.length,0);});
test('acid reactor stores only actual enemy life loss, finite cap and consumes it once with bounded real healing',()=>{const w=zergFixture(),u=zergElite(w,'baneling.3'),t=zergEnemy(w);u.armor=0;u.barrier=100;w.hit(u,100,[],1,'zerg',0,1,t.id);near(zergEliteCombat(u).stored,0);w.hit(u,100,[],1,'zerg',0,1,t.id);near(zergEliteCombat(u).stored,50);const hp=u.hp;w.fire(u,t);near(zergEliteCombat(u).stored,0);assert.ok(u.hp>=hp&&u.hp<=u.maxHp);});
test('fortress burrows as a detectable, damageable finite episode, stops attacking, heals and respects eighteen-second cooldown',()=>{const w=zergFixture(),u=zergElite(w,'roach.1'),t=zergEnemy(w);u.hp=u.maxHp*.3;const armor=u.armor;w.refreshStats(u);near(u.armor,armor+8);assert.equal(tickZergElite(w,u,1/60),true);w.fire(u,t);assert.equal(w.weaponFlights.length,0);w.time=.6;tickZergElite(w,u,1/60);assert.equal(u.cloaked,true);assert.equal(w.visibleTo(u,'zerg'),false);w.expedition.detectionFields.push({id:w.nextId++,x:0,z:0,radius:12,until:10,team:'enemy'});assert.equal(w.visibleTo(u,'zerg'),true);const hp=u.hp;w.hit(u,30,[],1,'zerg',0,1,t.id);near(hp-u.hp,30);w.time=3.6;tickZergElite(w,u,1/60);w.time=4.2;tickZergElite(w,u,1/60);assert.equal(zergEliteCombat(u).burrowPhase,0);u.hp=u.maxHp*.1;tickZergElite(w,u,1/60);assert.equal(zergEliteCombat(u).burrowPhase,0);});
test('acid throat caps target stacks, replaces sixth with fourfold true area contact and resets on retarget',()=>{const w=zergFixture(),u=zergElite(w,'roach.2'),t=zergEnemy(w,3),n=zergEnemy(w,3,1);for(let i=0;i<6;i++){w.fire(u,t);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*(i===5?4:1+.3*Math.min(5,i+1)));settle(w,.3);}assert.ok(n.hp<1e7);w.fire(u,n);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*1.3);assert.equal(zergEliteCombat(u).cycles,7);});
test('retaliating shell requires real enemy melee damage and half-second gate, successful attack grants finite regeneration',()=>{const w=zergFixture(),u=zergElite(w,'roach.3'),t=zergEnemy(w,1);t.attackRange=1;u.armor=0;const hp=t.hp;w.hit(u,100,[],1,'zerg',0,1,t.id);near(hp-t.hp,60);w.hit(u,100,[],1,'zerg',0,1,t.id);near(hp-t.hp,60);w.time=.5;t.attackRange=5;w.hit(u,100,[],1,'zerg',0,1,t.id);near(hp-t.hp,60);shoot(w,u,t);const before=u.hp;tickZergElite(w,u,1);near(u.hp-before,u.maxHp*.04);});
test('ravager triple bile needs existing technology, saves three delayed flights and retains original 2.5-second warning delay',()=>{const w=zergFixture(),u=zergElite(w,'ravager.1'),t=zergEnemy(w,4);w.expedition.tech.bile=0;zergEliteBile(w,u,.1);assert.equal(w.zergElites.biles.length,0);w.expedition.tech.bile=1;zergEliteBile(w,u,.1);assert.equal(w.zergElites.biles.length,3);assert.deepEqual(w.zergElites.biles.map(b=>b.launchAt),[0,.3,.6]);near(u.bileCooldown,9);const c=zergFixture();c.restoreRun(w.captureRun());settle(c,3.2);near(1e7-c.entities.get(t.id)!.hp,3600);assert.equal(c.zergElites.biles.length,0);});
test('siege acid star applies one armored/building factor and positive armor debuff; rain has six ground pulses and half Boss movement',()=>{for(const id of ['ravager.2','ravager.3'] as const){const w=zergFixture(),u=zergElite(w,id),t=zergEnemy(w,4);t.attributes=['Armored'];t.enemyTier='boss';zergEliteBile(w,u,.1);settle(w,2.51);near(1e7-t.hp,id==='ravager.2'?7200:1200);if(id==='ravager.2')near(zergEliteDebuff(w,t,'armor'),.5);else {const hp=t.hp;settle(w,6.01);near(hp-t.hp,380*6);}}});
test('needle storm launches five real seventy-percent packets; one attack identity and one primary receipt',()=>{const w=zergFixture(),u=zergElite(w,'hydralisk.1'),t=zergEnemy(w,5);w.fire(u,t);assert.equal(w.weaponFlights.length,5);assert.equal(new Set(w.weaponFlights.map(p=>p.attackId)).size,1);assert.equal(w.weaponFlights.filter(p=>p.primary).length,1);settle(w);near(1e7-t.hp,u.weaponDamage*3.5);near(u.attackRange,unitData(u).attackRange+2);});
test('long spine has real spear contact and downstream eighty-percent penetration in the same plane, stops at walls',()=>{const w=zergFixture(),u=zergElite(w,'hydralisk.2'),t=zergEnemy(w,4),n=zergEnemy(w,7),side=zergEnemy(w,7,3),air=zergEnemy(w,7,0,true);t.attributes=['Armored'];w.fire(u,t);settle(w,.033);near(t.hp,1e7);settle(w,.3);near(1e7-t.hp,u.weaponDamage*2.5);near(1e7-n.hp,u.weaponDamage*.8);near(side.hp,1e7);near(air.hp,1e7);});
test('hydra poison stacks at four, uses fixed life DOT, spreads only one remaining layer to four and cannot recurse',()=>{const w=zergFixture(),u=zergElite(w,'hydralisk.3'),t=zergEnemy(w,3),n=zergEnemy(w,5);for(let i=0;i<5;i++)shoot(w,u,t);assert.equal(w.zergElites.poisons.find(p=>p.target===t.id)!.layers,4);const hp=t.hp;settle(w,1);near(hp-t.hp,480);w.hit(t,t.hp+1,[],1,'terran',0,1,u.id);const p=w.zergElites.poisons.find(p=>p.target===n.id)!;assert.equal(p.layers,1);assert.equal(p.spread,false);w.hit(n,n.hp+1,[],1,'terran',0,1,u.id);assert.equal(w.zergElites.poisons.length,0);});
test('brood queen aura preserves wound ratios once, only permanent biological bodies and real regeneration',()=>{const w=zergFixture(),b=w.addUnit('roach','terran',2,0),old=b.maxHp;b.hp=old*.4;const queen=zergElite(w,'queen.1'),mechanical=w.addUnit('tank','terran',2,1),temporary=w.addUnit('roach','terran',2,2);temporary.temporary=true;const mhp=mechanical.maxHp,thp=temporary.maxHp/1.45;w.refreshStats(b);near(b.maxHp,old*1.45);near(b.hp/b.maxHp,.4);w.refreshStats(mechanical);w.refreshStats(temporary);near(mechanical.maxHp,mhp);near(temporary.maxHp,thp);tickTeamAuras(w,1);near(b.hp/b.maxHp,.42);queen.x=30;w.refreshStats(b);near(b.maxHp,old);near(b.hp/b.maxHp,.42);});
test('transfusion matron reserves five biological wounds, spends fifty energy once, heals four fixed seconds and stops on source death/range',()=>{const w=zergFixture(),u=zergElite(w,'queen.2');u.energy=50;const targets=[];for(let i=0;i<6;i++){const b=w.addUnit('ultralisk','terran',2+i*.3,0,5);b.hp=1;targets.push(b);}const mechanical=w.addUnit('tank','terran',2,1,5);mechanical.hp=1;zergEliteQueenAbility(w,u);assert.equal(w.zergElites.heals[0].targets.length,5);near(u.energy,0);settle(w,4.01);near(w.stats.healed,5*60*(1+15*1.3));near(mechanical.hp,1);near(targets[5].hp,1);assert.equal(w.zergElites.heals.length,0);u.energy=0;w.time=12;zergEliteQueenAbility(w,u);assert.equal(w.zergElites.heals.length,0);});
test('venom guard impacts real twofold payload and local ground-only slow; Boss debuffs halve, expire',()=>{const w=zergFixture(),u=zergElite(w,'queen.3'),t=zergEnemy(w,4),n=zergEnemy(w,5),air=zergEnemy(w,5,0,true);n.enemyTier='boss';shoot(w,u,t);near(1e7-t.hp,u.weaponDamage*2);near(1e7-n.hp,u.weaponDamage*2);near(air.hp,1e7);near(zergEliteDebuff(w,t,'move'),.5);near(zergEliteDebuff(w,n,'speed'),.15);w.time+=3;tickZergEliteState(w);near(zergEliteDebuff(w,t,'move'),0);});
test('three lurker lines grow from the real burrow point, hit each intersected body once per line and persist progression',()=>{const w=zergFixture(),u=zergElite(w,'lurker.1'),t=zergEnemy(w,8),n=zergEnemy(w,8,3);w.fire(u,t);assert.equal(w.zergElites.lines.length,3);near(t.hp,1e7);settle(w,.15);near(t.hp,1e7);const c=zergFixture();c.restoreRun(w.captureRun());settle(c,.5);near(1e7-c.entities.get(t.id)!.hp,u.weaponDamage);assert.ok(c.entities.get(n.id)!.hp<1e7);assert.equal(c.zergElites.lines.length,0);});
test('giant fourth spine substitutes fivefold eighteen-length damage and legal slow; wall blocks downstream contacts',()=>{const w=zergFixture(),u=zergElite(w,'lurker.2'),t=zergEnemy(w,6),n=zergEnemy(w,16);for(let i=0;i<4;i++){w.fire(u,t);settle(w,.8);}near(1e7-t.hp,u.weaponDamage*8);near(1e7-n.hp,u.weaponDamage*5);near(zergEliteDebuff(w,n,'move'),.6);});
test('ambusher speeds native burrow, opens exactly three fourfold attacks and cannot refill finite barrier within twelve seconds',()=>{const w=zergFixture(),u=zergElite(w,'lurker.3');u.nativeMode='lurker';u.desiredNativeMode='lurker_burrowed';tickNativeMode(w,u);assert.ok(u.nativeModeUntil!<1);w.time=u.nativeModeUntil!;tickNativeMode(w,u);near(zergEliteCombat(u).barrier,u.maxHp*.4);const t=zergEnemy(w,5);for(let i=0;i<4;i++){w.fire(u,t);near(w.zergElites.lines.at(-1)!.damage,u.weaponDamage*(i<3?4:1));settle(w,.6);}zergEliteCombat(u).barrier=0;zergEliteModeCompleted(w,u,'lurker');near(zergEliteCombat(u).barrier,0);});
test('six-wing glaive has six saved real sequential arrivals, unique targets, exact approved packet losses and no cycle recursion',()=>{const w=zergFixture(),u=zergElite(w,'mutalisk.1'),targets=Array.from({length:6},(_,i)=>zergEnemy(w,3+i*3,0,true));w.fire(u,targets[0]);settle(w,.15);const c=zergFixture();c.restoreRun(w.captureRun());settle(c,2);const damage=targets.map(t=>1e7-c.entities.get(t.id)!.hp);for(let i=0;i<6;i++)near(damage[i],u.weaponDamage*[1,.8,.65,.5,.4,.3][i]);assert.equal(zergEliteCombat(c.entities.get(u.id)!).cycles,1);});
test('strangler launches three independent glaives, each owns a short chain; misses never return unused hop damage',()=>{const w=zergFixture(),u=zergElite(w,'mutalisk.2'),a=zergEnemy(w,3,0,true),b=zergEnemy(w,5,0,true),c=zergEnemy(w,7,0,true);w.fire(u,a);assert.equal(w.weaponFlights.length,3);settle(w);near(1e7-a.hp,u.weaponDamage*3);near(1e7-b.hp,u.weaponDamage*1.05);near(1e7-c.hp,u.weaponDamage*.45);assert.equal(zergEliteCombat(u).cycles,1);});
test('bloodwing charges six seconds after two quiet seconds, consumes one eighty-percent shell and three-second attack burst',()=>{const w=zergFixture(),u=zergElite(w,'mutalisk.3'),t=zergEnemy(w,4,0,true);for(let i=0;i<481;i++){w.time+=1/60;tickZergElite(w,u,1/60);}near(zergEliteCombat(u).charge,1);u.hp-=100;w.fire(u,t);near(zergEliteCombat(u).barrier,u.maxHp*.8);near(zergEliteStatModifiers(w,u).speed,3);zergEliteCombat(u).barrier=0;w.fire(u,t);near(zergEliteCombat(u).barrier,0);w.time+=3;near(zergEliteStatModifiers(w,u).speed,1);});
test('air lock ramps continuously to fourfold, resets on retarget and never attacks ground',()=>{const w=zergFixture(),u=zergElite(w,'corruptor.1'),a=zergEnemy(w,4,0,true),b=zergEnemy(w,5,0,true),ground=zergEnemy(w,4);w.fire(u,a);settle(w,.3);const hp=a.hp;w.time=4;w.fire(u,a);settle(w,.3);near(hp-a.hp,u.weaponDamage*4);w.fire(u,b);settle(w,.3);near(1e7-b.hp,u.weaponDamage);const shots=w.stats.shots;w.fire(u,ground);assert.equal(w.stats.shots,shots);});
test('air guard redirects thirty-percent real life loss with one twenty-percent-HP budget per second, no recursion and twenty-five-percent self reduction',()=>{const w=zergFixture(),u=zergElite(w,'corruptor.2'),ally=w.addUnit('mutalisk','terran',2,0,5),ground=w.addUnit('roach','terran',2,1,5),t=zergEnemy(w,4,0,true);u.armor=ally.armor=ground.armor=0;w.hit(ally,100,[],1,'zerg',0,1,t.id);near(ally.maxHp-ally.hp,70);near(u.maxHp-u.hp,30);w.hit(ground,100,[],1,'zerg',0,1,t.id);near(ground.maxHp-ground.hp,100);const hp=u.hp;w.hit(u,100,[],1,'zerg',0,1,t.id);near(hp-u.hp,75);for(let i=0;i<100;i++)w.hit(ally,100,[],1,'zerg',0,1,t.id);assert.ok(zergEliteCombat(u).redirectSpent<=u.maxHp*.2);});
test('air plague caps one poison capsule, actual non-Boss death bursts once and spreads to at most three air recipients without recursion',()=>{const w=zergFixture(),u=zergElite(w,'corruptor.3'),a=zergEnemy(w,3,0,true),b=zergEnemy(w,5,0,true),g=zergEnemy(w,4);shoot(w,u,a);shoot(w,u,a);assert.equal(w.zergElites.poisons.length,1);w.hit(a,a.hp+1,[],1,'terran',0,1,u.id);near(1e7-b.hp,1800);near(g.hp,1e7);assert.equal(w.zergElites.poisons[0].spread,false);const before=w.stats.damage;w.hit(b,b.hp+1,[],1,'terran',0,1,u.id);assert.equal(w.zergElites.poisons.length,0);assert.ok(w.stats.damage>before);});
test('tyrant third cleave replaces damage and covers actual forward 170 degrees, radius 1.8 and light modifier',()=>{const w=zergFixture(),u=zergElite(w,'ultralisk.1'),a=zergEnemy(w,1.5),b=zergEnemy(w,2.2,1.2),rear=zergEnemy(w,-2);a.attributes=['Light'];for(let i=0;i<3;i++)w.fire(u,a);near(1e7-a.hp,u.weaponDamage*5*1.5);assert.ok(b.hp<1e7);near(rear.hp,1e7);});
test('immortal shell stores actual loss and releases finite survival heal once/25s; lethal blow cannot revive',()=>{const w=zergFixture(),u=zergElite(w,'ultralisk.2'),t=zergEnemy(w);u.armor=0;const initial=u.maxHp;w.hit(u,initial*.72,[],1,'zerg',0,1,t.id);near(zergEliteCombat(u).stored,0);near(u.hp,initial*(.28+.72*.4));near(zergEliteCombat(u).ready,25);const hp=u.hp;w.hit(u,100,[],1,'zerg',0,1,t.id);near(hp-u.hp,65);w.hit(u,u.hp*10,[],1,'zerg',0,1,t.id);near(u.hp,0);assert.equal(u.deadAt,w.time);});
test('primal trampler travels physical distance before finite arrival stomp; collisions stop movement, no teleport through wall',()=>{const w=zergFixture(),u=zergElite(w,'ultralisk.3'),t=zergEnemy(w,5);tickZergElite(w,u,1/60);assert.ok(u.x>0&&u.x<1);near(t.hp,1e7);const c=zergFixture();c.restoreRun(w.captureRun());const v=c.entities.get(u.id)!;for(let i=0;i<60;i++){c.time+=1/60;tickZergElite(c,v,1/60);}assert.ok(v.x<5);near(1e7-c.entities.get(t.id)!.hp,2200);near(zergEliteStatModifiers(c,v).speed,2);near(zergEliteCombat(v).ready,12);});
test('schema22 rejects malformed, replayed, foreign and nonfinite Zerg state atomically, pause freezes derived timers',()=>{const w=zergFixture(),u=zergElite(w,'mutalisk.1'),t=zergEnemy(w,5,0,true);w.fire(u,t);const save=w.captureRun();const copy=zergFixture();copy.restoreRun(save);const stable=copy.captureRun();const mutations=[(s:any)=>s.entities.get(u.id).zergEliteCombat.charge=2,(s:any)=>s.weaponFlights[0].bounceLimit=9,(s:any)=>s.weaponFlights[0].bounceDamage[3]=Infinity,(s:any)=>s.weaponFlights[0].seen=[t.id,t.id],(s:any)=>s.zergElites.frenzy.forged={stacks:9,until:3},(s:any)=>s.zergElites.gates.bad=NaN];for(const m of mutations){const bad=structuredClone(save);m(bad.state);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}copy.step();assert.deepEqual(copy.captureRun(),stable);});

test('all three permanent banelings retain independent VolatileBurstU2 building payload and native armor bypass',()=>{for(const id of ['baneling.1','baneling.2','baneling.3'] as const){const w=zergFixture(),u=zergElite(w,id),t=zergEnemy(w,1);t.attributes=['Structure','Light'];t.armor=1000;const factor=id==='baneling.1'?3:id==='baneling.2'?2:1.8,expected=(80+expeditionWeaponUpgrade(w,u,'VolatileBurstU2').damage)*expeditionWeaponScale(w,u)*factor;w.fire(u,t);near(1e7-t.hp,expected);assert.ok(u.hp>0);near(u.recoveryUntil!,5);}});
test('finite stored receipts accept actual enemy life loss without surviving source and exclude friendly, forced and transferred damage',()=>{const w=zergFixture(),u=zergElite(w,'baneling.3');u.armor=0;w.hit(u,20,[],1,'zerg',0,1);near(zergEliteCombat(u).stored,10);w.hit(u,20,[],1,'terran',0,1);near(zergEliteCombat(u).stored,10);w.hit(u,20,[],1,'zerg',0,1,undefined,true);near(zergEliteCombat(u).stored,10);w.hit(u,20,[],1,'zerg',0,1,undefined,false,true);near(zergEliteCombat(u).stored,10);});
test('new bloodwing requires full two seconds since birth and six further seconds; enemy damage restarts quiet wait',()=>{const w=zergFixture();w.time=10;const u=zergElite(w,'mutalisk.3');w.time=11.99;tickZergElite(w,u,1/60);near(zergEliteCombat(u).charge,0);w.time=12;tickZergElite(w,u,1/60);near(zergEliteCombat(u).charge,1/360);w.hit(u,1,[],1,'zerg',0,1);w.time=13.99;tickZergElite(w,u,1/60);near(zergEliteCombat(u).charge,1/360);});
test('saved matron window validates live range and source life at each pulse, without retargeting frozen recipients',()=>{const w=zergFixture(),u=zergElite(w,'queen.2');u.energy=50;const patients=Array.from({length:5},(_,i)=>{const p=w.addUnit('ultralisk','terran',2+i*.2,0,5);p.hp=1;return p;});zergEliteQueenAbility(w,u);const c=zergFixture();c.restoreRun(w.captureRun());c.entities.get(patients[0].id)!.x=40;settle(c,1.01);near(c.stats.healed,4*60*(1+3*1.3));const caster=c.entities.get(u.id)!;c.hit(caster,caster.hp*2,[],1,'zerg',0,1);const healed=c.stats.healed;settle(c,3.1);near(c.stats.healed,healed);assert.equal(c.zergElites.heals.length,0);});
test('charge rechecks a wall introduced after launch; it stops physically without a remote stomp',()=>{const w=zergFixture(),u=zergElite(w,'ultralisk.3'),t=zergEnemy(w,6);tickZergElite(w,u,1/60);assert.ok(zergEliteCombat(u).dash);w.obstacles=[{x:1.5,z:0,w:.5,h:8}];for(let i=0;i<90;i++){w.time+=1/60;tickZergElite(w,u,1/60);}assert.ok(u.x<1.5);near(t.hp,1e7);assert.equal(zergEliteCombat(u).dash,null);near(zergEliteCombat(u).ready,12);});
test('finite but forged bile, heal and spine payloads reject import atomically while genuine active windows restore',()=>{for(const id of ['ravager.2','queen.2','lurker.2'] as const){const w=zergFixture(),u=zergElite(w,id),t=zergEnemy(w,5);if(id==='ravager.2')zergEliteBile(w,u,.1);if(id==='queen.2'){const patient=w.addUnit('ultralisk','terran',2,0,5);patient.hp=1;u.energy=50;zergEliteQueenAbility(w,u);}if(id==='lurker.2'){zergEliteCombat(u).cycles=3;w.fire(u,t);}const saved=w.captureRun(),c=zergFixture();c.restoreRun(saved);const stable=c.captureRun(),bad=structuredClone(saved);if(id==='ravager.2')bad.state.zergElites.biles[0].damage+=1;if(id==='queen.2')bad.state.zergElites.heals[0].amount+=1;if(id==='lurker.2')bad.state.zergElites.lines[0].damage+=1;assert.throws(()=>c.restoreRun(bad));assert.deepEqual(c.captureRun(),stable);}});
test('explicit removal prunes poison without death explosion or derived propagation, leaving a valid save',()=>{const w=zergFixture(),u=zergElite(w,'corruptor.3'),t=zergEnemy(w,3,0,true);shoot(w,u,t);const damage=w.stats.damage;w.entities.delete(t.id);pruneZergEliteState(w);assert.equal(w.zergElites.poisons.length,0);near(w.stats.damage,damage);const c=zergFixture();c.restoreRun(w.captureRun());});

test('saved bile batches and transfusion windows reject cloned finite effects with fresh IDs before any World mutation',()=>{for(const id of ['ravager.1','queen.2'] as const){const w=zergFixture(),u=zergElite(w,id);zergEnemy(w,4);if(id==='ravager.1')zergEliteBile(w,u,0);else {const t=w.addUnit('ultralisk','terran',2,0,5);t.hp=1;u.energy=50;zergEliteQueenAbility(w,u);}const save=w.captureRun(),copy=zergFixture();copy.restoreRun(save);const stable=copy.captureRun(),bad=structuredClone(save),effects=id==='ravager.1'?bad.state.zergElites.biles:bad.state.zergElites.heals,extra=structuredClone(effects[0]);extra.id=bad.state.nextId++;effects.push(extra);assert.throws(()=>copy.restoreRun(bad));assert.deepEqual(copy.captureRun(),stable);}});

test('acid-throat six-shot sequence repeats after burst and a fifth-shot retarget cannot grant a free finisher',()=>{const w=zergFixture(),u=zergElite(w,'roach.2'),a=zergEnemy(w,4),b=zergEnemy(w,4,1);for(let i=0;i<12;i++){w.fire(u,a);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*(i%6===5?4:1+.3*(i%6+1)));settle(w,.3);}for(let i=0;i<5;i++){w.fire(u,a);settle(w,.3);}w.fire(u,b);near(w.weaponFlights.at(-1)!.damage,u.weaponDamage*1.3);near(zergEliteCombat(u).stacks,1);});

test('brood aura includes every permanent biological Zerg hero without changing intrinsic hero values or losing wound proportions',()=>{for(const id of ['kerrigan','zagara','dehaka','stukov','niadra','hots_leviathan'] as const){const w=zergFixture();assert.ok(w.acquireHero(id));const h=w.heroEntity(id)!;h.x=h.z=0;w.refreshStats(h,true);const base=h.maxHp,armor=h.armor;h.hp=base*.4;const q=zergElite(w,'queen.1',1,1,0);w.refreshStats(h);near(h.maxHp,base*1.45);near(h.hp/h.maxHp,.4);near(h.armor,armor+6);q.x=30;w.refreshStats(h);near(h.maxHp,base);near(h.hp/h.maxHp,.4);near(h.armor,armor);}});

test('an actual main hive can host hydra poison; saved structure capsules restore and deal fixed DOT through shared damage',()=>{const w=zergFixture(),u=zergElite(w,'hydralisk.3');w.hive={id:w.nextId++,x:3,z:0,hp:1e7,maxHp:1e7,armor:0,unitRadius:2,flying:false,attributes:['Structure','Biological'],owner:'zerg',race:'zerg',team:'enemy'};w.fire(u,w.hive);settle(w,.2);assert.equal(w.zergElites.poisons.length,1);const copy=zergFixture();copy.restoreRun(w.captureRun());const hp=copy.hive!.hp;settle(copy,1);near(hp-copy.hive!.hp,120);});
test('buying a replacement twin seat retires old frenzy ownership immediately, without corrupting an otherwise legal save',()=>{const w=zergFixture(),u=zergElite(w,'zergling.1'),t=zergEnemy(w,1);w.fire(u,t);const old=pairFor(w,u)!;assert.ok(w.zergElites.frenzy[old.id]);for(const b of pairBodies(w,old))w.hit(b,b.hp*5,[],1,'zerg',0,1);const n=createPair(w,{x:3,z:2},1);assert.notEqual(n.pairId,old.id);assert.equal(w.zergElites.frenzy[old.id],undefined);const copy=zergFixture();copy.restoreRun(w.captureRun());});
