import test from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {HEROES} from '../src/data/heroes';
import {PROTOSS_HERO_IDS,protossHeroGrowth,type ProtossHeroId} from '../src/data/protoss-heroes';
import {protossState,tickProtossHero,tickProtossHeroState,protossShieldArmor,protossIncomingFactor} from '../src/simulation/combat/protoss-hero-passives';
import {castExpeditionHero,resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';
import {tickHeroAttacks} from '../src/simulation/combat/hero-attack-upgrades';
import {initializeCarrierSubsystem,ownedInterceptors,tickCarrierSubsystem,cleanupCarrierSummons,refreshInterceptorStats} from '../src/simulation/combat/carriers';
import {refreshGroundHeroBuffs,groundHeroBuff,heroGroundSlow,heroGroundSuppression,heroWeaponVulnerability} from '../src/simulation/combat/hero-ground-auras';
import {readArchive,writeArchive} from '../src/persistence/archive';
import {RUN_SCHEMA} from '../src/simulation/persistence/run-snapshot';
import {settleWeaponFlights} from './helpers/weapon-flight';
const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function setup(id:ProtossHeroId,rank=1,bare=true){const w=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10507});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();for(const p of Object.values(w.expedition.production))p.enabled={};assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!,record=w.heroes.get(id)!;u.x=u.z=0;u.prev={x:0,z:0};u.rank=record.rank=rank;if(bare)w.heroes.clear();w.refreshStats(u,true);return {w,u,record};}
function foe(w:World,x=1,z=0){const e=w.addUnit('roach','zerg',x,z);e.hp=e.maxHp=1e6;e.armor=0;e.moveSpeed=0;e.nextShotAt=1e9;e.specialReady=1e9;w.hash.rebuild(w.entities.values());return e;}
function cast({w,u,record}:ReturnType<typeof setup>){w.heroes.set(u.heroId!,record);assert.ok(castExpeditionHero(w,u.heroId!));w.heroes.clear();}
function arrive(w:World,seconds:number){w.time+=seconds;w.hash.rebuild(w.entities.values());tickHeroAttacks(w);resolveExpeditionHeroCasts(w);tickProtossHeroState(w);}
function restored(w:World){const run=readArchive(writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()})).bundle.run!,copy=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[]});copy.restoreRun(run);return copy;}

for(const id of PROTOSS_HERO_IDS)for(const rank of [1,3,5])test(`P3C ${id} ${rank}: bare growth preserves losses and clocks without old multipliers`,()=>{const {w,u}=setup(id,rank),g=protossHeroGrowth(rank),b=HEROES[id];near(u.maxHp,b.hp*g.health);near(u.maxShield!,b.shield*g.health);near(u.weaponDamage,b.damage*g.damage);near(u.attackPeriod,b.period*g.period);u.hp-=71;u.shield!-=43;u.nextShotAt=17;u.weaponCooldown=.123;for(let i=0;i<3;i++)w.refreshStats(u);near(u.maxHp-u.hp,71);near(u.maxShield!-u.shield!,43);near(u.nextShotAt,17);near(u.weaponCooldown,.123);assert.equal(u.modelKey,b.model);assert.equal(u.maxEnergy,0);});

test('P3C Artanis registers full native shields, freezes maxima, pulses for eight seconds and does not heal life',()=>{const s=setup('artanis'),{w,u}=s,ally=w.addUnit('stalker','terran',2,0),worker=Object.assign(w.addUnit('stalker','terran',1,0),{unitType:'probe' as never}),temp=w.addUnit('zealot','terran',1,1);temp.temporary=true;const old=ally.maxShield!;ally.hp-=10;u.shield=0;worker.shield=0;temp.shield=0;w.hash.rebuild(w.entities.values());cast(s);assert.ok(w.protossHeroes.shields[0].targets.some(t=>t.id===ally.id));assert.ok(!w.protossHeroes.shields[0].targets.some(t=>t.id===worker.id||t.id===temp.id));near(u.shield,2000);ally.shield=0;ally.maxShield=old*2;arrive(w,1);near(ally.shield,old*.1);near(ally.maxHp-ally.hp,10);near(temp.shield,0);near(worker.shield,0);arrive(w,7);near(ally.shield,old*.8);assert.equal(w.protossHeroes.shields.length,0);arrive(w,3);near(ally.shield,old*.8);});
test('P3C Artanis seven-body effective passive is 3920/s, native-only and loss-limited',()=>{const {w,u}=setup('artanis');u.shield=u.maxShield;const bodies=[];for(let i=0;i<9;i++){const a=w.addUnit('stalker','terran',2+i*.15,0);a.shield=0;a.maxShield=1e6;bodies.push(a);}const mechanicalNoShield=w.addUnit('tank','terran',1,0);mechanicalNoShield.hp=1;tickProtossHero(w,u,1);near(w.stats.healed,3920);assert.equal(u.healTargets!.length,7);assert.equal(bodies.filter(a=>a.shield===560).length,7);near(mechanicalNoShield.hp,1);bodies.forEach(a=>a.shield=a.maxShield!-1);const before=w.stats.healed;tickProtossHero(w,u,1);near(w.stats.healed-before,7);});
test('P3C Artanis saved window preserves remaining pulses, cancels out of range and caster death',()=>{const s=setup('artanis'),{w,u}=s,ally=w.addUnit('stalker','terran',2,0);ally.shield=0;cast(s);arrive(w,1);const copy=restored(w);near(copy.entities.get(ally.id)!.shield!,ally.shield!);copy.entities.get(ally.id)!.x=50;arrive(copy,1);near(copy.entities.get(ally.id)!.shield!,ally.shield!);copy.entities.get(u.id)!.hp=0;arrive(copy,1);assert.equal(copy.protossHeroes.shields.length,0);});
test('P3C Artanis third actual primary cleaves ground frontal enemies once, excludes rear and air',()=>{const {w,u}=setup('artanis'),main=foe(w,1),front=foe(w,1,.5),rear=foe(w,-1),air=foe(w,1,-.5);air.flying=true;for(let i=0;i<3;i++){w.fire(u,main);settleWeaponFlights(w);}near(1e6-main.hp,u.weaponDamage*6);near(1e6-front.hp,u.weaponDamage*2);near(rear.hp,1e6);near(air.hp,1e6);assert.equal(protossState(u).cycles,3);});

test('P3C Zeratul spends exactly three opening cycles; no refill until out of combat and cooldown',()=>{const {w,u}=setup('zeratul'),e=foe(w);for(let i=0;i<3;i++){const hp=e.hp;w.fire(u,e);settleWeaponFlights(w);near(hp-e.hp,2400);}const hp=e.hp;w.fire(u,e);settleWeaponFlights(w);near(hp-e.hp,800);assert.equal(w.protossHeroes.echoes.length,1);assert.equal(protossState(u).opening,0);arrive(w,.4);near(hp-e.hp,1200);w.time=12.1;tickProtossHero(w,u,0);assert.equal(protossState(u).opening,3);});
test('P3C Zeratul echo freezes actual armored shield-plus-life damage and survives rank upgrade/save',()=>{const {w,u}=setup('zeratul'),e=foe(w);e.shield=e.maxShield=1000;e.shieldArmor=100;e.armor=300;protossState(u).cycles=3;protossState(u).lastFire=w.time;const before=e.hp+e.shield;w.fire(u,e);settleWeaponFlights(w);const dealt=before-e.hp-e.shield!,echo=w.protossHeroes.echoes[0];near(echo.damage,dealt*.5);u.rank=5;w.refreshStats(u);const copy=restored(w);near(copy.protossHeroes.echoes[0].damage,echo.damage);arrive(copy,.4);assert.equal(copy.protossHeroes.echoes.length,0);near(e.hp+e.shield!-copy.entities.get(e.id)!.hp-copy.entities.get(e.id)!.shield!,echo.damage);assert.equal(copy.entities.get(u.id)!.protossCombat!.cycles,4);});
for(const invalid of ['dead','far','hidden','source-dead'] as const)test(`P3C Zeratul echo cancels ${invalid} target/source without spending damage twice`,()=>{const {w,u}=setup('zeratul'),e=foe(w);protossState(u).cycles=3;protossState(u).lastFire=w.time;w.fire(u,e);settleWeaponFlights(w);const hp=e.hp;if(invalid==='dead')e.hp=0;if(invalid==='far')e.x=100;if(invalid==='hidden')e.cloaked=true;if(invalid==='source-dead')u.hp=0;arrive(w,.4);near(e.hp,invalid==='dead'?0:hp);assert.equal(w.protossHeroes.echoes.length,0);});
test('P3C Zeratul skill requires visibility, frozen fixed damage kills genuine Boss and caps two neighbors',()=>{const s=setup('zeratul'),{w,u}=s;w.stage=12;w.difficulty='easy';const b=w.spawnSpecial('ravager','boss',{x:1.5,z:0})!;const a=foe(w,1.5,.3),c=foe(w,1.5,-.3),d=foe(w,1.8,.3);w.hash.rebuild(w.entities.values());assert.equal(b.hp,9000);cast(s);arrive(w,.24);assert.equal(b.hp,9000);arrive(w,.01);assert.equal(b.hp,0);assert.equal([a,c,d].filter(e=>e.hp<1e6).length,2);assert.equal(w.stats.shots,0);});

test('P3C Alarak power comes from every third elite primary and caps at twenty without healing or changing clocks',()=>{const {w,u}=setup('alarak'),e=foe(w);e.enemyTier='boss';u.hp-=100;u.shield!-=50;u.nextShotAt=91;for(let i=0;i<65;i++){w.fire(u,e);const clock=u.nextShotAt;settleWeaponFlights(w);near(u.nextShotAt,clock);}u.nextShotAt=91;w.refreshStats(u);assert.equal(protossState(u).power,20);near(u.weaponDamage,1600);near(u.armor,20);near(u.maxHp-u.hp,100);near(u.maxShield!-u.shield!,50);near(u.nextShotAt,91);const copy=restored(w);assert.equal(copy.entities.get(u.id)!.protossCombat!.power,20);});
test('P3C Alarak death power excludes friendly, far and structure deaths and does not sacrifice paid bodies',()=>{const {w,u}=setup('alarak',1,false);const nearEnemy=foe(w),far=foe(w,50),structure=foe(w,2);structure.attributes=['Structure'];const ally=w.addUnit('zealot','terran',1,1),wallet=structuredClone(w.wallet);w.hit(nearEnemy,2e6,[],1,'terran',0,1,u.id);w.hit(far,2e6,[],1,'terran',0,1,u.id);w.hit(structure,2e6,[],1,'terran',0,1,u.id);w.hit(ally,2e6,[],1,'zerg',0,1,far.id);assert.equal(protossState(u).power,1);assert.deepEqual(w.wallet,wallet);});
test('P3C Fenix fourth primary adds one 250% solar area and cannot recursively trigger',()=>{const {w,u}=setup('fenix'),e=foe(w,4),nearby=foe(w,4,2),outside=foe(w,10);for(let i=0;i<4;i++){w.fire(u,e);settleWeaponFlights(w);}near(1e6-e.hp,u.weaponDamage*6.5);near(1e6-nearby.hp,u.weaponDamage*2.5);near(outside.hp,1e6);assert.equal(protossState(u).cycles,4);});
test('P3C Fenix real shield break restores sixty percent, speeds once and preserves damage clocks through save',()=>{const {w,u}=setup('fenix'),e=foe(w,4);u.nextShotAt=8;w.hit(u,u.maxShield!+100,[],1,'zerg',0,1,e.id);near(u.shield!,7200);near(u.attackPeriod,.125);near(u.nextShotAt,8);near(protossState(u).overdriveNext,20);w.hit(u,8000,[],1,'zerg',0,1,e.id);near(u.shield!,0);const copy=restored(w),same=copy.entities.get(u.id)!;near(same.attackPeriod,.125);copy.time=6;copy.refreshStats(same);near(same.attackPeriod,.25);copy.time=20;same.shield=1;copy.hit(same,2,[],1,'zerg',0,1,e.id);near(same.shield!,7200);});
test('P3C Fenix lethal overflow never revives and shield spending never triggers overdrive',()=>{const {w,u}=setup('fenix'),e=foe(w);u.shield=0;w.refreshStats(u);near(protossState(u).overdriveUntil,0);u.shield=1;w.hit(u,1e6,[],1,'zerg',0,1,e.id);near(u.hp,0);near(u.shield!,0);near(protossState(u).overdriveUntil,0);});

test('P3C Vorazun six-second veil respects combat episodes, firing and stat refresh without removing innate cloak',()=>{const {w,u}=setup('vorazun',1,false),a=w.addUnit('zealot','terran',1,0),worker=Object.assign(w.addUnit('stalker','terran',1,1),{unitType:'probe' as never});w.time=3;tickProtossHero(w,a,0);tickProtossHero(w,worker,0);assert.equal(a.cloaked,true);assert.equal(!!worker.cloaked,false);w.refreshStats(a);assert.equal(a.cloaked,true);w.time=9;tickProtossHero(w,a,0);assert.equal(a.cloaked,false);w.time=20;tickProtossHero(w,a,0);assert.equal(a.cloaked,false,'one veil per episode');a.lastDamagedAt=20;tickProtossHero(w,a,0);w.time=22;tickProtossHero(w,a,0);assert.equal(a.cloaked,true);const e=foe(w);w.fire(a,e);assert.equal(a.cloaked,false);w.fire(u,e);assert.equal(u.cloaked,true);});
for(const rank of [1,5])test(`P3C Vorazun ${rank}: ordinary timed stop and Boss/lord only slow, never deal fake damage`,()=>{const s=setup('vorazun',rank),{w}=s,ordinary=foe(w,3),boss=foe(w,3,1),lord=foe(w,3,-1);boss.enemyTier='boss';lord.enemyTier='lord';cast(s);arrive(w,.25);near(ordinary.stoppedUntil!,w.time+(rank===1?4.5:6.5));assert.equal(boss.stoppedUntil,undefined);near(boss.attackSlowFactor!,rank===1?.45:.65);near(lord.moveSlowFactor!,rank===1?.45:.65);near(w.stats.damage,0);});
test('P3C Vorazun controlled-target multiplier checks actual status, excluding aura-only slows',()=>{const {w,u}=setup('vorazun',1,false),e=foe(w);w.fire(u,e);settleWeaponFlights(w);near(1e6-e.hp,550);e.stoppedUntil=w.time+6;const before=e.hp;w.fire(u,e);settleWeaponFlights(w);near(before-e.hp,1375);});

test('P3C Flagship twelve real children fire saved packets, retain paid losses and never refill on reload',()=>{const {w,u}=setup('purifier_flagship',3),e=foe(w,1);initializeCarrierSubsystem(w);const children=ownedInterceptors(w,u.id);assert.equal(children.length,12);const c=children[0];c.x=c.z=0;w.fire(u,e);near(e.hp,1e6);w.fire(c,e);near(e.hp,1e6);assert.equal(w.heroAttacks.packets.length,1);const packet=w.heroAttacks.packets[0];assert.equal(packet.source.id,c.id);near(packet.damage,382.5);const copy=restored(w);initializeCarrierSubsystem(copy);assert.equal(ownedInterceptors(copy,u.id).length,12);arrive(copy,.15);near(copy.entities.get(e.id)!.hp,1e6-382.5);arrive(copy,1);near(copy.entities.get(e.id)!.hp,1e6-382.5);children[1].hp=0;const lost=restored(w);initializeCarrierSubsystem(lost);assert.equal(ownedInterceptors(lost,u.id).length,11);lost.wallet.minerals=15;lost.paused=false;tickCarrierSubsystem(lost,1);near(lost.wallet.minerals,0);const paid=restored(lost);paid.paused=false;tickCarrierSubsystem(paid,8);assert.equal(ownedInterceptors(paid,u.id).length,12);near(paid.wallet.minerals,0);assert.equal(paid.entities.get(u.id)!.carrierHangar!.job,null);});
test('P3C Flagship damage overdrive inherits rank and aura once; mother death retires children and unfinished work',()=>{const {w,u}=setup('purifier_flagship',1,false);initializeCarrierSubsystem(w);const c=ownedInterceptors(w,u.id)[0],e=foe(w);refreshInterceptorStats(w,c);near(c.weaponDamage,325);near(c.attackPeriod,.4/1.5);w.hit(u,100,[],1,'zerg',0,1,e.id);refreshInterceptorStats(w,c);near(c.attackPeriod,.4/1.5/2);const next=protossState(u).overdriveNext;w.hit(u,100,[],1,'zerg',0,1,e.id);near(protossState(u).overdriveNext,next);u.hp=0;cleanupCarrierSummons(w);assert.equal(ownedInterceptors(w,u.id).length,0);});

test('P3C six actual auras exclude workers, enter/leave without restoring damage and propagate once through mother',()=>{const {w,u}=setup('artanis',1,false),a=w.addUnit('stalker','terran',2,0),worker=Object.assign(w.addUnit('stalker','terran',1,0),{unitType:'probe' as never});refreshGroundHeroBuffs(w);near(protossShieldArmor(w,a),10);near(a.shieldArmor!,10);near(protossShieldArmor(w,worker),0);near(protossIncomingFactor(w,a),.6);a.shield!-=20;a.x=100;refreshGroundHeroBuffs(w);near(a.shieldArmor!,0);near(a.maxShield!-a.shield!,20/1.6);near(protossIncomingFactor(w,a),1);const z=setup('zeratul',1,false),ze=foe(z.w);near(heroWeaponVulnerability(z.w,ze),1.6);const al=setup('alarak',1,false),ae=foe(al.w);near(heroGroundSuppression(al.w,ae),.45);const v=setup('vorazun',1,false),ve=foe(v.w);near(heroGroundSlow(v.w,ve),.5);const f=setup('fenix',1,false),tank=f.w.addUnit('tank','terran',1,0);near(groundHeroBuff(f.w,tank).damage,.6);near(groundHeroBuff(f.w,f.w.addUnit('zealot','terran',1,1)).damage,0);});

test('P3C schema19 freezes pause and rejects malformed counters/duplicate receipts atomically',()=>{const s=setup('zeratul'),{w,u}=s,e=foe(w);protossState(u).cycles=3;protossState(u).lastFire=0;w.fire(u,e);settleWeaponFlights(w);assert.equal(w.captureRun().schema,RUN_SCHEMA);const before=w.captureRun();for(const mutate of [(r:any)=>r.state.entities.get(u.id).protossCombat.power=21,(r:any)=>r.state.entities.get(u.id).protossCombat.cycles=NaN,(r:any)=>r.state.protossHeroes.echoes.push(structuredClone(r.state.protossHeroes.echoes[0])),(r:any)=>r.state.protossHeroes.echoes[0].damage=Infinity]){const bad=structuredClone(before);mutate(bad);assert.throws(()=>w.restoreRun(bad));assert.deepEqual(w.captureRun(),before);}w.paused=true;const time=w.time;w.step();near(w.time,time);assert.equal(w.protossHeroes.echoes.length,1);});
