import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {World} from '../src/simulation/world';
import {initializeCarrierSubsystem,ownedInterceptors} from '../src/simulation/combat/carriers';
import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';
import {ProtossHeroEffects} from '../src/render/effects/protoss-hero-effects';
import {fleetPhase,fleetChildPoint,trailOpacity,PROTOSS_PRESENTATION} from '../src/render/effects/protoss-hero-presentation';
function setup(){const w=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[]});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();for(const p of Object.values(w.expedition.production))p.enabled={};w.acquireHero('purifier_flagship');const u=w.heroEntity('purifier_flagship')!;u.x=u.z=0;initializeCarrierSubsystem(w);const e=w.addUnit('roach','zerg',9,0);e.hp=e.maxHp=1e6;w.hash.rebuild(w.entities.values());assert.ok(w.castHero('purifier_flagship'));const view={scene:new THREE.Scene(),camera:new THREE.PerspectiveCamera(),gpu:new Map(),fx:{heroQuality:'full'}};const fx=new ProtossHeroEffects(view as any,w);fx.beginFrame();return {w,u,e,fx,c:w.heroCasts[0],children:ownedInterceptors(w,u.id)};}
test('Fleet formation is a read-only view of the twelve actual paid child identities',()=>{const {w,fx,c,children}=setup();const before=w.captureRun();w.time=.75;fx.beginFrame();const state=w.captureRun(),poses=children.map(a=>fx.childPresentation(a));assert.equal(poses.length,12);assert.ok(poses.every(p=>p&&p.modelKey==='elite.carrier.1'));assert.equal(new Set(poses.map(p=>[p!.point.x,p!.point.y,p!.point.z].join(','))).size,12);assert.deepEqual(w.captureRun(),state);assert.equal(w.nextId,before.state.nextId);assert.equal(w.heroCasts[0].id,c.id);assert.equal(w.heroCasts[0].damage,c.damage);});
test('Lost children cannot create formation bodies, charge anchors or replacements on restored casts',()=>{const {w,fx,children}=setup();children[2].hp=0;const before=w.captureRun();fx.beginFrame();assert.equal(fx.childPresentation(children[2]),null);assert.equal(fx.report().fleet.children.length,11);const copy=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[]});copy.restoreRun(before);const other=new ProtossHeroEffects({scene:new THREE.Scene(),camera:new THREE.PerspectiveCamera(),gpu:new Map(),fx:{heroQuality:'full'}} as any,copy);other.beginFrame();assert.deepEqual(other.report().fleet.children,fx.report().fleet.children);assert.equal(copy.nextId,w.nextId);assert.equal(ownedInterceptors(copy,children[0].summonOwnerId!).length,11);});
test('Gather and combined beam follow the actual moving mother without moving combat children',()=>{const {w,u,fx,children}=setup();w.time=.8;fx.beginFrame();const start=fx.childPresentation(children[0])!.point;const childBefore=structuredClone(children[0]);u.x+=3;const before=w.captureRun();fx.beginFrame();const moved=fx.childPresentation(children[0])!.point;assert.ok(Math.abs(moved.x-start.x-3)<1e-9);assert.ok(Math.abs(moved.z-start.z)<1e-9);assert.deepEqual(children[0],childBefore);assert.deepEqual(w.captureRun(),before);});
test('Fleet release is finite and source death removes all orphaned presentation anchors',()=>{const {w,u,c,fx,children}=setup();w.time=c.at;fx.beginFrame();resolveExpeditionHeroCasts(w);fx.beginFrame();assert.equal(w.heroCasts.length,0);assert.equal(fx.report().fleet.children.length,12);w.time=c.at+PROTOSS_PRESENTATION.fleetRelease+.01;fx.beginFrame();assert.equal(fx.childPresentation(children[0]),null);assert.deepEqual(fx.report().fleet.children,[]);const second=setup();second.u.hp=0;second.fx.beginFrame();assert.deepEqual(second.fx.report().fleet.children,[]);assert.equal(second.fx.childPresentation(second.children[0]),null);});
test('Restore/reset clears completed release trails rather than replaying damage or an old beam',()=>{const {w,c,fx}=setup();w.time=c.at;fx.beginFrame();resolveExpeditionHeroCasts(w);fx.beginFrame();assert.equal(fx.report().fleet.children.length,12);const saved=w.captureRun(),hp=w.entities.get(c.target)!.hp;w.restoreRun(saved);fx.reset();fx.beginFrame();assert.deepEqual(fx.report().fleet.children,[]);assert.equal(w.entities.get(c.target)!.hp,hp);assert.equal(w.heroCasts.length,0);});
test('Charge/beam phases respect frozen skill timestamps including a mid-charge restoration',()=>{const c={beganAt:20,at:21.4};assert.equal(fleetPhase(20.7,c.beganAt,c.at).beam,false);assert.equal(fleetPhase(21.2,c.beganAt,c.at).beam,true);assert.equal(fleetPhase(21.6,c.beganAt,c.at).beam,true);assert.equal(fleetPhase(22.2,c.beganAt,c.at).expired,true);assert.deepEqual(fleetPhase(20.8,20,21.4),fleetPhase(20.8,structuredClone(c).beganAt,structuredClone(c).at));});
test('Afterimages fade to zero without accepting future or negative-age presentation',()=>{assert.equal(trailOpacity(10,10.1,.95),0);assert.equal(trailOpacity(10,10,.95),1);assert.ok(trailOpacity(10.4,10,.95)>trailOpacity(10.8,10,.95));assert.equal(trailOpacity(11,10,.95),0);});
test('The formation interpolates toward a legal display slot while preserving frozen combat target',()=>{const {c,children}=setup();const before=structuredClone(c),child=structuredClone(children[0]);const a=fleetChildPoint(c,children[0],0,c.beganAt!),b=fleetChildPoint(c,children[0],0,c.beganAt!+.6);assert.equal(a.point.x,children[0].x);assert.equal(a.point.z,children[0].z);assert.ok([b.point.x,b.point.y,b.point.z,b.facing].every(Number.isFinite));assert.deepEqual(c,before);assert.deepEqual(children[0],child);});
