import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world.ts';
import {rewardPool} from '../src/simulation/progression/rewards.ts';
const world=()=>{const w=new World({waves:false});w.start();w.wallet={minerals:5000,gas:5000};return w;};
test('building round shows only unlocked types, permits repeated Barracks and freezes all clocks',()=>{const w=world();w.endStage();assert.deepEqual(w.rewards.map(r=>r.id),['research.marauder','build.barracks','build.factory']);const first=w.buildingsOf('barracks')[0],before={...w.wallet},offer=w.rewards.find(r=>r.id==='build.barracks')!,price=offer.minerals;assert.ok(w.choose(offer.offerId));assert.equal(w.rewardRound,'building');assert.equal(w.wallet.minerals,before.minerals-price);assert.equal(w.buildingsOf('barracks').length,2);const second=w.buildingsOf('barracks')[1];assert.notEqual(first.id,second.id);assert.equal(second.remaining,0);const snapshot=JSON.stringify({wallet:w.wallet,time:w.time,buildings:[...w.buildings.values()]});w.advance(30);assert.equal(JSON.stringify({wallet:w.wallet,time:w.time,buildings:[...w.buildings.values()]}),snapshot);assert.equal(w.choose(offer.offerId),false);w.skipReward();assert.ok(w.rewards.every(r=>r.kind!=='build'));assert.equal(new Set(w.rewards.map(r=>r.id)).size,3);assert.equal(w.choose('build.barracks'),false);w.skipReward();w.endStage();assert.deepEqual(w.rewards.map(r=>r.id),['research.marauder','build.barracks','build.factory']);});
test('reroll cost spans rounds, building types stay fixed but actual price changes',()=>{const w=world();w.endStage();w.random=()=>0;const old=w.rewards.map(r=>r.minerals),m=w.wallet.minerals;assert.ok(w.reroll());assert.deepEqual(w.rewards.map(r=>r.id),['research.marauder','build.barracks','build.factory']);assert.notDeepEqual(w.rewards.map(r=>r.minerals),old);assert.equal(w.wallet.minerals,m-50);w.skipReward();assert.equal(w.rerollCost(),90);const ids=w.rewards.map(r=>r.id).sort();assert.ok(w.reroll());assert.equal(w.wallet.minerals,m-140);assert.notDeepEqual(w.rewards.map(r=>r.id).sort(),ids);w.skipReward();assert.equal(w.rerollCost(),50);});
test('same-type factories share one paid batch and one pod',()=>{const w=world();w.buildings.clear();const a=w.addBuilding('factory',0),b=w.addBuilding('factory',0);a.techLab=b.techLab=true;w.wallet={minerals:300,gas:250};w.updateProduction(0);assert.equal(a.queue[0].unitType,'tank');assert.equal(b.queue[0].unitType,'tank');assert.equal(a.queue[0].id,b.queue[0].id);assert.deepEqual(w.wallet,{minerals:0,gas:0});w.updateProduction(40);assert.equal(w.pods.filter(p=>p.unitType==='tank').length,1);assert.equal(w.pods[0].passengers.length,2);assert.equal(w.allies().length,1);});
test('capacity across multiple buildings, paid pods and extra cards cannot exceed 25',()=>{const w=world();w.buildings.clear();for(let i=0;i<4;i++)w.addUnit('marine','terran',0,0,5);for(let i=0;i<8;i++)w.addBuilding('barracks',0);w.updateProduction(0);assert.equal([...w.buildings.values()].reduce((n,b)=>n+b.queue.length,0),4);assert.equal(w.capacity('marine'),false);const m=w.wallet.minerals;w.updateProduction(20);assert.equal(w.wallet.minerals,m);assert.equal(w.pods.length,1);assert.equal(w.pods[0].passengers.length,4);});
test('duplicate buildings wait for one full group payment',()=>{const w=world();w.buildings.clear();const a=w.addBuilding('barracks'),b=w.addBuilding('barracks');w.wallet={minerals:50,gas:0};w.updateProduction(0);assert.equal(a.queue.length,0);assert.equal(b.queue.length,0);assert.equal(w.wallet.minerals,50);w.wallet.minerals=100;w.updateProduction(0);assert.equal(a.queue[0].quantity,2);assert.equal(b.queue[0].id,a.queue[0].id);assert.equal(w.wallet.minerals,0);});
test('failed final hive objective grants no clear reward; success pays exactly once',()=>{for(const win of [false,true]){const w=world();w.stage=12;w.prepareStage();if(win)w.hive!.hp=0;const before={...w.wallet};w.endStage();assert.equal(w.phase,win?'won':'lost');if(win){assert.equal(w.wallet.minerals-before.minerals,w.config.reward[0]);assert.equal(w.clearReceipt?.stage,12);}else assert.deepEqual(w.wallet,before);const after={...w.wallet};w.endStage();assert.deepEqual(w.wallet,after);}});
test('extra reinforcement occupies capacity between card payment and next-stage landing',()=>{const w=world();w.endStage();w.skipReward();for(let i=0;i<4;i++)w.addUnit('marine','terran',0,0,5);w.allies()[0].rank=3;w.refreshStats(w.allies()[0]);const card=rewardPool().find(r=>r.id==='train.marine')!;w.rewards=[card];assert.ok(w.capacity('marine'));w.choose(card.offerId);assert.equal(w.capacity('marine'),false);assert.equal(w.pods.length,0);w.skipReward();assert.equal(w.pods.length,1);assert.equal(w.allies().length,5);});

test('all displayed offers may be bought; reroll creates fresh identities and positive resource payouts remain immediate',()=>{const w=world();w.endStage();w.skipReward();w.rewards=rewardPool().filter(r=>r.kind==='economy').slice(0,3);const before={...w.wallet},ids=w.rewards.map(r=>r.offerId);for(const id of ids)assert.ok(w.choose(id));assert.equal(w.phase,'reward');assert.equal(w.rewardRound,'random');assert.deepEqual(w.wallet,{minerals:before.minerals-100+175,gas:before.gas+75});for(const id of ids)assert.equal(w.choose(id),false);assert.ok(w.reroll());assert.ok(w.rewards.every(r=>!ids.includes(r.offerId)));assert.equal(w.rerollCost(),90);assert.equal(w.choose(ids[0]),false);w.skipReward();assert.equal(w.stage,2);});
test('repeat building offers after refresh have independent identity and do not change unbought prices',()=>{const w=world();w.stage=2;w.endStage();const a=w.rewards.find(r=>r.id==='build.barracks')!,b=w.rewards.find(r=>r.id==='build.factory')!;const other={...b};assert.ok(w.choose(a.offerId));assert.deepEqual(b,other);assert.ok(w.reroll());assert.ok(w.choose(w.rewards.find(r=>r.id===a.id)!.offerId));assert.equal(w.buildingsOf('barracks').length,3);assert.equal(w.rewardRound,'building');w.skipReward();assert.equal(w.rerollCost(),90);assert.ok(w.reroll());assert.equal(w.rerollCost(),130);});
