import test from 'node:test';
import assert from 'node:assert/strict';
import { canAfford, spend, purchaseBuilding, startTraining, tickProduction, applyWeaponHit, tryFire, healBiological, drawThree, rerollThree, claimOne } from '../src/simulation/rules.mjs';
// Synthetic fixtures. They are deliberately NOT named Marine/Zergling or claimed to be SC2 stats.
const wallet = () => ({ minerals: 1000, gas: 1000 });
const buildingDef = { id: 'test-factory', cost: { minerals: 120, gas: 40 }, buildSeconds: 5, supportedTypes: ['test-unit'] };
const unitDef = { id: 'test-unit', cost: { minerals: 20, gas: 2 }, trainSeconds: 8 };
const ready = (id = 'b1') => ({ id, type: buildingDef.id, constructionRemaining: 0, supportedTypes: ['test-unit'], job: null, sequence: 0 });
const unit = (patch = {}) => ({ id: 'target', owner: 1, hp: 100, maxHp: 100, armor: 2, attributes: ['Biological','Light'], flying: false, ...patch });
const weapon = { id: 'test-gun', damage: 12, hits: 2, minimumDamage: 0.5, period: 2, range: 5, minimumRange: 0, canMoveAndFire: false, targetLayer: 'ground', bonuses: [] };
const healRule = { hpPerSecond: 10, energyPerHp: 0.5, range: 4 };
const healer = (patch = {}) => ({ hp: 50, energy: 20, owner: 1, ...patch });
const pool = Array.from({ length: 6 }, (_, i) => ({ id: 'c'+i, level: i }));
const all = () => true;

test('spending validates both currencies and is atomic', () => { const w={minerals:500,gas:0}; assert.equal(spend(w,buildingDef.cost),false); assert.deepEqual(w,{minerals:500,gas:0}); });
test('negative cost cannot mint resources', () => assert.throws(() => spend(wallet(),{minerals:-1,gas:0})));
test('purchasing a building consumes the configured costs', () => { const w=wallet();const b=purchaseBuilding(w,buildingDef,'b1');assert.equal(w.minerals,880);assert.equal(w.gas,960);assert.equal(b.constructionRemaining,5); });
test('insufficient resources cannot construct a building', () => assert.equal(purchaseBuilding({minerals:0,gas:0},buildingDef,'b1'),null));
test('training cannot begin before building completion', () => { const b=purchaseBuilding(wallet(),buildingDef,'b');assert.equal(startTraining(b,wallet(),unitDef),false); });
test('training consumes resources once, not once per frame', () => { const w=wallet(), b=ready(); assert.equal(startTraining(b,w,unitDef),true);assert.equal(startTraining(b,w,unitDef),false);tickProduction([b],3,0);assert.deepEqual(w,{minerals:980,gas:998}); });
test('full unit capacity pauses new production without charging', () => { const w=wallet();assert.equal(startTraining(ready(),w,unitDef,false),false);assert.deepEqual(w,wallet()); });
test('unsupported unit types cannot be trained', () => assert.equal(startTraining(ready(),wallet(),{...unitDef,id:'other'}),false));
test('exactly one pod event per completed paid job', () => { const b=ready();startTraining(b,wallet(),unitDef);assert.equal(tickProduction([b],7,0).length,0);const events=tickProduction([b],1,7);assert.equal(events.length,1);assert.equal(events[0].producedAt,8);assert.equal(tickProduction([b],100,8).length,0); });
test('each building has an independent production timer', () => { const a=ready('a'),b=ready('b');startTraining(a,wallet(),unitDef);startTraining(b,wallet(),{...unitDef,trainSeconds:12});assert.equal(tickProduction([a,b],8,0).length,1);assert.equal(b.job.remaining,4);assert.equal(tickProduction([a,b],4,8).length,1); });
test('menus pause production', () => { const b=ready();startTraining(b,wallet(),unitDef);assert.deepEqual(tickProduction([b],60,0,true),[]);assert.equal(b.job.remaining,8); });
test('large step preserves production completion timestamp', () => { const b=ready();startTraining(b,wallet(),unitDef);assert.equal(tickProduction([b],20,40)[0].producedAt,48); });
test('new jobs use distinct pod IDs', () => {const b=ready();startTraining(b,wallet(),unitDef);const a=tickProduction([b],8,0)[0];startTraining(b,wallet(),unitDef);const c=tickProduction([b],8,8)[0];assert.notEqual(a.id,c.id);});
test('armor is applied separately to each weapon hit', () => {const u=unit();assert.equal(applyWeaponHit(u,weapon).damage,20);});
test('attribute bonuses apply only to matching attributes', () => {const u=unit();assert.equal(applyWeaponHit(u,{...weapon,bonuses:[{attribute:'Light',amount:3}]}).damage,26);});
test('the unit whose HP reaches zero dies, not another lower-ranked unit', () => {const a=unit({id:'veteran',hp:5,rank:5}), b=unit({id:'rookie',rank:1});assert.equal(applyWeaponHit(a,weapon).killedId,'veteran');assert.equal(b.hp,100);});
test('weapon cooldown and target layer are enforced', () => {const s=unit({id:'s'}),t=unit();assert.ok(tryFire(s,t,weapon,0,4));assert.equal(tryFire(s,t,weapon,1,4),null);assert.ok(tryFire(s,t,weapon,2,4));assert.equal(tryFire(s,unit({flying:true}),weapon,4,4),null);});
test('moving cannot fire a weapon that requires stopping', () => assert.equal(tryFire(unit(),unit(),weapon,0,4,true),null));
test('minimum and maximum range are enforced', () => {assert.equal(tryFire(unit(),unit(),weapon,0,6),null);assert.equal(tryFire(unit(),unit(),{...weapon,minimumRange:2},0,1),null);});
test('biological healing restores HP and spends energy', () => {const h=healer(),t=unit({hp:50});assert.equal(healBiological(h,t,healRule,1,2),10);assert.equal(t.hp,60);assert.equal(h.energy,15);});
test('mechanical-only units do not receive biological healing', () => assert.equal(healBiological(healer(),unit({hp:50,attributes:['Mechanical']}),healRule,1,2),0));
test('dual biological/mechanical attributes are not mistakenly excluded', () => assert.equal(healBiological(healer(),unit({hp:50,attributes:['Mechanical','Biological']}),healRule,1,2),10));
test('healing is capped by remaining energy', () => {const h=healer({energy:1}),t=unit({hp:50});assert.equal(healBiological(h,t,healRule,1,2),2);assert.equal(h.energy,0);});
test('healing cannot resurrect or heal hostile units', () => {assert.equal(healBiological(healer(),unit({hp:0}),healRule,1,2),0);assert.equal(healBiological(healer(),unit({hp:50,owner:2}),healRule,1,2),0);});
test('three-choice offers contain three distinct eligible cards', () => {const o=drawThree(pool,c=>c.level<4,()=>0);assert.equal(o.options.length,3);assert.equal(new Set(o.options.map(c=>c.id)).size,3);});
test('reroll spends configured currency exactly once', () => {const w=wallet(),o=drawThree(pool,all,()=>0);assert.ok(rerollThree(o,pool,all,w,{minerals:30,gas:2},()=>0.9));assert.deepEqual(w,{minerals:970,gas:998});assert.equal(o.rerolls,1);});
test('unaffordable rerolls preserve both cards and wallet', () => {const w={minerals:0,gas:0},o=drawThree(pool,all);const before=structuredClone(o);assert.equal(rerollThree(o,pool,all,w,{minerals:1,gas:0}),false);assert.deepEqual(o,before);});
test('invalid replacement pool does not consume refresh resources', () => {const w=wallet(),o=drawThree(pool,all);assert.throws(()=>rerollThree(o,pool.slice(0,2),all,w,{minerals:30,gas:0}));assert.deepEqual(w,wallet());});
test('only one reward can be claimed per offer', () => {const o=drawThree(pool,all,()=>0);assert.ok(claimOne(o,'c0'));assert.equal(claimOne(o,'c1'),null);assert.equal(rerollThree(o,pool,all,wallet(),{minerals:0,gas:0}),false);});
test('invalid building definition cannot consume resources', () => { const w=wallet(); assert.throws(() => purchaseBuilding(w,{...buildingDef,supportedTypes:null},'b1')); assert.deepEqual(w,wallet()); });
