import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world.ts';
import {SC2_UNITS,HEAL,SIEGE} from '../src/data/sc2-units.ts';
import {TUNING,STAGES} from '../src/data/game.ts';
import {drawRewards,eligibleReward} from '../src/simulation/progression/rewards.ts';
import {SpatialHash} from '../src/simulation/movement/spatial-hash.ts';
import {locomote,blocked} from '../src/simulation/movement/steering.ts';
const world=(initial:any=['marine'])=>{const w=new World({waves:false,obstacles:[],initial});w.start();return w;};
const close=(a:number,b:number,eps=1e-5)=>assert.ok(Math.abs(a-b)<eps,`${a} != ${b}`);
test('a normal new run starts with exactly one Rank-1 Marine, without a fixture override',()=>{
 const w=new World();
 const roster=()=>w.allies().map(u=>({id:u.id,type:u.unitType,rank:u.rank,hp:u.hp}));
 assert.equal(w.phase,'menu');assert.equal(w.stage,1);
 assert.deepEqual(roster(),[{id:w.allies()[0].id,type:'marine',rank:1,hp:45}]);
 const initial=roster();w.start();w.advance(1);
 assert.equal(w.phase,'battle');assert.equal(w.stage,1);assert.deepEqual(roster(),initial);
});
test('fixed profile has exactly the requested eight units',()=>{assert.equal(Object.keys(SC2_UNITS).length,8);assert.equal(SC2_UNITS.tank.maxHp,175);close(SC2_UNITS.marine.movementSpeed,3.15);close(SC2_UNITS.baneling.attackDamage,16);});
test('armor and independent HP never redirect death to another soldier',()=>{const w=world(['marine','marine']);const [a,b]=w.allies();a.rank=5;a.hp=2;w.hit(a,6);assert.equal(a.hp,0);assert.equal(b.hp,45);const roach=w.addUnit('roach','zerg',1,0);w.hit(roach,6);assert.equal(roach.hp,140);});
test('Marine fire has a damage point and weapon cooldown',()=>{const w=world();const m=w.allies()[0],e=w.addUnit('roach','zerg',3,0);e.hp=e.maxHp=100000;e.weaponDamage=0;e.moveSpeed=0;m.facing=Math.PI/2;m.moveSpeed=0;w.step();assert.equal(e.hp,100000);assert.ok(m.windup>0);w.advance(.1);assert.equal(e.hp,99995);const hp=e.hp;w.advance(.3);assert.equal(e.hp,hp);w.advance(.4);assert.ok(e.hp<hp);});
test('Medivac restores HP continuously, consumes energy, and caps HP',()=>{const w=world(['marine','medivac']);const [m,h]=w.allies();h.x=m.x;h.z=m.z;m.hp=10;const energy=h.energy;w.hash.rebuild(w.entities.values());w.heal(h,.5);close(m.hp,10+HEAL.hpPerSecond*.5);assert.ok(h.energy<energy);m.hp=44;w.heal(h,1);close(m.hp,45);});
test('Medivac cannot heal mechanical, dead, or hostile units',()=>{const w=world(['marine','medivac','tank']);const [m,h,t]=w.allies();m.hp=0;t.hp=1;h.x=t.x;h.z=t.z;const e=w.addUnit('zergling','zerg',h.x,h.z);e.hp=1;w.hash.rebuild(w.entities.values());w.heal(h,1);assert.equal(t.hp,1);assert.equal(e.hp,1);assert.equal(m.hp,0);});
test('healing is limited by available energy',()=>{const w=world(['marine','medivac']);const [m,h]=w.allies();m.hp=1;h.energy=.33;w.hash.rebuild(w.entities.values());w.heal(h,.1);assert.ok(m.hp>1&&m.hp<2.3);});
test('Baneling damages multiple soldiers but cannot hit air with its explosion',()=>{const w=world(['marine','marine','medivac']);const [a,b,h]=w.allies();a.x=b.x=h.x=0;a.z=b.z=h.z=0;const e=w.addUnit('baneling','zerg',.5,0);w.hash.rebuild(w.entities.values());w.fire(e,a);assert.equal(a.hp,10);assert.equal(b.hp,10);assert.equal(h.hp,150);assert.equal(e.hp,0);});
test('Baneling can kill multiple low-health Marines',()=>{const w=world(['marine','marine']);for(const m of w.allies()){m.x=0;m.z=0;m.hp=12;}const e=w.addUnit('baneling','zerg',.5,0);w.hash.rebuild(w.entities.values());w.fire(e,w.allies()[0]);assert.equal(w.allies().length,0);});
test('Hellion hits a line of Zerglings but misses those to the side',()=>{const w=world(['hellion']);const h=w.allies()[0],a=w.addUnit('zergling','zerg',2,0),b=w.addUnit('zergling','zerg',4,0),c=w.addUnit('zergling','zerg',2,3);w.hash.rebuild(w.entities.values());w.fire(h,a);assert.equal(a.hp,21);assert.equal(b.hp,21);assert.equal(c.hp,35);});
test('Ravager bile keeps its target point when the target dodges',()=>{const w=world();const m=w.allies()[0],r=w.addUnit('ravager','zerg',8,0);w.hash.rebuild(w.entities.values());r.bileCooldown=0;w.updateBile(r,1/60);const bile=w.effects.find(f=>f.kind==='bile')!;assert.ok(bile);const location={...bile.end};m.x=10;m.z=10;assert.deepEqual(bile.end,location);assert.equal(m.hp,45);});
test('different move speeds produce different displacement',()=>{const w=world(['marine','hellion']);w.anchor.x=30;w.trail=[{x:30,z:0}];for(const u of w.allies()){u.x=0;u.z=0;u.facing=Math.PI/2;}w.advance(1);const [m,h]=w.allies();assert.ok(h.x>m.x+.5);});
test('Marine attack stops produce additional trailing',()=>{const walk=world(),fight=world();for(const w of [walk,fight])w.input.x=1;const e=fight.addUnit('roach','zerg',4,0);e.hp=e.maxHp=100000;e.weaponDamage=0;e.moveSpeed=0;walk.advance(2);fight.advance(2);assert.ok(fight.allies()[0].x<walk.allies()[0].x);});
test('Tank spends time deploying and falls behind the moving anchor',()=>{const w=world(['tank']);const t=w.allies()[0],e=w.addUnit('roach','zerg',10,0);e.moveSpeed=0;e.weaponDamage=0;w.input.x=-1;w.advance(.5);assert.equal(t.action,'sieging');assert.ok(t.modeTimer>0);assert.ok(w.maxStretch>2);assert.ok(Math.abs(t.x)<.1);});
test('Tank changes range and undeploys when threatened close up',()=>{const w=world(['tank']);const t=w.allies()[0];t.mode='siege';w.refreshStats(t);assert.equal(t.attackRange,SIEGE.range);w.addUnit('zergling','zerg',1,0);w.step();assert.equal(t.action,'unsieging');assert.ok(t.modeTimer>2);});
test('reversal preserves identity, position continuity and finite turning',()=>{const w=world(['marine','hellion','tank']);w.input.x=1;w.advance(2);const before=w.allies().map(u=>({id:u.id,x:u.x,z:u.z,f:u.facing}));w.input.x=-1;w.step();for(let i=0;i<before.length;i++){const a=w.allies()[i],b=before[i];assert.equal(a.id,b.id);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)<.13);assert.ok(Math.abs(a.facing-b.f)<.2);}});
test('hard leash adds limited speed and never teleports',()=>{const w=world();const m=w.allies()[0];m.x=-40;w.anchor.x=40;w.trail=[{x:40,z:0}];for(let i=0;i<100;i++){const old=m.x;w.step();assert.ok(Math.abs(m.x-old)<=m.moveSpeed*TUNING.catchUp/60+.001);}assert.ok(m.x<0);});
test('separation spreads close units; spatial hash only visits local buckets',()=>{const w=world(['marine','marine']);const [a,b]=w.allies();a.x=0;b.x=.2;a.z=b.z=0;w.advance(.5);assert.ok(Math.hypot(a.x-b.x,a.z-b.z)>.45);const hash=new SpatialHash();const bodies=Array.from({length:300},(_,i)=>({...a,id:i,x:i%30*5,z:Math.floor(i/30)*5}));hash.rebuild(bodies);let found=0;hash.query({x:0,z:0},2,()=>found++);assert.equal(found,1);assert.ok(hash.visits<10);});
test('insufficient resources block building and production atomically',()=>{const w=world();w.wallet={minerals:10,gas:0};assert.equal(w.build('barracks'),false);assert.equal(w.queue('marine'),false);assert.deepEqual(w.wallet,{minerals:10,gas:0});});
test('production immediately debits each queued job once',()=>{const w=world();assert.ok(w.build('barracks'));w.buildings.get('barracks')!.remaining=0;const before=w.wallet.minerals;assert.ok(w.queue('marine'));assert.ok(w.queue('marine'));assert.equal(w.wallet.minerals,before-100);assert.equal(w.buildings.get('barracks')!.queue.length,2);});
test('one production completion emits one pod and never directly adds a soldier',()=>{const w=world();w.build('barracks');w.buildings.get('barracks')!.remaining=0;w.queue('marine');const count=w.allies().length;w.updateProduction(SC2_UNITS.marine.productionTime);assert.equal(w.pods.length,1);assert.equal(w.allies().length,count);w.updateProduction(1);assert.equal(w.pods.length,1);assert.equal(w.pods[0].guardianIds.size,22);});
test('two queued jobs produce two distinct rescue events',()=>{const w=world();w.build('barracks');w.buildings.get('barracks')!.remaining=0;w.queue('marine');w.queue('marine');w.updateProduction(20);w.updateProduction(20);assert.equal(w.pods.length,2);assert.notEqual(w.pods[0].jobId,w.pods[1].jobId);});
test('pod deadline begins on landing with no activation',()=>{const w=world();w.time=10;const p=w.spawnPod('marine',{x:40,z:40});assert.equal(p.expiresAt,40);w.time=40;w.updatePods();assert.equal(p.status,'expired');assert.equal(w.stats.failed,1);assert.equal(w.allies().length,1);});
test('destroyed pod fails without refund or reinforcement',()=>{const w=world();const p=w.spawnPod('marine',{x:40,z:40});const before={...w.wallet};p.hp=0;w.updatePods();assert.equal(p.status,'destroyed');assert.deepEqual(w.wallet,before);assert.equal(w.allies().length,1);});
test('clearing threats before timeout spawns a recruit at the pod',()=>{const w=world();const p=w.spawnPod('marine',{x:30,z:0});for(const id of p.guardianIds)w.entities.get(id)!.hp=0;w.hash.rebuild(w.entities.values());w.updatePods();assert.equal(p.status,'rescued');assert.equal(w.allies().length,2);assert.equal(w.entities.get(p.recruitId!)!.x,30);w.updatePods();assert.equal(w.allies().length,2);});
test('deadline takes priority over simultaneous threat clear',()=>{const w=world();const p=w.spawnPod('marine',{x:30,z:0});for(const id of p.guardianIds)w.entities.get(id)!.hp=0;w.time=p.expiresAt;w.updatePods();assert.equal(p.status,'expired');});
test('full roster promotes the lowest rank, never exceeds five soldiers or ranks',()=>{const w=world(['marine','marine','marine','marine','marine']);for(let i=0;i<21;i++)w.reinforce('marine',{x:20,z:20});assert.deepEqual(w.allies().map(u=>u.rank),[5,5,5,5,5]);});
test('a dead soldier is replaced by a new identity at rank one',()=>{const w=world(['marine','marine','marine','marine','marine']);const old=w.allies()[0];old.rank=5;w.hit(old,1000);const recruit=w.reinforce('marine',{x:20,z:20});assert.notEqual(recruit.id,old.id);assert.equal(recruit.rank,1);assert.equal(old.hp,0);});
test('all clocks freeze during reward and explicit pause',()=>{const w=world();const p=w.spawnPod('marine',{x:30,z:0});w.endStage();const t=w.time;w.advance(40);assert.equal(w.time,t);assert.equal(p.status,'active');w.phase='battle';w.paused=true;w.advance(40);assert.equal(w.time,t);});
test('12 stages retain 60 simulation seconds each',()=>{assert.equal(STAGES.length,12);const w=world();for(let stage=1;stage<=12;stage++){w.wallet={minerals:0,gas:0};if(stage===12){assert.ok(w.hive);w.hit(w.hive!,3000);}w.advance(59);assert.equal(w.phase,'battle');w.advance(1);close(w.time,stage*60);if(stage<12){assert.equal(w.phase,'reward');assert.ok(w.choose(w.rewards[0].id));}else assert.equal(w.phase,'won');}});
test('three distinct rewards allow only one claim per stage',()=>{const w=world();w.endStage();assert.equal(new Set(w.rewards.map(r=>r.id)).size,3);const r=w.rewards[0];assert.ok(w.choose(r.id));assert.equal(w.choose(r.id),false);assert.equal(w.stage,2);});
test('reroll costs 50 then 75 and changes the combination',()=>{const w=world();w.endStage();const old=w.rewards.map(r=>r.id).sort(),before=w.wallet.minerals;assert.ok(w.reroll());assert.equal(w.wallet.minerals,before-50);assert.notDeepEqual(w.rewards.map(r=>r.id).sort(),old);w.reroll();assert.equal(w.wallet.minerals,before-125);});
test('unaffordable reroll preserves cards and resources',()=>{const w=world();w.endStage();w.wallet.minerals=49;const old=w.rewards;assert.equal(w.reroll(),false);assert.equal(w.rewards,old);assert.equal(w.wallet.minerals,49);});
test('fallback pool permits a changed draw with deterministic RNG',()=>{const w=world();w.wallet={minerals:0,gas:0};const a=drawRewards(w,()=>0),b=drawRewards(w,()=>0,a.map(r=>r.id));assert.notDeepEqual(a,b);assert.equal(b.length,3);});
test('Stim consumes HP without killing a Marine at ten HP',()=>{const w=world(['marine','marine']);w.upgrades.set('stim',1);const [a,b]=w.allies();a.hp=10;assert.ok(w.stim());assert.equal(a.hp,10);assert.equal(b.hp,35);assert.equal(b.stimUntil,11);});
test('a firing vehicle completes its turn instead of cancelling against formation steering',()=>{const w=world(['hellion']);const h=w.allies()[0];h.facing=-Math.PI/2;const e=w.addUnit('roach','zerg',3,0);e.moveSpeed=0;e.weaponDamage=0;w.advance(2);assert.ok(e.hp<145);});
test('Medivac seeks an injured biological ally beyond current heal range',()=>{const w=world(['marine','medivac']);const [m,h]=w.allies();m.hp=10;m.x=5;m.moveSpeed=0;h.x=-5;h.z=0;w.hash.rebuild(w.entities.values());const patient=w.heal(h,1/60);assert.equal(patient?.id,m.id);assert.equal(m.hp,10);w.advance(1);assert.ok(h.x>-4);});
test('stage one teaches a coherent approach; stage two introduces opposing waves',()=>{const w=world();w.spawnWave();let enemies=[...w.entities.values()].filter(u=>u.owner==='zerg');assert.ok(enemies.every(e=>e.x>20));w.entities.clear();w.stage=2;w.spawnWave();enemies=[...w.entities.values()].filter(u=>u.owner==='zerg');assert.ok(enemies.some(e=>e.x>20)&&enemies.some(e=>e.x< -20));});
test('Tank formation goal leaves room behind the infantry firing line',()=>{const w=world(['marine','tank']);const [m,t]=w.allies();assert.ok(w.moveGoal(m).x-w.moveGoal(t).x>5);});
test('new recruits reuse vacant slots without reordering surviving soldiers',()=>{const w=world(['marine','marine','marine']);const [a,b,c]=w.allies();w.hit(b,1000);const next=w.reinforce('marine',{x:3,z:3});assert.equal(next.slot,1);assert.equal(a.slot,0);assert.equal(c.slot,2);});

test('idle anchor still allows formation adjustment between shots',()=>{const w=world();const m=w.allies()[0],e=w.addUnit('roach','zerg',4,0);e.moveSpeed=0;e.weaponDamage=0;m.weaponCooldown=.5;w.hash.rebuild(w.entities.values());const x=m.x;w.advance(.2);assert.notEqual(m.x,x);assert.ok(e.hp===145);});

test('vehicle separation never exceeds its movement speed cap',()=>{const w=world(['hellion']);const h=w.allies()[0];h.facing=Math.PI/2;for(let i=0;i<60;i++)locomote(h,{x:40,z:0},h.moveSpeed,{x:3,z:0},1/60,[]);assert.ok(Math.hypot(h.velocity.x,h.velocity.z)<=h.moveSpeed+1e-8);});

test('Baneling structure damage ignores armor in the locked profile',()=>{const w=world();const p=w.spawnPod('marine',{x:20,z:0});p.armor=9;const b=w.addUnit('baneling','zerg',20.5,0);w.hash.rebuild([...w.entities.values(),p]);w.fire(b,p);assert.equal(p.hp,p.maxHp-80);});

test('discounted production cards display the same cost that is charged',()=>{const w=world();w.build('barracks');w.buildings.get('barracks')!.remaining=0;w.upgrades.set('discount',1);const rewards=drawRewards(w,()=>0);const card=rewards.find(r=>r.id==='train.marine')!;assert.ok(card);assert.equal(card.minerals,43);const before=w.wallet.minerals;w.queue('marine');assert.equal(before-w.wallet.minerals,card.minerals);});

test('rerolled cards remain affordable after the refresh fee has been charged',()=>{const w=world();w.wallet={minerals:100,gas:100};w.endStage();w.random=()=>0;assert.ok(w.reroll());assert.equal(w.wallet.minerals,50);assert.ok(w.rewards.every(r=>eligibleReward(w,r)));});

test('hard leash prioritizes return but preserves close self-defense',()=>{const w=world();const m=w.allies()[0];w.anchor.x=30;w.trail=[{x:30,z:0}];m.x=0;m.facing=Math.PI/2;const e=w.addUnit('roach','zerg',1.5,0);e.moveSpeed=0;e.weaponDamage=0;w.advance(.3);assert.ok(e.hp<145);assert.ok(m.x<2);});

test('cached corner routing preserves collision and gets a soldier around a wall',()=>{const w=new World({waves:false,initial:['marine'],obstacles:[{x:4,z:0,w:2,h:8}]});w.start();const m=w.allies()[0];w.anchor.x=12;w.trail=[{x:12,z:0}];for(let i=0;i<600;i++){w.step();assert.ok(!(Math.abs(m.x-4)<1+m.unitRadius&&Math.abs(m.z)<4+m.unitRadius));}assert.ok(m.x>7);});

test('rescue guardians spawn outside adjacent solid terrain',()=>{const w=new World({waves:false,initial:[],obstacles:[{x:4,z:0,w:2,h:20}]});const pod=w.spawnPod('marine',{x:0,z:0});for(const id of pod.guardianIds){const e=w.entities.get(id)!;assert.equal(blocked(e,e.unitRadius,w.obstacles),false);}});
