import {test} from 'node:test';
import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';
import {SC2_UNITS,HEAL,TERRAN,SIEGE} from '../src/data/sc2-units';
import {TUNING} from '../src/data/game';
import {STAGES,stageConfig,stageSchedule,seeded} from '../src/data/stages';
import {RARITIES,rollRarity,MAP_REWARDS} from '../src/data/rewards';
import {rewardPool,drawRewards,drawReward,eligibleReward} from '../src/simulation/progression/rewards';
import {distance,clearLine} from '../src/simulation/movement/steering';
const close=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const setup=()=>{const w=new World({sandbox:true,waves:false,obstacles:[]});w.start();w.addBuilding('barracks',0);w.wallet={minerals:5000,gas:5000};return w;};
const card=(id:string,w:World)=>rewardPool(w).find(r=>r.id===id)!;
const buy=(w:World,id:string)=>{w.phase='reward';w.rewardRound='random';w.rewardClaimed=false;const r=card(id,w);assert.ok(r,id);w.rewards=[r];assert.ok(w.choose(r.offerId),id);return r;};

test('each three-stage block lasts 1/2/3/4 minutes; all seeded events fit without deleting budgets',()=>{
 assert.deepEqual(STAGES.map(s=>s.durationSeconds),[60,60,60,120,120,120,180,180,180,240,240,240]);
 assert.equal(STAGES.reduce((n,s)=>n+s.durationSeconds,0),1800);
 for(const d of ['easy','normal'] as const)for(let stage=1;stage<=12;stage++)for(let seed=0;seed<25;seed++){const c=stageConfig(stage,d),plan=stageSchedule(c,seed);assert.ok([...plan.waves,...plan.events].every(e=>e.at>0&&e.at<c.durationSeconds));assert.equal(plan.waves.reduce((n,w)=>n+w.types.length,0),Object.values(c.ambient).reduce((a,b)=>a+b,0));}
});
test('late SCV egg carries its own deadline through the shorter intermission',()=>{const w=setup();w.advance(45);const e=w.spawnEconomic('egg',{x:30,z:30});w.advance(15);assert.equal(w.phase,'reward');const deadline=e.expiresAt;w.advance(200);assert.equal(e.expiresAt,deadline);assert.equal(e.status,'active');w.skipReward();w.skipReward();w.advance(14);assert.equal(e.status,'active');w.advance(1);assert.equal(e.status,'expired');assert.equal(w.stats.scvsLost,1);});
test('models and collision footprints share 80 percent scale without changing SC2 movement or weapon data',()=>{const w=setup();for(const type of TERRAN){const u=w.addUnit(type,'terran',0,0);close(u.unitRadius,SC2_UNITS[type].unitRadius*.8);close(u.moveSpeed,SC2_UNITS[type].movementSpeed);close(u.attackPeriod,SC2_UNITS[type].attackPeriod);}assert.equal(TUNING.unitScale,.8);});
test('open-ground mixed squad has separate three-abreast ranks rather than overlapping vehicle queues',()=>{const w=setup();w.entities.clear();for(const type of TERRAN)for(let i=0;i<5;i++)w.addUnit(type,'terran',-i,0);const units=w.allies(),goals=units.map(u=>({u,p:w.moveGoal(u)}));for(const a of goals)for(const b of goals)if(a.u.id<b.u.id&&a.u.flying===b.u.flying)assert.ok(distance(a.p,b.p)>=a.u.unitRadius+b.u.unitRadius+.1);const tanks=goals.filter(g=>g.u.unitType==='tank');assert.ok(Math.max(...tanks.map(g=>g.p.z))-Math.min(...tanks.map(g=>g.p.z))>3);assert.ok(Math.max(...goals.map(g=>g.p.x))-Math.min(...goals.map(g=>g.p.x))<14);});
test('blocked formation slots fold into distinct reachable destinations without moving actors',()=>{const w=new World({sandbox:true,waves:false,initial:[],obstacles:[{x:-3,z:2,w:8,h:2},{x:-3,z:-2,w:8,h:2}]});for(let i=0;i<5;i++)w.addUnit('tank','terran',2+i*1.5,0);w.anchor={x:2,z:0,facing:Math.PI/2};const before=w.allies().map(u=>({x:u.x,z:u.z})),goals=w.allies().map(u=>w.moveGoal(u));assert.equal(new Set(goals.map(p=>`${p.x},${p.z}`)).size,5);for(let i=0;i<5;i++){assert.ok(clearLine(w.anchor,goals[i],.7,w.obstacles));assert.deepEqual({x:w.allies()[i].x,z:w.allies()[i].z},before[i]);}});
test('fifteen ranged fighters deploy to both flanks and all shoot the requested target',()=>{const w=setup();w.entities.clear();for(const type of ['marine','hellion','tank'] as const)for(let i=0;i<5;i++)w.addUnit(type,'terran',-w.allies().length*1.1,0);const e=w.addUnit('roach','zerg',12,0);e.hp=e.maxHp=100000;e.weaponCooldown=100000;e.moveSpeed=0;w.issueFocus(e.id);w.advance(16);for(const u of w.allies()){assert.ok(u.lastShotAt>8,`${u.unitType} ${u.id} could not fire`);assert.equal(u.attackTarget,e.id);}const zs=w.allies().map(u=>u.z);assert.ok(Math.min(...zs)<-2&&Math.max(...zs)>2);});
test('deployment never raises weapon rate or moves a manually sieged tank',()=>{const w=setup();w.addUnit('marine','terran',-2,0);const t=w.addUnit('tank','terran',-3,1);t.mode=t.desiredMode='siege';w.refreshStats(t);const p={x:t.x,z:t.z};const e=w.addUnit('roach','zerg',4,0);e.hp=e.maxHp=100000;e.moveSpeed=0;e.weaponCooldown=100000;w.issueFocus(e.id);w.advance(6);assert.equal(distance(t,p),0);for(const u of w.allies()){const shots=w.visualEvents.filter(e=>e.entityId===u.id&&e.kind==='attack');for(let i=1;i<shots.length;i++)assert.ok(shots[i].time-shots[i-1].time>=u.attackPeriod-1/60-1e-8);}});
test('mechanical repair is opt-in, continuous, energy limited and cannot heal self or structures',()=>{const w=setup(),m=w.addUnit('medivac','terran',0,0),t=w.addUnit('tank','terran',1,0);t.hp=1;m.energy=20;w.hash.rebuild(w.entities.values());w.heal(m,.2);assert.equal(t.hp,1);w.addBuilding('starport',0);buy(w,'tech.mechanicalHeal');const old=m.energy;w.heal(m,.2);close(t.hp,1+HEAL.hpPerSecond*.2);close(m.energy,old+m.energyRegen*.2-HEAL.hpPerSecond*.2*HEAL.energyPerHp);assert.equal(m.healTarget,t.id);t.hp=t.maxHp;m.hp=1;const pod=w.spawnPod('marine',{x:1,z:0});pod.hp=1;w.hash.rebuild([...w.entities.values(),pod]);w.heal(m,1);assert.equal(m.hp,1);assert.equal(pod.hp,1);m.energy=0;t.hp=1;m.energyRegen=0;w.heal(m,1);assert.equal(t.hp,1);});
test('completed Factory starts Hellion without purchasing or waiting for a tech lab',()=>{const w=new World({waves:false,obstacles:[]});w.buildings.clear();const b=w.addBuilding('factory',.1);w.wallet={minerals:100,gas:0};w.updateProduction(.1);assert.equal(b.techLab,false);assert.equal(b.upgradeRemaining,null);assert.equal(b.queue[0]?.unitType,'hellion');assert.deepEqual(w.wallet,{minerals:0,gas:0});});
test('green and blue cards charge once and grant Rank 3/5 immediately without creating pods',()=>{for(const rank of [3,5]){const w=setup(),before={...w.wallet};const r=buy(w,`veteran.marine.${rank}`);assert.equal(w.allies().length,2);assert.equal(w.allies()[1].rank,rank);assert.equal(w.pods.length,0);assert.equal(w.wallet.minerals,before.minerals-r.minerals);assert.equal(w.choose(r.offerId),false);w.skipReward();assert.equal(w.pods.length,0);}});
test('full roster veteran grant raises the lowest rank, preserving lost HP and cooldown',()=>{const w=setup();for(let i=0;i<4;i++)w.addUnit('marine','terran',i,2,4);const lowest=w.allies()[0];lowest.hp-=12;lowest.weaponCooldown=.4;const id=lowest.id;buy(w,'veteran.marine.3');assert.equal(w.allies().length,5);assert.equal(lowest.id,id);assert.equal(lowest.rank,3);close(lowest.maxHp-lowest.hp,12);assert.equal(lowest.weaponCooldown,.4);assert.equal(eligibleReward(w,card('veteran.marine.3',w)),false);});
test('paid orders and pods cannot be displaced by an immediate ranked card',()=>{const w=setup();w.allies()[0].rank=5;for(let i=0;i<3;i++)w.addUnit('marine','terran',i,2,5);w.addBuilding('barracks');w.addBuilding('barracks');assert.ok(w.queue('marine'));assert.equal(w.canRecruit('marine',3),false);w.phase='reward';w.rewardRound='random';const r=card('veteran.marine.3',w);w.rewards=[r];const money={...w.wallet};assert.equal(w.choose(r.offerId),false);assert.deepEqual(w.wallet,money);assert.equal(w.allies().length,4);});
test('rarity sampling matches 64/20/10/5/1 without filtering expensive cards',()=>{const rng=seeded(228),counts=Object.fromEntries(Object.keys(RARITIES).map(k=>[k,0]));for(let i=0;i<50000;i++)counts[rollRarity(rng)]++;for(const [r,d] of Object.entries(RARITIES))assert.ok(Math.abs(counts[r]/500-d.weight)<.5,`${r}: ${counts[r]}`);const w=setup();w.wallet={minerals:0,gas:0};for(const value of [.7,.9,.97,.995]){const rows=drawRewards(w,()=>value);assert.equal(rows.length,3);assert.equal(new Set(rows.map(r=>r.id)).size,3);assert.ok(rows.every(r=>!eligibleReward(w,r)));}});
test('purple and orange global buffs remain functional alongside new unit rewards',()=>{const w=setup();for(const rarity of ['purple','orange']){const rows=rewardPool(w).filter(r=>r.rarity===rarity&&r.kind==='buff');assert.ok(rows.length>=3);assert.ok(rows.every(r=>r.kind==='buff'));}const u=w.allies()[0],damage=u.weaponDamage;buy(w,'buff.weapon.orange');close(u.weaponDamage,damage*1.6);buy(w,'buff.vitality.purple');close(u.maxHp,SC2_UNITS.marine.maxHp*1.45);buy(w,'buff.tactical.orange');w.phase='battle';assert.ok(w.dash());close(w.dashReady-w.time,12/1.45);close(w.dashUntil-w.time,1.47);});
test('ranked ordinary and siege attacks both receive the same reward damage multiplier',()=>{const w=setup(),t=w.addUnit('tank','terran',0,0,3);buy(w,'buff.weapon.blue');t.mode='siege';w.refreshStats(t);const e=w.addUnit('roach','zerg',8,0);e.hp=e.maxHp=10000;w.hash.rebuild([t,e]);w.fire(t,e);const r=3/1.3;close(e.maxHp-e.hp,(SIEGE.damage+SIEGE.bonus[0].amount)*r*1.2-e.armor);});
test('map rewards roll at lower probabilities and pickup grants once without spending',()=>{assert.ok(MAP_REWARDS.combatChance<MAP_REWARDS.droneChance);for(const [r,data] of Object.entries(RARITIES))if(r!=='white')assert.ok(data.mapWeight<data.weight);const w=setup();const reward=card('veteran.marine.3',w),before={...w.wallet};w.rewardDrops.push({id:900,x:0,z:0,reward});assert.ok(w.collectRewardDrop(900));assert.equal(w.allies()[1].rank,3);assert.deepEqual(w.wallet,before);assert.equal(w.collectRewardDrop(900),false);assert.equal(w.allies().length,2);});
test('loot remains visible until collected and cannot bypass a cliff with a proximity pickup',()=>{const w=new World({sandbox:true,waves:false,obstacles:[],terrain:true});w.start();const r=rewardPool(w).find(r=>r.id==='economy.minerals')!;w.rewardDrops.push({id:999,x:30,z:8,reward:r});w.advance(.5);assert.equal(w.rewardDrops.length,1);w.paused=true;const p={...w.wallet};w.advance(20);assert.deepEqual(w.wallet,p);assert.equal(w.rewardDrops.length,1);});
test('map drop cannot start a Factory upgrade or duplicate settlement of a kill',()=>{const w=setup();w.addBuilding('factory',0);const rng=seeded(404);for(let i=0;i<100;i++)assert.notEqual(drawReward(w,rng,true)?.kind,'upgrade');w.random=()=>0;const e=w.addUnit('zergling','zerg',4,0);w.hit(e,1000);w.hit(e,1000);assert.equal(w.rewardDrops.length,1);assert.equal(w.pickups.length,1);});
