import test from 'node:test';import assert from 'node:assert/strict';
import {protossFixture,protossElite,target} from './helpers/protoss-elites';
import {World} from '../src/simulation/world';import {HEROES,type HeroId} from '../src/data/heroes';import {ELITES,type EliteId} from '../src/data/elites';
import {compositeHeroBuff,compositeHeroDebuff,compositeEliteBuff,compositeEliteDebuff,teamProtection,teamHealingFactor,recordTeamTransfusion,teamWeaponLeech,teamEntryBarrier,tickTeamAuras,absorbTeamBarrier} from '../src/simulation/combat/team-auras';
import {groundHeroBuff,refreshGroundHeroBuffs} from '../src/simulation/combat/hero-ground-auras';
import {heroAura} from '../src/simulation/combat/terran-hero-passives';import {tickZergEliteState,zergEliteQueenAbility} from '../src/simulation/combat/zerg-elite-runtime';
import {initializeCarrierSubsystem,ownedInterceptors} from '../src/simulation/combat/carriers';
import {expeditionWeaponBonuses} from '../src/simulation/combat/expedition-combat';
const near=(a:number,b:number,t=1e-5)=>assert.ok(Math.abs(a-b)<t,`${a} != ${b}`);
function hero(w:World,id:HeroId,x=0){const u=w.addUnit(HEROES[id].baseFamily,'terran',x,0);u.heroId=id;w.heroes.set(id,{id,rank:1,entityId:u.id,skillReady:0,revivePaid:false,awaitingSpawn:false});w.refreshStats(u,true);return u;}
function elite(w:World,id:EliteId,x=0){const u=w.addUnit(ELITES[id].family,'terran',x,0);u.eliteId=id;w.refreshStats(u,true);return u;}
test('new command damage scales the native armored bonus once alongside the main weapon',()=>{const w=protossFixture(),u=w.addUnit('stalker','terran',40,0),base=expeditionWeaponBonuses(w,u).bonuses.find(b=>b.attribute==='Armored')!.amount,damage=u.weaponDamage;hero(w,'fenix');hero(w,'purifier_flagship');w.refreshStats(u);near(u.weaponDamage/damage,1.9);near(expeditionWeaponBonuses(w,u).bonuses.find(b=>b.attribute==='Armored')!.amount/base,1.9);hero(w,'raynor');w.refreshStats(u);near(expeditionWeaponBonuses(w,u).bonuses.find(b=>b.attribute==='Armored')!.amount/base,1.9);});
test('Kerrigan global bio command and Leviathan stack additively once, old local HP remains distinct',()=>{const w=protossFixture(),b=w.addUnit('roach','terran',40,0);const base={hp:b.maxHp,damage:b.weaponDamage,period:b.attackPeriod,armor:b.armor,move:b.moveSpeed};const k=hero(w,'kerrigan'),l=hero(w,'hots_leviathan');w.refreshStats(b);near(b.weaponDamage/base.damage,1.7);near(base.period/b.attackPeriod,1.9);near(b.maxHp/base.hp,1.55);near(b.armor/base.armor,1.6);near(b.moveSpeed/base.move,1.5);b.hp=b.maxHp*.4;l.x=40;refreshGroundHeroBuffs(w);near(b.maxHp/base.hp,1.8);near(b.hp/b.maxHp,.4);k.hp=0;refreshGroundHeroBuffs(w);near(b.maxHp/base.hp,1.45);near(b.hp/b.maxHp,.4);});
test('Fenix and Flagship global mechanical/native pools stack once; transient bodies and workers excluded',()=>{const w=protossFixture(),b=w.addUnit('stalker','terran',40,0);const base={hp:b.maxHp,shield:b.maxShield!,damage:b.weaponDamage,period:b.attackPeriod};hero(w,'fenix');hero(w,'purifier_flagship');w.refreshStats(b);near(b.maxHp/base.hp,1.5);near(b.maxShield!/base.shield,1.9);near(b.weaponDamage/base.damage,1.9);near(base.period/b.attackPeriod,1.75);const temp=w.addUnit('stalker','terran',1,1);temp.temporary=true;const worker={...temp,temporary:false,unitType:'probe'} as any;near(compositeHeroBuff(w,temp).damage,0);near(compositeHeroBuff(w,worker).damage,0);});
for(const [id,key,n]of [['zagara','attackSlow',.45],['dehaka','weaponSuppression',.5],['alarak','weaponSuppression',.45],['vorazun','attackSlow',.5],['zeratul','armorReduction',.65]] as const)test(`${id}: approved debuff remains full on Boss and excludes structures/out-of-range targets`,()=>{const w=protossFixture(),h=hero(w,id),b=target(w);b.enemyTier='boss';near(compositeHeroDebuff(w,b,key),n);b.attributes=['Structure'];near(compositeHeroDebuff(w,b,key),0);b.attributes=[];b.x=40;near(compositeHeroDebuff(w,b,key),0);h.rank=5;b.x=3;near(compositeHeroDebuff(w,b,key),n);});
test('Niadra increases bio HP60 and armor10 after multipliers and restores3% without modifying intrinsic heal payload',()=>{const w=protossFixture(),b=w.addUnit('roach','terran',3,0),base=b.maxHp,armor=b.armor;hero(w,'niadra');w.refreshStats(b);near(b.maxHp/base,1.6);near(b.armor-armor,10);b.hp=b.maxHp*.2;tickTeamAuras(w,1);near(b.hp/b.maxHp,.23);});
test('Artanis shield60 and armor10/6, damage reduction40 replaces old30; entering/leaving preserves wounds',()=>{const w=protossFixture(),b=w.addUnit('stalker','terran',3,0),hp=b.maxHp,shield=b.maxShield!,armor=b.armor;const a=hero(w,'artanis');w.refreshStats(b);near(b.maxHp,hp);near(b.maxShield!/shield,1.6);near(b.armor-armor,6);near(b.shieldArmor!,10);b.hp*=.4;b.shield!*=.25;near(teamProtection(w,b,true),.4);a.x=40;refreshGroundHeroBuffs(w);near(b.hp/b.maxHp,.4);near(b.shield!/b.maxShield!,.25);});
test('Stukov freezes entry maximum, delays first pulse, tiers 6/3/1.2 and does not multiply DOT by weapon vulnerability',()=>{for(const [tier,ratio]of [[undefined,.06],['elite',.03],['boss',.012]]as const){const w=protossFixture(),h=hero(w,'stukov'),b=target(w);b.maxHp=b.hp=10000;b.enemyTier=tier;tickTeamAuras(w,0);near(b.hp,10000);w.time=.99;tickTeamAuras(w,0);near(b.hp,10000);w.time=1;tickTeamAuras(w,0);near(b.hp,10000*(1-ratio));near(teamHealingFactor(w,b),.5);h.x=40;w.time=1.1;tickTeamAuras(w,0);h.x=0;w.time=1.2;tickTeamAuras(w,0);near(b.hp,10000*(1-ratio));const clone=protossFixture();clone.restoreRun(w.captureRun());assert.deepEqual(clone.teamAuras.plague,w.teamAuras.plague);}});
test('family commanders grant all core attributes20 once, same identity duplicates do not compound',()=>{for(const id of ['zealot.3','zergling.3']as const){const w=protossFixture(),family=ELITES[id].family,b=w.addUnit(family,'terran',40,0),base={hp:b.maxHp,shield:b.maxShield!,damage:b.weaponDamage,period:b.attackPeriod,armor:b.armor,move:b.moveSpeed};elite(w,id);elite(w,id,1);w.refreshStats(b);near(b.maxHp/base.hp,1.2);near(b.weaponDamage/base.damage,1.2);near(base.period/b.attackPeriod,1.2);near(b.moveSpeed/base.move,1.2);near(b.armor,base.armor*1.2);if(base.shield>0)near(b.maxShield!/base.shield,1.2);}});
test('brood and flying shell have correct eligibility, strongest elite HP wins and flat armor sums',()=>{const w=protossFixture(),b=w.addUnit('mutalisk','terran',3,0),base=b.maxHp;elite(w,'queen.1');elite(w,'corruptor.2');w.refreshStats(b);near(b.maxHp/base,1.45);near(compositeEliteBuff(w,b).armorFlat,12);near(compositeEliteBuff(w,b).speed,.25);const h=hero(w,'kerrigan',3);w.refreshStats(h);near(compositeEliteBuff(w,h).maxHp,.45);});
test('sentry and flight support correctly scope ground/air shield armor, direct-only protection and same-source maximum',()=>{const w=protossFixture(),b=w.addUnit('stalker','terran',3,0),a=w.addUnit('phoenix','terran',3,1);elite(w,'sentry.1');elite(w,'immortal.3');elite(w,'carrier.3');near(compositeEliteBuff(w,b).maxShield,.4);near(compositeEliteBuff(w,b).armorFlat,8);near(compositeEliteBuff(w,b).shieldArmorFlat,10);near(teamProtection(w,b,true),.15);near(teamProtection(w,b,false),0);near(compositeEliteBuff(w,a).maxHp,.3);near(compositeEliteBuff(w,a).speed,.25);});
test('elite suppression halves control on Boss, armor/relative defense remain full and stronger reduction wins',()=>{const w=protossFixture(),b=target(w);elite(w,'queen.3');elite(w,'sentry.2');elite(w,'ravager.3');near(compositeEliteDebuff(w,b,'damage'),.3);near(compositeEliteDebuff(w,b,'speed'),.35);near(compositeEliteDebuff(w,b,'armor'),.45);b.enemyTier='boss';near(compositeEliteDebuff(w,b,'damage'),.15);near(compositeEliteDebuff(w,b,'speed'),.175);near(compositeEliteDebuff(w,b,'armor'),.45);near(compositeEliteDebuff(w,b,'defense'),.25);b.damageReduction=.5;b.armor=100;hero(w,'zeratul');const hp=b.hp;w.hit(b,1000,[],1,'terran',0,0);near(hp-b.hp,1000*(1-.5*.7)-100*.35);});
test('transfusion effective healing grants six seconds, active healing30 and actual weapon life leech15 with10% per-second cap',()=>{const w=protossFixture(),q=elite(w,'queen.2'),u=w.addUnit('roach','terran',2,0);recordTeamTransfusion(w,q,u,0);near(teamHealingFactor(w,u),1);recordTeamTransfusion(w,q,u,1);near(teamHealingFactor(w,u),1.3);u.hp=u.maxHp*.2;teamWeaponLeech(w,u,1e6);near(u.hp/u.maxHp,.3);teamWeaponLeech(w,u,1e6);near(u.hp/u.maxHp,.3);w.time=1;teamWeaponLeech(w,u,1e6);near(u.hp/u.maxHp,.4);const own=elite(w,'mutalisk.3',2);recordTeamTransfusion(w,q,own,1);own.hp*=.5;const hp=own.hp;teamWeaponLeech(w,own,1e6);near(own.hp,hp);w.time=6;near(teamHealingFactor(w,u),1);});
test('matron actually pays and releases sixteen quarter-second pulses with frozen five recipients',()=>{const w=protossFixture(),q=elite(w,'queen.2');q.energy=50;const targets=Array.from({length:5},(_,i)=>{const b=w.addUnit('ultralisk','terran',2+i*.4,0,5);b.hp=1;return b;});zergEliteQueenAbility(w,q);near(q.energy,0);w.time=.249;tickZergEliteState(w);near(w.stats.healed,0);for(let i=1;i<=16;i++){w.time=i*.25;tickZergEliteState(w);}near(w.stats.healed,5*60*(1+15*1.3));assert.equal(w.teamAuras.blood.length,5);});
test('entry barriers freeze basis, survive aura loss/save, finite absorption and cooldown cannot be reset by exiting',()=>{const w=protossFixture(),m=elite(w,'mutalisk.3'),q=elite(w,'queen.1'),b=w.addUnit('roach','terran',2,0);teamEntryBarrier(w,m,.5);const receipt=w.teamAuras.barriers.find(r=>r.target===b.id)!;near(receipt.maximum,b.maxHp*.15*.5);q.hp=0;refreshGroundHeroBuffs(w);const clone=protossFixture();clone.restoreRun(w.captureRun());const amount=receipt.amount;near(absorbTeamBarrier(w,b,amount+30),30);teamEntryBarrier(w,m,1);near(w.teamAuras.barriers.find(r=>r.target===b.id)!.amount,0);});
test('real carrier children inherit mother global/local aura once, never receive a second spatial membership',()=>{const w=protossFixture(),m=w.addUnit('carrier','terran',30,0);initializeCarrierSubsystem(w);const c=ownedInterceptors(w,m.id)[0],base={hp:c.maxHp,shield:c.maxShield!,damage:c.weaponDamage,period:c.attackPeriod};hero(w,'fenix');hero(w,'purifier_flagship');w.refreshStats(m);w.refreshStats(c);near(c.maxHp/base.hp,1.5);near(c.maxShield!/base.shield,1.9);near(c.weaponDamage/base.damage,1.9);near(base.period/c.attackPeriod,1.75);c.x=80;w.refreshStats(c);near(c.weaponDamage/base.damage,1.9);});
