import {test} from 'node:test';
import assert from 'node:assert/strict';
import {CharTerrain,AIR_HEIGHT,RAMPS} from '../src/data/terrain.ts';
import {World} from '../src/simulation/world.ts';
import {translate,distance} from '../src/simulation/movement/steering.ts';
import {charGeometry} from '../src/render/terrain/char-geometry.ts';
const t=new CharTerrain();
test('shared fixed Char map has three four-by-six ramps and stable two-level heights',()=>{assert.equal(t.height({x:0,z:0}),0);assert.equal(t.height({x:30,z:8}),3);assert.equal(t.height({x:-30,z:8}),3);assert.equal(t.height({x:0,z:-40}),3);for(const r of RAMPS){assert.equal(r.width,4);assert.equal(r.length,6);assert.equal(t.height(r),1.5);}assert.equal(t.height({x:21,z:0}),0);assert.equal(t.height({x:27,z:0}),3);});
test('ground footprints cannot cross cliff edges or escape the side of a ramp; air ignores cliffs',()=>{const ground={x:23.5,z:8},air={...ground};translate(ground,{x:1,z:0},.375,false,[],56,t);assert.equal(ground.x,23.5);translate(air,{x:1,z:0},.75,true,[],56,t);assert.equal(air.x,24.5);const slope={x:24,z:1};translate(slope,{x:0,z:1},.875,false,[],56,t);assert.equal(slope.z,1);assert.ok(t.walkLine({x:20,z:0},{x:28,z:0},.875));});
test('melee cannot attack through a cliff and ranged fire checks intervening terrain',()=>{const low={x:23.6,z:8},high={x:24.4,z:8};assert.equal(t.lineOfFire(low,high,false,false,true),false);assert.equal(t.lineOfFire({x:20,z:8},{x:28,z:8}),false);assert.ok(t.lineOfFire({x:20,z:0},{x:28,z:0}));assert.ok(t.lineOfFire({x:20,z:8},{x:28,z:8},true,true));assert.equal(t.bodyHeight({...low,flying:true}),AIR_HEIGHT);});
test('cached ramp navigation brings different ground units to a high plateau without teleporting',()=>{for(const type of ['marine','hellion','tank'] as const){const w=new World({sandbox:true,waves:false,obstacles:[],initial:[type],terrain:true});w.start();const u=w.allies()[0];u.x=18;u.z=8;u.prev={x:u.x,z:u.z};w.anchor.x=34;w.anchor.z=8;w.trail=[{x:34,z:8}];let maxHeight=0;for(let i=0;i<2400;i++){const before={x:u.x,z:u.z};w.step();assert.ok(distance(u,before)<.15);assert.ok(t.canOccupy(u,u.unitRadius));maxHeight=Math.max(maxHeight,t.height(u));}assert.equal(maxHeight,3,type+' never climbed');assert.ok(u.x>26,type+' did not follow the ramp');assert.ok(w.terrain!.routes.size<10);}});
test('spawn positions stay on opened reachable footprint-safe ground across all expansions',()=>{const w=new World();for(let stage=1;stage<=12;stage++){w.stage=stage;w.prepareStage();for(let i=0;i<15;i++){const p=w.eventPoint();assert.ok(w.terrain!.canOccupy(p,1.25));assert.ok(Math.abs(p.x)+1.25<w.mapHalf);assert.ok(Math.abs(p.z)+1.25<w.mapHalf);}}assert.ok(w.hive!.z<-34);});
test('renderer creates actual vertical cliff faces and upward-facing ramp/floor surfaces',()=>{const g=charGeometry();assert.ok(g.cliffs.attributes.position.count>100);let slope=0,up=0;const n=g.floor.attributes.normal;for(let i=0;i<n.count;i++){assert.ok(n.getY(i)>.8);if(n.getY(i)<.99)slope++;else up++;}assert.ok(slope>0&&up>0);});

// Flat-region optimization must not open shortcuts at the ramp shoulders or plateau corners.
test('flat broad phase agrees with footprint sampling near every cliff and ramp boundary',()=>{let seed=7921;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};for(let n=0;n<1200;n++){const a={x:random()*80-40,z:random()*80-40},b={x:a.x+random()*12-6,z:a.z+random()*12-6},r=random()*.9;if(t.flatHeight(a,b,r)<0)continue;const h=t.flatHeight(a,b,r);for(let i=0;i<=20;i++)for(const angle of [0,Math.PI/2,Math.PI,Math.PI*1.5])assert.equal(t.height({x:a.x+(b.x-a.x)*i/20+Math.cos(angle)*r,z:a.z+(b.z-a.z)*i/20+Math.sin(angle)*r}),h);}});
