import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {World} from '../src/simulation/world';
import {HEROES,type HeroId} from '../src/data/heroes';
import {ZERG_HERO_IDS} from '../src/data/zerg-heroes';
import {tickHeroAttacks} from '../src/simulation/combat/hero-attack-upgrades';
import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';
import {zergState,tickZergHero,tickZergHeroState,zergHeal,zergTeamBuff} from '../src/simulation/combat/zerg-hero-passives';
import {registerZergRevival,tickZergRevival,zergRevivalSeats,reservedZergElite} from '../src/simulation/combat/zerg-hero-revival';
import {heroState} from '../src/simulation/combat/terran-hero-passives';
import {refreshGroundHeroBuffs,heroGroundSuppression,heroWeaponVulnerability} from '../src/simulation/combat/hero-ground-auras';
import {pairBodies,tickBroods,joinPair} from '../src/simulation/zerg-brood';
import {retireFamily} from '../src/simulation/expedition-production';
import {RUN_SCHEMA} from '../src/simulation/persistence/run-snapshot';
import type {Entity} from '../src/simulation/types';

const near=(a:number,b:number)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function setup(id:HeroId,rank=1){const w=new World({race:'zerg',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10506});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();for(const p of Object.values(w.expedition.production))p.enabled={};assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!;u.rank=rank;w.heroes.get(id)!.rank=rank;u.x=u.z=0;u.prev={x:0,z:0};w.refreshStats(u,true);return {w,u};}
function target(w:World,x=2,z=0,air=false){const e=w.addUnit(air?'mutalisk':'roach','zerg',x,z);e.hp=e.maxHp=1e7;e.armor=0;e.stoppedUntil=1e9;e.specialReady=1e9;e.moveSpeed=0;w.hash.rebuild(w.entities.values());return e;}
function advance(w:World,seconds:number,casts=false){for(let i=0;i<Math.round(seconds*60);i++){w.time+=1/60;tickHeroAttacks(w);if(casts)resolveExpeditionHeroCasts(w);}}
function kill(w:World,u:Entity,source?:number){w.hit(u,u.hp+u.armor+1000,[],1,u.owner==='terran'?'zerg':'terran',0,1,source);assert.equal(u.hp,0);}
function roster(w:World,n=1,full=true){w.expedition.familySlots=['roach','zergling','hydralisk'];return Array.from({length:n},(_,i)=>{const a=w.addUnit('roach','terran',1+i*.5,1,3);a.stoppedUntil=1e9;if(!full)a.hp=a.maxHp*.2;return a;});}

for(const id of ZERG_HERO_IDS)test(`${id} bare I/V keeps authored body growth and excludes historical triple attack multipliers`,()=>{const {w,u}=setup(id);w.heroes.clear();w.refreshStats(u,true);near(u.maxHp,HEROES[id].hp);near(u.weaponDamage,HEROES[id].damage);near(u.attackPeriod,HEROES[id].period);u.rank=5;w.refreshStats(u,true);near(u.maxHp,HEROES[id].hp*2.4);near(u.weaponDamage,HEROES[id].damage*2.4*.8);near(u.attackPeriod,HEROES[id].period*.8);});

test('Kerrigan barrier derives only from actual enemy HP loss, ignores shield absorption and overkill, caps and expires',()=>{const {w,u}=setup('kerrigan'),a=target(w);a.hp=100;a.shield=a.maxShield=500;a.shieldArmor=0;w.hit(a,400,[],1,'terran',0,1,u.id);near(zergState(u).barrier,0);w.hit(a,400,[],1,'terran',0,1,u.id);near(zergState(u).barrier,25);const b=target(w,1);w.hit(b,u.maxHp*10,[],1,'terran',0,1,u.id);near(zergState(u).barrier,u.maxHp*.8);const hp=u.hp;w.hit(u,500,[],1,'zerg',0,1);near(u.hp,hp);near(zergState(u).barrier,u.maxHp*.8-500);w.time=9;tickZergHero(w,u,1/60);near(zergState(u).barrier,0);w.hit(u,100,[],1,'zerg',0,1);near(hp-u.hp,100);});
test('Kerrigan third real primary cycle cleaves nearby ground once, not air or distant bodies; rank stays frozen in flight',()=>{const {w,u}=setup('kerrigan',3),a=target(w,1.5),nearby=target(w,2,1),air=target(w,2,1,true),far=target(w,10);for(let i=0;i<2;i++){w.fire(u,a);advance(w,.2);}near(nearby.hp,1e7);const packet=u.weaponDamage;w.fire(u,a);u.rank=1;u.weaponDamage=1;advance(w,.2);near(1e7-nearby.hp,packet*2);near(air.hp,1e7);near(far.hp,1e7);assert.equal(w.visualEvents.filter(e=>e.kind==='hero-cleave').length,1);assert.equal(heroState(u).cycles,3);});
test('Zerg melee committed flight misses a target that moves beyond captured reach; ranged flight still lands after caster death',()=>{const {w,u}=setup('dehaka'),a=target(w,1.5);w.fire(u,a);a.x=15;advance(w,1);near(a.hp,1e7);const ranged=setup('stukov'),b=target(ranged.w,4);ranged.w.fire(ranged.u,b);ranged.u.hp=0;advance(ranged.w,1);assert.ok(b.hp<1e7);assert.equal(ranged.w.zergHeroes.infections.length,1);});
test('Zagara retains original permanent-biological team speed/move bonus; temporary brood and workers are excluded',()=>{const {w,u}=setup('zagara'),a=w.addUnit('roach','terran',2,0),temporary=w.addUnit('roach','terran',2,1);temporary.temporary=true;w.refreshStats(temporary);const period=a.attackPeriod,move=a.moveSpeed;u.hp=0;w.refreshStats(a);near(a.attackPeriod/period,1.4);near(move/a.moveSpeed,1.2);w.refreshStats(temporary);const slow=temporary.attackPeriod;u.hp=u.maxHp;w.refreshStats(temporary);near(temporary.attackPeriod,slow);assert.deepEqual(zergTeamBuff(w,{...a,unitType:'drone'} as any),{damage:0,health:0,armor:0,speed:0,move:0});});
test('Zagara ten real nearby kills hatch two original Baneling bodies, bounded at six and preserving blocked spawn rights',()=>{const {w,u}=setup('zagara');for(let i=0;i<10;i++)kill(w,target(w,3,i*.05),u.id);assert.equal(zergState(u).kills,10);const free=w.freePosition;w.freePosition=()=>null;tickZergHero(w,u,1/60);assert.equal(zergState(u).kills,10);w.freePosition=free;tickZergHero(w,u,1/60);let children=w.allies().filter(a=>a.temporaryKind==='hero-baneling');assert.equal(children.length,2);assert.ok(children.every(a=>a.unitType==='baneling'&&a.summonOwnerId===u.id&&a.temporaryUntil===10));zergState(u).kills=20;tickZergHero(w,u,1/60);tickZergHero(w,u,1/60);children=w.allies().filter(a=>a.temporaryKind==='hero-baneling');assert.equal(children.length,6);zergState(u).kills=10;tickZergHero(w,u,1/60);assert.equal(w.allies().filter(a=>a.temporaryKind==='hero-baneling').length,6);assert.equal(zergState(u).kills,10);kill(w,target(w,3),children[0].id);assert.equal(zergState(u).kills,10);});
test('Temporary hero Baneling expires without damage, and combat detonation dies once instead of normal friendly recovery',()=>{const {w,u}=setup('zagara');zergState(u).kills=10;tickZergHero(w,u,1/60);const b=w.allies().find(a=>a.temporaryKind==='hero-baneling')!,a=target(w,b.x+.4,b.z);b.weaponDamage=1000;const hp=a.hp;w.fire(b,a);assert.equal(b.hp,0);assert.ok(a.hp<hp);const after=a.hp;w.fire(b,a);near(a.hp,after);const second=w.allies().find(a=>a.temporaryKind==='hero-baneling')!;w.time=11;w.tick=660;w.step();assert.ok(!w.entities.has(second.id));assert.ok(!second.banelingRecoveryUntil);});
test('Zagara three frozen active shells are actual separate ground blasts; no air damage or percentage Boss kill',()=>{const {w,u}=setup('zagara',1),a=target(w,5),air=target(w,5,0,true);assert.ok(w.castHero('zagara'));assert.equal(w.heroCasts.length,3);u.rank=5;w.heroes.get('zagara')!.rank=5;advance(w,1.1,true);near(1e7-a.hp,6900);near(air.hp,1e7);assert.equal(w.heroCasts.length,0);});

test('Dehaka essence adapts to real dead body attributes and remains bounded; flight adaptation extends reach without air targeting',()=>{const {w,u}=setup('dehaka'),hp=u.maxHp,damage=u.weaponDamage;kill(w,target(w,2,0,true),u.id);assert.equal(zergState(u).essence,1);assert.ok(zergState(u).biologicalUntil>0&&zergState(u).flyingUntil>0);assert.ok(u.maxHp>hp&&u.weaponDamage>damage);near(u.attackRange,3);assert.equal(u.flying,false);assert.equal(w.targetAllowed(u,target(w,2,2,true)),false);const mech=w.addUnit('hellion','zerg',2,1);kill(w,mech,u.id);assert.ok(zergState(u).mechanicalUntil>0);u.hp-=u.maxHp*.1;const before=u.hp;tickZergHero(w,u,1);near(u.hp-before,u.maxHp*.03);w.time=9;w.refreshStats(u);near(u.attackRange,2);zergState(u).essence=999999;kill(w,target(w,2),u.id);kill(w,target(w,2),u.id);assert.equal(zergState(u).essence,1000000);});
test('Dehaka Devour deals fixed real damage to a ground Boss and grants independent timed reserve; positive life armor pays once',()=>{const {w,u}=setup('dehaka'),a=target(w,1.5);a.enemyTier='boss';a.hp=a.maxHp=9000;u.hp=u.maxHp*.5;assert.ok(w.castHero('dehaka'));advance(w,.4,true);assert.equal(a.hp,0);assert.equal(zergState(u).essence,9);assert.ok(u.hp>u.maxHp*.5);const s=zergState(u);near(s.reserve,u.maxHp*.3);u.armor=16;s.reserve=50;s.reserveMax=100;const hp=u.hp;w.hit(u,100,[],1,'zerg',0,0);near(hp-u.hp,34);near(s.reserve,0);s.reserve=500;s.reserveUntil=w.time+8;const amount=s.reserve;u.hp-=200;zergHeal(w,u,u,200,true);near(s.reserve,amount);w.time+=9;tickZergHero(w,u,1/60);near(s.reserve,0);});
test('Dehaka cannot Devour air, buildings, hidden or out-of-reach targets; rejected cast spends no cooldown',()=>{for(const kind of ['air','building','cloak','far']){const {w}=setup('dehaka'),a=target(w,kind==='far'?15:1.5,0,kind==='air');if(kind==='building')a.attributes.push('Structure');if(kind==='cloak')a.cloaked=true;const before=w.heroes.get('dehaka')!.skillReady;assert.equal(w.castHero('dehaka'),false,kind);near(w.heroes.get('dehaka')!.skillReady,before);assert.equal(w.heroCasts.length,0);}});
test('Dehaka mechanical armor adaptation is frozen at launch and ignores only half of positive armor',()=>{const {w,u}=setup('dehaka'),mech=w.addUnit('hellion','zerg',2,1);kill(w,mech,u.id);const a=target(w,1.5);a.armor=100;const weapon=u.weaponDamage;w.fire(u,a);w.time=8.01;tickHeroAttacks(w);near(1e7-a.hp,weapon-50);});

test('Stukov primary fatal hit records infection before death and creates exactly one actual corpse pool',()=>{const {w,u}=setup('stukov'),a=target(w);a.hp=20;w.fire(u,a);advance(w,.3);assert.equal(a.hp,0);assert.equal(w.zergHeroes.pools.length,1);assert.equal(w.zergHeroes.infections.length,0);w.hit(a,100,[],1,'terran',0,1,u.id);assert.equal(w.zergHeroes.pools.length,1);const patient=roster(w,1,false)[0],before=patient.hp;for(let i=1;i<=4;i++){w.time=w.zergHeroes.pools[0].until-4+i;tickZergHeroState(w);}near(patient.hp-before,Math.min(patient.maxHp-before,880));assert.equal(w.zergHeroes.pools.length,0);});
test('Stukov overlapping corpse pools heal only the strongest once per second and stop when source is dead',()=>{const {w,u}=setup('stukov',5),a=roster(w,1,false)[0];a.maxHp=10000;a.hp=100;w.zergHeroes.pools=[{id:w.nextId++,source:u.id,rank:1,point:{x:a.x,z:a.z},until:4,next:1},{id:w.nextId++,source:u.id,rank:5,point:{x:a.x,z:a.z},until:4,next:1}];w.time=1;tickZergHeroState(w);near(a.hp,628);u.hp=0;w.time=2;tickZergHeroState(w);near(a.hp,628);});
test('Stukov every sixth main cycle causes one adjacent grenade; corrosion persists as four fixed frozen pulses',()=>{const {w,u}=setup('stukov'),a=target(w,4),b=target(w,4,1);heroState(u).cycles=5;const weapon=u.weaponDamage;w.fire(u,a);advance(w,.3);near(1e7-b.hp,weapon*2*1.45);const before=a.hp;assert.ok(w.castHero('stukov'));advance(w,.3,true);assert.equal(w.heroCasts.filter(c=>c.phase==='dot').length,8);u.rank=5;advance(w,4.1,true);near(before-a.hp,5980);assert.equal(w.heroCasts.length,0);});

test('Niadra heals seven actual wounded permanent biological bodies even when she is more wounded, with no self or temporary heal',()=>{const {w,u}=setup('niadra'),allies=roster(w,7,false);for(const a of allies){a.maxHp=10000;a.hp=1000;}u.hp=1;const temporary=w.addUnit('roach','terran',2,1);temporary.temporary=true;temporary.hp=1;w.time=1;tickZergHero(w,u,1);assert.equal(u.healTargets?.length,7);near(w.stats.healed,3850);near(u.hp,1);near(temporary.hp,1);assert.ok(allies.every(a=>a.hp===1550));});
test('Niadra parasite death heals actual missing HP once, independent from her continuous heal',()=>{const {w,u}=setup('niadra'),patient=roster(w,1,false)[0],a=target(w,2);a.hp=1;const before=patient.hp;w.fire(u,a);advance(w,.3);near(patient.hp-before,Math.min(patient.maxHp-before,400));assert.equal(w.zergHeroes.parasites.length,0);const hp=patient.hp;w.hit(a,999,[],1,'terran',0,1,u.id);near(patient.hp,hp);});
test('Niadra active can heal an injured hero without registering or reviving that hero',()=>{const {w}=setup('niadra');assert.ok(w.acquireHero('kerrigan'));const ally=w.heroEntity('kerrigan')!;ally.x=2;ally.z=0;ally.hp=ally.maxHp*.3;w.hash.rebuild(w.entities.values());const hp=ally.hp;assert.ok(w.castHero('niadra'));near(ally.hp-hp,ally.maxHp*.2);assert.equal(w.zergHeroes.revivals.length,0);});
test('Niadra registers full-HP permanent seats, restores same identity/rank/variant/cooldown once and uses one charge per second',()=>{const {w,u}=setup('niadra',5),[a,b]=roster(w,2);a.eliteId='roach.1';w.refreshStats(a,true);a.nextShotAt=8;a.weaponCooldown=.6;const identity={id:a.id,born:a.bornAt,rank:a.rank,elite:a.eliteId};assert.ok(registerZergRevival(w,u,w.nextId++,5));kill(w,a);kill(w,b);assert.equal(zergRevivalSeats(w,'roach'),2);assert.ok(reservedZergElite(w,'roach.1'));const wallet={...w.wallet};w.time=1;tickZergRevival(w);const revived=w.entities.get(a.id)!;assert.equal(revived.id,identity.id);assert.equal(revived.bornAt,identity.born);assert.equal(revived.rank,identity.rank);assert.equal(revived.eliteId,identity.elite);near(revived.hp,revived.maxHp*.7);near(revived.nextShotAt,8);near(revived.weaponCooldown,.6);assert.equal(w.entities.get(b.id)!.hp,0);w.time=2;tickZergRevival(w);assert.ok(w.entities.get(b.id)!.hp>0);assert.deepEqual(w.wallet,wallet);kill(w,revived);w.time=3;tickZergRevival(w);assert.equal(w.entities.get(a.id)!.hp,0);assert.equal(w.zergHeroes.revivals[0].charges,2);});
test('Niadra blocked revival spends no charge and reserves dead capacity; expiry releases it, family retirement cancels historical rights',()=>{const {w,u}=setup('niadra'),[a]=roster(w);registerZergRevival(w,u,w.nextId++,1);kill(w,a);const capacity=w.availableCapacity('roach'),free=w.freePosition;w.freePosition=()=>null;w.time=1;tickZergRevival(w);assert.equal(w.zergHeroes.revivals[0].charges,2);assert.equal(w.familySeatCount('roach'),1);near(w.availableCapacity('roach'),capacity);w.freePosition=free;retireFamily(w,'roach','ravager');w.expedition.familySlots.push('roach');w.time=2;tickZergRevival(w);assert.equal(w.entities.get(a.id)?.hp??0,0);assert.equal(zergRevivalSeats(w,'roach'),0);const next=roster(w,1)[0];registerZergRevival(w,u,w.nextId++,1);kill(w,next);assert.equal(zergRevivalSeats(w,'roach'),1);w.time=11;tickZergRevival(w);assert.equal(zergRevivalSeats(w,'roach'),0);assert.equal(w.zergHeroes.revivals.length,0);});
test('Twin revival waits for both deaths, reserves original pair slot against new pairs, and restores both atomically as one charge',()=>{const {w,u}=setup('niadra',3);w.expedition.familySlots=['zergling','roach'];const first=w.addFamilyMember('zergling',{x:2,z:1},3),pair=w.expedition.zerglingPairs.find(p=>p.id===first.pairId)!,bodies=pairBodies(w,pair);assert.equal(bodies.length,2);registerZergRevival(w,u,w.nextId++,3);kill(w,bodies[0]);w.time=1;tickZergRevival(w);assert.equal(w.entities.get(bodies[0].id)!.hp,0);assert.equal(w.zergHeroes.revivals[0].charges,3);kill(w,bodies[1]);tickBroods(w);const oldSlot=pair.slot;const extra=w.addFamilyMember('zergling',{x:4,z:1});assert.notEqual(w.expedition.zerglingPairs.find(p=>p.id===extra.pairId)!.slot,oldSlot);const free=w.freePosition;let calls=0;w.freePosition=(...args)=>++calls===1?free.apply(w,args):null;w.time=2;tickZergRevival(w);assert.ok(bodies.every(b=>(w.entities.get(b.id)?.hp??0)===0));assert.equal(w.zergHeroes.revivals[0].charges,3);w.freePosition=free;w.time=3;tickZergRevival(w);const revived=pairBodies(w,pair);assert.equal(revived.length,2);assert.deepEqual(revived.map(u=>u.id).sort(),bodies.map(u=>u.id).sort());assert.ok(Math.hypot(revived[0].x-revived[1].x,revived[0].z-revived[1].z)>revived[0].unitRadius*2);assert.equal(w.zergHeroes.revivals[0].charges,2);assert.equal(pair.regrowAt,null);});
test('Registered Niadra revival receipt survives caster death for its existing eight-second window',()=>{const {w,u}=setup('niadra'),[a]=roster(w);registerZergRevival(w,u,w.nextId++,1);kill(w,u);kill(w,a);w.time=1;tickZergRevival(w);assert.ok(w.entities.get(a.id)!.hp>0);assert.equal(u.hp,0);});
test('Incomplete twin seats are excluded from registration; a late companion cannot create historical resurrection rights',()=>{const {w,u}=setup('niadra');w.expedition.familySlots=['zergling','roach'];const first=w.addUnit('zergling','terran',2,1),pair=joinPair(w,first);pair.birthPending=true;assert.equal(w.canCastHero('niadra'),false);const ordinary=w.addUnit('roach','terran',3,1);assert.ok(registerZergRevival(w,u,w.nextId++,1));assert.ok(w.zergHeroes.revivals[0].seats.every(s=>s.family==='roach'));const companion=w.addUnit('zergling','terran',2.8,1);joinPair(w,companion,pair.id);pair.birthPending=false;kill(w,first);kill(w,companion);w.time=1;tickZergRevival(w);assert.equal(w.entities.get(first.id)!.hp,0);assert.equal(w.entities.get(companion.id)!.hp,0);assert.equal(w.zergHeroes.revivals[0].charges,2);assert.ok(ordinary.hp>0);});
test('A refreshed Stukov corrosion replaces remaining source/target pulses instead of stacking two old schedules',()=>{const {w}=setup('stukov'),a=target(w,4);assert.ok(w.castHero('stukov'));advance(w,1.3,true);assert.equal(w.heroCasts.length,3);w.heroes.get('stukov')!.skillReady=w.time;const before=a.hp;assert.ok(w.castHero('stukov'));advance(w,.3,true);assert.equal(w.heroCasts.length,4);advance(w,4.1,true);near(before-a.hp,5980);assert.equal(w.heroCasts.length,0);});
test('Leviathan tentacles hit at most four real visible ground/air bodies on a two-second cadence and ignore buildings',()=>{const {w,u}=setup('hots_leviathan'),a=Array.from({length:6},(_,i)=>target(w,2+i*.2,1,i%2===1)),structure=target(w,2,-1);structure.attributes.push('Structure');a[5].cloaked=true;tickZergHero(w,u,1/60);assert.equal(w.visualEvents.filter(e=>e.kind==='hero-tentacle').length,4);assert.equal(a.filter(e=>e.hp<1e7).length,4);near(structure.hp,1e7);near(a[5].hp,1e7);const damage=w.stats.damage;w.time=1.99;tickZergHero(w,u,1/60);near(w.stats.damage,damage);w.time=2;tickZergHero(w,u,1/60);near(w.stats.damage-damage,2400);});
test('Leviathan retains three separately timed frozen storms after launch; one caster death cannot replay or erase committed pulses',()=>{const {w,u}=setup('hots_leviathan'),a=target(w,5);assert.ok(w.castHero('hots_leviathan'));assert.equal(w.heroCasts.length,3);advance(w,.85,true);near(1e7-a.hp,2760);u.hp=0;u.rank=5;advance(w,1.65,true);near(1e7-a.hp,8280);assert.equal(w.heroCasts.length,0);advance(w,2,true);near(1e7-a.hp,8280);});

test('Zerg auras are fixed rank-independent real rules; leaving or source death preserves body losses and weapon clocks',()=>{const {w,u}=setup('kerrigan'),a=w.addUnit('roach','terran',2,0);refreshGroundHeroBuffs(w);const damage=a.weaponDamage;a.hp-=20;a.weaponCooldown=.4;a.nextShotAt=3;u.x=20;refreshGroundHeroBuffs(w);near(damage/a.weaponDamage,1);near(a.maxHp-a.hp,20);near(a.weaponCooldown,.4);near(a.nextShotAt,3);u.x=0;u.rank=5;refreshGroundHeroBuffs(w);near(a.weaponDamage,damage);u.hp=0;refreshGroundHeroBuffs(w);near(damage/a.weaponDamage,1.5);near(a.maxHp-a.hp,20/1.35);});
test('Zerg debuffs affect real Boss weapon once at full strength and exclude structures; biological armor is after stat multipliers',()=>{for(const id of ['zagara','dehaka','stukov'] as const){const {w,u}=setup(id),a=target(w);a.enemyTier='boss';if(id==='zagara')near(w.enemyAttackSpeedFactor(a),.55);if(id==='dehaka')near(heroGroundSuppression(w,a),.5);if(id==='stukov'){near(heroWeaponVulnerability(w,a),1.45);const hp=a.hp;w.hit(a,100,[],1,'terran',0,1,u.id,false,false,0,true);near(hp-a.hp,145);}a.attributes.push('Structure');near(w.enemyAttackSpeedFactor(a),1);near(heroGroundSuppression(w,a),0);near(heroWeaponVulnerability(w,a),1);}const {w,u}=setup('niadra'),a=w.addUnit('roach','terran',2,0),armor=a.armor;u.x=20;refreshGroundHeroBuffs(w);near(armor-a.armor,10);});

for(const id of ['zagara','stukov','hots_leviathan'] as const)test(`schema18 ${id} saves primary flights and pending fixed pulses, restores paused, and resumes exactly once`,()=>{const {w,u}=setup(id,3),a=target(w,5);w.fire(u,a);assert.ok(w.castHero(id));advance(w,.05,true);const saved=w.captureRun();assert.equal(saved.schema,RUN_SCHEMA);const copy=setup(id).w;copy.restoreRun(saved);assert.equal(copy.paused,true);copy.step();assert.deepEqual(copy.heroAttacks,w.heroAttacks);advance(w,5,true);advance(copy,5,true);near(copy.entities.get(a.id)!.hp,w.entities.get(a.id)!.hp);near(copy.stats.damage,w.stats.damage);assert.deepEqual(copy.heroCasts,w.heroCasts);assert.equal(copy.heroAttackEvents.filter(e=>e.kind==='launch').length,0);});
test('schema18 preserves dead revival snapshots after corpse cleanup, essence, reserve, infection and parasite receipts',()=>{const {w,u}=setup('niadra',3),[a]=roster(w);assert.ok(w.acquireHero('dehaka'));assert.ok(w.acquireHero('stukov'));const de=w.heroEntity('dehaka')!,st=w.heroEntity('stukov')!,host=target(w);w.fire(u,host);w.fire(st,host);advance(w,.3);registerZergRevival(w,u,w.nextId++,3);kill(w,a);w.entities.delete(a.id);Object.assign(zergState(de),{essence:30,reserve:1000,reserveMax:1000,reserveUntil:8,biologicalUntil:8});const snapshot=w.captureRun(),copy=setup('niadra').w;copy.restoreRun(snapshot);assert.deepEqual(copy.zergHeroes,w.zergHeroes);assert.deepEqual(copy.entities.get(de.id)!.zergCombat,de.zergCombat);w.time=copy.time=1.3;tickZergHeroState(w);tickZergHeroState(copy);assert.equal(copy.entities.get(a.id)!.id,a.id);near(copy.entities.get(a.id)!.hp,w.entities.get(a.id)!.hp);assert.equal(copy.zergHeroes.revivals[0].charges,2);});
test('schema18 rejects forged revival bodies, duplicate identities, NaN passive and invalid fixed receipts before changing World',()=>{const {w,u}=setup('niadra'),[a]=roster(w);registerZergRevival(w,u,w.nextId++,1);kill(w,a);const before=w.captureRun();for(const mutation of [(s:any)=>s.state.zergHeroes.revivals[0].seats[0].members[0].x=NaN,(s:any)=>s.state.zergHeroes.revivals[0].seats[0].family='marine',(s:any)=>s.state.zergHeroes.revivals[0].charges=5,(s:any)=>s.state.zergHeroes.revivals[0].seats.push(structuredClone(s.state.zergHeroes.revivals[0].seats[0])),(s:any)=>s.state.entities.get(u.id).zergCombat.essence=NaN]){const bad=structuredClone(before);mutation(bad);assert.throws(()=>w.restoreRun(bad),/复生|虫族/);assert.deepEqual(w.captureRun(),before);}});
test('Foot auras retain visual layers without labels in both production adapters; approved attacks and skills stay intact',()=>{const z=fs.readFileSync('src/render/effects/zerg-hero-effects.ts','utf8'),t=fs.readFileSync('src/render/effects/confirmed-hero/controller.ts','utf8');assert.match(z,/this\.aura\.render\(visible\)/);assert.match(t,/this\.aura\.render\(visible\)/);assert.match(t,/this\.aura\.prepare\(\)/);const aura=fs.readFileSync('src/render/effects/confirmed-hero/hero-aura-effects.ts','utf8');assert.match(aura,/textLabels:0/);assert.match(z,/model\.baneling/);assert.match(z,/projectiles\.batches\.get\('hydralisk'\)/);assert.doesNotMatch(z,/\.hit\(|\.random\(/);});
