import type {World} from '../simulation/world';import type {ExpeditionReward} from '../simulation/progression/expedition-drafts';import {observeWorld,rememberObservationSource,observationIdentity,type ContributionKind} from '../simulation/observation';import {diagnosticHealthLock} from '../diagnostics/combat-lock';import {IDENTITIES} from '../../tools/backend/contracts.mjs';import type {TelemetryClient,TelemetryEvent} from './telemetry-client';
type Counts={id:string;damage:number;healed:number;shieldRestored:number;deaths:number;revivals:number};
type Roster={id:string;rank:number;count:number};
type Summary=Record<string,unknown>&{status:string;seconds:number;runSeconds:number;partial:boolean};
const empty=(id:string):Counts=>({id,damage:0,healed:0,shieldRestored:0,deaths:0,revivals:0});
/** Reads approved state; all totals live outside World and its saved graph. */
export class GameObserver {
 private observedRun:string|null=null;private key='';private previousTime=0;private runSeconds=0;private seconds=0;private highTime=0;private phase='';private partial=true;private started=false;private lastHeart=0;private consentId='';private ended='';
 private counts=new Map<string,Counts>();private roster=new Map<string,Roster>();private offers=new Map<string,{offer:ExpeditionReward;sold:boolean}>();private orders=new Set<number>();private rerolls=0;private histogram=new Map<number,number>();private frames=0;private longFrames=0;private peak=0;private firstBacklog=0;private lastBacklog=0;private kills=0;private killBase=0;
 constructor(readonly world:World,readonly client:TelemetryClient,readonly environment:()=>Pick<TelemetryEvent,'build'|'release'|'device'|'orientation'|'animation'|'diagnostic'>){world.listeners.add(()=>{try{this.changed();}catch{}});}
 syncConsent(){const id=this.client.active?this.client.identity?.consentId??'':'';if(id===this.consentId)return;this.consentId=id;observeWorld(this.world,null);this.observedRun=null;this.key='';this.offers.clear();this.orders.clear();this.started=false;if(!id)return;observeWorld(this.world,(id,kind,value)=>this.amount(id,kind,value));this.emit('session_start',{},null);this.changed();}
 private diagnostic(){return this.environment().diagnostic||this.world.diagnosticRun||diagnosticHealthLock(this.world).enabled;}
 private emit(kind:string,data:Record<string,unknown>,runId=this.world.runId,id?:string){this.client.record({...this.environment(),diagnostic:this.diagnostic(),kind,data,runId,...(id?{id}:{})});}
 private amount(id:string,kind:ContributionKind,value:number){if(!this.client.active||!this.observedRun||this.world.runId!==this.observedRun||this.world.time+1e-8<this.highTime)return;if(!IDENTITIES.has(id))id='unattributed';const row=this.counts.get(id)??empty(id);row[kind]+=value;this.counts.set(id,row);}
 private resetStage(partial:boolean){this.counts.clear();this.roster.clear();this.histogram.clear();this.frames=this.longFrames=this.peak=this.seconds=this.kills=0;this.firstBacklog=this.lastBacklog;this.killBase=this.world.stats.kills;this.partial=partial;this.key=this.stageKey();this.phase=this.world.phase;this.updateRoster();}
 private stageKey(){return `${this.world.runId}:${this.world.endless?'endless':'campaign'}:${this.world.endless?.round??this.world.stage}`;}
 private updateRoster(){const current=new Map<string,Roster>();for(const u of this.world.allies()){rememberObservationSource(this.world,u);if(u.temporary||u.summonKind||u.hp<=0)continue;const id=observationIdentity(this.world,u);if(!IDENTITIES.has(id))continue;const old=current.get(id)??{id,rank:1,count:0};old.rank=Math.max(old.rank,u.rank);old.count++;current.set(id,old);}const support=this.world.expedition.support;for(const [id,rank]of Object.entries({...support.unique.levels,...Object.fromEntries(Object.entries(support.levels).map(([id,rank])=>[this.world.expedition.race+'.'+id,rank])),...(support.ammo>0?{[this.world.expedition.race+'.strategic']:1}:{})}))if(rank&&IDENTITIES.has(id))current.set(id,{id,rank,count:1});for(const [id,row]of current){const old=this.roster.get(id);this.roster.set(id,{id,rank:Math.max(row.rank,old?.rank??1),count:Math.max(row.count,old?.count??0)});}}
 private quantile(q:number){const target=Math.ceil(this.frames*q);let n=0;for(const [ms,count]of [...this.histogram].sort((a,b)=>a[0]-b[0])){n+=count;if(n>=target)return ms/10;}return 0;}
 summary(status='reached'):Summary{const w=this.world,rows=[...this.counts.values()],total=(k:ContributionKind)=>rows.reduce((n,r)=>n+r[k],0);return {race:w.expedition.race,difficulty:w.difficulty,stage:w.endless?.round??w.stage,mode:w.endless?'endless':'campaign',playerLevel:Math.min(80,w.runConfig?.frozenTalents.allocated??0),seconds:this.seconds,runSeconds:this.runSeconds,status,partial:this.partial,damage:total('damage'),healed:total('healed'),shieldRestored:total('shieldRestored'),deaths:total('deaths'),revivals:total('revivals'),kills:this.kills,roster:[...this.roster.values()],contributions:rows,talents:{...(w.runConfig?.frozenTalents.levels??{})},research:Object.fromEntries(Object.entries(w.expedition.tech).filter(([k])=>/^research\..+\.(weapon|defense)$/.test(k))),performance:{p95:this.quantile(.95),p99:this.quantile(.99),frames:this.frames,longFrames:this.longFrames,peakUnits:this.peak,backlogDelta:Math.max(0,this.lastBacklog-this.firstBacklog)}};}
 private stage(status:string){this.emit('stage_summary',this.summary(status),this.observedRun,`${this.key}:${status}`.replace(':campaign:',':stage:campaign:').replace(':endless:',':stage:endless:'));}
 private begin(){const w=this.world;this.observedRun=w.runId;this.runSeconds=0;this.highTime=this.previousTime=w.time;this.ended='';this.resetStage(w.time>.001);this.started=true;this.offers.clear();this.orders=new Set(w.expedition.ledger.map(j=>j.id));this.rerolls=w.economyTotals.rerolls;const saved=this.client.readObservation();if(saved?.version===1&&saved.consentId===this.consentId&&saved.runId===w.runId&&saved.savedAt>Date.now()-86400000){this.runSeconds=Math.max(0,saved.runSeconds??0);if(Number.isFinite(saved.lastHeart)&&saved.lastHeart<=Date.now())this.lastHeart=saved.lastHeart;this.highTime=Math.max(w.time,saved.time??0);if(saved.key===this.key&&w.time+1e-8>=saved.time&&Array.isArray(saved.counts)&&Array.isArray(saved.roster)){for(const r of saved.counts)if(IDENTITIES.has(r.id)&&['damage','healed','shieldRestored','deaths','revivals'].every(k=>Number.isFinite(r[k])&&r[k]>=0))this.counts.set(r.id,r);for(const r of saved.roster)if(IDENTITIES.has(r.id)&&r.rank>=1&&r.rank<=7)this.roster.set(r.id,r);this.seconds=Math.max(0,saved.seconds??0);this.partial=true;}}
  if(w.time<=.001&&saved?.runId!==w.runId)this.emit('run_start',this.summary(),w.runId,`${w.runId}:start:new:0:reached`);else this.emit('run_resume',this.summary());this.stage('reached');}
 changed(){if(!this.client.active)return;const w=this.world;if(w.phase==='menu'||!w.runId){if(this.observedRun){this.persist();this.observedRun=null;}return;}if(w.runId!==this.observedRun)this.begin();const delta=Math.max(0,w.time-Math.max(this.previousTime,this.highTime));this.previousTime=w.time;if(delta){this.runSeconds+=delta;this.seconds+=delta;this.highTime=Math.max(this.highTime,w.time);}if(this.key!==this.stageKey()){this.resetStage(w.stageElapsed>.001);this.stage('reached');}this.updateRoster();this.kills=Math.max(this.kills,w.stats.kills-this.killBase);if(this.phase!==w.phase){if(w.phase==='reward')this.stage('cleared');else if(w.phase==='won')this.stage('won');else if(w.phase==='lost')this.stage('failed');this.phase=w.phase;}
  const end=w.phase==='lost'?'failed':w.phase==='finished'?'evacuated':'';if(end&&this.ended!==end){this.emit('run_end',this.summary(end),w.runId,`${w.runId}:end:${w.endless?'endless':'campaign'}:${w.endless?.round??w.stage}:${end}`);this.ended=end;}this.observeEconomy();}
 frame(milliseconds:number,backlog:number,simulating:boolean){if(!this.client.active)return;this.syncConsent();this.changed();if(!this.observedRun)return;const w=this.world;this.lastBacklog=backlog;if(simulating&&milliseconds>0&&milliseconds<=60000){const bin=Math.round(milliseconds*10);this.histogram.set(bin,(this.histogram.get(bin)??0)+1);this.frames++;if(milliseconds>20)this.longFrames++;this.peak=Math.max(this.peak,w.entities.size);}}
 pulse(){this.syncConsent();if(!this.client.active)return;this.changed();if(this.observedRun&&this.world.phase==='battle'&&!this.world.paused&&Date.now()-this.lastHeart>=60000){this.lastHeart=Date.now();this.emit('heartbeat',this.summary());}this.persist();this.client.persist();void this.client.flush();}
 persist(){if(!this.observedRun)return;this.client.writeObservation({version:1,consentId:this.consentId,runId:this.observedRun,key:this.key,time:this.highTime,seconds:this.seconds,runSeconds:this.runSeconds,lastHeart:this.lastHeart,counts:[...this.counts.values()],roster:[...this.roster.values()],savedAt:Date.now()});}
 leaving(){if(this.client.active&&this.observedRun){this.changed();if(!this.ended)this.stage(this.world.phase==='reward'?'cleared':this.world.phase==='won'?'won':'incomplete');this.persist();this.client.persist();}}
 private async card(id:string,action:string,quality:string,level:number,minerals:number,gas:number,key:string){const consentId=this.consentId,env={...this.environment(),diagnostic:this.diagnostic()},runId=this.world.runId,mode=this.world.endless?'endless':'campaign',stage=this.world.endless?.round??this.world.stage;try{const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(runId+':'+key))),hex=[...hash.slice(0,16)].map(b=>b.toString(16).padStart(2,'0')).join(''),eventId=hex.slice(0,8)+'-'+hex.slice(8,12)+'-4'+hex.slice(13,16)+'-8'+hex.slice(17,20)+'-'+hex.slice(20,32);if(consentId!==this.consentId||!this.client.active)return;this.client.record({...env,id:eventId,runId,kind:'card',data:{id,action,quality,level:Math.min(80,level),minerals,gas,mode,stage}});}catch{}}
 private cardLevel(r:ExpeditionReward){const e=r.expeditionEffect,w=this.world;if(!e)return 0;switch(e.kind){case 'support':return e.support==='strategic'?w.expedition.support.ammo:({...w.expedition.support.levels,...w.expedition.support.unique.levels} as Record<string,number>)[e.support]??0;case 'hero':return [...w.heroes.values()].find(h=>h.id===e.heroId)?.rank??0;case 'elite':return Math.max(0,...w.allies().filter(u=>u.eliteId===e.eliteId).map(u=>u.rank));case 'training':return e.rank;case 'card':return w.expedition.cardTotals[e.key]??0;case 'teamCard':return w.expedition.cardTotals['team.'+e.group+'.'+e.rarity]??0;case 'development':return e.expectedLevel;default:return 0;}}
 private observeEconomy(){const w=this.world;for(const [key,state]of this.offers){if(!state.sold&&state.offer.sold){state.sold=true;const r=state.offer,p=r.purchaseReceipt;void this.card(r.id,p?'purchased':'claimed',r.rarity,this.cardLevel(r),p?.minerals??0,p?.gas??0,key+':claim');}}
  const visible=[...(w.phase==='reward'?w.rewards:[]),...(w.expedition.pendingTalentLoot?.offers??[]),...(w.expedition.bossLootOpen?w.expedition.bossLootQueue.map(e=>e.reward):[])];for(const reward of visible){const r=reward as ExpeditionReward,key=r.offerId;if(this.offers.has(key))continue;this.offers.set(key,{offer:r,sold:!!r.sold});if(!r.sold)void this.card(r.id,'shown',r.rarity,this.cardLevel(r),0,0,key+':shown');}if(this.offers.size>200)for(const key of [...this.offers.keys()].slice(0,this.offers.size-200))this.offers.delete(key);
  for(const job of w.expedition.ledger){if(this.orders.has(job.id))continue;this.orders.add(job.id);const p=job.passengers;void this.card('production.'+job.family,p.some(p=>p.purpose!=='body')?'trained':'reinforced','none',p.length,p.reduce((n,p)=>n+p.paid.minerals,0),p.reduce((n,p)=>n+p.paid.gas,0),'production:'+job.id);}if(this.orders.size>1024)this.orders=new Set(w.expedition.ledger.map(j=>j.id));if(w.economyTotals.rerolls>this.rerolls){void this.card('shop.refresh','refreshed','none',0,w.economyTotals.rerolls-this.rerolls,0,'refresh:'+w.draftWindowId+':'+w.expedition.refreshCount);this.rerolls=w.economyTotals.rerolls;}}
}
