import {CONSENT_VERSION,validateEvent} from '../../tools/backend/contracts.mjs';
export type PublicDataConfig={enabled:boolean;version:string;operator:string;contact:string;backupDays:number|null;retention:Record<string,number>};
export type TelemetryEvent={id:string;sessionId:string;runId:string|null;kind:string;at:number;build:string;release:string;device:'desktop'|'mobile';orientation:'portrait'|'landscape';animation:string;diagnostic:boolean;data:Record<string,unknown>};
type Identity={visitorId:string;privacySecret:string;consentId?:string;uploadToken?:string;version:string;status:'active'|'pending'|'withdrawn';optedAt:number};
type Revocation={visitorId:string;privacySecret:string;remove:boolean};
export const TELEMETRY_KEYS={identity:'sc2.telemetry.identity.v1',queue:'sc2.telemetry.queue.v1',revocation:'sc2.telemetry.revocation.v1',observation:'sc2.telemetry.observation.v1'};
const defaults:PublicDataConfig={enabled:false,version:CONSENT_VERSION,operator:'',contact:'',backupDays:null,retention:{events:90,runs:180,visitors:365,daily:730,feedback:180,audit:90}};
let localLock:Promise<unknown>=Promise.resolve();
/** Independent, bounded, best-effort transport. No World, RNG, saves or resource cache access. */
export class TelemetryClient {
 config:PublicDataConfig={...defaults};identity:Identity|null=null;queue:TelemetryEvent[]=[];dropped=0;onChange=()=>{};sessionId:string|null=null;
 private controller:AbortController|null=null;private flushing=false;private epoch=0;private initialized=false;private pending=new Map<string,TelemetryEvent>();
 constructor(private options:{storage?:Storage;request?:typeof fetch;protocol?:string;now?:()=>number;uuid?:()=>string;secret?:()=>string}={}){}
 private get now(){return this.options.now??Date.now;}private get storage(){return this.options.storage;}
 private uuid(){return (this.options.uuid??(()=>crypto.randomUUID()))();}
 private secret(){return (this.options.secret??(()=>{const bytes=crypto.getRandomValues(new Uint8Array(32));return btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}))();}
 get offline(){return (this.options.protocol??location.protocol)==='file:';}
 get active(){return !this.offline&&this.config.enabled&&this.config.version===CONSENT_VERSION&&this.identity?.status==='active'&&this.identity.version===CONSENT_VERSION;}
 get pendingPrivacy(){return !!this.read(TELEMETRY_KEYS.revocation);}
 private read(key:string):any {try{return JSON.parse(this.storage?.getItem(key)??'null');}catch{return null;}}
 private write(key:string,value:unknown){try{if(value===null)this.storage?.removeItem(key);else this.storage?.setItem(key,JSON.stringify(value));}catch{}}
 private notify(){try{this.onChange();}catch{}}
 private exclusive<T>(work:()=>Promise<T>):Promise<T>{if(typeof navigator!=='undefined'&&navigator.locks)return navigator.locks.request('sc2.telemetry.v1',work);const next=localLock.then(work,work);localLock=next.catch(()=>{});return next;}
 private current(){const saved=this.read(TELEMETRY_KEYS.identity) as Identity|null;return this.active&&(!this.storage||saved?.status==='active'&&saved.consentId===this.identity?.consentId);}
 async api(path:string,data?:unknown,headers:Record<string,string>={},signal?:AbortSignal){if(this.offline)throw Error('offline');const request=this.options.request??fetch;const res=await request(path,{method:data===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:data===undefined?{}:{'Content-Type':'application/json','X-SC2-Client':'1',...headers},body:data===undefined?undefined:JSON.stringify(data),signal:signal??AbortSignal.timeout(10000)});const result=await res.json().catch(()=>({}));if(!res.ok){const e=Object.assign(Error(result.error??'network_error'),{status:res.status});throw e;}return result;}
 async initialize(){if(this.initialized)return;this.initialized=true;if(this.offline)return;try{const c=await this.api('/api/config');if(typeof c.enabled!=='boolean'||typeof c.version!=='string')return;this.config=c;this.identity=this.read(TELEMETRY_KEYS.identity);if(this.identity?.version!==CONSENT_VERSION&&this.identity){await this.withdraw(false);return;}if(this.active){const values=this.read(TELEMETRY_KEYS.queue);this.queue=Array.isArray(values)?values.filter(e=>{try{validateEvent(e,this.now());return e.at>=this.identity!.optedAt;}catch{return false;}}):[];this.trim();this.startSession();}else this.queue=[];await this.retryPrivacy();}catch{this.config={...defaults};}this.notify();}
 private startSession(){this.sessionId=this.uuid();}
 async allow(){return this.exclusive(async()=>{if(this.offline||!this.config.enabled||this.config.version!==CONSENT_VERSION)throw Error('service_unavailable');if(this.pendingPrivacy){await this.retryPrivacy();if(this.pendingPrivacy)throw Error('privacy_pending');}const prior=this.read(TELEMETRY_KEYS.identity) as Identity|null??this.identity;if(prior?.status==='active'&&prior.version===CONSENT_VERSION){this.identity=prior;if(!this.sessionId)this.startSession();this.notify();return;}const identity:Identity=prior?.status==='pending'&&prior.version===CONSENT_VERSION?prior:{visitorId:prior?.visitorId??this.uuid(),privacySecret:prior?.privacySecret??this.secret(),consentId:this.uuid(),uploadToken:this.secret(),version:CONSENT_VERSION,status:'pending',optedAt:this.now()};this.identity=identity;this.write(TELEMETRY_KEYS.identity,identity);const epoch=++this.epoch;await this.api('/api/telemetry/consent',{visitorId:identity.visitorId,privacySecret:identity.privacySecret,consentId:identity.consentId,uploadToken:identity.uploadToken,version:identity.version});const disk=this.read(TELEMETRY_KEYS.identity) as Identity|null;if(epoch!==this.epoch||this.storage&&(disk?.status!=='pending'||disk?.consentId!==identity.consentId))return;identity.status='active';identity.optedAt=this.now();this.queue=[];this.pending.clear();this.write(TELEMETRY_KEYS.observation,null);this.write(TELEMETRY_KEYS.identity,identity);this.write(TELEMETRY_KEYS.queue,[]);this.startSession();this.notify();});}
 async withdraw(remove=false){const identity=this.read(TELEMETRY_KEYS.identity)??this.identity;this.epoch++;this.controller?.abort();this.controller=null;this.queue=[];this.pending.clear();this.sessionId=null;this.write(TELEMETRY_KEYS.queue,null);this.write(TELEMETRY_KEYS.observation,null);if(identity){const existing=this.read(TELEMETRY_KEYS.revocation) as Revocation|null;this.write(TELEMETRY_KEYS.revocation,{visitorId:identity.visitorId,privacySecret:identity.privacySecret,remove:remove||existing?.remove||false});this.identity={visitorId:identity.visitorId,privacySecret:identity.privacySecret,version:identity.version,status:'withdrawn',optedAt:identity.optedAt};this.write(TELEMETRY_KEYS.identity,this.identity);}this.notify();await this.retryPrivacy();this.notify();}
 async retryPrivacy(){if(this.offline)return;const pending=this.read(TELEMETRY_KEYS.revocation) as Revocation|null;if(!pending)return;try{await this.api('/api/privacy/'+(pending.remove?'delete':'withdraw'),{visitorId:pending.visitorId,privacySecret:pending.privacySecret});if(JSON.stringify(this.read(TELEMETRY_KEYS.revocation))!==JSON.stringify(pending))return;this.write(TELEMETRY_KEYS.revocation,null);if(pending.remove){this.identity=null;this.write(TELEMETRY_KEYS.identity,null);}}catch{}}
 /** A storage event from another tab is an immediate local stop, even if the network is down. */
 synchronize(){const next=this.read(TELEMETRY_KEYS.identity) as Identity|null;if(!next||next.status!=='active'||next.consentId!==this.identity?.consentId){this.epoch++;this.controller?.abort();this.queue=[];this.pending.clear();this.sessionId=null;}this.identity=next;if(this.active&&!this.sessionId)this.startSession();this.notify();}
 record(input:Omit<TelemetryEvent,'id'|'sessionId'|'at'>&{id?:string}){if(!this.current()||!this.sessionId)return;const e={...input,id:input.id??this.uuid(),sessionId:this.sessionId,at:this.now()};try{validateEvent(e,this.now());}catch{this.dropped++;return;}this.queue=this.queue.filter(row=>row.id!==e.id);this.queue.push(e);this.pending.set(e.id,e);this.trim();}
 private trim(){const before=this.queue.length;this.queue=this.queue.filter(e=>e.at>=this.now()-86400000);let bytes=JSON.stringify(this.queue).length*3;while(this.queue.length>200||bytes>256*1024){const i=this.queue.findIndex(e=>e.kind==='heartbeat');this.queue.splice(i<0?0:i,1);bytes=JSON.stringify(this.queue).length*3;}const kept=new Set(this.queue.map(e=>e.id));for(const id of this.pending.keys())if(!kept.has(id))this.pending.delete(id);this.dropped+=before-this.queue.length;}
 private async merge(accepted=new Map<string,TelemetryEvent>()){await this.exclusive(async()=>{if(!this.current())return;const disk=this.read(TELEMETRY_KEYS.queue),rows:TelemetryEvent[]=Array.isArray(disk)?disk:[],merged=new Map<string,TelemetryEvent>();for(const e of [...rows,...this.pending.values()]){try{validateEvent(e,this.now());if((!accepted.has(e.id)||JSON.stringify(accepted.get(e.id))!==JSON.stringify(e))&&e.at>=this.identity!.optedAt)merged.set(e.id,e);}catch{}}this.queue=[...merged.values()].sort((a,b)=>a.at-b.at);this.trim();this.write(TELEMETRY_KEYS.queue,this.queue);this.pending.clear();});}
 async persist(){if(!this.active)return;this.trim();if(this.storage)await this.merge();}
 readObservation(){return this.active?this.read(TELEMETRY_KEYS.observation):null;}
 writeObservation(value:unknown){if(this.active)this.write(TELEMETRY_KEYS.observation,value);}
 async flush(){if(!this.current()||this.flushing)return;this.flushing=true;await this.persist();if(!this.current()||!this.queue.length){this.flushing=false;return;}const epoch=this.epoch,controller=this.controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),10000),values:TelemetryEvent[]=[];for(const e of this.queue){if(values.length===32||JSON.stringify({events:[...values,e]}).length*3>64000)break;values.push(e);}if(!values.length){const large=this.queue.shift()!;await this.merge(new Map([[large.id,large]]));this.flushing=false;clearTimeout(timeout);return;}try{const result=await this.api('/api/telemetry/batch',{events:values},{'X-SC2-Token':this.identity!.uploadToken!},controller.signal);if(epoch!==this.epoch||!this.current())return;const ids=new Set<string>(Array.isArray(result.accepted)?result.accepted:[]),accepted=new Map(values.filter(e=>ids.has(e.id)).map(e=>[e.id,e]));this.queue=this.queue.filter(e=>!accepted.has(e.id)||JSON.stringify(accepted.get(e.id))!==JSON.stringify(e));if(this.storage)await this.merge(accepted);}catch(e){if((e as {status?:number}).status===401||((e as {status?:number}).status===409)){await this.withdraw(false);}}finally{clearTimeout(timeout);this.flushing=false;this.controller=null;await this.persist();}}
}
