import * as THREE from 'three';
import {GLTFLoader, type GLTF} from 'three/addons/loaders/GLTFLoader.js';
import {clone as cloneSkeleton} from 'three/addons/utils/SkeletonUtils.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {restoreSc2Materials,sc2BodyBounds} from '../../src/render/loaders/sc2-materials';

type HeroId='raynor'|'tychus'|'nova'|'swann'|'tosh'|'yamato_battlecruiser';
type Archive={models:Record<string,string>;textures:Record<string,string>;sources:unknown[]};
type Actor={root:THREE.Group;model:THREE.Object3D;mixer:THREE.AnimationMixer;actions:Record<string,THREE.AnimationAction>;clips:THREE.AnimationClip[];scale:number;hitUntil:number;materials:THREE.MeshStandardMaterial[]};
type Particle={p:THREE.Vector3;v:THREE.Vector3;life:number;born:number;width:number;height:number;growth:number;color:THREE.Color;opacity:number;rotation:number;spin:number;gravity:number;direction?:THREE.Vector3;atlas:number;frames:number;frame:number;motion?:'shell'|'spark'};
type Projectile={from:THREE.Vector3;to:THREE.Vector3;born:number;duration:number;hero:HeroId;power:boolean;cycle:number;target:number;object?:THREE.Object3D;lastTrail:THREE.Vector3};
const descriptions:Record<HeroId,{name:string;weapon:string;accent:string;period:number;note:string}>={
 raynor:{name:'雷诺',weapon:'穿甲步枪',accent:'#e6bd77',period:.2,note:'枪口火舌、分离曳光、抛壳与穿甲命中。'},
 tychus:{name:'泰凯斯',weapon:'重型机枪',accent:'#e8a675',period:.1,note:'持续预热、密集曳光、热焰与散热余烟。'},
 nova:{name:'诺娃',weapon:'能量狙击枪',accent:'#88d5e6',period:.5,note:'针状弹芯、细长能量尾迹与电离命中。'},
 swann:{name:'斯旺',weapon:'重型榴弹发射器',accent:'#d5b984',period:.3,note:'原型榴弹、推进焰、金属碎片与烟尘。'},
 tosh:{name:'托什',weapon:'灵能步枪',accent:'#ce9cad',period:.3,note:'灵能弹芯、螺旋丝线与精神裂爆。'},
 yamato_battlecruiser:{name:'大和战列巡洋舰',weapon:'双联重型炮',accent:'#e1a68a',period:.2,note:'两个真实炮位连续齐射，独立弹道与重型命中。'},
};
const $=(id:string)=>document.getElementById(id)!;
const archive:Archive=JSON.parse($('archive').textContent!);$('archive').remove();
const viewport=$('viewport'),scene=new THREE.Scene();scene.background=new THREE.Color('#17202b');scene.fog=new THREE.FogExp2('#17202b',.012);
const camera=new THREE.PerspectiveCamera(38,1,.08,150);camera.position.set(4.3,7.2,10.3);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.info.autoReset=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;viewport.append(renderer.domElement);
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,.8,0);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=7;controls.maxDistance=29;controls.minPolarAngle=.15;controls.maxPolarAngle=Math.PI*.46;controls.maxTargetRadius=3.5;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(1,1),.45,.28,1.1);composer.addPass(bloom);composer.addPass(new OutputPass());
scene.add(new THREE.HemisphereLight(0xbacde0,0x51565c,2.0));const sun=new THREE.DirectionalLight(0xffe8d0,3);sun.position.set(-4,10,6);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);sun.shadow.camera.left=-13;sun.shadow.camera.right=13;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;sun.shadow.bias=-.0004;sun.shadow.normalBias=.025;scene.add(sun);const rim=new THREE.DirectionalLight(0x81bdcf,1.6);rim.position.set(4,4,-6);scene.add(rim);
const muzzleLight=new THREE.PointLight(0xffae50,0,3,2),impactLight=new THREE.PointLight(0xffad67,0,4,2);scene.add(muzzleLight,impactLight);
const targetPoint=new THREE.Vector3(3.65,.75,0),targetPositions=[new THREE.Vector3(3.65,0,0),new THREE.Vector3(4.35,0,2),new THREE.Vector3(4.35,0,-2),new THREE.Vector3(4.1,2.8,-1)];
const targetGroup=new THREE.Group();scene.add(targetGroup);let shooter:Actor|undefined,targets:Actor[]=[],hero:HeroId='raynor',rank=1,paused=false,ready=false,speed=1,clock=0,fireStarted=0,nextShot=.35,cycle=0,shotCount=0,hitCount=0,selection=0,bloomOn=true,muzzleUntil=0,impactUntil=0,view='close';
const projectedFrameTimes:number[]=[],warnings:string[]=[];const models=new Map<string,GLTF>(),textures=new Map<string,THREE.Texture>(),projectiles:Projectile[]=[];
const zero=new THREE.Vector3(),yAxis=new THREE.Vector3(0,1,0),localForward=new THREE.Vector3(0,0,1),tempV=new THREE.Vector3(),tempQ=new THREE.Quaternion(),tempM=new THREE.Matrix4(),tempO=new THREE.Object3D();
let seed=8721;function rand(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}const signed=()=>rand()*2-1;
function floorTexture(){const c=document.createElement('canvas');c.width=c.height=1024;const cx=c.getContext('2d')!;cx.fillStyle='#4b5051';cx.fillRect(0,0,1024,1024);let noise=7364;for(let i=0;i<34000;i++){noise=(Math.imul(noise,1664525)+1013904223)>>>0;const v=noise%44;cx.fillStyle='rgba('+v+','+v+','+v+',.12)';cx.fillRect((noise>>>8)%1024,(noise>>>19)%1024,2,2);}cx.strokeStyle='#6a6c67';cx.lineWidth=2;for(let i=0;i<1024;i+=128){cx.beginPath();cx.moveTo(i,0);cx.lineTo(i,1024);cx.moveTo(0,i);cx.lineTo(1024,i);cx.stroke();}cx.strokeStyle='#b3a06e';cx.lineWidth=8;cx.strokeRect(280,280,464,464);cx.setLineDash([24,20]);cx.strokeStyle='#929d99';cx.lineWidth=3;cx.beginPath();cx.moveTo(512,280);cx.lineTo(512,744);cx.stroke();const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;return t;}
const ground=new THREE.Mesh(new THREE.PlaneGeometry(28,28),new THREE.MeshStandardMaterial({map:floorTexture(),roughness:.97,metalness:.03}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
const boundary=new THREE.Mesh(new THREE.BoxGeometry(16,.22,.16),new THREE.MeshStandardMaterial({color:0x252e34,roughness:.8}));for(const z of [-6.4,6.4]){const b=boundary.clone();b.position.set(0,.1,z);b.receiveShadow=true;scene.add(b);}for(let i=0;i<12;i++){const pin=new THREE.Mesh(new THREE.BoxGeometry(.07,.015,.6),new THREE.MeshStandardMaterial({color:i%2?0xbaab81:0x8c9695,roughness:.9}));pin.position.set(-5.5+i,.022,4.6);scene.add(pin);}

class ParticleBatch{
 particles:Particle[]=[];mesh:THREE.InstancedMesh;uv:THREE.InstancedBufferAttribute;fade:THREE.InstancedBufferAttribute;col:THREE.InstancedBufferAttribute;
 constructor(public key:string,tex:THREE.Texture,public smoke=false){
  const geometry=new THREE.PlaneGeometry(1,1);this.uv=new THREE.InstancedBufferAttribute(new Float32Array(256*4),4);this.fade=new THREE.InstancedBufferAttribute(new Float32Array(256),1);this.col=new THREE.InstancedBufferAttribute(new Float32Array(256*3),3);geometry.setAttribute('cell',this.uv);geometry.setAttribute('fade',this.fade);geometry.setAttribute('tint',this.col);
  const material=new THREE.ShaderMaterial({uniforms:{map:{value:tex},smoke:{value:smoke?1:0}},vertexShader:'attribute vec4 cell;attribute float fade;attribute vec3 tint;varying vec2 vUv;varying float vFade;varying vec3 vTint;void main(){vUv=cell.xy+uv*cell.zw;vFade=fade;vTint=tint;gl_Position=projectionMatrix*modelViewMatrix*instanceMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D map;uniform float smoke;varying vec2 vUv;varying float vFade;varying vec3 vTint;void main(){vec4 t=texture2D(map,vUv);float a=t.a*vFade;if(smoke>.5){a*=smoothstep(.0,.12,dot(t.rgb,vec3(.333)));gl_FragColor=vec4(t.rgb*vTint,a);}else{gl_FragColor=vec4(t.rgb*vTint,a);}\n#include <tonemapping_fragment>\n#include <colorspace_fragment>\n}',transparent:true,depthWrite:false,depthTest:true,blending:smoke?THREE.NormalBlending:THREE.AdditiveBlending,side:THREE.DoubleSide,toneMapped:true});
  this.mesh=new THREE.InstancedMesh(geometry,material,256);this.mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.mesh.count=0;this.mesh.frustumCulled=false;this.mesh.renderOrder=smoke?3:4;scene.add(this.mesh);
 }
 add(p:Particle){if(this.particles.length>=256)this.particles.shift();this.particles.push(p);}
 update(dt:number){let count=0;for(let i=0;i<this.particles.length;){const p=this.particles[i],age=clock-p.born;if(age>=p.life){this.particles.splice(i,1);continue;}if(age<0){i++;continue;}p.v.y-=p.gravity*dt;p.p.addScaledVector(p.v,dt);if(p.motion==='spark'&&p.p.y<.04){p.p.y=.04;p.v.y=Math.abs(p.v.y)*.3;p.v.multiplyScalar(.45);}const q=age/p.life,opacity=p.opacity*Math.pow(1-q,this.smoke?.7:1.15),scale=1+p.growth*q;tempO.position.copy(p.p);if(p.direction){const a=p.direction.clone().normalize(),toward=camera.position.clone().sub(p.p).normalize(),right=new THREE.Vector3().crossVectors(a,toward).normalize(),normal=new THREE.Vector3().crossVectors(right,a);tempM.makeBasis(right,a,normal);tempO.quaternion.setFromRotationMatrix(tempM);}else{tempO.quaternion.copy(camera.quaternion);tempQ.setFromAxisAngle(localForward,p.rotation+p.spin*age);tempO.quaternion.multiply(tempQ);}tempO.scale.set(p.width*scale,p.height*scale,1);tempO.updateMatrix();this.mesh.setMatrixAt(count,tempO.matrix);this.fade.setX(count,opacity);this.col.setXYZ(count,p.color.r,p.color.g,p.color.b);const cols=p.atlas||1,frames=p.frames||1,frame=(Math.min(frames-1,Math.floor(q*frames))+p.frame)%frames,rows=Math.ceil(frames/cols);this.uv.setXYZW(count,(frame%cols)/cols,1-(Math.floor(frame/cols)+1)/rows,1/cols,1/rows);count++;i++;}this.mesh.count=count;this.mesh.instanceMatrix.needsUpdate=true;this.uv.needsUpdate=true;this.fade.needsUpdate=true;this.col.needsUpdate=true;}
 clear(){this.particles=[];this.mesh.count=0;}
}
const particles=new Map<string,ParticleBatch>();
function particle(key:string,p:THREE.Vector3,options:Partial<Particle>={}){const batch=particles.get(key);if(!batch)return;batch.add({p:p.clone(),v:new THREE.Vector3(),life:.3,born:clock,width:.45,height:.45,growth:.3,color:new THREE.Color(1,1,1),opacity:1,rotation:rand()*Math.PI*2,spin:0,gravity:0,atlas:1,frames:1,frame:0,...options});}
function glow(p:THREE.Vector3,color:THREE.Color,size:number,life=.08){particle('flare2b',p,{color,width:size,height:size,life,opacity:.75,growth:.8,rotation:0});}
function smoke(p:THREE.Vector3,size:number,heavy=false){particle('kenney-smoke_04',p,{color:new THREE.Color(heavy?.29:.5,heavy?.31:.51,heavy?.34:.53),width:size,height:size*.9,life:heavy?1.15:.65,opacity:heavy?.42:.28,growth:2.1,v:new THREE.Vector3(signed()*.4,.35+rand()*.35,signed()*.35),spin:signed()*.35});}
function sparks(p:THREE.Vector3,n:number,color:THREE.Color,force=3){for(let i=0;i<n;i++){const velocity=new THREE.Vector3(signed()*force,.5+rand()*force,signed()*force);particle('kenney-trace_05',p,{color,width:.06+rand()*.03,height:.24+rand()*.28,life:.18+rand()*.3,growth:-.45,v:velocity,direction:velocity.clone().normalize(),gravity:5,opacity:.85,motion:'spark'});}}
const shells=new THREE.InstancedMesh(new THREE.CylinderGeometry(.026,.028,.13,6),new THREE.MeshStandardMaterial({color:0xb79446,metalness:.78,roughness:.38}),192);shells.instanceMatrix.setUsage(THREE.DynamicDrawUsage);shells.frustumCulled=false;shells.castShadow=true;scene.add(shells);type Casing={p:THREE.Vector3;v:THREE.Vector3;born:number;spin:THREE.Vector3;rotation:THREE.Euler};const casings:Casing[]=[];
const flightCores=new THREE.InstancedMesh(new THREE.CylinderGeometry(.035,.035,1,6),new THREE.MeshBasicMaterial({color:0xffffff,toneMapped:true}),64);flightCores.instanceMatrix.setUsage(THREE.DynamicDrawUsage);flightCores.frustumCulled=false;flightCores.count=0;scene.add(flightCores);
function casing(p:THREE.Vector3){if(casings.length>=192)casings.shift();casings.push({p:p.clone().add(new THREE.Vector3(-.13,-.09,-.12)),v:new THREE.Vector3(-.4-rand()*.5,1.4+rand(),-1.8-rand()*1.4),born:clock,spin:new THREE.Vector3(rand()*12,rand()*15,rand()*10),rotation:new THREE.Euler(rand()*Math.PI,rand()*Math.PI,rand()*Math.PI)});}
function tickCasings(dt:number){let count=0;for(let i=0;i<casings.length;){const c=casings[i];if(clock-c.born>3){casings.splice(i,1);continue;}c.v.y-=9.8*dt;c.p.addScaledVector(c.v,dt);if(c.p.y<.04){c.p.y=.04;if(c.v.y<-.5)c.v.y*=-.25;else c.v.y=0;c.v.x*=.86;c.v.z*=.86;c.spin.multiplyScalar(.75);}c.rotation.x+=c.spin.x*dt;c.rotation.y+=c.spin.y*dt;c.rotation.z+=c.spin.z*dt;tempO.position.copy(c.p);tempO.rotation.copy(c.rotation);tempO.scale.setScalar(1);tempO.updateMatrix();shells.setMatrixAt(count++,tempO.matrix);i++;}shells.count=count;shells.instanceMatrix.needsUpdate=true;}
const waveGroup=new THREE.Group();scene.add(waveGroup);type Wave={mesh:THREE.Mesh;born:number;life:number;size:number;rotation:number};const waves:Wave[]=[];
function psionicWave(p:THREE.Vector3,large=false){const color=new THREE.Color(large?2.1:1.1,large?.55:1.9,large?1.1:2.8);for(let i=0;i<(large?14:6);i++){const a=i*Math.PI*2/(large?14:6),v=new THREE.Vector3(Math.cos(a)*(large?3.3:1.6),.3+rand()*.7,Math.sin(a)*(large?3.3:1.6));particle('energyplane3_red',p,{color,width:large?.19:.1,height:large?.55:.3,life:large?.26:.16,growth:.4,v,direction:v.clone().normalize(),opacity:.5});}particle('kenney-twirl_01',p,{color,width:large?.8:.45,height:large?.8:.45,life:large?.24:.13,spin:large?8:4,growth:1.3,opacity:.4});}
function tickWaves(){for(let i=waves.length-1;i>=0;i--){const w=waves[i],q=(clock-w.born)/w.life;if(q>=1){waveGroup.remove(w.mesh);w.mesh.geometry.dispose();(w.mesh.material as THREE.Material).dispose();waves.splice(i,1);continue;}w.mesh.scale.setScalar(.12+Math.sqrt(q)*w.size);(w.mesh.material as THREE.MeshBasicMaterial).opacity=(1-q)*.4;}}

function toBytes(base64:string){const raw=atob(base64),out=new Uint8Array(raw.length);for(let i=0;i<out.length;i++)out[i]=raw.charCodeAt(i);return out;}
const loader=new GLTFLoader();
async function loadAll(){let completed=0;const keys=Object.keys(archive.models);for(const key of keys){const buffer=toBytes(archive.models[key]).buffer;const model=await loader.parseAsync(buffer,'');await restoreSc2Materials(model);models.set(key,model);completed++;$('loading-text').textContent='正在准备英雄 '+completed+' / '+keys.length;}
 const tLoader=new THREE.TextureLoader();await Promise.all(Object.entries(archive.textures).map(async([key,value])=>{const t=await tLoader.loadAsync('data:image/png;base64,'+value);t.colorSpace=THREE.SRGBColorSpace;t.minFilter=THREE.LinearMipmapLinearFilter;t.magFilter=THREE.LinearFilter;t.generateMipmaps=true;textures.set(key,t);particles.set(key,new ParticleBatch(key,t,key==='kenney-smoke_04'||key==='smokelit'||key==='smoke_wispy11'||key==='kenney-smoke_09'));}));await choose('raynor');$('loading').hidden=true;ready=true;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.disabled=false;
}
function makeActor(key:string,height:number,width?:number):Actor{
 const original=models.get(key)!;const model=cloneSkeleton(original.scene);if(key==='nova'){const gun=model.getObjectByName('Bone_Gun');if(gun)gun.position.set(0,0,0);model.traverse(n=>{if(n instanceof THREE.SkinnedMesh&&!['M3_Mesh_6','M3_Mesh_7','M3_Mesh_15'].includes(n.name)){n.visible=false;n.userData.sc2Role='inactive';}});}
 const mixer=new THREE.AnimationMixer(model),actions:Record<string,THREE.AnimationAction>={};for(const c of original.animations)actions[c.name]=mixer.clipAction(c);const stand=actions[key==='nova'?'Stand A':'Stand']??Object.values(actions)[0];stand?.play();mixer.update(0);model.updateMatrixWorld(true);const bounds=sc2BodyBounds(model),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),scale=width?width/Math.max(size.x,size.z):height/size.y;model.position.x-=center.x;model.position.y-=bounds.min.y;model.position.z-=center.z;const root=new THREE.Group();root.scale.setScalar(scale);root.add(model);const materials:THREE.MeshStandardMaterial[]=[];model.traverse(n=>{if(n instanceof THREE.Mesh){n.castShadow=n.userData.sc2Role==='body';n.receiveShadow=true;const wasArray=Array.isArray(n.material),all=wasArray?n.material as THREE.Material[]:[n.material as THREE.Material];const copies=all.map(m=>{const copy=m.clone() as THREE.MeshStandardMaterial;copy.onBeforeCompile=m.onBeforeCompile;copy.customProgramCacheKey=m.customProgramCacheKey;copy.emissiveIntensity=.5;copy.userData.labEmissive=copy.emissive?.clone();if(copy.isMeshStandardMaterial)materials.push(copy);return copy;});n.material=wasArray?copies:copies[0];}});return {root,model,mixer,actions,clips:original.animations,scale,hitUntil:0,materials};
}
function setAttack(a:Actor,key:string){a.mixer.stopAllAction();const name=key==='nova'?'Attack A':key==='swann'?'Attack Right':'Attack',action=a.actions[name]??a.actions.Stand??Object.values(a.actions)[0];action?.setLoop(THREE.LoopRepeat,Infinity).play();if(action)action.timeScale=key==='swann'?1.1:key==='nova'?.9:1;}
function removeActor(a:Actor){scene.remove(a.root);a.root.removeFromParent();a.mixer.stopAllAction();a.mixer.uncacheRoot(a.model);for(const m of a.materials)m.dispose();}
async function choose(id:HeroId){if(!models.has(id))return;const serial=++selection;hero=id;clock=0;fireStarted=0;cycle=0;shotCount=hitCount=0;nextShot=.35;seed=8721;paused=false;for(const p of projectiles)if(p.object)scene.remove(p.object);projectiles.length=0;flightCores.count=0;for(const b of particles.values())b.clear();casings.length=0;for(const w of waves){waveGroup.remove(w.mesh);w.mesh.geometry.dispose();(w.mesh.material as THREE.Material).dispose();}waves.length=0;if(shooter)removeActor(shooter);for(const a of targets)removeActor(a);targets=[];shooter=makeActor(id,id==='tychus'?2.4:id==='swann'?2.3:2.15,id==='yamato_battlecruiser'?6.7:undefined);shooter.root.position.set(id==='yamato_battlecruiser'?-4.2:-3.4,id==='yamato_battlecruiser'?2.1:0,0);shooter.root.rotation.y=Math.PI/2;scene.add(shooter.root);setAttack(shooter,id);
 for(let i=0;i<4;i++){const a=makeActor(i===3?'mutalisk':'roach',i===3?1.3:1.35);a.root.position.copy(targetPositions[i]);a.root.rotation.y=-Math.PI/2;if(i===3)a.root.visible=id==='yamato_battlecruiser';targetGroup.add(a.root);targets.push(a);}document.documentElement.style.setProperty('--accent',descriptions[id].accent);$('hero-name').textContent=descriptions[id].name;$('weapon-name').textContent=descriptions[id].weapon;$('description').textContent=descriptions[id].note;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.setAttribute('aria-pressed',String(b.dataset.hero===id));$('toggle').textContent='暂停';setView(view);if(serial!==selection)return;
}
function mount(side=0){shooter!.root.updateMatrixWorld(true);const names=hero==='yamato_battlecruiser'?[side?'Ref_Weapon_04':'Ref_Weapon_01']:hero==='swann'?['Ref_Weapon_Right','Ref_Weapon_Left']:['Ref_Weapon','Ref_Weapon_01'];let node:THREE.Object3D|undefined;for(const n of names){node=shooter!.model.getObjectByName(n);if(node)break;}const p=node?node.getWorldPosition(new THREE.Vector3()):shooter!.root.position.clone().add(new THREE.Vector3(.7,1.3,0));return p;}
function fire(){cycle++;const id=hero,large=id==='raynor'&&cycle%3===0||id==='nova'&&cycle===1||id==='tosh'&&cycle%4===0;const count=id==='yamato_battlecruiser'?2:1;
 for(let side=0;side<count;side++){
  const from=mount(side),target=id==='yamato_battlecruiser'&&side===1?3:0,to=targetPositions[target].clone().add(new THREE.Vector3(0,target===3?.3:.78,0));to.z+=signed()*(id==='tychus'?.25:.09);const dir=to.clone().sub(from).normalize();const warm=new THREE.Color(id==='nova'?1.15:2.2,id==='nova'?2.2:1.1,id==='nova'?2.7:.42),size=id==='yamato_battlecruiser'?1.05:id==='swann'?.7:id==='nova'?.48:.44;
  glow(from,warm,size*.55,.035);const muzzleKey=id==='nova'?'flare1_blueelec':id==='tosh'?'energyplane3_red':id==='swann'?'kenney-muzzle_03':'kenney-muzzle_05';particle(muzzleKey,from.clone().addScaledVector(dir,.17),{color:warm,width:size*.65,height:size*1.5,life:id==='yamato_battlecruiser'?.1:.075,opacity:.75,direction:dir,growth:.45});
  if(id==='raynor'||id==='tychus'||id==='nova')casing(from.clone().addScaledVector(dir,-.45));
  if(id==='swann'||id==='yamato_battlecruiser'||cycle%3===0)smoke(from.clone().addScaledVector(dir,.2),id==='yamato_battlecruiser'?.55:.2);
  let object:THREE.Object3D|undefined;if(id==='swann'){object=cloneSkeleton(models.get('grenade')!.scene);const b=sc2BodyBounds(object),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3());object.position.sub(c);const wrapper=new THREE.Group();wrapper.add(object);wrapper.scale.setScalar(.45/Math.max(s.x,s.y,s.z));scene.add(wrapper);object=wrapper;}
  const flightSpeed=id==='swann'?18:id==='yamato_battlecruiser'?23:id==='tosh'?33:id==='nova'?85:60;
  projectiles.push({from,to,born:clock,duration:from.distanceTo(to)/flightSpeed,hero:id,power:large,cycle,target,object,lastTrail:from.clone()});shotCount++;
  muzzleLight.color.copy(warm);muzzleLight.position.copy(from);muzzleLight.intensity=id==='yamato_battlecruiser'?8:4;muzzleUntil=clock+.05;
 }
}
function ribbon(key:string,head:THREE.Vector3,tail:THREE.Vector3,width:number,color:THREE.Color,opacity=.8,life=.09){const delta=head.clone().sub(tail),length=delta.length();if(length<.01)return;particle(key,head.clone().add(tail).multiplyScalar(.5),{width,height:length,direction:delta.normalize(),color,life,opacity,growth:0,rotation:0});}
function impact(p:Projectile){const point=p.to,id=p.hero;hitCount++;targets[p.target].hitUntil=clock+.085;const col=new THREE.Color(id==='nova'?.55:id==='tosh'?2.1:2.4,id==='nova'?1.8:id==='tosh'?.65:1.1,id==='nova'?2.7:id==='tosh'?1.35:.4);
 if(id==='raynor'||id==='tychus'){
  glow(point,col,p.power?.75:.4,.07);particle('sparks4',point,{color:col,width:.62,height:.62,atlas:2,frames:4,frame:Math.floor(rand()*4),life:.11,opacity:.85,growth:.3});sparks(point,id==='tychus'?6:9,col,p.power?4.2:2.8);smoke(point,.24);
  if(id==='tychus'&&p.cycle%5===0)for(const index of [1,2]){const end=targetPositions[index].clone().add(new THREE.Vector3(0,.6,0));sparks(end,3,new THREE.Color(1.5,.6,.2),2);targets[index].hitUntil=clock+.06;}
 }else if(id==='nova'){
  glow(point,col,p.power?1.15:.6,.09);particle('flare1_blueelec',point,{color:new THREE.Color(1.6,1.8,2.2),width:p.power?1.3:.75,height:p.power?.65:.4,life:.15,growth:.1,rotation:0});sparks(point,p.power?15:8,col,3);psionicWave(point,false);smoke(point,.3);
 }else if(id==='swann'||id==='yamato_battlecruiser'){
  const scale=id==='yamato_battlecruiser'?1.15:.85;particle('fireanim_x4',point,{color:new THREE.Color(1.8,1.45,1),width:scale,height:scale,atlas:8,frames:32,life:.34,growth:.2,opacity:.86});glow(point,col,scale*.75,.055);sparks(point,id==='swann'?14:11,col,3.5);smoke(point,scale*.7,true);particle('kenney-smoke_09',point,{color:new THREE.Color(.5,.4,.3),width:scale,height:scale,life:.5,growth:1.2,opacity:.24,spin:signed()*.3});
  if(id==='yamato_battlecruiser'&&p.cycle%8===0&&p.target===0)for(const index of [1,2]){const end=targetPositions[index].clone().add(new THREE.Vector3(0,.65,0));ribbon('emergytrailorange',end,point,.10,new THREE.Color(1.8,.8,.3),.5,.15);particle('fireanim_x4',end,{width:.65,height:.65,atlas:8,frames:32,life:.3,color:new THREE.Color(1.3,1.05,.8)});targets[index].hitUntil=clock+.09;}
 }else{
  glow(point,col,.6,.08);particle('nebulacloudsalphaparticle_purple',point,{color:new THREE.Color(1.6,.9,1.4),width:p.power?1.2:.65,height:p.power?1.2:.65,life:.25,atlas:2,frames:4,growth:.4});sparks(point,6,new THREE.Color(1.6,.65,1.2),2.6);if(p.power){psionicWave(point,true);for(const index of [1,2]){const end=targetPositions[index].clone().add(new THREE.Vector3(0,.75,0));ribbon('energyplane3_red',point,end,.22,new THREE.Color(1.5,.7,1.2),.55,.22);targets[index].hitUntil=clock+.09;}}
 }
 impactLight.position.copy(point);impactLight.color.copy(col);impactLight.intensity=id==='swann'||id==='yamato_battlecruiser'?9:4;impactUntil=clock+.085;
}
function tickFlights(){let coreCount=0;for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i],q=Math.min(1,(clock-p.born)/p.duration),head=p.from.clone().lerp(p.to,q);if(p.hero==='swann')head.y+=Math.sin(q*Math.PI)*.2;const dir=p.to.clone().sub(p.from).normalize();if(p.object){p.object.position.copy(head);p.object.quaternion.setFromUnitVectors(localForward,dir);}
 if(p.hero!=='swann'&&q<1&&coreCount<64){const length=Math.min(head.distanceTo(p.from),p.hero==='nova'?2.3:p.hero==='yamato_battlecruiser'?1.25:p.hero==='tosh'?.65:p.power?1.8:1.2),width=p.hero==='yamato_battlecruiser'?1.35:p.hero==='tychus'?.65:.75;tempO.position.copy(head).addScaledVector(dir,-length*.5);tempO.quaternion.setFromUnitVectors(yAxis,dir);tempO.scale.set(width,length,width);tempO.updateMatrix();flightCores.setMatrixAt(coreCount,tempO.matrix);flightCores.setColorAt(coreCount,p.hero==='nova'?new THREE.Color(2.3,3,3.5):p.hero==='tosh'?new THREE.Color(3,1,1.4):new THREE.Color(3.2,2.3,1.2));coreCount++;}
 if(p.hero==='raynor'||p.hero==='tychus'){
  const length=p.hero==='tychus'?.85:p.power?1.9:1.25,tail=head.clone().addScaledVector(dir,-Math.min(length,head.distanceTo(p.from)));ribbon('kenney-trace_05',head,tail,p.power?.09:.055,new THREE.Color(2.4,1.85,.9),.95,.06);glow(head,new THREE.Color(2.7,2.2,1.6),.13,.035);
 }else if(p.hero==='nova'){
  ribbon('emergytrailcyan',head,p.lastTrail,.09,new THREE.Color(1.3,2.2,2.7),.8,.2);ribbon('energyplane3',head,p.lastTrail,.16,new THREE.Color(1.5,1.8,2.4),.7,.14);glow(head,new THREE.Color(1,2.2,3),p.power?.2:.14,.04);
 }else if(p.hero==='tosh'){
  ribbon('emergytrailorange',head,p.lastTrail,.15,new THREE.Color(2,1.2,1.6),.8,.14);const phase=q*24+p.cycle;const tangent=new THREE.Vector3(0,Math.sin(phase)*.12,Math.cos(phase)*.12);particle('energyplane3_red',head.clone().add(tangent),{width:.19,height:.2,color:new THREE.Color(1.8,.8,1.2),life:.12,opacity:.75,growth:-.5});glow(head,new THREE.Color(2.5,.9,1.7),.2,.04);
 }else if(p.hero==='yamato_battlecruiser'){
  ribbon('emergytrailorange',head,p.lastTrail,.22,new THREE.Color(2.3,1.5,1),.85,.17);ribbon('firestreak7',head,head.clone().addScaledVector(dir,-.7),.22,new THREE.Color(1.8,1.3,1),.9,.055);glow(head,new THREE.Color(2.4,1.4,.65),.28,.045);
 }else{
  particle('fireball_10',head.clone().addScaledVector(dir,-.13),{width:.2,height:.38,direction:dir,color:new THREE.Color(1.8,1.5,1),life:.055,opacity:.75});if(rand()<.3)smoke(head,.16);
 }p.lastTrail.copy(head);
 if(q>=1){impact(p);if(p.object)scene.remove(p.object);projectiles.splice(i,1);}}flightCores.count=coreCount;flightCores.instanceMatrix.needsUpdate=true;if(flightCores.instanceColor)flightCores.instanceColor.needsUpdate=true;
}
function animateActors(dt:number){shooter?.mixer.update(dt);for(const [i,a]of targets.entries()){a.mixer.update(dt);if(i===3)a.root.position.y=targetPositions[i].y+Math.sin(clock*2)*.12;for(const m of a.materials){if(!m.isMeshStandardMaterial)continue;if(a.hitUntil>clock){m.emissive.setRGB(.35,.11,.025);m.emissiveIntensity=1.3;}else{m.emissive.copy(m.userData.labEmissive??new THREE.Color(0,0,0));m.emissiveIntensity=.5;}}}shooter?.root.updateMatrixWorld(true);}
function period(){const growth=[1,.95,.9,.85,.8][rank-1];return descriptions[hero].period*growth/(hero==='tychus'?1+Math.min(2,(clock-fireStarted)/2):1);}
function sceneCorners(){const ship=hero==='yamato_battlecruiser',box=new THREE.Box3(new THREE.Vector3(ship?-7.8:-4.6,0,ship?-3.1:-1.3),new THREE.Vector3(5.5,ship?4.9:2.6,3.1));const points:THREE.Vector3[]=[];for(const x of [box.min.x,box.max.x])for(const y of [box.min.y,box.max.y])for(const z of [box.min.z,box.max.z])points.push(new THREE.Vector3(x,y,z));return points;}
function fitNarrowViewport(){if(camera.aspect>=1.3)return;for(let i=0;i<18;i++){camera.updateMatrixWorld();const bad=sceneCorners().some(p=>{const q=p.clone().project(camera);return Math.abs(q.x)>.9||Math.abs(q.y)>.9;});if(!bad)break;camera.position.sub(controls.target).multiplyScalar(1.08).add(controls.target);controls.update();}controls.maxDistance=Math.max(29,camera.position.distanceTo(controls.target)*1.2);}
function setView(next:string){view=next;const ship=hero==='yamato_battlecruiser';if(next==='battle'){camera.position.set(ship?9:7,ship?15:13,ship?18:14);controls.target.set(0,.5,0);}else{camera.position.set(ship?7.4:4.3,ship?9:7.2,ship?13.7:10.3);controls.target.set(ship?-.3:0,ship?1.7:.8,0);}controls.update();fitNarrowViewport();$('view').textContent=next==='battle'?'切换近景':'切换战场视角';}
function resize(){const w=viewport.clientWidth,h=viewport.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();fitNarrowViewport();renderer.setSize(w,h,false);composer.setSize(w,h);}
new ResizeObserver(resize).observe(viewport);resize();
for(const [id,d]of Object.entries(descriptions)){const b=document.createElement('button');b.dataset.hero=id;b.textContent=d.name;b.disabled=true;b.setAttribute('aria-pressed',String(id===hero));b.onclick=()=>choose(id as HeroId);$('hero-tabs').append(b);}
$('toggle').onclick=()=>{paused=!paused;$('toggle').textContent=paused?'继续开火':'暂停';};$('view').onclick=()=>setView(view==='close'?'battle':'close');$('restart').onclick=()=>choose(hero);$('speed').onchange=()=>{speed=Number(($('speed') as HTMLSelectElement).value);};$('rank').onchange=()=>{rank=Number(($('rank') as HTMLSelectElement).value);};$('glow').onchange=()=>{bloomOn=($('glow') as HTMLInputElement).checked;};
document.addEventListener('visibilitychange',()=>{previous=performance.now();});let previous=performance.now();
function frame(now:number){requestAnimationFrame(frame);const wallDt=Math.min(.05,Math.max(0,(now-previous)/1000));previous=now;const dt=ready&&!paused?wallDt*speed:0;controls.update();if(ready){if(dt>0){clock+=dt;animateActors(dt);let guard=0;while(clock>=nextShot&&guard++<4){fire();nextShot+=period();}tickFlights();for(const p of particles.values())p.update(dt);tickCasings(dt);tickWaves();if(clock>=muzzleUntil)muzzleLight.intensity=0;if(clock>=impactUntil)impactLight.intensity=0;}projectedFrameTimes.push(wallDt*1000);if(projectedFrameTimes.length>240)projectedFrameTimes.shift();$('counter').textContent='已发射 '+shotCount+' 发';$('pace').textContent=hero==='tychus'?(clock-fireStarted<4?'枪管预热中':'持续高速射击'):'连续普攻';}
 if(ready&&paused)for(const p of particles.values())p.update(0);renderer.info.reset();if(bloomOn)composer.render();else renderer.render(scene,camera);
}
requestAnimationFrame(frame);loadAll().catch(e=>{$('loading-text').textContent='加载失败：'+e.message;warnings.push(e.message);console.error(e);});
(window as any).__ATTACK_LAB__={select:choose,setPaused:(p:boolean)=>{paused=p;$('toggle').textContent=p?'继续开火':'暂停';},setSpeed:(s:number)=>{speed=s;},report:()=>({ready,hero,rank,paused,speed,time:clock,shots:shotCount,hits:hitCount,flights:projectiles.length,flightPhases:projectiles.map(p=>(clock-p.born)/p.duration),particles:[...particles.values()].reduce((n,p)=>n+p.particles.length,0),casings:casings.length,waves:waves.length,drawCalls:renderer.info.render.calls,frameTimes:projectedFrameTimes.slice(),models:[...models.keys()],textures:textures.size,warnings})};
