import {ENDLESS} from '../data/endless';
import {PointerCommitGuard} from './presentation/navigation';
import {renderIntermission,IntermissionNavigation,offerArt,type IntermissionRoute} from './presentation/intermission';
import {battleInputCapture,trapTab} from './presentation/input-capture';
import {CarrierInspector} from './hud/carrier-inspector';
import {bindHudSafeLayout} from './hud/layout';
import {HudSettings} from './hud/preferences';
import {hudGlyph} from './hud/glyphs';
import {finalObjectives} from './hud/objectives';
import {BattleCommands} from './hud/battle-commands';
import {actionForButton,activateBattleAction,battleActionState,type BattleActionId} from './controls/battle-actions';
import {setTextScale,textScale} from './text-scale';
import {openResourceDownloads} from './hud/resource-downloads';
import {tacticalCard,UNIQUE_SUPPORT} from '../data/unique-support';
import {familyRetirementPreview} from '../simulation/expedition-production';
import {toggleNativeFullscreen,fullscreenLabel} from './mobile/viewport';
import {SquadConsole} from './hud/squad-console';
import {DetectionHint} from './hud/detection-hint';
import {RESCUE_PRESENTATION} from '../data/economy';
import {renderBossLoot} from './hud/boss-loot-panel';
import type {SaveControls} from './hud/save-controls';
import type {RunSession,LoadPreview} from '../app/run-session';
import type {AssetReadinessCoordinator} from '../app/asset-readiness';
import {renderMenu,renderReadiness,type MenuPage} from './hud/m3-menu';
import type {Difficulty} from '../data/stages';
import type {PresetSlot} from '../simulation/progression/permanent-profile';
import type {ControlSettings} from './controls/settings';
import {healthReadout,rankLabel,rewardOwnership,unitCallsign,statusReadout} from './unit-identity';
import {HEROES,ALL_HERO_IDS,HERO_IDS_BY_RACE,type HeroId} from '../data/heroes';
import {talentRank,type TalentLine} from '../data/mvp-talents';
import {ELITES,type EliteId} from '../data/elites';
import {RARITIES} from '../data/rewards';
import {Minimap} from './hud/minimap';
import {World} from '../simulation/world';
import type {Reward} from '../simulation/types';
import type {ExpeditionReward} from '../simulation/progression/expedition-drafts';
import {SC2_UNITS,type UnitType} from '../data/sc2-units';
import {icon,missingAssets} from '../assets/manifest';
import type {BattleRenderer} from '../render/scene/battle-renderer';
import {ORDINARY_EFFECT_LABELS,resolveOrdinaryEffects,HERO_EFFECT_LABELS,resolveHeroEffects,QUALITY_LABELS,resolveQuality,ANIMATION_MODE_LABELS,resolveAnimationMode} from '../render/settings/quality';
import {RACES,RACE_NAMES,type Race,type FamilyId} from '../data/races';
import {PRODUCTION_LINES,type ProductionLineId} from '../data/expedition-buildings';
import {renderExpeditionProduction,renderFamilyReceipt,renderUnitOperations} from './hud/expedition-panel';
import {renderMvpTalentPanel,type TalentPage} from './hud/mvp-talent-panel';
const fmt=(n:number)=>String(Math.max(0,Math.ceil(n))).padStart(2,'0');
const clock=(n:number)=>{const seconds=Math.max(0,Math.ceil(n));return fmt(Math.floor(seconds/60))+':'+fmt(seconds%60);};
const cost=(m:number,g:number)=>`${m} 矿${g?' / '+g+' 气':''}`;
function eliteVariantButtons(w:World,family:FamilyId,action:string,attributes:string,enabled:boolean,label:string){const variants=Object.values(ELITES).filter(e=>e.family===family);return `<div class="elite-variant-grid" role="group" aria-label="${SC2_UNITS[family as UnitType]?.zh??family}精英型号">${variants.map(elite=>`<button class="elite-variant" data-action="${action}" ${attributes} data-variant="${elite.id}" ${enabled&&w.canAcquireElite(elite.id)?'':'disabled'}><b>${elite.name}</b><small>${elite.description}</small><strong>${w.eliteOwned(elite.id)?.rank===5?'已满级':w.eliteOwned(elite.id)?'升级 · '+label:'招募 · '+label}</strong></button>`).join('')||'<span>本家族暂无可招募的精英型号</span>'}</div>`;}
function eliteFamilyOf(reward:Reward):FamilyId|undefined {if(!('expeditionEffect' in reward))return;const effect=(reward as ExpeditionReward).expeditionEffect;return effect.kind==='elite'?effect.family:undefined;}
function renderTalentLootCard(w:World,offer:Reward,index:number,receipt:string,rarity:'purple'|'orange'){const family=eliteFamilyOf(offer),shell=`<span class="card-number">0${index+1}</span>${offerArt(offer)}<h3>${family?SC2_UNITS[family as UnitType]?.zh+' · 精英型号':offer.name}</h3><p>${offer.description}</p><strong>免费领取</strong>`;return family?`<article class="reward-card rarity-${rarity} elite-family-card">${shell}${eliteVariantButtons(w,family,'talent-loot',`data-receipt="${receipt}" data-id="${offer.offerId}"`,true,'免费领取')}</article>`:`<button class="reward-card rarity-${rarity}" data-action="talent-loot" data-receipt="${receipt}" data-id="${offer.offerId}">${shell}</button>`;}
function renderRescueChoices(w:World,saveUI:string){const right=w.eliteRescueChoice;if(!right)return '';const elite=ELITES[right.eliteId as EliteId];return `<div class="reward-screen"><span class="eyebrow">ELITE RESCUE</span><h2>${SC2_UNITS[elite.family as UnitType]?.zh??elite.family} · 救援权</h2><p>选择一款精英加入队伍。</p><div id="reward-cards"><article class="reward-card rarity-purple elite-family-card">${icon(elite.icon,elite.name)}<h3>选择精英型号</h3>${eliteVariantButtons(w,elite.family,'elite-rescue-claim',`data-receipt="${right.receipt}"`,true,'免费领取')}</article></div><button class="refresh" data-action="elite-rescue-decline" data-receipt="${right.receipt}">放弃本次救援 · 继续战斗</button>${saveUI}<button class="refresh" data-action="restart">返回标题 · 保留救援权</button></div>`;}
function renderStarterHero(w:World,selected:HeroId|null){const race=w.permanentProfile.activeRace;if(!talentRank(w.permanentProfile.levels,race,'hero_support'))return '';
 return `<label class="graphics-settings">开局英雄<select data-setting="starter-hero" aria-label="开局英雄">${HERO_IDS_BY_RACE[race].map(id=>`<option value="${id}" ${selected===id?'selected':''}>${HEROES[id].name} · ${HEROES[id].skill}</option>`).join('')}</select></label>`;
}
export class HUD {
 playerServices?:import('./hud/player-services').PlayerServices;
 private detectionHint=new DetectionHint();readonly intermission=new IntermissionNavigation();
 private overlayKey='';private overlayScroll=new Map<string,number[]>();
 private pendingFocus:(()=>HTMLElement|null|undefined)|null=null;private focusQueued=false;
 saveUI:SaveControls|null=null;
 session:RunSession|null=null;readiness:AssetReadinessCoordinator|null=null;
 coverIndexes:Record<Race,number>={terran:0,zerg:0,protoss:0};coverAuto=true;private coverAt=0;
 menuPage:MenuPage='title';menuRace:Race='terran';menuDifficulty:Difficulty='normal';menuPreset:PresetSlot=0;loadPreview:LoadPreview|null=null;flowError='';pendingStageAdvance=false;
 onPrepareNew:()=>void=()=>{};onPrepareLoad:()=>void=()=>{};onPrepareEndless:()=>void=()=>{};onCommitFlow:()=>void=()=>{};onCancelFlow:()=>void=()=>{};onPrepareReinforcement:()=>void=()=>{};
 talentPage:TalentPage='races';talentRace:Race='terran';talentLine:TalentLine='resources';
 private commitGuard=new PointerCommitGuard();
 settingsOpen=false;private settingsTab:'controls'|'graphics'|'saves'='controls';talentOpen=false;selectedTalentId:string|null=null;unitOperationsOpen=false;private operationsWasPaused=false;ready=true;loading='载入战场';lastPhase='';starterHeroChoice:HeroId|null=null;inputReset:()=>void=()=>{};onStart:()=>void=()=>{};onRestart:()=>void=()=>{};
 readonly carrierInspector:CarrierInspector;root:HTMLElement;readonly minimap:Minimap;readonly squadConsole:SquadConsole;readonly battleCommands:BattleCommands;private cache=new Map<string,string>();private iconLoaded=new Set<string>();private preparingElite:EliteId|null=null;
 constructor(readonly world:World,readonly view:BattleRenderer,readonly controls:ControlSettings,readonly preferences=new HudSettings()){this.root=document.querySelector('#interface')!;
  this.menuRace=world.permanentProfile.activeRace;this.menuPreset=world.permanentProfile.activePreset;try{const value=localStorage.getItem('sc2.newGameDifficulty');if(value==='easy'||value==='normal'||value==='hard'||value==='hell')this.menuDifficulty=value;}catch{}
  this.root.innerHTML=`<header id="topbar"><span class="callsign">SC2 <b>//</b> SURVIVORS</span><div class="resource">${icon('ui.minerals')}<span id="minerals">50</span></div><div class="resource gas">${icon('ui.gas')}<span id="gas">0</span></div><span id="stage" class="stage"></span><strong id="clock">02:00</strong><button data-action="pause" class="small" aria-label="暂停">Ⅱ</button></header>
   <div id="mission"></div><div id="notice" role="status" aria-live="polite"></div><div id="production-status"></div>
   <div id="hero-skills" class="console"></div><div id="skills" class="console"></div>
   <div id="joystick" aria-label="移动小队摇杆"><span class="stick-axis"></span><span class="stick-knob"></span></div><div id="stretch"></div><div id="portrait-hint">建议旋转至横屏</div>
   <button id="boss-loot-toggle" class="small" data-action="boss-loot-open" hidden style="position:fixed;right:14px;bottom:86px;z-index:120">首领奖励</button><section id="overlay"></section><aside id="debug" class="console" hidden></aside>`;
  this.battleCommands=new BattleCommands(world,this.root.querySelector('#skills')!);this.squadConsole=new SquadConsole(world,this.root,preferences);this.carrierInspector=new CarrierInspector(world,this.root);this.minimap=new Minimap(world,view,this.root,controls);
  this.minimap.element.querySelector('#map-toggle')!.addEventListener('click',()=>preferences.toggle('mapCollapsed'));
  preferences.listeners.add(()=>{this.update();document.dispatchEvent(new Event('sc2-hud-layout'));});
  bindHudSafeLayout(this.root);
  this.root.addEventListener('keydown',e=>{const modal=this.root.querySelector<HTMLElement>('.talent-node-layer');if(modal)trapTab(e,modal);});
  document.addEventListener('sc2-open-unit-operations',()=>this.openUnitOperations());
  this.root.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;if(el.dataset.setting==='text-scale')setTextScale(Number(el.value));else if(el.dataset.setting==='camera-shake')view.setCameraShake(el.value==='true');else if(el.dataset.setting==='ordinary-effects')view.nonHeroEffects.setQuality(resolveOrdinaryEffects(el.value));else if(el.dataset.setting==='hero-effects')view.fx.setHeroQuality(resolveHeroEffects(el.value));else if(el.dataset.setting==='quality')view.setQuality(resolveQuality(el.value));else if(el.dataset.setting==='animation-mode')view.setAnimationMode(resolveAnimationMode(el.value));else if(el.dataset.setting==='menu-preset'){this.menuPreset=Number(el.value) as PresetSlot;this.starterHeroChoice=null;}else if(el.dataset.setting==='menu-hero')this.starterHeroChoice=el.value as HeroId;else if(el.dataset.setting==='development-target')world.setDevelopmentTarget(el.value||null);else if(el.dataset.setting==='hatchery-sequence')world.assignHatcherySequence(Number(el.dataset.id),el.value as ProductionLineId);else if(el.dataset.setting==='desktop'||el.dataset.setting==='touch')controls.set(el.dataset.setting,el.value);this.update();});
  this.root.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled||this.commitGuard.blocks(e,performance.now()))return;const action=button.dataset.action!,battleAction=actionForButton(world,action);if(battleAction){if(battleInputCapture())return;if(this.unitOperationsOpen)this.executePanelAction(()=>activateBattleAction(world,battleAction));else activateBattleAction(world,battleAction);this.update();return;}if(action==='resource-downloads'){if(world.phase!=='battle'||world.paused)openResourceDownloads(world.phase==='menu'?this.menuRace:world.expedition.race);return;}if(action==='fullscreen'){void toggleNativeFullscreen().then(ok=>{if(!ok){world.announce('此浏览器暂不支持全屏');this.flowError='此浏览器暂不支持全屏';}this.update();});return;}
   if(this.saveUI?.handle(action))return;
   if(action==='ui-back'){const entry=this.intermission.back();this.update();if(entry?.focus)this.focusAfterUpdate(()=>this.root.querySelector<HTMLElement>(entry.focus));return;}
   else if(action==='ui-page'&&world.phase==='reward'&&['direction','production','rest','heroes','contracts','catalog'].includes(button.dataset.page??'')){this.intermission.push({page:button.dataset.page} as IntermissionRoute,`[data-action="ui-page"][data-page="${button.dataset.page}"]`);}
   else if(action==='ui-offer'&&world.phase==='reward'&&world.rewards.some(r=>r.offerId===button.dataset.id)){this.intermission.push({page:'offer',id:button.dataset.id!},`[data-action="ui-offer"][data-id="${CSS.escape(button.dataset.id!)}"]`);}
   else if(action==='ui-contract'&&world.phase==='reward'){this.intermission.push({page:'contract',id:button.dataset.id!},`[data-action="ui-contract"][data-id="${CSS.escape(button.dataset.id!)}"]`);}
   else if(action==='ui-elite'&&world.phase==='reward'&&button.dataset.variant&&button.dataset.variant in ELITES){this.intermission.push({page:'elite',id:button.dataset.id!,variant:button.dataset.variant as EliteId,contract:button.dataset.contract==='true'},`[data-action="ui-elite"][data-variant="${button.dataset.variant}"]`);}
   else if(action==='ui-catalog-filter'&&['ordinary','elite','hero','development','support','training'].includes(button.dataset.filter??'')){this.intermission.filter=button.dataset.filter as IntermissionNavigation['filter'];}
   else if(action==='ui-catalog-detail'){this.intermission.push({page:'catalog-detail',id:button.dataset.id!},`[data-action="ui-catalog-detail"][data-id="${CSS.escape(button.dataset.id!)}"]`);}
   else if(action==='cover-race' &&RACES.includes(button.dataset.race as Race)){this.menuRace=button.dataset.race as Race;this.coverAt=performance.now();}
   else if(action==='cover-prev'||action==='cover-next'){this.coverIndexes[this.menuRace]=(this.coverIndexes[this.menuRace]+(action==='cover-next'?1:2))%3;this.coverAt=performance.now();}
   else if(action==='cover-auto')this.coverAuto=!this.coverAuto;
   else if(action==='menu-new'){this.flowError='';this.menuPage='race';this.menuRace=world.permanentProfile.activeRace;this.menuPreset=world.permanentProfile.activePreset;}
   else if(action==='menu-race'&&RACES.includes(button.dataset.race as Race)){this.menuRace=button.dataset.race as Race;this.menuPreset=world.permanentProfile.activePresetFor(this.menuRace);this.starterHeroChoice=null;}
   else if(action==='menu-race-next')this.menuPage='difficulty';
   else if(action==='menu-difficulty'){const d=button.dataset.difficulty;if(d==='easy'||d==='normal'||d==='hard'||d==='hell'){this.menuDifficulty=d;try{localStorage.setItem('sc2.newGameDifficulty',d);}catch{}}}
   else if(action==='menu-difficulty-next')this.menuPage='confirm';
   else if(action==='menu-edit-talents'){this.talentRace=this.menuRace;this.talentPage='lines';this.talentOpen=true;this.selectedTalentId=null;this.flowError='';}
   else if(action==='menu-start'){this.flowError='';this.onPrepareNew();}
   else if((action==='menu-load'||action==='menu-load-summary')){this.flowError='';this.menuPage='load';}
   else if(action==='menu-load-local'){try{this.loadPreview=this.session?.prepareLoad()??null;this.menuPage='load-preview';this.flowError='';}catch(error){this.flowError=String((error as Error).message);}}
   else if(action==='menu-load-file'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{if(file.size>32*1024*1024)throw Error('存档文件过大');const raw=await (this.readiness?.readImportFile(file)??file.text());if(raw===null)return;this.readiness?.cancel();this.loadPreview=this.session?.prepareLoad(raw)??null;this.menuPage='load-preview';this.flowError='';}catch(error){this.readiness?.cancel();this.flowError=String((error as Error).message);}this.update();});input.click();}
   else if(action==='menu-load-ready'){this.flowError='';this.onPrepareLoad();}
   else if(action==='menu-back')this.menuBack();
   else if(action==='flow-cancel'){this.readiness?.cancel();this.onCancelFlow();this.flowError='';}
   else if(action==='flow-retry')void this.readiness?.retry();
   else if(action==='flow-continue')this.onCommitFlow();
   else if(action==='endless'){this.inputReset();world.chooseCampaignExit('endless');}
   else if(action==='evacuate'){this.inputReset();world.chooseCampaignExit('evacuate');}
   else if(action==='endless-back'){this.inputReset();world.backFromEndlessPreparation();}
   else if(action==='endless-prepare'){this.inputReset();this.onPrepareEndless();}
   else if(action==='restart'){this.squadConsole.close();this.carrierInspector.close();this.settingsOpen=false;this.talentOpen=false;this.menuPage='title';this.readiness?.cancel();this.onRestart();}else if(action==='pause')this.pause();else if(action==='settings'){this.inputReset();this.talentOpen=false;this.settingsOpen=true;if(world.phase==='battle')world.paused=true;}else if(action==='settings-tab'&&['controls','graphics','saves'].includes(button.dataset.tab??''))this.settingsTab=button.dataset.tab as typeof this.settingsTab;else if(action==='settings-back')this.settingsOpen=false;
   else if(action==='talents'){this.settingsOpen=false;this.talentOpen=true;this.talentPage='races';}else if(action==='talents-back')this.talentBack();
   else if(action==='mvp-talent-race'&&RACES.includes(button.dataset.race as Race)){this.talentRace=button.dataset.race as Race;this.talentPage='lines';this.selectedTalentId=null;}
   else if(action==='talent-line'&&['resources','soldiers','army','micro'].includes(button.dataset.line??'')){this.talentLine=button.dataset.line as TalentLine;this.talentPage='tree';this.selectedTalentId=null;}
   else if(action==='mvp-talent-preset'){world.permanentProfile.activatePreset(this.talentRace,Number(button.dataset.slot) as PresetSlot);}
   else if(action==='mvp-talent-select'){this.selectedTalentId=button.dataset.id??null;this.talentPage='node';}
   else if(action==='mvp-talent-buy'){if(world.selectRace(this.talentRace))world.permanentProfile.buy(button.dataset.id!);}
   else if(action==='mvp-talent-respec'){if(world.selectRace(this.talentRace))world.permanentProfile.respec(button.dataset.line as TalentLine|'all');}
   else if(action==='mvp-talent-copy'){world.permanentProfile.savePresetBlueprint(this.talentRace,Number(button.dataset.slot) as PresetSlot,world.permanentProfile.levelsFor(this.talentRace));}
   else if((action==='unit-operations-back'||action==='unit-operations-close'))this.closeUnitOperations();
   else if(action==='unit-mode')this.executePanelAction(()=>world.setFamilyMode(button.dataset.family as FamilyId,button.dataset.mode!));
   else if(action==='family-ability')this.executePanelAction(()=>activateBattleAction(world,button.dataset.family==='stalker'?'stalker-blink':'banshee-cloak'));
   else if(action==='production-output'){const line=button.dataset.line as ProductionLineId,family=button.dataset.family as FamilyId,plan=world.expedition.production[line];if(plan)world.setProductionOutputs(line,plan.outputs.includes(family)?plan.outputs.filter(id=>id!==family):[...plan.outputs,family]);}
   else if(action==='production-enable'){const family=button.dataset.family as FamilyId,plan=Object.values(world.expedition.production).find(plan=>plan?.outputs.includes(family));if(plan)world.setProductionEnabled(family,!plan.enabled[family]);}
   else if(action==='tactical-bind'){const family=button.dataset.family as FamilyId,field=button.closest<HTMLElement>('[data-tactical-family]'),target=Number(field?.querySelector<HTMLSelectElement>('[data-tactical-target]')?.value),direction=field?.querySelector<HTMLSelectElement>('[data-tactical-direction]')?.value as 'assault'|'guard'|'mobility';world.setTacticalEvolutionPlan(family,target,direction);}
   else if(action==='tactical-toggle'){const family=button.dataset.family as FamilyId,plan=world.expedition.tacticalPlans[family];if(plan)world.setTacticalEvolutionEnabled(family,!plan.enabled);}
   else if(action==='tactical-cancel')world.cancelTacticalEvolutionPlan(button.dataset.family as FamilyId,Number(button.dataset.revision));
   else if(action==='family-replace'){this.inputReset();world.commitFamilyReplacement(button.dataset.request!,button.dataset.old as FamilyId,Number(button.dataset.revision));}
   else if(action==='family-reject'){this.inputReset();world.rejectIncomingBatch(button.dataset.request!,Number(button.dataset.revision));}
   else if(action==='elite-contract'){this.inputReset();if(world.buyEliteContract(button.dataset.id!,button.dataset.variant as EliteId|undefined)&&!world.expedition.pendingShopElite)this.finishPurchase(e);}
   else if(action==='boss-loot-open'){this.inputReset();world.openBossLoot();}
   else if(action==='boss-loot-close'){this.inputReset();world.closeBossLoot();}
   else if(action==='boss-loot-variant'){this.inputReset();world.selectBossLootVariant(button.dataset.receipt!,button.dataset.variant as EliteId);}
   else if(action==='boss-loot-variant-back'){this.inputReset();world.selectBossLootVariant(button.dataset.receipt!,null);}
   else if(action==='boss-loot-claim'){this.inputReset();world.claimBossLoot(button.dataset.receipt!,button.dataset.variant as EliteId|undefined,button.dataset.target?Number(button.dataset.target):undefined);}
   else if(action==='talent-loot'){this.inputReset();world.claimTalentLoot(button.dataset.receipt!,button.dataset.id!,button.dataset.variant as EliteId|undefined);}
   else if(action==='elite-rescue-claim'){this.inputReset();world.claimEliteRescueRight(button.dataset.receipt!,button.dataset.variant as EliteId|undefined);}
   else if(action==='elite-rescue-decline'){this.inputReset();world.declineEliteRescueRight(button.dataset.receipt!);}
   else if(action==='elite-cancel'){this.inputReset();world.cancelPendingEliteChoice(button.dataset.elite as EliteId);}
   else if(action==='repair-all'){const units=button.dataset.family?world.familyBodies(button.dataset.family as FamilyId):world.allies(),quote=world.previewRepair(units.filter(unit=>!unit.temporary&&!unit.summonOwnerId).map(unit=>unit.id));if(quote&&quote.id===button.dataset.quote)world.purchaseRepair(quote.id);}
   else if(action==='revive')world.reviveHero(button.dataset.id as HeroId);
   else if(action==='elite-replace'){const elite=ELITES[button.dataset.elite as EliteId];if(elite&&this.view.gpu.has(elite.model)&&this.view.assetsPending===0){this.inputReset();world.replaceWithElite(elite.id,Number(button.dataset.id));}}
   else if(action==='elite-assets-retry')this.onPrepareReinforcement();
   else if(action==='shop-supply-cancel')world.cancelShopSupply();else if(action==='shop-supply-confirm'){if(world.confirmShopSupply(button.dataset.family as FamilyId))this.finishPurchase(e);}else if(action==='shop-elite-cancel')world.cancelShopElite();else if(action==='shop-elite-confirm'){if(world.confirmShopElite(Number(button.dataset.id)))this.finishPurchase(e);}else if(action==='development-direction'){const panel=button.closest('details');if(panel)panel.open=false;if(world.setDevelopmentDirection(button.dataset.line as ProductionLineId))this.intermission.reset();}else if(action==='reroll')world.reroll();else if(action==='reward'){this.inputReset();if(world.choose(button.dataset.id!,button.dataset.variant as EliteId|undefined)&&!world.expedition.pendingShopElite&&!world.expedition.pendingShopSupply)this.finishPurchase(e);}else if(action==='skip'){
    this.inputReset();
    if(world.phase==='reward'&&world.rewardRound==='random'&&!world.endlessEntry){this.pendingStageAdvance=true;this.onPrepareReinforcement();}
    else world.skipReward();
   }
   this.update();
  });controls.listeners.add(()=>this.update());world.listeners.add(()=>this.update());world.permanentProfile.listeners.add(()=>this.update());this.update();
 }
 graphicsControls(){return '<button class="small" data-action="settings">设置 · 操作与画质</button>';}
 private finishPurchase(event:MouseEvent){this.intermission.reset();this.commitGuard.commit(event,performance.now());}
 talentBack(){if(this.talentPage==='node')this.talentPage='tree';else if(this.talentPage==='tree')this.talentPage='lines';else if(this.talentPage==='lines')this.talentPage='races';else this.talentOpen=false;}
 talentPanel(){return renderMvpTalentPanel(this.world.permanentProfile,this.selectedTalentId,{page:this.talentPage,race:this.talentRace,line:this.talentLine});}

 settingsPanel(){return `<div class="end-screen control-settings"><span class="eyebrow">OPTIONS</span><h2>设置</h2><nav class="settings-tabs" aria-label="设置分类">${(['controls','graphics','saves'] as const).map(tab=>`<button data-action="settings-tab" data-tab="${tab}" aria-pressed="${this.settingsTab===tab}">${({controls:'操作',graphics:'画质与显示',saves:'存档'})[tab]}</button>`).join('')}</nav><section data-ui-scroll ${this.settingsTab==='controls'?'':'hidden'}>
  <label class="graphics-settings">电脑移动<select data-setting="desktop" aria-label="电脑移动"><option value="mouse" ${this.controls.desktop==='mouse'?'selected':''}>鼠标 · 左 / 右键点击移动</option><option value="keyboard" ${this.controls.desktop==='keyboard'?'selected':''}>键盘 · WASD / 方向键</option></select></label>
  <label class="graphics-settings">手机移动<select data-setting="touch" aria-label="手机移动"><option value="joystick" ${this.controls.touch==='joystick'?'selected':''}>摇杆 · 左侧虚拟摇杆</option><option value="tap" ${this.controls.touch==='tap'?'selected':''}>点击 · 点按战场移动</option></select></label>
  <p>按前进方向自动索敌、停步开火后继续移动。<br>无需点选敌人；点击敌人所在位置也只会前往该位置。</p>
  <p>手柄：左摇杆移动，右摇杆选择技能，A / X 施放。<br>键盘技能：T 架炮，E 兴奋剂，Space 推进，G 侦测，1 / 2 / 3 英雄。</p>
  <button class="small" data-action="controller">手柄校准</button>
  </section><section data-ui-scroll ${this.settingsTab==='graphics'?'':'hidden'}><label class="graphics-settings">画质<select data-setting="quality" aria-label="画质">${Object.entries(QUALITY_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.quality===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <label class="graphics-settings">镜头震动<select data-setting="camera-shake" aria-label="镜头震动"><option value="false" ${this.view.cameraShake?'':'selected'}>关闭（默认）</option><option value="true" ${this.view.cameraShake?'selected':''}>开启</option></select></label>
  <label class="graphics-settings">普通兵与支援<select data-setting="ordinary-effects" aria-label="普通兵与支援特效">${Object.entries(ORDINARY_EFFECT_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.nonHeroEffects.quality===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <label class="graphics-settings">英雄特效<select data-setting="hero-effects" aria-label="英雄特效">${Object.entries(HERO_EFFECT_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.fx.heroQuality===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <label class="graphics-settings">单位动作<select data-setting="animation-mode" aria-label="单位动作">${Object.entries(ANIMATION_MODE_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.animationMode===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <p>完整动作更流畅，节能模式更省电。</p><label class="graphics-settings">文字大小<select data-setting="text-scale" aria-label="文字大小">${[1,1.25,1.5].map(n=>`<option value="${n}" ${textScale()===n?'selected':''}>${n*100}%</option>`).join('')}</select></label>
  </section><section data-ui-scroll ${this.settingsTab==='saves'?'':'hidden'}>${this.saveUI?.render('settings')??'<p>当前无可用存档操作。</p>'}</section><button class="primary" data-action="settings-back">返回</button></div>`;}
 private presentationKey(){const w=this.world;return JSON.stringify([w.runId,w.phase,this.readiness?.state.kind,this.readiness?.state.phase,this.talentOpen?[this.talentPage,this.talentRace,this.talentLine]:null,this.settingsOpen?this.settingsTab:null,this.menuPage,this.intermission.current,this.intermission.filter,w.expedition.pendingShopSupply?.offerId,w.expedition.pendingShopElite?.offerId,w.expedition.bossLootOpen,w.expedition.pendingReceipt?.id]);}
 private navigationFocus(){if(this.talentOpen){const selector=this.talentPage==='node'?'.talent-node-layer button':this.talentPage==='tree'?`[data-action="mvp-talent-select"]${this.selectedTalentId?'[data-id="'+this.selectedTalentId+'"]':''}`:this.talentPage==='lines'?`[data-action="talent-line"][data-line="${this.talentLine}"]`:`[data-action="mvp-talent-race"][data-race="${this.talentRace}"]`;return this.root.querySelector<HTMLButtonElement>(selector);}return this.root.querySelector<HTMLButtonElement>('.formal-intermission .reward-actions button:not(:disabled),.m3-menu .primary:not(:disabled),.m3-menu button:not(:disabled),.formal-home .primary,.reward-card button:not(:disabled),button.reward-card:not(:disabled),[data-action="family-reject"],[data-action="skip"]');}
 private focusAfterUpdate(pick:()=>HTMLElement|null|undefined){this.pendingFocus=pick;if(this.focusQueued)return;this.focusQueued=true;queueMicrotask(()=>{this.focusQueued=false;const target=this.pendingFocus?.();this.pendingFocus=null;if(target?.isConnected&&document.activeElement!==target)target.focus({preventScroll:true});});}
 put(id:string,html:string){if(this.cache.get(id)===html)return;const root=document.getElementById(id)!,focused=document.activeElement as HTMLElement|null,wasInside=!!focused&&root.contains(focused),panel=focused?.tagName==='SUMMARY'?focused.parentElement?.dataset.panel:null;const focusKeys=['action','id','setting','race','slot','tab','line','page','filter','family','variant','heroSlot','mode','receipt'] as const,focusIdentity=Object.fromEntries(focusKeys.filter(key=>focused?.dataset[key]!==undefined).map(key=>[key,focused!.dataset[key]]));const oldIndex=wasInside?[...root.querySelectorAll('button,select,summary')].indexOf(focused!):-1;const panels=[...root.querySelectorAll<HTMLDetailsElement>('details[data-panel][open]')].map(e=>e.dataset.panel);const scrollSelector='[data-ui-scroll],.mvp-talents,.title-screen,.end-screen,.reward-screen',nextKey=id==='overlay'?this.presentationKey():'';if(id==='overlay'){this.overlayScroll.set(this.overlayKey,[root.scrollTop,...[...root.querySelectorAll<HTMLElement>(scrollSelector)].map(e=>e.scrollTop)]);this.overlayKey=nextKey;}root.innerHTML=html;if(id==='overlay'){const saved=this.overlayScroll.get(nextKey);if(saved){root.scrollTop=saved[0];[...root.querySelectorAll<HTMLElement>(scrollSelector)].forEach((e,i)=>e.scrollTop=saved[i+1]??0);}}for(const panel of root.querySelectorAll<HTMLDetailsElement>('details[data-panel]'))if(panels.includes(panel.dataset.panel))panel.open=true;this.cache.set(id,html);if(wasInside)this.focusAfterUpdate(()=>{const all=[...root.querySelectorAll<HTMLElement>('button,select,summary')].filter(e=>e.getClientRects().length&&!e.closest('[inert]'));const same=all.find(e=>!e.matches(':disabled')&&(panel?e.tagName==='SUMMARY'&&e.parentElement?.dataset.panel===panel:Object.keys(focusIdentity).length>0&&Object.entries(focusIdentity).every(([key,value])=>e.dataset[key]===value)));return same??all.slice(Math.max(0,oldIndex)).find(e=>!e.matches(':disabled'))??all.find(e=>!e.matches(':disabled'));});}
  menuBack(){if(this.readiness?.state.kind){this.readiness.cancel();this.onCancelFlow();return;}if(this.talentOpen){this.talentBack();this.update();return;}if(this.menuPage==='load-preview'){this.session?.cancelPreparedLoad();this.loadPreview=null;this.menuPage='load';}else if(this.menuPage==='load'||this.menuPage==='race')this.menuPage='title';else if(this.menuPage==='difficulty')this.menuPage='race';else if(this.menuPage==='confirm')this.menuPage='difficulty';this.flowError='';this.update();}
 openUnitOperations(){if(this.world.phase!=='battle'||this.world.paused||this.world.requiresPlayerDecision)return;this.operationsWasPaused=this.world.paused;this.unitOperationsOpen=true;this.world.paused=true;this.inputReset();this.world.changed();}
 closeUnitOperations(){if(!this.unitOperationsOpen)return;this.unitOperationsOpen=false;this.world.paused=this.operationsWasPaused;this.inputReset();this.world.changed();}
 private executePanelAction(run:()=>boolean){if(!this.unitOperationsOpen||this.world.phase!=='battle'||this.world.requiresPlayerDecision||this.operationsWasPaused)return false;this.inputReset();this.unitOperationsOpen=false;this.world.paused=false;const used=run();if(!used){this.unitOperationsOpen=true;this.world.paused=true;this.world.announce('当前操作无法执行');}this.world.changed();return used;}
  pause(){if(this.playerServices?.close())return;if(this.squadConsole.close()){this.inputReset();return;}if(!this.carrierInspector.root.hidden){this.carrierInspector.close();return;}if(this.readiness?.state.kind){this.menuBack();return;}if(this.settingsOpen){this.settingsOpen=false;this.inputReset();this.update();return;}if(this.talentOpen){this.talentBack();this.inputReset();this.update();return;}if(this.world.phase==='menu'){this.menuBack();return;}if(this.world.expedition.bossLootOpen){const loot=this.world.expedition.bossLootQueue[0];if(loot?.variant)this.world.selectBossLootVariant(loot.receipt,null);else this.world.closeBossLoot();this.inputReset();this.update();return;}if(this.world.expedition.pendingShopSupply){this.world.cancelShopSupply();this.inputReset();this.update();return;}if(this.world.expedition.pendingShopElite){this.world.cancelShopElite();this.inputReset();this.update();return;}if(this.unitOperationsOpen){this.closeUnitOperations();return;}if(this.settingsOpen){this.settingsOpen=false;this.inputReset();this.update();return;}if(this.world.phase==='reward'&&this.intermission.depth){const entry=this.intermission.back();this.update();if(entry?.focus)this.focusAfterUpdate(()=>this.root.querySelector<HTMLElement>(entry.focus));return;}if(this.world.phase==='reward'&&this.world.endlessEntry){this.world.backFromEndlessPreparation();return;}if(this.world.phase==='battle'){this.world.paused=!this.world.paused;this.inputReset();this.world.changed();}}
 setLoading(text:string){this.loading=text;this.update();}
 finishLoading(){const missing=missingAssets();this.ready=this.view.initialAssetsLoaded&&missing.length===0&&this.view.modelErrors.length===0;this.loading=this.ready?'战场就绪':'缺少战场素材';this.update();this.root.querySelector<HTMLButtonElement>('[data-action=save-continue]:not(:disabled),[data-action=start]')?.focus();}
 update(){const w=this.world;this.intermission.sync(w);if(w.phase==='menu'&&this.menuPage==='title'&&!this.talentOpen&&!this.settingsOpen&&this.coverAuto&&!matchMedia('(prefers-reduced-motion: reduce)').matches&&performance.now()-this.coverAt>9000&&!this.root.querySelector('.home-cover-controls:hover,.home-cover-controls:focus-within')){this.coverAt=performance.now();this.coverIndexes[this.menuRace]=(this.coverIndexes[this.menuRace]+1)%3;}document.body.dataset.rules='mvp';document.body.dataset.race=w.expedition.race;this.root.dataset.race=w.phase==='menu'?this.menuRace:w.expedition.race;document.body.dataset.touchControls=this.controls.touch;document.body.dataset.desktopControls=this.controls.desktop;const battleUI=w.phase==='battle'&&!w.paused&&!w.requiresPlayerDecision&&!this.readiness?.state.kind&&!this.settingsOpen&&!this.talentOpen;document.body.dataset.uiPhase=this.readiness?.state.kind?'loading':this.talentOpen?'talents':this.settingsOpen?'settings':w.phase==='battle'&&!battleUI?'pause':w.phase;this.minimap.update(battleUI,this.preferences.mapCollapsed);
  this.put('minerals',String(Math.floor(w.wallet.minerals)));this.put('gas',String(Math.floor(w.wallet.gas)));this.put('stage',w.endless?`∞ <b>${w.endless.round}</b>`:`<b>${String(w.stage).padStart(2,'0')}</b> / ${18}`);this.put('clock',clock(w.duration-w.stageElapsed));
  this.put('mission',`<span class="eyebrow">${({easy:'简单',normal:'普通',hard:'困难',hell:'地狱'}[w.difficulty])} / ${w.terrain?.definition?.source.name??'CHAR'}</span><b>${w.endless?'无尽战场 · 第 '+w.endless.round+' 轮':w.config.name}</b>${finalObjectives(w)}`);
  const routine=/守住小队|增援即将落地|已加入队伍|雇佣兵抵达|小队转移完成/.test(w.notice);this.put('notice',w.time<w.noticeUntil&&!routine?w.notice.split(' · ')[0]:'');document.querySelector<HTMLElement>('#notice')!.title=w.notice;this.put('stretch','');
  this.squadConsole.update(battleUI);this.carrierInspector.update();
  const actionsReady=!this.view.assetsPending&&!this.readiness?.state.kind;document.body.dataset.battleActionsReady=String(actionsReady);this.battleCommands.update(!actionsReady);
  const detection=this.root.querySelector<HTMLButtonElement>('#detection')!,nearbyCloak=this.detectionHint.update(w);detection.classList.toggle('cloak-threat',nearbyCloak);if(nearbyCloak)detection.setAttribute('aria-label','附近有隐形威胁，使用侦测 · G');
  this.put('hero-skills',[...w.heroes.keys()].map((id,heroSlot)=>{const h=w.heroes.get(id)!,u=w.heroEntity(id),data=HEROES[id],alive=!!u&&u.hp>0,left=w.time+1e-8>=h.skillReady?0:Math.max(0,h.skillReady-w.time),duration=u?.lastSkillAt===undefined?data.cooldown:Math.max(.01,h.skillReady-u.lastSkillAt),hp=healthReadout(alive?u!.hp:0,u?.maxHp??data.hp*(1+.2*(h.rank-1))),casting=w.heroCasts.some(c=>c.hero===id&&c.phase!=='dot'),status=alive?left>0?'冷却 '+Math.ceil(left)+'秒':data.skill:h.revivePaid?'下关复活':h.awaitingSpawn?'待部署':'阵亡',label=`${data.name} · ${rankLabel(h.rank)} · ${status}`;return `<div class="hero-status ${alive?'':'fallen'} ${hp.critical?'critical':''} ${left>0?'cooling':'skill-ready'} ${casting?'casting':''}" data-hero="${id}"><button class="hero-skill" data-action="hero-${id}" data-hero-slot="${heroSlot}" data-battle-action="hero-slot-${heroSlot}" ${battleActionState(w,`hero-slot-${heroSlot}` as BattleActionId).enabled&&!this.view.assetsPending?'':'disabled'} title="${label}" aria-label="${label}" style="--cooldown:${Math.min(100,left/duration*100).toFixed(2)}%">${icon('hero.'+id,data.name)}<i class="skill-mask" aria-hidden="true"></i><span class="hero-name">${data.name}</span><span class="skill-count" aria-hidden="true">${alive?left>0?Math.ceil(left):'':hudGlyph('fallen')}</span><kbd>${heroSlot+1}</kbd><em class="hero-rank">${rankLabel(h.rank)}</em></button><div class="hero-vitals" role="meter" aria-label="${data.name}生命" aria-valuemin="0" aria-valuenow="${hp.current}" aria-valuemax="${hp.max}"><i style="width:${hp.ratio*100}%"></i></div></div>`;}).join(''));

  this.put('production-detail',`<span>${RESCUE_PRESENTATION[w.expedition.race].workerName} ${w.workers}</span>${Object.entries(w.expedition.production).map(([line,plan])=>{const job=w.expedition!.ledger.find(j=>j.line===line&&j.state!=='settled');return `<span>${PRODUCTION_LINES[line as ProductionLineId].name} · ${job?SC2_UNITS[job.family].zh+' ×'+job.passengers.filter(p=>p.status==='waiting').length+' · '+(job.state==='training'?fmt(job.remaining)+'s':'救援中'):plan!.outputs.filter(f=>plan!.enabled[f]).map(f=>SC2_UNITS[f].zh).join(' / ')||'已关闭'}</span>`;}).join('')}`);
  this.put('production-status',`<span>${RESCUE_PRESENTATION[w.expedition.race].workerName} ${w.workers}</span>`);
  const bossLootToggle=document.querySelector<HTMLButtonElement>('#boss-loot-toggle')!;bossLootToggle.hidden=!w.expedition.bossLootQueue.length||w.expedition.bossLootOpen||w.phase==='menu'||!!this.readiness?.state.kind||this.settingsOpen||this.talentOpen||this.unitOperationsOpen;bossLootToggle.setAttribute('aria-label',`首领奖励 · ${w.expedition.bossLootQueue.length}件待领`);bossLootToggle.title=bossLootToggle.getAttribute('aria-label')!;this.put('boss-loot-toggle',`${hudGlyph('loot')}<span>${w.expedition.bossLootQueue.length}</span>`);
  const overlay=document.querySelector<HTMLElement>('#overlay')!;overlay.hidden=!this.readiness?.state.kind&&!this.settingsOpen&&!this.talentOpen&&w.phase==='battle'&&!w.paused&&!w.requiresPlayerDecision;
  if(this.readiness?.showLoading)this.put('overlay',renderReadiness(this.readiness.state));
  else if(this.talentOpen)this.put('overlay',this.talentPanel());
  else if(this.settingsOpen)this.put('overlay',this.settingsPanel());
  else if(this.unitOperationsOpen)this.put('overlay',renderUnitOperations(w));
  else if(w.expedition.bossLootOpen&&w.expedition.bossLootQueue.length)this.put('overlay',renderBossLoot(w,key=>this.view.gpu.has(key)&&this.view.assetsPending===0));
  else if(w.expedition.pendingTalentLoot){const choice=w.expedition.pendingTalentLoot;this.put('overlay',`<div class="reward-screen"><span class="eyebrow">TALENT DROP · ${choice.rarity==='orange'?'ORANGE':'PURPLE'}</span><h2>出金大师 · 免费奖励</h2><p>从这次击杀的${choice.rarity==='orange'?'橙色':'紫色'}奖励中选一项。</p><div id="reward-cards">${choice.offers.map((offer,index)=>renderTalentLootCard(w,offer,index,choice.receipt,choice.rarity)).join('')}</div>${this.saveUI?.render('pause')??''}<button class="refresh" data-action="restart">返回标题 · 保留本次选择</button></div>`);}
  else if(w.expedition.pendingShopSupply){this.put('overlay',`<div class="reward-screen"><h2>选择替换兵种</h2><div id="reward-cards">${w.expedition.familySlots.map(f=>{const p=familyRetirementPreview(w,f);return `<button class="reward-card" data-action="shop-supply-confirm" data-family="${f}">${icon('unit.'+f)}<h3>${SC2_UNITS[f].zh}</h3><p>${p.members.map(u=>`${u.rank}→${u.toRank}`).join(' / ')||'无存活成员'}</p><p>退款 ${p.refund.minerals}矿 ${p.refund.gas}气 · 舱内损失 ${p.lostPassengers}</p><strong>替换并购买</strong></button>`;}).join('')}</div><button data-action="shop-supply-cancel">取消 · 返回商店</button></div>`);}
  else if(w.expedition.pendingShopElite){const choice=w.expedition.pendingShopElite,elite=ELITES[choice.variantId],loaded=this.view.gpu.has(elite.model)&&this.view.assetsPending===0,failed=this.view.modelErrors.some(error=>error.startsWith(elite.model+':'));if(loaded)this.preparingElite=null;else if(!failed&&this.preparingElite!==choice.variantId){this.preparingElite=choice.variantId;queueMicrotask(()=>{if(w.expedition.pendingShopElite?.variantId===choice.variantId)this.onPrepareReinforcement();});}this.put('overlay',`<div class="reward-screen"><h2>${elite.name} · 选择替换成员</h2><p>选择一名队员替换为精英。</p>${!loaded?`<p role="status">${failed?'精英模型加载失败，请重新准备增援或取消购买。':'正在准备精英模型，完成后才可确认购买。'}</p><button class="refresh" data-action="elite-assets-retry">重新准备精英素材</button>`:''}<div id="reward-cards">${w.eliteCandidates(choice.variantId).map(u=>`<button class="reward-card rarity-purple" data-action="shop-elite-confirm" data-id="${u.id}" ${loaded?'':'disabled'}>${icon('unit.'+u.unitType)}<h3>${unitCallsign(u)}</h3><p>Rank ${u.rank} · HP ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)}</p><strong>确认替换并购买</strong></button>`).join('')}</div><button class="refresh" data-action="shop-elite-cancel">取消 · 返回商店</button>${this.saveUI?.render('reward')??''}</div>`);}
  else if(w.expedition.pendingReceipt)this.put('overlay',renderFamilyReceipt(w));
  else if(w.eliteRescueChoice){this.put('overlay',renderRescueChoices(w,this.saveUI?.render('pause')??''));}
  else if(w.eliteChoice){const id=w.eliteChoice,e=ELITES[id];const loaded=this.view.gpu.has(e.model)&&this.view.assetsPending===0,failed=this.view.modelErrors.some(error=>error.startsWith(e.model+':'));if(loaded)this.preparingElite=null;else if(!failed&&this.preparingElite!==id){this.preparingElite=id;queueMicrotask(()=>{if(w.eliteChoice===id)this.onPrepareReinforcement();});}this.put('overlay',`<div class="reward-screen"><span class="eyebrow">ELITE REINFORCEMENT</span><h2>${e.name}</h2><p>${e.description}</p><p>选择一名普通队员晋升。</p>${!loaded?`<p role="status">${failed?'精英模型加载失败，请重试素材加载或放弃编入。':'正在准备精英模型，完成后才可编入。'}</p><button class="refresh" data-action="elite-assets-retry">重新准备精英素材</button>`:''}<div id="reward-cards">${w.eliteCandidates(id).map(u=>`<button class="reward-card rarity-purple" data-action="elite-replace" data-elite="${id}" data-id="${u.id}" ${loaded?'':'disabled'}>${icon('unit.'+u.unitType)}<h3>${unitCallsign(u)}</h3><p>Rank ${u.rank} · HP ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)}</p><strong>替换为 Rank 1 ${e.name}</strong></button>`).join('')}</div><button class="refresh" data-action="elite-cancel" data-elite="${id}">放弃本次精英编入 · 继续战斗</button>${this.saveUI?.render('pause')??''}<button class="refresh" data-action="restart">返回标题 · 保留本次选择</button></div>`);}
  else if(w.phase==='menu')this.put('overlay',renderMenu({coverIndex:this.coverIndexes[this.menuRace],coverAuto:this.coverAuto,page:this.menuPage,race:this.menuRace,difficulty:this.menuDifficulty,preset:this.menuPreset,hero:this.starterHeroChoice,loadPreview:this.loadPreview,error:this.flowError},w.permanentProfile,this.session));
  else if(w.phase==='reward')this.put('overlay',renderIntermission(w,this.saveUI?.render('reward')??'',this.intermission));
  else if(w.phase==='endless-ready')this.put('overlay',`<div class="end-screen"><span class="eyebrow">ENDLESS / PREPARATION COMPLETE</span><h2>无尽整备完成</h2><p>本窗口发展和强化已经结算。确认后将载入独立平地与原版据点建筑；小队、伤损、订单和空投随行。</p><button class="primary" data-action="endless-prepare">准备无尽战场</button><button data-action="endless-back">返回撤离选择</button><button data-action="save-export">导出当前存档</button><button class="refresh" data-action="restart">返回标题 · 保留整备</button></div>`);
  else if(w.phase==='won'||w.phase==='lost'||w.phase==='finished')this.put('overlay',`<div class="end-screen"><span class="eyebrow">MISSION ${w.phase==='lost'?'FAILED':'COMPLETE'}</span><h2>${w.phase==='lost'?'小队失联':w.phase==='finished'?'撤离完成':'第18关胜利'}</h2><p>${w.notice}</p><div class="clear-reward">${w.phase==='won'?'通关奖励已结算；请选择撤离或进入无尽整备。':''}</div><div class="end-stats"><span>${w.endless?'无尽坚持':'关卡'} <b>${w.endless?clock(w.endlessElapsed):w.stage+' / 18'}</b></span><span>击杀 <b>${w.stats.kills}</b></span><span>救援 <b>${w.stats.rescued}</b></span><span>失守 <b>${w.stats.failed}</b></span></div>${w.phase==='won'?'<button class="primary" data-action="evacuate">撤离 · 结束本局</button><button class="primary endless-launch" data-action="endless">进入无尽整备</button><p>整备后前往独立平地，无尽每轮'+ENDLESS.roundDuration+'秒。</p>':''}${this.saveUI?.render('ended')??''}<button class="primary" data-action="restart">返回标题</button></div>`);
  else if(w.paused)this.put('overlay',`<div class="end-screen"><span class="eyebrow">TACTICAL PAUSE</span><h2>战场已暂停</h2><button data-action="resource-downloads">资源下载</button>${this.flowError?'<p>此浏览器暂不支持全屏</p>':''}<button data-action="fullscreen">${fullscreenLabel()}</button><p>控制前进方向，小队自动停步走射。<br>在设置中选择鼠标 / 键盘、点击 / 摇杆。</p>${this.graphicsControls()}${this.saveUI?.render('pause')??''}${w.expedition.bossLootQueue.length?'<button class="refresh" data-action="boss-loot-open">首领奖励 · 待领取</button>':''}<button class="primary" data-action="pause">继续行动</button><button class="refresh" data-action="restart">返回标题 · 保留续局</button></div>`);
  this.root.classList.toggle('in-battle',w.phase==='battle');this.playerServices?.mount(this.root);
  const focusPhase=this.readiness?.state.kind?'loading:'+this.readiness.state.kind+':'+this.readiness.state.phase:this.talentOpen?'talents:'+this.talentPage+':'+this.talentRace+':'+this.talentLine:this.settingsOpen?'settings':w.phase==='menu'?'menu:'+this.menuPage:w.expedition.bossLootOpen?'boss-loot:'+w.expedition.bossLootQueue[0]?.receipt+':'+w.expedition.bossLootQueue[0]?.variant:w.expedition.pendingTalentLoot?'loot:'+w.expedition.pendingTalentLoot.receipt:w.eliteRescueChoice?'scout:'+w.eliteRescueChoice.receipt:w.expedition.pendingShopSupply?'shop-supply:'+w.expedition.pendingShopSupply.offerId:w.expedition.pendingShopElite?'shop-elite:'+w.expedition.pendingShopElite.offerId+':'+w.expedition.pendingShopElite.variantId:w.expedition.pendingReceipt?'receipt:'+w.expedition.pendingReceipt.id:w.eliteChoice?'elite:'+w.eliteChoice:w.phase==='reward'?'intermission:'+JSON.stringify(this.intermission.current)+':'+w.rewardRound:w.phase+':'+w.paused;if(this.lastPhase!==focusPhase){this.lastPhase=focusPhase;this.inputReset();if(w.phase==='menu'||this.readiness?.state.kind||w.phase==='reward'||w.expedition.pendingReceipt||w.expedition.pendingTalentLoot||w.expedition.bossLootOpen||w.expedition.pendingShopElite||w.eliteRescueChoice)this.focusAfterUpdate(()=>this.navigationFocus());}
 }
 async iconReport(){const ids=[...new Set([...document.querySelectorAll<HTMLImageElement>('img')].map(i=>i.src))];await Promise.all(ids.map(src=>new Promise<void>(resolve=>{const im=new Image();im.onload=()=>{if(im.naturalWidth)this.iconLoaded.add(src);resolve();};im.onerror=()=>resolve();im.src=src;})));return this.iconLoaded.size;}
}


