import {World} from '../simulation/world';
import {TERRAN,SC2_UNITS} from '../data/sc2-units';
import {icon,missingAssets} from '../assets/manifest';
import type {BattleRenderer} from '../render/scene/battle-renderer';
import {QUALITY_LABELS,resolveQuality} from '../render/settings/quality';
import {eligibleReward} from '../simulation/progression/rewards';
const fmt=(n:number)=>String(Math.max(0,Math.ceil(n))).padStart(2,'0');
const clock=(n:number)=>{const seconds=Math.max(0,Math.ceil(n));return fmt(Math.floor(seconds/60))+':'+fmt(seconds%60);};
const cost=(m:number,g:number)=>`${m} M${g?' / '+g+' G':''}`;
export class HUD {
 ready=false;loading='载入战场';lastPhase='';inputReset:()=>void=()=>{};onStart:()=>void=()=>{};
 root:HTMLElement;private cache=new Map<string,string>();private iconLoaded=new Set<string>();
 constructor(readonly world:World,readonly view:BattleRenderer){this.root=document.querySelector('#interface')!;
  this.root.innerHTML=`<header id="topbar"><span class="callsign">TERRAN <b>//</b> SURVIVORS</span><div class="resource">${icon('ui.minerals')}<span id="minerals">50</span></div><div class="resource gas">${icon('ui.gas')}<span id="gas">0</span></div><span id="stage" class="stage"></span><strong id="clock">02:00</strong><button data-action="pause" class="small" aria-label="暂停">Ⅱ</button></header>
   <div id="mission"></div><div id="notice" role="status" aria-live="polite"></div><div id="pod-alerts"></div><div id="production-status"></div>
   <div id="roster" class="console"></div><div id="skills" class="console"><button data-action="stim" id="stim">${icon('tech.stim')}<span>STIM <kbd>E</kbd></span></button><button data-action="dash" id="dash">${icon('tech.boost')}<span>推进 <kbd>SPACE</kbd></span></button></div>
   <div id="joystick" aria-label="移动小队摇杆"><span class="stick-axis"></span><span class="stick-knob"></span></div><div id="stretch"></div><div id="portrait-hint">建议旋转至横屏</div>
   <section id="overlay"></section><aside id="debug" class="console" hidden></aside>`;
  this.root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;if(button.dataset.action==='stim'||button.dataset.action==='dash'){e.preventDefault();if(button.dataset.action==='stim')world.stim();else world.dash();this.update();}});
  this.root.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;if(el.dataset.setting==='quality')view.setQuality(resolveQuality(el.value));else if(el.dataset.setting==='difficulty')world.setDifficulty(el.value==='easy'?'easy':'normal');this.update();});
  this.root.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;const action=button.dataset.action!;
   if(action==='start'&&this.ready){this.onStart();world.start();}
   else if(action==='restart')location.reload();else if(action==='pause')this.pause();
   else if(action==='stim')world.stim();else if(action==='dash')world.dash();
   else if(action==='reroll')world.reroll();else if(action==='reward'){this.inputReset();world.choose(button.dataset.id!);}else if(action==='skip'){this.inputReset();world.skipReward();}
   this.update();
  });world.listeners.add(()=>this.update());this.update();
 }
 graphicsControls(){return `<label class="graphics-settings"><span>画质</span><select data-setting="quality" aria-label="画质">${Object.entries(QUALITY_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.quality===id?'selected':''}>${label}</option>`).join('')}</select></label>`;}
 put(id:string,html:string){if(this.cache.get(id)===html)return;document.getElementById(id)!.innerHTML=html;this.cache.set(id,html);}
 pause(){if(this.world.phase==='battle'){this.world.paused=!this.world.paused;this.inputReset();this.world.changed();}}
 setLoading(text:string){this.loading=text;this.update();}
 finishLoading(){const missing=missingAssets();this.ready=this.view.loadedModels===8&&missing.length===0;this.loading=this.ready?'战场就绪':'缺少战场素材';this.update();this.root.querySelector<HTMLButtonElement>('[data-action=start]')?.focus();}
 update(){const w=this.world;
  this.put('minerals',String(Math.floor(w.wallet.minerals)));this.put('gas',String(Math.floor(w.wallet.gas)));this.put('stage',`STAGE <b>${String(w.stage).padStart(2,'0')}</b> / 12`);this.put('clock',clock(w.duration-w.stageElapsed));
  this.put('mission',`<span class="eyebrow">${w.difficulty==='easy'?'简单':'普通'} / CHAR</span><b>${w.config.name}</b>${w.stage===12?'<span>摧毁虫巢 · 存活至撤离</span>':''}`);
  this.put('notice',w.time<w.noticeUntil?w.notice:'');this.put('stretch',`战线 <b class="${w.maxStretch>20?'warning':''}">${w.maxStretch.toFixed(1)} m</b>`);
  this.put('roster',TERRAN.map(t=>{const units=w.allies().filter(u=>u.unitType===t);return `<div class="unit-status">${icon('unit.'+t,SC2_UNITS[t].name)}<div><span class="unit-name">${SC2_UNITS[t].zh}</span><b>${units.length}<small>/5</small></b><div class="soldiers">${Array.from({length:5},(_,i)=>{const u=units[i];return `<span class="soldier ${u?'':'empty'}" title="${u?'Rank '+u.rank+' · '+Math.ceil(u.hp)+' / '+Math.ceil(u.maxHp)+' HP':'空席'}">${u?'ⅠⅡⅢⅣⅤ'[u.rank-1]:'–'}<i style="--hp:${u?u.hp/u.maxHp*100:0}%;--health:${u&&u.hp/u.maxHp<.3?'#ef7449':'#79e6a2'}"></i></span>`;}).join('')}</div></div></div>`;}).join(''));
  const stim=document.querySelector<HTMLButtonElement>('#stim')!,dash=document.querySelector<HTMLButtonElement>('#dash')!;stim.disabled=!w.upgrades.has('stim')||w.phase!=='battle'||w.paused;dash.disabled=w.time<w.dashReady||w.phase!=='battle'||w.paused;dash.title=w.time<w.dashReady?`冷却 ${fmt(w.dashReady-w.time)} 秒`:'短时推进';stim.title=w.upgrades.has('stim')?'枪兵消耗 10 HP，提高攻速与移速':'尚未研究兴奋剂';
  this.put('pod-alerts',w.pods.filter(p=>['falling','active','opening'].includes(p.status)).slice(-4).map(p=>{const dx=p.x-w.anchor.x,dz=p.z-w.anchor.z;return `<div class="pod-alert"><span class="arrow" style="transform:rotate(${Math.atan2(dz,dx)}rad)">➤</span><span>${SC2_UNITS[p.unitType].zh}增援<small>${Math.round(Math.hypot(dx,dz))} m · HP ${Math.ceil(p.hp)} / ${p.maxHp}</small></span><b>${p.status==='falling'?'空投中':p.status==='opening'?'出舱中':'受袭'}</b></div>`;}).join('')+[...w.economicTargets.values()].filter(e=>e.kind==='egg'&&e.status==='active').map(e=>`<div class="pod-alert worker-alert"><span class="arrow" style="transform:rotate(${Math.atan2(e.z-w.anchor.z,e.x-w.anchor.x)}rad)">➤</span><span>被困 SCV<small>${Math.round(Math.hypot(e.x-w.anchor.x,e.z-w.anchor.z))} m</small></span><b>${clock(e.expiresAt!-w.time)}</b></div>`).join(''));
  this.put('production-status',`<span>SCV ${w.scvs}</span>${[...w.buildings.values()].map(b=>`<span>${icon('building.'+b.type)}${b.remaining>0?'建造 '+fmt(b.remaining)+'s':b.queue[0]?SC2_UNITS[b.queue[0].unitType].zh+' '+fmt(b.queue[0].remaining)+'s':'待命'}</span>`).join('')}`);
  const overlay=document.querySelector<HTMLElement>('#overlay')!;overlay.hidden=w.phase==='battle'&&!w.paused;
  if(w.phase==='menu')this.put('overlay',`<div class="title-screen"><span class="eyebrow">TERRAN EXPEDITION / CHAR SECTOR</span><h1>SC2 <span>SURVIVORS</span></h1><h2>星际幸存小队</h2><div class="title-rule"></div><p class="lead">前线已经抵达。你的坦克还在路上。</p><p>穿越虫潮，救援增援与工兵，守住 12 关。</p><button class="primary launch" data-action="start" ${this.ready?'':'disabled'}>${this.ready?'部署小队　 /　 DEPLOY':this.loading}</button><label class="graphics-settings">难度 <select data-setting="difficulty" aria-label="难度"><option value="easy" ${w.difficulty==='easy'?'selected':''}>简单</option><option value="normal" ${w.difficulty==='normal'?'selected':''}>普通</option></select></label>${this.graphicsControls()}<div class="controls-note"><span>WASD / 方向键 · 移动</span><span>E · 兴奋剂</span><span>SPACE · 推进</span></div><small class="legal">非官方 · 非盈利 · 朋友试玩 / StarCraft II 素材属于 Blizzard Entertainment</small>${import.meta.env.DEV&&!this.ready?`<p class="warning">${missingAssets().map(a=>a.id).concat(this.view.modelErrors).join(' / ')}</p>`:''}</div>`);
  else if(w.phase==='reward')this.put('overlay',`<div class="reward-screen"><span class="eyebrow">MISSION DEBRIEF / ${String(w.stage).padStart(2,'0')}</span><h2>战地增援</h2><p>购买一项支援，或保留资源继续行动。</p><div id="reward-cards">${w.rewards.map((r,i)=>`<button class="reward-card" data-action="reward" data-id="${r.id}" ${eligibleReward(w,r)?'':'disabled'}><span class="card-number">0${i+1}</span>${icon(r.icon,r.name)}<h3>${r.name}</h3><p>${r.description}</p><strong>${cost(r.minerals,r.gas)}${r.discount?`<em>${Math.round((1-r.discount)*100)}% 价格</em>`:''}</strong><span class="card-select">${eligibleReward(w,r)?'购买支援　▸':'资源不足'}</span></button>`).join('')}</div><div class="reward-actions"><button class="refresh" data-action="reroll" ${w.wallet.minerals<w.rerollCost()?'disabled':''}>⟳ REFRESH <span>${w.rerollCost()} Minerals</span></button><button class="refresh" data-action="skip">跳过 · 保留资源</button></div><small>资源 ${Math.floor(w.wallet.minerals)} M / ${Math.floor(w.wallet.gas)} G · 只能购买一项</small></div>`);
  else if(w.phase==='won'||w.phase==='lost')this.put('overlay',`<div class="end-screen"><span class="eyebrow">MISSION ${w.phase==='won'?'COMPLETE':'FAILED'}</span><h2>${w.phase==='won'?'撤离成功':'小队失联'}</h2><p>${w.notice}</p><div class="end-stats"><span>关卡 <b>${w.stage} / 12</b></span><span>击杀 <b>${w.stats.kills}</b></span><span>救援 <b>${w.stats.rescued}</b></span><span>失守 <b>${w.stats.failed}</b></span></div><button class="primary" data-action="restart">重新部署</button></div>`);
  else if(w.paused)this.put('overlay',`<div class="end-screen"><span class="eyebrow">TACTICAL PAUSE</span><h2>战场已暂停</h2>${this.graphicsControls()}<button class="primary" data-action="pause">继续行动</button></div>`);
  this.root.classList.toggle('in-battle',w.phase==='battle');
  if(this.lastPhase!==w.phase){this.lastPhase=w.phase;this.inputReset();if(w.phase==='reward')queueMicrotask(()=>this.root.querySelector<HTMLButtonElement>('.reward-card:not(:disabled),[data-action="skip"]')?.focus());}
 }
 async iconReport(){const ids=[...new Set([...document.querySelectorAll<HTMLImageElement>('img')].map(i=>i.src))];await Promise.all(ids.map(src=>new Promise<void>(resolve=>{const im=new Image();im.onload=()=>{if(im.naturalWidth)this.iconLoaded.add(src);resolve();};im.onerror=()=>resolve();im.src=src;})));return this.iconLoaded.size;}
}
