import {CarrierInspector} from './hud/carrier-inspector';
import {bindHudSafeLayout} from './hud/layout';
import {setTextScale,textScale} from './text-scale';
import {openResourceDownloads} from './hud/resource-downloads';
import {tacticalCard,UNIQUE_SUPPORT} from '../data/unique-support';
import {familyRetirementPreview} from '../simulation/expedition-production';
import {toggleNativeFullscreen,fullscreenLabel} from './mobile/viewport';
import {SquadConsole} from './hud/squad-console';
import {DetectionHint} from './hud/detection-hint';
import {RESCUE_PRESENTATION} from '../data/economy';
import {renderBossLoot} from './hud/boss-loot-panel';
import type {SaveControls} from './hud/save-controls';
import type {RunSession,LoadPreview} from '../app/run-session';
import type {AssetReadinessCoordinator} from '../app/asset-readiness';
import {renderMenu,renderReadiness,type MenuPage} from './hud/m3-menu';
import type {Difficulty} from '../data/stages';
import type {PresetSlot} from '../simulation/progression/permanent-profile';
import type {ControlSettings} from './controls/settings';
import {healthReadout,rankLabel,rewardOwnership,unitCallsign,statusReadout} from './unit-identity';
import {HEROES,ALL_HERO_IDS,HERO_IDS_BY_RACE,type HeroId} from '../data/heroes';
import {talentRank} from '../data/mvp-talents';
import {ELITES,type EliteId} from '../data/elites';
import {RARITIES} from '../data/rewards';
import {Minimap} from './hud/minimap';
import {World} from '../simulation/world';
import type {Reward} from '../simulation/types';
import type {ExpeditionReward} from '../simulation/progression/expedition-drafts';
import {SC2_UNITS,type UnitType} from '../data/sc2-units';
import {icon,missingAssets} from '../assets/manifest';
import type {BattleRenderer} from '../render/scene/battle-renderer';
import {QUALITY_LABELS,resolveQuality,ANIMATION_MODE_LABELS,resolveAnimationMode} from '../render/settings/quality';
import {RACES,RACE_NAMES,type Race,type FamilyId} from '../data/races';
import {PRODUCTION_LINES,type ProductionLineId} from '../data/expedition-buildings';
import {renderExpeditionProduction,renderFamilyReceipt,renderUnitOperations} from './hud/expedition-panel';
import {renderMvpTalentPanel} from './hud/mvp-talent-panel';
const fmt=(n:number)=>String(Math.max(0,Math.ceil(n))).padStart(2,'0');
const clock=(n:number)=>{const seconds=Math.max(0,Math.ceil(n));return fmt(Math.floor(seconds/60))+':'+fmt(seconds%60);};
const cost=(m:number,g:number)=>`${m} 矿${g?' / '+g+' 气':''}`;
function eliteVariantButtons(w:World,family:FamilyId,action:string,attributes:string,enabled:boolean,label:string){const variants=Object.values(ELITES).filter(e=>e.family===family);return `<div class="elite-variant-grid" role="group" aria-label="${SC2_UNITS[family as UnitType]?.zh??family}精英型号">${variants.map(elite=>`<button class="elite-variant" data-action="${action}" ${attributes} data-variant="${elite.id}" ${enabled&&w.canAcquireElite(elite.id)?'':'disabled'}><b>${elite.name}</b><small>${elite.template} · ${elite.description}</small><strong>${w.eliteOwned(elite.id)?.rank===5?'已满级':w.eliteOwned(elite.id)?'升级 · '+label:'招募 · '+label}</strong></button>`).join('')||'<span>本家族暂无可招募的精英型号</span>'}</div>`;}
function eliteFamilyOf(reward:Reward):FamilyId|undefined {if(!('expeditionEffect' in reward))return;const effect=(reward as ExpeditionReward).expeditionEffect;return effect.kind==='elite'?effect.family:undefined;}
function shortOffer(r:Reward){
 const e=(r as ExpeditionReward).expeditionEffect;
 if(e?.kind==='card'&&e.effect==='cultivation')return e.amount===1?`1名${SC2_UNITS[e.family].zh}提升1级`:`${SC2_UNITS[e.family].zh}合计提升${e.amount}级`;
 if(e?.kind==='resource')return '获得 '+[e.minerals?`${e.minerals}矿`:null,e.gas?`${e.gas}气`:null].filter(Boolean).join(' + ');
 if(e?.kind==='hero')return '招募英雄／已有英雄提升1级';
 if(e?.kind==='elite')return e.targetRank===5?'选择型号 · 招募或提升至V级':'选择型号 · 招募I级／已有型号升1级';
 if(e?.kind==='development')return r.description.split('。')[0];
 return r.description.split('；')[0].split('。')[0];
}
function renderDraftCard(w:World,r:Reward,i:number){const receipt=(r as ExpeditionReward).purchaseReceipt,family=eliteFamilyOf(r),enabled=w.canChooseReward(r),shell=`<span class="card-number">0${i+1} · ${RARITIES[r.rarity].name}</span>${icon(r.icon,r.name)}<h3>${family?SC2_UNITS[family as UnitType]?.zh+' · 精英型号':r.name}</h3>${rewardOwnership(w,r)?`<span class="card-ownership" data-ownership="${r.kind}" data-unit="${r.value}">${rewardOwnership(w,r)}</span>`:''}<p>${shortOffer(r)}</p><strong>${r.sold?(receipt?.freeSource?'已售罄 · 天赋免单':'已售罄'):w.rewardRound==='random'&&w.expedition.freePurchasesRemaining>0?'天赋免单':cost(r.minerals,r.gas)}${r.discount?`<small>随机 ${Math.round((1-r.discount)*100)}% 价格</small>`:''}${w.talent('permanent_discount')?'<small>含永久折扣</small>':''}</strong>`;
 if(family)return `<article class="reward-card rarity-${r.rarity} elite-family-card" style="--rarity:${RARITIES[r.rarity].color}" data-rarity="${r.rarity}">${shell}<details class="offer-details" data-panel="variant-${r.offerId}"><summary>选择型号</summary>${eliteVariantButtons(w,family,'reward',`data-id="${r.offerId}"`,enabled,r.sold?'已售罄':'购买此型')}</details></article>`;
 return `<article class="shop-offer"><button class="reward-card rarity-${r.rarity}" style="--rarity:${RARITIES[r.rarity].color}" data-rarity="${r.rarity}" data-action="reward" data-id="${r.offerId}" ${enabled?'':'disabled'}>${shell}${r.discount?`<em>${Math.round((1-r.discount)*100)}% 价格</em>`:''}<span class="card-select">${r.sold?'已售罄':enabled?'购买　▸':'暂不可购买'}</span></button><details class="offer-details" data-panel="offer-${r.offerId}"><summary>详情</summary><p>${r.description}</p></details></article>`;
}
function renderTalentLootCard(w:World,offer:Reward,index:number,receipt:string,rarity:'purple'|'orange'){const family=eliteFamilyOf(offer),shell=`<span class="card-number">0${index+1}</span>${icon(offer.icon,offer.name)}<h3>${family?SC2_UNITS[family as UnitType]?.zh+' · 精英型号':offer.name}</h3><p>${offer.description}</p><strong>免费领取</strong>`;return family?`<article class="reward-card rarity-${rarity} elite-family-card">${shell}${eliteVariantButtons(w,family,'talent-loot',`data-receipt="${receipt}" data-id="${offer.offerId}"`,true,'免费领取')}</article>`:`<button class="reward-card rarity-${rarity}" data-action="talent-loot" data-receipt="${receipt}" data-id="${offer.offerId}">${shell}</button>`;}
function renderRescueChoices(w:World,saveUI:string){const right=w.eliteRescueChoice;if(!right)return '';const elite=ELITES[right.eliteId as EliteId];return `<div class="reward-screen"><span class="eyebrow">ELITE RESCUE</span><h2>${SC2_UNITS[elite.family as UnitType]?.zh??elite.family} · 救援权</h2><p>选择一款精英加入队伍。</p><div id="reward-cards"><article class="reward-card rarity-purple elite-family-card">${icon(elite.icon,elite.name)}<h3>选择精英型号</h3>${eliteVariantButtons(w,elite.family,'elite-rescue-claim',`data-receipt="${right.receipt}"`,true,'免费领取')}</article></div><button class="refresh" data-action="elite-rescue-decline" data-receipt="${right.receipt}">放弃本次救援 · 继续战斗</button>${saveUI}<button class="refresh" data-action="restart">返回标题 · 保留救援权</button></div>`;}
function renderEliteContracts(w:World){if(w.rewardRound!=='random'||!w.expedition.eliteContracts.length)return '';
 return `<section class="elite-contracts"><h3>精英特约 · 付费自选</h3><div class="production-choices">${w.expedition.eliteContracts.map(c=>{const elite=ELITES[c.eliteId as EliteId],canBuy=!c.purchased&&w.wallet.minerals>=c.minerals&&w.wallet.gas>=c.gas;return `<article class="reward-card rarity-purple elite-family-card">${icon('unit.'+c.family)}<h4>${SC2_UNITS[c.family as UnitType]?.zh??elite?.name??c.eliteId} · 精英型号</h4><p>${cost(c.minerals,c.gas)} · ${c.purchased?'已购买':'选择其中一种型号，一次结算'}</p>${eliteVariantButtons(w,c.family,'elite-contract',`data-id="${c.id}"`,canBuy,'购买此型')}</article>`;}).join('')}</div></section>`;
}
function renderStarterHero(w:World,selected:HeroId|null){const race=w.permanentProfile.activeRace;if(!talentRank(w.permanentProfile.levels,race,'hero_support'))return '';
 return `<label class="graphics-settings">开局英雄<select data-setting="starter-hero" aria-label="开局英雄">${HERO_IDS_BY_RACE[race].map(id=>`<option value="${id}" ${selected===id?'selected':''}>${HEROES[id].name} · ${HEROES[id].skill}</option>`).join('')}</select></label>`;
}
function renderIntermission(w:World,saveUI:string){
 const building=w.rewardRound==='building',direction=w.expedition.developmentDirection;
 const directions=Object.entries(PRODUCTION_LINES).filter(([,l])=>l.race===w.expedition.race).map(([id,l])=>`<button class="refresh" data-action="development-direction" data-line="${id}" aria-pressed="${id===direction}">${l.name}</button>`).join('');
 const revive=[...w.heroes.keys()].filter(id=>!(w.heroEntity(id)?.hp)).map(id=>{const h=w.heroes.get(id)!,p=w.revivalCost(h.rank);return `<button class="refresh" data-action="revive" data-id="${id}" ${w.canReviveHero(id)?'':'disabled'}>${HEROES[id].name} · ${h.revivePaid?'下关归队':'复活'} <small>${cost(p.minerals,p.gas)}</small></button>`;}).join('');
 return `<div class="reward-screen compact-intermission"><header class="intermission-heading"><span>${w.endless?'无尽 '+w.endless.round:'第 '+w.stage+' 关'} · ${building?'发展':'商店'}</span><h2>${building?'选择发展':'补强部队'}</h2><small>本轮 +${Math.floor(w.clearReceipt?.minerals??0)} 矿 · +${Math.floor(w.clearReceipt?.gas??0)} 气</small></header>
 ${building?`<details class="direction-picker" data-panel="direction" ${direction?'':'open'}><summary>${direction?'更换方向 · '+PRODUCTION_LINES[direction].name:'选择发展方向'}</summary><div class="production-lines">${directions}</div></details>`:''}
 <div id="reward-cards">${w.rewards.map((r,i)=>renderDraftCard(w,r,i)).join('')}</div>
 <div class="reward-actions">${w.endlessEntry?'<button class="refresh" data-action="endless-back">返回</button>':''}<button class="refresh" data-action="reroll" ${building&&!direction||!Number.isFinite(w.rerollCost())||w.wallet.minerals<w.rerollCost()?'disabled':''}>刷新 <span>${Number.isFinite(w.rerollCost())?(w.rerollCost()===0?'免费':w.rerollCost()+' 矿'):'—'}</span></button><button class="refresh primary-next" data-action="skip">${building?'跳过，去商店':w.endlessEntry?'进入无尽':w.endless?'下一轮':'下一关'}</button></div>
 <details class="army-preparation" data-panel="army"><summary>部队整备${revive?' · 有英雄待复活':''}</summary>${renderEliteContracts(w)}${renderExpeditionProduction(w)}<div class="hero-revivals">${revive}</div>${saveUI}</details></div>`;
}
export class HUD {
 private detectionHint=new DetectionHint();
 private pendingFocus:(()=>HTMLElement|null|undefined)|null=null;private focusQueued=false;
 saveUI:SaveControls|null=null;
 session:RunSession|null=null;readiness:AssetReadinessCoordinator|null=null;
 menuPage:MenuPage='title';menuRace:Race='terran';menuDifficulty:Difficulty='normal';menuPreset:PresetSlot=0;loadPreview:LoadPreview|null=null;flowError='';pendingStageAdvance=false;
 onPrepareNew:()=>void=()=>{};onPrepareLoad:()=>void=()=>{};onPrepareEndless:()=>void=()=>{};onCommitFlow:()=>void=()=>{};onCancelFlow:()=>void=()=>{};onPrepareReinforcement:()=>void=()=>{};
 settingsOpen=false;talentOpen=false;selectedTalentId:string|null=null;unitOperationsOpen=false;ready=true;loading='载入战场';lastPhase='';starterHeroChoice:HeroId|null=null;private touchActionAt=0;inputReset:()=>void=()=>{};onStart:()=>void=()=>{};onRestart:()=>void=()=>{};
 readonly carrierInspector:CarrierInspector;root:HTMLElement;readonly minimap:Minimap;readonly squadConsole:SquadConsole;private cache=new Map<string,string>();private iconLoaded=new Set<string>();private preparingElite:EliteId|null=null;
 constructor(readonly world:World,readonly view:BattleRenderer,readonly controls:ControlSettings){this.root=document.querySelector('#interface')!;
  this.menuRace=world.permanentProfile.activeRace;this.menuPreset=world.permanentProfile.activePreset;try{const value=localStorage.getItem('sc2.newGameDifficulty');if(value==='easy'||value==='normal'||value==='hard'||value==='hell')this.menuDifficulty=value;}catch{}
  this.root.innerHTML=`<header id="topbar"><span class="callsign">SC2 <b>//</b> SURVIVORS</span><div class="resource">${icon('ui.minerals')}<span id="minerals">50</span></div><div class="resource gas">${icon('ui.gas')}<span id="gas">0</span></div><span id="stage" class="stage"></span><strong id="clock">02:00</strong><button data-action="pause" class="small" aria-label="暂停">Ⅱ</button></header>
   <div id="mission"></div><div id="notice" role="status" aria-live="polite"></div><div id="production-status"></div>
   <div id="hero-skills" class="console"></div><div id="skills" class="console"><button data-action="tactical" id="tactical" hidden><span>战术技能</span></button><button data-action="strategic" id="strategic"><span>战略打击</span></button><button data-action="unit-operations" id="unit-operations" hidden><span>单位操作</span></button><button data-action="detection" id="detection" hidden><span>侦测 <kbd>G</kbd></span></button><button data-action="siege" id="siege">${icon('tech.siege')}<span id="siege-label">架炮 <kbd>T</kbd></span></button><button data-action="stim" id="stim">${icon('tech.stim')}<span>STIM <kbd>E</kbd></span></button><button data-action="dash" id="dash">${icon('tech.boost')}<span>推进 <kbd>SPACE</kbd></span></button><button data-action="airlift" id="airlift" hidden>${icon('unit.medivac')}<span>空运 <kbd>F</kbd></span></button></div>
   <div id="joystick" aria-label="移动小队摇杆"><span class="stick-axis"></span><span class="stick-knob"></span></div><div id="stretch"></div><div id="portrait-hint">建议旋转至横屏</div>
   <button id="boss-loot-toggle" class="small" data-action="boss-loot-open" hidden style="position:fixed;right:14px;bottom:86px;z-index:120">首领奖励</button><section id="overlay"></section><aside id="debug" class="console" hidden></aside>`;
  this.squadConsole=new SquadConsole(world,this.root);this.carrierInspector=new CarrierInspector(world,this.root);this.minimap=new Minimap(world,view,this.root,controls);
  bindHudSafeLayout(this.root);
  this.root.addEventListener('focusin',e=>{const node=(e.target as HTMLElement).closest<HTMLElement>('[data-action="mvp-talent-select"]');if(node?.dataset.id&&node.dataset.id!==this.selectedTalentId){this.selectedTalentId=node.dataset.id;this.update();}});
  const openTransfer=()=>{this.unitOperationsOpen=false;world.paused=false;this.inputReset();document.dispatchEvent(new CustomEvent('sc2-target-family',{detail:'transfer'}));world.changed();};
  this.root.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;if(['stim','dash','siege','airlift','detection',...ALL_HERO_IDS.map(id=>'hero-'+id)].includes(button.dataset.action??'')){e.preventDefault();this.touchActionAt=performance.now();if(button.dataset.action?.startsWith('hero-'))world.castHero(button.dataset.action.slice(5) as HeroId);else if(button.dataset.action==='detection')world.castDetection();else if(button.dataset.action==='stim')world.stim();else if(button.dataset.action==='siege')world.toggleTanks();else if(button.dataset.action==='airlift')openTransfer();else world.dash();this.update();}});
  this.root.addEventListener('change',e=>{const el=e.target;if(!(el instanceof HTMLSelectElement))return;if(el.dataset.setting==='text-scale')setTextScale(Number(el.value));else if(el.dataset.setting==='quality')view.setQuality(resolveQuality(el.value));else if(el.dataset.setting==='animation-mode')view.setAnimationMode(resolveAnimationMode(el.value));else if(el.dataset.setting==='menu-preset'){this.menuPreset=Number(el.value) as PresetSlot;this.starterHeroChoice=null;}else if(el.dataset.setting==='menu-hero')this.starterHeroChoice=el.value as HeroId;else if(el.dataset.setting==='development-target')world.setDevelopmentTarget(el.value||null);else if(el.dataset.setting==='hatchery-sequence')world.assignHatcherySequence(Number(el.dataset.id),el.value as ProductionLineId);else if(el.dataset.setting==='desktop'||el.dataset.setting==='touch')controls.set(el.dataset.setting,el.value);this.update();});
  this.root.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(!button||button.disabled)return;const action=button.dataset.action!;if(action==='resource-downloads'){if(world.phase!=='battle'||world.paused)openResourceDownloads(world.phase==='menu'?this.menuRace:world.expedition.race);return;}if(action==='tactical'){if(world.expedition.race==='protoss')document.dispatchEvent(new CustomEvent('sc2-target-family',{detail:'tactical'}));else world.castTactical();this.update();return;}if(action==='strategic'){document.dispatchEvent(new CustomEvent('sc2-target-family',{detail:'strategic'}));return;}if(action==='fullscreen'){void toggleNativeFullscreen().then(ok=>{if(!ok){world.announce('此浏览器暂不支持全屏');this.flowError='此浏览器暂不支持全屏';}this.update();});return;}if(['siege','stim','dash','airlift','detection',...ALL_HERO_IDS.map(id=>'hero-'+id)].includes(action)&&performance.now()-this.touchActionAt<700)return;
   if(this.saveUI?.handle(action))return;
   if(action==='menu-new'){this.flowError='';this.menuPage='race';this.menuRace=world.permanentProfile.activeRace;this.menuPreset=world.permanentProfile.activePreset;}
   else if(action==='menu-race'&&RACES.includes(button.dataset.race as Race)){this.menuRace=button.dataset.race as Race;this.menuPreset=world.permanentProfile.activePresetFor(this.menuRace);this.starterHeroChoice=null;}
   else if(action==='menu-race-next')this.menuPage='difficulty';
   else if(action==='menu-difficulty'){const d=button.dataset.difficulty;if(d==='easy'||d==='normal'||d==='hard'||d==='hell'){this.menuDifficulty=d;try{localStorage.setItem('sc2.newGameDifficulty',d);}catch{}}}
   else if(action==='menu-difficulty-next')this.menuPage='confirm';
   else if(action==='menu-edit-talents'){if(world.selectRace(this.menuRace)){const active=world.permanentProfile.activePresetFor(this.menuRace);if(this.menuPreset!==active&&world.permanentProfile.previewTalentAllocation(this.menuRace,this.menuPreset))world.permanentProfile.activatePreset(this.menuRace,this.menuPreset);this.talentOpen=true;this.selectedTalentId=null;this.flowError='';}}
   else if(action==='menu-start'){this.flowError='';this.onPrepareNew();}
   else if(action==='menu-load'){this.flowError='';this.menuPage='load';}
   else if(action==='menu-load-local'){try{this.loadPreview=this.session?.prepareLoad()??null;this.menuPage='load-preview';this.flowError='';}catch(error){this.flowError=String((error as Error).message);}}
   else if(action==='menu-load-file'){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{if(file.size>32*1024*1024)throw Error('存档文件过大');const raw=await (this.readiness?.readImportFile(file)??file.text());if(raw===null)return;this.readiness?.cancel();try{this.loadPreview=this.session?.prepareLoad(raw)??null;this.menuPage='load-preview';this.flowError='';}catch(error){if(this.session?.inspectSave(raw).kind==='legacy'){this.session.importJSON(raw);this.flowError='旧开发战局不能续玩；可在本页导出原档并导入永久资源。';}else throw error;}}catch(error){this.readiness?.cancel();this.flowError=String((error as Error).message);}this.update();});input.click();}
   else if(action==='menu-load-ready'){this.flowError='';this.onPrepareLoad();}
   else if(action==='menu-back')this.menuBack();
   else if(action==='flow-cancel'){this.readiness?.cancel();this.onCancelFlow();this.flowError='';}
   else if(action==='flow-retry')void this.readiness?.retry();
   else if(action==='flow-continue')this.onCommitFlow();
   else if(action==='endless'){this.inputReset();world.chooseCampaignExit('endless');}
   else if(action==='evacuate'){this.inputReset();world.chooseCampaignExit('evacuate');}
   else if(action==='endless-back'){this.inputReset();world.backFromEndlessPreparation();}
   else if(action==='endless-prepare'){this.inputReset();this.onPrepareEndless();}
   else if(action==='restart'){this.settingsOpen=false;this.talentOpen=false;this.menuPage='title';this.readiness?.cancel();this.onRestart();}else if(action==='pause')this.pause();else if(action==='settings'){this.inputReset();this.talentOpen=false;this.settingsOpen=true;if(world.phase==='battle')world.paused=true;}else if(action==='settings-back')this.settingsOpen=false;
   else if(action==='talents'){this.settingsOpen=false;this.talentOpen=true;}else if(action==='talents-back')this.talentOpen=false;
   else if(action==='mvp-talent-race'&&RACES.includes(button.dataset.race as Race)){if(world.selectRace(button.dataset.race as Race)){this.starterHeroChoice=null;this.selectedTalentId=null;this.menuRace=button.dataset.race as Race;this.menuPreset=world.permanentProfile.activePreset;}}
   else if(action==='mvp-talent-preset'){world.permanentProfile.activatePreset(world.permanentProfile.activeRace,Number(button.dataset.slot) as 0|1|2);}
   else if(action==='mvp-talent-select'){this.selectedTalentId=button.dataset.id??null;}
   else if(action==='mvp-talent-buy'){world.permanentProfile.buy(button.dataset.id!);}
   else if(action==='mvp-talent-respec'){world.permanentProfile.respec(button.dataset.line as 'resources'|'soldiers'|'army'|'micro'|'all');}
   else if(action==='mvp-talent-copy'){world.permanentProfile.savePresetBlueprint(world.permanentProfile.activeRace,Number(button.dataset.slot) as 0|1|2,world.permanentProfile.levels);}
   else if(action==='unit-operations'&&world.phase==='battle'){this.unitOperationsOpen=true;world.paused=true;this.inputReset();world.changed();}
   else if((action==='unit-operations-back'||action==='unit-operations-close')){this.unitOperationsOpen=false;world.paused=false;this.inputReset();world.changed();}
   else if(action==='unit-mode'){this.unitOperationsOpen=false;world.paused=false;this.inputReset();world.setFamilyMode(button.dataset.family as FamilyId,button.dataset.mode!);world.changed();}
   else if(action==='family-ability'){this.unitOperationsOpen=false;world.paused=false;this.inputReset();if(button.dataset.family==='stalker')document.dispatchEvent(new CustomEvent('sc2-target-family',{detail:'stalker'}));else world.castFamilyAbility(button.dataset.family as FamilyId);world.changed();}
   else if(action==='production-output'){const line=button.dataset.line as ProductionLineId,family=button.dataset.family as FamilyId,plan=world.expedition.production[line];if(plan)world.setProductionOutputs(line,plan.outputs.includes(family)?plan.outputs.filter(id=>id!==family):[...plan.outputs,family]);}
   else if(action==='production-enable'){const family=button.dataset.family as FamilyId,plan=Object.values(world.expedition.production).find(plan=>plan?.outputs.includes(family));if(plan)world.setProductionEnabled(family,!plan.enabled[family]);}
   else if(action==='tactical-bind'){const family=button.dataset.family as FamilyId,field=button.closest<HTMLElement>('[data-tactical-family]'),target=Number(field?.querySelector<HTMLSelectElement>('[data-tactical-target]')?.value),direction=field?.querySelector<HTMLSelectElement>('[data-tactical-direction]')?.value as 'assault'|'guard'|'mobility';world.setTacticalEvolutionPlan(family,target,direction);}
   else if(action==='tactical-toggle'){const family=button.dataset.family as FamilyId,plan=world.expedition.tacticalPlans[family];if(plan)world.setTacticalEvolutionEnabled(family,!plan.enabled);}
   else if(action==='tactical-cancel')world.cancelTacticalEvolutionPlan(button.dataset.family as FamilyId,Number(button.dataset.revision));
   else if(action==='family-replace'){this.inputReset();world.commitFamilyReplacement(button.dataset.request!,button.dataset.old as FamilyId,Number(button.dataset.revision));}
   else if(action==='family-reject'){this.inputReset();world.rejectIncomingBatch(button.dataset.request!,Number(button.dataset.revision));}
   else if(action==='elite-contract'){this.inputReset();world.buyEliteContract(button.dataset.id!,button.dataset.variant as EliteId|undefined);}
   else if(action==='boss-loot-open'){this.inputReset();world.openBossLoot();}
   else if(action==='boss-loot-close'){this.inputReset();world.closeBossLoot();}
   else if(action==='boss-loot-variant'){this.inputReset();world.selectBossLootVariant(button.dataset.receipt!,button.dataset.variant as EliteId);}
   else if(action==='boss-loot-variant-back'){this.inputReset();world.selectBossLootVariant(button.dataset.receipt!,null);}
   else if(action==='boss-loot-claim'){this.inputReset();world.claimBossLoot(button.dataset.receipt!,button.dataset.variant as EliteId|undefined,button.dataset.target?Number(button.dataset.target):undefined);}
   else if(action==='talent-loot'){this.inputReset();world.claimTalentLoot(button.dataset.receipt!,button.dataset.id!,button.dataset.variant as EliteId|undefined);}
   else if(action==='elite-rescue-claim'){this.inputReset();world.claimEliteRescueRight(button.dataset.receipt!,button.dataset.variant as EliteId|undefined);}
   else if(action==='elite-rescue-decline'){this.inputReset();world.declineEliteRescueRight(button.dataset.receipt!);}
   else if(action==='elite-cancel'){this.inputReset();world.cancelPendingEliteChoice(button.dataset.elite as EliteId);}
   else if(action==='repair-all'){const units=button.dataset.family?world.familyBodies(button.dataset.family as FamilyId):world.allies(),quote=world.previewRepair(units.filter(unit=>!unit.temporary&&!unit.summonOwnerId).map(unit=>unit.id));if(quote&&quote.id===button.dataset.quote)world.purchaseRepair(quote.id);}
   else if(action==='detection')world.castDetection();else if(action==='siege')world.toggleTanks();else if(action==='stim')world.stim();else if(action==='dash')world.dash();else if(action==='airlift')openTransfer();
   else if(action.startsWith('hero-'))world.castHero(action.slice(5) as HeroId);else if(action==='revive')world.reviveHero(button.dataset.id as HeroId);
   else if(action==='elite-replace'){const elite=ELITES[button.dataset.elite as EliteId];if(elite&&this.view.gpu.has(elite.model)&&this.view.assetsPending===0){this.inputReset();world.replaceWithElite(elite.id,Number(button.dataset.id));}}
   else if(action==='elite-assets-retry')this.onPrepareReinforcement();
   else if(action==='shop-supply-cancel')world.cancelShopSupply();else if(action==='shop-supply-confirm')world.confirmShopSupply(button.dataset.family as FamilyId);else if(action==='shop-elite-cancel')world.cancelShopElite();else if(action==='shop-elite-confirm')world.confirmShopElite(Number(button.dataset.id));else if(action==='development-direction'){const panel=button.closest('details');if(panel)panel.open=false;world.setDevelopmentDirection(button.dataset.line as ProductionLineId);}else if(action==='reroll')world.reroll();else if(action==='reward'){this.inputReset();world.choose(button.dataset.id!,button.dataset.variant as EliteId|undefined);}else if(action==='skip'){
    this.inputReset();
    if(world.phase==='reward'&&world.rewardRound==='random'&&!world.endlessEntry){this.pendingStageAdvance=true;this.onPrepareReinforcement();}
    else world.skipReward();
   }
   this.update();
  });controls.listeners.add(()=>this.update());world.listeners.add(()=>this.update());world.permanentProfile.listeners.add(()=>this.update());this.update();
 }
 graphicsControls(){return '<button class="small" data-action="settings">设置 · 操作与画质</button>';}
 talentPanel(){return renderMvpTalentPanel(this.world.permanentProfile,this.selectedTalentId);}

 settingsPanel(){return `<div class="end-screen control-settings"><span class="eyebrow">OPTIONS</span><h2>操作设置</h2>
  <label class="graphics-settings">电脑移动<select data-setting="desktop" aria-label="电脑移动"><option value="mouse" ${this.controls.desktop==='mouse'?'selected':''}>鼠标 · 左 / 右键点击移动</option><option value="keyboard" ${this.controls.desktop==='keyboard'?'selected':''}>键盘 · WASD / 方向键</option></select></label>
  <label class="graphics-settings">手机移动<select data-setting="touch" aria-label="手机移动"><option value="joystick" ${this.controls.touch==='joystick'?'selected':''}>摇杆 · 左侧虚拟摇杆</option><option value="tap" ${this.controls.touch==='tap'?'selected':''}>点击 · 点按战场移动</option></select></label>
  <p>按前进方向自动索敌、停步开火后继续移动。<br>无需点选敌人；点击敌人所在位置也只会前往该位置。</p>
  <p>手柄：左摇杆移动，右摇杆选择技能，A / X 施放。<br>键盘技能：T 架炮，E 兴奋剂，Space 推进，G 侦测，1 / 2 / 3 英雄。</p>
  <button class="small" data-action="controller">手柄校准</button>
  <label class="graphics-settings">画质<select data-setting="quality" aria-label="画质">${Object.entries(QUALITY_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.quality===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <label class="graphics-settings">单位动作<select data-setting="animation-mode" aria-label="单位动作">${Object.entries(ANIMATION_MODE_LABELS).map(([id,label])=>`<option value="${id}" ${this.view.animationMode===id?'selected':''}>${label}</option>`).join('')}</select></label>
  <p>完整动作更流畅，节能模式更省电。</p><label class="graphics-settings">文字大小<select data-setting="text-scale" aria-label="文字大小">${[1,1.25,1.5].map(n=>`<option value="${n}" ${textScale()===n?'selected':''}>${n*100}%</option>`).join('')}</select></label>
  ${this.saveUI?.render('settings')??''}<button class="primary" data-action="settings-back">返回</button></div>`;}
 private focusAfterUpdate(pick:()=>HTMLElement|null|undefined){this.pendingFocus=pick;if(this.focusQueued)return;this.focusQueued=true;queueMicrotask(()=>{this.focusQueued=false;const target=this.pendingFocus?.();this.pendingFocus=null;if(target?.isConnected&&document.activeElement!==target)target.focus({preventScroll:true});});}
 put(id:string,html:string){if(this.cache.get(id)===html)return;const root=document.getElementById(id)!,focused=document.activeElement as HTMLElement|null,wasInside=!!focused&&root.contains(focused),action=focused?.dataset.action,offer=focused?.dataset.id,setting=focused?.dataset.setting,race=focused?.dataset.race,slot=focused?.dataset.slot,panel=focused?.tagName==='SUMMARY'?focused.parentElement?.dataset.panel:null;const oldIndex=wasInside?[...root.querySelectorAll('button,select,summary')].indexOf(focused!):-1;const panels=[...root.querySelectorAll<HTMLDetailsElement>('details[data-panel][open]')].map(e=>e.dataset.panel);root.innerHTML=html;for(const panel of root.querySelectorAll<HTMLDetailsElement>('details[data-panel]'))if(panels.includes(panel.dataset.panel))panel.open=true;this.cache.set(id,html);if(wasInside)this.focusAfterUpdate(()=>{const all=[...root.querySelectorAll<HTMLElement>('button,select,summary')];const same=all.find(e=>!e.matches(':disabled')&&(panel?e.tagName==='SUMMARY'&&e.parentElement?.dataset.panel===panel:offer?e.dataset.id===offer:setting?e.dataset.setting===setting:e.dataset.action===action&&(!race||e.dataset.race===race)&&(!slot||e.dataset.slot===slot)));return same??all.slice(Math.max(0,oldIndex)).find(e=>!e.matches(':disabled'))??all.find(e=>!e.matches(':disabled'));});}
  menuBack(){if(this.readiness?.state.kind){this.readiness.cancel();this.onCancelFlow();return;}if(this.talentOpen){this.talentOpen=false;this.update();return;}if(this.menuPage==='load-preview'){this.session?.cancelPreparedLoad();this.loadPreview=null;this.menuPage='load';}else if(this.menuPage==='load'||this.menuPage==='race')this.menuPage='title';else if(this.menuPage==='difficulty')this.menuPage='race';else if(this.menuPage==='confirm')this.menuPage='difficulty';this.flowError='';this.update();}
  pause(){if(this.readiness?.state.kind||this.world.phase==='menu'){this.menuBack();return;}if(this.world.expedition.bossLootOpen){this.world.closeBossLoot();this.inputReset();this.update();return;}if(this.unitOperationsOpen){this.unitOperationsOpen=false;this.world.paused=false;this.inputReset();this.world.changed();return;}if(this.settingsOpen){this.settingsOpen=false;this.inputReset();this.update();return;}if(this.world.phase==='reward'&&this.world.endlessEntry){this.world.backFromEndlessPreparation();return;}if(this.world.phase==='battle'){this.world.paused=!this.world.paused;this.inputReset();this.world.changed();}}
 setLoading(text:string){this.loading=text;this.update();}
 finishLoading(){const missing=missingAssets();this.ready=this.view.initialAssetsLoaded&&missing.length===0&&this.view.modelErrors.length===0;this.loading=this.ready?'战场就绪':'缺少战场素材';this.update();this.root.querySelector<HTMLButtonElement>('[data-action=save-continue]:not(:disabled),[data-action=start]')?.focus();}
 update(){const w=this.world;document.body.dataset.rules='mvp';document.body.dataset.race=w.expedition.race;document.body.dataset.touchControls=this.controls.touch;document.body.dataset.desktopControls=this.controls.desktop;this.minimap.update();
  this.put('minerals',String(Math.floor(w.wallet.minerals)));this.put('gas',String(Math.floor(w.wallet.gas)));this.put('stage',w.endless?`ENDLESS <b>${String(w.endless.round).padStart(2,'0')}</b>`:`STAGE <b>${String(w.stage).padStart(2,'0')}</b> / ${18}`);this.put('clock',clock(w.duration-w.stageElapsed));
  this.put('mission',`<span class="eyebrow">${({easy:'简单',normal:'普通',hard:'困难',hell:'地狱'}[w.difficulty])} / ${w.terrain?.definition?.source.name??'CHAR'}</span><b>${w.endless?'无尽战场 · 第 '+w.endless.round+' 轮':w.config.name}</b>${w.endless?`<span>坚持 ${clock(w.endlessElapsed)} · 精英 ${w.endless.elites} / Boss ${w.endless.bosses}</span>`:w.stage===18?'<span>摧毁虫巢 · 击杀雷兽首领 · 存活至撤离</span>':''}`);
  this.put('notice',w.time<w.noticeUntil?w.notice:'');this.put('stretch','');
  this.squadConsole.update();this.carrierInspector.update();
  const stim=document.querySelector<HTMLButtonElement>('#stim')!,dash=document.querySelector<HTMLButtonElement>('#dash')!,airlift=document.querySelector<HTMLButtonElement>('#airlift')!;stim.hidden=w.expedition.race!=='terran';stim.disabled=!w.expedition.tech.stim||w.phase!=='battle'||w.paused;dash.disabled=w.time<w.dashReady||w.phase!=='battle'||w.paused;dash.title=w.time<w.dashReady?`冷却 ${fmt(w.dashReady-w.time)} 秒`:'短时推进';stim.title=w.expedition.tech.stim?'枪兵消耗 10 HP，提高攻速与移速':'尚未研究兴奋剂';airlift.hidden=!w.talent('airlift');airlift.disabled=w.phase!=='battle'||w.paused||w.time<w.airliftReady||!!w.talentTransferPlan;const transferName=w.expedition.race==='terran'?'空运':w.expedition.race==='zerg'?'地下转移':'战场召回';airlift.title=w.talentTransferPlan?'转移准备中':w.time<w.airliftReady?`冷却 ${fmt(w.airliftReady-w.time)} 秒`:'选择前方集结点';this.put('airlift',`${icon(w.expedition.race==='terran'?'unit.medivac':w.expedition.race==='zerg'?'unit.queen':'unit.sentry')}<span>${transferName} <kbd>F</kbd></span>`);
  this.put('hero-skills',[...w.heroes.keys()].map((id,heroSlot)=>{const h=w.heroes.get(id)!,u=w.heroEntity(id),data=HEROES[id],alive=!!u&&u.hp>0,left=Math.max(0,h.skillReady-w.time),hp=healthReadout(alive?u!.hp:0,u?.maxHp??data.hp*(1+.2*(h.rank-1)));return `<div class="hero-status ${alive?'':'fallen'} ${hp.critical?'critical':''}" data-hero="${id}"><button class="hero-skill" data-action="hero-${id}" data-hero-slot="${heroSlot}" ${w.canCastHero(id)&&!this.view.assetsPending?'':'disabled'} title="${data.name} · Rank ${h.rank} · ${data.skill}">${icon('hero.'+id,data.name)}<span><b>★ ${data.name} ${rankLabel(h.rank)}</b><small>${alive?left>0?'冷却 '+clock(left):data.skill:h.revivePaid?'下关复活':h.awaitingSpawn?'待部署':'阵亡'}</small><kbd>${heroSlot+1}</kbd></span></button><div class="hero-vitals" role="meter" aria-label="${data.name}生命" aria-valuemin="0" aria-valuenow="${hp.current}" aria-valuemax="${hp.max}"><i style="width:${hp.ratio*100}%"></i><span>HP ${hp.current} / ${hp.max}${u?.maxShield?' · 盾 '+Math.ceil(u.shield??0):''}</span></div></div>`;}).join(''));

  const operations=document.querySelector<HTMLButtonElement>('#unit-operations')!;operations.hidden=false;operations.disabled=w.phase!=='battle'||w.paused||w.requiresPlayerDecision;
  const tactical=document.querySelector<HTMLButtonElement>('#tactical')!,tacticalId=tacticalCard(w.expedition.race),tacticalState=w.expedition.support.unique;tactical.hidden=!(tacticalState.levels[tacticalId]);tactical.disabled=w.phase!=='battle'||w.paused||w.requiresPlayerDecision||w.time<tacticalState.ready||!!tacticalState.prism;this.put('tactical',`<span>${UNIQUE_SUPPORT[tacticalId].name}${w.time<tacticalState.ready?' '+Math.ceil(tacticalState.ready-w.time)+'s':''}</span>`);
  const strike=document.querySelector<HTMLButtonElement>('#strategic')!,support=w.expedition.support;strike.hidden=support.ammo===0&&!support.impacts.some(i=>i.kind==='strategic');strike.disabled=w.phase!=='battle'||w.paused||w.requiresPlayerDecision||support.ammo<=0||support.impacts.some(i=>i.kind==='strategic');this.put('strategic',`<span>${w.expedition.race==='terran'?'核弹':w.expedition.race==='zerg'?'生体巨爆':'净化打击'} ×${support.ammo}</span>`);
  const detection=document.querySelector<HTMLButtonElement>('#detection')!;detection.hidden=false;const nearbyCloak=this.detectionHint.update(w);detection.classList.toggle('cloak-threat',nearbyCloak);detection.setAttribute('aria-label',nearbyCloak?'附近有隐形威胁，使用侦测':'侦测');detection.disabled=w.phase!=='battle'||w.paused||w.requiresPlayerDecision||w.time<w.expedition.detectionReady;this.put('detection',`<span>侦测 <kbd>G</kbd>${w.time<w.expedition.detectionReady?'<small>'+clock(w.expedition.detectionReady-w.time)+'</small>':''}</span>`);detection.title=w.time<w.expedition.detectionReady?'侦测冷却 '+clock(w.expedition.detectionReady-w.time):'侦测隐形单位 · 半径12 · 持续8秒 · 冷却10秒';
  document.querySelector<HTMLButtonElement>('#siege')!.hidden=!w.expedition.familySlots.includes('tank');
  const tanks=w.allies().filter(u=>u.unitType==='tank'),morphing=tanks.filter(u=>u.modeTimer>0).length;document.querySelector<HTMLButtonElement>('#siege')!.disabled=!tanks.length||w.phase!=='battle'||w.paused;this.put('siege-label',`${w.tankCommand==='tank'?'架炮':'收炮'} ${tanks.length}<kbd>T</kbd>${morphing?'<small>变形中 '+morphing+'</small>':''}`);
  this.put('production-detail',`<span>${RESCUE_PRESENTATION[w.expedition.race].workerName} ${w.workers}</span>${Object.entries(w.expedition.production).map(([line,plan])=>{const job=w.expedition!.ledger.find(j=>j.line===line&&j.state!=='settled');return `<span>${PRODUCTION_LINES[line as ProductionLineId].name} · ${job?SC2_UNITS[job.family].zh+' ×'+job.passengers.filter(p=>p.status==='waiting').length+' · '+(job.state==='training'?fmt(job.remaining)+'s':'救援中'):plan!.outputs.filter(f=>plan!.enabled[f]).map(f=>SC2_UNITS[f].zh).join(' / ')||'已关闭'}</span>`;}).join('')}`);
  this.put('production-status',`<span>${RESCUE_PRESENTATION[w.expedition.race].workerName} ${w.workers}</span>`);
  const bossLootToggle=document.querySelector<HTMLButtonElement>('#boss-loot-toggle')!;bossLootToggle.hidden=!w.expedition.bossLootQueue.length||w.expedition.bossLootOpen||w.phase==='menu'||!!this.readiness?.state.kind||this.settingsOpen||this.talentOpen||this.unitOperationsOpen;bossLootToggle.textContent=`首领奖励 · ${w.expedition.bossLootQueue.length} 件待领`;
  const overlay=document.querySelector<HTMLElement>('#overlay')!;overlay.hidden=!this.readiness?.state.kind&&!this.settingsOpen&&!this.talentOpen&&w.phase==='battle'&&!w.paused&&!w.requiresPlayerDecision;
  if(this.readiness?.showLoading)this.put('overlay',renderReadiness(this.readiness.state));
  else if(this.talentOpen)this.put('overlay',this.talentPanel());
  else if(this.settingsOpen)this.put('overlay',this.settingsPanel());
  else if(this.unitOperationsOpen)this.put('overlay',renderUnitOperations(w));
  else if(w.expedition.bossLootOpen&&w.expedition.bossLootQueue.length)this.put('overlay',renderBossLoot(w,key=>this.view.gpu.has(key)&&this.view.assetsPending===0));
  else if(w.expedition.pendingTalentLoot){const choice=w.expedition.pendingTalentLoot;this.put('overlay',`<div class="reward-screen"><span class="eyebrow">TALENT DROP · ${choice.rarity==='orange'?'ORANGE':'PURPLE'}</span><h2>出金大师 · 免费奖励</h2><p>从这次击杀的${choice.rarity==='orange'?'橙色':'紫色'}奖励中选一项。</p><div id="reward-cards">${choice.offers.map((offer,index)=>renderTalentLootCard(w,offer,index,choice.receipt,choice.rarity)).join('')}</div>${this.saveUI?.render('pause')??''}<button class="refresh" data-action="restart">返回标题 · 保留本次选择</button></div>`);}
  else if(w.expedition.pendingShopSupply){this.put('overlay',`<div class="reward-screen"><h2>选择替换兵种</h2><div id="reward-cards">${w.expedition.familySlots.map(f=>{const p=familyRetirementPreview(w,f);return `<button class="reward-card" data-action="shop-supply-confirm" data-family="${f}">${icon('unit.'+f)}<h3>${SC2_UNITS[f].zh}</h3><p>${p.members.map(u=>`${u.rank}→${u.toRank}`).join(' / ')||'无存活成员'}</p><p>退款 ${p.refund.minerals}矿 ${p.refund.gas}气 · 舱内损失 ${p.lostPassengers}</p><strong>替换并购买</strong></button>`;}).join('')}</div><button data-action="shop-supply-cancel">取消 · 返回商店</button></div>`);}
  else if(w.expedition.pendingShopElite){const choice=w.expedition.pendingShopElite,elite=ELITES[choice.variantId],loaded=this.view.gpu.has(elite.model)&&this.view.assetsPending===0,failed=this.view.modelErrors.some(error=>error.startsWith(elite.model+':'));if(loaded)this.preparingElite=null;else if(!failed&&this.preparingElite!==choice.variantId){this.preparingElite=choice.variantId;queueMicrotask(()=>{if(w.expedition.pendingShopElite?.variantId===choice.variantId)this.onPrepareReinforcement();});}this.put('overlay',`<div class="reward-screen"><h2>${elite.name} · 选择替换成员</h2><p>选择一名队员替换为精英。</p>${!loaded?`<p role="status">${failed?'精英模型加载失败，请重新准备增援或取消购买。':'正在准备精英模型，完成后才可确认购买。'}</p><button class="refresh" data-action="elite-assets-retry">重新准备精英素材</button>`:''}<div id="reward-cards">${w.eliteCandidates(choice.variantId).map(u=>`<button class="reward-card rarity-purple" data-action="shop-elite-confirm" data-id="${u.id}" ${loaded?'':'disabled'}>${icon('unit.'+u.unitType)}<h3>${unitCallsign(u)}</h3><p>Rank ${u.rank} · HP ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)}</p><strong>确认替换并购买</strong></button>`).join('')}</div><button class="refresh" data-action="shop-elite-cancel">取消 · 返回商店</button>${this.saveUI?.render('reward')??''}</div>`);}
  else if(w.expedition.pendingReceipt)this.put('overlay',renderFamilyReceipt(w));
  else if(w.eliteRescueChoice){this.put('overlay',renderRescueChoices(w,this.saveUI?.render('pause')??''));}
  else if(w.eliteChoice){const id=w.eliteChoice,e=ELITES[id];const loaded=this.view.gpu.has(e.model)&&this.view.assetsPending===0,failed=this.view.modelErrors.some(error=>error.startsWith(e.model+':'));if(loaded)this.preparingElite=null;else if(!failed&&this.preparingElite!==id){this.preparingElite=id;queueMicrotask(()=>{if(w.eliteChoice===id)this.onPrepareReinforcement();});}this.put('overlay',`<div class="reward-screen"><span class="eyebrow">ELITE REINFORCEMENT</span><h2>${e.name}</h2><p>${e.description}</p><p>选择一名普通队员晋升。</p>${!loaded?`<p role="status">${failed?'精英模型加载失败，请重试素材加载或放弃编入。':'正在准备精英模型，完成后才可编入。'}</p><button class="refresh" data-action="elite-assets-retry">重新准备精英素材</button>`:''}<div id="reward-cards">${w.eliteCandidates(id).map(u=>`<button class="reward-card rarity-purple" data-action="elite-replace" data-elite="${id}" data-id="${u.id}" ${loaded?'':'disabled'}>${icon('unit.'+u.unitType)}<h3>${unitCallsign(u)}</h3><p>Rank ${u.rank} · HP ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)}</p><strong>替换为 Rank 1 ${e.name}</strong></button>`).join('')}</div><button class="refresh" data-action="elite-cancel" data-elite="${id}">放弃本次精英编入 · 继续战斗</button>${this.saveUI?.render('pause')??''}<button class="refresh" data-action="restart">返回标题 · 保留本次选择</button></div>`);}
  else if(w.phase==='menu')this.put('overlay',renderMenu({page:this.menuPage,race:this.menuRace,difficulty:this.menuDifficulty,preset:this.menuPreset,hero:this.starterHeroChoice,loadPreview:this.loadPreview,error:this.flowError},w.permanentProfile,this.session));
  else if(w.phase==='reward')this.put('overlay',renderIntermission(w,this.saveUI?.render('reward')??''));
  else if(w.phase==='endless-ready')this.put('overlay',`<div class="end-screen"><span class="eyebrow">ENDLESS / PREPARATION COMPLETE</span><h2>无尽整备完成</h2><p>本窗口发展和强化已经结算。确认后将载入独立平地与原版据点建筑；小队、伤损、订单和空投随行。</p><button class="primary" data-action="endless-prepare">准备无尽战场</button><button data-action="endless-back">返回撤离选择</button><button data-action="save-export">导出当前存档</button><button class="refresh" data-action="restart">返回标题 · 保留整备</button></div>`);
  else if(w.phase==='won'||w.phase==='lost'||w.phase==='finished')this.put('overlay',`<div class="end-screen"><span class="eyebrow">MISSION ${w.phase==='lost'?'FAILED':'COMPLETE'}</span><h2>${w.phase==='lost'?'小队失联':w.phase==='finished'?'撤离完成':'第18关胜利'}</h2><p>${w.notice}</p><div class="clear-reward">${w.phase==='won'?'通关奖励已结算；请选择撤离或进入无尽整备。':''}</div><div class="end-stats"><span>${w.endless?'无尽坚持':'关卡'} <b>${w.endless?clock(w.endlessElapsed):w.stage+' / 18'}</b></span><span>击杀 <b>${w.stats.kills}</b></span><span>救援 <b>${w.stats.rescued}</b></span><span>失守 <b>${w.stats.failed}</b></span></div>${w.phase==='won'?'<button class="primary" data-action="evacuate">撤离 · 结束本局</button><button class="primary endless-launch" data-action="endless">进入无尽整备</button><p>整备后前往独立平地，无尽每轮240秒。</p>':''}${this.saveUI?.render('ended')??''}<button class="primary" data-action="restart">返回标题</button></div>`);
  else if(w.paused)this.put('overlay',`<div class="end-screen"><span class="eyebrow">TACTICAL PAUSE</span><h2>战场已暂停</h2><button data-action="resource-downloads">资源下载</button>${this.flowError?'<p>此浏览器暂不支持全屏</p>':''}<button data-action="fullscreen">${fullscreenLabel()}</button><p>控制前进方向，小队自动停步走射。<br>在设置中选择鼠标 / 键盘、点击 / 摇杆。</p>${this.graphicsControls()}${this.saveUI?.render('pause')??''}${w.expedition.bossLootQueue.length?'<button class="refresh" data-action="boss-loot-open">首领奖励 · 待领取</button>':''}<button class="primary" data-action="pause">继续行动</button><button class="refresh" data-action="restart">返回标题 · 保留续局</button></div>`);
  this.root.classList.toggle('in-battle',w.phase==='battle');
  const focusPhase=this.readiness?.state.kind?'loading:'+this.readiness.state.kind+':'+this.readiness.state.phase:w.phase==='menu'?'menu:'+this.menuPage:w.expedition.bossLootOpen?'boss-loot:'+w.expedition.bossLootQueue[0]?.receipt+':'+w.expedition.bossLootQueue[0]?.variant:w.expedition.pendingTalentLoot?'loot:'+w.expedition.pendingTalentLoot.receipt:w.eliteRescueChoice?'scout:'+w.eliteRescueChoice.receipt:w.expedition.pendingShopSupply?'shop-supply:'+w.expedition.pendingShopSupply.offerId:w.expedition.pendingShopElite?'shop-elite:'+w.expedition.pendingShopElite.offerId+':'+w.expedition.pendingShopElite.variantId:w.expedition.pendingReceipt?'receipt:'+w.expedition.pendingReceipt.id:w.eliteChoice?'elite:'+w.eliteChoice:w.phase==='reward'?w.phase+':'+w.rewardRound:w.phase;if(this.lastPhase!==focusPhase){this.lastPhase=focusPhase;this.inputReset();if(w.phase==='menu'||this.readiness?.state.kind||w.phase==='reward'||w.expedition.pendingReceipt||w.expedition.pendingTalentLoot||w.expedition.bossLootOpen||w.expedition.pendingShopElite||w.eliteRescueChoice)this.focusAfterUpdate(()=>this.root.querySelector<HTMLButtonElement>('.m3-menu .primary:not(:disabled),.m3-menu button:not(:disabled),.reward-card button:not(:disabled),button.reward-card:not(:disabled),[data-action="family-reject"],[data-action="skip"]'));}
 }
 async iconReport(){const ids=[...new Set([...document.querySelectorAll<HTMLImageElement>('img')].map(i=>i.src))];await Promise.all(ids.map(src=>new Promise<void>(resolve=>{const im=new Image();im.onload=()=>{if(im.naturalWidth)this.iconLoaded.add(src);resolve();};im.onerror=()=>resolve();im.src=src;})));return this.iconLoaded.size;}
}


