/** Inspection only. A successful loader does not certify original identity or SC2 fidelity. */
export async function createViewer(host){
 const T=await import('three'),{GLTFLoader}=await import('three/addons/loaders/GLTFLoader.js'),{OrbitControls}=await import('three/addons/controls/OrbitControls.js');
 const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=T.SRGBColorSpace;
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.01,500);camera.position.set(4,3,5);scene.add(new T.HemisphereLight(0xcbe8ff,0x453d32,2));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(3,6,4);scene.add(sun);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;host.append(renderer.domElement);const observer=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();});observer.observe(host);
 let model,mixer,actions=[],active,paused=false;const clock=new T.Clock();let lost=false;
 function disposeTree(root){root?.traverse(o=>{o.geometry?.dispose();for(const m of (Array.isArray(o.material)?o.material:[o.material]).filter(Boolean)){for(const v of Object.values(m))if(v?.isTexture)v.dispose();m.dispose();}});}
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;});renderer.domElement.addEventListener('webglcontextrestored',()=>{lost=false;});
 renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(lost||document.hidden||paused)return;controls.update();mixer?.update(dt);renderer.render(scene,camera);});
 return {async load(url){const loader=new GLTFLoader();const gltf=await loader.loadAsync(url);const next=gltf.scene;let meshes=0,skins=0;next.traverse(o=>{if(o.isMesh)meshes++;if(o.isSkinnedMesh)skins++;});if(!meshes)throw Error('GLB has no meshes');mixer?.stopAllAction();if(model){scene.remove(model);disposeTree(model);}model=next;scene.add(model);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3()),center=bounds.getCenter(new T.Vector3()),extent=Math.max(size.x,size.y,size.z);if(!Number.isFinite(extent)||extent<=0)throw Error('Invalid model bounds');model.position.sub(center);camera.position.set(extent*1.1,extent*.8,extent*1.5);camera.near=Math.max(.001,extent/1000);camera.far=Math.max(500,extent*100);camera.updateProjectionMatrix();controls.target.set(0,0,0);mixer=new T.AnimationMixer(model);actions=gltf.animations.map(c=>mixer.clipAction(c));active=null;return {url,meshes,skins,animations:gltf.animations.map((a,i)=>a.name||`animation_${i}`),originalIdentityVerified:false,blenderVerified:false};},play(i){if(!actions[i])return;active?.stop();active=actions[i];active.reset().play();},pause(value){paused=value;},dispose(){renderer.setAnimationLoop(null);observer.disconnect();controls.dispose();mixer?.stopAllAction();disposeTree(model);renderer.dispose();renderer.domElement.remove();}};
}
