import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {configurePlatformAssetUrl} from '../../src/assets/manifest';
import {checksum,encodeGraph} from '../../src/persistence/graph-codec';
import {scenario,type Scenario} from '../visual-plan-validation-20261009/scenario';
import {groups,identities,type Group,themes} from '../visual-plan-validation-20261009/catalog';
import type {HeroId} from '../../src/data/heroes';

const canvas=document.querySelector<HTMLCanvasElement>('#battle')!,errors:string[]=[];
let s:Scenario,r:BattleRenderer,initial:ReturnType<Scenario['world']['captureRun']>,profile='',viewHeight=19,build:unknown;
const status=(text:string)=>document.querySelector('#status')!.textContent=text;
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
const state=()=>checksum(JSON.stringify(encodeGraph({run:s.world.captureRun(),profile:s.world.permanentProfile.exportJSON()})));
function size(){r.setQuality('native');r.renderer.setPixelRatio(1);r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);r.camera.top=viewHeight;r.camera.bottom=-viewHeight;r.camera.left=-viewHeight*canvas.clientWidth/canvas.clientHeight;r.camera.right=-r.camera.left;r.camera.updateProjectionMatrix();}
function draw(){const before=state();size();r.render(0,1);if(before!==state())throw Error('Rendering mutated World/Profile/RNG');return report();}
function report(){const q={build,group:s?.group.id,theme:s?.theme,state:s?state():null,time:s?.world.time,tick:s?.world.tick,phase:s?.world.phase,subjects:s?.subjects.map(({identity,entity})=>{const u=s.world.entities.get(entity.id)??entity;return {identity:identity.id,entityId:u.id,hp:u.hp,barrier:u.barrier??0,barrierReady:u.barrierReady,deadAt:u.deadAt,x:u.x,z:u.z,action:u.action,shots:u.shotSequence};}),runtime:r?.report(),surfaces:r?[...r.gpu].filter(([,b])=>b.materialSurfaces?.length).map(([key,b])=>({key,count:b.count,capacity:1024,bytes:b.materialSurfaces.reduce((n,m)=>n+m.data.byteLength,0),materials:b.materialSurfaces.map(m=>({name:m.prepared.source.name,hash:m.prepared.profile.glbSha256,slots:Array.from({length:Math.min(b.count,20)},(_,i)=>({alpha:m.data[(10*1024+i)*4],emission:m.data[(2*1024+i)*4],opacityMultiply:m.data[(6*1024+i)*4],opacityAdd:m.data[(6*1024+i)*4+1],emissionUV:[m.data[(3*1024+i)*4],m.data[(3*1024+i)*4+1]]}))}))})):[],errors:[...errors,...(r?.report().errors??[])]};document.querySelector('#report')!.textContent=JSON.stringify(q);return q;}
async function assets(){r.prepareRosterAssets();for(const u of s.world.entities.values())if(u.hp>0)await r.ensureUnitVariant(u.modelKey??u.unitType,u.unitType);await r.prepareCurrentAssets();await r.waitForPendingAssets();}
async function settle(){await assets();for(let i=0;i<3;i++){draw();await frame();}if(report().errors.length)throw Error(JSON.stringify(report().errors));}
function selectGroup(id:string):Group {const found=groups.find(g=>g.id===id);if(found)return found;const hero=identities.find(i=>i.hero===id as HeroId);if(!hero)throw Error('Unknown fixture '+id);return {id,name:hero.name,race:hero.race,identities:[hero]};}
async function load(group='immortal',theme:typeof themes[number]='industrial'){
 document.body.dataset.ready='false';const next=scenario(selectGroup(group),theme,1);
 next.world.runId='material-batch1-fixture:'+group+':'+theme;
 // Fixed native bodies and native hit/order entry points; no synthetic visual events.
 for(const u of next.world.entities.values())u.stoppedUntil=u.nextShotAt=u.specialReady=1e9;
 if(!r){s=next;r=new BattleRenderer(canvas,s.world);await r.load(status,s.group.race);}
 else{const world=s.world;world.permanentProfile.importJSON(next.world.permanentProfile.exportJSON());world.restoreRun(next.world.captureRun());s={...next,world,subjects:next.subjects.map(x=>({...x,entity:world.entities.get(x.entity.id)!}))};r.resetRun();await r.prepareCampaignAssets(world.captureRun().config.campaignMap!);}
 viewHeight=19;await settle();initial=structuredClone(s.world.captureRun());profile=s.world.permanentProfile.exportJSON();document.body.dataset.ready='true';status(group+' · '+theme);return report();
}
async function reset(){s.world.permanentProfile.importJSON(profile);s.world.restoreRun(structuredClone(initial));s.subjects=s.subjects.map(x=>({...x,entity:s.world.entities.get(x.entity.id)!}));r.resetRun();await settle();return report();}
async function ticks(count:number){s.world.paused=false;for(let i=0;i<count;i++){s.world.step();r.render(1/60,1);if(i%12===11)await frame();}s.world.paused=true;await settle();return report();}
async function hit(index:number,amount:number){const u=s.subjects[index]?.entity;if(!u)throw Error('Missing subject');s.world.hit(u,amount,[],1,u.owner==='terran'?'zerg':'terran');return draw();}
async function reload(){const run=s.world.captureRun(),before=state();s.world.restoreRun(structuredClone(run));s.subjects=s.subjects.map(x=>({...x,entity:s.world.entities.get(x.entity.id)!}));r.resetRun();await settle();if(before!==state())throw Error('Current save changed after restore');return report();}
async function move(){for(const {entity:u} of s.subjects)u.stoppedUntil=u.nextShotAt=u.specialReady=0;s.world.paused=false;if(!s.world.issueMove({x:0,z:9}))throw Error('Native move order refused');s.world.paused=true;return ticks(30);}
async function attack(){const before=s.subjects.map(x=>x.entity.shotSequence??0);for(const {entity:u} of s.subjects){u.stoppedUntil=u.nextShotAt=u.specialReady=0;const p=s.world.freePosition('roach',{x:u.x,z:u.z-3},0,4);if(!p)throw Error('No native target position');const t=s.world.addUnit('roach','zerg',p.x,p.z);t.hp=t.maxHp=1e6;t.stoppedUntil=t.nextShotAt=t.specialReady=1e9;}s.world.hash.rebuild(s.world.entities.values());for(let i=0;i<180;i++){await ticks(1);if(s.subjects.every((x,n)=>(x.entity.shotSequence??0)>before[n]))return report();}throw Error('Native attacks did not fire');}
async function reorder(){const before=state();s.world.entities=new Map([...s.world.entities].reverse());draw();return {before,after:state(),report:report()};}
async function view(height:number,index?:number){viewHeight=height;if(index!==undefined){const u=s.subjects[index].entity;s.world.anchor.x=u.x;s.world.anchor.z=u.z;(r as any).cameraTarget.set(u.x,r.ground(u),u.z);}else{s.world.anchor.x=s.world.anchor.z=0;(r as any).cameraTarget.set(0,r.ground({x:0,z:0}),0);}return draw();}
async function hero(id:HeroId,alive:boolean){if(alive){if(!s.world.acquireHero(id))throw Error('Hero unavailable');const u=s.world.heroEntity(id)!;let p:{x:number;z:number}|null=null;const edge=s.world.mapHalf-4;for(let z=-edge;z<=edge&&!p;z+=3)for(let x=-edge;x<=edge&&!p;x+=3){const q=s.world.freePosition(u.unitType,{x,z},0,.1);if(q&&!(r as any).visible(q)&&s.world.terrain!.canOccupy(q,u.unitRadius))p=q;}if(!p)throw Error('No legal off-camera hero position');u.x=p.x;u.z=p.z;u.prev={...p};u.stoppedUntil=u.nextShotAt=u.specialReady=1e9;await settle();}else{const u=s.world.heroEntity(id);if(!u)throw Error('Hero missing');s.world.hit(u,1e8,[],1,'zerg');if(u.hp>0)throw Error('Native hero death did not occur');draw();}return report();}
function deathStatus(){return s.subjects.map(({entity:u})=>{const key=u.modelKey??u.unitType,b=r.gpu.get(key+'.death')??r.gpu.get(key),duration=b?.pose('dead')?.duration??1.5;return {id:u.id,key,clip:b?.actions.dead?.name,duration,life:Math.min(5,Math.max(1.5,duration)),count:b?.count,retained:(r as any).corpses.has(u.id)};});}
function textureFiltering(){const before=state(),rows:unknown[]=[];for(const quality of ['native','balanced','performance'] as const){r.setQuality(quality);const expected=Math.min(r.renderer.capabilities.getMaxAnisotropy(),quality==='native'?8:quality==='balanced'?4:1);for(const [key,b]of r.gpu)for(const surface of b.materialSurfaces??[])for(const [role,texture]of Object.entries(surface.prepared.textures)){if(texture.anisotropy!==expected)throw Error('Source sampler missed existing quality: '+key+'/'+role+'/'+quality);rows.push({key,role,quality,actual:texture.anisotropy,expected});}}draw();if(state()!==before)throw Error('Texture filtering changed simulation');return rows;}
function pipeline(){const composer=(r as any).heroComposer;return {toneMapping:r.renderer.toneMapping,exposure:r.renderer.toneMappingExposure,output:r.renderer.outputColorSpace,targetType:composer.renderTarget1.texture.type,targetColorSpace:composer.renderTarget1.texture.colorSpace,passes:composer.passes.map((p:any)=>({type:p.constructor.name,enabled:p.enabled,strength:p.strength,radius:p.radius,threshold:p.threshold,defines:p.material?.defines}))};}
async function pixels(){draw();const gl=r.renderer.getContext(),x=Math.floor(canvas.width*.25),y=Math.floor(canvas.height*.38),width=40,height=40,data=new Uint8Array(width*height*4);gl.readPixels(x,y,width,height,gl.RGBA,gl.UNSIGNED_BYTE,data);return {region:{x,y,width,height},checksum:checksum(Array.from(data).join(',')),rgb:Array.from(data.slice(0,12)),pipeline:pipeline(),state:state()};}
async function cost(seconds=5){await settle();const before=state(),frames:number[]=[],submits:number[]=[],drawCalls:number[]=[],triangles:number[]=[],visibility:string[]=[],focused:boolean[]=[],start=performance.now();let previous=start;r.renderer.info.autoReset=false;while(performance.now()-start<seconds*1000){await frame();const now=performance.now();frames.push(now-previous);previous=now;r.renderer.info.reset();const at=performance.now();r.render(0,1);submits.push(performance.now()-at);drawCalls.push(r.renderer.info.render.calls);triangles.push(r.renderer.info.render.triangles);visibility.push(document.visibilityState);focused.push(document.hasFocus());}const gl=r.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {seconds:(performance.now()-start)/1000,frames,submits,drawCalls,triangles,visibility:[...new Set(visibility)],focused:[...new Set(focused)],unchanged:before===state(),gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,browser:navigator.userAgent,report:report(),method:'Short paused rendering cost record, not stable-FPS or natural performance acceptance'};}
addEventListener('error',e=>errors.push(e.message));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));addEventListener('resize',()=>{if(r)draw();});
(window as any).materialLab={load,reset,ticks,hit,reload,move,attack,reorder,view,hero,cost,draw,report,pixels,pipeline,deathStatus,textureFiltering};
try{build=await(await fetch('./build.json')).json();const manifest=await(await fetch('./asset-manifest.json')).json();configurePlatformAssetUrl(id=>manifest.assets[id]?.url?'/'+manifest.assets[id].url:null);await load();}catch(e){errors.push(String(e));status('失败 '+e);document.body.dataset.ready='true';report();}
