import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {groups} from '../visual-plan-validation-20261009/catalog.ts';
const root='reports/local/material-batch2-20261010';
const data=JSON.parse(await fs.readFile(root+'/identity-repairs.json','utf8'));
const rows=data.identities.map(identity=>({...identity,group:groups.find(g=>g.identities.some(i=>i.id===identity.id)).id}));
const pairs=[];
for(const row of rows){pairs.push([row.evidence.beforeNear,row.evidence.afterNear]);for(const theme of ['industrial','mar-sara','char','ice','frontier'])pairs.push([row.evidence.beforeMaps+'/'+row.group+'-'+theme+'-far.png',row.evidence.afterMaps+'/'+row.group+'-'+theme+'-far.png']);for(const layout of ['landscape','portrait','small'])pairs.push([row.evidence.beforeMobile+'/'+row.group+'-'+layout+'.png',row.evidence.afterMobile+'/'+row.group+'-'+layout+'.png']);}
for(const file of new Set(pairs.flat()))assert.ok((await fs.stat(root+'/'+file)).isFile(),file);
const body=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>全单位材质 · 前后对照</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#111820;color:#e0e8ee}body{margin:0;padding:24px}h1{font-size:24px;margin:0 0 8px}p{color:#a9b8c3;line-height:1.6}nav{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:20px 0}select,button{background:#1f2e3a;color:inherit;border:1px solid #60717c;border-radius:5px;padding:10px;font:inherit;max-width:100%}button{cursor:pointer}main{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0;min-width:0;background:#080d12;border:1px solid #34434e}figcaption{padding:12px}img{width:100%;display:block}#detail{font-size:14px;line-height:1.7;max-width:1100px;overflow-wrap:anywhere}a{color:#9ccffd}@media(max-width:750px){body{padding:14px}main{grid-template-columns:1fr}}
</style><h1>全单位材质 · 前后对照</h1><p>30 普通 · 90 精英 · 18 英雄。相同原生场景、输入与存档；近景分别按完整身体构图。<a href="sequence-gallery.html">查看连续动作对照</a>。画面来自诊断采样，未作为自然战役、原作客户端或真机验收。</p>
<nav><button id="previous" aria-label="上一个身份">←</button><select id="identity" aria-label="单位身份"></select><button id="next" aria-label="下一个身份">→</button><select id="view" aria-label="场景"><option value="near">完整身体近景</option><option value="industrial">工业区 · 战场</option><option value="mar-sara">玛萨拉 · 战场</option><option value="char">查尔 · 战场</option><option value="ice">冰原 · 战场</option><option value="frontier">边境 · 战场</option><option value="landscape">横屏 844×390</option><option value="portrait">竖屏 390×844</option><option value="small">小屏 320×568</option></select><span id="count"></span></nav>
<main><figure><figcaption>修复前 · b56201c</figcaption><a id="beforeLink"><img id="before" alt="修复前原始截图"></a></figure><figure><figcaption>修复后 · 第二批（近景 R9／战场 R7；带出生动作的组为 R11 完成动作后补拍）</figcaption><a id="afterLink"><img id="after" alt="修复后原始截图"></a></figure></main><p id="detail"></p>
<script type="application/json" id="data">${JSON.stringify(rows).replaceAll('<','\\u003c')}</script><script>
const rows=JSON.parse(document.querySelector('#data').textContent),select=document.querySelector('#identity'),view=document.querySelector('#view');
rows.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.name+' · '+r.id;select.append(o)});
function show(){const r=rows[Number(select.value)],v=view.value,mobile=['landscape','portrait','small'].includes(v);const paths=v==='near'?[r.evidence.beforeNear,r.evidence.afterNear]:mobile?[r.evidence.beforeMobile+'/'+r.group+'-'+v+'.png',r.evidence.afterMobile+'/'+r.group+'-'+v+'.png']:[r.evidence.beforeMaps+'/'+r.group+'-'+v+'-far.png',r.evidence.afterMaps+'/'+r.group+'-'+v+'-far.png'];['before','after'].forEach((id,i)=>{document.querySelector('#'+id).src=paths[i];document.querySelector('#'+id+'Link').href=paths[i]});document.querySelector('#count').textContent=(Number(select.value)+1)+' / '+rows.length;document.querySelector('#detail').textContent='模型：'+r.model+'；源材质表面：'+r.materialCount+'。'+(r.elite?'精英显示倍率：地面 '+r.elite.groundScale+' / 飞行 1.15。真实机制：'+r.mechanism:'保留原显示尺寸。')+' '+(r.fixed.length?r.fixed.join('；')+'。':'')+(r.sourceGaps.length?'来源缺口：'+r.sourceGaps.join('；')+'。':'')+'仍需人工判断战场辨识度、自然运动细节与原作参考的一致性。';location.hash=r.id;}
select.onchange=view.onchange=show;for(const [id,delta]of [['previous',-1],['next',1]])document.querySelector('#'+id).onclick=()=>{select.value=(Number(select.value)+delta+rows.length)%rows.length;show()};const initial=rows.findIndex(r=>r.id===decodeURIComponent(location.hash.slice(1)));if(initial>=0)select.value=initial;show();
</script></html>`;
await fs.writeFile(root+'/comparison-gallery.html',body);
console.log(JSON.stringify({identities:rows.length,uniqueImages:new Set(pairs.flat()).size,path:root+'/comparison-gallery.html'}));
