import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {labServer} from './server.mjs';
const arg=(name,fallback)=>{const i=process.argv.indexOf(name);return i<0?fallback:process.argv[i+1];};
const root='reports/local/material-batch2-20261010',build=arg('--build','baseline-r2'),label=arg('--label','before-matrix-r1'),suite=arg('--suite','maps'),selection=arg('--groups','all');
const settleTicks=Number(arg('--settle-ticks','0'));assert.ok(Number.isInteger(settleTicks)&&settleTicks>=0&&settleTicks<=600);
assert.match(label,/^[a-z0-9-]+$/);assert.match(build,/^[a-z0-9-]+$/);
const out=root+'/'+label;await fs.mkdir(out,{recursive:true});
try{await fs.access(out+'/results.json');throw Error('Evidence exists; choose a new label');}catch(e){if(e.code!=='ENOENT')throw e;}
const server=labServer(root+'/'+build);await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const result={build:JSON.parse(await fs.readFile(root+'/'+build+'/build.json','utf8')),label,suite,settleTicks,method:'Native World diagnostic; paused snapshots and native ticks. Per-group isolated browser contexts. Not natural performance or physical-device acceptance.',startedAt:new Date().toISOString(),records:[],errors:[]};
await fs.copyFile(new URL(import.meta.url),out+'/runner.mjs');
const save=()=>fs.writeFile(out+'/results.json',JSON.stringify(result,null,2));
let page,context;
const call=(method,...args)=>page.evaluate(async({method,args})=>window.materialLab[method](...args),{method,args});
async function open(){context=await browser.newContext({viewport:{width:1280,height:756},deviceScaleFactor:1});page=await context.newPage();page.setDefaultTimeout(300000);page.on('pageerror',e=>result.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});await page.goto('http://127.0.0.1:'+server.address().port,{timeout:300000});await page.waitForFunction(()=>document.body.dataset.ready==='true',null,{timeout:300000});}
async function capture(name){const q=await call('draw');assert.deepEqual(q.errors,[]);assert.deepEqual(result.errors,[]);assert.equal(q.runtime.assetsPending,0);await page.screenshot({path:out+'/'+name+'.png'});result.records.push({name,group:q.group,theme:q.theme,state:q.state,time:q.time,tick:q.tick,subjects:q.subjects,runtime:q.runtime,surfaces:q.surfaces.filter(s=>s.count>0),errors:q.errors});await save();}
try{
 await open();const catalog=await call('catalog');await context.close();
 const groups=(suite==='fleet'?['mixed-fleet']:suite==='forms'?catalog.modes:suite==='actors'?catalog.actors:suite==='enemies'?catalog.enemies:catalog.groups.map(g=>g.id)).filter(id=>selection==='all'||selection.split(',').includes(id));
 for(const group of groups){await open();
  if(suite==='maps'||suite==='settled')for(const theme of catalog.themes){await call('load',group,theme);if(settleTicks)await call('ticks',settleTicks);await capture(group+'-'+theme+'-far');}
  if(suite==='portraits'||suite==='settled'){const q=await call('load',group);if(settleTicks)await call('ticks',settleTicks);for(let i=0;i<q.subjects.length;i++){const focused=await call('focus',i);await capture(q.subjects[i].identity+'-near');result.records.at(-1).portraitBounds=focused.portraitBounds;await save();}}
  if(suite==='actions'){let q=await call('load',group);await capture(group+'-idle');await call('move');await capture(group+'-move');await call('load',group);await call('combat');await capture(group+'-combat-1');if(group.startsWith('heroes-')){result.records.push({name:group+'-native-casts',...(await call('cast'))});await capture(group+'-skill-02');}await call('ticks',300);await capture(group+'-combat-6');q=await call('load',group);for(let i=0;i<q.subjects.length;i++)await call('hit',i,1e8);await capture(group+'-death-0');let previous=0;for(const tick of [12,30,90,330]){await call('ticks',tick-previous);previous=tick;await capture(group+'-death-'+tick);}await call('reload');await capture(group+'-death-reloaded');}
  if(suite==='mobile'||suite==='settled')for(const [name,width,height]of [['landscape',844,390],['portrait',390,844],['small',320,568]]){await page.setViewportSize({width,height});await call('load',group);if(settleTicks)await call('ticks',settleTicks);await capture(group+'-'+name);}
  if(suite==='forms'){await call('load',group);await capture(group+'-before');result.records.push({name:group+'-native-mode',...(await call('mode'))});await capture(group+'-after');await call('combat');await capture(group+'-attack');await call('reload');await capture(group+'-reload');let q=await call('draw');for(let i=0;i<q.subjects.length;i++)if(q.subjects[i].hp>0)await call('hit',i,1e8);await capture(group+'-death-0');for(const [label,ticks]of [['death-03',18],['death-15',72],['death-55',240]]){await call('ticks',ticks);await capture(group+'-'+label);}}
  if(suite==='invariants'){await call('load',group);const models=await call('models');if(!build.startsWith('baseline'))for(const m of models)if(m.elite&&!m.hero){assert.equal(m.displayScale,m.flying?1.15:['thor','ultralisk','colossus','carrier'].includes(m.unitType)?1.12:1.25);assert.ok(Math.abs(m.bodyHeight-m.ordinaryHeight)<1e-5,m.identity+' compounds original skin size');}await call('combat');const q=await call('draw'),materials=await call('materialState');for(let i=0;i<5;i++)await call('draw');assert.equal((await call('draw')).state,q.state);assert.deepEqual(await call('materialState'),materials);await call('reload');await capture(group+'-reload');await call('reorder');await capture(group+'-reorder');await call('load',group);for(let i=0;i<(await call('draw')).subjects.length;i++)await call('hit',i,1);await capture(group+'-hit');await call('ticks',18);await capture(group+'-hit-ended');result.records.push({name:group+'-independent-material-clock',models,pauseUnchanged:true});}
  if(suite==='fleet'){await call('load',group);const models=await call('models');await capture(group+'-idle');await call('combat');await capture(group+'-combat');result.records.push({name:group+'-native-cast',...(await call('cast'))});await capture(group+'-cast');for(const ticks of [72,108,300]){await call('ticks',ticks);await capture(group+'-later-'+ticks);}await call('reload');await capture(group+'-reload');await call('reorder');await capture(group+'-reorder');const q=await call('draw');for(let i=0;i<q.subjects.length;i++)await call('hit',i,1e8);await capture(group+'-death');await call('ticks',330);await capture(group+'-reclaimed');result.records.push({name:group+'-models',models});}
  if(suite==='actors'||suite==='enemies'){let q=await call('load',group);await capture(group+'-idle');await call('combat');await capture(group+'-active');if(suite==='actors'){await call('actorLifecycle','open');await call('ticks',60);await capture(group+'-opened');}await call('reload');await capture(group+'-reload');q=await call('draw');for(let i=0;i<q.subjects.length;i++)if(q.subjects[i].hp>0)await call('hit',i,1e8);if(suite==='actors')await call('actorLifecycle','destroy');await capture(group+'-death-0');for(const [name,ticks]of [['death-03',18],['death-15',72],['death-55',240]]){await call('ticks',ticks);await capture(group+'-'+name);}}
  await context.close();console.log(JSON.stringify({group,suite,captures:result.records.length}));
 }
 result.passed=result.errors.length===0;
}catch(error){result.passed=false;result.failure=String(error.stack??error);console.error(result.failure);await page?.screenshot({path:out+'/failure.png'}).catch(()=>{});process.exitCode=1;}
finally{result.finishedAt=new Date().toISOString();await save();await browser.close();await new Promise(r=>server.close(r));}
