import * as THREE from 'three';
import {World} from '../../src/simulation/world';import {BattleRenderer} from '../../src/render/scene/battle-renderer';import {FixedStepper} from '../../src/simulation/fixed-stepper';
import {ELITES} from '../../src/data/elites';import {PROTOSS_ELITE_IDS,PROTOSS_ELITE_RULES,type ProtossEliteId} from '../../src/data/protoss-elites';
import {ASSETS,assetUrl} from '../../src/assets/manifest';import {loadEmbeddedAssets,prepareEmbeddedAssetIds} from '../../src/assets/offline-pack';
import {RUN_SCHEMA,type RunSnapshot} from '../../src/simulation/persistence/run-snapshot';import type {FamilyId} from '../../src/data/races';
import {initializeCarrierSubsystem,ownedInterceptors} from '../../src/simulation/combat/carriers';
const $=(id:string)=>document.getElementById(id)!;const selected=new Set<string>(JSON.parse($('demo-assets').textContent!));for(const id of ASSETS.keys())if(!selected.has(id))ASSETS.delete(id);
const w=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10577}),canvas=$('battle')as HTMLCanvasElement,view=new BattleRenderer(canvas,w);view.cameraShake=false;
let id:ProtossEliteId='zealot.1',rank=1,scenario='group',ready=false,last=performance.now(),saved:RunSnapshot|null=null,source=0,zoom=1.4;let initial=new Map<number,number>();const walls=new THREE.Group();view.scene.add(walls);
const families=[...new Set(PROTOSS_ELITE_IDS.map(id=>ELITES[id].family))],family=()=>ELITES[id].family;
function resize(){view.resize();view.camera.zoom=canvas.clientWidth<canvas.clientHeight?.92:zoom;view.camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function foe(x:number,z:number,air=false){const e=w.addUnit(air?'mutalisk':'marine','zerg',x,z,1,'regular',13);e.hp=e.maxHp=1e6;e.armor=0;e.nextShotAt=e.specialReady=1e9;e.moveSpeed=0;e.stoppedUntil=0;e.attributes=scenario==='light'?['Light','Biological']:['Armored','Biological'];if(scenario==='boss')e.enemyTier='boss';e.energy=50;initial.set(e.id,e.hp);return e;}
function setup(){view.resetRun();w.resetRun();w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.stage=13;w.obstacles=[];w.anchor.x=-4;initial=new Map();w.wallet.minerals=0;for(const c of Object.values(w.expedition.production))c.enabled={};for(const m of [...walls.children]){m.removeFromParent();(m as THREE.Mesh).geometry.dispose();((m as THREE.Mesh).material as THREE.Material).dispose();}
 const f=family();w.expedition.familySlots=['stalker','sentry','carrier',f].filter((x,i,a)=>a.indexOf(x)===i)as FamilyId[];w.expedition.tech['unlock.'+f]=1;w.expedition.tech.storm=1;w.expedition.tech.charge=1;w.expedition.tech.blink=1;
 const u=w.addUnit(f,'terran',-4,0,rank);u.eliteId=id;u.modelKey=ELITES[id].model;w.refreshStats(u,true);u.energy=u.maxEnergy;source=u.id;initializeCarrierSubsystem(w);
 const air=scenario==='air'||f==='phoenix'&&id!=='phoenix.2'&&scenario!=='ground',line=scenario==='line',melee=f==='zealot',n=scenario==='single'?1:6;for(let i=0;i<n;i++)foe(line?2+i*2.1:melee?-.5+(i%3)*1.5:3+(i%3)*2,line?0:-2+Math.floor(i/3)*3,air);
 if(id==='sentry.1'||id==='high_templar.3'||scenario==='wounds'||scenario==='empty'){for(let i=0;i<7;i++){const b=w.addUnit(id==='high_templar.3'?'sentry':'stalker','terran',-1+(i%3)*1.3,-3+Math.floor(i/3)*2.5,5);b.shield=0;b.energy=0;b.nextShotAt=b.stoppedUntil=1e9;initial.set(b.id,b.hp);}if(scenario==='empty')u.energy=u.energyRegen=0;}
 if(id==='phoenix.3'){u.nextShotAt=8;for(let i=0;i<5;i++){const b=w.addUnit('stalker','terran',-3+i,3,5);b.stoppedUntil=b.nextShotAt=1e9;}}
 if(id==='zealot.2'||id==='sentry.3'||id==='immortal.2'||scenario==='lowshield'){const e=[...w.entities.values()].find(e=>e.owner==='zerg')!;w.hit(u,(u.shield??0)+200,[],1,'zerg',0,1,e.id);}if(id==='void_ray.3')u.shield=u.maxShield!*.2;
 if(scenario==='wall'){w.obstacles=[{x:0,z:0,w:.7,h:7}];const m=new THREE.Mesh(new THREE.BoxGeometry(.7,.75,7),new THREE.MeshStandardMaterial({color:0x717981,metalness:.6,roughness:.6}));m.position.set(0,.375,0);walls.add(m);}
 w.hash.rebuild(w.entities.values());w.paused=false;stepper.reset();$('pause').textContent='暂停';$('name').textContent=PROTOSS_ELITE_RULES[id].name;$('result').textContent='';$('description').textContent=ELITES[id].description;$('strike').hidden=false;$('mode').hidden=f!=='stalker';$('mode').textContent='向前闪现';for(const b of document.querySelectorAll<HTMLButtonElement>('[data-elite]'))b.setAttribute('aria-pressed',String(b.dataset.elite===id));resize();w.changed();
}
function chooseFamily(f:FamilyId){id=PROTOSS_ELITE_IDS.find(id=>ELITES[id].family===f)!;($('family')as HTMLSelectElement).value=f;$('variants').innerHTML=PROTOSS_ELITE_IDS.filter(id=>ELITES[id].family===f).map(id=>`<button data-elite="${id}" aria-pressed="false">${PROTOSS_ELITE_RULES[id].name}</button>`).join('');for(const b of document.querySelectorAll<HTMLButtonElement>('[data-elite]'))b.onclick=()=>{id=b.dataset.elite as ProtossEliteId;setup();};$('scenario').innerHTML=[['group','群体'],['single','单目标'],['line','沿线目标'],['light','轻甲'],['ground','地面'],['air','空中'],['boss','Boss条件'],['wounds','护盾伤员'],['empty','能量耗尽'],['lowshield','护盾破裂'],['wall','阻挡对照']].map(([v,t])=>`<option value="${v}">${t}</option>`).join('');scenario='group';setup();}
function step(){if(w.paused)return false;w.stageElapsed=0;w.step();return true;}const stepper=new FixedStepper(1/60,step,()=>performance.now(),8);function advance(seconds:number){for(let i=0;i<Math.ceil(Math.min(45,seconds)*60);i++)if(!step())break;}
function hurt(friendly=false){const caster=w.entities.get(source);if(!caster)return;const enemy=[...w.entities.values()].find(e=>e.owner==='zerg');for(const u of friendly?w.allies().filter(u=>u.id!==source):[caster])w.hit(u,(u.shield??0)+(u.barrier??0)+Math.min(u.hp*.1,300),[],1,'zerg',0,1,enemy?.id);}
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;const alpha=ready&&!w.paused?stepper.advance(dt):0;view.render(dt,alpha);if(!ready)return;const u=w.entities.get(source),s=u?.protossEliteCombat;$('time').textContent=w.time.toFixed(1)+'s';$('energy').textContent=Math.ceil(u?.energy??0)+' / '+Math.ceil(u?.maxEnergy??0);$('healed').textContent=Math.round(w.stats.healed).toString();$('damage').textContent=Math.round(w.stats.damage).toString();$('state').textContent=u?.unitType==='carrier'?`出勤子机 ${ownedInterceptors(w,u.id).length} · 在途 ${w.weaponFlights.length}`:`攻击周期 ${s?.cycles??0} · 在途 ${w.weaponFlights.length} · 护盾 ${Math.ceil(u?.shield??0)}`;}
const labels=['狂热者','使徒','追猎者','哨兵','不朽者','巨像','高阶圣堂武士','凤凰','虚空辉光舰','航母'];$('family').innerHTML=families.map((f,i)=>`<option value="${f}">${labels[i]}</option>`).join('');
($('family')as HTMLSelectElement).onchange=()=>chooseFamily(($('family')as HTMLSelectElement).value as FamilyId);($('rank')as HTMLSelectElement).onchange=()=>{rank=+($('rank')as HTMLSelectElement).value;setup();};($('scenario')as HTMLSelectElement).onchange=()=>{scenario=($('scenario')as HTMLSelectElement).value;setup();};($('quality')as HTMLSelectElement).onchange=()=>{view.fx.heroQuality=($('quality')as HTMLSelectElement).value as any;};
$('restart').onclick=setup;$('pause').onclick=()=>{w.paused=!w.paused;stepper.reset();$('pause').textContent=w.paused?'继续':'暂停';};$('skip').onclick=()=>advance(8);$('zoom').onclick=()=>{zoom=zoom===1.4?1:1.4;resize();};$('mode').onclick=()=>{const u=w.entities.get(source);if(u&&!w.paused)w.castFamilyAbility('stalker',{x:u.x+3,z:u.z});};$('hurt').onclick=()=>hurt();$('strike').onclick=()=>hurt(true);$('save').onclick=()=>{saved=structuredClone(w.captureRun());$('result').textContent='已保存';};$('restore').onclick=()=>{if(!saved)return;view.resetRun();w.restoreRun(saved);stepper.reset();$('pause').textContent='继续';$('result').textContent='已恢复 · 暂停';};
addEventListener('blur',()=>{if(ready){w.paused=true;stepper.reset();$('pause').textContent='继续';}});
(window as any).__PROTOSS_ELITE_REPORT__=()=>({ready,id,rank,scenario,time:w.time,paused:w.paused,schema:RUN_SCHEMA,source:w.entities.get(source),allies:w.allies(),children:ownedInterceptors(w,source),state:structuredClone(w.protossElites),auras:structuredClone(w.teamAuras),flights:structuredClone(w.weaponFlights),healed:w.stats.healed,damage:w.stats.damage,shots:w.stats.shots,render:view.report(),targets:[...initial].map(([id,before])=>{const t=w.entities.get(id);return {id,before,hp:t?.hp,maxHp:t?.maxHp,shield:t?.shield,energy:t?.energy,air:t?.flying,team:t?.team};})});
(window as any).__PROTOSS_ELITE_ADVANCE__=(seconds:number)=>{advance(seconds);view.render(0,0);};
async function load(){await loadEmbeddedAssets();await prepareEmbeddedAssetIds(selected,(d,t)=>$('interface').textContent=`准备战场 ${d}/${t}`);await view.fx.load();await view.nonHeroEffects.load();await view.protossEliteEffects.load();await view.zergEliteEffects.load();await view.p4Effects.loadMedicalTextures();await view.terranEliteEffects.load();for(const f of [...families,'marine','mutalisk']as FamilyId[])if(!await view.ensureUnitVariant(f,f))throw Error(view.modelErrors.join(';'));if(!await view.ensureUnitVariant('interceptor','carrier'))throw Error(view.modelErrors.join(';'));for(const id of PROTOSS_ELITE_IDS)if(!await view.ensureUnitVariant(ELITES[id].model,ELITES[id].family))throw Error(view.modelErrors.join(';'));const tex=await new THREE.TextureLoader().loadAsync(assetUrl('map.terrain.diffuse')!);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(.18,.18);const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({map:tex,color:0x92989f,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;view.scene.add(floor);chooseFamily('zealot');await view.warmPresentationBatches();ready=true;$('interface').hidden=true;($('family')as HTMLSelectElement).disabled=false;last=performance.now();}
requestAnimationFrame(frame);load().catch(e=>{$('interface').textContent='载入失败：'+e.message;console.error(e);});
