/** Original local imports when present; otherwise explicitly labeled local synthesis. */
import {assetUrl,ASSETS} from '../../assets/manifest';
import type {World} from '../../simulation/world';
export class AudioEffects {
 context:AudioContext|null=null;buffers=new Map<string,AudioBuffer>();lastSerial=0;lastRescue=0;lastFailure=0;voices=0;loading:Promise<void>|null=null;decodeErrors:string[]=[];played=new Map<string,number>();healers=new Map<number,AudioBufferSourceNode>();private healerLastActive=new Map<number,number>();
 async start(){try{this.context??=new AudioContext();await this.context.resume();this.loading??=this.load();await this.loading;}catch(e){this.decodeErrors.push(String(e));}}
 private async load(){for(const a of ASSETS.values()){if(a.kind!=='audio'||a.status!=='available'||this.buffers.has(a.id.replace('audio.','')))continue;const url=assetUrl(a.id);if(!url)continue;
  try{const response=await fetch(url);if(!response.ok)throw Error(String(response.status));const bytes=await response.arrayBuffer();this.buffers.set(a.id.replace('audio.',''),await this.context!.decodeAudioData(bytes));}catch(e){this.decodeErrors.push(a.id+': '+String(e));}
 }}
 report(){return {originalDecoded:[...this.buffers.keys()].filter(id=>id.startsWith('sc2.')).length,decoded:[...this.buffers].map(([id,b])=>({id,duration:b.duration,channels:b.numberOfChannels,sampleRate:b.sampleRate})),errors:this.decodeErrors,played:Object.fromEntries(this.played),activeHealers:this.healers.size};}
 play(id:string,volume:number){const b=this.buffers.get(id);if(!b||!this.context||this.voices>=12&&id!=='sc2.scv.ready')return;const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=b;gain.gain.value=volume;source.connect(gain).connect(this.context.destination);this.voices++;source.onended=()=>{this.voices--;source.disconnect();gain.disconnect();};source.start();this.played.set(id,(this.played.get(id)??0)+1);}
 update(w:World){let played=0;for(const e of w.visualEvents){if(e.serial<=this.lastSerial)continue;this.lastSerial=e.serial;if(e.kind==='scv-rescue'&&w.time-e.time<.5){this.play('sc2.scv.ready',.22);continue;}if(w.time-e.time>.2||Math.hypot(e.x-w.anchor.x,e.z-w.anchor.z)>24||played>=3)continue;
  if(e.kind==='attack'){const id=`sc2.${e.unitType}.${e.siege?'siege':'attack'}`;const fallback=e.unitType==='marine'?'shot':['tank','baneling','hellion'].includes(e.unitType??'')?'blast':null;const sound=this.buffers.has(id)?id:fallback;if(sound){this.play(sound,.045);played++;}}
  else if(e.kind==='death'){const id=`sc2.${e.unitType}.death`;if(this.buffers.has(id)){this.play(id,.06);played++;}}
 }const healing=this.buffers.get('sc2.medivac.heal');if(healing&&this.context){const ids=new Set<number>();if(w.phase==='battle'&&!w.paused)for(const u of w.entities.values()){if(u.hp<=0||!u.healTarget||Math.hypot(u.x-w.anchor.x,u.z-w.anchor.z)>24)continue;ids.add(u.id);this.healerLastActive.set(u.id,w.time);if(!this.healers.has(u.id)){const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=healing;source.loop=true;gain.gain.value=.035;source.connect(gain).connect(this.context.destination);source.onended=()=>{source.disconnect();gain.disconnect();};source.start();this.healers.set(u.id,source);this.played.set('sc2.medivac.heal',(this.played.get('sc2.medivac.heal')??0)+1);}}for(const [id,source] of this.healers)if(!ids.has(id)&&(w.phase!=='battle'||w.paused||(w.entities.get(id)?.hp??0)<=0||w.time-(this.healerLastActive.get(id)??-1)>.15)){source.stop();this.healers.delete(id);this.healerLastActive.delete(id);}}
 if(w.stats.rescued!==this.lastRescue||w.stats.failed!==this.lastFailure){this.play('alert',.15);this.lastRescue=w.stats.rescued;this.lastFailure=w.stats.failed;}}
}
