/** Original local imports when present; otherwise explicitly labeled local synthesis. */
import {assetUrl,ASSETS} from '../../assets/manifest';
import type {World} from '../../simulation/world';
export class AudioEffects {
 masterVolume=1;battleVolume=1;interfaceVolume=0;
 private masterBus:GainNode|null=null;private battleBus:GainNode|null=null;private interfaceBus:GainNode|null=null;
 constructor(){try{const p=JSON.parse(localStorage.getItem('sc2.audio-mix')??'{}');this.setMix(p.master??1,p.battle??1,p.interface??0);}catch{}}
 setMix(master:number,battle:number,ui:number){if(![master,battle,ui].every(n=>Number.isFinite(n)&&n>=0&&n<=1))return;this.masterVolume=master;this.battleVolume=battle;this.interfaceVolume=ui;if(this.masterBus)this.masterBus.gain.value=master;if(this.battleBus)this.battleBus.gain.value=battle;if(this.interfaceBus)this.interfaceBus.gain.value=ui;try{localStorage.setItem('sc2.audio-mix',JSON.stringify({master,battle,interface:ui}));}catch{}}
 private output(channel:'battle'|'interface'='battle'){const c=this.context!;if(!this.masterBus){this.masterBus=c.createGain();this.masterBus.gain.value=this.masterVolume;this.masterBus.connect(c.destination);this.battleBus=c.createGain();this.battleBus.gain.value=this.battleVolume;this.battleBus.connect(this.masterBus);this.interfaceBus=c.createGain();this.interfaceBus.gain.value=this.interfaceVolume;this.interfaceBus.connect(this.masterBus);}return channel==='interface'?this.interfaceBus!:this.battleBus!;}
 /** Short interface feedback is independent of combat voices and World events. */
 interfaceCue(){if(this.interfaceVolume<=0||this.masterVolume<=0)return;try{this.context??=new AudioContext();void this.context.resume();const c=this.context,o=c.createOscillator(),g=c.createGain(),at=c.currentTime;o.type='sine';o.frequency.setValueAtTime(620,at);o.frequency.exponentialRampToValueAtTime(780,at+.045);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.035,at+.005);g.gain.exponentialRampToValueAtTime(.0001,at+.07);o.connect(g).connect(this.output('interface'));o.start(at);o.stop(at+.075);o.onended=()=>{o.disconnect();g.disconnect();};}catch{}}
 context:AudioContext|null=null;buffers=new Map<string,AudioBuffer>();lastSerial=0;lastRescue=0;lastFailure=0;voices=0;loading:Promise<void>|null=null;decodeErrors:string[]=[];played=new Map<string,number>();healers=new Map<number,AudioBufferSourceNode>();private healerLastActive=new Map<number,number>();
 private activeSources=new Set<AudioBufferSourceNode>();
 reset(){for(const s of this.activeSources)s.stop();for(const s of this.healers.values())s.stop();this.healers.clear();this.healerLastActive.clear();this.lastSerial=0;this.lastRescue=0;this.lastFailure=0;this.played.clear();}
 async preload(progress:(done:number,total:number,label:string)=>void=()=>{}){this.context??=new AudioContext();this.loading??=this.load(progress).catch(error=>{this.loading=null;throw error;});await this.loading;}
 async start(){try{await this.preload();await this.context!.resume();}catch(e){this.decodeErrors.push(String(e));}}
 private async load(progress:(done:number,total:number,label:string)=>void){const assets=[...ASSETS.values()].filter(a=>a.kind==='audio'&&a.status==='available'&&!this.buffers.has(a.id.replace('audio.','')));let done=0;for(const a of assets){const url=assetUrl(a.id);try{if(!url)throw Error('missing asset');const response=await fetch(url);if(!response.ok)throw Error(String(response.status));const bytes=await response.arrayBuffer();this.buffers.set(a.id.replace('audio.',''),await this.context!.decodeAudioData(bytes));}catch(e){this.decodeErrors.push(a.id+': '+String(e));if(a.required)throw Error('必需音效未就绪：'+a.id);}progress(++done,assets.length,a.id);}}
 report(){return {originalDecoded:[...this.buffers.keys()].filter(id=>id.startsWith('sc2.')).length,decoded:[...this.buffers].map(([id,b])=>({id,duration:b.duration,channels:b.numberOfChannels,sampleRate:b.sampleRate})),errors:this.decodeErrors,played:Object.fromEntries(this.played),activeHealers:this.healers.size};}
 play(id:string,volume:number){const b=this.buffers.get(id);if(!b||!this.context||this.voices>=12&&id!=='sc2.scv.ready')return;const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=b;gain.gain.value=volume;source.connect(gain).connect(this.output());this.voices++;this.activeSources.add(source);source.onended=()=>{this.activeSources.delete(source);this.voices--;source.disconnect();gain.disconnect();};source.start();this.played.set(id,(this.played.get(id)??0)+1);}
 update(w:World){let played=0;for(const e of w.visualEvents){if(e.serial<=this.lastSerial)continue;this.lastSerial=e.serial;if(e.kind==='scv-rescue'&&w.time-e.time<.5){if(w.expedition.race==='terran')this.play('sc2.scv.ready',.22);continue;}if(w.time-e.time>.2||Math.hypot(e.x-w.anchor.x,e.z-w.anchor.z)>24||played>=3)continue;
  if(e.kind==='attack'){const id=`sc2.${e.unitType}.${e.siege?'siege':'attack'}`;const fallback=e.unitType==='marine'?'shot':['tank','baneling','hellion'].includes(e.unitType??'')?'blast':null;const sound=this.buffers.has(id)?id:fallback;if(sound){this.play(sound,.045);played++;}}
  else if(e.kind==='skill-launch'){const id=`sc2.${e.unitType}.attack`;this.play(this.buffers.has(id)?id:['tychus','yamato_battlecruiser','hots_leviathan'].includes(e.heroId??'')?'blast':'shot',.08);played++;}
  else if(e.kind==='death'){const id=`sc2.${e.unitType}.death`;if(this.buffers.has(id)){this.play(id,.06);played++;}}
 }const healing=this.buffers.get('sc2.medivac.heal');if(healing&&this.context){const ids=new Set<number>();if(w.phase==='battle'&&!w.paused)for(const u of w.entities.values()){if(u.hp<=0||!u.healTarget||Math.hypot(u.x-w.anchor.x,u.z-w.anchor.z)>24)continue;ids.add(u.id);this.healerLastActive.set(u.id,w.time);if(!this.healers.has(u.id)){const source=this.context.createBufferSource(),gain=this.context.createGain();source.buffer=healing;source.loop=true;source.onended=()=>{source.disconnect();gain.disconnect();};gain.gain.value=.035;source.connect(gain).connect(this.output());source.onended=()=>{source.disconnect();gain.disconnect();};source.start();this.healers.set(u.id,source);this.played.set('sc2.medivac.heal',(this.played.get('sc2.medivac.heal')??0)+1);}}for(const [id,source] of this.healers)if(!ids.has(id)&&(w.phase!=='battle'||w.paused||(w.entities.get(id)?.hp??0)<=0||w.time-(this.healerLastActive.get(id)??-1)>.15)){source.stop();this.healers.delete(id);this.healerLastActive.delete(id);}}
 if(w.stats.rescued!==this.lastRescue||w.stats.failed!==this.lastFailure){this.play('alert',.15);this.lastRescue=w.stats.rescued;this.lastFailure=w.stats.failed;}}
}
