import * as THREE from 'three';
import {assetUrl} from '../../assets/manifest';
import type {World} from '../../simulation/world';
import {AIR_HEIGHT} from '../../data/terrain';
import type {BattleEffects} from './battle-effects';

/** Read-only presentation of the opt-in P4 samples. No rule timers or combat RNG. */
export class EliteSupportEffects {
 quality:'full'|'balanced'|'low'='full';
 private group=new THREE.Group();private beams:THREE.Mesh[]=[];private shields:THREE.Mesh[]=[];private emitted=new Set<number>();private phases=new Map<number,string>();private tick=-1;
 private beamMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{clock:{value:0},tint:{value:new THREE.Color(0x9af1ba)},sourceMap:{value:new THREE.Texture()}},vertexShader:'varying vec2 uvBeam; void main(){uvBeam=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'uniform sampler2D sourceMap;uniform float clock;uniform vec3 tint;varying vec2 uvBeam;void main(){float y=abs(uvBeam.y-.5)*2.;vec3 sampleColor=texture2D(sourceMap,vec2(uvBeam.y,fract(uvBeam.x*2.-clock*.45))).rgb;float fiber=max(sampleColor.r,max(sampleColor.g,sampleColor.b));float core=exp(-y*y*36.);float veil=exp(-y*y*3.)*.16;float ends=smoothstep(0.,.03,uvBeam.x)*smoothstep(0.,.03,1.-uvBeam.x);gl_FragColor=vec4(mix(tint,vec3(.92,1.,.94),core*.6),(fiber*.62+veil)*ends);}' });
 private shieldMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.FrontSide,blending:THREE.AdditiveBlending,uniforms:{clock:{value:0}},vertexShader:'varying vec3 p;varying vec3 n;varying vec3 eye;void main(){p=position;n=normalize(normalMatrix*normal);vec4 v=modelViewMatrix*vec4(position,1.);eye=normalize(-v.xyz);gl_Position=projectionMatrix*v;}',fragmentShader:'uniform float clock;varying vec3 p;varying vec3 n;varying vec3 eye;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(eye))),3.);vec2 q=vec2(atan(p.z,p.x)*7.,p.y*14.);q.x+=mod(floor(q.y),2.)*.5;vec2 c=abs(fract(q)-.5);float grid=pow(max(c.x,c.y)*2.,18.);float scan=pow(max(0.,sin(p.y*9.-clock*2.)),18.);float alpha=clamp(rim*.38+grid*.075+scan*.1,0.,.5);gl_FragColor=vec4(vec3(.18,.72,.82)+rim*vec3(.4,.55,.55),alpha);}' });
 private fogs:THREE.Mesh[]=[];private nodes:THREE.Sprite[]=[];private fogCount=0;
 private flareMaterial=new THREE.SpriteMaterial({color:0xc6ffe0,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});
 private healMaterial=new THREE.SpriteMaterial({color:0xe4fff0,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending});
 private fogMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{clock:{value:0}},vertexShader:'varying vec2 v;void main(){v=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`uniform float clock;varying vec2 v;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}float fbm(vec2 p){return noise(p)*.55+noise(p*2.1)*.28+noise(p*4.3)*.17;}void main(){vec2 p=(v-.5)*2.;float edge=pow(max(0.,1.-dot(p,p)),1.6);float cloud=fbm(v*5.+vec2(clock*.18,-clock*.12));float wisps=fbm(v*9.+vec2(-clock*.12,clock*.15));float a=edge*smoothstep(.24,.72,cloud)*(.25+wisps*.27);gl_FragColor=vec4(mix(vec3(.16,.60,.29),vec3(.60,1.,.70),cloud),a);}`});
 async loadMedicalTextures(){const loader=new THREE.TextureLoader();for(const [id,mat] of [['p4.texture.beam',this.beamMaterial],['p4.texture.flare',this.flareMaterial],['p4.texture.heal',this.healMaterial]] as const){const url=assetUrl(id);if(!url)continue;const tex=await loader.loadAsync(url);if(mat instanceof THREE.ShaderMaterial)mat.uniforms.sourceMap={value:tex};else mat.map=tex;mat.needsUpdate=true;}}
 private plane=new THREE.PlaneGeometry(1,1);private sphere=new THREE.SphereGeometry(1,32,20);
 constructor(scene:THREE.Scene,private fx:BattleEffects){scene.add(this.group);}
 reset(){this.emitted.clear();this.phases.clear();this.tick=-1;for(const m of [...this.beams,...this.shields,...this.fogs,...this.nodes])m.visible=false;}
 report(){return {beams:this.beams.filter(m=>m.visible).length,shields:this.shields.filter(m=>m.visible).length,fogTargets:this.fogCount,quality:this.quality};}
 render(w:World,camera:THREE.Camera,visible:(p:{x:number;z:number})=>boolean){
  this.group.visible=[...w.entities.values()].some(u=>u.owner==='terran'&&!!u.eliteId)||!!w.eliteSupport.mines.length||!!w.eliteSupport.fires.length;if(!this.group.visible)return;
  for(const b of [...this.beams,...this.shields,...this.fogs,...this.nodes])b.visible=false;this.beamMaterial.uniforms.clock.value=w.time;this.shieldMaterial.uniforms.clock.value=w.time;
  let links=0,shells=0,clouds=0,nodes=0;this.fogCount=0;this.fogMaterial.uniforms.clock.value=w.time;
 const sprite=(p:THREE.Vector3,size:number,medical=false)=>{let m=this.nodes[nodes++];if(!m){m=new THREE.Sprite(this.flareMaterial);this.group.add(m);this.nodes.push(m);}m.material=medical?this.healMaterial:this.flareMaterial;m.position.copy(p);m.scale.setScalar(size);m.visible=true;};
  for(const u of w.entities.values())if(u.hp>0&&visible(u)&&u.owner==='terran'&&!!u.eliteId&&['medivac','science_vessel'].includes(u.unitType)&&!u.heroId)for(const id of u.healTargets??[]){const target=w.entities.get(id);if(!target?.hp||!visible(target))continue;if(u.unitType==='science_vessel'){this.fogCount++;const height=target.flying?AIR_HEIGHT:.15;for(let i=0;i<3;i++){let fog=this.fogs[clouds++];if(!fog){fog=new THREE.Mesh(this.plane,this.fogMaterial);this.group.add(fog);this.fogs.push(fog);}fog.position.set(target.x+Math.sin(w.time*.4+i)*.12,height+.35+i*.35,target.z+Math.cos(w.time*.3+i)*.12);fog.quaternion.copy(camera.quaternion);fog.scale.set(2.6-i*.35,1.8-i*.15,1);fog.renderOrder=3;fog.visible=true;}for(let i=0;i<(this.quality==='low'?2:6);i++){const angle=i*2.399+w.time*.7,r=.25+(i%3)*.18;sprite(new THREE.Vector3(target.x+Math.sin(angle)*r,height+.25+((w.time*.35+i*.19)%1.2),target.z+Math.cos(angle)*r),.09);}continue;}
 let mesh=this.beams[links];if(!mesh){mesh=new THREE.Mesh(this.plane,this.beamMaterial);mesh.frustumCulled=false;this.group.add(mesh);this.beams.push(mesh);}links++;
   const from=new THREE.Vector3(u.x,u.flying?AIR_HEIGHT-.1:(w.terrain?.height(u)??0)+.8,u.z),to=new THREE.Vector3(target.x,target.flying?AIR_HEIGHT+.5:(w.terrain?.height(target)??0)+.7,target.z),along=to.clone().sub(from),mid=from.clone().add(to).multiplyScalar(.5),length=along.length();along.normalize();const eye=camera.position.clone().sub(mid).normalize(),across=new THREE.Vector3().crossVectors(eye,along).normalize(),normal=new THREE.Vector3().crossVectors(along,across).normalize();mesh.position.copy(mid);mesh.quaternion.setFromRotationMatrix(new THREE.Matrix4().makeBasis(along,across,normal));mesh.scale.set(length,.38,1);mesh.visible=true;sprite(from,.46);sprite(to,.6);for(let i=0;i<(this.quality==='low'?1:2);i++){const t=(w.time*.5+i*.5)%1;sprite(new THREE.Vector3(target.x+Math.sin(i*3+w.time)*.18,to.y+t*.9,target.z),.17*(1-t*.4),true);}
  }
  for(const b of [...w.eliteSupport.barriers,...[...w.entities.values()].filter(u=>u.eliteId==='viking.3'&&!!u.eliteCombat).map(u=>({target:u.id,amount:u.eliteCombat!.barrier,until:u.eliteCombat!.barrierUntil}))]){const u=w.entities.get(b.target);if(!u?.hp||b.until<=w.time||b.amount<=0||!visible(u))continue;let mesh=this.shields[shells];if(!mesh){mesh=new THREE.Mesh(this.sphere,this.shieldMaterial);this.group.add(mesh);this.shields.push(mesh);}shells++;mesh.visible=true;mesh.position.set(u.x,u.flying?AIR_HEIGHT+.5:(w.terrain?.height(u)??0)+.55,u.z);mesh.scale.set(Math.max(.7,u.unitRadius+ .35),.95,Math.max(.7,u.unitRadius+.35));}
  // Mine dust, blast and residual fire are rendered by TerranEliteEffects using feathered original textures.
 }
}
