import * as THREE from 'three';
import type {BattleRenderer} from '../scene/battle-renderer';
import type {World} from '../../simulation/world';
import type {Entity,HeroCast} from '../../simulation/types';
import type {Point3,AttackPacket} from '../../simulation/combat/hero-attack-upgrades';
import {HEROES} from '../../data/heroes';
import {isProtossHero,PROTOSS_HERO_IDS} from '../../data/protoss-heroes';
import {ProtossHeroMaterials} from './protoss-hero-materials';
import {PROTOSS_PRESENTATION as P,clamp01,mixPoint,fleetPhase,fleetFrame,fleetChildPoint,trailOpacity} from './protoss-hero-presentation';
import {ownedInterceptors} from '../../simulation/combat/carriers';
import {HeroAuraEffects} from './confirmed-hero/hero-aura-effects';
import {weaponWorldPoint} from './hero-feedback';
import {modelPresentationScale} from '../../data/combat-presentation';
import {commitInstances} from '../units/instance-updates';
const colors={artanis:0xffd685,zeratul:0x7be2b7,alarak:0xf14b68,fenix:0x90caff,vorazun:0xb4a0ec,purifier_flagship:0xffe3a1};
const object=new THREE.Object3D(),tint=new THREE.Color();
const mix=(a:Point3,b:Point3,t:number):Point3=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t});
type Echo={kind:string;hero:string;rank:number;at:number;life:number;from:Point3;to:Point3;source:number;castId?:number;facing?:number};
type Fleet={cast:HeroCast;source:Entity;children:Entity[]};
/** Layered source-texture psionic blades, solar cores, shield facets and temporal shells.
 * Read-only adapter over real packets, casts and saved state. No combat or gameplay RNG here. */
export class ProtossHeroEffects {
 ready=false;private material:ProtossHeroMaterials;private aura:HeroAuraEffects;private cores?:THREE.InstancedMesh;private shields?:THREE.InstancedMesh;private coreCount=0;private shieldCount=0;private blades=0;private links=0;private stasis=0;private echoes:Echo[]=[];private serial=0;private lastTime=0;private generation='';private sampled=new Map<string,number>();private anchors=new Map<number,HeroCast>();private fleets:Fleet[]=[];private supportTargets=new Set<number>();private skillBlades=0;private convergence=0;private fleetBeams=0;private beamWidth=0;
 stats={launches:0,impacts:0,skillImpacts:0,heals:0,solar:0,echoes:0,stasis:0,peakCores:0};
 constructor(private view:BattleRenderer,private world:World){this.material=new ProtossHeroMaterials(view.scene,view.camera,view.fx);this.aura=new HeroAuraEffects(view,world,PROTOSS_HERO_IDS);}
 prepare(){if(this.ready)return;this.material.prepare();this.aura.prepare();const batch=this.view.fx.batches.get('fx.hero-basic.energyplane3');if(!batch)throw Error('Missing original psionic texture');const map=(batch.mesh.material as THREE.ShaderMaterial).uniforms.map.value;
  const material=(shell:boolean)=>new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{map:{value:map},time:{value:0},shell:{value:shell?1:0}},vertexShader:'varying vec2 uv0;varying vec3 normal0;varying vec3 eye0;varying vec3 c;void main(){uv0=uv;c=instanceColor;vec4 p=modelViewMatrix*instanceMatrix*vec4(position,1.);normal0=normalize(normalMatrix*mat3(instanceMatrix)*normal);eye0=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',fragmentShader:`uniform sampler2D map;uniform float time;uniform float shell;varying vec2 uv0;varying vec3 normal0;varying vec3 eye0;varying vec3 c;void main(){float rim=pow(1.-abs(dot(normalize(normal0),normalize(eye0))),2.8);float grain=texture2D(map,uv0*2.+vec2(time*.045,-time*.08)).r;float weave=pow(.5+.5*cos(uv0.x*80.+sin(uv0.y*35.-time)*2.),18.)*pow(.5+.5*cos(uv0.y*55.+time*.3),8.);float a=mix(.25+grain*.2+rim*.4,.008+rim*(.16+grain*.12)+weave*.095,shell);gl_FragColor=vec4(c*(.65+grain*.4+rim*.25),a);
   #include <tonemapping_fragment>
   #include <colorspace_fragment>
  }`});
  this.cores=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,3),material(false),512);this.shields=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,2),material(true),256);
  for(const mesh of [this.cores,this.shields]){mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);mesh.setColorAt(0,tint);mesh.renderOrder=3;this.view.scene.add(mesh);}this.ready=true;this.view.fx.protossHeroes=true;
 }
 reset(){this.aura.reset();this.material.reset();this.echoes=[];this.sampled.clear();this.anchors.clear();this.fleets=[];this.supportTargets.clear();this.serial=0;this.lastTime=this.world.time;this.generation=this.world.runId??'';this.coreCount=this.shieldCount=this.blades=this.skillBlades=this.links=this.stasis=this.convergence=this.fleetBeams=this.beamWidth=0;if(this.cores)this.cores.count=0;if(this.shields)this.shields.count=0;this.stats={launches:0,impacts:0,skillImpacts:0,heals:0,solar:0,echoes:0,stasis:0,peakCores:0};}
 private point(p:{x:number;z:number;flying?:boolean},height=.85):Point3{return {x:p.x,z:p.z,y:(p.flying?5.6:this.world.terrain?.height(p)??0)+height};}
 private mount(u:Entity,skill=false,seconds=.04){const model=this.view.gpu.get(u.modelKey??u.unitType),weapon=model?.weaponAt(skill?'skill':'attack',seconds);if(!weapon)return this.point(u,1.1);return weaponWorldPoint({x:u.x,z:u.z,flying:u.flying,facing:u.attackFacing} as any,weapon,modelPresentationScale(u),this.world.terrain?.height(u)??0);}
 private once(key:string,period:number){const last=this.sampled.get(key)??-100;if(this.world.time-last<period)return false;this.sampled.set(key,this.world.time);return true;}
 private body(p:Point3,scale:Point3,color:number,shell=false){const mesh=shell?this.shields:this.cores,index=shell?this.shieldCount:this.coreCount;if(!mesh||index>=mesh.instanceMatrix.count)return;object.position.set(p.x,p.y,p.z);object.rotation.set(this.world.time*.2,this.world.time*.4,p.x*.13);object.scale.set(scale.x,scale.y,scale.z);object.updateMatrix();mesh.setMatrixAt(index,object.matrix);mesh.setColorAt(index,tint.set(color));if(shell)this.shieldCount++;else this.coreCount++;}
 private curve(from:Point3,to:Point3,width:number,color:number,opacity=1,bend=.1,segments=16){let previous=from;const dx=to.x-from.x,dz=to.z-from.z,length=Math.max(.001,Math.hypot(dx,dz));for(let i=1;i<=segments;i++){const t=i/segments,p=mix(from,to,t),wave=Math.sin(t*Math.PI)*bend;p.x+=dz/length*wave;p.z-=dx/length*wave;p.y+=Math.sin(t*Math.PI)*bend*.5;this.material.ribbon('blade',previous,p,width*(.3+.7*Math.sin(t*Math.PI)),color,opacity,0,true,1.15);previous=p;}}
 private motes(p:Point3,count:number,color:number,size=.07,life=.3){const actual=this.view.fx.heroQuality==='full'?count:Math.max(2,Math.ceil(count*(this.view.fx.heroQuality==='balanced'?.65:.3)));for(let i=0;i<actual;i++){const a=i*2.399+this.world.time,r=.1+(i%5)*.12;this.view.fx.emit({asset:'fx.hero-skill.kenney-spark_02',...p,vx:Math.sin(a)*r*3,vy:.5+(i%3)*.4,vz:Math.cos(a)*r*3,start:this.world.time,life,size,growth:-.025,color,ground:false,angle:a,opacity:.8,priority:'trail'});}}
 private blade(from:Point3,to:Point3,color:number,rank:number,t:number,dual=false,skill=false,opacity=1){
  const angle=Math.atan2(to.x-from.x,to.z-from.z),radius=skill?3.3:Math.min(2.6,Math.max(1.5,Math.hypot(to.x-from.x,to.z-from.z))),sides=dual?[-1,1]:[1],width=skill?P.skillBladeWidth:P.basicBladeWidth;
  for(const side of sides){const points:Point3[]=[],widths:number[]=[];for(let i=0;i<=28;i++){const f=i/28,a=angle+side*(-1.25+f*2.05*Math.max(.35,t));points.push({x:from.x+Math.sin(a)*radius*(.46+f*.54),y:from.y-.25+Math.sin(f*Math.PI)*.32,z:from.z+Math.cos(a)*radius*(.46+f*.54)});widths.push(width*Math.sin(f*Math.PI));}this.material.stroke(points,widths,color,opacity*.62,1.1);if(rank>=3)this.material.stroke(points.map(p=>({...p,y:p.y+.035})),widths.map(v=>v*(rank>=5?.28:.2)),0xfff4d5,opacity*.42,1.1);
   this.material.sprite('glow',points.at(-1)!,skill?.5:.25,color,opacity*.5);
  }this.blades+=sides.length;if(skill)this.skillBlades+=sides.length;
 }
 private impact(p:Point3,color:number,rank:number,big=false,opacity=1){this.material.sprite('glow',p,big?2.2:.6,0xfff9de,opacity*.6);this.material.sprite('plasma',p,big?4.8:1.05,color,opacity*.55,0,this.world.time,true);if(this.once('impact:'+p.x+':'+p.z+':'+color,.16))this.motes(p,big?(rank>=5?28:18):rank>=5?8:4,color,big?.1:.06,big?.65:.3);}
 private packet(p:AttackPacket){if(!isProtossHero(p.hero)||p.lost||this.world.time<p.born||this.world.time>=p.arrival)return;const t=clamp01((this.world.time-p.born)/Math.max(.001,p.arrival-p.born)),from=this.childPresentation(p.source)?.point??this.mount(p.source),color=colors[p.hero];if(['artanis','zeratul','alarak','vorazun'].includes(p.hero)){this.blade(from,p.to,color,p.rank,Math.max(.25,t),p.hero==='artanis');return;}
  const head=mix(from,p.to,t),tail=mix(from,p.to,Math.max(0,t-.12)),radius=p.hero==='fenix'?.19:.07;this.body(head,{x:radius,y:radius,z:radius},color);this.material.sprite('glow',head,radius*2,0xfcf5da,.72);this.material.ribbon('beam',tail,head,radius,color,.65);if(p.rank>=3)this.body(head,{x:radius*1.7,y:radius*1.7,z:radius*1.7},color,true);if(this.once('tail:'+p.id,.05))this.motes(head,p.rank>=5?3:1,color,.04,.18);
 }
 private castSource(c:HeroCast){const data=HEROES[c.hero],live=this.world.entities.get(c.source);return {...live,heroId:c.hero,modelKey:data.model,unitType:data.baseFamily,rank:c.rank??live?.rank??1,x:c.presentationLaunch?.x??c.origin.x,z:c.presentationLaunch?.z??c.origin.z,flying:data.flying,attackFacing:c.presentationLaunch?.facing??Math.atan2(c.point.x-c.origin.x,c.point.z-c.origin.z)} as Entity;}
 /** Called before bodies are drawn, so a real child has exactly one display body in its skill formation. */
 beginFrame(){
  const w=this.world;if(w.time<this.lastTime||this.generation!==(w.runId??''))this.reset();this.lastTime=w.time;this.generation=w.runId??'';
  for(const c of w.heroCasts)if(isProtossHero(c.hero)&&!this.anchors.has(c.id))this.anchors.set(c.id,{...c,origin:{...c.origin},point:{...c.point},presentationLaunch:c.presentationLaunch?{...c.presentationLaunch}:undefined});
  for(const event of w.heroAttackEvents)if(isProtossHero(event.packet.hero)&&this.once('event:'+event.kind+':'+event.packet.id,20)){if(event.kind==='launch')this.stats.launches++;if(event.kind==='impact'&&!event.packet.lost){this.stats.impacts++;this.echoes.push({kind:'hit',hero:event.packet.hero,rank:event.packet.rank,at:event.at,life:['artanis','zeratul','alarak','vorazun'].includes(event.packet.hero)?P.basicTrail:.32,from:this.mount(event.packet.source),to:{...event.p},source:event.packet.source.id});}}
  for(const e of w.visualEvents)if(e.serial>this.serial){this.serial=e.serial;if(!isProtossHero(e.heroId))continue;const hero=e.heroId,rank=e.rank??1,anchor=e.castId?this.anchors.get(e.castId):undefined,p=this.point({...e.end,flying:e.endY>3}),from=anchor?this.mount(this.castSource(anchor),true):this.point({...e,flying:e.flying});
   if(e.kind==='skill-impact')this.stats.skillImpacts++;if(e.kind==='skill-status')this.stats.stasis++;if(e.kind==='skill-heal')this.stats.heals++;if(e.kind==='weapon-area'&&hero==='fenix')this.stats.solar++;if(e.kind==='weapon-area'&&hero==='zeratul')this.stats.echoes++;
   const melee=['artanis','zeratul','alarak','vorazun'].includes(hero),relevant=['skill-impact','skill-status','weapon-area','skill-heal'].includes(e.kind)||e.kind==='skill-launch'&&hero==='artanis';if(!relevant)continue;
   const kind=e.kind==='skill-launch'?'ritual':e.kind,key='echo:'+hero+':'+kind+':'+(e.castId??e.serial);if(kind!=='skill-heal'&&!this.once(key,20))continue;
   this.echoes.push({kind,hero,rank,at:e.time,life:kind==='skill-heal'?.28:hero==='purifier_flagship'?1.1:melee?P.skillTrail:.85,from,to:p,source:e.entityId,castId:e.castId,facing:e.facing});
  }
  this.echoes=this.echoes.filter(e=>trailOpacity(w.time,e.at,e.life)>0);for(const [id,c] of this.anchors)if(w.time>c.at+1.2)this.anchors.delete(id);
  const casts=w.heroCasts.filter(c=>c.hero==='purifier_flagship');for(const e of this.echoes)if(e.hero==='purifier_flagship'&&e.kind==='skill-impact'&&w.time-e.at<P.fleetRelease){const c=e.castId?this.anchors.get(e.castId):undefined;if(c&&!casts.some(a=>a.id===c.id))casts.push(c);}
  this.fleets=casts.flatMap(c=>{const source=w.entities.get(c.source);if(!source||source.hp<=0||fleetPhase(w.time,c.beganAt??c.at-1.4,c.at).expired)return [];const display={...c,origin:{x:source.x,z:source.z},presentationLaunch:c.presentationLaunch?{...c.presentationLaunch,x:source.x,z:source.z}:undefined};return [{cast:display,source,children:ownedInterceptors(w,source.id).sort((a,b)=>a.id-b.id)}];});
 }
 childPresentation(u:Entity){if(u.hp<=0||u.summonKind!=='interceptor')return null;const fleet=this.fleets.find(f=>f.source.id===u.summonOwnerId);if(!fleet)return null;const index=fleet.children.findIndex(c=>c.id===u.id);if(index<0)return null;const pose=fleetChildPoint(fleet.cast,u,index,this.world.time);return {...pose,modelKey:fleet.source.modelKey??HEROES.purifier_flagship.model,scale:modelPresentationScale(fleet.source)*.205};}
 private fleet(f:Fleet,visible:(p:{x:number;z:number})=>boolean){const w=this.world,c=f.cast,frame=fleetFrame(c),phase=fleetPhase(w.time,c.beganAt??c.at-1.4,c.at),fade=c.at<w.time?trailOpacity(w.time,c.at,P.fleetRelease):1;if(!visible(frame.center)&&!visible(c.point))return;
  for(let i=0;i<f.children.length;i++){const child=f.children[i],p=fleetChildPoint(c,child,i,w.time).point;if(!visible(p))continue;this.body(p,{x:.26+phase.charge*.3,y:.22+phase.charge*.22,z:.26+phase.charge*.3},0xffdf92,true);this.material.sprite('glow',p,.75+phase.charge*.8,0xffdf8b,.5*fade);if(phase.progress>.12){this.material.ribbon('beam',p,frame.focus,.23,0xffd577,(.25+phase.charge*.35)*fade,0,true,1.05);this.convergence++;}if(this.once('fleet-charge:'+child.id,.13))this.motes(p,2,0xffda8d,.05,.24);}
  this.body(frame.focus,{x:.28+phase.charge*.65,y:.28+phase.charge*.65,z:.28+phase.charge*.65},0xffeabd);this.body(frame.focus,{x:1.1,y:1.1,z:1.1},0x8bcaff,true);this.material.sprite('glow',frame.focus,2.7,0xffe5a6,.55*fade);
  if(phase.beam){const target=w.body(c.target),to=this.point({...c.point,flying:target?.flying},.95);this.material.ribbon('beam',frame.focus,to,P.fleetBeamHalo,0x83baff,.2*fade,0,true,.9);this.material.ribbon('beam',frame.focus,to,P.fleetBeamWidth,0xffde91,.94*fade,0,true,1.35);this.material.ribbon('beam',frame.focus,to,.85,0xfff6d7,.8*fade,0,true,1.25);this.material.sprite('glow',to,3.5,0xffedac,.65*fade);this.fleetBeams++;this.beamWidth=P.fleetBeamWidth;}
 }
 private wave(from:Point3,to:Point3,color:number,t:number,opacity=1){const angle=Math.atan2(to.x-from.x,to.z-from.z),head=mixPoint(from,to,clamp01(t)),radius=2.15,points:Point3[]=[],widths:number[]=[];for(let i=0;i<=32;i++){const a=angle-Math.PI/2+i*Math.PI/32;points.push({x:head.x+Math.sin(a)*radius*.55,y:head.y+.14+Math.sin(i*Math.PI/32)*.6,z:head.z+Math.cos(a)*radius*.55});widths.push(1.1*Math.sin(i*Math.PI/32));}this.material.stroke(points,widths,color,opacity*.75,1.2);this.material.sprite('plasma',head,3.2,color,opacity*.6);this.skillBlades++;}
 private cast(c:HeroCast){if(!isProtossHero(c.hero)||c.hero==='purifier_flagship')return;const w=this.world,data=HEROES[c.hero],rank=c.rank??1,color=colors[c.hero],source=this.castSource(c),from=this.mount(source,true,c.presentationLaunch?.poseSeconds??Math.max(0,w.time-(c.beganAt??w.time))),to=this.point({...c.point,flying:w.body(c.target)?.flying}),begin=c.beganAt??c.at-data.delay,t=clamp01((w.time-begin)/Math.max(.01,data.delay));
  if(c.hero==='alarak'){if(w.time<c.at-.2){this.body(from,{x:.3+t*.2,y:.4+t*.25,z:.3+t*.2},color,true);this.material.sprite('glow',from,1.2,color,.5);return;}const angle=Math.atan2(c.point.x-c.origin.x,c.point.z-c.origin.z),end={x:c.origin.x+Math.sin(angle)*data.length,y:to.y,z:c.origin.z+Math.cos(angle)*data.length};this.wave(this.point(c.origin,1),end,color,(w.time-(c.at-.2))/.2);return;}
  if(c.hero==='fenix'){const f=clamp01((w.time-(c.at-.4))/.4),head=mix(from,to,f);head.y+=Math.sin(f*Math.PI)*.5;this.body(head,{x:.52,y:.52,z:.52},0xffe5ad);this.body(head,{x:.8,y:.8,z:.8},0x91ceff,true);this.material.ribbon('beam',mix(from,to,Math.max(0,f-.24)),head,1.15,0xb3e2ff,.7);if(this.once('solar-cast:'+c.id,.07))this.motes(head,5,0xffd789,.06,.3);return;}
  if(c.hero==='zeratul'){this.blade(from,to,color,rank,Math.max(.3,t),false,true);this.material.sprite('plasma',from,2.8,color,.4);return;}
  if(c.hero==='vorazun'){this.blade(from,to,color,rank,Math.max(.35,t),true,true,.7);this.body(to,{x:1+t,y:1.5,z:1+t},color,true);}
 }
 render(visible:(p:{x:number;z:number})=>boolean){if(!this.ready)return;this.beginFrame();const w=this.world;this.coreCount=this.shieldCount=this.blades=this.skillBlades=this.links=this.stasis=this.convergence=this.fleetBeams=this.beamWidth=0;this.supportTargets.clear();this.material.begin(w.time);for(const mesh of [this.cores!,this.shields!])(mesh.material as THREE.ShaderMaterial).uniforms.time.value=w.time;
  for(const p of w.heroAttacks.packets)if(visible(p.source)||visible(p.to))this.packet(p);for(const c of w.heroCasts)if(visible(c.origin)||visible(c.point))this.cast(c);for(const f of this.fleets)this.fleet(f,visible);
  for(const e of this.echoes){if(!visible(e.to)&&!visible(e.from))continue;const t=clamp01((w.time-e.at)/e.life),alpha=trailOpacity(w.time,e.at,e.life),color=colors[e.hero as keyof typeof colors];
   if(e.kind==='skill-heal'){this.material.sprite('glow',e.to,.7,0xaad9ff,alpha*.5);continue;}
   if(e.kind==='hit'){if(['artanis','zeratul','alarak','vorazun'].includes(e.hero))this.blade(e.from,e.to,color,e.rank,1,e.hero==='artanis',false,alpha*.58);else this.impact(e.to,color,e.rank,false,alpha);continue;}
   if(e.hero==='alarak'&&e.kind==='skill-impact'){const anchor=e.castId?this.anchors.get(e.castId):undefined,angle=anchor?Math.atan2(anchor.point.x-anchor.origin.x,anchor.point.z-anchor.origin.z):e.facing??0,origin=anchor?this.point(anchor.origin,1):e.from,end={x:origin.x+Math.sin(angle)*HEROES.alarak.length,y:origin.y,z:origin.z+Math.cos(angle)*HEROES.alarak.length};this.wave(origin,end,color,1,alpha);continue;}
   if(e.hero==='zeratul'||e.kind==='weapon-area'&&e.hero==='artanis'||e.kind==='ritual'||e.hero==='vorazun'&&e.kind==='skill-status'){this.blade(e.from,e.to,color,e.rank,1,e.hero==='artanis'||e.hero==='vorazun',true,alpha);if(e.kind!=='ritual')this.impact(e.to,color,e.rank,false,alpha);continue;}
   if(e.kind==='skill-status')continue;const big=e.kind==='skill-impact'&&['fenix','purifier_flagship'].includes(e.hero)||e.kind==='weapon-area'&&e.hero==='fenix';this.impact(e.to,color,e.rank,big,alpha);if(big){const radius=(e.hero==='purifier_flagship'?4:3.2)*(.35+t*.75);this.body(e.to,{x:radius,y:radius*.35,z:radius},color,true);}
  }
  for(const u of w.allies())if(isProtossHero(u.heroId)&&visible(u)){const p=this.point(u,1),s=u.protossCombat;if(s&&(s.overdriveUntil>w.time||u.heroId==='alarak'&&s.power>0))this.body(p,{x:u.heroId==='purifier_flagship'?1.8:.72,y:u.heroId==='purifier_flagship'?1.1:1.2,z:u.heroId==='purifier_flagship'?1.8:.72},colors[u.heroId],true);
   for(const id of u.healTargets??[]){const a=w.entities.get(id);if(a&&a.hp>0&&visible(a)&&w.edgeDistance(u,a)<=8&&w.hasAttackLine(u,a)){this.supportTargets.add(id);const target=this.point(a,1);this.body(target,{x:.58,y:.9,z:.58},0xb8dfff,true);this.material.sprite('glow',target,.48,0xa4d7ff,.24);if(this.once('shield:'+id,.2))this.motes(target,2,0xbfe7ff,.055,.4);}}
  }
  for(const r of w.protossHeroes.shields){const source=w.entities.get(r.source);if(!source||source.hp<=0||r.until<w.time)continue;for(const f of r.targets){const a=w.entities.get(f.id);if(a&&a.hp>0&&visible(a)&&w.edgeDistance(source,a)<=6&&w.hasAttackLine(source,a)){this.body(this.point(a,1),{x:.78,y:1.16,z:.78},0xa6dfff,true);this.supportTargets.add(a.id);}}}
  if(w.heroEntity('vorazun'))for(const u of w.entities.values())if(u.owner==='zerg'&&u.hp>0&&visible(u)&&((u.stoppedUntil??0)>w.time&&(u.stoppedUntil??0)<w.time+7||(u.attackSlowUntil??0)>w.time)){this.body(this.point(u,1),{x:.76,y:1.2,z:.76},0xb9a5eb,true);this.stasis++;}
  this.aura.render(visible);this.stats.peakCores=Math.max(this.stats.peakCores,this.coreCount);this.material.end();commitInstances(this.cores!,this.coreCount);commitInstances(this.shields!,this.shieldCount);if(this.sampled.size>8192)this.sampled.clear();
 }
 report(){return {ready:this.ready,auras:this.aura.report(),cores:this.coreCount,shieldShells:this.shieldCount,blades:this.blades,skillBlades:this.skillBlades,healingLinks:this.links,shieldRecipients:this.supportTargets.size,stasisShells:this.stasis,skillTrails:this.echoes.filter(e=>e.kind!=='hit'&&e.kind!=='skill-heal').length,fleet:{children:this.fleets.flatMap(f=>f.children.map(c=>c.id)),models:this.fleets.map(f=>f.source.modelKey),convergence:this.convergence,beams:this.fleetBeams,width:this.beamWidth},presentation:P,stats:{...this.stats},materials:this.material.report(),actions:Object.fromEntries(PROTOSS_HERO_IDS.map(id=>{const a=this.view.gpu.get(HEROES[id].model)?.actions;return [id,{attack:a?.attack?.name,skill:a?.skill?.name}];}))};}
}
