import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import type {BattleRenderer} from '../scene/battle-renderer';
import type {World} from '../../simulation/world';
import type {Entity,HeroCast,VisualEvent} from '../../simulation/types';
import type {Point3,AttackPacket} from '../../simulation/combat/hero-attack-upgrades';
import {isZergHero,ZERG_HERO_IDS} from '../../data/zerg-heroes';
import {HEROES} from '../../data/heroes';
import {UpgradeMaterials} from './confirmed-hero/upgrade-materials';
import {HeroAuraEffects} from './confirmed-hero/hero-aura-effects';
import {weaponWorldPoint} from './hero-feedback';
import {modelPresentationScale} from '../../data/combat-presentation';
import {assetUrl} from '../../assets/manifest';
import {prepareEmbeddedAssetIds} from '../../assets/offline-pack';
import {restoreSc2Materials,sc2BodyBounds} from '../loaders/sc2-materials';
import {commitInstances} from '../units/instance-updates';

type Echo={at:number;life:number;p:Point3;from:Point3;hero:string;rank:number;kind:string;id:number};
type BodyBatch={mesh:THREE.InstancedMesh;count:number};
const colors:Record<string,number>={kerrigan:0xcc8fff,zagara:0xc6ed64,dehaka:0xffd68e,stukov:0xc5dc76,niadra:0xaefcc7,hots_leviathan:0xabbcff};
const object=new THREE.Object3D(),tint=new THREE.Color(),up=new THREE.Vector3(0,1,0),v=(p:Point3)=>new THREE.Vector3(p.x,p.y,p.z);
const mix=(a:Point3,b:Point3,t:number):Point3=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,z:a.z+(b.z-a.z)*t});

/** Original textured bodies, fine curved filaments, organic membrane and source flipbooks.
 * Everything follows real packets/casts/state; there is no damage or gameplay RNG in this renderer.
 */
export class ZergHeroEffects {
 ready=false;private aura:HeroAuraEffects;private material:UpgradeMaterials;private bodies:BodyBatch[]=[];private spines:BodyBatch[]=[];private membrane?:THREE.InstancedMesh;
 private membraneCount=0;private echoes:Echo[]=[];private lastSerial=0;private generation='';private lastTime=0;private samples=new Map<string,number>();private dedupe=new Map<string,number>();private anchors=new Map<number,{p:Point3;at:number}>();
 private coreCount=0;private clawCount=0;private acidCount=0;private healingCount=0;private barrierCount=0;private cocoonCount=0;
 stats={launches:0,impacts:0,cleaves:0,skillImpacts:0,skillPulses:0,dots:0,heals:0,revives:0,hatches:0,tentacles:0,peakCores:0};
 constructor(private view:BattleRenderer,private world:World){this.material=new UpgradeMaterials(view.scene,view.camera,view.fx);this.aura=new HeroAuraEffects(view,world,ZERG_HERO_IDS);}
 async prepare(){if(this.ready)return;await prepareEmbeddedAssetIds(['model.baneling']);this.material.prepare();this.aura.prepare();
  const gltf=await restoreSc2Materials(await new GLTFLoader().loadAsync(assetUrl('model.baneling')!));gltf.scene.updateMatrixWorld(true);const box=sc2BodyBounds(gltf.scene),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=.48/Math.max(size.x,size.y,size.z);
  gltf.scene.traverse(n=>{if(!(n instanceof THREE.Mesh)||n.userData.sc2Role!=='body')return;const geometry=n.geometry.clone(),positions=geometry.getAttribute('position'),p=new THREE.Vector3();for(let i=0;i<positions.count;i++){n.getVertexPosition(i,p).applyMatrix4(n.matrixWorld).sub(center).multiplyScalar(scale);positions.setXYZ(i,p.x,p.y,p.z);}geometry.deleteAttribute('skinIndex');geometry.deleteAttribute('skinWeight');geometry.computeVertexNormals();const mesh=new THREE.InstancedMesh(geometry,n.material,128);mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);viewAdd(this.view,mesh);this.bodies.push({mesh,count:0});});
  if(!this.bodies.length)throw Error('Original Baneling acid-sac body missing');
  for(const b of this.view.fx.projectiles.batches.get('hydralisk')??[]){const mesh=new THREE.InstancedMesh(b.geometry,b.material,256);mesh.count=0;mesh.frustumCulled=false;mesh.instanceMatrix.setUsage(THREE.DynamicDrawUsage);viewAdd(this.view,mesh);this.spines.push({mesh,count:0});}
  const texture=this.view.fx.batches.get('fx.bile.4');if(!texture)throw Error('Original Zerg acid texture missing');const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{time:{value:0},map:{value:(texture.mesh.material as THREE.ShaderMaterial).uniforms.map.value}},
   vertexShader:'varying vec2 vUv;varying vec3 n;varying vec3 eye;varying vec3 c;void main(){vUv=uv;c=instanceColor;vec4 p=modelViewMatrix*instanceMatrix*vec4(position,1.);n=normalize(normalMatrix*mat3(instanceMatrix)*normal);eye=normalize(-p.xyz);gl_Position=projectionMatrix*p;}',
   fragmentShader:`uniform float time;uniform sampler2D map;varying vec2 vUv;varying vec3 n;varying vec3 eye;varying vec3 c;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(eye))),2.6);float tissue=texture2D(map,vUv*1.4+vec2(time*.027,-time*.051)).r;float veins=pow(.5+.5*sin(vUv.x*52.+sin(vUv.y*34.+time*1.8)*3.5),10.);float web=pow(.5+.5*sin(vUv.y*48.+cos(vUv.x*29.-time)*2.6),14.);float a=.012+tissue*.015+rim*(.19+tissue*.12)+(veins+web)*.05;gl_FragColor=vec4(c*(.45+rim*.5+tissue*.25),a);#include <tonemapping_fragment>\n#include <colorspace_fragment>}`.replace(';#include',';\n#include')});
  this.membrane=new THREE.InstancedMesh(new THREE.IcosahedronGeometry(1,3),mat,256);this.membrane.count=0;this.membrane.frustumCulled=false;this.membrane.instanceMatrix.setUsage(THREE.DynamicDrawUsage);this.membrane.setColorAt(0,tint);this.membrane.renderOrder=3;viewAdd(this.view,this.membrane);this.ready=true;this.view.fx.zergHeroes=true;
 }
 reset(){this.aura.reset();this.echoes=[];this.samples.clear();this.dedupe.clear();this.anchors.clear();this.lastSerial=0;this.lastTime=this.world.time;this.generation=this.world.runId??'';this.stats={launches:0,impacts:0,cleaves:0,skillImpacts:0,skillPulses:0,dots:0,heals:0,revives:0,hatches:0,tentacles:0,peakCores:0};this.material.reset();for(const b of [...this.bodies,...this.spines])b.mesh.count=b.count=0;if(this.membrane)this.membrane.count=0;}
 private point(p:{x:number;z:number;flying?:boolean},height=.8):Point3{return {x:p.x,z:p.z,y:(p.flying?5.6:this.world.terrain?.height(p)??0)+height};}
 private once(key:string,period:number){const previous=this.samples.get(key)??-100;if(this.world.time-previous<period)return false;this.samples.set(key,this.world.time);return true;}
 private single(key:string){if(this.dedupe.has(key))return false;this.dedupe.set(key,this.world.time);return true;}
 private sprite(asset:string,p:Point3,size:number,life:number,color:number,growth=0,ground=false,velocity?:Point3,opacity=1){this.view.fx.emit({asset,...p,vx:velocity?.x??0,vy:velocity?.y??0,vz:velocity?.z??0,start:this.world.time,life,size,growth,color,ground,angle:this.world.time*.29,opacity,neutralize:false,priority:'trail'});}
 private motes(p:Point3,count:number,color:number,force=2,life=.45){count=this.view.fx.heroQuality==='full'?count:Math.max(2,Math.ceil(count*(this.view.fx.heroQuality==='balanced'?.7:.35)));for(let i=0;i<count;i++){const a=i*2.399+this.world.time,dy=.4+(i%5)*.24;this.sprite('fx.hero-skill.kenney-spark_02',p,.045+(i%3)*.018,life,color,-.04,false,{x:Math.sin(a)*force,y:dy,z:Math.cos(a)*force});}}
 private skin(p:Point3,scale:Point3,color:number,turn=0){if(!this.membrane||this.membraneCount>=256)return;object.position.set(p.x,p.y,p.z);object.rotation.set(.06,turn,.04);object.scale.set(scale.x,scale.y,scale.z);object.updateMatrix();this.membrane.setMatrixAt(this.membraneCount,object.matrix);this.membrane.setColorAt(this.membraneCount++,tint.set(color));}
 private body(batches:BodyBatch[],p:Point3,scale:number,facing:number,spin=0){for(const b of batches){if(b.count>=b.mesh.instanceMatrix.count)continue;object.position.set(p.x,p.y,p.z);object.rotation.set(spin,facing,spin*.2);object.scale.setScalar(scale);object.updateMatrix();b.mesh.setMatrixAt(b.count++,object.matrix);}}
 private mount(source:Entity,action:'attack'|'skill'='attack',seconds=.05,side?:string){const model=this.view.gpu.get(source.modelKey??source.unitType),weapon=model?.weaponAt(action,seconds,side)??{x:0,y:1,z:.5};return weaponWorldPoint({x:source.x,z:source.z,facing:source.attackFacing,flying:source.flying} as VisualEvent,weapon,modelPresentationScale(source),this.world.terrain?.height(source)??0);}
 private curve(from:Point3,to:Point3,bend:number,width:number,color:number,phase=0,opacity=1,segments=14){const dir=v(to).sub(v(from)).normalize(),right=new THREE.Vector3().crossVectors(dir,up).normalize();if(right.lengthSq()<.1)right.set(1,0,0);let previous=from;for(let i=1;i<=segments;i++){const t=i/segments,p=mix(from,to,t),s=Math.sin(t*Math.PI);p.x+=right.x*Math.sin(t*6+phase)*bend*s;p.z+=right.z*Math.sin(t*6+phase)*bend*s;p.y+=bend*.55*s;this.material.ribbon('arc',previous,p,width,color,opacity,0,true,1.2);previous=p;}}
 private claw(from:Point3,p:Point3,hero:string,rank:number,life:number,wide=false){const color=colors[hero],strands=rank>=5?3:rank>=3?2:1,angle=Math.atan2(p.x-from.x,p.z-from.z);for(let j=0;j<strands;j++){let previous:Point3|undefined;for(let i=0;i<=13;i++){const t=i/13,a=angle+(t-.5)*1.4,extent=(wide?1.5:.65)+j*.09,q={x:p.x+Math.cos(a)*extent*(t-.5)*1.8,y:p.y+.08+Math.sin(t*Math.PI)*(.25+j*.08),z:p.z-Math.sin(a)*extent*(t-.5)*1.8};if(previous){this.material.ribbon('arc',previous,q,(wide?.19:.095)*(1-life*.65),color,Math.sin(Math.PI*life)**.5,0,true,1.7);this.material.ribbon('arc',previous,q,wide?.055:.027,0xf8e4ff,Math.sin(Math.PI*life)*.6,0,true,1.5);}previous=q;}}this.clawCount++;}
 private impact(p:Point3,hero:string,rank:number,big=false){const color=colors[hero];this.sprite(hero==='kerrigan'?'fx.hero-basic.flare1_blueelec':'fx.baneling.1',p,big?3.2:.7,big?.65:.27,color,.2);this.sprite('fx.bile.6',p,big?2.5:.42,big?.58:.26,hero==='dehaka'?0xc7bb83:0xc5e290,big?1.2:.2);this.motes(p,big?22:rank>=5?9:rank>=3?6:4,color,big?4.5:1.5);if(big)this.sprite('fx.bile.4',{...p,y:(this.world.terrain?.height(p)??0)+.05},2.7,.8,color,2.2,true,undefined,.35);}
 private attackEvents(){for(const e of this.world.heroAttackEvents){if(!isZergHero(e.packet.hero))continue;const p=e.packet,color=colors[p.hero];if(e.kind==='launch'){this.stats.launches++;this.sprite('fx.hero-basic.flare2b',this.mount(p.source),p.hero==='hots_leviathan'?.45:.22,.09,color);this.motes(this.mount(p.source),p.rank>=5?4:2,color,.8,.18);}if(e.kind==='impact'){this.stats.impacts++;this.impact(e.p,p.hero,p.rank);if(p.hero==='kerrigan'||p.hero==='dehaka')this.echoes.push({at:e.at,life:.24,p:e.p,from:this.mount(p.source),hero:p.hero,rank:p.rank,kind:'claw',id:p.id});}}
  this.world.heroAttackEvents=this.world.heroAttackEvents.filter(e=>!isZergHero(e.packet.hero));
 }
 private event(e:VisualEvent){if(!isZergHero(e.heroId))return;const hero=e.heroId,p={...e.end,y:e.endY},from={x:e.x,y:e.y,z:e.z},rank=e.rank??1,color=colors[hero];
  if(e.kind==='hero-cleave'){this.stats.cleaves++;this.echoes.push({at:e.time,life:.36,p,from,hero,rank,kind:'cleave',id:e.serial});this.motes(p,rank>=5?18:10,color,3);}
  if(e.kind==='hero-tentacle'){this.stats.tentacles++;this.echoes.push({at:e.time,life:.42,p,from:{...from,y:from.y+.5},hero,rank,kind:'tentacle',id:e.serial});this.impact(p,hero,rank);}
  if(e.kind==='hero-revive'){this.stats.revives++;this.echoes.push({at:e.time,life:.8,p,from,hero,rank,kind:'hatch',id:e.serial});this.sprite('fx.baneling.1',p,1.4,.65,0xbbea9e,1.2);this.motes(p,18,0xd2fac4,2.2,.8);}
  if(e.kind==='hero-hatch'){this.stats.hatches++;this.sprite('fx.bile.6',p,.8,.55,0xb5d777,.6);this.motes(p,9,color,1.2);}
  if(e.kind==='hero-essence'){this.echoes.push({at:e.time,life:.55,p:from,from:p,hero,rank,kind:'essence',id:e.serial});}
  if(e.kind==='skill-heal'){this.stats.heals++;this.echoes.push({at:e.time,life:.55,p,from,hero,rank,kind:'heal',id:e.serial});this.sprite('fx.hero-basic.flare2b',p,.6,.24,0xc4ffc1);this.motes(p,5,0xc4ffc1,1);}
  if(e.kind==='skill-launch'){if(e.castId!==undefined)this.anchors.set(e.castId,{p,at:e.time});this.sprite('fx.bile.4',from,.55,.18,color);this.motes(from,rank>=5?8:4,color,1.1);}
  if(e.kind==='skill-dot'){this.stats.dots++;this.impact(p,hero,rank);this.echoes.push({at:e.time,life:.4,p,from:p,hero,rank,kind:'acid',id:e.serial});}
  if(e.kind==='skill-impact'){this.stats.skillImpacts++;const big=['zagara','stukov','hots_leviathan'].includes(hero)&&this.single('impact:'+e.castId),center=big&&e.castId!==undefined?this.anchors.get(e.castId)?.p??p:p;this.impact(center,hero,rank,big);if(hero==='hots_leviathan'&&big)this.stats.skillPulses++;this.echoes.push({at:e.time,life:hero==='dehaka'?.35:.5,p:center,from,hero,rank,kind:hero==='dehaka'?'claw':hero==='kerrigan'?'cleave':'acid',id:e.serial});}
 }
 private packet(p:AttackPacket){const t=Math.max(0,Math.min(1,(this.world.time-p.born)/(p.arrival-p.born))),from=this.mount(p.source),head=mix(from,p.to,t),hero=p.hero,color=colors[hero],rank=p.rank;
  if(hero==='kerrigan'||hero==='dehaka'){this.claw(from,p.to,hero,rank,Math.max(.05,t));return;}
  const tail=mix(from,p.to,Math.max(0,t-.15));head.y+=Math.sin(Math.PI*t)*.1;const size=hero==='hots_leviathan'?.32:hero==='niadra'?.17:.21;this.coreCount++;
  this.material.sprite('glow',head,size*.8,0xf3ffd9,.9);this.skin(head,{x:size,y:size*.7,z:size},color,this.world.time*2);this.curve(tail,head,.05,size*.65,color,this.world.time*13,.55,8);
  if(hero==='stukov'||hero==='niadra')this.body(this.spines,head,hero==='stukov'?.55:.44,p.source.attackFacing);else if(hero==='zagara')this.body(this.bodies,head,.55,p.source.attackFacing,this.world.time*4);
  this.material.ribbon('warmTrail',tail,head,size*.42,color,.65,0,true);if(rank>=3)this.curve(tail,head,.06,rank>=5?.085:.06,hero==='niadra'?0xbdaaff:0xf6ffd8,this.world.time*11,.4,12);
  if(this.once('tail:'+p.id,.035)){this.sprite(hero==='hots_leviathan'?'fx.hero-skill.nebulacloudsalphaparticle_purple':'fx.bile.4',head,size*1.6,.27,color,.32,false,undefined,.45);if(rank>=3)this.motes(head,rank>=5?3:2,color,.4,.22);}this.acidCount++;
 }
 private cast(c:HeroCast){if(!isZergHero(c.hero)||c.phase==='dot')return;const now=this.world.time,hero=c.hero,data=HEROES[hero],pose=c.presentationLaunch,live=this.world.entities.get(c.source),source={...live,heroId:hero,modelKey:data.model,unitType:data.baseFamily,rank:c.rank??live?.rank??1,x:pose?.x??live?.x??c.origin.x,z:pose?.z??live?.z??c.origin.z,flying:!!data.flying,attackFacing:pose?.facing??Math.atan2(c.point.x-c.origin.x,c.point.z-c.origin.z)} as Entity,rank=source.rank,color=colors[hero],from=this.mount(source,'skill',pose?.poseSeconds??Math.max(0,now-(c.beganAt??now))),target=this.world.body(c.target),to=this.point({...c.point,flying:target?.flying});
  const flight=hero==='kerrigan'?.2:hero==='zagara'?.35:hero==='stukov'?.25:hero==='hots_leviathan'?.4:.35,start=c.at-flight,t=Math.max(0,Math.min(1,(now-start)/flight));
  if(now<start){const growth=1-Math.min(1,(start-now)/.5);this.skin(from,{x:.13+growth*.13,y:.19+growth*.2,z:.13+growth*.13},color,now*2);if(this.once('charge:'+c.id,.07))this.motes(from,rank>=5?4:2,color,.65,.3);return;}
  if(hero==='kerrigan'){const angle=Math.atan2(c.point.x-c.origin.x,c.point.z-c.origin.z),end={x:c.origin.x+Math.sin(angle)*HEROES[hero].length,z:c.origin.z+Math.cos(angle)*HEROES[hero].length,y:to.y},head=mix({...c.origin,y:from.y},end,t),tail=mix({...c.origin,y:from.y},end,Math.max(0,t-.3));this.curve(tail,head,.12,.38,color,now*9,.8,18);this.curve(tail,head,.045,.075,0xf5dbff,now*13,.9,18);const across={x:Math.cos(angle),z:-Math.sin(angle)};for(const side of [-1,1]){const a={x:tail.x+across.x*1.04*side,y:tail.y,z:tail.z+across.z*1.04*side},b={x:head.x+across.x*1.04*side,y:head.y,z:head.z+across.z*1.04*side};this.curve(a,b,.1,.09,color,now*7,.6);}if(this.once('wave:'+c.id,.045)){this.sprite('fx.hero-skill.nebulacloudsalphaparticle_purple',head,2.1,.4,color,1.6,false,undefined,.28);this.motes(head,rank>=5?8:4,0xdfbbff,2.2);}return;}
  if(hero==='zagara'||hero==='stukov'){const head=mix(from,to,t);head.y+=Math.sin(Math.PI*t)*(hero==='zagara'?1.5:.6);this.body(hero==='zagara'?this.bodies:this.spines,head,hero==='zagara'?1.65:1.1,source.attackFacing,hero==='zagara'?now*5:0);this.skin(head,{x:.34,y:.29,z:.34},color,now*2);const tail=mix(from,to,Math.max(0,t-.16));tail.y+=Math.sin(Math.PI*Math.max(0,t-.16))*(hero==='zagara'?1.5:.6);this.curve(tail,head,.07,.15,color,now*10,.65);if(this.once('skilltrail:'+c.id,.035)){this.sprite('fx.bile.4',head,.65,.36,color,.65,false,undefined,.4);this.motes(head,rank>=5?4:2,color,.6,.28);}return;}
  if(hero==='dehaka'){this.curve(from,to,Math.sin(t*Math.PI)*.23,.18,0x90745e,now*3,.8,18);this.curve(from,to,.045,.055,0xffecc0,now*5,.65,18);this.skin(to,{x:.26,y:.2,z:.28},color,now);return;}
  if(hero==='hots_leviathan'){const cloud={...to,y:to.y+2.2},charge=1-(c.at-now)/.4;this.skin(cloud,{x:.65+charge*.45,y:.4,z:.65+charge*.45},0xab75d1,now);const strands=rank>=5?7:rank>=3?5:3;for(let i=0;i<strands;i++){const a=now*.7+i*Math.PI*2/strands,p={x:cloud.x+Math.sin(a)*2.6,y:cloud.y+.5*Math.sin(a*3),z:cloud.z+Math.cos(a)*2.6};this.curve(p,to,.13,.08,i%2?0xb9eca0:0xb79dff,now+i,.7,16);}if(this.once('storm:'+c.id,.07)){this.sprite('fx.hero-skill.nebulacloudsalphaparticle_purple',cloud,3,.45,0xaa84cf,.4,false,undefined,.27);this.motes(cloud,rank>=5?6:3,0xd3fda9,2,.4);}return;}
 }
 render(visible:(p:{x:number;z:number})=>boolean=()=>true){if(!this.ready)return;const w=this.world,last=w.visualEvents.at(-1);if(this.generation!==(w.runId??'')||w.time<this.lastTime||last&&last.serial<this.lastSerial)this.reset();this.lastTime=w.time;this.material.begin();this.membraneCount=this.coreCount=this.clawCount=this.acidCount=this.healingCount=this.barrierCount=this.cocoonCount=0;for(const b of [...this.bodies,...this.spines])b.count=0;(this.membrane!.material as THREE.ShaderMaterial).uniforms.time.value=w.time;this.attackEvents();
  for(const c of w.heroCasts)if(isZergHero(c.hero)&&c.phase!=='dot')this.anchors.set(c.id,{p:this.point({...c.point,flying:w.body(c.target)?.flying}),at:w.time});
  for(const e of w.visualEvents)if(e.serial>this.lastSerial){if(w.time-e.time<1.6)this.event(e);this.lastSerial=e.serial;}
  for(const p of w.heroAttacks.packets)if(isZergHero(p.hero)&&!p.lost)this.packet(p);for(const c of w.heroCasts)this.cast(c);
  this.echoes=this.echoes.filter(e=>w.time-e.at<e.life);for(const e of this.echoes){const t=(w.time-e.at)/e.life,opacity=1-t,color=colors[e.hero]??0xa6d888;if(e.kind==='claw'||e.kind==='cleave')this.claw(e.from,e.p,e.hero,e.rank,t,e.kind==='cleave');if(e.kind==='tentacle')this.curve(e.from,e.p,Math.sin(t*Math.PI)*.8,.12,color,t*4,opacity,24);if(e.kind==='heal'){this.curve(e.from,e.p,.27,.09,0xb3ffca,t*6,opacity,20);this.healingCount++;}if(e.kind==='essence'){const p=mix(e.from,e.p,t);p.y+=Math.sin(t*Math.PI)*.8;this.material.sprite('glow',p,.15,0xffdfa8,opacity);this.curve(e.from,p,.04,.05,0xd3bf9a,t*5,opacity);}if(e.kind==='acid'||e.kind==='hatch')this.skin(e.p,{x:(e.kind==='hatch'?.7:.38)*(1+t),y:.25+opacity*.3,z:(e.kind==='hatch'?.7:.38)*(1+t)},color,t*3);}
  for(const u of w.allies())if(isZergHero(u.heroId)){const s=u.zergCombat,p=this.point(u,1);if(u.heroId==='kerrigan'&&s&&s.barrier>0&&s.barrierUntil>w.time){this.skin(p,{x:.58,y:.95,z:.55},0xbca6ef,w.time*.13);this.barrierCount++;}if(u.heroId==='dehaka'&&s&&s.reserve>0&&s.reserveUntil>w.time){this.skin(this.point(u,.8),{x:1.1,y:1.25,z:1.4},0xe5c283,w.time*.08);this.barrierCount++;}if(u.heroId==='niadra')for(const id of u.healTargets??[]){const a=w.entities.get(id);if(!a||a.hp<=0)continue;this.curve(this.mount(u),this.point(a,.7),.18,.067,0xa6f5bb,w.time*5+id,.7,18);this.healingCount++;if(this.once('healing:'+id,.2))this.motes(this.point(a,.7),2,0xceffc5,.45,.3);}}
  for(const pool of w.zergHeroes.pools)if(pool.until>w.time&&this.once('pool:'+pool.id,.25))this.sprite('fx.bile.4',this.point(pool.point,.04),pool.until-w.time>1?5:3,.4,0x8eac63,0,true,undefined,.18);
  for(const r of w.zergHeroes.revivals)if(r.until>w.time)for(const seat of r.seats)if(!seat.claimed)for(const body of seat.members){const live=w.entities.get(body.id),dead=!live||live.hp<=0;if(dead&&seat.deadAt!==null){this.skin(this.point(body,.42),{x:.5,y:.68,z:.5},0xa9daa0,w.time*.15);this.cocoonCount++;if(this.once('cocoon:'+body.id,.18))this.motes(this.point(body,.4),3,0xb8e4a9,.35,.5);}else if(live&&this.once('mark:'+body.id,.4))this.sprite('fx.bile.4',this.point(live,1.1),.25,.35,0xadd99a,0,false,undefined,.2);}
  this.aura.render(visible);this.stats.peakCores=Math.max(this.stats.peakCores,this.coreCount);this.material.end();for(const b of [...this.bodies,...this.spines])commitInstances(b.mesh,b.count);commitInstances(this.membrane!,this.membraneCount);for(const [key,time] of this.dedupe)if(w.time-time>12)this.dedupe.delete(key);for(const [key,a] of this.anchors)if(w.time-a.at>12)this.anchors.delete(key);if(this.samples.size>4096)this.samples.clear();
 }
 report(){return {ready:this.ready,auraDisplays:this.aura.count/2,auras:this.aura.report(),cores:this.coreCount,claws:this.clawCount,acidLayers:this.acidCount,healingLinks:this.healingCount,barriers:this.barrierCount,cocoons:this.cocoonCount,membranes:this.membraneCount,originalBanelingMeshes:this.bodies.length,originalSpineMeshes:this.spines.length,acidSacInstances:this.bodies[0]?.count??0,spineInstances:this.spines[0]?.count??0,stats:{...this.stats},materials:this.material.report(),actions:Object.fromEntries(ZERG_HERO_IDS.map(id=>{const a=this.view.gpu.get(HEROES[id].model)?.actions;return [id,{attack:a?.attack?.name,skill:a?.skill?.name}];}))};}
}
function viewAdd(view:BattleRenderer,mesh:THREE.Object3D){view.scene.add(mesh);}
