import * as THREE from 'three';
import {World} from '../../src/simulation/world';
import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {FixedStepper} from '../../src/simulation/fixed-stepper';
import {HEROES} from '../../src/data/heroes';
import {ZERG_HERO_IDS as ids,type ZergHeroId} from '../../src/data/zerg-heroes';
import {ASSETS,assetUrl} from '../../src/assets/manifest';
import {loadEmbeddedAssets,prepareEmbeddedAssetIds} from '../../src/assets/offline-pack';
import {captureBattleView} from '../../src/render/input/battle-view';
import {bindBattleView,activateBattleAction} from '../../src/ui/controls/battle-actions';
import {groundHeroBuff} from '../../src/simulation/combat/hero-ground-auras';
import {terrainArray} from '../../src/render/terrain/map-surface';
import type {Entity} from '../../src/simulation/types';
type Mode='battle'|'attack'|'skill'|'revival'|'boss12'|'boss3';
const $=(id:string)=>document.getElementById(id)!;
const selected=new Set<string>(JSON.parse($('demo-assets').textContent!));for(const id of ASSETS.keys())if(!selected.has(id))ASSETS.delete(id);
const world=new World({race:'zerg',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10506});
const canvas=$('battle') as HTMLCanvasElement,view=new BattleRenderer(canvas,world);view.fx.heroQuality='full';view.cameraShake=false;bindBattleView(world,()=>captureBattleView(canvas,view.camera));
let hero:ZergHeroId='kerrigan',rank=5,mode:Mode='battle',ready=false,spawnAt=0,wave=0,previous=performance.now(),zoom='close',boss:number|null=null,bossHp=0,bossAt=0,bossResult='',castAt:number|null=null,enemyShotAt=0,observer:number|null=null;
const keys=new Set<string>(),baseline=new Map<number,number>(),patients:number[]=[],observedShots=new Set<number>();
const description:Record<ZergHeroId,string>={
 kerrigan:'近战灵能爪击；每第三次攻击横扫。实际生命伤害的25%转为8秒护障，上限为最大生命的80%。主动沿线释放灵能冲击。',
 zagara:'有原始虫体的酸囊投射；附近每10次击杀孵化2只爆虫，最多6只、存活10秒。主动连续发射3枚爆虫弹。保留生物友军攻速+40%、移动+20%。',
 dehaka:'原始爪击与精华吸收；击杀提供适应，吞噬额外提供精华、回血和独立生命储备。吞噬为固定高额伤害，可对地面Boss施放。',
 stukov:'感染弹体命中挂6秒感染；感染宿主死亡留下4秒治疗池，重叠只取最强。每第六次攻击追加爆破；主动腐蚀弹附带4次伤害。',
 niadra:'寄生刺与七体持续治疗；寄生宿主死亡触发范围回血。主动登记8秒复生窗口，I/V可复生2/4个编制，每秒一个，双跳虫共用一个次数。',
 hots_leviathan:'有生体纹理的等离子弹与真实触须，每2秒攻击最多4个目标。主动在目标区域释放三轮等离子风暴。保留附近生物友军生命+25%。'
};
function resize(){view.resize();view.camera.zoom=canvas.clientWidth<canvas.clientHeight?1.04:zoom==='close'?1.65:1.18;view.camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function dummy(x:number,z:number,air=false){const e=world.addUnit(air?'mutalisk':'roach','zerg',x,z,1,'regular',13);e.hp=e.maxHp=2000000;e.armor=0;e.moveSpeed=0;e.stoppedUntil=1e9;e.specialReady=1e9;baseline.set(e.id,e.hp);return e;}
function spawn(){wave++;for(let i=0;i<5;i++){const a=world.time*.21+i*.65;world.addUnit(i%3===2?'zergling':'roach','zerg',world.anchor.x+5.3+Math.cos(a)*2,world.anchor.z+Math.sin(a)*4,1,'regular',13);}if(hero==='hots_leviathan'&&wave%2===1)world.addUnit('mutalisk','zerg',world.anchor.x+7,world.anchor.z-3,1,'regular',13);}
function brood(){world.expedition.familySlots=['roach','hydralisk','zergling'];for(let i=0;i<5;i++){const a=world.addUnit(i<4?'roach':'hydralisk','terran',.3+(i%3)*1.25,-2+Math.floor(i/3)*2.5,3);a.hp=Math.max(1,a.maxHp*.2);a.stoppedUntil=1e9;patients.push(a.id);baseline.set(a.id,a.hp);}const ling=world.addFamilyMember('zergling',{x:3.2,z:2},3);for(const a of world.allies().filter(a=>a.pairId===ling.pairId)){a.hp=Math.max(1,a.maxHp*.2);a.stoppedUntil=1e9;patients.push(a.id);baseline.set(a.id,a.hp);}}
function choose(id:ZergHeroId){
 if(id==='niadra'&&(mode==='boss12'||mode==='boss3')){mode='revival';($('mode') as HTMLSelectElement).value=mode;}
 hero=id;view.resetRun();world.resetRun();world.start();world.entities.clear();world.heroes.clear();world.pods=[];world.hive=null;world.expansionHives.clear();world.economicTargets.clear();world.fortifications.clear();world.pickups=[];world.rewardDrops=[];world.stage=mode==='boss12'||mode==='boss3'?12:13;world.difficulty=mode==='boss12'||mode==='boss3'?'easy':'normal';world.stageElapsed=0;baseline.clear();patients.length=0;observedShots.clear();boss=null;bossResult='';castAt=null;observer=null;
 for(const plan of Object.values(world.expedition.production))plan.enabled={};world.acquireHero(id);const u=world.heroEntity(id)!;u.rank=rank;world.heroes.get(id)!.rank=rank;world.refreshStats(u,true);u.x=-1.5;u.z=0;u.prev={x:u.x,z:u.z};world.anchor.x=world.anchor.z=0;spawnAt=0;wave=0;world.paused=false;keys.clear();world.resetDirectionalInput();
 if(mode==='attack'||mode==='skill'){const melee=id==='kerrigan'||id==='dehaka';for(const [x,z] of (melee?[[.3,0],[1,1.1],[3,0],[5,0],[3,-1.1]]:[[3,0],[5,0],[7,0],[4,1.2],[6,-1.3]]))dummy(x,z);if(['zagara','stukov','niadra','hots_leviathan'].includes(id))dummy(5,-3,true);}
 if(id==='niadra'){brood();patients.sort((a,b)=>Number(!world.entities.get(a)?.pairId)-Number(!world.entities.get(b)?.pairId)||a-b);if(mode==='skill'||mode==='revival'){const e=dummy(5.2,1);e.weaponDamage=8000;e.attackRange=12;observer=e.id;}}
 if(mode==='skill'||mode==='revival'||mode==='boss12'||mode==='boss3')u.stoppedUntil=1e9;
 if(mode==='boss12'||mode==='boss3'){
  if(mode==='boss3'){world.stage=18;world.endless={round:3,startedAt:world.time,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=world.spawnSpecial('queen','boss',{x:12,z:0})!;world.entities.delete(first.id);}
  const e=world.spawnSpecial(mode==='boss3'?'lurker':'ravager','boss',{x:id==='dehaka'?.5:5,z:0})!;e.moveSpeed=0;e.stoppedUntil=1e9;e.specialReady=1e9;if(mode==='boss3')world.castDetection();boss=e.id;bossHp=Math.round(e.hp);bossAt=world.time;baseline.set(e.id,e.hp);bossResult=`Boss ${Math.ceil(e.hp)} HP · 护甲 ${e.armor}`;
 }
 world.hash.rebuild(world.entities.values());for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.setAttribute('aria-pressed',String(b.dataset.hero===id));$('name').textContent=HEROES[id].name;$('description').textContent=description[id];$('pause').textContent='暂停';$('portrait').innerHTML=assetUrl('hero.'+id)?`<img src="${assetUrl('hero.'+id)}" alt="${HEROES[id].name}">`:'';$('state').textContent='';resize();world.changed();
}
function cast(){const u=world.heroEntity(hero);if(!u)return;const stopped=u.stoppedUntil;u.stoppedUntil=0;const ok=activateBattleAction(world,'hero-slot-0');u.stoppedUntil=stopped;if(ok){castAt=world.time;enemyShotAt=world.time+.38;if(mode==='boss12'||mode==='boss3')bossAt=world.time;}}
const stepper=new FixedStepper(1/60,()=>{if(!ready||world.paused||world.phase!=='battle')return false;world.stageElapsed=0;world.rewardDrops=[];if(mode==='battle'&&world.time>=spawnAt&&world.enemyCount()<24){spawn();spawnAt=world.time+1.25;}
 if(observer&&castAt!==null&&world.time>=enemyShotAt&&world.time-castAt<7.3){const e=world.entities.get(observer),a=patients.map(id=>world.entities.get(id)).find(a=>a&&a.hp>0&&!observedShots.has(a.id));if(e&&a){world.fire(e,a);observedShots.add(a.id);}enemyShotAt=world.time+1.3;}
 world.input.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);world.input.z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(mode==='boss3'&&world.endless)world.endless.startedAt=world.time;world.step();return true;},()=>performance.now(),8);
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-previous)/1000);previous=now;const alpha=ready&&!world.paused?stepper.advance(dt):0;view.render(dt,alpha);if(!ready)return;const u=world.heroEntity(hero),hp=Math.max(0,u?.hp??0),max=u?.maxHp??1;$('vital-fill').style.width=hp/max*100+'%';$('health').textContent=Math.ceil(hp)+' / '+Math.ceil(max);$('kills').textContent=String(world.stats.kills);$('time').textContent=Math.floor(world.time/60).toString().padStart(2,'0')+':'+Math.floor(world.time%60).toString().padStart(2,'0');$('enemies').textContent=String(world.enemyCount());
 const remaining=Math.max(0,(world.heroes.get(hero)?.skillReady??0)-world.time);($('cast') as HTMLButtonElement).disabled=remaining>0||world.paused;$('cast').textContent=remaining>0?`${HEROES[hero].skill} · ${Math.ceil(remaining)}s`:'释放技能 · 空格';if(boss&&!world.entities.get(boss)?.hp&&bossResult.includes('Boss '))bossResult=`一发击杀 · ${bossHp} HP · ${(world.time-bossAt).toFixed(2)} 秒`;else if(boss&&world.entities.get(boss)?.hp&&world.time-bossAt>HEROES[hero].delay)bossResult=`Boss 剩余 ${Math.ceil(world.entities.get(boss)!.hp)} / ${bossHp}`;$('boss-result').textContent=bossResult;
 if(($('details') as HTMLDetailsElement).open){const s=u?.zergCombat,window=world.zergHeroes.revivals[0];$('state').textContent=hero==='dehaka'?`精华 ${s?.essence??0} · 生命储备 ${Math.ceil(s?.reserve??0)}`:hero==='kerrigan'?`灵能护障 ${Math.ceil(s?.barrier??0)}`:hero==='niadra'?`治疗 ${Math.ceil(world.stats.healed)} · 复生 ${view.zergHeroes.stats.revives} · 剩余次数 ${window?.charges??0}`:'';}
}
for(const id of ids){const b=document.createElement('button');b.dataset.hero=id;b.textContent=HEROES[id].name;b.disabled=true;b.onclick=()=>{choose(id);stepper.reset();};$('heroes').append(b);}
$('cast').onclick=cast;$('pause').onclick=()=>{world.paused=!world.paused;$('pause').textContent=world.paused?'继续':'暂停';stepper.reset();};$('restart').onclick=()=>{choose(hero);stepper.reset();};$('rank').onchange=()=>{rank=Number(($('rank') as HTMLSelectElement).value);choose(hero);stepper.reset();};$('mode').onchange=()=>{mode=($('mode') as HTMLSelectElement).value as Mode;if(mode==='boss12'||mode==='boss3'){rank=mode==='boss12'?1:5;($('rank') as HTMLSelectElement).value=String(rank);choose('dehaka');}else if(mode==='revival')choose('niadra');else choose(hero);stepper.reset();};$('zoom').onclick=()=>{zoom=zoom==='close'?'battle':'close';$('zoom').textContent=zoom==='close'?'战场视角':'近景视角';resize();};
$('quality').onchange=()=>{view.fx.heroQuality=($('quality') as HTMLSelectElement).value as 'full'|'balanced'|'low';};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;const k=e.key.toLowerCase();if(e.code==='Space'){e.preventDefault();cast();}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();world.resetDirectionalInput();});canvas.addEventListener('pointerdown',e=>{if(!ready||world.paused)return;const p=view.pickMove(e.clientX,e.clientY);if(p)world.issueMove(p.point);});canvas.addEventListener('contextmenu',e=>e.preventDefault());
async function load(){await loadEmbeddedAssets();await prepareEmbeddedAssetIds(selected,(d,t)=>{$('interface').textContent=`准备虫群 ${d}/${t}`;});await view.fx.load();await view.confirmedHeroes.prepare();await view.zergHeroes.prepare();for(const type of ['roach','zergling','mutalisk','ravager','lurker','baneling','hydralisk'] as const)if(!await view.ensureUnitVariant(type,type))throw Error(view.modelErrors.join(';'));for(const id of ids)if(!await view.ensureUnitVariant(HEROES[id].model,HEROES[id].baseFamily))throw Error(view.modelErrors.join(';'));
 const texture=await new THREE.TextureLoader().loadAsync(assetUrl('map.terrain.diffuse')!);texture.colorSpace=THREE.SRGBColorSpace;const layers=terrainArray(texture),material=new THREE.MeshStandardMaterial({map:texture,color:0xa0a69a,roughness:1});material.onBeforeCompile=s=>{s.uniforms.groundLayers={value:layers};s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nuniform highp sampler2DArray groundLayers;');s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','float groundPatch=sin(vMapUv.x*27.0)*sin(vMapUv.y*31.0);vec3 ground=texture(groundLayers,vec3(vMapUv*32.0,4.0)).rgb;ground=mix(ground,texture(groundLayers,vec3(vMapUv*32.0,5.0)).rgb,smoothstep(-.5,.6,groundPatch)*.25);diffuseColor.rgb*=ground;');};material.customProgramCacheKey=()=> 'zerg-demo-original-terrain-layers-v1';const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),material);floor.rotation.x=-Math.PI/2;floor.position.y=-.025;view.scene.add(floor);view.initialAssetsLoaded=false;choose(hero);await view.warmPresentationBatches();ready=true;$('interface').hidden=true;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.disabled=false;previous=performance.now();}
requestAnimationFrame(frame);load().catch(e=>{$('interface').textContent='载入失败：'+e.message;console.error(e);});
(window as any).__ZERG_HERO_REPORT__=()=>({ready,hero,rank,mode,paused:world.paused,phase:world.phase,time:world.time,quality:view.fx.heroQuality,shots:world.stats.shots,kills:world.stats.kills,damage:world.stats.damage,healed:world.stats.healed,boss:{id:boss,originalHp:bossHp,hp:boss?world.entities.get(boss)?.hp??0:null,result:bossResult},modelErrors:view.modelErrors,fxErrors:view.fx.errors,render:view.zergHeroes.report(),terranAuras:view.confirmedHeroes.report().auras,packets:world.heroAttacks.packets.map(p=>({id:p.id,hero:p.hero,kind:p.kind,target:p.target,damage:p.damage})),casts:world.heroCasts.map(c=>({id:c.id,hero:c.hero,at:c.at,phase:c.phase,rank:c.rank,damage:c.damage})),state:world.zergHeroes,source:world.heroEntity(hero),targets:[...baseline].map(([id,hp])=>({id,hpBefore:hp,hp:world.entities.get(id)?.hp??0})),buffs:world.allies().map(u=>({id:u.id,...groundHeroBuff(world,u)})),performance:{fps:view.fps,drawCalls:view.renderer.info.render.calls,triangles:view.renderer.info.render.triangles}});
