import {assertManifest,AssetCatalog} from '../src/assets/catalog.mjs';
import {drawThree,rerollThree,claimOne} from '../src/simulation/rules.mjs';
const $=id=>document.getElementById(id), registry=new AssetCatalog(), resolved=new Map();
let manifest;
try{const r=await fetch('../assets/manifest.json');if(!r.ok)throw Error(`HTTP ${r.status}`);manifest=assertManifest(await r.json());}catch(e){$('asset-summary').textContent='清单载入失败：'+e.message;throw e;}
// Prefer already downloaded, checked local bytes; the private manifest is never committed.
try{const r=await fetch('../assets/private/manifest.runtime.json');if(r.ok){const cached=await r.json();for(const row of cached.assets??[]){if(row.status==='bytes-checked'&&/^assets\/private\/[a-z0-9._-]+\.(glb|png|jpe?g)$/.test(row.localPath??'')){const url=new URL('../'+row.localPath,import.meta.url).href;resolved.set(row.id,{...row,status:'indexed',local:true,sourceUrl:url,previewUrl:row.kind==='model'?row.previewUrl:url});}}}}catch{/* Remote resolution remains explicit through the button. */}
const root=$('game-root');
root.addEventListener('selectstart',e=>{if(!e.target?.closest?.('.allow-select,input,textarea,select'))e.preventDefault();});
root.addEventListener('contextmenu',e=>{if(!e.target?.closest?.('.allow-select,input,textarea,select'))e.preventDefault();});
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>{for(const b of document.querySelectorAll('[data-tab]')){const yes=b===button;b.setAttribute('aria-selected',String(yes));$(b.dataset.tab).hidden=!yes;}};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function art(id){const box=el('span','art','未载入');const data=resolved.get(id);if(data?.status==='indexed'){const image=new Image();image.alt=manifest.assets.find(a=>a.id===id)?.label??id;image.onload=()=>box.replaceChildren(image);image.onerror=()=>{box.textContent='图像不可用';box.classList.add('error');};image.src=data.previewUrl;}return box;}
function renderAssets(){const list=manifest.assets.filter(a=>$('filter').value==='all'||a.kind===$('filter').value);$('asset-grid').replaceChildren(...list.map(a=>{const box=el('article','asset');box.append(art(a.id));const info=el('div');info.append(el('strong','',a.label),el('p','muted',a.id));const s=resolved.get(a.id);const text=s?.error?'核对失败：'+s.error:s?.status==='indexed'?'已匹配索引 · 画面待验证':s?.status==='ambiguous'?'候选冲突 · 需人工选择':s?.status==='missing'?'未找到精确条目':a.indexObserved?'已记录索引 · 文件待验证':'待精确匹配';info.append(el('small',s?.error?'error':'status',text));box.append(info);return box;}));$('asset-summary').textContent=`${manifest.assets.length} 项资源 · ${[...resolved.values()].filter(x=>x.status==='indexed').length} 项本次精确匹配 · 0 项被自动认定为原版`;}
$('filter').onchange=renderAssets;renderAssets();
$('resolve').onclick=async()=>{const button=$('resolve');button.disabled=true;const selected=manifest.assets.filter(a=>$('filter').value==='all'||a.kind===$('filter').value);let count=0;await Promise.all(selected.map(async a=>{try{if(!resolved.get(a.id)?.local)resolved.set(a.id,await registry.resolve(a));}catch(e){resolved.set(a.id,{status:'error',error:e.message});}finally{count++;$('progress').style.width=`${100*count/selected.length}%`;}}));renderAssets();renderChoices();button.disabled=false;};
for(const a of manifest.assets.filter(a=>a.id.startsWith('model.')&&a.id!=='model.droppod')){const option=el('option','',a.label);option.value=a.id;$('model-select').append(option);}
let viewer;
$('load-model').onclick=async()=>{const button=$('load-model');button.disabled=true;$('model-status').textContent='核对并载入中…';try{const a=manifest.assets.find(x=>x.id===$('model-select').value);const result=resolved.get(a.id)?.local?resolved.get(a.id):await registry.resolve(a);if(result.status!=='indexed')throw Error('没有唯一的模型索引匹配');resolved.set(a.id,result);const module=await import('../src/ui/model-viewer.mjs');viewer??=await module.createViewer($('model-host'));const summary=await viewer.load(result.sourceUrl);$('model-message')?.remove();$('model-status').textContent='已载入候选模型 · 原版身份仍需人工核对';$('model-log').textContent=JSON.stringify(summary,null,2);$('animation').replaceChildren(...summary.animations.map((name,i)=>{const o=el('option','',name);o.value=String(i);return o;}));$('animation').disabled=!summary.animations.length;if(summary.animations.length)viewer.play(0);renderAssets();}catch(e){$('model-status').textContent='载入失败：'+e.message;$('model-log').textContent='未以几何占位模型替代。请检查来源服务、CORS 和 GLB 完整性。\n'+e.message;}finally{button.disabled=false;}};
$('animation').onchange=()=>viewer?.play(Number($('animation').value));
const pool=[{id:'stim',name:'兴奋剂研发',asset:'tech.stim',text:'验证科技奖励的领取路径。'},{id:'shield',name:'战斗盾牌研发',asset:'tech.shield',text:'验证单位科技图标与奖励映射。'},{id:'infernal',name:'预燃器研发',asset:'tech.infernal',text:'验证机械科技奖励映射。'},{id:'mineral',name:'晶体矿补给',asset:'ui.minerals',text:'测试效果：增加 50 晶体矿。'},{id:'gas',name:'瓦斯补给',asset:'ui.gas',text:'测试效果：增加 15 瓦斯。'},{id:'marine',name:'步兵增援',asset:'unit.marine',text:'验证兵员奖励选择。'}];
let wallet,offer;
function reset(){wallet={minerals:150,gas:25};offer=drawThree(pool,()=>true);$('claim-status').textContent='每回合只能领取一项';renderChoices();}
function renderChoices(){if(!offer)return;$('minerals').textContent=wallet.minerals;$('gas').textContent=wallet.gas;$('choices').replaceChildren(...offer.options.map(c=>{const b=el('button','choice');b.disabled=offer.claimed!==null;b.append(art(c.asset),el('strong','',c.name),el('span','',c.text),el('span','','领取此项'));b.onclick=()=>{const picked=claimOne(offer,c.id);if(!picked)return;if(picked.id==='mineral')wallet.minerals+=50;if(picked.id==='gas')wallet.gas+=15;$('claim-status').textContent='已领取：'+picked.name;renderChoices();};return b;}));$('reroll').disabled=offer.claimed!==null||wallet.minerals<25;}
$('reroll').onclick=()=>{if(rerollThree(offer,pool,()=>true,wallet,{minerals:25,gas:0}))renderChoices();};$('reset-rewards').onclick=reset;reset();
$('font-status').textContent='当前不请求任何远程字体文件。缺少上述本地字体时，浏览器使用系统中文字体与等宽数字回退。';
