import {IDENTITIES,InputError,RACES} from './contracts.mjs';
export function parseFilters(params,now=Date.now(),maxDays=90){
 const day=d=>new Date(d+8*3600000).toISOString().slice(0,10),to=params.get('to')??day(now),from=params.get('from')??day(now-29*86400000);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(from)||!/^\d{4}-\d{2}-\d{2}$/.test(to))throw new InputError();const start=Date.parse(from+'T00:00:00+08:00'),end=Date.parse(to+'T00:00:00+08:00')+86400000;if(!Number.isFinite(start)||!Number.isFinite(end)||day(start)!==from||day(end-86400000)!==to||end<=start||end-start>maxDays*86400000)throw new InputError('range_must_be_1_to_'+maxDays+'_days');
 const f={from,to,start:new Date(start),end:new Date(end),race:params.get('race')??'',difficulty:params.get('difficulty')??'',build:params.get('build')??'',mode:params.get('mode')??'',diagnostic:params.get('diagnostic')==='1',minLevel:Number(params.get('minLevel')??0),maxLevel:Number(params.get('maxLevel')??80)};
 if(f.race&&!RACES.includes(f.race)||f.difficulty&&!['easy','normal','hard','hell'].includes(f.difficulty)||f.mode&&!['campaign','endless'].includes(f.mode)||f.build&&!/^(?:[a-f0-9]{64}|development|local)$/.test(f.build)||!Number.isInteger(f.minLevel)||!Number.isInteger(f.maxLevel)||f.minLevel<0||f.maxLevel>80||f.minLevel>f.maxLevel)throw new InputError();return f;
}
export async function metrics(repo,filters){const key=JSON.stringify(filters),old=repo.cache.get(key);if(old&&old.until>repo.now())return old.data;const p=[filters.start,filters.end,filters.diagnostic],where=['(EXISTS(SELECT 1 FROM events ev WHERE ev.visitor_id=r.visitor_id AND ev.run_id=r.run_id AND ev.occurred_at>=$1 AND ev.occurred_at<$2) OR EXISTS(SELECT 1 FROM stage_summaries ss WHERE ss.visitor_id=r.visitor_id AND ss.run_id=r.run_id AND ss.observed_at>=$1 AND ss.observed_at<$2))','($3::boolean OR NOT r.diagnostic)'];
 for(const [k,col]of [['race','race'],['difficulty','difficulty'],['build','build']])if(filters[k]){p.push(filters[k]);where.push(`r.${col}=$${p.length}`);}p.push(filters.minLevel,filters.maxLevel);where.push(`r.player_level BETWEEN $${p.length-1} AND $${p.length}`);if(filters.mode){p.push(filters.mode);where.push('EXISTS(SELECT 1 FROM stage_summaries ss WHERE ss.visitor_id=r.visitor_id AND ss.run_id=r.run_id AND ss.mode=$'+p.length+')');}const rw=where.join(' AND '),q=(sql,args=p)=>repo.db.query(sql,args).then(r=>r.rows);
 const runFilter=filters.race||filters.difficulty||filters.minLevel>0||filters.maxLevel<80,ep=[filters.start,filters.end,filters.diagnostic],ew=['e.occurred_at>=$1','e.occurred_at<$2','($3::boolean OR NOT e.diagnostic)','($3::boolean OR NOT EXISTS(SELECT 1 FROM sessions sx WHERE sx.id=e.session_id AND sx.diagnostic))','($3::boolean OR NOT EXISTS(SELECT 1 FROM run_summaries rx WHERE rx.visitor_id=e.visitor_id AND rx.run_id=e.run_id AND rx.diagnostic))'];if(filters.build){ep.push(filters.build);ew.push(`e.build=$${ep.length}`);}if(runFilter){ep.push(filters.race,filters.difficulty,filters.minLevel,filters.maxLevel);ew.push(`EXISTS(SELECT 1 FROM run_summaries r WHERE r.visitor_id=e.visitor_id AND r.run_id=e.run_id AND ($${ep.length-3}='' OR r.race=$${ep.length-3}) AND ($${ep.length-2}='' OR r.difficulty=$${ep.length-2}) AND r.player_level BETWEEN $${ep.length-1} AND $${ep.length})`);}if(filters.mode){ep.push(filters.mode);ew.push(`e.data->>'mode'=$${ep.length}`);}const visits=`SELECT DISTINCT e.visitor_id,e.session_id,(e.occurred_at AT TIME ZONE 'Asia/Shanghai')::date AS day FROM events e WHERE ${ew.join(' AND ')}`;
 const daily=await q(`WITH visits AS (${visits}) SELECT day::text,count(DISTINCT visitor_id)::int AS browsers,count(DISTINCT session_id)::int AS sessions FROM visits GROUP BY day ORDER BY day`,ep),summary=(await q(`SELECT count(*)::int AS runs,count(DISTINCT r.visitor_id)::int AS run_browsers,count(*) FILTER(WHERE started_at IS NOT NULL)::int AS starts,count(*) FILTER(WHERE ended_at IS NOT NULL)::int AS ended,count(*) FILTER(WHERE ended_at IS NULL)::int AS unfinished,COALESCE(sum(seconds),0)::float8 AS observed_seconds FROM run_summaries r WHERE ${rw}`))[0];
 const until=new Date(filters.end).getTime(),active=[];for(const n of [1,7,30]){const t=new Date(Math.max(new Date(filters.start).getTime(),until-n*86400000));active.push((await q(`WITH visits AS (${visits}) SELECT count(DISTINCT visitor_id)::int AS n FROM visits WHERE day>=($${ep.length+1}::timestamptz AT TIME ZONE 'Asia/Shanghai')::date`,[...ep,t]))[0].n);}Object.assign(summary,{dau:active[0],wau:active[1],mau:active[2]});
 const audience=(await q(`WITH visits AS (${visits}) SELECT count(DISTINCT v.id) FILTER(WHERE v.created_at >= $1)::int AS new_browsers,count(DISTINCT v.id) FILTER(WHERE v.created_at < $1)::int AS returning_browsers,count(DISTINCT x.session_id)::int AS sessions FROM visits x JOIN visitors v ON v.id=x.visitor_id`,ep))[0];Object.assign(summary,audience);
 const retention=[];for(const days of [1,7,30]){const rows=await q(`WITH visits AS (${visits}),cohort AS (SELECT DISTINCT v.id,(v.created_at AT TIME ZONE 'Asia/Shanghai')::date AS first_day FROM visitors v JOIN visits x ON x.visitor_id=v.id WHERE v.created_at>=$1 AND v.created_at<$2 AND v.created_at<$${ep.length+1}) SELECT count(*)::int AS eligible,count(*) FILTER(WHERE EXISTS(SELECT 1 FROM visits x WHERE x.visitor_id=cohort.id AND x.day=cohort.first_day+$${ep.length+2}::integer))::int AS returned FROM cohort`,[...ep,new Date(Math.min(Date.parse(new Date(repo.now()+8*3600000).toISOString().slice(0,10)+'T00:00:00+08:00'),until)-days*86400000),days]);retention.push({days,...rows[0],rate:rows[0].eligible?rows[0].returned/rows[0].eligible:null});}
 const sp=[...p],sw=[rw,'s.observed_at>=$1','s.observed_at<$2'];if(filters.mode){sp.push(filters.mode);sw.push(`s.mode=$${sp.length}`);}const source=`FROM stage_summaries s JOIN run_summaries r USING(visitor_id,run_id) WHERE ${sw.join(' AND ')}`;
 const funnel=await q(`SELECT s.mode,s.stage,r.race,r.difficulty,count(*)::int AS samples,count(*) FILTER(WHERE s.data->>'status' IN ('cleared','won','evacuated'))::int AS cleared,count(*) FILTER(WHERE s.data->>'status'='failed')::int AS failed,count(*) FILTER(WHERE s.data->>'status' IN ('incomplete','reached'))::int AS unfinished ${source} GROUP BY s.mode,s.stage,r.race,r.difficulty ORDER BY s.mode,s.stage,r.race,r.difficulty LIMIT 500`,sp);
 const stages=await q(`SELECT s.data,r.run_id,r.visitor_id ${source}`,sp),use=new Map(),contributors=new Map(),sampleRuns=new Set();for(const s of stages){const run=s.visitor_id+':'+s.run_id;sampleRuns.add(run);for(const row of s.data.roster??[]){const a=use.get(row.id)??{runs:new Set(),maxRank:0,campaign:0,endless:0};a.runs.add(run);a.maxRank=Math.max(a.maxRank,row.rank);a[s.data.mode]=Math.max(a[s.data.mode],s.data.stage);use.set(row.id,a);}for(const row of s.data.contributions??[]){const a=contributors.get(row.id)??{damage:0,healed:0,shieldRestored:0,deaths:0,revivals:0,stages:0};for(const k of ['damage','healed','shieldRestored','deaths','revivals'])a[k]+=row[k]??0;a.stages++;contributors.set(row.id,a);}}
 const usage=[...IDENTITIES].map(id=>({id,runs:use.get(id)?.runs.size??0,maxRank:use.get(id)?.maxRank??0,highestCampaign:use.get(id)?.campaign??0,highestEndless:use.get(id)?.endless??0,denominator:sampleRuns.size,damage:contributors.get(id)?.damage??0,healed:contributors.get(id)?.healed??0,shieldRestored:contributors.get(id)?.shieldRestored??0,deaths:contributors.get(id)?.deaths??0,revivals:contributors.get(id)?.revivals??0,observedStages:contributors.get(id)?.stages??0}));
 const builds=buildSummaries(stages,sampleRuns.size);
 const cards=await q(`SELECT e.data->>'id' AS id,e.data->>'action' AS action,e.data->>'quality' AS quality,(e.data->>'level')::integer AS level,count(*)::int AS samples,COALESCE(sum((e.data->>'minerals')::float8),0)::float8 AS minerals,COALESCE(sum((e.data->>'gas')::float8),0)::float8 AS gas FROM events e WHERE ${ew.join(' AND ')} AND e.kind='card' GROUP BY e.data->>'id',e.data->>'action',e.data->>'quality',e.data->>'level' ORDER BY samples DESC`,ep);
 const load=await q(`SELECT (e.data->>'cold')::boolean AS cold,count(*)::int AS samples,avg((e.data->>'milliseconds')::float8)::float8 AS mean_ms,sum((e.data->>'networkBytes')::float8)::float8 AS network_bytes,sum((e.data->>'failures')::float8)::float8 AS failures,avg((e.data->>'parseMs')::float8)::float8 AS parse_ms,avg((e.data->>'gpuMs')::float8)::float8 AS gpu_ms,sum((e.data->>'cacheHits')::float8)::float8 AS cache_hits,sum((e.data->>'cacheMisses')::float8)::float8 AS cache_misses FROM events e WHERE ${ew.join(' AND ')} AND e.kind='load' GROUP BY e.data->>'cold'`,ep);
 const performance=await q(`SELECT s.mode,count(*)::int AS samples,avg((s.data->'performance'->>'p95')::float8)::float8 AS mean_stage_p95,avg((s.data->'performance'->>'p99')::float8)::float8 AS mean_stage_p99,max((s.data->'performance'->>'p99')::float8)::float8 AS worst_stage_p99,sum((s.data->'performance'->>'longFrames')::float8)::float8 AS long_frames,sum((s.data->'performance'->>'frames')::float8)::float8 AS frames,max((s.data->'performance'->>'peakUnits')::float8)::float8 AS peak_units,max((s.data->'performance'->>'backlogDelta')::float8)::float8 AS backlog_delta ${source} GROUP BY s.mode`,sp);
 const result={filters:{...filters,start:filters.start.toISOString(),end:filters.end.toISOString()},summary,daily,retention,funnel,usage,builds,cards,load,performance,sampleRuns:sampleRuns.size,partialStages:stages.filter(s=>s.data.partial).length,notes:['仅明确授权的浏览器样本；浏览器不是自然人，不计算全站同意率。','日期为Asia/Shanghai；开发、锁血和诊断导入默认排除。','继续读档沿用战局ID；未结束战局为未完成，不记为失败。','战局汇总为区间内有活动战局的累计观察值；关卡按最后摘要时间筛选。','搭配指同一观察阶段出现，不保证同时在场；相关性不代表因果。','无来源的实际恢复归入unattributed或natural_regeneration，不按阵容猜测归因。','帧时为各已观察关卡的P95/P99汇总，不是将所有原始帧合并后的分位数。']};if(repo.cache.size>=50)repo.cache.delete(repo.cache.keys().next().value);repo.cache.set(key,{until:repo.now()+30000,data:result});return result;
}
function buildSummaries(stages,denominator){const groups=new Map();function add(kind,id,level,s){const key=JSON.stringify([kind,id,level]),a=groups.get(key)??{kind,id,level,runs:new Set(),highestCampaign:0,highestEndless:0};a.runs.add(s.visitor_id+':'+s.run_id);const field=s.data.mode==='endless'?'highestEndless':'highestCampaign';a[field]=Math.max(a[field],s.data.stage);groups.set(key,a);}for(const s of stages){const ids=(s.data.roster??[]).map(r=>r.id).sort();for(let i=0;i<ids.length;i++)for(let j=i+1;j<ids.length;j++)add('pair',ids[i]+' + '+ids[j],0,s);for(const kind of ['talents','research'])for(const [id,level]of Object.entries(s.data[kind]??{}))if(level>0)add(kind,id,level,s);}return [...groups.values()].map(a=>({...a,runs:a.runs.size,denominator})).sort((a,b)=>b.runs-a.runs||a.id.localeCompare(b.id)).slice(0,500);}
export async function archivedDaily(repo,filters){const p=[filters.from,filters.to],where=['day >= $1::date','day <= $2::date'];if(filters.build){p.push(filters.build);where.push(`dimensions::jsonb->>'build'=$${p.length}`);}if(!filters.diagnostic)where.push("NOT (dimensions::jsonb->>'diagnostic')::boolean");const rows=(await repo.db.query('SELECT day::text,dimensions::jsonb AS dimensions,data FROM daily_metrics WHERE '+where.join(' AND ')+' ORDER BY day,dimensions',p)).rows;return rows.map(r=>({day:r.day,build:r.dimensions.build,diagnostic:r.dimensions.diagnostic,...r.data}));}
export async function refreshDaily(repo){const rows=(await repo.db.query(`SELECT (occurred_at AT TIME ZONE 'Asia/Shanghai')::date AS day,build,diagnostic,count(DISTINCT visitor_id)::int AS browsers,count(DISTINCT session_id)::int AS sessions,count(*) FILTER(WHERE kind='run_start')::int AS starts FROM events WHERE received_at >= $1 GROUP BY day,build,diagnostic`,[new Date(repo.now()-90*86400000)])).rows;await repo.db.transaction(async tx=>{await tx.query('DELETE FROM daily_metrics WHERE day >= ($1::timestamptz AT TIME ZONE \'Asia/Shanghai\')::date',[new Date(repo.now()-90*86400000)]);for(const r of rows)await tx.query('INSERT INTO daily_metrics(day,dimensions,data,updated_at) VALUES($1,$2,$3::jsonb,$4)',[r.day,JSON.stringify({build:r.build,diagnostic:r.diagnostic}),JSON.stringify({browsers:r.browsers,sessions:r.sessions,starts:r.starts}),new Date(repo.now())]);});return {days:rows.length};}
