import {randomUUID} from 'node:crypto';import {CONSENT_VERSION,RETENTION,InputError,validateEvent,validateFeedback} from './contracts.mjs';import {hash,equal,passwordHash,passwordMatches,token} from './security.mjs';
import fs from 'node:fs/promises';import path from 'node:path';
const json=v=>JSON.stringify(v),dayMs=86400000;
export class ApiError extends Error {constructor(status,code){super(code);this.status=status;this.code=code;}}
const deny=()=>{throw new ApiError(401,'credential_invalid');};
function mergeStage(a,b){if(!a)return b;const next={...b};for(const k of ['seconds','damage','healed','shieldRestored','deaths','revivals','kills'])next[k]=Math.max(a[k]??0,b[k]??0);const priority={incomplete:0,reached:0,failed:1,cleared:2,won:2,evacuated:2};if(priority[a.status]>priority[b.status])next.status=a.status;next.partial=a.partial||b.partial;const contributions=new Map((a.contributions??[]).map(v=>[v.id,v]));for(const row of b.contributions??[]){const old=contributions.get(row.id)??{};contributions.set(row.id,{id:row.id,...Object.fromEntries(['damage','healed','shieldRestored','deaths','revivals'].map(k=>[k,Math.max(old[k]??0,row[k]??0)]))});}next.contributions=[...contributions.values()];return next;}
export class Repository {
 constructor(db,{backupDays=30,now=()=>Date.now(),journal}={}){this.db=db;this.backupDays=backupDays;this.now=now;this.journal=journal;this.cache=new Map();}
 invalidate(){this.cache.clear();}
 async grant({visitorId,privacySecret,consentId,uploadToken,version}){if(version!==CONSENT_VERSION)throw new ApiError(409,'consent_version_changed');const privacyHash=hash(privacySecret),uploadHash=hash(uploadToken);return this.db.transaction(async tx=>{
  await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['visitor:'+visitorId]);
  if((await tx.query('SELECT 1 FROM deletion_manifest WHERE subject_hash=$1 AND scope=$2',[hash(visitorId),'visitor'])).rows.length)throw new ApiError(409,'identity_deleted');
  await tx.query('INSERT INTO visitors(id,privacy_hash,created_at,last_seen) VALUES($1,$2,$3,$3) ON CONFLICT DO NOTHING',[visitorId,privacyHash,new Date(this.now())]);const v=(await tx.query('SELECT privacy_hash FROM visitors WHERE id=$1 FOR UPDATE',[visitorId])).rows[0];if(!v||!equal(v.privacy_hash,privacyHash))deny();
  if((await tx.query('SELECT 1 FROM deletion_manifest WHERE subject_hash=$1 AND scope=$2',[hash(visitorId),'visitor'])).rows.length)throw new ApiError(409,'identity_deleted');
  const existing=(await tx.query('SELECT * FROM consent_records WHERE id=$1',[consentId])).rows[0];if(existing){if(existing.visitor_id!==visitorId||existing.revoked_at||!equal(existing.upload_hash,uploadHash))deny();return {version,granted:true};}
  await tx.query('UPDATE consent_records SET revoked_at=$2 WHERE visitor_id=$1 AND revoked_at IS NULL',[visitorId,new Date(this.now())]);await tx.query('INSERT INTO consent_records(id,visitor_id,version,upload_hash,granted_at) VALUES($1,$2,$3,$4,$5)',[consentId,visitorId,version,uploadHash,new Date(this.now())]);return {version,granted:true};
 });}
 async credential(uploadToken,tx=this.db){const row=(await tx.query('SELECT id,visitor_id,granted_at FROM consent_records WHERE upload_hash=$1 AND revoked_at IS NULL AND version=$2',[hash(uploadToken),CONSENT_VERSION])).rows[0];if(!row)deny();await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['visitor:'+row.visitor_id]);if(!(await tx.query('SELECT id FROM visitors WHERE id=$1 FOR UPDATE',[row.visitor_id])).rows.length)deny();const active=(await tx.query('SELECT id,visitor_id,granted_at FROM consent_records WHERE id=$1 AND revoked_at IS NULL FOR UPDATE',[row.id])).rows[0];if(!active)deny();return active;}
 async batch(uploadToken,values){if(!Array.isArray(values)||values.length<1||values.length>32)throw new InputError();const events=values.map(v=>validateEvent(v,this.now()));const out=await this.db.transaction(async tx=>{
  const consent=await this.credential(uploadToken,tx),accepted=[];for(const e of events){if(e.at<new Date(consent.granted_at).getTime()-300000)throw new InputError('event_predates_consent');
   const at=new Date(e.at),s=await tx.query('INSERT INTO sessions(id,visitor_id,started_at,last_at,build,release,device,orientation,animation,diagnostic) VALUES($1,$2,$3,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(id) DO UPDATE SET last_at=GREATEST(sessions.last_at,EXCLUDED.last_at),diagnostic=sessions.diagnostic OR EXCLUDED.diagnostic WHERE sessions.visitor_id=EXCLUDED.visitor_id RETURNING id,diagnostic',[e.sessionId,consent.visitor_id,at,e.build,e.release,e.device,e.orientation,e.animation,e.diagnostic]);if(!s.rows.length)throw new ApiError(409,'session_conflict');e.diagnostic=!!s.rows[0].diagnostic;if(e.diagnostic){await tx.query('UPDATE events SET diagnostic=true WHERE session_id=$1 AND NOT diagnostic',[e.sessionId]);await tx.query('UPDATE run_summaries r SET diagnostic=true WHERE NOT diagnostic AND EXISTS(SELECT 1 FROM events e WHERE e.session_id=$1 AND e.visitor_id=r.visitor_id AND e.run_id=r.run_id)',[e.sessionId]);}
   const insert=await tx.query('INSERT INTO events(visitor_id,event_id,consent_id,session_id,run_id,kind,occurred_at,received_at,build,release,diagnostic,data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ON CONFLICT DO NOTHING RETURNING event_id',[consent.visitor_id,e.id,consent.id,e.sessionId,e.runId,e.kind,at,new Date(this.now()),e.build,e.release,e.diagnostic,json(e.data)]);accepted.push(e.id);if(!insert.rows.length&&!['stage_summary','run_end'].includes(e.kind))continue;
   if(['run_start','run_resume','stage_summary','run_end','heartbeat'].includes(e.kind)){const d=e.data,ended=e.kind==='run_end',status=ended?d.status:'incomplete';await tx.query(`INSERT INTO run_summaries(visitor_id,run_id,started_at,last_at,ended_at,race,difficulty,build,diagnostic,seconds,highest_stage,highest_round,player_level,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT(visitor_id,run_id) DO UPDATE SET started_at=COALESCE(run_summaries.started_at,EXCLUDED.started_at),last_at=GREATEST(run_summaries.last_at,EXCLUDED.last_at),ended_at=COALESCE(EXCLUDED.ended_at,run_summaries.ended_at),seconds=GREATEST(run_summaries.seconds,EXCLUDED.seconds),highest_stage=GREATEST(run_summaries.highest_stage,EXCLUDED.highest_stage),highest_round=GREATEST(run_summaries.highest_round,EXCLUDED.highest_round),player_level=GREATEST(run_summaries.player_level,EXCLUDED.player_level),diagnostic=run_summaries.diagnostic OR EXCLUDED.diagnostic,status=CASE WHEN EXCLUDED.ended_at IS NOT NULL THEN EXCLUDED.status ELSE run_summaries.status END`,[consent.visitor_id,e.runId,e.kind==='run_start'?at:null,at,ended?at:null,d.race,d.difficulty,e.build,e.diagnostic,d.runSeconds,d.mode==='campaign'?d.stage:1,d.mode==='endless'?d.stage:0,d.playerLevel,status]);
    if(e.kind==='stage_summary'||e.kind==='run_end'){const prior=(await tx.query('SELECT data FROM stage_summaries WHERE visitor_id=$1 AND run_id=$2 AND mode=$3 AND stage=$4 FOR UPDATE',[consent.visitor_id,e.runId,d.mode,d.stage])).rows[0]?.data;await tx.query('INSERT INTO stage_summaries(visitor_id,run_id,mode,stage,observed_at,data) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT(visitor_id,run_id,mode,stage) DO UPDATE SET observed_at=EXCLUDED.observed_at,data=EXCLUDED.data',[consent.visitor_id,e.runId,d.mode,d.stage,at,json(mergeStage(prior,d))]);}
   }
  }await tx.query('UPDATE visitors SET last_seen=GREATEST(last_seen,$2) WHERE id=$1',[consent.visitor_id,new Date(Math.max(...events.map(e=>e.at)))]);return {accepted};});this.invalidate();return out;
 }
 async privacy(visitorId,privacySecret,remove=false){await this.db.transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['visitor:'+visitorId]);const v=(await tx.query('SELECT privacy_hash FROM visitors WHERE id=$1 FOR UPDATE',[visitorId])).rows[0];if(!v){if(remove){await this.tombstone(tx,visitorId,'visitor');return;}deny();}if(!equal(v.privacy_hash,hash(privacySecret)))deny();if(remove){await this.tombstone(tx,visitorId,'visitor');await tx.query('DELETE FROM visitors WHERE id=$1',[visitorId]);}else await tx.query('UPDATE consent_records SET revoked_at=$2 WHERE visitor_id=$1 AND revoked_at IS NULL',[visitorId,new Date(this.now())]);});this.invalidate();return {deleted:remove,withdrawn:true};}
 async tombstone(tx,id,scope){const row={subject_hash:hash(id),scope,deleted_at:new Date(this.now()).toISOString(),expires_at:new Date(this.now()+(this.backupDays+1)*dayMs).toISOString()};if(this.journal){await fs.mkdir(path.dirname(this.journal),{recursive:true});const file=await fs.open(this.journal,'a',0o600);try{await file.write(JSON.stringify(row)+'\n');await file.sync();}finally{await file.close();}}await tx.query('INSERT INTO deletion_manifest(subject_hash,scope,deleted_at,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT(subject_hash) DO UPDATE SET expires_at=GREATEST(deletion_manifest.expires_at,EXCLUDED.expires_at)',[row.subject_hash,scope,row.deleted_at,row.expires_at]);}
 async submitFeedback(value){const d=validateFeedback(value);return this.db.transaction(async tx=>{await tx.query('LOCK TABLE feedback IN SHARE ROW EXCLUSIVE MODE');if((await tx.query('SELECT 1 FROM deletion_manifest WHERE subject_hash=$1',[hash(d.id)])).rows.length)throw new ApiError(409,'feedback_deleted');const result=await tx.query('INSERT INTO feedback(id,receipt_hash,category,body,contact,summary,created_at,updated_at,consent_version) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7,$7,$8) ON CONFLICT DO NOTHING RETURNING id',[d.id,hash(d.receipt),d.category,d.text,d.contact,json(d.summary),new Date(this.now()),d.consentVersion]);if(!result.rows.length){const previous=(await tx.query('SELECT receipt_hash FROM feedback WHERE id=$1',[d.id])).rows[0];if(!previous||!equal(previous.receipt_hash,hash(d.receipt)))deny();}return {id:d.id,received:true};});}
 async feedbackForReceipt(id,receipt,remove=false){return this.db.transaction(async tx=>{if(remove)await tx.query('LOCK TABLE feedback IN SHARE ROW EXCLUSIVE MODE');const r=(await tx.query('SELECT * FROM feedback WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r)throw new ApiError(404,'feedback_not_found');if(!equal(r.receipt_hash,hash(receipt)))deny();if(remove){await this.tombstone(tx,id,'feedback');await tx.query('DELETE FROM feedback WHERE id=$1',[id]);return {deleted:true};}return {id:r.id,category:r.category,text:r.body,contact:r.contact,summary:r.summary,status:r.status,createdAt:r.created_at};});}
 async createAdmin(username,password,canExportContacts=false){if(!/^[a-z0-9][a-z0-9._-]{2,39}$/i.test(username))throw new InputError('invalid_admin_name');const encoded=await passwordHash(password);await this.db.query('INSERT INTO admin_users(id,username,password_hash,can_export_contacts) VALUES($1,$2,$3,$4)',[randomUUID(),username.toLowerCase(),encoded,canExportContacts]);}
 async login(username,password){const key=hash(String(username).toLowerCase());const gate=(await this.db.query('SELECT * FROM auth_throttles WHERE key=$1',[key])).rows[0];if(gate?.blocked_until&&new Date(gate.blocked_until).getTime()>this.now())throw new ApiError(429,'login_limited');const user=(await this.db.query('SELECT * FROM admin_users WHERE username=$1',[String(username).toLowerCase()])).rows[0];
  // Missing names use the same expensive derivation, avoiding a fast username oracle.
  const dummy='scrypt$131072$8$1$U2MyTG9naW5UaW1pbmcwMQ$'+'A'.repeat(86);const matches=await passwordMatches(password,user?.password_hash??dummy);if(!user||user.disabled||!matches){await this.db.query(`INSERT INTO auth_throttles(key,failures,window_start,blocked_until) VALUES($1,1,$2,NULL) ON CONFLICT(key) DO UPDATE SET failures=CASE WHEN auth_throttles.window_start<$3 THEN 1 ELSE auth_throttles.failures+1 END,window_start=CASE WHEN auth_throttles.window_start<$3 THEN $2 ELSE auth_throttles.window_start END,blocked_until=CASE WHEN auth_throttles.window_start>=$3 AND auth_throttles.failures>=4 THEN $4::timestamptz ELSE NULL END`,[key,new Date(this.now()),new Date(this.now()-900000),new Date(this.now()+900000)]);throw new ApiError(401,'login_failed');}
  const session=token(),csrf=token();await this.db.transaction(async tx=>{await tx.query('DELETE FROM auth_throttles WHERE key=$1',[key]);await tx.query('INSERT INTO admin_sessions(token_hash,user_id,csrf_hash,created_at,last_seen,expires_at) VALUES($1,$2,$3,$4,$4,$5)',[hash(session),user.id,hash(csrf),new Date(this.now()),new Date(this.now()+8*3600000)]);await this.audit(user.id,'login',{},tx);});return {session,csrf,user:{username:user.username,canExportContacts:user.can_export_contacts}};
 }
 async admin(session,csrf,mutating=false){if(!session)deny();const row=(await this.db.query('SELECT s.*,u.username,u.can_export_contacts,u.disabled FROM admin_sessions s JOIN admin_users u ON u.id=s.user_id WHERE s.token_hash=$1',[hash(session)])).rows[0];if(!row||row.disabled||new Date(row.expires_at).getTime()<=this.now()||new Date(row.last_seen).getTime()<this.now()-1800000)deny();if(mutating&&(!csrf||!equal(hash(csrf),row.csrf_hash)))throw new ApiError(403,'csrf_invalid');await this.db.query('UPDATE admin_sessions SET last_seen=$2 WHERE token_hash=$1',[hash(session),new Date(this.now())]);return {id:row.user_id,username:row.username,canExportContacts:row.can_export_contacts};}
 async logout(session,user){await this.db.query('DELETE FROM admin_sessions WHERE token_hash=$1',[hash(session)]);await this.audit(user.id,'logout');}
 async audit(id,action,details={},tx=this.db){await tx.query('INSERT INTO admin_audit(user_id,action,details,created_at) VALUES($1,$2,$3::jsonb,$4)',[id,action,json(details),new Date(this.now())]);}
 async feedbackList(filters={}){const values=[],where=[];for(const [key,column]of [['category','category'],['status','status'],['build',"summary->>'build'"]])if(filters[key]){values.push(filters[key]);where.push(column+'=$'+values.length);}if(filters.from){values.push(filters.from);where.push('created_at >= $'+values.length+'::timestamptz');}if(filters.to){values.push(filters.to);where.push('created_at < $'+values.length+'::timestamptz');}return (await this.db.query('SELECT id,category,body,summary,created_at,updated_at,status,priority,tags,admin_note,(contact <> \'\') AS has_contact FROM feedback'+(where.length?' WHERE '+where.join(' AND '):'')+' ORDER BY created_at DESC LIMIT 500',values)).rows;}
 async updateFeedback(id,changes,user){const r=await this.db.query('UPDATE feedback SET status=$2,priority=$3,tags=$4::jsonb,admin_note=$5,updated_at=$6 WHERE id=$1 RETURNING id',[id,changes.status,changes.priority,json(changes.tags),changes.note,new Date(this.now())]);if(!r.rows.length)throw new ApiError(404,'feedback_not_found');await this.audit(user.id,'feedback_update',{id,status:changes.status,priority:changes.priority});return {updated:true};}
 async contacts(ids,user){if(!user.canExportContacts)throw new ApiError(403,'contact_export_forbidden');if(!Array.isArray(ids)||ids.length>500)throw new InputError();const rows=(await this.db.query('SELECT id,contact FROM feedback WHERE id=ANY($1::uuid[]) ORDER BY created_at DESC',[ids])).rows;await this.audit(user.id,'contact_export',{count:rows.length,ids});return rows;}
 async maintenance(){const now=this.now();await this.db.transaction(async tx=>{for(const [table,column,days]of [['events','received_at',RETENTION.events],['sessions','last_at',RETENTION.events],['run_summaries','last_at',RETENTION.runs],['visitors','last_seen',RETENTION.visitors],['daily_metrics','day',RETENTION.daily],['feedback','created_at',RETENTION.feedback],['admin_audit','created_at',RETENTION.audit],['consent_records','revoked_at',RETENTION.events]])await tx.query(`DELETE FROM ${table} WHERE ${column} < $1`,[new Date(now-days*dayMs)]);await tx.query('DELETE FROM admin_sessions WHERE expires_at<$1 OR last_seen<$2',[new Date(now),new Date(now-1800000)]);await tx.query('DELETE FROM auth_throttles WHERE window_start<$1',[new Date(now-dayMs)]);await tx.query('DELETE FROM deletion_manifest WHERE expires_at<$1',[new Date(now)]);});this.invalidate();return {retention:RETENTION};}
 async exportDeletionManifest(){return (await this.db.query('SELECT subject_hash,scope,deleted_at,expires_at FROM deletion_manifest ORDER BY deleted_at')).rows;}
 async replayDeletionManifest(rows){if(!Array.isArray(rows)||rows.length>1000000)throw new InputError();const wanted=new Set();for(const r of rows){if(!/^[a-f0-9]{64}$/.test(r.subject_hash)||!['visitor','feedback'].includes(r.scope)||!Number.isFinite(Date.parse(r.expires_at))||!Number.isFinite(Date.parse(r.deleted_at)))throw new InputError();wanted.add(r.scope+':'+r.subject_hash);}let deleted=0;await this.db.transaction(async tx=>{for(const scope of ['visitor','feedback']){const table=scope==='visitor'?'visitors':'feedback';let after='00000000-0000-0000-0000-000000000000';for(;;){const ids=(await tx.query(`SELECT id FROM ${table} WHERE id>$1::uuid ORDER BY id LIMIT 1000`,[after])).rows;if(!ids.length)break;for(const {id}of ids)if(wanted.has(scope+':'+hash(id))){await tx.query(`DELETE FROM ${table} WHERE id=$1`,[id]);deleted++;}after=ids.at(-1).id;}}for(const r of rows)await tx.query('INSERT INTO deletion_manifest(subject_hash,scope,deleted_at,expires_at) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[r.subject_hash,r.scope,r.deleted_at,r.expires_at]);});this.invalidate();return {deleted};}
}
