import {createHash,randomBytes,scrypt,timingSafeEqual} from 'node:crypto';import {promisify} from 'node:util';
import path from 'node:path';
const derive=promisify(scrypt);export const hash=value=>createHash('sha256').update(value).digest('hex');export const token=()=>randomBytes(32).toString('base64url');
let passwordJobs=0;
export async function boundedPasswordWork(fn){if(passwordJobs>=2){const error=Error('login_busy');error.status=429;error.code='login_busy';throw error;}passwordJobs++;try{return await fn();}finally{passwordJobs--;}}
export function equal(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y);}
export async function passwordHash(password){if(typeof password!=='string'||password.length<14||password.length>256)throw Error('password_must_be_14_to_256_characters');const salt=randomBytes(16).toString('base64url'),key=await derive(password,salt,64,{N:131072,r:8,p:1,maxmem:192*1024*1024});return `scrypt$131072$8$1$${salt}$${key.toString('base64url')}`;}
export async function passwordMatches(password,stored){if(typeof password!=='string'||password.length>256)return false;const [alg,n,r,p,salt,key]=String(stored).split('$');if(alg!=='scrypt'||n!=='131072'||r!=='8'||p!=='1'||!salt||!key)return false;const derived=await derive(password,salt,64,{N:131072,r:8,p:1,maxmem:192*1024*1024});return equal(derived.toString('base64url'),key);}
/** Ephemeral request throttling: no IP or request address is persisted or exported. */
export class RateLimiter {buckets=new Map();secret=token();allow(key,limit,windowMs,now=Date.now()){const id=hash(this.secret+key),old=this.buckets.get(id);if(!old&&this.buckets.size>=10000){for(const [k,v]of this.buckets)if(v.until<=now)this.buckets.delete(k);if(this.buckets.size>=10000)return false;}const b=old&&old.until>now?old:{n:0,until:now+windowMs};b.n++;this.buckets.set(id,b);return b.n<=limit;}}
export const csvCell=value=>'"'+String(value??'').replace(/^[\s]*[=+@-]/,m=>"'"+m).replaceAll('"','""')+'"';
export function configFromEnv(env=process.env){const enabled=env.SC2_BACKEND_ENABLED==='1',local=env.SC2_LOCAL_DEV==='1';if(!enabled)return {enabled:false,local};const origin=new URL(env.SC2_PUBLIC_ORIGIN??'');if(origin.origin!==env.SC2_PUBLIC_ORIGIN||origin.username||origin.password||origin.protocol!=='https:'&&!(local&&origin.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(origin.hostname)))throw Error('backend_origin_requires_https_or_explicit_loopback');const operator=env.SC2_PRIVACY_OPERATOR?.trim(),contact=env.SC2_PRIVACY_CONTACT?.trim(),backupDays=Number(env.SC2_BACKUP_RETENTION_DAYS);if(!operator||operator.length>120||!contact||contact.length>200||!Number.isInteger(backupDays)||backupDays<1||backupDays>365)throw Error('privacy_operator_contact_and_backup_days_required');if(!env.DATABASE_URL&&!(local&&env.SC2_PGLITE_DIR))throw Error('persistent_postgres_required');const journal=env.SC2_DELETION_JOURNAL??(local&&env.SC2_PGLITE_DIR?path.resolve(env.SC2_PGLITE_DIR,'../deletions.jsonl'):null);if(!journal||!path.isAbsolute(journal))throw Error('independent_deletion_journal_path_required');return {enabled:true,local,origin:origin.origin,secure:origin.protocol==='https:',operator,contact,backupDays,journal,url:env.DATABASE_URL,localDirectory:env.SC2_PGLITE_DIR};}
