import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {World} from '../../src/simulation/world';
import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {FixedStepper} from '../../src/simulation/fixed-stepper';
import {AnimatedBatch} from '../../src/render/units/animated-batch';
import {restoreSc2Materials} from '../../src/render/loaders/sc2-materials';
import {ELITES,type EliteId} from '../../src/data/elites';
import {SC2_UNITS,HEAL} from '../../src/data/sc2-units';
import {ALL_FAMILIES,FAMILIES_BY_RACE,RACE_NAMES,type FamilyId,type Race} from '../../src/data/races';
import {UNIQUE_SUPPORT,type UniqueSupportId} from '../../src/data/unique-support';
import {buySupport,type SupportCard} from '../../src/simulation/combat/shop-support';
import {initializeCarrierSubsystem,ownedInterceptors} from '../../src/simulation/combat/carriers';
import {ASSETS,assetUrl} from '../../src/assets/manifest';
import {loadEmbeddedAssets,prepareEmbeddedAssetIds} from '../../src/assets/offline-pack';
import {RUN_SCHEMA,type RunSnapshot} from '../../src/simulation/persistence/run-snapshot';
import {encodeGraph} from '../../src/persistence/graph-codec';
import {ordinaryEmissionScale} from '../../src/render/effects/ordinary-presentation';
import type {Entity} from '../../src/simulation/types';

const $=(id:string)=>document.getElementById(id)!;
const selected=new Set<string>(JSON.parse($('demo-assets').textContent!));for(const id of ASSETS.keys())if(!selected.has(id))ASSETS.delete(id);
const w=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10604}),canvas=$('battle')as HTMLCanvasElement,view=new BattleRenderer(canvas,w);view.cameraShake=false;
let race:Race='terran',family:FamilyId='marine',rank=1,variant='ordinary',scene='single',card:SupportCard='mines',level=1,scenario='group',ready=false,busy=false,source=0,last=performance.now(),zoom=1.8,saved:RunSnapshot|null=null,sources:number[]=[];
let targets:number[]=[];const common={mines:['追踪蜘蛛雷','虫巢地雷','静滞地雷'],bombardment:['空中轰炸','孢子轰击','轨道轰击'],mutation:['燃烧弹','毒性强化','灵能注入'],strategic:['战术核弹','孢子炸弹','净化打击']}as const;
function resize(){view.resize();const portrait=canvas.clientWidth<canvas.clientHeight;view.camera.zoom=portrait?(scene==='compare'?1.15:1.45):scene==='compare'?.88:scene==='mixed'?1.2:zoom;const shift=portrait?3.2:0;view.camera.left+=shift;view.camera.right+=shift;view.camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function enemy(x:number,z:number,air=false,hp=1e6){const u=w.addUnit(air?'mutalisk':'marine','zerg',x,z,1,'regular',13);u.maxHp=u.hp=hp;u.armor=0;u.moveSpeed=0;u.nextShotAt=u.specialReady=1e9;u.attributes=['Armored','Biological'];targets.push(u.id);return u;}
function add(f:FamilyId,x:number,z:number,id?:EliteId){const u=w.addFamilyMember(f,{x,z},rank);if(id){u.eliteId=id;u.modelKey=ELITES[id].model;}w.refreshStats(u,true);u.energy=u.maxEnergy;if(f==='lurker'){u.nativeMode=u.desiredNativeMode='lurker_burrowed';w.refreshStats(u,true);}if(u.pairId){const pair=w.expedition.zerglingPairs.find(p=>p.id===u.pairId)!;for(const member of pair.members){const twin=w.entities.get(member)!;twin.eliteId=u.eliteId;twin.modelKey=u.modelKey;w.refreshStats(twin,true);}}sources.push(u.id);return u;}
function setup(){view.resetRun();w.resetRun();w.selectRace(race);w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.expedition.zerglingPairs=[];w.stage=13;w.anchor.x=-4;w.anchor.z=0;w.wallet.minerals=0;w.wallet.gas=0;sources=[];targets=[];for(const c of Object.values(w.expedition.production))c.enabled={};
 const medical=['medivac','science_vessel','queen'].includes(family),mixed=scene==='mixed',fs=mixed?(race==='terran'?['marine','hellion','tank','medivac','science_vessel']:race==='zerg'?['zergling','hydralisk','ravager','queen','mutalisk']:['zealot','stalker','colossus','high_templar','carrier'])as FamilyId[]:[family];
 w.expedition.familySlots=[...new Set([...fs,medical?(family==='science_vessel'?'tank':race==='terran'?'marine':'roach'):family,scene==='cards'?(race==='terran'?'marine':race==='zerg'?'hydralisk':'stalker'):family])]as FamilyId[];for(const f of w.expedition.familySlots)w.expedition.tech['unlock.'+f]=1;for(const key of ['storm','charge','blink','transform','hellbat','viking_assault'])w.expedition.tech[key]=1;
 if(scene==='compare'){for(let i=0;i<4;i++)add(family,-4,(i-1.5)*5,i?`${family}.${i}`as EliteId:undefined);}else if(mixed){for(const [i,f]of fs.entries())add(f,-5+(i%2)*1.3,(i-2)*2.7);}else add(family,-4,0,variant==='ordinary'?undefined:`${family}.${variant}`as EliteId);
 source=sources[0];initializeCarrierSubsystem(w);
 const air=scenario==='air'||['viking','phoenix','corruptor'].includes(family)&&scenario!=='ground',melee=['zealot','zergling','baneling','ultralisk'].includes(family),rows=scene==='compare'?4:1;
 for(let row=0;row<rows;row++)for(let i=0;i<(scene==='cards'&&card==='zerg.hatch'?16:scenario==='single'?1:6);i++){const z=rows===4?(row-1.5)*5:0,x=melee?-1+(i%3)*1.5:2.5+(i%3)*1.5;enemy(x,z+(Math.floor(i/3)-.5)*1.65,air,scene==='cards'&&card==='zerg.parasite'?120:scene==='cards'&&['zerg.hatch','zerg.consume'].includes(card)?20:1e6);}
 if(medical||scene==='cards'&&['zerg.consume','zerg.evolve'].includes(card)){for(let i=0;i<3;i++){const f=family==='science_vessel'?'tank':race==='terran'?'marine':race==='zerg'?'roach':'stalker',patient=w.addUnit(f,'terran',-2+i*.5,-3+i*3,5);patient.hp=patient.maxHp*.15;patient.nextShotAt=patient.stoppedUntil=1e9;}}
 if(scene==='cards'){for(let i=0;i<level;i++)if(!buySupport(w,card))throw Error('支援卡条件未满足：'+card);}
 if(scenario==='empty')for(const id of sources){const u=w.entities.get(id)!;u.energy=u.energyRegen=0;}
 w.hash.rebuild(w.entities.values());w.paused=false;stepper.reset();$('pause').textContent='暂停';$('result').textContent='';$('name').textContent=scene==='cards'?cardLabel(card):SC2_UNITS[family].zh;const modes=family==='hellion'||family==='viking'||family==='tank'||family==='stalker';$('mode').hidden=!modes;$('mode').textContent=family==='stalker'?'向前闪现':'转换形态';$('tactical').hidden=scene!=='cards'||!['terran.overdrive','zerg.evolve','protoss.prism','strategic'].includes(card);$('tactical').textContent=card==='strategic'?'发射战略弹药':'施放战术技能';$('mine').hidden=scene!=='cards'||card!=='mines';resize();w.changed();updateText();
}
function cardLabel(id:SupportCard){return id in UNIQUE_SUPPORT?UNIQUE_SUPPORT[id as UniqueSupportId].name:common[id as keyof typeof common][['terran','zerg','protoss'].indexOf(race)];}
function updateLists(){$('family').innerHTML=FAMILIES_BY_RACE[race].map(f=>`<option value="${f}">${SC2_UNITS[f].zh}</option>`).join('');($('family')as HTMLSelectElement).value=family;const cards=['mines','bombardment','mutation','strategic',...Object.keys(UNIQUE_SUPPORT).filter(id=>UNIQUE_SUPPORT[id as UniqueSupportId].race===race)]as SupportCard[];if(!cards.includes(card))card=cards[0];$('card').innerHTML=cards.map(id=>`<option value="${id}">${cardLabel(id)}</option>`).join('');($('card')as HTMLSelectElement).value=card;$('variants').innerHTML=['ordinary','1','2','3'].map(v=>`<option value="${v}">${v==='ordinary'?'普通兵':ELITES[`${family}.${v}`as EliteId].name}</option>`).join('');($('variants')as HTMLSelectElement).value=variant;$('card-controls').hidden=scene!=='cards';$('variants').hidden=scene==='compare'||scene==='cards'||scene==='mixed';}
async function choose(){if(busy)return;busy=true;$('interface').hidden=false;$('interface').textContent='准备观察对象…';try{if(scene==='cards')family=race==='terran'?'marine':race==='zerg'?'hydralisk':'stalker';updateLists();const needed=new Set<FamilyId>([family,'marine','mutalisk','tank','roach','stalker']);if(scene==='mixed')for(const f of FAMILIES_BY_RACE[race])needed.add(f);for(const f of needed)if(!await view.ensureUnitVariant(f,f))throw Error(view.modelErrors.join(';'));if(scene==='compare'||variant!=='ordinary'){for(const i of scene==='compare'?[1,2,3]:[+variant]){const e=ELITES[`${family}.${i}`as EliteId];if(!await view.ensureUnitVariant(e.model,e.family))throw Error(view.modelErrors.join(';'));}}if(family==='hellion')await view.ensureUnitVariant('hellion.hellbat','hellion');if(family==='viking')await view.ensureUnitVariant('viking.assault','viking');setup();ready=true;$('interface').hidden=true;}catch(e){$('interface').textContent='载入失败：'+String(e);console.error(e);}finally{busy=false;}}
function step(){if(w.paused||busy)return false;w.stageElapsed=0;w.step();return true;}const stepper=new FixedStepper(1/60,step,()=>performance.now(),8);
function advance(seconds:number){for(let i=0;i<Math.ceil(Math.min(65,seconds)*60);i++)if(!step())break;view.render(0,0);updateText();}
function hurt(){const attacker=w.entities.get(targets[0]);for(const u of w.allies().filter(u=>!u.summonKind))w.hit(u,(u.shield??0)+Math.min(u.hp*.3,250),[],1,'zerg',0,1,attacker?.id);}
function updateText(){const s=w.expedition.support; $('time').textContent=w.time.toFixed(1)+'s';$('damage').textContent=Math.round(w.stats.damage).toString();$('healed').textContent=Math.round(w.stats.healed).toString();$('state').textContent=`在途 ${w.weaponFlights.length+s.unique.packets.length} · 实体 ${w.allies().length} · 战略库存 ${s.ammo}`;$('description').textContent=scene==='cards'?(card in UNIQUE_SUPPORT?UNIQUE_SUPPORT[card as UniqueSupportId].description:card==='strategic'?'每次购买增加一发；3000伤害、半径8、三秒预警，同一时间只允许一个待落点。':card==='mines'?'每关6/9/12枚。人族追踪蜘蛛雷、虫族与神族为静态雷；都使用正式伤害和引爆条件。':card==='bombardment'?'每20/15/10秒一次；180伤害、半径2.5、0.75秒预警。':'仅对应普通兵与精英主攻击实际生命伤害产生三秒追加效果，最多三层。'):'保留原兵种数值、模式、目标层与攻击周期；军衔只增强局部发光和装饰，不扩大命中区域。';}
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;const alpha=ready&&!busy&&!w.paused?stepper.advance(dt):0;if(ready)view.render(dt,alpha);if(ready)updateText();}
for(const id of ['race','family','scene','rank','variants','card','level','scenario'])($(id)as HTMLSelectElement).onchange=()=>{if(id==='race'){race=($('race')as HTMLSelectElement).value as Race;family=FAMILIES_BY_RACE[race][0];variant='ordinary';}if(id==='family'){family=($('family')as HTMLSelectElement).value as FamilyId;variant='ordinary';}if(id==='scene')scene=($('scene')as HTMLSelectElement).value;if(id==='rank')rank=+($('rank')as HTMLSelectElement).value;if(id==='variants')variant=($('variants')as HTMLSelectElement).value;if(id==='card')card=($('card')as HTMLSelectElement).value as SupportCard;if(id==='level')level=+($('level')as HTMLSelectElement).value;if(id==='scenario')scenario=($('scenario')as HTMLSelectElement).value;void choose();};
($('quality')as HTMLSelectElement).onchange=()=>view.nonHeroEffects.setQuality(($('quality')as HTMLSelectElement).value as any);
$('pause').onclick=()=>{w.paused=!w.paused;stepper.reset();$('pause').textContent=w.paused?'继续':'暂停';};$('restart').onclick=()=>setup();$('skip').onclick=()=>advance(2);$('long').onclick=()=>advance(20);$('hurt').onclick=hurt;$('zoom').onclick=()=>{zoom=zoom===1.8?2.4:1.8;resize();};
$('mode').onclick=()=>{if(family==='stalker'){const u=w.entities.get(source)!;w.castFamilyAbility('stalker',{x:u.x+3,z:u.z});}else if(family==='tank')w.requestSiege(w.entities.get(source)?.mode!=='siege');else w.setFamilyMode(family,family==='hellion'?(w.entities.get(source)?.nativeMode==='hellbat'?'hellion':'hellbat'):(w.entities.get(source)?.nativeMode==='viking_assault'?'viking':'viking_assault'));};
$('tactical').onclick=()=>{const point={x:4,z:0};const ok=card==='strategic'?w.commitStrategicStrike(point):w.castTactical(race==='protoss'?point:undefined);$('result').textContent=ok?'已施放':'当前条件未满足';};
$('mine').onclick=()=>{if(!w.expedition.support.mines.length)advance(.05);const mine=w.expedition.support.mines[0];if(!mine)return;w.anchor.x=mine.point.x;w.anchor.z=mine.point.z;enemy(mine.point.x+1,mine.point.z,false);w.hash.rebuild(w.entities.values());resize();$('result').textContent='观察第一枚真实布设的地雷';};
$('save').onclick=()=>{saved=structuredClone(w.captureRun());$('result').textContent='已保存';};$('restore').onclick=()=>{if(!saved)return;view.resetRun();w.restoreRun(saved);stepper.reset();$('pause').textContent='继续';$('result').textContent='已恢复 · 暂停';};addEventListener('blur',()=>{if(ready){w.paused=true;stepper.reset();$('pause').textContent='继续';}});
(window as any).__P4_SHOWCASE__=()=>({ready,busy,race,family,rank,variant,scene,card,level,scenario,time:w.time,paused:w.paused,schema:RUN_SCHEMA,source:w.entities.get(source),medicalEnergyCost:HEAL.energyPerHp,heroQuality:view.fx.heroQuality,sources:sources.map(id=>w.entities.get(id)),allies:w.allies(),forts:[...w.fortifications.values()],children:ownedInterceptors(w,source),damage:w.stats.damage,healed:w.stats.healed,shots:w.stats.shots,kills:w.stats.kills,flights:structuredClone(w.weaponFlights),support:structuredClone(w.expedition.support),spells:structuredClone(w.expedition.spells),effects:structuredClone(w.effects),render:view.report(),emission:sources.map(id=>ordinaryEmissionScale(w.entities.get(id)!))});
(window as any).__P4_ADVANCE__=advance;
(window as any).__P4_RENDER_PURITY__=()=>{const before=JSON.stringify(encodeGraph(w.captureRun()));view.nonHeroEffects.render(w,()=>true,e=>({x:e.x,y:e.y,z:e.z}));return before===JSON.stringify(encodeGraph(w.captureRun()));};
async function load(){await loadEmbeddedAssets();await prepareEmbeddedAssetIds([...selected].filter(id=>ASSETS.get(id)?.kind==="effect-texture"||id.startsWith("p4.texture.")||["model.projectile.marauder","model.projectile.hydralisk","model.hero-upgrade.vikingfightermissile","model.egg","terrain.char","map.terrain.diffuse"].includes(id)),(d,t)=>$('interface').textContent=`准备战场 ${d}/${t}`);await view.fx.load();await view.nonHeroEffects.load();await view.protossEliteEffects.load();await view.zergEliteEffects.load();await view.p4Effects.loadMedicalTextures();await view.terranEliteEffects.load();await view.prepareP4Assets();await view.prepareEndlessAssets();view.gpu.set('egg',new AnimatedBatch(await restoreSc2Materials(await new GLTFLoader().loadAsync(assetUrl('model.egg')!)),view.scene,1.3));await view.ensureUnitVariant('interceptor','carrier');const tex=await new THREE.TextureLoader().loadAsync(assetUrl('map.terrain.diffuse')!);tex.colorSpace=THREE.SRGBColorSpace;tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(.18,.18);const floor=new THREE.Mesh(new THREE.PlaneGeometry(160,160),new THREE.MeshStandardMaterial({map:tex,color:0x92989f,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;view.scene.add(floor);await choose();await view.warmPresentationBatches();($('race')as HTMLSelectElement).disabled=false;last=performance.now();}
requestAnimationFrame(frame);load().catch(e=>{$('interface').textContent='载入失败：'+e.message;console.error(e);});
