import {familyBackground} from './family-art-r9.mjs';
import {unitPainting} from './unit-illustrations-r10.mjs';
// SC2 intermission presentation. All purchases below are disposable preview state.
export function createIntermissionUI(env){
 const {state,frame,img,money,svg,button,esc,modalShell,pushModal,popModal,go,render,renderModal,toast,getFixture}=env;
 const S={race:null,round:0,refreshes:0,direction:0,built:false,builtCard:null,bought:new Set(),owned:new Map(),offers:[],selection:null,variant:null,member:0,libraryRace:'terran',group:'all',quality:'all',query:'',page:0,displayState:'available',hero:0,heroPage:0};
 const groupNames={unitcards:'兵种特色',all:'全部',development:'基地建设',team:'全军强化',supply:'援军',training:'晋升',efficiency:'战地后勤',support:'种族战术',economy:'补给',elite:'精锐',elitevariants:'精锐特色',hero:'英雄',herounique:'英雄立绘',service:'休整'};
 const raceNames={terran:'人族',zerg:'虫族',protoss:'神族'},qualityNames={white:'标准',green:'优良',blue:'稀有',purple:'史诗',orange:'传奇'},roman=['','I','II','III','IV','V'];
 const coverIds={raynor:'terran-raynor',tychus:'terran-tychus',nova:'terran-nova',kerrigan:'zerg-kerrigan',zagara:'zerg-zagara',dehaka:'zerg-dehaka',artanis:'protoss-artanis',zeratul:'protoss-zeratul',fenix:'protoss-fenix'};
 const cards=()=>getFixture().cards;
 const find=(group,fn=()=>true,race=state.race)=>cards().find(c=>c.race===race&&c.group===group&&fn(c));
 const lineList=()=>Object.entries(getFixture().lines).filter(([,l])=>l.race===state.race);
 const familyList=()=>getFixture().families[state.race];
 const affordable=c=>!c.price||(state.minerals>=c.price.minerals&&state.gas>=c.price.gas);
 function init(){if(S.race===state.race)return;S.race=state.race;S.direction=0;S.round=0;S.refreshes=0;S.built=false;S.builtCard=null;S.bought.clear();S.owned.clear();S.hero=0;S.heroPage=0;S.offers=[];}
 function shopSet(n){
  const fs=familyList(),family=fs[1].id;
  const heroes=cards().filter(c=>c.race===state.race&&c.group==='hero'&&c.rank===1);
  const support=cards().filter(c=>c.race===state.race&&c.group==='support');
  const efficiency=cards().filter(c=>c.race===state.race&&c.group==='efficiency'&&c.rarity==='blue');
  const banks=[
   [find('team',c=>c.subtype==='firepower'&&c.rarity==='blue'),find('elite',c=>c.subtype==='eliteOffer'&&c.family===family&&c.rarity==='purple'),heroes[0]],
   [support.find(c=>c.subtype==='mines'),support.find(c=>c.rarity==='blue'&&!['bombardment'].includes(c.subtype)),support.find(c=>c.rarity==='purple'&&c.subtype!=='mutation')],
   [find('supply',c=>c.families[0]===fs[0].id&&c.subtype==='pod'&&c.count===2),find('supply',c=>c.families[0]===fs[1].id&&c.subtype==='direct'&&c.count===2),find('team',c=>c.subtype==='defense'&&c.rarity==='purple')],
   [find('training',c=>c.families[0]===fs[0].id&&c.rank===3),find('economy',c=>c.subtype==='gas'),efficiency[0]],
   [support.find(c=>c.rarity==='orange'&&c.subtype!=='strategic'),find('elite',c=>c.subtype==='eliteOffer'&&c.family===fs[2].id&&c.rarity==='orange'),heroes[2]],
   [find('economy',c=>c.subtype==='salvage'),support.find(c=>c.subtype==='bombardment'),find('team',c=>c.subtype==='firepower'&&c.rarity==='green')]
  ];return banks[n%banks.length].filter(Boolean);
 }
 function offers(){init();if(!S.offers.length)S.offers=shopSet(S.round);return S.offers;}
 function battleHeader(name,step=2){return `<header class="im-heading"><div class="im-title">${button(svg('back'),'route:battle','im-back','aria-label="返回战场"')}<div><span class="im-eyebrow">第 6 关完成 · ${raceNames[state.race]}</span><h1>${name}</h1></div></div><div class="im-wallet" aria-label="现有资源">${money(state.minerals,state.gas)}</div></header><nav class="im-steps" aria-label="关间整备"><button data-action="route:development" ${step===1?'aria-current="step"':''}><b>${step>1?svg('check'):'01'}</b>基地建设</button><i></i><button data-action="route:shop" ${step===2?'aria-current="step"':''}><b>02</b>战备补给</button><i></i><span><b>03</b>返回前线</span></nav>`;}
 function raceTabs(action,active,all=false){return `<div class="im-races" role="group" aria-label="卡片种族">${(all?['all',...Object.keys(raceNames)]:Object.keys(raceNames)).map(r=>`<button data-action="${action}" data-value="${r}" aria-pressed="${active===r}">${r==='all'?'全种族':raceNames[r]}</button>`).join('')}</div>`;}
 function shell(content){return `<section class="intermission-screen">${content}</section>`;}
 function refreshControl(disabled=false){const cost=50+40*S.refreshes;return `<div class="im-refresh">${button(svg('refresh')+' 刷新','im-refresh','secondary',disabled||state.minerals<cost?'disabled':'')}<span>${money(cost)}</span></div>`;}
 function development(){
  init();const lines=lineList(),line=lines[S.direction][0],lineCards=cards().filter(c=>c.race===state.race&&c.group==='development'&&c.line===line);
  const facility=state.race==='zerg'?find('development',c=>c.subtype==='facility'):lineCards.find(c=>c.subtype==='facility');
  const unlock=lineCards.filter(c=>c.subtype==='unlock'),skill=lineCards.find(c=>c.subtype==='skill'),system=lineCards.find(c=>c.subtype==='system');
  const banks=[[facility,unlock[1]??unlock[0],system],[unlock[2]??unlock[0],skill??system,lineCards.find(c=>c.subtype==='research'&&c.rank===1)],[facility,lineCards.find(c=>c.subtype==='research'&&c.rank===2),unlock[0]]];
  const choices=banks[S.round%banks.length].filter(Boolean);
  return shell(`${battleHeader('基地建设',1)}<div class="im-direction" role="group" aria-label="发展方向">${lines.map(([id,l],i)=>`<button data-action="im-direction" data-value="${i}" aria-pressed="${S.direction===i}" ${S.built?'disabled':''}>${img('unit.'+l.families[0])}<span>${l.name}</span></button>`).join('')}<span class="im-status">${S.built?svg('check')+' 已整备':'选择一项'}</span></div><div class="im-choice-grid" aria-label="发展选项">${choices.map((c,i)=>card(c,{index:i,flow:'development',sold:S.built,selected:S.selection===c.id})).join('')}</div><footer class="im-footer">${refreshControl(S.built)}${button(S.built?'前往补给 '+svg('next'):'暂缓建设 '+svg('next'),'route:shop','primary')}</footer>`);
 }
 function shop(){init();return shell(`${battleHeader('战备补给')}<div class="im-caption"><span><i class="im-live-dot"></i>${state.race==='terran'?'军需官待命':state.race==='zerg'?'虫群待命':'跃迁信号就绪'}</span><span class="im-purchase-count">${S.bought.size?S.bought.size+' 项已备齐':'补给已送达'}</span></div><div class="im-choice-grid" aria-label="商店选项">${offers().map((c,i)=>card(c,{index:i,flow:'shop',sold:S.bought.has(c.id),selected:S.selection===c.id})).join('')}</div><footer class="im-footer">${refreshControl()}${button('返回前线 '+svg('next'),'route:battle','primary')}</footer>`);}
 function card(c,{index=0,flow='catalogue',sold=false,selected=false,displayState='available'}={}){
  const unavailable=displayState==='short'||(!affordable(c)&&flow!=='catalogue'),stageLocked=flow==='development'&&c.afterStage>6,closed=flow==='development'&&S.built&&S.builtCard!==c.id,locked=displayState==='locked'||stageLocked||closed,owned=displayState==='owned',pending=displayState==='pending',isSold=(flow==='development'?S.builtCard===c.id:sold)||displayState==='sold';
  const label=isSold?'已获得':pending?'正在集结':closed?'本轮已整备':stageLocked?'第 '+c.afterStage+' 关开放':locked?'尚未解锁':unavailable?'资源不足':owned?'已达上限':flow==='catalogue'?'查看':c.subtype==='eliteOffer'?'挑选精锐':c.group==='hero'?'查看英雄':flow==='development'?(c.subtype==='facility'?'扩建':'研究'):'购买';
  const action=flow==='catalogue'?'im-inspect':c.subtype==='eliteOffer'?'im-elite':c.group==='hero'?'im-inspect':'im-buy';
  const status=isSold?'已获得':pending?'正在集结':closed?'已整备':locked?'待解锁':unavailable?'资源不足':owned?'已达上限':'';
  const off=displayState==='discount15'?.15:displayState==='discount30'?.3:displayState==='discount50'?.5:0,free=displayState==='free';
  const shownPrice=c.price?{minerals:free?0:Math.ceil(c.price.minerals*(1-off)),gas:free?0:Math.ceil(c.price.gas*(1-off))}:null;
  return `<article class="im-card ${isSold?'im-sold':''} ${pending?'im-pending':''} ${selected||displayState==='selected'?'im-selected':''} ${locked||owned?'im-locked':''} ${unavailable?'im-short':''}" data-card-id="${c.id}" data-card-race="${c.race}" data-quality="${c.rarity}" data-kind="${c.art}" style="--deal-index:${index}"><span class="im-edge" aria-hidden="true"></span><div class="im-card-meta"><span>${esc(c.kicker)}</span><div class="im-quality" aria-label="${qualityNames[c.rarity]}">${Array.from({length:5},(_,i)=>`<i class="${i<=Object.keys(qualityNames).indexOf(c.rarity)?'lit':''}"></i>`).join('')}</div></div><button class="im-card-face" data-action="im-inspect" data-value="${c.id}" data-flow="${flow}" aria-label="查看${esc(c.name)}详情">${cardArt(c)}<div class="im-card-copy"><div class="im-card-title"><h2>${esc(c.name)}</h2>${c.rank?`<span class="im-rank">${roman[c.rank]}</span>`:''}${c.count?`<span class="im-count">×${c.count}${c.families[0]==='zergling'?'对':''}</span>`:''}</div><p class="im-flavour">${esc(c.summary)}</p><p class="im-effect">${esc(shortStat(c))}</p></div></button><div class="im-card-bottom"><div class="im-card-price" aria-label="${shownPrice?'费用 '+shownPrice.minerals+' 矿物 '+shownPrice.gas+' 瓦斯':'按伤损结算'}">${shownPrice?money(shownPrice.minerals,shownPrice.gas):'<span class="im-variable-price">按伤损结算</span>'}${off&&c.price?`<del class="im-price-original">${c.price.minerals} / ${c.price.gas}</del>`:''}</div>${button((isSold?svg('check'):flow==='catalogue'?svg('eye'):'')+(free?'免费领取':label),action,'im-card-action',`data-value="${c.id}" data-flow="${flow}" ${flow!=='catalogue'&&(isSold||pending||unavailable||locked||owned)?'disabled':''}`)}</div>${status||off||free?`<span class="im-card-status">${isSold?svg('check'):''}${off?'−'+(off*100)+'%':free?'免费':status}</span>`:''}</article>`;
 }
 function shortStat(c){if(c.subtype==='eliteVariant'){const match=c.stat.match(/^[^。；]+/);return match?match[0]:c.stat;}if(c.group==='support')return c.stat.length>26?c.stat.slice(0,25)+'…':c.stat;return c.stat;}
 function artDrawing(c){
  const stroke='var(--card-ink)',faint='var(--card-faint)',defs=`<defs><linearGradient id="cg-${c.id}" x2=".7" y2="1"><stop stop-color="${stroke}" stop-opacity=".75"/><stop offset="1" stop-color="${stroke}" stop-opacity=".04"/></linearGradient></defs>`;
  const base=`<g fill="none" stroke="${faint}" stroke-width="1"><path d="M22 132H73L83 122H240M20 38H96M209 44H295M29 18V145M289 15V140"/><circle cx="161" cy="84" r="59" stroke-dasharray="1 7"/><path d="M38 118V112M44 118V108M50 118V114M262 30V36M268 30V40M274 30V36"/></g>`;
  const paths={
   firepower:`<g fill="none" stroke="${stroke}"><path d="M35 102L196 40L242 54L94 117Z" stroke-width="2"/><path d="M81 117L89 132L107 125L104 107M111 92L116 113L144 105L141 80M178 45L184 63M198 40L204 57"/><path d="M227 48L288 28M241 60L295 47M253 73L282 70" stroke-width="3"/><path d="M48 105L51 114L82 120"/></g>`,
   defense:`<path d="M161 22L220 45L214 103L161 141L108 103L102 45Z" fill="url(#cg-${c.id})" stroke="${stroke}" stroke-width="2"/><path d="M161 34L206 52L201 97L161 126L121 97L116 52Z" fill="none" stroke="${stroke}" stroke-opacity=".6"/><path d="M137 77L155 94L186 58" fill="none" stroke="${stroke}" stroke-width="4"/>`,
   facility:`<g fill="url(#cg-${c.id})" stroke="${stroke}"><path d="M83 69L163 37L237 64L157 99Z M83 69V111L157 140V99M157 99V140L237 105V64"/><path d="M123 54V32L173 14L209 30V54M98 91L134 106V125M179 99L221 82V108"/><path d="M163 37V15M157 108L237 73" fill="none"/></g>`,
   technology:`<g fill="none" stroke="${stroke}"><path d="M105 42H212V126H105Z M113 50H204V118H113Z"/><path d="M91 57H105M91 74H105M91 91H105M91 108H105M212 57H226M212 74H226M212 91H226M212 108H226M120 27V42M140 27V42M160 27V42M180 27V42M200 27V42M120 126V139M140 126V139M160 126V139M180 126V139M200 126V139" stroke-width="3"/><path d="M140 65L177 81L143 104Z" fill="url(#cg-${c.id})"/></g>`,
   energy:`<g fill="none" stroke="${stroke}"><path d="M165 20L215 84L165 146L115 84Z" fill="url(#cg-${c.id})"/><path d="M165 41L196 84L165 124L135 84ZM92 59L62 84L92 109M239 59L268 84L239 109"/><path d="M165 51L148 85H176L162 112" stroke-width="3"/></g>`,
   resources:`<g stroke="${stroke}" fill="url(#cg-${c.id})"><path d="M81 104L91 56L111 37L133 65L125 125Z M124 122L134 71L163 38L184 80L173 130Z M174 130L185 78L209 60L231 98L219 129Z"/><path d="M111 37L116 99L91 56M163 38L156 105L134 71M209 60L204 118L185 78" fill="none"/></g>`,
   mines:`<g stroke="${stroke}" fill="url(#cg-${c.id})"><ellipse cx="164" cy="91" rx="48" ry="26"/><path d="M116 91L121 111L161 125L207 108L212 91M132 84L156 72L190 82L191 98L164 108L136 97Z"/><path d="M118 95L87 98L78 112M136 113L112 136M209 92L240 92L249 110M194 113L223 131" fill="none" stroke-width="3"/><circle cx="164" cy="86" r="6"/><path d="M135 42A39 39 0 0 1 195 42M122 30A58 58 0 0 1 208 30" fill="none" stroke-dasharray="4 5"/></g>`,
   bombardment:`<g fill="none" stroke="${stroke}"><ellipse cx="161" cy="117" rx="78" ry="18"/><ellipse cx="161" cy="117" rx="41" ry="10"/><path d="M207 15L177 77M168 20L148 68M132 26L117 79" stroke-width="3"/><path d="M154 108L161 88L167 109M124 105L130 85M190 107L201 91"/><path d="M80 117H115M210 117H243M161 143V133"/></g>`,
   mutation:`<g fill="none" stroke="${stroke}"><path d="M161 19C144 46 118 69 116 94A45 45 0 0 0 206 94C202 68 176 50 161 19Z" fill="url(#cg-${c.id})"/><path d="M161 52C143 76 134 82 135 99C138 121 174 123 183 105M94 101L72 102M229 101H251M109 59L92 45M216 59L232 42"/><circle cx="163" cy="92" r="14" stroke-width="2"/></g>`,
   strategic:`<g fill="none" stroke="${stroke}"><circle cx="161" cy="83" r="58"/><circle cx="161" cy="83" r="34"/><path d="M161 7V52M161 115V155M84 83H130M193 83H240" stroke-width="2"/><path d="M161 57L141 96H182Z" fill="url(#cg-${c.id})"/><path d="M77 128L62 145M245 38L260 20M81 39L65 25M240 127L257 143"/></g>`,
   ricochet:`<g fill="none" stroke="${stroke}"><path d="M64 118L130 65L205 114L257 35" stroke-width="3"/><circle cx="130" cy="65" r="14"/><circle cx="205" cy="114" r="14"/><circle cx="257" cy="35" r="14"/><path d="M77 120H53L60 100M124 38L130 32L138 37M182 135L174 128L180 120"/></g>`,
   missiles:`<g fill="url(#cg-${c.id})" stroke="${stroke}">${[0,1,2].map(i=>`<g transform="translate(${64+i*64} ${63-i*14}) rotate(-26)"><path d="M0 25L10 0L21 25V71H0Z M0 58L-11 79L0 72M21 58L32 79L21 72"/><path d="M5 78V113M15 79V121" fill="none" stroke-width="2"/></g>`).join('')}</g>`,
   recovery:`<g fill="none" stroke="${stroke}"><path d="M145 34H176V65H207V96H176V126H145V96H115V65H145Z" fill="url(#cg-${c.id})"/><path d="M80 107A87 87 0 0 1 77 65M86 114L78 101L66 114M242 55A87 87 0 0 1 244 99M235 48L246 62L257 48"/><path d="M36 84H75L87 65L100 104L112 84M209 84H228L240 71L250 94L260 84H291"/></g>`,
   training:`<g fill="url(#cg-${c.id})" stroke="${stroke}"><path d="M161 25L210 52V107L161 136L111 107V52Z"/><path d="M133 81L161 61L190 81M133 96L161 76L190 96M133 111L161 91L190 111" fill="none" stroke-width="3"/><path d="M90 69L75 59V116L91 107M231 69L247 59V116L231 107"/></g>`,
   supply:`<g fill="none" stroke="${stroke}"><path d="M114 63H207L223 122H99Z" fill="url(#cg-${c.id})"/><path d="M114 64L145 78H178L207 63M145 78V111H178V78M101 121L126 135H198L222 121"/><path d="M132 17V50M161 8V50M190 17V50M123 41L132 50L141 41M151 41L161 51L171 41M181 41L190 50L199 41" stroke-width="2"/></g>`,
   production:`<g fill="none" stroke="${stroke}"><circle cx="161" cy="84" r="49"/><path d="M161 48V85L183 98" stroke-width="3"/><path d="M122 16L151 19L137 38M151 19A65 65 0 0 1 219 113M200 144L174 143L189 124M174 143A65 65 0 0 1 103 53"/><path d="M246 65L260 78L246 91M271 65L285 78L271 91"/></g>`,
   parasite:`<g fill="none" stroke="${stroke}"><path d="M161 39C111 24 114 111 161 126C208 108 210 25 161 39Z" fill="url(#cg-${c.id})"/><path d="M125 60L89 43L80 53M122 82H78M132 102L97 118M196 60L230 43L241 55M202 82H249M189 103L228 122M161 46V116"/><circle cx="159" cy="72" r="10"/></g>`,
   hatch:`<g stroke="${stroke}" fill="url(#cg-${c.id})"><path d="M144 44C157 17 178 28 189 56C220 119 208 132 163 132C110 130 111 103 144 44Z"/><path d="M155 50L164 78L152 94L180 104L164 129" fill="none"/><path d="M109 97L90 72M102 114L75 111M217 96L238 76M220 115L248 110" fill="none"/></g>`,
   evolve:`<g fill="url(#cg-${c.id})" stroke="${stroke}"><path d="M161 22L210 52L220 106L161 140L102 106L113 51Z"/><path d="M113 51L139 67L161 22L183 67L210 52M139 67L123 103L161 121L198 103L183 67M123 103L102 106M198 103L220 106M161 121V140" fill="none"/><path d="M145 84H177M161 68V101" stroke-width="3"/></g>`,
   echo:`<g fill="none" stroke="${stroke}"><path d="M67 124L116 94L163 39L182 53L135 108Z" fill="url(#cg-${c.id})"/><path d="M137 121L196 55L209 64L157 128M193 126L243 72L250 76L207 126" opacity=".6"/><path d="M92 127L111 133M166 26L171 13M218 35L232 24"/></g>`,
   prism:`<g fill="none" stroke="${stroke}"><path d="M88 65L118 45L148 66L137 102L101 102Z" fill="url(#cg-${c.id})"/><path d="M135 80L280 32L278 133Z" fill="url(#cg-${c.id})"/><path d="M144 80H285M119 44V27M99 102L86 123" stroke-width="2"/></g>`,
   overdrive:`<g fill="none" stroke="${stroke}"><circle cx="163" cy="84" r="57" stroke-dasharray="27 8"/><path d="M177 20L132 90H160L151 145L202 72H172Z" fill="url(#cg-${c.id})"/><path d="M63 55L86 80L63 104M244 55L267 80L244 104" stroke-width="3"/></g>`,
   counter:`<g fill="none" stroke="${stroke}"><path d="M162 25L213 49L207 104L176 130L165 93L178 82L158 70L157 27M151 31L112 49L118 104L148 127L141 91L152 80L136 68Z" fill="url(#cg-${c.id})"/><path d="M100 58L58 39M95 91L48 97M225 56L266 35M225 91L273 101M165 139V154" stroke-width="2"/></g>`,
  };
  const art=paths[c.art]??paths[c.art==='hero'||c.art==='elite'?'training':'technology'];
  const organic=c.race==='zerg'?`<path d="M30 130Q61 61 106 144M288 123Q245 24 218 146" fill="none" stroke="${faint}" stroke-width="5"/>`:c.race==='protoss'?`<path d="M41 29L59 44L48 68M276 28L258 44L270 69M57 140L73 134M269 139L253 133" fill="none" stroke="${faint}" stroke-width="2"/>`:'';
  return `<svg class="im-engraving" viewBox="0 0 320 166" aria-hidden="true" focusable="false">${defs}${base}${organic}${art}</svg>`;
 }
 function cardArt(c){
  const cover=coverIds[c.heroId],coverSrc=cover?env.coverAsset(cover):null;
  const paired=c.families?.[0]==='zergling',bodies=c.group==='supply'?c.count*(paired?2:1):c.group==='training'?2*(paired?2:1):paired&&['unlock','eliteOffer','eliteVariant'].includes(c.subtype)?2:1;
  const painting=unitPainting(c,bodies);
  if(painting){const badge=!['unit','elite','hero','supply','training'].includes(c.art)?`<span class="im-painting-badge" aria-hidden="true">${img(c.icon,'')}</span>`:'';return `<div class="im-card-art has-unit-painting">${painting}${badge}<span class="im-art-surface" aria-hidden="true"></span></div>`;}
  const background=familyBackground(c),unitArt=['unit','elite','hero','supply','training'].includes(c.art),cols=Math.min(3,bodies),rows=bodies>3?2:1;
  const cohort=bodies>1&&unitArt?`<span class="im-cohort" data-body-count="${bodies}" style="--body-cols:${cols};--body-rows:${rows}" aria-label="${bodies} 个战斗单位">${Array.from({length:bodies},(_,i)=>`<img src="${env.asset(c.icon)}" alt="" draggable="false" style="--body-col:${i%3-(cols-1)/2};--body-row:${Math.floor(i/3)-(rows-1)/2}">`).join('')}</span>`:`<span class="im-emblem ${unitArt?'im-unit-emblem':''} ${background?'im-scene-unit':''}">${img(c.icon,'')}<i></i></span>`;
  const visual=(c.art==='hero'&&coverSrc)?`<img class="im-painted" src="${coverSrc}" alt="" draggable="false">`:`${background}${background?`<img class="im-environment-texture" src="${env.mapAsset(c.race+'-wide')}" alt="" draggable="false">`:artDrawing(c)}${cohort}`;
  return `<div class="im-card-art ${background?'has-family-scene':''}">${visual}<span class="im-art-surface" aria-hidden="true"></span><span class="im-art-code" aria-hidden="true">${c.race==='terran'?'TERRAN':c.race==='zerg'?'SWARM':'PROTOSS'} ${c.rank?roman[c.rank]:qualityNames[c.rarity]}</span></div>`;
 }
 function library(){
  const matchesGroup=c=>S.group==='unitcards'?c.group==='development'&&c.subtype==='unlock':S.group==='elitevariants'?c.subtype==='eliteVariant'&&c.rarity==='purple':S.group==='herounique'?c.group==='hero'&&c.rank===1:S.group==='all'||c.group===S.group;
  const all=cards().filter(c=>(S.libraryRace==='all'||c.race===S.libraryRace)&&matchesGroup(c)&&(S.quality==='all'||c.rarity===S.quality)&&(!S.query||(c.name+c.kicker+c.summary+c.families.map(f=>getFixture().families[c.race].find(x=>x.id===f)?.name).join('')).includes(S.query)));
  const size=frame.clientWidth>900?6:3,pages=Math.max(1,Math.ceil(all.length/size));S.page=Math.min(S.page,pages-1);
  return shell(`<header class="im-heading"><div class="im-title">${button(svg('back'),'route:shop','im-back','aria-label="返回商店"')}<div><span class="im-eyebrow">关间卡片 · 美术预览</span><h1>卡片图鉴</h1></div></div><span class="im-library-total">${all.length} <small>张</small></span></header><div class="im-library-filters">${raceTabs('im-library-race',S.libraryRace,true)}<div class="im-filter-selects"><label><span class="sr-only">卡片类别</span><select aria-label="卡片类别" data-im-filter="group">${Object.entries(groupNames).map(([key,label])=>`<option value="${key}" ${S.group===key?'selected':''}>${label}</option>`).join('')}</select></label><label><span class="sr-only">卡片品质</span><select aria-label="卡片品质" data-im-filter="quality"><option value="all">全部品质</option>${Object.entries(qualityNames).map(([key,label])=>`<option value="${key}" ${S.quality===key?'selected':''}>${label}</option>`).join('')}</select></label><input class="im-search" type="search" placeholder="搜索卡片" aria-label="搜索卡片" data-im-filter="query" value="${esc(S.query)}"></div></div><div class="im-catalogue-grid" aria-label="卡片图鉴列表">${all.slice(S.page*size,(S.page+1)*size).map((c,i)=>card(c,{index:i,displayState:S.displayState})).join('')||'<p class="im-empty">没有找到这张卡片。</p>'}</div><footer class="im-footer im-catalogue-footer"><label class="im-state-picker"><span>状态</span><select aria-label="卡片状态" data-im-filter="displayState">${Object.entries({available:'待选择',selected:'已选中',pending:'正在集结',sold:'已获得',short:'资源不足',locked:'尚未解锁',owned:'已达上限',discount15:'优惠 15%',discount30:'优惠 30%',discount50:'优惠 50%',free:'免费领取'}).map(([id,label])=>`<option value="${id}" ${S.displayState===id?'selected':''}>${label}</option>`).join('')}</select></label><div class="im-pagination">${button(svg('back'),'im-library-prev','secondary',`aria-label="上一页卡片" ${S.page===0?'disabled':''}`)}<span>${S.page+1} / ${pages}</span>${button(svg('next'),'im-library-next','secondary',`aria-label="下一页卡片" ${S.page===pages-1?'disabled':''}`)}</div></footer>`);
 }
 function heroes(){init();const heroes=cards().filter(c=>c.race===state.race&&c.group==='hero'&&c.rank===1);return shell(`${battleHeader('英雄待命')}<div class="im-caption"><span>英雄 ${S.owned.size} / 3</span><div class="im-pagination">${button(svg('back'),'im-hero-prev','secondary',`aria-label="上一组英雄" ${S.heroPage===0?'disabled':''}`)}<span>${S.heroPage+1} / 2</span>${button(svg('next'),'im-hero-next','secondary',`aria-label="下一组英雄" ${S.heroPage===1?'disabled':''}`)}</div></div><div class="im-choice-grid">${heroes.slice(S.heroPage*3,S.heroPage*3+3).map((c,i)=>card(c,{index:i,flow:'catalogue',selected:S.selection===c.id})).join('')}</div><footer class="im-footer"><span class="im-status">英雄最多三位</span>${button('返回补给','route:shop','primary')}</footer>`);}
 function services(){init();const selected=cards().filter(c=>c.race===state.race&&c.entry==='service'&&(c.subtype==='repair'||c.rank===1)).slice(0,3);return shell(`${battleHeader('战地休整')}<div class="im-caption"><span>生命恢复 · 英雄复活</span><span>战斗暂停</span></div><div class="im-choice-grid">${selected.map((c,i)=>card(c,{index:i,flow:'catalogue'})).join('')}</div><footer class="im-footer"><span class="im-status">生命已满时无需修复</span>${button('返回补给','route:shop','primary')}</footer>`);}
 function details(){
  const c=cards().find(c=>c.id===S.selection);if(!c)return modalShell('卡片','','','im-detail-dialog',button('返回','modal-close','primary'));
  const catalog=S.detailFlow==='catalogue',sold=S.bought.has(c.id)||S.builtCard===c.id&&S.detailFlow==='development',closed=S.built&&S.detailFlow==='development'&&S.builtCard!==c.id,stageLocked=S.detailFlow==='development'&&c.afterStage>6,can=affordable(c)&&!sold&&!closed&&!stageLocked;
  const footer=button('返回','modal-close','secondary')+(!catalog?button(c.subtype==='eliteOffer'?'挑选精锐':closed?'本轮已整备':stageLocked?'第 '+c.afterStage+' 关开放':sold?'已获得':affordable(c)?(c.group==='hero'?(c.rank>1?'晋升':'招募'):'确认'):deficit(c),c.subtype==='eliteOffer'?'im-elite':'im-buy','primary',`data-value="${c.id}" data-flow="${S.detailFlow}" ${can?'':'disabled'}`):'');
  return modalShell(c.name,c.kicker,`<div class="im-detail-layout"><div class="im-detail-art" data-card-race="${c.race}" data-quality="${c.rarity}" data-kind="${c.art}">${cardArt(c)}<span class="im-detail-rank">${c.rank?roman[c.rank]:qualityNames[c.rarity]}</span></div><div class="im-detail-copy"><p class="im-detail-flavour">${esc(c.summary)}</p><p class="im-detail-rule">${esc(c.detail)}</p>${c.group==='hero'?`<div class="im-skill-readout">${img(c.icon)}<div><small>主动技能</small><b>${esc(getFixture().heroes[c.heroId].skill)}</b></div><strong>${getFixture().heroes[c.heroId].cooldown}<small>秒</small></strong></div>`:''}<div class="im-detail-price">${c.price?money(c.price.minerals,c.price.gas):'按所选部队伤损结算'}</div>${!catalog&&!affordable(c)?`<span class="im-deficit">${deficit(c)}</span>`:''}</div></div>`,'im-detail-dialog',footer);
 }
 function deficit(c){return [state.minerals<c.price.minerals?'缺 '+(c.price.minerals-state.minerals)+' 矿物':'',state.gas<c.price.gas?'缺 '+(c.price.gas-state.gas)+' 瓦斯':''].filter(Boolean).join(' · ');}
 function elitePreview(){
  const c=cards().find(c=>c.id===S.selection&&c.subtype==='eliteOffer')||find('elite',c=>c.subtype==='eliteOffer'&&c.rarity==='purple'&&c.family===familyList()[1].id);
  S.selection=c.id;const variants=cards().filter(v=>v.subtype==='eliteVariant'&&c.variantIds.includes(v.sourceId)&&v.rarity===c.rarity);if(!variants.some(v=>v.id===S.variant))S.variant=variants[0].id;
  const confirm=affordable(c)?`<span class="im-confirm-label">确认 ${svg('check')}</span><span class="im-confirm-price">${money(c.price.minerals,c.price.gas)}</span>`:deficit(c);
  return modalShell('挑选精锐',c.name,`<div class="im-elite-choices" role="radiogroup" aria-label="精锐种类">${variants.map((v,i)=>`<button class="im-elite-choice ${S.variant===v.id?'selected':''}" role="radio" aria-checked="${S.variant===v.id}" data-action="im-variant" data-value="${v.id}" data-card-race="${v.race}" data-quality="${v.rarity}">${cardArt(v)}<div><span class="im-elite-rank">${roman[v.rank]} · 精锐</span><h3>${esc(v.name)}</h3><p>${esc(v.stat)}</p></div><i class="im-radio" aria-hidden="true">${S.variant===v.id?svg('check'):''}</i></button>`).join('')}</div><div class="im-elite-confirm"><div><span>晋升老兵</span><div class="im-members" role="group" aria-label="选择老兵">${Array.from({length:5},(_,i)=>`<button data-action="im-member" data-value="${i}" aria-pressed="${S.member===i}" aria-label="晋升老兵 ${i+1}">${img(c.icon)}<b>${i+1}</b></button>`).join('')}</div></div><div class="im-elite-price">${money(c.price.minerals,c.price.gas)}</div></div>`,'im-elite-dialog',button('取消','modal-close','secondary')+button(confirm,'im-buy','primary',`data-value="${c.id}" data-flow="shop" aria-label="确认精锐，${c.price.minerals} 矿物，${c.price.gas} 瓦斯" ${affordable(c)&&!S.bought.has(c.id)?'':'disabled'}`));
 }
 function handle(action,b){
  if(!action.startsWith('im-'))return false;init();const c=cards().find(c=>c.id===b.dataset.value);
  if(action==='im-inspect'){S.selection=c.id;S.detailFlow=b.dataset.flow||'catalogue';pushModal('card',b);return true;}
  if(action==='im-elite'){S.selection=c?.id??S.selection;if(state.layers.at(-1)?.name==='card')popModal();pushModal('elite',b);return true;}
  if(action==='im-buy'){
   if(!c||!affordable(c)||S.bought.has(c.id)||b.dataset.flow==='development'&&(S.built||c.afterStage>6))return true;
   if(c.group==='hero'&&S.owned.size>=3&&!S.owned.has(c.heroId)){toast('三位英雄已集结。');return true;}
   state.minerals-=c.price?.minerals??0;state.gas-=c.price?.gas??0;
   if(b.dataset.flow==='development'){S.built=true;S.builtCard=c.id;}else S.bought.add(c.id);
   if(c.group==='hero')S.owned.set(c.heroId,c.rank);
   if(c.effect.kind==='resource'){state.minerals+=c.effect.minerals;state.gas+=c.effect.gas;}
   S.selection=c.id;state.layers=[];render({focus:false});frame.querySelector(b.dataset.flow==='development'?'.im-footer>.primary':'.im-card-action:not(:disabled)')?.focus({preventScroll:true});toast((c.group==='hero'?c.name+'已加入':c.group==='elite'?'精锐已集结':b.dataset.flow==='development'?'基地整备完成':'补给已收下')+'。');return true;
  }
  if(action==='im-refresh'){
   const cost=50+40*S.refreshes;if(state.minerals<cost||state.page==='development'&&S.built)return true;state.minerals-=cost;S.refreshes++;S.round++;
   if(state.page==='shop'){const next=shopSet(S.round);S.offers=S.offers.map((old,i)=>S.bought.has(old.id)?old:next[i]??old);}
   S.selection=null;render({focus:false});toast('新补给到了。');return true;
  }
  if(action==='im-direction'){S.direction=Number(b.dataset.value);S.selection=null;render({focus:false});return true;}
  if(action==='im-variant'){S.variant=b.dataset.value;renderModal(false);return true;}
  if(action==='im-member'){S.member=Number(b.dataset.value);renderModal(false);return true;}
  if(action==='im-library-race'){S.libraryRace=b.dataset.value;S.page=0;render({focus:false});return true;}
  if(action==='im-library-prev'||action==='im-library-next'){S.page=Math.max(0,S.page+(action.endsWith('next')?1:-1));render({focus:false});return true;}
  if(action==='im-hero-prev'||action==='im-hero-next'){S.heroPage=action.endsWith('next')?1:0;render({focus:false});return true;}
  return true;
 }
 function change(e){const key=e.target.dataset.imFilter;if(!key)return false;S[key]=e.target.value;S.page=0;const focusKey=key;render({focus:false});const node=frame.querySelector(`[data-im-filter="${focusKey}"]`);node?.focus({preventScroll:true});if(key==='query'){const length=S.query.length;node?.setSelectionRange(length,length);}return true;}
 function keydown(e){
  if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return false;
  const active=document.activeElement,group=active?.closest('[role=radiogroup]');
  if(!group||!active.matches('[data-action=im-variant]'))return false;
  const buttons=[...group.querySelectorAll('[data-action=im-variant]')],index=buttons.indexOf(active),delta=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1,next=buttons[(index+delta+buttons.length)%buttons.length];
  e.preventDefault();handle('im-variant',next);frame.querySelector('[data-action=im-variant][data-value="'+next.dataset.value+'"]')?.focus({preventScroll:true});return true;
 }
 function configure(params){S.libraryRace=Object.hasOwn(raceNames,params.get('race'))?params.get('race'):state.race;S.group=Object.hasOwn(groupNames,params.get('group'))?params.get('group'):'unitcards';S.query=params.get('query')||'';}
 return {development,shop,heroes,library,services,details,elitePreview,handle,change,keydown,configure};
}
