import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
const project=new URL('../../',import.meta.url),out=new URL('reports/local/ui-redesign-20261003/',project);
const screenRoot='C:/Users/zyuu/.codex/visualizations/2026/10/03/01a0ff75-6cfc-7be0-b2f6-92489157b232/';
const read=async path=>JSON.parse(await fs.readFile(path,'utf8'));
const [allRecords,before,manifest,oldManifest]=await Promise.all([read(screenRoot+'sc2-ui-r7/layout-records-r7.json'),read(screenRoot+'sc2-ui-r6/layout-r6.json'),read(new URL('artifact-r7.json',out)),read(new URL('artifact-r6.json',out))]);
const requested={'terran-desktop':[1280,900],'terran-portrait':[390,844],'terran-wide':[844,390],'terran-small-portrait':[360,640],'terran-small-wide':[667,375],'terran-small-wide-folded':[667,375],'zerg-portrait':[390,844],'protoss-wide':[844,390]};
const records=allRecords.filter(r=>requested[r.label]?.[0]===r.viewport.width&&requested[r.label]?.[1]===r.viewport.height);
assert.equal(records.length,8);
for(const r of records){assert.equal(r.minimap.fits,true,r.label);assert.equal(r.minimap.ornamentPointerEvents,'none',r.label);assert.equal(r.playfieldText,'',r.label);assert.deepEqual(r.issues,[],r.label);assert.deepEqual(r.covered,[],r.label);assert.deepEqual(r.missing,[],r.label);assert.equal(r.rowCount,r.folded?0:2,r.label);}
const area=records.filter(r=>r.race==='terran'&&!r.folded).map(r=>{const old=before.find(x=>x.race==='terran'&&!x.folded&&x.viewport.width===r.viewport.width&&x.viewport.height===r.viewport.height);assert.ok(old,r.label);for(const k of ['width','height','x','y'])assert.ok(Math.abs(old.map[k]-r.map[k])<.01,r.label+' map '+k);return {label:r.label,viewport:r.viewport,map:r.map,unchangedFromR6:true};});
for(const k of ['paintedCovers','mapCompositions','talentFixtureSha256'])assert.deepEqual(manifest[k],oldManifest[k],k);
const html=await fs.readFile(new URL('SC2-UI-Preview-r7.html',out),'utf8');assert.equal(Buffer.byteLength(html),manifest.bytes);assert.equal(crypto.createHash('sha256').update(html).digest('hex'),manifest.sha256);assert.equal(/<link[^>]+rel="stylesheet"|<script[^>]+src=/.test(html),false);
const verification={date:'2026-10-05',scope:'Static UI prototype R7 minimap frame only',artifact:{path:manifest.artifact,bytes:manifest.bytes,sha256:manifest.sha256},commands:['node --check preview/ui-20261003/app.mjs','node --check preview/ui-20261003/build-static.mjs','node preview/ui-20261003/build-static.mjs','node preview/ui-20261003/summarize-r7.mjs','git status --short -uno'],layout:{states:records.length,races:3,sizes:[...new Set(records.map(r=>r.viewport.width+'x'+r.viewport.height))],mainControlsIssues:[],minimapHousingFitsAll:true,screenSizeRetained:true,openConsoleRows:2,foldedConsoleRows:0},area,unchanged:{covers:true,maps:true,talentFixture:true,runtimeChanged:false},reference:{viewed:'https://www.arbse.net/Files/StarCraft2/id350/starcraft_units_05.JPG',description:'Original SC2 Terran gameplay screenshot, directly viewed in browser. Observed beveled steel housing, asymmetric upper plate, recessed screen, fasteners, narrow vents and small lights. New frame is locally authored inline SVG; source image is not embedded, downloaded or uploaded.',officialCandidate:'https://news.blizzard.com/en-us/article/5740272/game-guide-terran-unit-combos',unavailable:'Linked legacy us.media.blizzard.com screenshot had a certificate error; no security warning bypass.'},screenshots:screenRoot+'sc2-ui-r7/',records:screenRoot+'sc2-ui-r7/layout-records-r7.json',attempts:['First three viewport requests affected the reference tab; the measured viewport remained 829x738. Those records were retained separately as viewport-first-attempt.json and excluded. Returned to preview tab and confirmed requested viewport before actual captures.'],limitations:['No real phone/gamepad, no disconnected-browser check, no formal runtime tests, no game/balance/performance/human acceptance. Existing acceptance gaps remain open. Other prototype pages were not rerun for this minimap-only revision.']};
await fs.writeFile(new URL('revision-7/verification-r7.json',out),JSON.stringify(verification,null,2));
console.log(JSON.stringify({artifact:verification.artifact,layout:verification.layout,mainMapGeometryUnchanged:area.every(r=>r.unchangedFromR6)},null,2));
