import type {World} from '../../simulation/world';
import {ELITES,type EliteId} from '../../data/elites';
import {SC2_UNITS} from '../../data/sc2-units';
import {HEROES,type HeroId} from '../../data/heroes';
import {familyRetirementPreview} from '../../simulation/expedition-production';
import {rankLabel,unitCallsign} from '../unit-identity';
import {canClaimTalentLoot} from '../../simulation/progression/expedition-drafts';
import {draftContext} from '../../simulation/expedition-economy';
import {offerView} from './intermission';
import {gameText} from './game-copy';
import {button,glyph,image,money,esc,modal} from './reference-primitives';
import {referenceCard,referenceCardArt,referenceCardDetail,type CardView} from './reference-card';
const eliteView=(w:World,id:EliteId):CardView=>{const e=ELITES[id];return {id,race:w.expedition.race,rarity:'purple',name:e.name,kicker:SC2_UNITS[e.family].zh+' · 精锐',flavour:'专属战法，守住火线。',stat:gameText(e.description),detail:gameText(e.description),identity:id,icon:e.icon,art:'elite',rank:Math.min(5,(w.eliteOwned(id)?.rank??0)+1),bodies:e.family==='zergling'?2:1,free:true,minerals:0,gas:0};};
export const decisionSaveActions=(busy=false)=>`<div class="decision-archive-actions">${button(busy?'保存中…':'保存进度','save-now','text-button',busy?'disabled':'')}${button('导出存档','save-export','text-button')}</div>`;
function screen(name:string,subtitle:string,cards:CardView[],footer:string,detailId:string|null=null){const c=cards.find(c=>c.id===detailId);return `<div class="reward-screen formal-intermission decision-screen"><section class="intermission-screen"><header class="im-heading"><div class="im-title"><div><span class="im-eyebrow">${esc(subtitle)}</span><h1>${esc(name)}</h1></div></div></header><div class="im-choice-grid decision-grid">${cards.map((c,i)=>referenceCard({...c,detailAction:'ui-decision-info',detailAttrs:`data-id="${esc(c.id)}"`},i)).join('')||'<p class="im-empty">暂无可接收奖励的战士，奖励将保留。</p>'}</div><footer class="im-footer">${footer}</footer></section>${c?modal(c.name,c.kicker,referenceCardDetail(c),'im-detail-dialog',button('返回','decision-back','secondary')+button(c.label??'领取',c.action!,'primary',`${c.attrs??''} ${c.locked||c.owned||c.sold?'disabled':''}`),'decision-back'):''}</div>`;}
export function renderTalentLoot(w:World,detail:string|null,archive=''){const choice=w.expedition.pendingTalentLoot;if(!choice)return '';const cards=choice.offers.flatMap<CardView>(r=>{const e=r.expeditionEffect,attrs=`data-receipt="${choice.receipt}" data-id="${r.offerId}"`;return e.kind==='elite'?Object.values(ELITES).filter(v=>v.family===e.family).map(v=>({...eliteView(w,v.id),id:r.offerId+':'+v.id,rarity:choice.rarity,rank:e.targetRank??Math.min(5,(w.eliteOwned(v.id)?.rank??0)+1),action:'talent-loot',attrs:attrs+` data-variant="${v.id}"`,locked:!w.canAcquireElite(v.id),label:'免费领取'})): [{...offerView(w,r),free:true,short:false,locked:!canClaimTalentLoot(draftContext(w),r),action:'talent-loot',attrs,label:'免费领取'}];});return screen('出金大师',`${choice.rarity==='orange'?'传奇':'史诗'} · 免费奖励`,cards,archive+button('返回标题 · 保留选择','restart','secondary'),detail);}
export function renderEliteRescue(w:World,detail:string|null,archive=''){const right=w.eliteRescueChoice;if(!right)return '';const e=ELITES[right.eliteId as EliteId],cards=Object.values(ELITES).filter(v=>v.family===e.family).map(v=>({...eliteView(w,v.id),action:'elite-rescue-claim',attrs:`data-receipt="${right.receipt}" data-variant="${v.id}"`,locked:!w.canAcquireElite(v.id),label:'免费领取'}));return screen('精英救援',SC2_UNITS[e.family].zh+' · 选择一位精锐',cards,archive+button('放弃救援','elite-rescue-decline','secondary',`data-receipt="${right.receipt}"`)+button('返回标题 · 保留救援','restart','text-button'),detail);}
export function renderEliteMembers(w:World,id:EliteId,loaded:boolean,failed:boolean,target:number|null,shop=false,archive=''){const elite=ELITES[id],candidates=w.eliteCandidates(id),selected=candidates.find(u=>u.id===target)??candidates[0],attrs=shop?`data-id="${selected?.id??''}"`:`data-elite="${id}" data-id="${selected?.id??''}"`,c=eliteView(w,id),offer=w.rewards.find(r=>r.offerId===w.expedition.pendingShopElite?.offerId),contract=w.expedition.eliteContracts.find(c=>c.id===w.expedition.pendingShopElite?.offerId),price=offer??contract;
 return modal('晋升老兵',elite.name,`<div class="im-detail-layout"><div class="im-detail-art" data-card-race="${w.expedition.race}" data-quality="purple" data-kind="elite">${referenceCardArt(c,'promotion')}</div><div class="im-detail-copy"><p class="im-detail-rule">${esc(gameText(elite.description))}</p><div class="im-elite-confirm"><div><span>选择老兵</span><div class="im-members" role="group" aria-label="选择老兵">${candidates.map((u,i)=>`<button data-action="ui-decision-target" data-id="${u.id}" aria-pressed="${u.id===selected?.id}" aria-label="${esc(gameText(unitCallsign(u)))}，生命 ${Math.ceil(u.hp)} / ${Math.ceil(u.maxHp)}">${image('unit.'+u.unitType)}<b>${i+1}</b></button>`).join('')}</div>${selected?`<p>${esc(gameText(unitCallsign(selected)))} · ${rankLabel(selected.rank)}<br>生命 ${Math.ceil(selected.hp)} / ${Math.ceil(selected.maxHp)}</p>`:'<p>暂无可晋升战士。</p>'}</div></div><div class="im-detail-price">${shop&&price?money(price.minerals,price.gas):'免费编入'}</div>${loaded?'':`<p class="im-deficit" role="status">${failed?'增援未能就绪，请重试。':'增援准备中…'}</p>${button('重新准备','elite-assets-retry','small')}`}</div></div>`,'im-elite-dialog',archive+button(shop?'取消':'放弃编入',shop?'shop-elite-cancel':'elite-cancel','secondary',shop?'':`data-elite="${id}"`)+button(shop?'确认晋升':'确认编入',shop?'shop-elite-confirm':'elite-replace','primary',`${attrs} ${loaded&&selected?'':'disabled'}`),shop?'shop-elite-cancel':'restart');
}
export function renderSupplyReplacement(w:World){const p=w.expedition.pendingShopSupply,r=w.rewards.find(r=>r.offerId===p?.offerId),e=r&&(r as import('../../simulation/progression/expedition-drafts').ExpeditionReward).expeditionEffect;if(!p||e?.kind!=='supply')return '';return modal('接收增援','兵种 '+w.expedition.familySlots.length+' / 5',`<div class="incoming-family">${image('unit.'+e.family)}<div><h2>${SC2_UNITS[e.family].zh} ×${e.count}${e.family==='zergling'?'对':''}</h2><p>选择一支部队轮换</p></div></div><div class="family-list">${w.expedition.familySlots.map(f=>{const q=familyRetirementPreview(w,f);return `<button data-action="shop-supply-confirm" data-family="${f}">${image('unit.'+f)}<div><b>${SC2_UNITS[f].zh}</b><span>${q.members.map(u=>rankLabel(u.rank)+' → '+rankLabel(u.toRank)).join(' / ')||'暂无存活战士'}</span><small>返还 ${q.refund.minerals} 矿 / ${q.refund.gas} 气 · 已出发损失 ${q.lostPassengers} 名</small></div>${glyph('next')}</button>`;}).join('')}</div>`,'family-modal',button('取消 · 返回补给','shop-supply-cancel','secondary'),'shop-supply-cancel');}
