import type {World} from '../../simulation/world';
import {RACE_NAMES} from '../../data/races';
import {DIFFICULTY_COPY,RACE_VISUALS} from '../hud/m3-menu';
import {ENDLESS} from '../../data/endless';
import {button,image,glyph,masthead,money,modal,page,tags,title,esc,infoButton} from './reference-primitives';
const clock=(t:number)=>Math.floor(t/60).toString().padStart(2,'0')+':'+Math.floor(t%60).toString().padStart(2,'0');
const soldiers=(w:World)=>w.allies().filter(u=>!u.temporary&&!u.summonOwnerId).length;
export function renderPause(w:World,saveHtml:string){return modal('暂停',(w.endless?'无尽 '+w.endless.round:'第 '+w.stage+' 关')+' · '+(w.terrain?.definition?.source.name??'战役前线'),`<div class="pause-summary">${image('unit.'+RACE_VISUALS[w.expedition.race].unit)}<div><b>${RACE_NAMES[w.expedition.race]} / ${DIFFICULTY_COPY[w.difficulty].name}</b><span>${soldiers(w)} 名战士 · ${clock(w.time)}</span></div>${money(w.wallet.minerals,w.wallet.gas)}</div><nav class="pause-actions">${button(glyph('play')+' 继续','pause','primary','data-autofocus')}${button(glyph('save')+' 战局档案','pause-saves')}${button('整备部队','pause-production')}${button(glyph('gear')+' 操作与画质','settings')}${button(glyph('download')+' 导出','save-export')}${button('返回标题','restart','text-button')}</nav><p class="pause-hint">暂停中</p>`,'pause-modal','', 'pause');}
export function renderVictory(w:World,saveHtml:string,busy=false){const won=w.phase==='won',lost=w.phase==='lost',name=won?'胜利':lost?'小队失联':'撤离完成';return page(`${masthead('作战档案')}<section class="victory-page ${lost?'mission-lost':''}"><div class="victory-crest">${glyph(lost?'target':'shield')}<div class="victory-rays"></div></div><div class="victory-title"><span>${w.endless?'无尽战场':lost?'作战结束':'战役完成'}</span><h1>${name}</h1><p>${w.endless?'第 '+w.endless.round+' 轮 · '+clock(w.endlessElapsed):w.stage+' / 18'+(won?' · 主巢摧毁':'')}</p></div><div class="victory-stats"><div><span>${w.endless?'坚持时间':'完成关卡'}</span><b>${w.endless?clock(w.endlessElapsed):w.stage}<small>${w.endless?'':'/18'}</small></b></div><div><span>击杀</span><b>${w.stats.kills.toLocaleString('zh-CN')}</b></div><div><span>成功救援</span><b>${w.stats.rescued}</b></div><div><span>幸存战士</span><b>${soldiers(w)}</b></div></div><p class="victory-reward">${glyph('hex')}资源已结算</p><div class="victory-actions">${won?button('撤离','evacuate','secondary')+button('无尽 '+glyph('arrow'),'endless','primary'):button('返回标题','restart','primary')}</div><div class="victory-footer">${button(busy?'保存中…':'保存进度','save-now','text-button',busy?'disabled':'')}${button('导出战局档案','save-export','text-button')}${won?button('返回标题','restart','text-button'):''}</div><div data-player-services-host></div></section>`,'end-screen formal-ending');}
export function renderEndless(w:World,mapPreview=''){return page(`${masthead('无尽整备')}${title('无尽','endless-back')}<section class="endless-layout"><div class="endless-map panel">${mapPreview?`<img class="endless-map-image" src="${mapPreview}" alt="当前部队与战区">`:'<div class="endless-live-map" aria-label="无尽作战区域">'+glyph('target')+'</div>'}<div class="endless-map-label"><h2>无尽战场</h2><span>据点防线</span></div></div><aside class="endless-info"><h2>下一片前线</h2>${tags([ENDLESS.roundDuration+' s / 轮','4 轮 / 发展'])}<div class="endless-checklist"><div>${glyph('check')}部队</div><div>${glyph('check')}伤损 / 冷却</div><div>${glyph('check')}生产订单</div></div>${infoButton('无尽战场','一轮守住 '+ENDLESS.roundDuration+' 秒，每四轮返回基地整备。部队、伤损、技能冷却和训练、空投订单随行。')}${button('整备','pause-production','secondary')}${button('出发 '+glyph('arrow'),'endless-prepare','primary')}</aside></section><div class="screen-bottom">${button('导出存档','save-export','text-button')}${button('返回标题','restart','text-button')}</div>`,'end-screen formal-endless');}
