/** Player-facing translations only. Stored definitions and combat values stay intact. */
export const ATTR_NAMES:Record<string,string>={Light:'轻甲',Armored:'重甲',Biological:'生物',Mechanical:'机械',Massive:'巨型',Psionic:'灵能',Heroic:'英雄',Structure:'建筑'};
export const WEAPON_NAMES:Record<string,string>={marine:'高斯步枪',marauder:'惩罚者榴弹',tank:'坦克炮',medivac:'医疗束',reaper:'双持手枪',hellion:'地狱火喷射器',thor:'雷神之锤',viking:'飞弹',banshee:'背冲火箭',science_vessel:'纳米修复',zergling:'利爪',baneling:'酸液爆破',roach:'酸液',ravager:'等离子喷射',hydralisk:'骨针',queen:'毒刺',lurker:'地刺',mutalisk:'刃虫',corruptor:'腐蚀喷吐',ultralisk:'巨刃',zealot:'灵能双刃',adept:'共鸣刃',stalker:'粒子裂解炮',sentry:'裂解光束',immortal:'相位裂解炮',colossus:'热能射线',high_templar:'灵能之力',phoenix:'离子炮',void_ray:'棱镜光束',carrier:'截击机'};
export const NATIVE_ABILITIES:Record<string,readonly [string,string]>={
 marine:['兴奋剂','注入兴奋剂，短时提高射击与移动速度。'],marauder:['重甲猎手','榴弹擅长击穿重甲，只能攻击地面敌人。'],tank:['攻城模式','架起炮台，轰击远处的地面敌群。收炮后恢复移动。'],medivac:['战地医疗','持续治疗受伤友军。生物单位全效，机械单位为三分之一；仅为实际恢复的生命消耗能量。'],science_vessel:['纳米修复','机械单位全效修复，生物单位为三分之一；仅为实际恢复的生命消耗能量。'],reaper:['越障突击','翻越高低地形，凭双枪追击敌人。'],hellion:['烈焰突击','喷出火焰打击前方敌人；可切换为恶火，以扇形火焰守住近处战线。'],thor:['重型火力','以重装武器压制敌军，分别使用对地和对空火力。'],viking:['变形突击','空中模式攻击飞行敌人；突击模式落地后攻击地面敌人。'],banshee:['隐形行动','隐匿身形，以背冲火箭打击地面敌人。'],
 zergling:['双生虫群','两只跳虫并肩作战，各自承受伤害。一只存活时，另一只可在 15 秒后再生。'],roach:['甲壳恢复','以厚重甲壳顶住前线，喷吐酸液攻击地面敌人。'],hydralisk:['骨针齐射','从地面到天空，都在骨针射程之内。'],queen:['虫群支援','以毒刺掩护虫群，消耗能量施展治疗。'],baneling:['爆裂重生','撞向敌人并引爆酸囊，进入 5 秒恢复后重新参战。'],ravager:['腐蚀胆汁','向指定区域喷出胆汁，击中范围内的敌人。'],lurker:['潜地伏击','潜入地下后以地刺贯穿地面敌军；移动前需要钻出地面。'],mutalisk:['刃虫弹射','飞行中喷出刃虫，向附近敌人弹射。'],corruptor:['空中猎杀','以腐蚀喷吐攻击飞行敌人。'],ultralisk:['巨刃横扫','以巨刃横扫近处地面敌人。'],
 zealot:['冲锋','接近地面敌人，以双刃切入战线。'],adept:['共鸣刃','以共鸣刃打击地面敌人，擅长对付轻甲目标。'],stalker:['闪烁','瞬移到附近位置，穿梭于敌军火力之间。'],immortal:['屏障','迎击敌军火力时张开屏障，抵挡一轮冲击。'],sentry:['守护之盾','消耗能量撑起守护场，为附近友军挡下部分火力。'],colossus:['热能切割','双束热能射线横扫地面敌军。'],high_templar:['灵能风暴','消耗能量释放灵能风暴，以范围火力覆盖敌群。'],phoenix:['引力光束','升起可以被牵引的地面目标，在空中迎击敌人。'],void_ray:['棱镜光束','持续照射目标，积蓄棱镜火力。'],carrier:['机库','截击机离舰作战。损失会削弱火力，补充需要资源与时间。']
};
export const HERO_PASSIVES:Record<string,string>={raynor:'游骑兵火力',tychus:'旋转机炮',nova:'隐秘行动',swann:'战地工程',tosh:'幽魂火力',yamato_battlecruiser:'重装舰炮',kerrigan:'灵能护障',zagara:'孵化狂潮',dehaka:'原始进化',stukov:'感染蔓延',niadra:'寄生疗愈',hots_leviathan:'深空触须',artanis:'灵能双刃',zeratul:'虚空回响',fenix:'太阳过载',alarak:'权势',vorazun:'暗影突袭',purifier_flagship:'舰队火网'};
export const gameText=(value:string)=>value.replace('首目标全包，后排每敌一次80%；地空贯穿分层，不隔山射击。','主目标承受全部伤害；贯穿后方敌人时，每个敌人承受一次 80% 伤害。地面与空中攻击各自贯穿；地形会阻挡攻击。').replace('不能把新五倍再乘旧模板同类充能，直接替换。','五倍伤害替代原有的同类充能加成，不叠加。').replace(/Boss|boss|BOSS/g,'首领').replace(/\bMVP\s*1\.0\b|TAL-[A-Z]\d+[^，。；]*|见\s*\d+(?:\.\d+)+|第\s*\d+(?:\.\d+)+\s*节|已批准(?:提案)?/g,'').replace(/英雄席位/g,'英雄名额').replace(/(?:同系|同族|独立)?席位/g,'编制').replace(/家族槽(?:位)?/g,'兵种编制').replace(/家族/g,'兵种').replace(/型号/g,'种类').replace(/\bRank\s*/gi,'军衔 ').replace(/\bHP\b/g,'生命').replace(/\bLight\b|\bArmored\b|\bBiological\b|\bMechanical\b|\bMassive\b|\bPsionic\b|\bHeroic\b/g,v=>ATTR_NAMES[v]??v).replace(/\d+\.\d{6,}/g,n=>String(Number(Number(n).toFixed(4)))).replace(/\s*·\s*·/g,' · ').trim();
