import {heroAbilityCopy} from './ability-copy';
import type {World} from '../../simulation/world';
import type {Reward} from '../../simulation/types';
import {EXPEDITION_CARD_DEFINITIONS,type ExpeditionReward,type ExpeditionCardEffect} from '../../simulation/progression/expedition-drafts';
import {TEAM_CARD_VALUES} from '../../simulation/progression/team-cards';
import {supplyPrice} from '../../simulation/progression/supply-cards';
import {HEROES,type HeroId} from '../../data/heroes';
import {ELITES,type EliteId} from '../../data/elites';
import {SC2_UNITS} from '../../data/sc2-units';
import {FAMILIES_BY_RACE,RACES,RACE_NAMES,type Race,type FamilyId} from '../../data/races';
import {PRODUCTION_LINES,DEVELOPMENT} from '../../data/expedition-buildings';
import {UNIQUE_SUPPORT} from '../../data/unique-support';
import {RARITIES,type Rarity} from '../../data/rewards';
import {renderExpeditionProduction,renderRepairs,renderProductionWindow} from '../hud/expedition-panel';
import {rewardOwnership,rankLabel} from '../unit-identity';
import {paintedArt} from './painted-art';
import {button,image,glyph,money,esc,modal} from './reference-primitives';
import {referenceCard,referenceCardArt,referenceCardDetail,type CardView} from './reference-card';
import {gameText,NATIVE_ABILITIES} from './game-copy';
import {MenuHistory} from './navigation';
import {CARD_PRESENTATION} from './card-presentation.generated';
import {draftContext,offerEligible} from '../../simulation/expedition-economy';
export type IntermissionRoute={page:'root'|'menu'|'direction'|'production'|'rest'|'heroes'|'contracts'|'catalog'}|{page:'offer';id:string}|{page:'elite';id:string;variant:EliteId;contract?:boolean}|{page:'contract';id:string}|{page:'catalog-detail';id:string};
export type CatalogueGroup='all'|'ordinary'|'elite'|'hero'|'development'|'support'|'training'|'team'|'supply'|'economy'|'efficiency';
export class IntermissionNavigation extends MenuHistory<IntermissionRoute>{
 private context='';filter:CatalogueGroup='ordinary';race:Race|'all'='all';quality:Rarity|'all'='all';query='';page=0;variant:EliteId|null=null;productionTab:'production'|'orders'|'plans'='production';
 constructor(){super({page:'root'});}
 sync(w:World){const key=[w.runId,w.phase,w.rewardRound,w.expedition.draftWindow].join(':');if(key!==this.context){this.context=key;this.variant=null;this.page=0;this.reset();}}
}
const cost=(m:number,g:number)=>`${m} 矿${g?' / '+g+' 气':''}`;
const effect=(r:Reward)=>(r as ExpeditionReward).expeditionEffect;
const family=(r:Reward)=>{const e=effect(r);return e&&'family' in e?e.family:undefined;};
const qualityList:Rarity[]=['white','green','blue','purple','orange'];
const groupNames:Record<CatalogueGroup,string>={all:'全部',ordinary:'作战单位',elite:'精锐特色',hero:'英雄',development:'基地建设',support:'种族战术',training:'晋升',team:'全军强化',supply:'援军',economy:'补给',efficiency:'战地后勤'};
const trim=(s:string)=>gameText(s);
const SUPPORT_COPY:Record<string,{names:readonly string[];rarity:Rarity;copy:string}>={
 mines:{names:['蜘蛛雷','爆裂虫卵','灵能地雷'],rarity:'green',copy:'每关布置 6 / 9 / 12 枚地雷，最多三层；伤害 120，爆炸半径 2，触发距离 1.2。人族蜘蛛雷会钻出地面并追击目标。'},
 bombardment:{names:['炮火轰炸','酸液轰炸','轨道轰击'],rarity:'blue',copy:'每 20 / 15 / 10 秒轰炸可见敌军，最多三层；预警 0.75 秒，伤害 180，半径 2.5。'},
 mutation:{names:['燃烧弹','腐蚀弹','灼能弹'],rarity:'purple',copy:'本族主力的普通攻击追加 3 秒持续伤害：本次伤害的 30% / 45% / 60%。同一来源与目标最多保留三次灼烧。'},
 strategic:{names:['核弹','生体巨爆','净化打击'],rarity:'orange',copy:'获得一枚战略打击弹药。指定落点，3 秒后造成 3000 伤害，半径 8。'}
};
export function offerPrice(w:World,r:Reward){const receipt=(r as ExpeditionReward).purchaseReceipt;return r.sold?(receipt?.freeSource?'已获得 · 天赋免单':'已获得'):w.rewardRound==='random'&&w.expedition.freePurchasesRemaining>0?'天赋免单':cost(r.minerals,r.gas);}
/** Actual training targets, including each paired body, are painted without changing unit scale. */
export function offerView(w:World,r:Reward):CardView{
 const e=effect(r),f=family(r),base:CardView={id:r.offerId,race:w.expedition.race,rarity:r.rarity,name:gameText(r.name),kicker:'战备补给',flavour:'前线待命，补给就绪。',stat:trim(r.description),detail:gameText(r.description)+' '+gameText(rewardOwnership(w,r)),art:'technology',icon:r.icon,minerals:r.minerals,gas:r.gas,baseMinerals:r.baseMinerals,baseGas:r.baseGas,discount:r.discount,sold:r.sold,free:w.rewardRound==='random'&&w.expedition.freePurchasesRemaining>0&&!r.sold,short:!r.sold&&!(w.rewardRound==='random'&&w.expedition.freePurchasesRemaining>0)&&(w.wallet.minerals<r.minerals||w.wallet.gas<r.gas),locked:!r.sold&&!offerEligible(w,r),action:'reward',detailAction:'ui-offer',label:r.sold?'已获得':'购买',attrs:`data-id="${esc(r.offerId)}"`};
 if(e?.kind==='hero'){const h=HEROES[e.heroId as HeroId],owned=w.heroes.get(e.heroId as HeroId);Object.assign(base,{identity:e.heroId,art:'hero',kicker:'英雄 · '+RACE_NAMES[w.expedition.race],flavour:'听候召唤，奔赴前线。',rank:Math.min(5,(owned?.rank??0)+1),action:'ui-offer',label:'查看英雄',stat:h.skill,detail:`${h.skill}：${heroAbilityCopy(e.heroId as HeroId).active} ${heroAbilityCopy(e.heroId as HeroId).passive} ${gameText(r.description)}`});}
 else if(e?.kind==='training'){const identities=e.targets.flatMap(t=>Array(t.family==='zergling'?2:1).fill(t.family));Object.assign(base,{identity:identities[0],bodyIdentities:identities,bodies:identities.length,art:'training',kicker:'士兵晋升',flavour:'历经战火，晋升精锐。',rank:e.rank,stat:e.targets.map(t=>SC2_UNITS[t.family].zh+' '+rankLabel(t.rank)+' → '+rankLabel(e.rank)).join(' · '),detail:'晋升 '+e.targets.map(t=>SC2_UNITS[t.family].zh+' '+rankLabel(t.rank)+' → '+rankLabel(e.rank)).join('；')+'。'+gameText(r.description)});}
 else if(e?.kind==='elite'){const id=e.eliteId as EliteId,elite=ELITES[id];Object.assign(base,{identity:id,art:'elite',kicker:'精锐 · '+SC2_UNITS[e.family].zh,flavour:'专属战法，守住火线。',rank:e.targetRank??Math.min(5,(w.eliteOwned(id)?.rank??0)+1),stat:trim(elite?.description??r.description),detail:gameText(elite?.description??r.description)+' '+gameText(rewardOwnership(w,r)),bodies:e.family==='zergling'?2:1,action:'ui-offer',label:'挑选精锐'});}
 else if(e?.kind==='supply')Object.assign(base,{identity:e.family,art:'supply',kicker:e.mode==='pod'?'救援空投':'即刻增援',flavour:{terran:'补给抵达，火力就绪。',zerg:'巢穴已醒，虫群涌来。',protoss:'折跃就绪，听候召唤。'}[w.expedition.race],bodies:e.count*(e.family==='zergling'?2:1),count:e.count,paired:e.family==='zergling'});
 else if(f)Object.assign(base,{identity:f,bodies:f==='zergling'?2:1,art:e?.kind==='card'?({weapon:'firepower',vitality:'defense',armor:'defense',recovery:'recovery',energy:'energy',production:'production',cultivation:'training'})[e.effect]:'unit',kicker:SC2_UNITS[f].zh+' · 强化'});
 else if(e?.kind==='development'){const d=DEVELOPMENT.find(d=>d.id===e.definitionId);Object.assign(base,{identity:d?.unlock==='family'?d.families[0]:undefined,art:d?.kind==='facility'?'facility':d?.unlock==='family'?'unit':'technology',kicker:d?.kind==='facility'?'生产设施':d?.kind==='research'?'路线研究':'兵种科技',flavour:'基地整备，支援前线。',rank:d?.kind==='research'?e.expectedLevel+1:undefined,bodies:d?.families[0]==='zergling'?2:1});}
 else if(e?.kind==='teamCard')Object.assign(base,{art:e.group==='firepower'?'firepower':'defense',kicker:'全军强化',flavour:'并肩作战，越战越强。'});
 else if(e?.kind==='resource')Object.assign(base,{art:'energy',kicker:'资源补给',flavour:'补给不断，战线不熄。'});
 else if(e?.kind==='support')Object.assign(base,{art:e.support.includes('.')?e.support.split('.')[1]:e.support,kicker:'种族战术',flavour:'备好战术，迎击敌军。'});
 // Reuse individual approved flavour and engravings. Obsolete elite mechanics
 // are excluded: their current approved identity/description above governs.
 const meta=e?.kind==='elite'?null:CARD_PRESENTATION.find(c=>c.race===w.expedition.race&&(e?.kind==='development'?c.sourceId===e.definitionId:e?.kind==='hero'?c.heroId===e.heroId&&c.rank===base.rank:e?.kind==='training'?c.group==='training'&&c.rank===e.rank:e?.kind==='supply'?c.sourceId===`supply.${e.mode}.${e.family}.${e.count}`:e?.kind==='teamCard'?c.sourceId===`team.${e.group}.${e.rarity}`:e?.kind==='card'?c.subtype===e.effect&&c.family===e.family:e?.kind==='support'?c.sourceId===`support.${e.support.includes('.')?e.support:w.expedition.race+'.'+e.support}`:e?.kind==='resource'?c.group==='economy'&&c.sourceId===r.id:null));
 if(meta){base.flavour=gameText(meta.flavour);base.kicker=gameText(meta.kicker);base.art=meta.art;base.icon=meta.icon;}
 if(e?.kind==='support'&&SUPPORT_COPY[e.support])base.detail=SUPPORT_COPY[e.support].copy;
 return base;
}
export function offerArt(r:Reward,w?:World){if(w)return referenceCardArt(offerView(w,r));const e=effect(r),f=family(r);if(e?.kind==='training'){const ids=e.targets.flatMap(t=>Array(t.family==='zergling'?2:1).fill(t.family));return paintedArt(ids[0],r.name,ids.length,r.offerId,ids);}if(e?.kind==='hero')return paintedArt(e.heroId,r.name,1,r.offerId);if(f)return paintedArt(e?.kind==='elite'?e.eliteId:f,r.name,e?.kind==='supply'?e.count*(f==='zergling'?2:1):f==='zergling'?2:1,r.offerId);return `<span class="im-emblem">${image(r.icon,r.name)}</span>`;}
type CatalogItem={id:string;name:string;art?:string;icon?:string;copy:string};
/** Base identities remain a pure, stable read API. Catalogue variants are derived below. */
export function catalogue(w:World,filter:CatalogueGroup,race=w.expedition.race):CatalogItem[]{
 if(filter==='ordinary')return FAMILIES_BY_RACE[race].map(f=>({id:f,name:SC2_UNITS[f].zh,art:f,copy:`${SC2_UNITS[f].flying?'空中':'地面'}单位 · 生命 ${SC2_UNITS[f].maxHp} · 护甲 ${SC2_UNITS[f].armor} · 移速 ${SC2_UNITS[f].movementSpeed.toFixed(2)}。武器 ${SC2_UNITS[f].attackDamage} × ${SC2_UNITS[f].attacks}，周期 ${SC2_UNITS[f].attackPeriod.toFixed(2)} 秒，射程 ${SC2_UNITS[f].attackRange}。${NATIVE_ABILITIES[f]?.[1]??''}`}));
 if(filter==='elite')return Object.values(ELITES).filter(e=>FAMILIES_BY_RACE[race].includes(e.family as never)).map(e=>({id:e.id,name:e.name,art:e.id,copy:gameText(e.description)}));
 if(filter==='hero')return Object.entries(HEROES).filter(([,h])=>h.race===race).map(([id,h])=>({id,name:h.name,art:id,copy:`${h.skill}：${heroAbilityCopy(id as HeroId).active} ${heroAbilityCopy(id as HeroId).passive}`}));
 if(filter==='development')return DEVELOPMENT.filter(d=>d.race===race).map(d=>({id:d.id,name:d.name,art:d.unlock==='family'?d.families[0]:undefined,icon:d.kind==='facility'?'building.'+d.id:'tech.attack',copy:`${d.kind==='facility'?'生产设施':d.kind==='research'?'研究':'科技'} · ${d.line?PRODUCTION_LINES[d.line].name:'基础设施'} · 最高 ${d.maxLevel} 级。${d.kind==='facility'?'增加生产设施。':d.unlock==='family'?'解锁兵种的持续生产。':'同类设施与新造部队共享。'}${d.requires.length?'前置：'+d.requires.map(id=>DEVELOPMENT.find(x=>x.id===id)?.name??'相关科技').join(' / ')+'。':''}`}));
 if(filter==='support')return Object.entries(UNIQUE_SUPPORT).filter(([,s])=>s.race===race).map(([id,s])=>({id,name:s.name,icon:'tech.boost',copy:s.description}));
 return Object.entries(EXPEDITION_CARD_DEFINITIONS).map(([id,d])=>({id,name:d.name,icon:'tech.attack',copy:`白 / 绿 / 蓝 / 紫 / 橙：${d.values.join(' / ')}。累计上限 ${d.cap}。`}));
}
type CatalogueCard=CardView&{group:CatalogueGroup};
let catalogueDefinitionCache:readonly CatalogueCard[]|null=null;
function cardEffectCopy(e:ExpeditionCardEffect,v:number){return e==='cultivation'?`普通士兵共获得 ${v} 点培养；优先军衔最低者。`:e==='armor'?`本兵种护甲 +${v}。`:({weapon:'主武器伤害',vitality:'生命与护盾',recovery:'治疗与修复',energy:'能量恢复',production:'训练周转'})[e]+` +${Number((v*100).toFixed(2))}%。`;}
export function catalogueCards(w:World):readonly CatalogueCard[]{if(catalogueDefinitionCache)return catalogueDefinitionCache;const result:CatalogueCard[]=[],context=draftContext(w);
 for(const race of RACES){for(const group of ['ordinary','elite','hero','development','support'] as const)for(const c of catalogue(w,group,race)){const elite=ELITES[c.id as EliteId],d=DEVELOPMENT.find(d=>d.id===c.id),support=UNIQUE_SUPPORT[c.id as keyof typeof UNIQUE_SUPPORT];result.push({id:race+':'+c.id,race,group,rarity:group==='hero'?'orange':group==='elite'?'purple':support?.rarity??'white',name:c.name,kicker:groupNames[group],flavour:group==='hero'?'听候召唤，奔赴前线。':group==='elite'?'专属战法，守住火线。':'整备就绪，奔赴前线。',stat:trim(c.copy),detail:gameText(c.copy),identity:c.art,icon:c.icon??(group==='hero'?'hero.':'unit.')+(elite?.family??c.id),art:group==='hero'?'hero':group==='elite'?'elite':group==='ordinary'||d?.unlock==='family'?'unit':d?.kind==='facility'?'facility':'technology',bodies:(elite?.family??c.art)==='zergling'?2:1});}
  for(const f of FAMILIES_BY_RACE[race]){
   for(const mode of ['pod','direct'] as const)for(let count=1;count<=3;count++){const price=supplyPrice(f,count,mode);result.push({id:`${race}:supply.${mode}.${f}.${count}`,race,group:'supply',rarity:qualityList[count-1+(mode==='direct'?1:0)],name:SC2_UNITS[f].zh,kicker:mode==='pod'?'救援空投':'即刻增援',flavour:{terran:'补给抵达，火力就绪。',zerg:'巢穴已醒，虫群涌来。',protoss:'折跃就绪，听候召唤。'}[race],stat:mode==='pod'?'空投后救援':'立即加入小队',detail:(mode==='pod'?'通过救援空投加入。':'直接加入小队。')+'不解锁持续生产；需要生产设施、对应研究与剩余编制。所示为基础费用，战况与天赋可改变报价。',identity:f,icon:'unit.'+f,art:'supply',count,paired:f==='zergling',bodies:count*(f==='zergling'?2:1),...price});}
   for(const [id,d] of Object.entries(EXPEDITION_CARD_DEFINITIONS))for(const [i,v] of d.values.entries()){const e=id as ExpeditionCardEffect,capability=context.familyInfo(f);if(e==='weapon'&&!capability.canAttack||e==='recovery'&&!capability.canSupport||e==='energy'&&!capability.usesEnergy)continue;const detail=cardEffectCopy(e,v);result.push({id:`${race}:card.${e}.${f}.${qualityList[i]}`,race,group:'efficiency',rarity:qualityList[i],name:SC2_UNITS[f].zh+' · '+d.name,kicker:d.name,flavour:'整备部队，守住前线。',stat:detail,detail:detail+`累计上限 ${e==='armor'||e==='cultivation'?d.cap:Number((d.cap*100).toFixed(2))+'%'}；需要符合条件的本兵种。`,identity:f,icon:'unit.'+f,art:({weapon:'firepower',vitality:'defense',armor:'defense',recovery:'recovery',energy:'energy',production:'production',cultivation:'training'})[e],bodies:f==='zergling'?2:1});}
  }
  for(let rank=2;rank<=5;rank++){const f=FAMILIES_BY_RACE[race][0];result.push({id:`${race}:training.${rank}`,race,group:'training',rarity:qualityList[rank-1],name:'士兵晋升',kicker:'士兵晋升',flavour:'历经战火，晋升精锐。',stat:'两名普通士兵晋升 '+rankLabel(rank),detail:'军衔最低的两名普通士兵晋升。具体部队与费用在商店报价时确定。跳虫每对晋升两只身体。',identity:f,icon:'unit.'+f,art:'training',rank,bodies:f==='zergling'?4:2});}
  for(const [i,rarity] of qualityList.entries())for(const g of ['firepower','defense'] as const){const detail=g==='firepower'?`伤害 +${TEAM_CARD_VALUES.damage[i]*100}% · 攻速 +${TEAM_CARD_VALUES.speed[i]*100}%`:`生命与护盾 +${TEAM_CARD_VALUES.health[i]*100}% · 护甲 +${TEAM_CARD_VALUES.armor[i]}`;result.push({id:`${race}:team.${g}.${rarity}`,race,group:'team',rarity,name:g==='firepower'?'全军火力':'全军防御',kicker:'全军强化',flavour:'并肩作战，越战越强。',stat:detail,detail:detail,icon:g==='firepower'?'tech.attack':'tech.armor',art:g});}
  for(const [id,name,m,g] of [['minerals','矿物补给',100,0],['gas','瓦斯补给',0,50],['salvage','战地回收',75,25],['supply','补给运输',100,25]] as const)result.push({id:`${race}:economy.${id}`,race,group:'economy',rarity:'white',name,kicker:'资源补给',flavour:'补给不断，战线不熄。',stat:`获得 ${m} 矿物 / ${g} 瓦斯`,detail:`获得 ${m} 矿物 / ${g} 瓦斯。`,icon:g&&!m?'ui.gas':'ui.minerals',art:'energy'});
 }
 for(const race of RACES)for(const [id,d] of Object.entries(EXPEDITION_CARD_DEFINITIONS))result.push({id:race+':'+id,race,group:'efficiency',rarity:'white',name:d.name,kicker:'培养总览',flavour:'整备部队，守住前线。',stat:cardEffectCopy(id as ExpeditionCardEffect,d.values[0]),detail:d.values.map((v,i)=>RARITIES[qualityList[i]].name+'：'+cardEffectCopy(id as ExpeditionCardEffect,v)).join(' ')+' 累计上限 '+d.cap,icon:'tech.attack',art:'training'});
 for(const race of RACES)for(const [id,d] of Object.entries(SUPPORT_COPY)){const meta=CARD_PRESENTATION.find(c=>c.race===race&&c.sourceId===`support.${race}.${id}`);result.push({id:`${race}:support.${race}.${id}`,race,group:'support',rarity:d.rarity,name:d.names[RACES.indexOf(race)],kicker:meta?.kicker??'种族战术',flavour:meta?.flavour??'备好战术，迎击敌军。',stat:d.copy.split('；')[0],detail:d.copy,icon:meta?.icon??'tech.attack',art:meta?.art??id});}
 for(const c of result){const id=c.id.slice(c.id.indexOf(':')+1),meta=c.group==='elite'?null:CARD_PRESENTATION.find(p=>p.race===c.race&&(c.group==='hero'?p.heroId===id&&p.rank===1:c.group==='ordinary'?p.subtype==='unlock'&&p.family===c.identity:p.sourceId===id));if(meta){c.flavour=gameText(meta.flavour);c.kicker=gameText(meta.kicker);c.art=meta.art;c.icon=meta.icon;}c.stat=gameText(c.stat);c.detail=gameText(c.detail);}
 catalogueDefinitionCache=result;return result;
}
const countPages=()=>((typeof document==='undefined'?1280:document.querySelector('#game-root')?.clientWidth??1280)>900?6:3);
function library(w:World,nav:IntermissionNavigation){const all=catalogueCards(w).filter(c=>(nav.race==='all'||c.race===nav.race)&&(nav.filter==='all'||c.group===nav.filter)&&(nav.quality==='all'||c.rarity===nav.quality)&&(!nav.query||(c.name+c.kicker+c.detail).includes(nav.query))),size=countPages(),pages=Math.max(1,Math.ceil(all.length/size)),page=Math.min(nav.page,pages-1);
 return `<header class="im-heading"><div class="im-title">${button(glyph('back'),'ui-back','im-back','aria-label="返回商店"')}<div><span class="im-eyebrow">作战图鉴</span><h1>卡片图鉴</h1></div></div><span class="im-library-total">${all.length} <small>张</small></span></header><div class="im-library-filters"><div class="im-races" role="group" aria-label="卡片种族">${(['all',...RACES] as const).map(r=>button(r==='all'?'全种族':RACE_NAMES[r],'ui-catalog-race','',`data-race="${r}" aria-pressed="${nav.race===r}"`)).join('')}</div><div class="im-filter-selects"><label><span class="sr-only">卡片类别</span><select aria-label="卡片类别" data-catalog-filter="group">${Object.entries(groupNames).map(([id,name])=>`<option value="${id}" ${nav.filter===id?'selected':''}>${name}</option>`).join('')}</select></label><label><span class="sr-only">卡片品质</span><select aria-label="卡片品质" data-catalog-filter="quality"><option value="all">全部品质</option>${qualityList.map(id=>`<option value="${id}" ${nav.quality===id?'selected':''}>${RARITIES[id].name}</option>`).join('')}</select></label><input class="im-search" type="search" placeholder="搜索卡片" aria-label="搜索卡片" data-catalog-filter="query" value="${esc(nav.query)}"></div></div><div class="im-catalogue-grid" aria-label="卡片图鉴列表">${all.slice(page*size,(page+1)*size).map((c,i)=>referenceCard({...c,action:'ui-catalog-detail',detailAction:'ui-catalog-detail',attrs:`data-id="${c.id}"`},i,true)).join('')||'<p class="im-empty">没有找到这张卡片。</p>'}</div><footer class="im-footer im-catalogue-footer"><span class="im-status">作战图鉴 · 费用以战场报价为准</span><div class="im-pagination">${button(glyph('back'),'ui-catalog-prev','secondary',`aria-label="上一页卡片" ${page===0?'disabled':''}`)}<span>${page+1} / ${pages}</span>${button(glyph('next'),'ui-catalog-next','secondary',`aria-label="下一页卡片" ${page===pages-1?'disabled':''}`)}</div></footer>`;
}
function eliteChoices(w:World,f:FamilyId,id:string,nav:IntermissionNavigation,contract=false,r?:Reward){const variants=Object.values(ELITES).filter(e=>e.family===f),selected=variants.find(e=>e.id===nav.variant)??variants[0],c=w.expedition.eliteContracts.find(c=>c.id===id),price=contract?c:r,owned=w.eliteOwned(selected.id),enabled=w.canAcquireElite(selected.id)&&(contract?!!c&&!c.purchased&&w.wallet.minerals>=c.minerals&&w.wallet.gas>=c.gas:!!r&&w.canChooseReward(r));
 return modal('挑选精锐',SC2_UNITS[f].zh,`<div class="im-elite-choices" role="radiogroup" aria-label="精锐种类">${variants.map(e=>{const v:CardView={id:e.id,race:w.expedition.race,rarity:r?.rarity??'purple',name:e.name,kicker:'精锐',flavour:'',stat:trim(e.description),detail:gameText(e.description),identity:e.id,icon:e.icon,art:'elite',bodies:f==='zergling'?2:1};return `<button class="im-elite-choice ${selected.id===e.id?'selected':''}" role="radio" aria-checked="${selected.id===e.id}" data-action="ui-variant-select" data-variant="${e.id}" data-card-race="${v.race}" data-quality="${v.rarity}">${referenceCardArt(v,'variant')}<div><span class="im-elite-rank">${w.eliteOwned(e.id)?rankLabel(w.eliteOwned(e.id)!.rank):'Ⅰ'} · 精锐</span><h3>${esc(e.name)}</h3><p>${esc(v.stat)}</p></div><i class="im-radio" aria-hidden="true">${selected.id===e.id?glyph('check'):''}</i></button>`;}).join('')}</div><div class="im-elite-confirm"><div><span>${owned?'晋升精锐':'招募精锐'}</span><p class="im-selected-rule">${esc(gameText(selected.description))}</p></div><div class="im-elite-price">${price?money(price.minerals,price.gas):'报价已结束'}</div></div>`,'im-elite-dialog',button('取消','ui-back','secondary')+button(owned?.rank===5?'已达上限':owned?'晋升':'招募',contract?'elite-contract':'reward','primary',`data-id="${esc(id)}" data-variant="${selected.id}" ${enabled?'':'disabled'}`));
}
export function restCards(w:World):CardView[]{
 const race=w.expedition.race,quote=w.previewRepair(w.allies().filter(u=>!u.temporary&&!u.summonOwnerId).map(u=>u.id)),hurt=!!quote&&quote.health>0,canPay=!!quote&&w.wallet.minerals>=quote.minerals&&w.wallet.gas>=quote.gas;
 const result:CardView[]=[{id:'repair',race,rarity:'white',name:'修复部队',kicker:'战地休整',flavour:'补好伤口，重新列队。',stat:hurt?'恢复 '+Math.ceil(quote.health)+' 生命':'生命已满',detail:'可选择全队或一个兵种。费用按当前缺失生命计算；生命已满时无需支付。',icon:'tech.heal',art:'recovery',minerals:quote?.minerals??0,gas:quote?.gas??0,action:'repair-all',attrs:`data-family="" data-quote="${esc(quote?.id??'')}"`,detailAction:'ui-rest-repair',detailAttrs:'',owned:!hurt,short:hurt&&!canPay,label:hurt?'修复全队':'无需修复'}];
 for(const [id,h] of w.heroes){const alive=!!w.heroEntity(id)?.hp,p=w.revivalCost(h.rank),pending=h.revivePaid||h.awaitingSpawn,detail='复活这位 '+rankLabel(h.rank)+' 级英雄。'+(alive?'英雄仍在队伍，无需复活。':pending?'已支付复活费用，下关归队。':'保留原有军衔，下关归队。');result.push({id,race,rarity:'orange',name:HEROES[id].name,kicker:'英雄复活',flavour:'战场，还在等你回来。',stat:alive?'在队':pending?'下关归队':'阵亡 → 返回队伍',detail,identity:id,icon:'hero.'+id,art:'hero',rank:h.rank,minerals:p.minerals,gas:p.gas,owned:alive,pending,locked:!w.canReviveHero(id),reason:alive?'在队':pending?(h.awaitingSpawn?'待部署':'下关归队'):w.phase!=='reward'?'休整时复活':undefined,short:!alive&&!pending&&(w.wallet.minerals<p.minerals||w.wallet.gas<p.gas),action:'revive',attrs:`data-id="${id}"`,detailAction:'ui-info',detailAttrs:`data-title="${esc(HEROES[id].name)}" data-copy="${esc(detail)}"`,label:alive?'在队':pending?'已安排':'复活'});}
 return result;
}
export function renderIntermission(w:World,saveUI:string,nav:IntermissionNavigation){
 const route=nav.current,building=w.rewardRound==='building',direction=w.expedition.developmentDirection;
 const heading=(name:string,step=building?1:2)=>`<header class="im-heading"><div class="im-title">${button(glyph('back'),nav.depth?'ui-back':'ui-menu','im-back',`aria-label="${nav.depth?'返回上级':'整备菜单'}"`)}<div><span class="im-eyebrow">${w.endlessEntry?'无尽入场':w.endless?'无尽 '+w.endless.round:'第 '+w.stage+' 关完成'} · ${RACE_NAMES[w.expedition.race]}</span><h1>${name}</h1></div></div><div class="im-wallet" aria-label="现有资源">${money(w.wallet.minerals,w.wallet.gas)}</div></header><nav class="im-steps" aria-label="关间整备"><span ${step===1?'aria-current="step"':''}><b>${step>1?glyph('check'):'01'}</b>基地建设</span><i></i><span ${step===2?'aria-current="step"':''}><b>02</b>战备补给</span><i></i><span><b>03</b>返回前线</span></nav>`;
 const tools=`<nav class="pause-actions" aria-label="整备服务">${(['production','rest','heroes','contracts','catalog'] as const).map(page=>button(({production:'生产',rest:'休整',heroes:'英雄',contracts:'精锐',catalog:'图鉴'})[page],'ui-page','text-button',`data-page="${page}"`)).join('')}${button(glyph('gear')+' 操作与画质','settings','text-button','aria-label="打开设置"')}${w.endlessEntry?button('返回撤离选择','endless-back','text-button'):''}</nav>`;
 const root=()=>`${heading(building?'基地建设':'战备补给')}${building?`<div class="im-direction" role="group" aria-label="发展方向">${Object.entries(PRODUCTION_LINES).filter(([,l])=>l.race===w.expedition.race).map(([id,l])=>`<button data-action="development-direction" data-line="${id}" aria-pressed="${direction===id}">${image('unit.'+l.families[0])}<span>${l.name}</span></button>`).join('')}<span class="im-status">${direction?'选择一项':'选择发展方向'}</span></div>`:`<div class="im-caption"><span><i class="im-live-dot"></i>${{terran:'军需官待命',zerg:'虫群待命',protoss:'跃迁信号就绪'}[w.expedition.race]}</span><span class="im-purchase-count">${w.rewards.filter(r=>r.sold).length? w.rewards.filter(r=>r.sold).length+' 项已备齐':'补给已送达'}</span></div>`}<div class="im-choice-grid" id="reward-cards" aria-label="${building?'发展':'商店'}选项">${w.rewards.map((r,i)=>referenceCard(offerView(w,r),i)).join('')||'<p class="im-empty">选择发展方向后查看建设项目。</p>'}</div><footer class="im-footer reward-actions"><div class="im-refresh">${button(glyph('refresh')+' 刷新','reroll','secondary',building&&!direction||!Number.isFinite(w.rerollCost())||w.wallet.minerals<w.rerollCost()?'disabled':'')}<span>${Number.isFinite(w.rerollCost())?w.rerollCost()===0?'免费':money(w.rerollCost()):'—'}</span></div>${button((building?'前往补给':w.endlessEntry?'进入无尽':w.endless?'下一轮':'返回前线')+' '+glyph('next'),'skip','primary')}</footer>`;
 let content='',layer='';
 if(route.page==='root'||route.page==='menu'||route.page==='offer'||route.page==='elite'||route.page==='contract'){content=root();if(route.page==='menu')layer=modal('基地整备','',tools,'pause-modal',button('返回补给','ui-back','primary'));else if(route.page==='offer'){const r=w.rewards.find(r=>r.offerId===route.id);if(r){const e=effect(r);layer=e?.kind==='elite'?eliteChoices(w,e.family,r.offerId,nav,false,r):modal(gameText(r.name),offerView(w,r).kicker,referenceCardDetail(offerView(w,r)),'im-detail-dialog',button('返回','ui-back','secondary')+button(r.sold?'已获得':'确认 · '+offerPrice(w,r),'reward','primary',`data-id="${esc(r.offerId)}" ${w.canChooseReward(r)?'':'disabled'}`));}}
  else if(route.page==='contract'){const c=w.expedition.eliteContracts.find(c=>c.id===route.id);if(c)layer=eliteChoices(w,c.family,c.id,nav,true);}
  else if(route.page==='elite'){const e=ELITES[route.variant],r=w.rewards.find(r=>r.offerId===route.id);layer=modal(e.name,'精锐',referenceCardDetail({...offerView(w,r??w.rewards[0]),id:e.id,name:e.name,identity:e.id,detail:gameText(e.description)}),'im-detail-dialog',button('返回','ui-back','primary'));}}
 else if(route.page==='catalog'||route.page==='catalog-detail'){content=library(w,nav);if(route.page==='catalog-detail'){const c=catalogueCards(w).find(c=>c.id===route.id||c.id===w.expedition.race+':'+route.id);if(c)layer=modal(c.name,c.kicker,referenceCardDetail(c),'im-detail-dialog',button('返回图鉴','ui-back','primary'));}}
 else if(route.page==='direction')content=`${heading('发展方向',1)}<div class="im-direction" role="group" aria-label="发展方向">${Object.entries(PRODUCTION_LINES).filter(([,l])=>l.race===w.expedition.race).map(([id,l])=>`<button data-action="development-direction" data-line="${id}" aria-pressed="${direction===id}">${image('unit.'+l.families[0])}<span>${l.name}</span></button>`).join('')}</div>`;
 else if(route.page==='production'){content=root();layer=renderProductionWindow(w,nav.productionTab);}
 else if(route.page==='rest'){const cards=restCards(w),pages=Math.ceil(cards.length/3),at=Math.min(nav.page,pages-1);content=`${heading('战地休整')}<div class="im-caption"><span>生命恢复 · 英雄复活</span><span>战斗暂停</span></div><div class="im-choice-grid">${cards.slice(at*3,at*3+3).map((c,i)=>referenceCard(c,i)).join('')}</div><footer class="im-footer"><span class="im-status">生命已满时无需修复</span>${pages>1?`<div class="im-pagination">${button(glyph('back'),'ui-catalog-prev','secondary',`aria-label="上一组休整" ${at===0?'disabled':''}`)}<span>${at+1} / ${pages}</span>${button(glyph('next'),'ui-catalog-next','secondary',`aria-label="下一组休整" ${at===pages-1?'disabled':''}`)}</div>`:''}${button('返回补给','ui-back','primary')}</footer>`;}
 else if(route.page==='heroes'){const heroes=Object.entries(HEROES).filter(([,h])=>h.race===w.expedition.race),page=Math.min(nav.page,1);content=`${heading('英雄待命')}<div class="im-caption"><span>英雄 ${w.heroes.size} / 3</span><div class="im-pagination">${button(glyph('back'),'ui-catalog-prev','secondary',`aria-label="上一组英雄" ${page===0?'disabled':''}`)}<span>${page+1} / 2</span>${button(glyph('next'),'ui-catalog-next','secondary',`aria-label="下一组英雄" ${page===1?'disabled':''}`)}</div></div><div class="im-choice-grid">${heroes.slice(page*3,page*3+3).map(([id,h],i)=>{const r=w.rewards.find(r=>effect(r)?.kind==='hero'&&(effect(r) as {heroId:string}).heroId===id);const c=catalogueCards(w).find(c=>c.id===w.expedition.race+':'+id)!;return referenceCard(r?offerView(w,r):{...c,action:'ui-catalog-detail',detailAction:'ui-catalog-detail',attrs:`data-id="${c.id}"`,label:'查看',stat:w.heroes.has(id as HeroId)?'在队 · '+rankLabel(w.heroes.get(id as HeroId)!.rank):h.skill},i,!r);}).join('')}</div><footer class="im-footer"><span class="im-status">英雄最多三位 · 招募等待军需报价</span>${button('返回补给','ui-back','primary')}</footer>`;}
 else if(route.page==='contracts')content=`${heading('精英特约')}<div class="im-choice-grid">${w.expedition.eliteContracts.map((c,i)=>referenceCard({id:c.id,race:w.expedition.race,rarity:'purple',name:SC2_UNITS[c.family].zh,kicker:'精英特约',flavour:'专属战法，守住火线。',stat:'挑选本兵种精锐',detail:'',identity:c.family,icon:'unit.'+c.family,art:'elite',bodies:c.family==='zergling'?2:1,minerals:c.minerals,gas:c.gas,sold:c.purchased,action:'ui-contract',detailAction:'ui-contract',label:c.purchased?'已获得':'挑选精锐',attrs:`data-id="${c.id}"`},i)).join('')||'<p class="im-empty">本轮没有精英特约。</p>'}</div><footer class="im-footer">${button('返回补给','ui-back','primary')}</footer>`;
 return `<div class="reward-screen formal-intermission" data-ui-route="${route.page}"><section class="intermission-screen">${content}</section>${layer}</div>`;
}
