import {heroAbilityCopy} from './ability-copy';
import type {World} from '../../simulation/world';
import type {Reward} from '../../simulation/types';
import {EXPEDITION_CARD_DEFINITIONS,type ExpeditionReward} from '../../simulation/progression/expedition-drafts';
import {HEROES,type HeroId} from '../../data/heroes';
import {ELITES,type EliteId} from '../../data/elites';
import {SC2_UNITS} from '../../data/sc2-units';
import {FAMILIES_BY_RACE,type FamilyId} from '../../data/races';
import {PRODUCTION_LINES,DEVELOPMENT} from '../../data/expedition-buildings';
import {UNIQUE_SUPPORT} from '../../data/unique-support';
import {RARITIES} from '../../data/rewards';
import {icon} from '../../assets/manifest';
import {renderExpeditionProduction,renderRepairs} from '../hud/expedition-panel';
import {rewardOwnership,rankLabel} from '../unit-identity';
import {paintedArt,escapeHtml as esc} from './painted-art';
import {MenuHistory} from './navigation';
export type IntermissionRoute={page:'root'|'direction'|'production'|'rest'|'heroes'|'contracts'|'catalog'}|{page:'offer';id:string}|{page:'elite';id:string;variant:EliteId;contract?:boolean}|{page:'contract';id:string}|{page:'catalog-detail';id:string};
export class IntermissionNavigation extends MenuHistory<IntermissionRoute>{
 private context='';filter:'ordinary'|'elite'|'hero'|'development'|'support'|'training'='ordinary';
 constructor(){super({page:'root'});}
 sync(w:World){const key=[w.runId,w.phase,w.rewardRound,w.expedition.draftWindow].join(':');if(key!==this.context){this.context=key;this.reset();}}
}
const cost=(m:number,g:number)=>`${m} 矿${g?' / '+g+' 气':''}`;
const effect=(r:Reward)=>(r as ExpeditionReward).expeditionEffect;
const family=(r:Reward)=>{const e=effect(r);return e&&'family' in e?e.family:undefined;};
export function offerArt(r:Reward){const e=effect(r),f=family(r);if(e?.kind==='hero')return paintedArt(e.heroId,r.name);if(f){const bodies=e.kind==='supply'?e.count*(f==='zergling'?2:1):f==='zergling'?2:1;return paintedArt(f,r.name,bodies);}return `<span class="offer-symbol">${icon(r.icon,r.name)}</span>`;}
export function offerPrice(w:World,r:Reward){const receipt=(r as ExpeditionReward).purchaseReceipt;return r.sold?(receipt?.freeSource?'已售罄 · 天赋免单':'已售罄'):w.rewardRound==='random'&&w.expedition.freePurchasesRemaining>0?'天赋免单':cost(r.minerals,r.gas);}
const short=(r:Reward)=>r.description.replace(/\d+\.\d{6,}/g,n=>String(Number(Number(n).toFixed(4)))).split('。')[0];
function card(w:World,r:Reward,i:number){return `<article class="formal-card rarity-${r.rarity}" data-rarity="${r.rarity}"><button data-action="ui-offer" data-id="${esc(r.offerId)}" aria-label="查看${esc(r.name)}"><span class="card-number">0${i+1} / ${RARITIES[r.rarity].name}</span>${offerArt(r)}<div class="formal-card-copy"><h3>${esc(r.name)}</h3><p>${esc(short(r))}</p><strong>${offerPrice(w,r)}</strong><span>${r.sold?'已售罄':'查看详情　›'}</span></div></button></article>`;}
function variants(w:World,f:FamilyId,id:string,contract=false){return `<div class="formal-card-grid">${Object.values(ELITES).filter(e=>e.family===f).map(e=>`<article class="formal-card rarity-purple"><button data-action="ui-elite" data-id="${esc(id)}" data-variant="${e.id}" ${contract?'data-contract="true"':''}>${paintedArt(e.id,e.name,f==='zergling'?2:1)}<div class="formal-card-copy"><h3>${e.name}</h3><p>${esc(e.description.split('。')[0])}</p><span>${w.eliteOwned(e.id)?'已拥有 '+rankLabel(w.eliteOwned(e.id)!.rank):'未拥有'}　›</span></div></button></article>`).join('')}</div>`;}
function offerDetail(w:World,r:Reward){const e=effect(r);return `<div class="offer-detail-summary">${offerArt(r)}<div><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><p>${esc(rewardOwnership(w,r))}</p><strong>${offerPrice(w,r)}</strong>${r.discount?`<p>本次价格为 ${Math.round((1-r.discount)*100)}% · 以当前报价结算</p>`:''}</div></div>${e?.kind==='elite'?variants(w,e.family,r.offerId):''}`;}
type CatalogItem={id:string;name:string;art?:string;icon?:string;copy:string};
export function catalogue(w:World,filter:IntermissionNavigation['filter']):CatalogItem[]{
 const race=w.expedition.race;
 if(filter==='ordinary')return FAMILIES_BY_RACE[race].map(f=>({id:f,name:SC2_UNITS[f].zh,art:f,copy:`${SC2_UNITS[f].flying?'空中':'地面'}单位 · 原生生命 ${SC2_UNITS[f].maxHp} · 护甲 ${SC2_UNITS[f].armor} · 移速 ${SC2_UNITS[f].movementSpeed.toFixed(2)}。原生武器 ${SC2_UNITS[f].attackDamage} × ${SC2_UNITS[f].attacks}，周期 ${SC2_UNITS[f].attackPeriod.toFixed(2)} 秒，射程 ${SC2_UNITS[f].attackRange}。本局实际属性受等级、培养及状态影响，在战场单位详情中查看。`}));
 if(filter==='elite')return Object.values(ELITES).filter(e=>FAMILIES_BY_RACE[race].includes(e.family as never)).map(e=>({id:e.id,name:e.name,art:e.id,copy:e.description}));
 if(filter==='hero')return Object.entries(HEROES).filter(([,h])=>h.race===race).map(([id,h])=>({id,name:h.name,art:id,copy:`主动：${h.skill}。${heroAbilityCopy(id as HeroId).active} ${heroAbilityCopy(id as HeroId).passive}`}));
 if(filter==='development')return DEVELOPMENT.filter(d=>d.race===race).map(d=>({id:d.id,name:d.name,icon:d.kind==='facility'?'building.'+d.id:'tech.attack',copy:`${d.kind==='facility'?'生产设施':d.kind==='research'?'研究':'科技'} · ${d.line?PRODUCTION_LINES[d.line].name:'基础设施'} · 最高 ${d.maxLevel} 级。购买资格及价格以本轮实际发展报价为准。`}));
 if(filter==='support')return Object.entries(UNIQUE_SUPPORT).filter(([,s])=>s.race===race).map(([id,s])=>({id,name:s.name,icon:'tech.boost',copy:s.description}));
 return Object.entries(EXPEDITION_CARD_DEFINITIONS).map(([id,d])=>({id,name:d.name,icon:'tech.attack',copy:`白 / 绿 / 蓝 / 紫 / 橙：${d.values.join(' / ')}。对应本局卡片的家族、实际对象和累计上限；只有商店的有效报价可以购买。`}));
}
export function renderIntermission(w:World,saveUI:string,nav:IntermissionNavigation){
 const route=nav.current,building=w.rewardRound==='building',direction=w.expedition.developmentDirection;
 let title=building?'选择发展':'补强部队',body='',footer='';
 const titles:Partial<Record<IntermissionRoute['page'],string>>={direction:'发展方向',production:'持续生产',rest:'战地整备',heroes:'英雄招募',contracts:'精英特约',catalog:'卡片图鉴'};title=titles[route.page]??title;
 if(route.page==='root')body=`${building?`<button class="direction-link" data-action="ui-page" data-page="direction">${direction?'当前方向 · '+PRODUCTION_LINES[direction].name:'选择发展方向'}　›</button>`:''}<div id="reward-cards" class="formal-card-grid">${w.rewards.map((r,i)=>card(w,r,i)).join('')}</div>`;
 else if(route.page==='direction')body=`<div class="direction-grid">${Object.entries(PRODUCTION_LINES).filter(([,l])=>l.race===w.expedition.race).map(([id,l])=>`<button data-action="development-direction" data-line="${id}" aria-pressed="${id===direction}">${paintedArt(l.families[0],l.name)}<h3>${l.name}</h3><p>${l.families.map(f=>SC2_UNITS[f].zh).join(' / ')}</p><span>确定发展方向　›</span></button>`).join('')}</div>`;
 else if(route.page==='production')body=renderExpeditionProduction(w);
 else if(route.page==='rest')body=`${renderRepairs(w)}<section class="hero-revivals"><h3>英雄归队</h3>${[...w.heroes].map(([id,h])=>{const alive=!!w.heroEntity(id)?.hp,p=w.revivalCost(h.rank);return `<article class="rest-hero">${paintedArt(id,HEROES[id].name)}<h4>${HEROES[id].name} · ${rankLabel(h.rank)}</h4><button data-action="revive" data-id="${id}" ${w.canReviveHero(id)?'':'disabled'}>${alive?'在队':h.revivePaid?'下关归队':'复活 · '+cost(p.minerals,p.gas)}</button></article>`;}).join('')||'<p>尚未招募英雄。</p>'}</section>${saveUI}`;
 else if(route.page==='heroes'){const heroes=w.rewards.filter(r=>effect(r)?.kind==='hero');body=`<p>本轮实际英雄报价。无报价时可浏览图鉴，等待后续招募机会。</p><div class="formal-card-grid">${heroes.map((r,i)=>card(w,r,i)).join('')||'<p>本轮没有英雄招募报价。</p>'}</div>`;}
 else if(route.page==='contracts')body=`<div class="formal-card-grid">${w.expedition.eliteContracts.map(c=>`<article class="formal-card rarity-purple"><button data-action="ui-contract" data-id="${c.id}">${paintedArt(c.family,SC2_UNITS[c.family].zh,c.family==='zergling'?2:1)}<div class="formal-card-copy"><h3>${SC2_UNITS[c.family].zh} · 精英型号</h3><strong>${c.purchased?'已购买':cost(c.minerals,c.gas)}</strong><span>选择型号　›</span></div></button></article>`).join('')||'<p>本轮没有精英特约。</p>'}</div>`;
 else if(route.page==='offer'){const r=w.rewards.find(r=>r.offerId===route.id);title=r?.name??'报价已结束';body=r?offerDetail(w,r):'<p>该报价已失效，请返回查看本轮卡片。</p>';if(r&&effect(r)?.kind!=='elite')footer=`<button class="primary" data-action="reward" data-id="${esc(r.offerId)}" ${w.canChooseReward(r)?'':'disabled'}>${r.sold?'已售罄':'确认购买 · '+offerPrice(w,r)}</button>`;}
 else if(route.page==='contract'){const c=w.expedition.eliteContracts.find(c=>c.id===route.id);title='选择精英型号';body=c?`<p>${c.purchased?'已购买':cost(c.minerals,c.gas)}</p>${variants(w,c.family,c.id,true)}`:'<p>该特约已结束。</p>';}
 else if(route.page==='elite'){const elite=ELITES[route.variant],r=w.rewards.find(r=>r.offerId===route.id),c=w.expedition.eliteContracts.find(c=>c.id===route.id),owned=w.eliteOwned(route.variant);title=elite.name;const enabled=w.canAcquireElite(route.variant)&&(route.contract?!!c&&!c.purchased&&w.wallet.minerals>=c.minerals&&w.wallet.gas>=c.gas:!!r&&w.canChooseReward(r)),price=route.contract?(c?cost(c.minerals,c.gas):'报价失效'):r?offerPrice(w,r):'报价失效';body=`<div class="offer-detail-summary">${paintedArt(elite.id,elite.name,elite.family==='zergling'?2:1)}<div><h3>${elite.name}</h3><p>${esc(elite.description)}</p><p>${owned?'已拥有 '+rankLabel(owned.rank)+' · '+(owned.rank>=5?'已满级':'提升一级'):'招募精英 · 编制满员时继续选择替换对象'}</p><strong>${price}</strong></div></div>`;footer=`<button class="primary" data-action="${route.contract?'elite-contract':'reward'}" data-id="${esc(route.id)}" data-variant="${route.variant}" ${enabled?'':'disabled'}>确认${owned?'升级':'招募'} · ${price}</button>`;}
 else if(route.page==='catalog'||route.page==='catalog-detail'){const items=catalogue(w,nav.filter);if(route.page==='catalog-detail'){const item=items.find(c=>c.id===route.id);title=item?.name??'图鉴';body=item?`<div class="offer-detail-summary">${item.art?paintedArt(item.art,item.name,item.art==='zergling'?2:1):`<span class="offer-symbol">${icon(item.icon??'tech.attack',item.name)}</span>`}<div><h3>${esc(item.name)}</h3><p>${esc(item.copy)}</p><small>图鉴 · 只读</small></div></div>`:'';}else body=`<nav class="catalog-filters" aria-label="图鉴分类">${(['ordinary','elite','hero','development','support','training'] as const).map(id=>`<button data-action="ui-catalog-filter" data-filter="${id}" aria-pressed="${nav.filter===id}">${({ordinary:'普通兵',elite:'精英',hero:'英雄',development:'建筑与科技',support:'支援',training:'培养'})[id]}</button>`).join('')}</nav><div class="formal-card-grid catalog-grid">${items.map(item=>`<article class="formal-card"><button data-action="ui-catalog-detail" data-id="${esc(item.id)}">${item.art?paintedArt(item.art,item.name,item.art==='zergling'?2:1):`<span class="offer-symbol">${icon(item.icon??'tech.attack',item.name)}</span>`}<div class="formal-card-copy"><h3>${esc(item.name)}</h3><span>查看详情　›</span></div></button></article>`).join('')}</div>`;}
 const menu=`<nav class="intermission-nav" aria-label="关间菜单">${(['production','rest','heroes','contracts','catalog'] as const).filter(page=>!building||!['heroes','contracts'].includes(page)).map(page=>`<button data-action="ui-page" data-page="${page}" aria-pressed="${route.page===page}">${titles[page]}</button>`).join('')}<button data-action="settings">设置</button></nav>`;
 const rootActions=`<button data-action="reroll" ${building&&!direction||!Number.isFinite(w.rerollCost())||w.wallet.minerals<w.rerollCost()?'disabled':''}>刷新 · ${Number.isFinite(w.rerollCost())?(w.rerollCost()===0?'免费':w.rerollCost()+' 矿'):'—'}</button><button class="primary primary-next" data-action="skip">${building?'跳过，去商店':w.endlessEntry?'进入无尽':w.endless?'下一轮':'下一关'}</button>`;
 return `<div class="reward-screen formal-intermission" data-ui-route="${route.page}"><header class="formal-page-header"><div><span class="eyebrow">${w.endless?'无尽 '+w.endless.round:'第 '+w.stage+' 关'} / ${building?'发展':'商店'}</span><h2>${esc(title)}</h2></div><div class="page-wallet">${icon('ui.minerals')} ${Math.floor(w.wallet.minerals)} ${icon('ui.gas')} ${Math.floor(w.wallet.gas)}</div></header>${route.page==='root'?menu:''}<div class="intermission-content" data-ui-scroll>${body}</div><footer class="reward-actions">${nav.depth?'<button data-action="ui-back">返回</button>':w.endlessEntry?'<button data-action="endless-back">返回</button>':''}${route.page==='root'?rootActions:footer}</footer></div>`;
}
