import type {World} from '../../simulation/world';
import type {RunSnapshot} from '../../simulation/persistence/run-snapshot';
import {campaignTerrain,MAP_THEMES} from '../../data/campaign-map';
import {minimapFrame,paintMinimapTerrain} from '../hud/minimap';
export function savedRunInfo(r:Readonly<RunSnapshot>|null|undefined){if(!r)return null;const s=r.state;return {race:r.config.race,difficulty:r.config.difficulty,stage:s.stage,mapName:s.endless?'无尽战场':r.config.campaignMap?MAP_THEMES[r.config.campaignMap.theme].name:'战役前线',wallet:s.wallet,bodies:[...s.entities.values()].filter(u=>u.owner==='terran'&&u.hp>0&&!u.summonKind&&!u.summonOwnerId&&!u.temporary).length,points:r.config.frozenTalents.allocated,phase:s.phase,runId:s.runId,mapHash:s.battlefield.mapHash};}
/** UI-only image cache. Neither run/profile formats nor resource records change. */
export class MapPreview {
 private signature='';private cached:{runId:string;mapHash:string;url:string}|null=null;private overview=new Map<string,string>();private scratch:HTMLCanvasElement;
 constructor(){this.scratch=document.createElement('canvas');this.scratch.width=640;this.scratch.height=360;try{const c=JSON.parse(localStorage.getItem('sc2.ui.save-image')??'null');if(c&&typeof c.runId==='string'&&typeof c.mapHash==='string'&&typeof c.url==='string'&&c.url.startsWith('data:image/webp;'))this.cached=c;}catch{}}
 /** Called after the existing render, only for a newly paused frame. */
 capture(w:World,canvas:HTMLCanvasElement){if(!(w.phase==='battle'&&w.paused||w.phase==='won'||w.phase==='endless-ready'||w.phase==='reward'&&w.endlessEntry)||!w.runId||!w.battlefield.mapHash||!canvas.width||!canvas.height)return;const signature=w.runId+':'+w.tick+':'+w.battlefield.mapHash;if(this.signature===signature)return;this.signature=signature;try{const ctx=this.scratch.getContext('2d')!,scale=Math.max(640/canvas.width,360/canvas.height);ctx.clearRect(0,0,640,360);ctx.drawImage(canvas,(640-canvas.width*scale)/2,(360-canvas.height*scale)/2,canvas.width*scale,canvas.height*scale);this.cached={runId:w.runId,mapHash:w.battlefield.mapHash,url:this.scratch.toDataURL('image/webp',.82)};localStorage.setItem('sc2.ui.save-image',JSON.stringify(this.cached));}catch{}}
 forRun(r:Readonly<RunSnapshot>|null|undefined){if(!r)return null;const info=savedRunInfo(r)!;if(this.cached?.runId===info.runId&&this.cached.mapHash===info.mapHash)return this.cached.url;if(!r.config.campaignMap||r.state.endless)return null;const key=r.config.mapHash+':'+r.state.stage;if(this.overview.has(key))return this.overview.get(key)!;try{const terrain=campaignTerrain(r.config.campaignMap);terrain.stage=r.state.stage;const d=terrain.definition,frame=minimapFrame(d,r.state.stage),c=document.createElement('canvas');c.width=c.height=320;const ctx=c.getContext('2d')!,pixels=ctx.createImageData(320,320);paintMinimapTerrain(d,terrain,frame,r.state.stage,320,pixels.data);ctx.putImageData(pixels,0,0);const url=c.toDataURL('image/webp',.82);this.overview.set(key,url);return url;}catch{return null;}}
 live(w:World){return this.cached?.runId===w.runId&&this.cached.mapHash===w.battlefield.mapHash?this.cached.url:null;}
}
