(() => {
 const root=document.getElementById('scs-opening-visual');if(!root)return;
 const screen=root.querySelector('.scs-screen'),canvas=root.querySelector('.scs-stars'),ctx=canvas.getContext('2d');
 const preference=matchMedia('(prefers-reduced-motion:reduce)');let enabled=true;
 try{enabled=localStorage.getItem('sc2.ui-motion')!=='false';}catch{}
 let seed=742391,frame=0,ended=false,width=0,height=0,motionTime=0,previous=performance.now();
 const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;};
 const stars=Array.from({length:138},()=>({x:random(),y:random(),depth:.2+random()*.8,phase:random()*6.2832}));
 function resize(){screen.classList.toggle('scs-portrait',innerHeight>innerWidth);width=screen.clientWidth;height=screen.clientHeight;const density=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.round(width*density);canvas.height=Math.round(height*density);ctx?.setTransform(density,0,0,density,0,0);draw();}
 function draw(){if(!ctx||!width||!height)return;ctx.clearRect(0,0,width,height);for(const star of stars){const x=((star.x-motionTime*.009*star.depth)%1+1)%1*width,y=((star.y+motionTime*.0024*star.depth)%1)*height,intensity=(.24+star.depth*.36)*(.76+.24*Math.sin(motionTime*.7+star.phase));ctx.globalAlpha=intensity;ctx.fillStyle='#b1dded';ctx.beginPath();ctx.arc(x,y,.32+star.depth*.9,0,Math.PI*2);ctx.fill();if(star.depth>.83){ctx.globalAlpha=intensity*.28;ctx.strokeStyle='#71cef4';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(x-3.8,y+.8);ctx.lineTo(x+1.2,y-.25);ctx.stroke();}}ctx.globalAlpha=1;}
 function update(now){frame=0;if(ended||!root.isConnected)return;const moving=enabled&&!preference.matches;root.classList.toggle('scs-still',!moving||document.hidden);if(moving&&!document.hidden)motionTime+=Math.min((now-previous)/1000,.1);previous=now;draw();if(moving)frame=requestAnimationFrame(update);}
 function restart(){if(frame)cancelAnimationFrame(frame);update(performance.now());}
 function progress(event){const d=event.detail??{},value=typeof d.value==='number'&&Number.isFinite(d.value)?Math.max(0,Math.min(100,d.value)):null,track=root.querySelector('.scs-track');track.classList.toggle('is-indeterminate',value===null);if(value===null){track.removeAttribute('aria-valuenow');root.querySelector('.scs-fill').style.removeProperty('width');root.querySelector('.scs-percent').textContent='…';}else{track.setAttribute('aria-valuenow',String(value));root.querySelector('.scs-fill').style.width=value+'%';root.querySelector('.scs-percent').textContent=Math.floor(value)+'%';}root.querySelector('.scs-phase').textContent=d.phase==='ready'?'SYSTEM READY':d.phase==='loading'?'LOADING':'INITIALIZING';root.querySelector('.scs-detail').textContent=d.phase==='ready'?'DEPLOYMENT READY':d.phase==='loading'?'LOADING BATTLEFIELD':'PREPARING MISSION';}
 function finish(){if(ended)return;ended=true;if(frame)cancelAnimationFrame(frame);observer.disconnect();removeEventListener('resize',resize);preference.removeEventListener('change',restart);document.removeEventListener('visibilitychange',restart);document.removeEventListener('sc2-opening-progress',progress);document.removeEventListener('sc2-opening-finish',finish);document.getElementById('game-root')?.removeAttribute('inert');root.remove();document.querySelector('[data-action="menu-new"]')?.focus({preventScroll:true});}
 const observer=new ResizeObserver(resize);observer.observe(screen);addEventListener('resize',resize);preference.addEventListener('change',restart);document.addEventListener('visibilitychange',restart);document.addEventListener('sc2-opening-progress',progress);document.addEventListener('sc2-opening-finish',finish);resize();restart();
})();
