import {assetUrl} from '../../assets/manifest';
import {PAINTED_CARDS} from '../../assets/ui-art.generated';
import type {Race} from '../../data/races';
export const COVER_HEROES:Record<Race,readonly string[]>={terran:['raynor','nova','tychus'],zerg:['kerrigan','zagara','dehaka'],protoss:['artanis','zeratul','fenix']};
export const escapeHtml=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Plate={width:number;height:number;assetKey:string;sceneBounds:{x:number;y:number;width:number;height:number};bodyBounds:{x:number;y:number;width:number;height:number};bodyHeight?:number;bodyWidth?:number;air?:boolean;skyTop?:string;skyBottom?:string;atmosphere?:string};
const positions:Record<number,readonly (readonly [number,number])[]>={1:[[0,0]],2:[[-48,-6],[47,10]],3:[[-88,-6],[88,-4],[0,12]],4:[[-53,-27],[52,-27],[-52,38],[53,40]],6:[[-86,-27],[0,-28],[86,-26],[-86,40],[86,42],[0,44]]};
/** R11 original plate rectangles, with a constant body scale for every cohort size. */
export function paintedArt(identity:string,name:string,bodies=1,context=identity,bodyIdentities?:readonly string[]):string{
 if(!positions[bodies])throw Error('Unsupported painted body count: '+bodies);
 const a=(PAINTED_CARDS as Record<string,Plate>)[identity];
 if(!a){const cover=assetUrl('ui.cover.'+identity);return cover?`<span class="im-painting-canvas painted-art hero-cover" data-art-key="${escapeHtml(identity)}" data-body-count="1"><img class="im-painted" src="${cover}" alt="${escapeHtml(name)}" draggable="false"></span>`:'';}
 const url=assetUrl('ui.paint.'+a.assetKey);if(!url)return '';
 const bb=a.bodyBounds,sb=a.sceneBounds,scale=Math.min((a.bodyWidth??(a.air?240:184))/bb.width,(a.bodyHeight??(a.air?150:224))/bb.height),w=bb.width*scale,h=bb.height*scale;
 // IDs depend only on presentation identity/context. A live readout does not
 // acquire a new SVG identity or replace its DOM every simulation tick.
 let hash=2166136261;for(const c of context+'|'+identity+'|'+bodies)hash=Math.imul(hash^c.charCodeAt(0),16777619);
 const id='painted-r11-'+(hash>>>0).toString(36),ss=Math.max(400/sb.width,300/sb.height),sx=(400-sb.width*ss)/2-sb.x*ss,sy=(300-sb.height*ss)/2-sb.y*ss;
 const figures=positions[bodies].map(([dx,dy],i)=>{const key=bodyIdentities?.[i]??identity,p=(PAINTED_CARDS as Record<string,Plate>)[key]??a,b=p.bodyBounds,s=Math.min((p.bodyWidth??(p.air?240:184))/b.width,(p.bodyHeight??(p.air?150:224))/b.height),dw=b.width*s,dh=b.height*s,src=assetUrl('ui.paint.'+p.assetKey)??url;return `<g class="im-painted-unit" data-unit-index="${i+1}" data-unit-scale="1" data-unit-identity="${escapeHtml(key)}" transform="translate(${dx} ${dy})">${p.air?'':`<ellipse cx="200" cy="258" rx="${Math.min(61,dw*.29)}" ry="6" fill="#01070c" opacity=".62" filter="url(#${id}-contact)"/>`}<svg x="${200-dw/2}" y="${255-dh}" width="${dw}" height="${dh}" viewBox="${b.x} ${b.y} ${b.width} ${b.height}" overflow="hidden"><image href="${src}" width="${p.width}" height="${p.height}"/></svg></g>`;}).join('');
 return `<span class="im-painting-canvas painted-art" data-art-key="${escapeHtml(identity)}" data-body-count="${bodies}"><svg class="im-painting-scene" viewBox="0 0 400 300" preserveAspectRatio="xMidYMid slice" aria-hidden="true" focusable="false"><defs><clipPath id="${id}-scene-frame"><rect width="400" height="300"/></clipPath><linearGradient id="${id}-sky" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${a.skyTop??'#5b6c81'}"/><stop offset="1" stop-color="${a.skyBottom??'#2c4252'}"/></linearGradient></defs><rect width="400" height="300" fill="url(#${id}-sky)"/><g clip-path="url(#${id}-scene-frame)"><image href="${url}" x="${sx}" y="${sy}" width="${a.width*ss}" height="${a.height*ss}"/></g></svg><svg class="im-unit-painting im-raster-painting" viewBox="0 0 400 300" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${escapeHtml(name)}，${bodies} 个战士" data-family="${escapeHtml(identity.split('.')[0])}" data-art-key="${escapeHtml(identity)}" data-body-count="${bodies}" data-body-width="${w}" data-body-height="${h}" data-art-method="painted-raster-layers" focusable="false"><defs><clipPath id="${id}-frame"><rect width="400" height="300"/></clipPath><filter id="${id}-contact" x="-30%" y="-160%" width="160%" height="420%"><feGaussianBlur stdDeviation="3"/></filter><radialGradient id="${id}-mist"><stop stop-color="${a.atmosphere??'#7995ac'}" stop-opacity=".2"/><stop offset="1" stop-color="${a.atmosphere??'#7995ac'}" stop-opacity="0"/></radialGradient><linearGradient id="${id}-fade" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#071622" stop-opacity="0"/><stop offset="1" stop-color="#071622" stop-opacity=".94"/></linearGradient></defs><g clip-path="url(#${id}-frame)">${figures}</g><ellipse cx="200" cy="270" rx="173" ry="19" fill="url(#${id}-mist)"/></svg></span>`;
}
