import type {Race} from '../../data/races';
import type {Rarity} from '../../data/rewards';
import {paintedArt} from './painted-art';
import {referenceEngraving} from './reference-engraving';
import {button,image,money,glyph,esc} from './reference-primitives';
export interface CardView {id:string;race:Race;rarity:Rarity;name:string;kicker:string;flavour:string;stat:string;detail:string;art:string;identity?:string;icon:string;bodies?:number;bodyIdentities?:readonly string[];rank?:number;count?:number;paired?:boolean;minerals?:number;gas?:number;baseMinerals?:number;baseGas?:number;discount?:number;sold?:boolean;free?:boolean;pending?:boolean;locked?:boolean;short?:boolean;owned?:boolean;action?:string;attrs?:string;detailAction?:string;detailAttrs?:string;label?:string;reason?:string;progress?:{purchases:string;total:string}}
const qualities={white:'标准',green:'优良',blue:'稀有',purple:'史诗',orange:'传奇'},roman=['','Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ'];
export function referenceCardArt(c:CardView,context='card'){
 const painting=c.identity?paintedArt(c.identity,c.name,c.bodies??1,context+'-'+c.id,c.bodyIdentities):'';
 return painting?`<div class="im-card-art has-unit-painting">${painting}${!['unit','elite','hero','supply','training'].includes(c.art)?`<span class="im-painting-badge" aria-hidden="true">${image(c.icon)}</span>`:''}<span class="im-art-surface" aria-hidden="true"></span></div>`:`<div class="im-card-art">${referenceEngraving(c)}<span class="im-emblem">${image(c.icon)}<i></i></span><span class="im-art-surface" aria-hidden="true"></span><span class="im-art-code" aria-hidden="true">${c.race==='terran'?'TERRAN':c.race==='zerg'?'SWARM':'PROTOSS'} ${c.rank?roman[c.rank]:qualities[c.rarity]}</span></div>`;
}
export function referenceCard(c:CardView,index=0,catalog=false){
 const off=!!c.discount,status=c.reason??(c.sold?'已获得':c.pending?'正在集结':c.locked?'待解锁':c.short?'资源不足':c.owned?'已达上限':''),price=c.minerals===undefined?'<span class="im-variable-price">随战况报价</span>':money(c.free?0:c.minerals,c.free?0:c.gas),attrs=c.attrs??`data-id="${esc(c.id)}"`,detailAttrs=c.detailAttrs??attrs,action=c.action??'ui-offer',detailAction=c.detailAction??'ui-offer';
 return `<article class="im-card ${c.sold?'im-sold':''} ${c.pending?'im-pending':''} ${c.locked||c.owned?'im-locked':''} ${c.short?'im-short':''}" data-card-id="${esc(c.id)}" data-card-race="${c.race}" data-quality="${c.rarity}" data-kind="${c.art}" style="--deal-index:${index}"><span class="im-edge" aria-hidden="true"></span><div class="im-card-meta"><span>${esc(c.kicker)}</span><div class="im-quality" aria-label="${qualities[c.rarity]}">${Array.from({length:5},(_,i)=>`<i class="${i<=Object.keys(qualities).indexOf(c.rarity)?'lit':''}"></i>`).join('')}</div></div><button class="im-card-face" data-action="${detailAction}" ${detailAttrs} aria-label="查看${esc(c.name)}详情">${referenceCardArt(c)}<div class="im-card-copy"><div class="im-card-title"><h2>${esc(c.name)}</h2>${c.rank?`<span class="im-rank">${roman[c.rank]}</span>`:''}${c.count?`<span class="im-count">×${c.count}${c.paired?'对':''}</span>`:''}</div><p class="im-flavour">${esc(c.flavour)}</p><p class="im-effect">${esc(c.stat)}</p>${c.progress?`<div class="im-card-progress"><span>${esc(c.progress.purchases)}</span><p>${esc(c.progress.total)}</p></div>`:''}</div></button><div class="im-card-bottom"><div class="im-card-price">${price}${off&&c.minerals!==undefined?`<del class="im-price-original">${c.baseMinerals??c.minerals} / ${c.baseGas??c.gas??0}</del>`:''}</div>${button((c.sold?glyph('check'):catalog?glyph('eye'):'')+(c.free?'免费领取':c.label??(catalog?'查看':c.sold?'已获得':'购买')),action,'im-card-action',`${attrs} ${!catalog&&(c.sold||c.pending||c.short||c.locked||c.owned)?'disabled':''}`)}</div>${status||off||c.free?`<span class="im-card-status">${c.sold?glyph('check'):''}${off?'−'+Math.round(c.discount!*100)+'%':status|| (c.free?'免费':'')}</span>`:''}</article>`;
}
export function referenceCardDetail(c:CardView){return `<div class="im-detail-layout"><div class="im-detail-art" data-card-race="${c.race}" data-quality="${c.rarity}" data-kind="${c.art}">${referenceCardArt(c,'detail')}<span class="im-detail-rank">${c.rank?roman[c.rank]:qualities[c.rarity]}</span></div><div class="im-detail-copy"><p class="im-detail-flavour">${esc(c.flavour)}</p><p class="im-detail-rule">${esc(c.detail)}</p>${c.progress?`<div class="im-card-progress"><span>${esc(c.progress.purchases)}</span><p>${esc(c.progress.total)}</p></div>`:''}<div class="im-detail-price">${c.minerals===undefined?'随战况报价':money(c.free?0:c.minerals,c.free?0:c.gas)}</div></div></div>`;}
