import type {BattleRenderer} from '../../render/scene/battle-renderer';
import type {AudioEffects} from '../../render/effects/audio';
import type {ControlSettings} from '../controls/settings';
import {QUALITY_LABELS,ANIMATION_MODE_LABELS,ORDINARY_EFFECT_LABELS,HERO_EFFECT_LABELS} from '../../render/settings/quality';
import {textScale} from '../text-scale';
import {button,glyph,modal,esc} from './reference-primitives';
export type SettingsTab='controls'|'graphics'|'skins';
const select=(label:string,key:string,value:string,options:Record<string,string>)=>`<label class="setting-row"><span>${label}</span><select data-setting="${key}" aria-label="${label}">${Object.entries(options).map(([id,name])=>`<option value="${id}" ${id===value?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
export function renderSettings(tab:SettingsTab,view:BattleRenderer,controls:ControlSettings,audio?:AudioEffects|null,motion=true,skins=''){
 const range=(label:string,key:string,value:number)=>`<label class="setting-row"><span>${label}</span><div class="slider-setting"><input type="range" min="0" max="100" step="1" value="${Math.round(value*100)}" aria-label="${label}" data-audio="${key}"><output>${Math.round(value*100)}%</output></div></label>`;
 const body=tab==='skins'?skins:tab==='controls'?select('电脑移动','desktop',controls.desktop,{mouse:'鼠标点击移动',keyboard:'WASD / 方向键'})+select('手机移动','touch',controls.touch,{joystick:'左侧虚拟摇杆',tap:'点击战场移动'})+`<div class="keyboard-diagram"><div><kbd>W</kbd><span><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><small>移动方向</small></div><div><kbd>T</kbd><kbd>E</kbd><kbd>G</kbd><small>架炮 · 兴奋剂 · 侦测</small></div><div><kbd>1</kbd><kbd>2</kbd><kbd>3</kbd><small>英雄技能</small></div></div>${button('手柄校准','controller','small')}`+range('主音量','master',audio?.masterVolume??1)+range('战场音效','battle',audio?.battleVolume??1)+range('界面音效','interface',audio?.interfaceVolume??0):select('画质','quality',view.quality,QUALITY_LABELS)+select('单位动作','animation-mode',view.animationMode,ANIMATION_MODE_LABELS)+select('文字大小','text-scale',String(textScale()),{'1':'100%','1.25':'125%','1.5':'150%'})+`<label class="setting-row"><span>界面动态效果</span><button class="toggle-switch" data-action="toggle-ui-motion" aria-pressed="${motion}" aria-label="动态效果">${motion?'开启':'关闭'}<i></i></button></label>`+select('镜头震动','camera-shake',String(view.cameraShake),{false:'关闭',true:'开启'})+select('普通兵与支援','ordinary-effects',view.nonHeroEffects.quality,ORDINARY_EFFECT_LABELS)+select('英雄特效','hero-effects',view.fx.heroQuality,HERO_EFFECT_LABELS);
 return modal('设置','',`<nav class="settings-tabs" role="group" aria-label="设置分类">${(['controls','graphics','skins'] as const).map(id=>`<button data-action="settings-tab" data-tab="${id}" aria-pressed="${tab===id}">${({controls:'操作',graphics:'画质',skins:'皮肤',audio:'声音',saves:'档案'})[id]}</button>`).join('')}</nav><div class="settings-body" data-ui-scroll>${body}</div>`,'settings-modal',button('返回','settings-back','primary'),'settings-back');
}

/** Archive actions remain at their original pause entry. */
export function renderArchives(saveHtml:string,canImport:boolean){return modal('战局档案','',`<div class="settings-save-actions">${saveHtml}${button(glyph('download')+' 导入战局','menu-load-file','small',canImport?'':'disabled')}${canImport?'':'<p>返回标题后可导入其他战局。</p>'}${button('资源下载','resource-downloads','small')}${button('全屏','fullscreen','small')}${button('返回标题','restart','text-button')}</div><div data-player-services-host class="settings-service-host"></div>`,'settings-modal',button('返回','archives-back','primary'),'archives-back');}
