import {COVER_HEROES} from './painted-art';
import type {Race} from '../../data/races';
import {RACES,RACE_NAMES} from '../../data/races';
import {assetUrl} from '../../assets/manifest';
import {MVP_TALENTS,TALENT_BY_ID,nextTalentPurchase,allocationPoints,allocationCost,PREVIOUS_TIER_POINTS,type TalentDefinition,type TalentLine,type TalentLevels} from '../../data/mvp-talents';
import type {PermanentProfile} from '../../simulation/progression/permanent-profile';
import {TALENT_PRESENTATION} from './talent-presentation.generated';
import {gameText} from './game-copy';
import {button,iconButton,image,glyph,esc,modal} from './reference-primitives';
import {RACE_VISUALS} from '../hud/m3-menu';
export const LINE_NAMES:Record<TalentLine,string>={resources:'后勤',soldiers:'武装',army:'军团',micro:'微操'};
const LINE_ICONS:Record<TalentLine,string>={resources:'ui.minerals',soldiers:'tech.attack',army:'hero.raynor',micro:'tech.boost'};
const LINE_COPY:Record<TalentLine,readonly [string,string]>={resources:['补给不断，火力不熄。','采集 · 建设 · 招募'],soldiers:['枪更猛，命更硬。','火力 · 防护 · 军衔'],army:['并肩作战，越战越强。','老兵 · 援军 · 精锐'],micro:['一招快，步步先。','射程 · 部署 · 走位']};
const roman=['Ⅰ','Ⅱ','Ⅲ','Ⅳ','Ⅴ','Ⅵ','Ⅶ'];
const text=(t:TalentDefinition)=>TALENT_PRESENTATION[t.id]??{name:gameText(t.name),flavour:'磨好利刃，奔赴前线。'};
const listFor=(r:Race,l:TalentLine)=>MVP_TALENTS.filter(t=>t.race===r&&t.line===l);
const iconFor=(t:TalentDefinition,index=0)=>t.line==='resources'?(index%3===1?'ui.gas':index%3===2?(t.race==='terran'?'building.barracks':'unit.'+RACE_VISUALS[t.race].unit):'ui.minerals'):t.line==='soldiers'?'unit.'+({terran:['marine','marauder','tank','medivac','reaper'],zerg:['zergling','roach','hydralisk','queen','baneling'],protoss:['zealot','stalker','immortal','sentry','colossus']})[t.race][index%5]:t.line==='army'?'hero.'+COVER_HEROES[t.race][index%3]:'tech.boost';
export function talentPlayerReason(reason:string|null,t:TalentDefinition){if(!reason)return null;return gameText(reason).replace(/\b([RSA])(\d{2})\b/g,(_,line,number)=>{const id=t.id[0]+'-'+line+number,node=TALENT_BY_ID.get(id);return node?text(node).name:'前置天赋';});}
function requirements(t:TalentDefinition,levels:TalentLevels){const list=listFor(t.race,t.line),number=Number(t.id.slice(-2)),byNumber=(n:number)=>list.find(v=>Number(v.id.slice(-2))===n)!,full=(n:number)=>(levels[byNumber(n).id]??0)===byNumber(n).maxRank,result:{label:string;ready:boolean;ids:string[];group?:boolean}[]=[];
 const named=(ns:number[],min=0)=>({label:ns.map(n=>text(byNumber(n)).name).join(' / ')+(min?'至少 '+min+' 级':'学满'),ready:ns.every(n=>min?(levels[byNumber(n).id]??0)>=min:full(n)),ids:ns.map(n=>byNumber(n).id)});
 if(t.line==='micro'){if(number>1)result.push(named([number-1]));return result;}
 if(t.tier>1)result.push({label:'上一阶投入 '+PREVIOUS_TIER_POINTS[t.tier-1]+' 点',ready:list.filter(v=>v.tier===t.tier-1).reduce((n,v)=>n+(levels[v.id]??0),0)>=PREVIOUS_TIER_POINTS[t.tier-1],ids:[],group:true});
 if(number>=2&&number<=4)result.push(named([1]));else if(number>=5&&number<=13)result.push(named([number-3]));
 else if(number===14&&t.line==='soldiers')result.push(named([11,12]));else if(number===15&&t.line==='soldiers')result.push(named([12,13]));else if(number===16&&t.line!=='army')result.push(named([14,15]));
 if(t.line==='resources'&&number>=14||number===16){const next=Math.min(t.maxRank,(levels[t.id]??0)+1),count=number===14?next:number===15?next+1:2;result.push({label:'第五阶 '+count+' 项学满',ready:[11,12,13].filter(full).length>=count,ids:[11,12,13].map(n=>byNumber(n).id),group:true});}
 if(t.line==='army'&&number===14)result.push(named([10]));if(t.line==='army'&&number===15)result.push(named([11,13],1));return result;
}
function tree(r:Race,line:TalentLine,levels:TalentLevels,balance:number){const list=listFor(r,line),slot=(t:TalentDefinition)=>{const group=list.filter(v=>v.tier===t.tier),i=group.indexOf(t);return group.length===1?2:group.length===2?i*2+1:i+1;},links=list.flatMap(t=>requirements(t,levels).flatMap(req=>req.ids.map(id=>({from:list.find(v=>v.id===id)!,to:t,ready:req.ready,group:req.group})))),lines=(vertical:boolean)=>links.map(link=>{const sx=(link.from.tier-.5)*100,sy=(slot(link.from)-.5)*100,tx=(link.to.tier-.5)*100,ty=(slot(link.to)-.5)*100;return `<path class="${link.ready?'lit':''} ${link.group?'group-link':''}" d="${vertical?'M '+sy+' '+sx+' V '+((sx+tx)/2)+' H '+ty+' V '+tx:'M '+sx+' '+sy+' H '+((sx+tx)/2)+' V '+ty+' H '+tx}"/>`;}).join('');
 return `<div class="talent-tree-board"><svg class="tree-connectors horizontal" viewBox="0 0 700 300" preserveAspectRatio="none" aria-hidden="true">${lines(false)}</svg><svg class="tree-connectors vertical" viewBox="0 0 300 700" preserveAspectRatio="none" aria-hidden="true">${lines(true)}</svg><div class="tree-tiers" aria-hidden="true">${roman.map(n=>`<span>${n}</span>`).join('')}</div><div class="talent-full-tree" role="group" aria-label="${RACE_NAMES[r]}${LINE_NAMES[line]}完整天赋树">${list.map((t,i)=>`<button class="talent-map-node ${(levels[t.id]??0)>0?'learned':''} ${!nextTalentPurchase(r,levels,t.id,balance)?'available':''}" data-action="mvp-talent-select" data-id="${t.id}" style="--tier:${t.tier};--lane:${slot(t)}" aria-label="${esc(text(t).name)}，${levels[t.id]??0} / ${t.maxRank}级">${image(iconFor(t,i))}<b>${esc(text(t).name)}</b><small>${levels[t.id]??0}<span> / ${t.maxRank}</span></small></button>`).join('')}</div></div>`;
}
export type TalentPage='races'|'lines'|'tree'|'node'|'presets';
export function renderTalentScreens(profile:PermanentProfile,selectedId:string|null,view:{race:Race;line:TalentLine;page:TalentPage}){
 const r=view.race,levels=profile.levelsFor(r),balance=profile.raceBalance(r),spent=profile.spentFor(r),points=allocationPoints(levels),page=view.page==='node'?'tree':view.page==='presets'?'lines':view.page,level=page==='lines'?'paths':page,heading=page==='races'?'天赋':page==='lines'?RACE_NAMES[r]+'天赋':LINE_NAMES[view.line];
 const trail=`<nav class="talent-breadcrumb" aria-label="天赋菜单"><button data-action="talent-level" data-page="races" ${page==='races'?'aria-current="page"':''}>种族</button><span>›</span>${page==='races'?'<span>方向</span>':`<button data-action="talent-level" data-page="lines" ${page==='lines'?'aria-current="page"':''}>${RACE_NAMES[r]}</button>`}<span>›</span><span ${page==='tree'?'aria-current="page"':''}>${page==='tree'?LINE_NAMES[view.line]:'天赋树'}</span></nav>`;
 let body=page==='races'?`<section class="talent-race-menu" aria-label="选择天赋种族">${RACES.map(id=>{const v=RACE_VISUALS[id];return `<button class="talent-race-choice panel" data-action="mvp-talent-race" data-race="${id}" style="--choice-accent:${v.accent}"><div class="talent-choice-art"><img class="painted-cover" src="${assetUrl('ui.cover.'+COVER_HEROES[id][0])??''}" alt=""></div><div class="talent-choice-copy"><small>${v.english}</small><h2>${RACE_NAMES[id]}</h2><p>${v.title}</p><span>${profile.levelFor(id)} / 80</span>${glyph('next')}</div></button>`;}).join('')}</section>`:page==='lines'?`<section class="talent-path-menu" aria-label="选择天赋方向">${(Object.keys(LINE_NAMES) as TalentLine[]).map((line,i)=>{const list=listFor(r,line),sum=list.reduce((n,t)=>n+(levels[t.id]??0),0),cap=list.reduce((n,t)=>n+t.maxRank,0);return `<button class="talent-path-choice panel" data-action="talent-line" data-line="${line}"><span class="path-number">0${i+1}</span><div class="path-icon">${image(line==='army'?'hero.'+COVER_HEROES[r][0]:LINE_ICONS[line])}</div><h2>${LINE_NAMES[line]}</h2><p>${LINE_COPY[line][0]}</p><small>${LINE_COPY[line][1]}</small><div class="path-progress"><i style="--fill:${sum/cap*100}%"></i></div><span class="path-investment">${sum} / ${cap}</span>${glyph('next')}</button>`;}).join('')}</section>`:tree(r,view.line,levels,balance);
 let layer='';const t=TALENT_BY_ID.get(selectedId??'');
 if(view.page==='node'&&t?.race===r){const lv=levels[t.id]??0,reason=talentPlayerReason(nextTalentPurchase(r,levels,t.id,balance),t);layer=modal(text(t).name,LINE_NAMES[t.line]+' · 第 '+roman[t.tier-1]+' 阶',`<div class="talent-modal-title">${image(iconFor(t))}<div><span>${lv} / ${t.maxRank}</span><p>${esc(text(t).flavour)}</p></div></div><div class="talent-effects"><p>${esc(gameText(t.description))}</p></div>${requirements(t,levels).length?`<section class="talent-requirements"><h2>学习条件</h2>${requirements(t,levels).map(req=>`<div class="${req.ready?'ready':''}">${glyph(req.ready?'check':'hex')}<span>${esc(req.label)}</span></div>`).join('')}</section>`:''}<div class="talent-learn-cost"><span>天赋资源</span>${glyph('hex')}<b>${t.resourceCost}</b><span>· 1 点</span></div>`,'talent-modal talent-node-layer',button('返回天赋树','talents-back','secondary')+button(reason??'学习','mvp-talent-buy','primary',`data-id="${t.id}" ${reason?'disabled':''}`),'talents-back');}
 if(view.page==='presets'){layer=modal('天赋预设',RACE_NAMES[r],`<div class="preset-tabs">${([0,1,2] as const).map(slot=>{const p=profile.getPreset(r,slot)!,price=allocationCost(p.levels);return `<button data-action="mvp-talent-preset" data-slot="${slot}" aria-pressed="${profile.activePresetFor(r)===slot}" ${balance+spent>=price?'':'disabled'}><b>${esc(p.name)}</b><small>${allocationPoints(p.levels)} 点 · ${price} 资源</small></button>`;}).join('')}</div><p>余额 ${balance} · 已投入 ${spent}</p>${button('复制到下一方案','mvp-talent-copy','small',`data-slot="${(profile.activePresetFor(r)+1)%3}"`)}`,'talent-modal',button('返回','talents-back','primary'),'talents-back');}
 return `<section class="talent-screen level-${level}"><header class="talent-heading"><div>${iconButton('back',page==='races'?'返回':'返回上级','talents-back')}<h1>${heading}</h1></div><div class="talent-ledger"><span class="talent-point-count"><b>${points}</b> / 80</span><span class="talent-budget">${glyph('hex')}<b>${balance}</b></span></div></header>${trail}${body}<footer class="talent-menu-footer">${page!=='races'?button('洗点','mvp-talent-respec','small',`data-line="all" ${spent?'':'disabled'}`)+iconButton('info','查看天赋规则','talent-rules')+button('方案','talent-presets','small'):'<span>磨好利刃，再上战场。</span>'}${button('返回','talent-exit','primary')}</footer></section>${layer}`;
}
