import {heroAbilityCopy} from './ability-copy';
import type {World} from '../../simulation/world';
import type {Entity} from '../../simulation/types';
import type {FamilyId} from '../../data/races';
import {RACE_NAMES} from '../../data/races';
import {unitData,expeditionWeaponBonuses} from '../../simulation/combat/expedition-combat';
import {protossEliteBonuses} from '../../simulation/combat/protoss-elite-runtime';
import {HEROES,type HeroId} from '../../data/heroes';
import {ELITES} from '../../data/elites';
import {statusReadout,rankLabel} from '../unit-identity';
import {paintedArt} from './painted-art';
import {image,glyph,esc} from './reference-primitives';
import {ATTR_NAMES,WEAPON_NAMES,NATIVE_ABILITIES,HERO_PASSIVES,gameText} from './game-copy';
export type InspectorTab='stats'|'abilities'|'army';
export interface UnitSeat {key:string;family?:FamilyId;unit?:Entity;bodies:Entity[];name:string;image:string;hero?:HeroId;defeated?:boolean;regrowAt?:number}
const n=(v:number)=>Number.isFinite(v)?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):'—';
const health=(label:string,v:number,max:number,cls='')=>`<div class="ui12-vital ${cls}"><div><span>${label}</span><strong>${n(Math.max(0,Math.ceil(v-1e-7)))}<small> / ${n(Math.ceil(max))}</small></strong></div><div class="ui12-meter" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${Math.ceil(max)}" aria-valuenow="${Math.max(0,Math.ceil(v))}"><i style="--fill:${max>0?Math.max(0,Math.min(100,v/max*100)):0}%"></i></div></div>`;
/** Pure projections of live entities. Inspection never constructs a body or pauses the world. */
export function inspectorStats(w:World,u:Entity){const data=unitData(u),medical=!u.heroId&&['medivac','science_vessel'].includes(u.unitType),children=[...w.entities.values()].filter(c=>c.summonOwnerId===u.id&&c.hp>0),period=u.shotInterval>0&&u.lastShotAt>=u.bornAt?u.shotInterval:u.attackPeriod;return {medical,children,damage:u.weaponDamage,attacks:data.attacks,period,basePeriod:u.attackPeriod,healing:u.healRate,targets:u.healTargets??(u.healTarget?[u.healTarget]:[]),range:u.attackRange,target:data.targetType,move:u.moveSpeed,armor:u.armor,shieldArmor:u.shieldArmor??0};}
function rows(w:World,s:UnitSeat){const u=s.unit,id=s.hero??u?.heroId,result:{id:string;name:string;body:string;tag:string;meta?:string}[]=[];
 if(id){const h=HEROES[id],state=w.heroes.get(id),left=Math.max(0,(state?.skillReady??w.time)-w.time),casting=w.heroCasts.some(c=>c.hero===id&&c.phase!=='dot'),copy=heroAbilityCopy(id);result.push({id:'active',name:h.skill,body:copy.active,tag:'主动',meta:!u?'未部署':casting?'施放中':left>0?`冷却 ${Math.ceil(left)} 秒`:'就绪'},{id:'passive',name:HERO_PASSIVES[id]??'固有能力',body:copy.passive,tag:'被动'});}
 if(u?.eliteId)result.push({id:'elite',name:ELITES[u.eliteId].name,body:ELITES[u.eliteId].description,tag:'精英'});
 if(!id&&s.family){const base=NATIVE_ABILITIES[s.family]??[WEAPON_NAMES[s.family],'自动打击射程内的敌人。'];result.push({id:'native',name:base[0],body:base[1],tag:'能力'});}
 if(u?.maxEnergy)result.push({id:'energy',name:'能量恢复',body:`每秒恢复 ${n(u.energyRegen)} 能量。施法等待 ${Math.max(0,Math.ceil((u.abilityReady??w.time)-w.time))} 秒。`,tag:'能源'});
 return result;
}
function stats(w:World,s:UnitSeat){const u=s.unit;if(!u)return `<p class="ui12-empty">${s.hero?(w.heroes.get(s.hero)?.revivePaid?'复活已备妥，下关归队。':'英雄已阵亡，可在整备时复活。'):s.regrowAt!==undefined?(s.family==='zergling'?'跳虫再生中 · ':'重生中 · ')+Math.max(0,Math.ceil((s.regrowAt-w.tick)/60))+' 秒':'等待训练或增援。'}</p>`;
 const d=unitData(u),bonuses=protossEliteBonuses(u,expeditionWeaponBonuses(w,u).bonuses),v=inspectorStats(w,u),child=v.children[0],weapon=child?'截击机':s.hero?'普通攻击':WEAPON_NAMES[u.unitType]??'武器',cells:[string,string,string,string][]=[];
 if(v.medical)cells.push(['每秒治疗',n(v.healing),'生命','shield'],['行动方式',u.flying?'空中':'地面','支援','hex']);
 else cells.push([child?'单机伤害':'武器伤害',v.target==='none'&&!child?'—':n(child?.weaponDamage??v.damage)+(v.attacks>1?' × '+v.attacks:''),'','swords'],['攻击间隔',v.target==='none'&&!child?'—':n(child?.attackPeriod??v.period),v.target==='none'&&!child?'':'秒','refresh']);
 cells.push(['护甲',n(v.armor),'','shield']);if(u.maxShield)cells.push(['护盾护甲',n(v.shieldArmor),'','hex']);cells.push(['移动速度',n(v.move),'','arrow'],[v.medical?'治疗目标':'攻击目标',v.medical?'友军':({ground:'地面',air:'空中',both:'地面 / 空中',none:child?'所属战机':'—'})[v.target],'','target']);if(!v.medical)cells.push(['射程',v.range<=.2?'近战':n(v.range),'','eye']);
 const mode=u.nativeMode??(u.unitType==='tank'?u.mode:''),modeName=({tank:'坦克',siege:'架炮',hellion:'恶火',hellbat:'恶蝠',viking_assault:'突击',lurker_burrowed:'潜地',lurker:'移动'} as Record<string,string>)[mode??''];
 return `<div class="ui12-stats" aria-label="核心属性" data-weapon="${esc(weapon)}">${cells.map(([label,value,unit,icon])=>`<div class="ui12-stat"><span class="ui12-stat-icon">${glyph(icon)}</span><div><span>${label}</span><strong>${value}${unit?`<small>${unit}</small>`:''}</strong></div></div>`).join('')}</div>${v.children.length?`<div class="ui12-hangar">${image('unit.carrier')}<span>出击中</span><strong>${v.children.length}<small> 架</small></strong></div>`:''}${bonuses.length?`<div class="ui12-bonus">${glyph('target')}${bonuses.map(b=>`对${ATTR_NAMES[b.attribute]??b.attribute} +${n(b.amount)}`).join(' · ')}</div>`:''}${modeName?`<p class="ui12-state">${modeName}模式</p>`:''}${v.medical?`<p class="ui12-state">照护 ${v.targets.length} 名 · 异类恢复为 1/3</p>`:''}${statusReadout(w,u).detail?`<p class="ui12-state">${esc(gameText(statusReadout(w,u).detail))}</p>`:''}${u.recoveryUntil&&u.recoveryUntil>w.time?`<p class="ui12-state">恢复 ${Math.ceil(u.recoveryUntil-w.time)} 秒</p>`:''}${u.heroId==='dehaka'?`<p class="ui12-state">精华 ${n(u.zergCombat?.essence??0)} · 生命储备 ${n((u.zergCombat?.reserveUntil??0)>w.time?u.zergCombat?.reserve??0:0)}</p>`:''}${u.eliteId||s.hero?`<button class="ui12-signature ${s.hero?'hero':''}" data-inspect-tab="abilities">${s.hero?image(s.image):'<span>◆</span>'}<div><small>${s.hero?'英雄技能':'精英特性'}</small><strong>${esc(s.hero?HEROES[s.hero].skill:ELITES[u.eliteId!].name)}</strong></div>${s.hero?`<span class="ui12-ready">${rows(w,s)[0]?.meta??''}</span>`:''}${glyph('next')}</button>`:''}`;
}
function portrait(s:UnitSeat,selected:string){const u=s.unit;return `<button class="ui12-roster-unit ${s.hero?'hero':u?.eliteId?'elite':'ordinary'} ${s.key===selected?'focused':''}" data-inspect-seat="${s.key}" aria-label="切换到${esc(s.name)}" aria-pressed="${s.key===selected}">${s.image?image(s.image):''}<span class="portrait-rank">${u?rankLabel(u.rank):''}</span>${s.hero||u?.eliteId?`<span class="portrait-badge">${s.hero?'★':'◆'}</span>`:''}<span class="portrait-hp"><i style="--fill:${u?u.hp/u.maxHp*100:0}%"></i></span>${u?.maxShield?`<span class="portrait-shield"><i style="--fill:${(u.shield??0)/u.maxShield*100}%"></i></span>`:''}${s.family==='zergling'?`<span class="twin-count">${s.bodies.length}/2</span>`:''}</button>`;}
export function renderUnitInspector(w:World,s:UnitSeat,all:readonly UnitSeat[],tab:InspectorTab,expanded:ReadonlySet<string>){
 const u=s.unit,rank=u?.rank??(s.hero?w.heroes.get(s.hero)?.rank:0)??0,id=u?.heroId??u?.eliteId??s.hero??s.family??'',kind=s.hero?'hero':u?.eliteId?'elite':'ordinary',index=all.indexOf(s),count=(typeof document==='undefined'?1280:document.querySelector('#game-root')?.clientWidth??1280)<430?3:5,start=Math.max(0,Math.min(all.length-count,index-Math.floor(count/2))),abilities=rows(w,s),d=u?unitData(u):null;
 const content=tab==='stats'?stats(w,s):tab==='abilities'?`<div class="ui12-abilities">${abilities.map(row=>`<section class="ui12-ability ${expanded.has(row.id)?'open':''}"><details class="ui12-ability-details" data-ability="${row.id}" ${expanded.has(row.id)?'open':''}><summary>${image(s.image)}<span><small>${row.tag}</small><strong>${esc(row.name)}</strong></span>${row.meta?`<em>${row.meta}</em>`:''}${glyph('next')}</summary><div class="ui12-ability-copy"><p>${esc(gameText(row.body))}</p></div></details></section>`).join('')}</div>`:`<div class="ui12-full-roster" aria-label="部队一览">${all.map((v,i)=>`<button data-inspect-seat="${v.key}" class="ui12-roster-choice ${v.hero?'hero':v.unit?.eliteId?'elite':'ordinary'}" aria-pressed="${v.key===s.key}" aria-label="切换到${esc(v.name)}">${image(v.image)}<b>${v.hero?'★':v.unit?.eliteId?'◆':i+1}</b><small>${esc(v.name)}</small></button>`).join('')}</div>`;
 const twin=s.family==='zergling',timer=s.regrowAt!==undefined?Math.max(0,Math.ceil((s.regrowAt-w.tick)/60)):null;
 return `<div class="modal-scrim ui12-scrim"><section class="modal-window ui12-window" role="dialog" aria-modal="true" aria-labelledby="ui12-name" tabindex="-1" data-kind="${kind}" data-tab="${({stats:'stats',abilities:'skills',army:'roster'})[tab]}" data-unit-identity="${esc(id)}" data-unit-rank="${rank}" data-unit-key="${s.key}"><header class="ui12-header"><div class="ui12-title"><span class="ui12-class">${({ordinary:'作战单位',elite:'精英',hero:'英雄'})[kind]}<i> / </i>${RACE_NAMES[w.expedition.race]}</span><h1 id="ui12-name">${esc(s.name)}<b class="ui12-rank" aria-label="军衔 ${rank}">${rank?rankLabel(rank):''}</b></h1></div><button class="icon-button ui12-close" data-inspect-close aria-label="返回战场" data-autofocus>${glyph('close')}</button></header><div class="ui12-body"><aside class="ui12-visual"><div class="ui12-art">${paintedArt(id,s.name,twin?Math.max(1,s.bodies.length):1,'inspector-'+s.key)}<span class="ui12-art-fade"></span><div class="ui12-traits">${[u?(u.flying?'空中':'地面'):'未部署',...(d?.attributes??[]).filter(a=>a!=='Heroic').map(a=>ATTR_NAMES[a]).filter(Boolean)].map(a=>`<span>${a}</span>`).join('')}</div><div class="ui12-rank-marks" aria-hidden="true">${Array.from({length:5},(_,i)=>`<i class="${i<rank?'lit':''}"></i>`).join('')}</div></div><div class="ui12-vitals">${s.bodies.map((b,i)=>health(twin?'跳虫 '+['①','②'][i]:'生命',b.hp,b.maxHp,b.hp/b.maxHp<.3?'critical':'')).join('')}${twin&&s.bodies.length<2?health('跳虫 ②'+(timer!==null?' · 再生 '+timer+' 秒':''),0,u?.maxHp??0,'critical'):''}${u?.maxShield?health('护盾',u.shield??0,u.maxShield,'shield'):''}${u?.maxEnergy?health('能量',u.energy,u.maxEnergy,'energy'):''}${!u?'<p class="ui12-state">暂无存活战士</p>':''}</div></aside><div class="ui12-readout"><div class="ui12-tabs" role="tablist" aria-label="单位信息">${(['stats','abilities','army'] as const).map(k=>`<button role="tab" id="ui12-${k}-tab" aria-selected="${tab===k}" aria-controls="ui12-tabpanel" data-inspect-tab="${k}">${k==='stats'?'属性':k==='abilities'?s.hero?'技能':'能力':'部队'}${k==='stats'?'':`<span>${k==='army'?all.length:String(abilities.length).padStart(2,'0')}</span>`}</button>`).join('')}</div><div id="ui12-tabpanel" class="inspector-content" role="tabpanel" aria-labelledby="ui12-${tab}-tab" tabindex="0" data-inspector-scroll>${content}</div></div></div><footer class="ui12-footer"><div class="ui12-roster"><button class="ui12-step" data-inspect-neighbor="-1" aria-label="上一个单位" ${index===0?'disabled':''}>${glyph('back')}</button><div class="ui12-roster-list" aria-label="切换作战单位">${all.slice(start,start+count).map(v=>portrait(v,s.key)).join('')}</div><button class="ui12-step" data-inspect-neighbor="1" aria-label="下一个单位" ${index===all.length-1?'disabled':''}>${glyph('next')}</button></div><span class="ui12-index"><b>${String(index+1).padStart(2,'0')}</b> / ${all.length}</span><button class="game-button ui12-return" data-inspect-close><span>返回战场 <kbd>Esc</kbd></span></button></footer></section></div>`;
}
