import {facilities,technology,type BaseTab} from '../presentation/base-panels';
import type {World} from '../../simulation/world';

import {SC2_UNITS,type UnitType} from '../../data/sc2-units';
import {PRODUCTION_LINES,type ProductionLineId} from '../../data/expedition-buildings';
import type {FamilyId} from '../../data/races';
import {button,image,glyph,modal,esc} from '../presentation/reference-primitives';
import {rankLabel} from '../unit-identity';
const cost=(m:number,g:number)=>m+' 矿'+(g?' / '+g+' 气':'');
const name=(f:FamilyId)=>f in SC2_UNITS?SC2_UNITS[f as UnitType].zh:'科技球';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderRepairs(w:World){const ordinary=w.expedition?.familySlots??[];const groups=[{family:'',label:'全队',ids:w.allies().filter(u=>!u.temporary&&!u.summonOwnerId).map(u=>u.id)},...ordinary.map(family=>({family,label:name(family),ids:w.familyBodies(family).filter(u=>!u.temporary&&!u.summonOwnerId).map(u=>u.id)}))];return `<div class="repair-services"><h4>修复部队</h4>${groups.map(group=>{const quote=w.previewRepair(group.ids),enabled=quote&&quote.health>0&&w.wallet.minerals>=quote.minerals&&w.wallet.gas>=quote.gas;return `<button class="small" data-action="repair-all" data-family="${group.family}" data-quote="${escape(quote?.id??'')}" ${enabled?'':'disabled'}>${group.label}生命修复 · ${quote?.minerals??0} 矿／${quote?.gas??0} 气${!quote?.health?' · 无伤损':''}</button>`;}).join('')}</div>`;}
function renderTacticalPlans(w:World){const s=w.expedition;if(!s||!w.talent('star_warrior'))return '';
 return `<div class="tactical-plans"><h4>战术进阶</h4><p>满员满级后，生产可用于战术进阶。</p>${s.familySlots.map(f=>{const plan=s.tacticalPlans[f],candidates=w.ordinaryUnits(f).filter(u=>u.hp>0&&u.rank>=5&&(u.tacticalTier??0)<5),pending=s.ledger.filter(j=>j.family===f).reduce((n,j)=>n+j.passengers.filter(p=>p.status==='waiting'&&p.purpose==='tacticalProgress').length,0),cancel=w.previewTacticalEvolutionCancellation(f);
 return `<fieldset data-tactical-family="${f}"><legend>${name(f)}${plan?` · 进阶储备 ${plan.bank}+${pending}/5`:''}</legend><select data-tactical-target aria-label="${name(f)}进阶目标">${candidates.map((u,i)=>`<option value="${u.id}" ${plan?.targetEntityId===u.id?'selected':''}>${name(f)} ${i+1} · 军衔 ${rankLabel(u.rank)} · ${u.tacticalTier??0}阶</option>`).join('')}</select><select data-tactical-direction aria-label="${name(f)}进阶方向">${([['assault','突击'],['guard','坚守'],['mobility','机动']] as const).map(([value,label])=>`<option value="${value}" ${plan?.direction===value?'selected':''}>${label}</option>`).join('')}</select><button class="small" data-action="tactical-bind" data-family="${f}" ${candidates.length?'':'disabled'}>${plan?'更新目标':'选择目标'}</button>${plan?`<button class="small" data-action="tactical-toggle" data-family="${f}" aria-pressed="${plan.enabled}">${plan.enabled?'暂停进阶':'继续进阶'}</button><button class="small" data-action="tactical-cancel" data-family="${f}" data-revision="${cancel?.revision}">确认取消 · 退 ${cancel?.refund.minerals??0} 矿／${cancel?.refund.gas??0} 气，已投放损失 ${cancel?.lost??0}，清空 ${cancel?.bank??0} 份储备</button>`:''}</fieldset>`;}).join('')}</div>`;
}
export function renderProductionWindow(w:World,tab:BaseTab='facilities',back='ui-back'){
 const s=w.expedition,body=tab==='production'?`<div class="production-list">${Object.entries(PRODUCTION_LINES).filter(([,d])=>d.race===s.race).map(([id,d])=>{const p=s.production[id as ProductionLineId],facilities=s.facilities.filter(f=>f.line===id),jobs=s.ledger.filter(j=>j.line===id&&j.state!=='settled'),job=jobs[0],enabled=!!p?.outputs.some(f=>p.enabled[f]),icon=id==='barracks'||id==='factory'||id==='starport'?'building.'+id:'unit.'+d.families[0];return `<section class="production-row"><div class="production-name">${image(icon)}<div><h2>${d.name}</h2><span>${facilities.length} 座 · ${p?.outputs.length?'援军集结':'等待解锁'}</span></div><button class="toggle-switch" data-action="production-line-enable" data-line="${id}" aria-label="${d.name}训练开关" aria-pressed="${enabled}" ${p?.outputs.length?'':'disabled'}>${enabled?'开启':'待命'}<i></i></button></div><div class="production-units">${d.families.filter(f=>w.isFamilyAvailable(f)||p?.outputs.includes(f)).map(f=>`<div class="production-unit-control"><button data-action="production-output" data-line="${id}" data-family="${f}" aria-pressed="${!!p?.outputs.includes(f)}" ${!p||!p.outputs.includes(f)&&p.outputs.length>=2?'disabled':''}>${image('unit.'+f)}${name(f)}</button>${p?.outputs.includes(f)?`<button class="toggle-switch unit-training-toggle" data-action="production-enable" data-family="${f}" aria-label="${name(f)}生产" aria-pressed="${!!p.enabled[f]}">${p.enabled[f]?'生产中':'已关闭'}<i></i></button>`:''}</div>`).join('')||'<span class="muted">尚未解锁兵种</span>'}</div><div class="production-order"><span>${job?name(job.family)+' × '+job.passengers.filter(c=>c.status==='waiting').length+' · '+(job.state==='training'?'训练中 · '+Math.ceil(job.remaining)+' 秒':'援军待命 · 等待救援'):enabled?'等待下一批训练':'待命'}${jobs.length>1?' · '+jobs.length+' 批订单':''}</span></div></section>`;}).join('')}</div><div class="production-services">${button('生命修复','ui-rest-repair','small')}${button('英雄复活','ui-rest-revivals','small')}</div>`+`<div class="production-list">${s.race==='zerg'?s.facilities.map((f,i)=>`<label class="setting-row"><span>孵化场 ${i+1}</span><select data-setting="hatchery-sequence" data-id="${f.id}" ${s.ledger.some(j=>j.state==='training'&&j.facilityIds.includes(f.id))?'disabled':''}>${(['zerg.basic','zerg.evolution','zerg.air'] as const).map(line=>`<option value="${line}" ${f.line===line?'selected':''}>${PRODUCTION_LINES[line].name}</option>`).join('')}</select></label>`).join(''):''}${renderTacticalPlans(w).replace(/Rank /g,'军衔 ').replace(/成员 \d+/g,'士兵')}</div>`:tab==='facilities'?facilities(w):technology(w);
 return modal('设施调整','',`<nav class="settings-tabs" role="group" aria-label="生产类别">${(['facilities','production','technology'] as const).map(id=>button(({facilities:'设施',production:'训练',technology:'当前科技'})[id],'ui-production-tab','',`data-tab="${id}" aria-pressed="${tab===id}"`)).join('')}</nav>${body}`,'production-modal',button('完成整备',back,'primary'),back);
}
export function renderFamilyReceipt(w:World){const s=w.expedition,r=s?.pendingReceipt;if(!s||!r)return '';return modal('接收增援','兵种 '+s.familySlots.length+' / 5','<div class="incoming-family">'+image('unit.'+r.family)+'<div><h2>'+name(r.family)+'</h2><p>已抵达</p></div><details class="inline-rule"><summary class="info-button" aria-label="查看轮换部队说明">'+glyph('info')+'</summary><p>让一支小队撤离，为新援军腾出位置。尚未登舰的训练费用返还，已经出发的部队不退款。培养按一半继承；科技与强化保留。</p></details></div><div class="family-list">'+s.familySlots.map(f=>{const p=w.previewFamilyReplacement(r.id,f);return '<button data-action="family-replace" data-old="'+f+'" data-request="'+esc(r.id)+'" data-revision="'+w.revision+'" '+(p?'':'disabled')+'>'+image('unit.'+f)+'<div><b>'+name(f)+'</b><span>'+(p?.members.map(u=>rankLabel(u.rank)+' → '+rankLabel(u.toRank)+(u.eliteId?' · 精英退役':'')).join(' / ')||'暂无存活战士')+'</span><small>返还 '+cost(p?.refund.minerals??0,p?.refund.gas??0)+' · 已出发损失 '+(p?.lostPassengers??0)+' 名</small></div>'+glyph('next')+'</button>';}).join('')+'</div>','family-modal family-receipt',button('放弃增援 · 不退款','family-reject','secondary','data-request="'+esc(r.id)+'" data-revision="'+w.revision+'"'),'restart');}
