import type {World} from '../../simulation/world';
import {SC2_UNITS,type UnitType} from '../../data/sc2-units';
import {DEVELOPMENT,PRODUCTION_LINES,type ProductionLineId} from '../../data/expedition-buildings';
import type {FamilyId} from '../../data/races';
const name=(f:FamilyId)=>f in SC2_UNITS?SC2_UNITS[f as UnitType].zh:'科技球';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function renderRepairs(w:World){const ordinary=w.expedition?.familySlots??[];const groups=[{family:'',label:'全队',ids:w.allies().filter(u=>!u.temporary&&!u.summonOwnerId).map(u=>u.id)},...ordinary.map(family=>({family,label:name(family),ids:w.familyUnits(family).filter(u=>!u.temporary&&!u.summonOwnerId).map(u=>u.id)}))];return `<div class="repair-services"><h4>驻地生命修复</h4>${groups.map(group=>{const quote=w.previewRepair(group.ids),enabled=quote&&quote.health>0&&w.wallet.minerals>=quote.minerals&&w.wallet.gas>=quote.gas;return `<button class="small" data-action="repair-all" data-family="${group.family}" data-quote="${escape(quote?.id??'')}" ${enabled?'':'disabled'}>${group.label}生命修复 · ${quote?.minerals??0} 矿／${quote?.gas??0} 气${!quote?.health?' · 无伤损':''}</button>`;}).join('')}</div>`;}
function renderTacticalPlans(w:World){const s=w.expedition;if(!s||!w.talent('star_warrior'))return '';
 return `<div class="tactical-plans"><h4>七份付费最终体 · 战术进阶 I—V</h4><p>只有同家族满员且培养已满时，未来付款才会投入进阶；已付款乘员保持用途。</p>${s.familySlots.map(f=>{const plan=s.tacticalPlans[f],candidates=w.ordinaryUnits(f).filter(u=>u.hp>0&&u.rank>=5&&(u.tacticalTier??0)<5),pending=s.ledger.filter(j=>j.family===f).reduce((n,j)=>n+j.passengers.filter(p=>p.status==='waiting'&&p.purpose==='tacticalProgress').length,0),cancel=w.previewTacticalEvolutionCancellation(f);
 return `<fieldset data-tactical-family="${f}"><legend>${name(f)}${plan?` · 进阶票 ${plan.bank}+${pending}/7`:''}</legend><select data-tactical-target aria-label="${name(f)}进阶目标">${candidates.map(u=>`<option value="${u.id}" ${plan?.targetEntityId===u.id?'selected':''}>成员 ${u.id} · Rank ${u.rank} · ${u.tacticalTier??0}阶</option>`).join('')}</select><select data-tactical-direction aria-label="${name(f)}进阶方向">${([['assault','突击'],['guard','坚守'],['mobility','机动']] as const).map(([value,label])=>`<option value="${value}" ${plan?.direction===value?'selected':''}>${label}</option>`).join('')}</select><button class="small" data-action="tactical-bind" data-family="${f}" ${candidates.length?'':'disabled'}>${plan?'维持／更新绑定':'绑定目标'}</button>${plan?`<button class="small" data-action="tactical-toggle" data-family="${f}" aria-pressed="${plan.enabled}">${plan.enabled?'停止未来付款':'继续未来付款'}</button><button class="small" data-action="tactical-cancel" data-family="${f}" data-revision="${cancel?.revision}">确认取消 · 退 ${cancel?.refund.minerals??0} 矿／${cancel?.refund.gas??0} 气，已投放损失 ${cancel?.lost??0}，销毁 ${cancel?.bank??0} 票</button>`:''}</fieldset>`;}).join('')}</div>`;
}
export function renderExpeditionProduction(w:World){const s=w.expedition;if(!s)return '';return `<section class="expedition-production"><h3>持续生产</h3><p>每条线最多选两种，交替生产。关闭只影响下一笔付款。</p>${Object.entries(s.production).map(([id,p])=>{const line=id as ProductionLineId,definition=PRODUCTION_LINES[line],facilities=s.facilities.filter(f=>f.line===line),job=s.ledger.find(j=>j.line===line&&j.state!=='settled');return `<fieldset><legend>${escape(definition.name)} · ${facilities.length} 座</legend><div class="production-choices">${definition.families.filter(f=>w.isFamilyAvailable(f)||p?.outputs.includes(f)).map(f=>`<span><button class="small" data-action="production-output" data-line="${id}" data-family="${f}" aria-pressed="${p!.outputs.includes(f)}" ${!p!.outputs.includes(f)&&p!.outputs.length>=2?'disabled':''}>${name(f)}</button>${p!.outputs.includes(f)?`<button class="small" data-action="production-enable" data-family="${f}" aria-label="${name(f)}未来生产" aria-pressed="${!!p!.enabled[f]}">${p!.enabled[f]?'生产中':'已关闭'}</button>`:''}</span>`).join('')||'<small>尚未解锁兵种</small>'}</div>${job?`<small>${name(job.family)} × ${job.passengers.filter(c=>c.status==='waiting').length} · ${job.state==='training'?Math.ceil(job.remaining)+' 秒后完成':'已付款，等待救援'}</small>`:''}</fieldset>`;}).join('')}${s.race==='zerg'?`<div>${s.facilities.map(f=>`<label>孵化设施 ${f.id}<select data-setting="hatchery-sequence" data-id="${f.id}" ${s.ledger.some(j=>j.state==='training'&&j.facilityIds.includes(f.id))?'disabled':''}>${(['zerg.basic','zerg.evolution','zerg.air'] as const).map(line=>`<option value="${line}" ${f.line===line?'selected':''} ${line==='zerg.evolution'&&!s.tech.lair||line==='zerg.air'&&!s.tech.spire?'disabled':''}>${PRODUCTION_LINES[line].name}</option>`).join('')}</select></label>`).join('')}</div>`:''}<label>下次发展目标<select data-setting="development-target"><option value="">跟随当前编制</option>${DEVELOPMENT.filter(d=>d.race===s.race).map(d=>`<option value="${d.id}" ${s.developmentTarget===d.id?'selected':''}>${d.name}</option>`).join('')}</select></label>${renderRepairs(w)}${renderTacticalPlans(w)}</section>`;}
export function renderFamilyReceipt(w:World){const s=w.expedition,r=s?.pendingReceipt;if(!s||!r)return '';return `<div class="reward-screen family-receipt"><span class="eyebrow">增援已抵达 · 战斗暂停</span><h2>接收${name(r.family)}</h2><p>五个家族槽已满。选择退役家族；每种人数上限仍为5，培养按一半继承。</p><div id="reward-cards">${s.familySlots.map(f=>{const p=w.previewFamilyReplacement(r.id,f);return `<button class="reward-card" data-action="family-replace" data-old="${f}" data-request="${escape(r.id)}" data-revision="${w.revision}" ${p?'':'disabled'}><h3>退役${name(f)}</h3><p>${p?.members.map(u=>`等级 ${u.rank} → ${u.toRank}${u.eliteId?'（精英退役）':''}`).join('<br>')||'该家族当前无存活成员'}</p><p>返还训练付款：${p?.refund.minerals??0} 矿／${p?.refund.gas??0} 气</p><p>已投放不退款：${p?.lostPassengers??0} 名</p><small>关闭${name(f)}未来生产，已研究科技与强化保留。</small></button>`;}).join('')}</div><button class="refresh" data-action="family-reject" data-request="${escape(r.id)}" data-revision="${w.revision}">放弃本批并关闭${name(r.family)}未来生产（不退款）</button></div>`;}
export function renderUnitOperations(w:World){const s=w.expedition;if(!s)return '';const controls:Partial<Record<FamilyId,[string,string][]>>={tank:[['tank','收炮'],['siege','架炮']],hellion:[['hellion','恶火'],['hellbat','恶蝠']],viking:[['viking','战机'],['viking_assault','突击']],thor:[['thor','爆裂弹'],['thor_high_impact','高冲击弹']],lurker:[['lurker','钻出'],['lurker_burrowed','埋地']]};return `<div class="unit-operations"><h3>单位操作</h3>${s.familySlots.map(f=>controls[f]?.map(([mode,label])=>`<button class="small" data-action="unit-mode" data-family="${f}" data-mode="${mode}" ${f==='hellion'&&mode==='hellbat'&&!s.tech.armory?'disabled':''}>${name(f)} · ${label}</button>`).join('')??(f==='banshee'&&s.tech.cloak?'<button class="small" data-action="family-ability" data-family="banshee">女妖 · 切换隐形</button>':f==='stalker'&&s.tech.blink?'<button class="small" data-action="family-ability" data-family="stalker">追猎者 · 选择闪烁落点</button>':'')).join('')}${w.talent('airlift')?`<button class="small" data-action="airlift" ${w.time<w.airliftReady||!!w.talentTransferPlan?'disabled':''}>${s.race==='terran'?'空运':s.race==='zerg'?'地下转移':'战场召回'} · 选择落点</button>`:''}<button class="small" data-action="unit-operations-close">关闭</button></div>`;}
