import {COVER_HEROES,paintedArt} from '../presentation/painted-art';
import {assetUrl} from '../../assets/manifest';
import {RACES,RACE_NAMES,type Race} from '../../data/races';
import {HEROES,HERO_IDS_BY_RACE,type HeroId} from '../../data/heroes';
import {SC2_UNITS} from '../../data/sc2-units';
import {talentRank} from '../../data/mvp-talents';
import type {Difficulty} from '../../data/stages';
import type {PermanentProfile,PresetSlot} from '../../simulation/progression/permanent-profile';
import type {LoadPreview,RunSession} from '../../app/run-session';
import type {ReadinessState} from '../../app/asset-readiness';
import {button,iconButton,glyph,image,money,masthead,title,tags,page,esc,modal,infoButton,brandLogo} from '../presentation/reference-primitives';
import {savedRunInfo} from '../presentation/map-preview';

export type MenuPage='title'|'race'|'difficulty'|'confirm'|'load'|'load-preview';
export interface MenuSelection {page:MenuPage;race:Race;difficulty:Difficulty;preset:PresetSlot;hero:HeroId|null;loadPreview:LoadPreview|null;error:string;coverIndex?:number;coverLockedRace?:Race|null;previewImage?:string|null}
export const RACE_VISUALS:Record<Race,{english:string;unit:'marine'|'zergling'|'zealot';traits:string[];bodies:number;minerals:number;building:string;rgb:string;accent:string;title:string}>={
 terran:{english:'Terran',unit:'marine',traits:['远程','机械','阵地'],bodies:1,minerals:50,building:'兵营',rgb:'78,139,176',accent:'#78c9ef',title:'钢铁，火力，坚守。'},
 zerg:{english:'Zerg',unit:'zergling',traits:['虫群','恢复','进化'],bodies:2,minerals:50,building:'孵化场 / 血池',rgb:'130,76,157',accent:'#b899db',title:'进化不止，虫群不息。'},
 protoss:{english:'Protoss',unit:'zealot',traits:['护盾','精锐','灵能'],bodies:1,minerals:0,building:'传送门',rgb:'169,139,74',accent:'#e5cb86',title:'以灵能之刃，重铸荣耀。'}
};
export const DIFFICULTY_COPY:Record<Difficulty,{name:string;short:string;reward:string}>={easy:{name:'简单',short:'威胁 ×0.5',reward:'+1 / 3 关'},normal:{name:'普通',short:'威胁 ×0.9',reward:'+1 / 3 关'},hard:{name:'困难',short:'强化攻势',reward:'+2 / 3 关'},hell:{name:'地狱',short:'扩张巢 · 第 4 关',reward:'+1 / 关'}};
const cover=(race:Race,index=0)=>`<img class="painted-cover" src="${assetUrl('ui.cover.'+COVER_HEROES[race][index])??''}" alt="" draggable="false">`;
const steps=(step:number)=>`<nav class="step-nav" aria-label="新游戏步骤">${(['race','difficulty','confirm'] as const).map((id,i)=>`<button data-action="menu-stage" data-page="${id}" class="${i+1===step?'active':''} ${i+1<step?'done':''}" ${i+1>step?'disabled':''}><span>${i+1<step?glyph('check'):i+1}</span>${['种族','难度','出发'][i]}</button>`).join('')}</nav>`;
const footer=()=>`<footer class="game-footer"><span>非官方同人 · StarCraft II 素材属于 Blizzard Entertainment</span><div>${iconButton('gear','打开设置','settings')}<span>本地战局</span></div></footer>`;
const error=(text:string)=>text?`<p class="menu-error" role="alert">${esc(text)}</p>`:'';
const counts=(levels:Record<string,number|undefined>)=>Object.values(levels).reduce<number>((n,v)=>n+(v??0),0);

export function renderMenu(s:MenuSelection,profile:PermanentProfile,session:RunSession|null){
 const r=RACE_VISUALS[s.race],name=RACE_NAMES[s.race],index=s.coverIndex??0;
 if(s.page==='title'){
  const hero=COVER_HEROES[s.race][index] as HeroId;
  return page(`<div class="cover-backdrop" aria-hidden="true"><img class="cover-layer is-active" data-cover-id="${hero}" src="${assetUrl('ui.cover.'+hero)??''}" alt="" draggable="false"><img class="cover-layer" alt="" draggable="false"><div class="cover-shade"></div><div class="cover-atmosphere"></div></div>${masthead('通讯在线',false)}<section class="home-page"><div class="home-copy"><div class="title-emblem">${glyph('shield')}<span>${r.english}</span></div><div class="wordmark">${brandLogo("home-brand-logo")}</div><div class="title-rule"><i></i><span>战役 · 18 关</span><i></i></div><nav class="main-actions" aria-label="主菜单">${button('新游戏','menu-new','primary main-action','data-autofocus')}${button('读取存档','menu-load','main-action')}${button('天赋','talents','main-action')}</nav>${error(s.error)}</div><div class="cover-factions" role="group" aria-label="阵营封面">${RACES.map(id=>`<button data-action="cover-race" data-race="${id}" aria-pressed="${id===s.coverLockedRace}" data-current="${id===s.race}" aria-label="${RACE_NAMES[id]}封面">${image('unit.'+RACE_VISUALS[id].unit)}<span>${RACE_NAMES[id]}</span></button>`).join('')}</div></section>${footer()}`,'formal-home');
 }
 if(s.page==='race')return page(`${masthead('新游戏')}${title('选择阵营','menu-back',steps(1))}<section class="race-grid" role="radiogroup" aria-label="选择种族">${RACES.map(id=>{const v=RACE_VISUALS[id];return `<button class="race-card ${id===s.race?'selected':''}" style="--card-accent:${v.accent};--portrait-rgb:${v.rgb}" data-action="menu-race" data-race="${id}" role="radio" aria-checked="${id===s.race}"><div class="race-card-art">${cover(id)}</div><div class="race-card-copy"><div class="race-card-title"><h2>${RACE_NAMES[id]}</h2><span>${v.english}</span><i>${glyph('check')}</i></div>${tags(v.traits)}<div class="race-start">${image('unit.'+v.unit)}<span>×${v.bodies}</span><span class="starter-building">${v.building}</span></div><div class="race-resource">${money(v.minerals,0)}</div></div></button>`;}).join('')}</section><div class="screen-bottom"><span>${name} · 待命</span>${button('继续 '+glyph('next'),'menu-race-next','primary')}</div>`,'m3-menu');
 if(s.page==='difficulty')return page(`${masthead('新游戏')}${title('选择难度','menu-back',steps(2))}<section class="difficulty-layout"><aside class="deployment-aside">${cover(s.race,index)}<div class="difficulty-faction"><span class="line-caption">${r.english}</span><h2>${name}</h2>${tags(['战役 18 关','无尽'])}</div></aside><div class="difficulty-options" role="radiogroup" aria-label="选择难度">${(Object.keys(DIFFICULTY_COPY) as Difficulty[]).map((id,i)=>{const d=DIFFICULTY_COPY[id];return `<button class="difficulty-card ${id===s.difficulty?'selected':''} ${id==='hell'?'hell':''}" data-action="menu-difficulty" data-difficulty="${id}" role="radio" aria-checked="${id===s.difficulty}"><span class="difficulty-insignia">${image(['unit.zergling','unit.roach','unit.ultralisk','hero.kerrigan'][i])}<b>${['I','II','III','IV'][i]}</b></span><div class="difficulty-copy"><div class="difficulty-card-heading"><h2>${d.name}</h2>${id==='normal'?'<small>标准</small>':''}</div><span>${d.short}</span></div><div class="difficulty-reward"><small>永久资源</small><span>${glyph('hex')}<b>${d.reward}</b></span></div><span class="radio-mark" aria-hidden="true"></span></button>`;}).join('')}</div></section><div class="screen-bottom difficulty-footer">${infoButton('难度','难度在本局内保持不变。完成关卡获得本族永久资源。','规则')}${button('继续 '+glyph('next'),'menu-difficulty-next','primary')}</div>`,'m3-menu');
 if(s.page==='confirm'){
  const preset=profile.getPreset(s.race,s.preset)!,allocation=profile.previewTalentAllocation(s.race,s.preset),points=counts(preset.levels),unlocked=talentRank(preset.levels,s.race,'hero_support')>0;
  const hero=unlocked?(s.hero&&HERO_IDS_BY_RACE[s.race].includes(s.hero as never)?s.hero:HERO_IDS_BY_RACE[s.race][0]):null;
  return page(`${masthead('新游戏')}${title('作战部署','menu-back',steps(3))}<section class="confirm-layout"><article class="deployment-art panel">${cover(s.race,index)}<div class="deployment-art-label"><small>${r.english}</small><h2>${name}</h2><span>${DIFFICULTY_COPY[s.difficulty].name} · 18 关</span></div></article><div class="deployment-config"><section class="panel config-panel"><h2>天赋预设</h2><div class="preset-tabs" role="group" aria-label="天赋预设">${([0,1,2] as PresetSlot[]).map(slot=>`<button data-action="menu-preset-select" data-slot="${slot}" aria-pressed="${slot===s.preset}">${esc(profile.getPreset(s.race,slot)!.name)}</button>`).join('')}</div><div class="allocation-readout"><b>${points}<span>/ 80</span></b><div>战术投入<small>${allocation?`${allocation.cost} 资源 · 余额 ${profile.raceBalance(s.race)}`:'资源不足'}</small></div>${button('编辑','menu-edit-talents','small')}</div></section><section class="panel config-panel"><h2>初始部队</h2><div class="starting-roster starter-unit-roster"><div class="starting-art">${paintedArt(r.unit,SC2_UNITS[r.unit].zh,r.bodies,'deployment-'+s.race)}</div><div><b>${SC2_UNITS[r.unit].zh+' ×'+r.bodies}</b><p>${r.building}</p></div></div>${hero?`<div class="starting-roster starter-hero-roster"><div class="starting-art">${paintedArt(hero,HEROES[hero].name,1,'deployment-hero-'+hero)}</div><div><b>${HEROES[hero].name} Ⅱ</b></div></div>`:''}${hero?`<label class="starter-hero-select">开局英雄<select data-setting="menu-hero" aria-label="开局英雄">${HERO_IDS_BY_RACE[s.race].map(id=>`<option value="${id}" ${id===hero?'selected':''}>${HEROES[id].name}</option>`).join('')}</select></label>`:''}<div class="starting-resource">${money(r.minerals,0)}</div></section>${session?.canResume?`<div class="departure-notice">${glyph('save')}<span>替换续局槽</span><button data-action="save-export">导出</button>${infoButton('续局槽','开始新游戏将替换续局槽。可先导出当前存档。')}</div>`:''}${error(s.error)}</div></section><div class="screen-bottom"><span>${allocation?'部署就绪':'请调整天赋'}</span>${button('出发 '+glyph('arrow'),'menu-start','primary launch',`data-autofocus ${allocation?'':'disabled'}`)}</div>`,'m3-menu m3-deployment');
 }
 const w=session?.world,p=s.loadPreview?.snapshot??session?.savedSnapshot,info=savedRunInfo(p),resume=session?.canResume,saveRace=info?.race??s.race,vr=RACE_VISUALS[saveRace],stage=info?.stage??1;
 const wallet=info?.wallet??{minerals:0,gas:0},summary=session?.summary??'',when=session?.savedAt?new Date(session.savedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
 const card=`<article class="save-card panel"><div class="save-scene" ${s.previewImage?`style="background-image:url('${s.previewImage}')"`:''}><span class="save-tag">续局</span><span class="saved-stage">${String(stage).padStart(2,'0')} <small>/ 18</small></span></div><div class="save-copy"><div>${image('unit.'+vr.unit)}<div><h2>${esc(summary.split(' · ')[0]||RACE_NAMES[saveRace])}</h2><p>${esc(info?.mapName??'战役前线')}</p></div></div><dl><dt>部队</dt><dd>${info?.bodies??0}</dd><dt>天赋</dt><dd>${info?.points??0} / 80</dd><dt>保存</dt><dd>${when}</dd></dl><div class="save-wallet">${money(wallet.minerals,wallet.gas)}</div>${button('载入 '+glyph('next'),'menu-load-local','primary',resume?'':'disabled')}</div></article>`;
 const base=page(`${masthead('战局档案')}${title('读取存档')}<section class="saves-layout">${resume||s.page==='load-preview'?card:`<article class="save-card panel empty-save"><div class="save-scene">${glyph('save')}</div><div class="save-copy"><h2>暂无续局</h2><p>从新的前线开始。</p>${button('新游戏','menu-new','primary')}</div></article>`}<aside class="save-side"><div class="panel"><h2>导入战局</h2>${button(glyph('download')+' 选择文件','menu-load-file','small')}</div><div class="save-note">${glyph('pause')}<div><b>暂停中</b></div>${infoButton('恢复战局','从暂停的战场恢复，保留部队伤损、冷却与训练进度。准备好后继续。')}</div>${error(s.error)}</aside></section>`,'m3-menu');
 if(s.page!=='load-preview')return base;
 const candidate=savedRunInfo(s.loadPreview?.snapshot),description=s.loadPreview?.summary??'请选择可读取的存档',stateName=({battle:'暂停',reward:'基地整备',won:'撤离选择','endless-ready':'无尽整备',lost:'作战结束',finished:'撤离完成',menu:'标题'})[candidate?.phase??'menu'];
 return base+modal('检查存档','',`<div class="load-preview-summary"><h2>${esc(description)}</h2><p>${s.loadPreview?.source==='import'?'导入战局':when}</p><div>${money(candidate?.wallet.minerals??0,candidate?.wallet.gas??0)}</div><dl><dt>本局天赋</dt><dd>${candidate?.points??0} / 80</dd><dt>作战部队</dt><dd>${candidate?.bodies??0} 名战士</dd><dt>恢复状态</dt><dd>${stateName}</dd></dl></div>`,'load-modal',button('返回','menu-back','secondary')+button('载入这份存档','menu-load-ready','primary',s.loadPreview?'':'disabled'),'menu-back');
}

export function renderReadiness(state:ReadinessState,context:{race?:Race;difficulty?:Difficulty;map?:string}={}){
 const ready=state.phase==='ready',failed=state.phase==='error',ratio=state.total>0?Math.max(0,Math.min(1,state.done/state.total)):0,read=['read','idle'].includes(state.phase),late=['audio','gpu','validate','ready'].includes(state.phase),race=context.race??'terran';
 return page(`${masthead('战场装载')}<section class="loading-page" data-ready="${ready}"><div class="loading-portrait" aria-hidden="true">${cover(race)}</div><div class="loading-emblem">${glyph('target')}<div class="loading-ring"></div></div><h1>${ready?'部署就绪':failed?'暂时无法出发':'部署中'}</h1><p>${RACE_NAMES[race]} · ${DIFFICULTY_COPY[context.difficulty??'normal'].name} · ${esc(context.map??'战役前线')}</p><div class="loading-progress" role="progressbar" aria-label="战场装载" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.round(ratio*100)}"><div class="progress-track"><i style="width:${Math.round(ratio*100)}%"></i></div><strong>${ready?100:Math.round(ratio*100)}%</strong></div><div class="load-stages"><span class="${!read?'done':''}">${glyph(!read?'check':'hex')}战局</span><span class="${late?'done':''}">${glyph(late?'check':'hex')}部队</span><span class="${ready?'done':''}">${glyph(ready?'check':'target')}战场</span></div>${failed?`<p class="loading-error">部分资源未能就绪，请重试。</p><details><summary>查看原因</summary><p>${esc(state.error??'')}</p></details>`:ready&&state.label.includes('缓存空间不足')?'<p>本次资源未能全部缓存，下次进入时将补下载。</p>':''}<div class="loading-actions">${ready?'':button('返回','flow-cancel','small')}${failed?button('重试','flow-retry','primary')+button('导出存档','save-export','small'):button('进入战场','flow-continue','primary',ready?'data-autofocus':'disabled')}</div></section>`,'m3-menu m3-loading');
}
