import {text,attr,style,reconcile} from '../native-hud/dom';
import type {World} from '../../simulation/world';
import {HEROES} from '../../data/heroes';
import type {HudSettings} from './preferences';
import {familyAction,packedSeats} from './packed-roster';
import {COMMAND_ACTIONS,battleActionState,activateBattleAction,type BattleActionId} from '../controls/battle-actions';
import {renderUnitInspector,type InspectorTab,type UnitSeat} from '../presentation/unit-inspector';
import {updateLiveInspector} from '../presentation/live-inspector';
import {battleInputCapture,trapTab} from '../presentation/input-capture';
import {image,glyph,esc} from '../presentation/reference-primitives';
import {hudGlyph} from './glyphs';
import {rankLabel} from '../unit-identity';
import {activeSkin,commandArt} from '../native-hud/skins';
import {armyFrame,commandFrame,controlFrame,type HudMode} from '../native-hud/frames';
import {selectionFrame,updateSelection} from '../native-hud/selection';
import {assetUrl} from '../../assets/manifest';
import '../native-hud/battle.css';
const globals:BattleActionId[]=['dash','detection','airlift','tactical','strategic'];
const number=(n:number)=>n>=1000?Number((n/1000).toFixed(1))+'k':String(Math.ceil(n));
const arrow=(up:boolean)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="${up?'M5 15l7-7 7 7':'M5 9l7 7 7-7'}"/></svg>`;
export class SquadConsole {
 readonly root:HTMLElement;private grid:HTMLElement;private detail:HTMLElement;private pager:HTMLElement;private commands:HTMLElement;
 private commandIds:BattleActionId[]=[];private selected='';private page=0;private structure='';private commandStructure='';private detailHTML='';private run='';private rows:UnitSeat[]=[];private detailOpen=false;private tab:InspectorTab='stats';private expanded=new Set<string>();private columns=6;private pageSize=12;private blocked=false;private visible=false;private pageAnchor=0;private commandPage=0;private pageHTML='';private foldHTML='';private skinKey='';private selectionKey='';
 private suppressUntil=0;private ignorePressClick=false;private press:{id:number;key:string;x:number;y:number;timer:number}|null=null;private swipe:{id:number;x:number;y:number}|null=null;
 blocksTap(b:HTMLButtonElement){return !!(b.dataset.seat||b.dataset.command)&&performance.now()<this.suppressUntil;}
 get isOpen(){return this.detailOpen&&!this.root.hidden;}
 get mobile(){return matchMedia('(pointer:coarse)').matches||matchMedia('(max-width:700px)').matches||matchMedia('(max-width:1100px) and (max-height:600px)').matches;}
 get landscape(){return this.mobile&&innerWidth>innerHeight;}
 get mode():HudMode{return !this.mobile?'pc':this.landscape?'landscape':'portrait';}
 constructor(private world:World,parent:HTMLElement,private preferences:HudSettings,private onUse=()=>{}){
  this.root=document.createElement('section');this.root.id='battle-console';this.root.className='battle-console packed-console';this.root.setAttribute('aria-label','作战控制台');
  this.root.innerHTML=`<div class="console-body"><div class="command-row"><div class="native-command-frame"></div><section id="console-commands" aria-label="英雄技能与全局指令"></section><nav id="native-command-pages" aria-label="技能分页"></nav></div><div class="army-row"><div class="native-army-frame"></div><button id="army-toggle" class="console-fold" aria-controls="army-hud"></button><section id="army-hud"><div id="roster" role="group" aria-label="全队单位"></div></section><nav id="army-pages" aria-label="部队分页"></nav></div></div><section id="native-selection" hidden aria-label="所选士兵生命"></section><div id="unit-inspector" data-captures-battle-input hidden></div><div id="production-detail" hidden></div>`;
  parent.append(this.root);this.grid=this.root.querySelector('#roster')!;this.detail=this.root.querySelector('#unit-inspector')!;this.pager=this.root.querySelector('#army-pages')!;this.commands=this.root.querySelector('#console-commands')!;
  this.root.addEventListener('pointerdown',()=>{this.ignorePressClick=false;},true);
  this.root.addEventListener('click',e=>{if(this.ignorePressClick){this.ignorePressClick=false;e.preventDefault();e.stopImmediatePropagation();}},true);
  const inspectKey=(e:Event)=>(e.target as HTMLElement).closest<HTMLElement>('[data-seat],[data-hero-seat]');
  this.root.addEventListener('pointerdown',e=>{e.stopPropagation();const b=inspectKey(e);if(e.pointerType==='mouse'||e.button!==0||!b)return;const key=b.dataset.seat??b.dataset.heroSeat!;this.clearPress();if(b.dataset.seat&&this.mobile)this.swipe={id:e.pointerId,x:e.clientX,y:e.clientY};this.press={id:e.pointerId,key,x:e.clientX,y:e.clientY,timer:window.setTimeout(()=>{this.ignorePressClick=true;this.suppressUntil=performance.now()+900;this.open(key);this.clearPress();},480)};});
  this.root.addEventListener('pointermove',e=>{if(this.press?.id===e.pointerId&&Math.hypot(e.clientX-this.press.x,e.clientY-this.press.y)>10)this.clearPress();});
  for(const type of ['pointerup','pointercancel','lostpointercapture'])this.root.addEventListener(type,e=>{const p=e as PointerEvent;if(type==='pointerup'&&this.swipe?.id===p.pointerId){const dx=p.clientX-this.swipe.x,dy=p.clientY-this.swipe.y;const primary=this.mode==='portrait'?dy:dx,secondary=this.mode==='portrait'?dx:dy;if(Math.abs(primary)>36&&Math.abs(primary)>Math.abs(secondary)*1.2){this.suppressUntil=performance.now()+500;requestAnimationFrame(()=>this.turnPage(primary<0?1:-1));}}this.swipe=null;this.clearPress();});
  this.root.addEventListener('contextmenu',e=>{const b=inspectKey(e);if(!b)return;e.preventDefault();this.suppressUntil=performance.now()+300;this.open(b.dataset.seat??b.dataset.heroSeat!);});
  this.root.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('button');if(!b||b.disabled)return;
   if(b.dataset.seat||b.dataset.command){if(performance.now()<this.suppressUntil){e.preventDefault();return;}if(this.blocked||battleInputCapture())return;if(b.dataset.seat){this.selected=b.dataset.seat;this.update();}else{this.onUse();activateBattleAction(world,b.dataset.command as BattleActionId);this.update();}return;}
   if(b.id==='army-toggle'){preferences.toggle('armyCollapsed');this.update();return;}if(b.dataset.commandPage){this.commandPage=Math.max(0,this.commandPage+Number(b.dataset.commandPage));this.update();return;}if(b.hasAttribute('data-selection-close')){this.selected='';this.update();return;}if(b.hasAttribute('data-selection-detail')){this.open(this.selected);return;}if(b.dataset.page){this.turnPage(Number(b.dataset.page));return;}
   if(b.dataset.inspectClose!==undefined)this.close();if(b.dataset.inspectTab)this.setTab(b.dataset.inspectTab as InspectorTab);if(b.dataset.inspectSeat)this.select(b.dataset.inspectSeat);if(b.dataset.inspectNeighbor){const at=this.rows.findIndex(s=>s.key===this.selected);this.select(this.rows[Math.max(0,Math.min(this.rows.length-1,at+Number(b.dataset.inspectNeighbor)))]?.key);}
  });
  this.detail.addEventListener('toggle',e=>{const d=e.target as HTMLDetailsElement;if(d.dataset.ability){if(d.open)this.expanded.add(d.dataset.ability);else this.expanded.delete(d.dataset.ability);}},true);
  this.root.addEventListener('keydown',e=>{const b=inspectKey(e);if(b&&(e.key==='ContextMenu'||e.shiftKey&&e.key==='F10')){e.preventDefault();this.open(b.dataset.seat??b.dataset.heroSeat!);}if(this.detailOpen){e.stopPropagation();if(e.key==='Escape'){e.preventDefault();this.close();return;}if((e.target as HTMLElement).dataset.inspectTab&&['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const tabs=[...this.detail.querySelectorAll<HTMLButtonElement>('[data-inspect-tab]')],at=tabs.indexOf(e.target as HTMLButtonElement),i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(at+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length,key=tabs[i].dataset.inspectTab as InspectorTab;this.setTab(key);this.detail.querySelector<HTMLButtonElement>(`[data-inspect-tab="${key}"]`)?.focus();}trapTab(e,this.detail);}});
  this.grid.addEventListener('keydown',e=>{const delta=({ArrowLeft:-1,ArrowRight:1,ArrowUp:-this.columns,ArrowDown:this.columns} as Record<string,number>)[e.key];if(!delta)return;e.preventDefault();e.stopPropagation();const b=[...this.grid.querySelectorAll<HTMLButtonElement>('button')],at=b.indexOf(document.activeElement as HTMLButtonElement);b[Math.max(0,Math.min(b.length-1,at+delta))]?.focus();});
  document.addEventListener('sc2-inspection-open',e=>{if((e as CustomEvent).detail==='carrier')this.close();});
  document.addEventListener('sc2-hud-skill-focus',e=>{const at=this.commandIds.indexOf((e as CustomEvent).detail);if(at<0)return;const page=Math.floor(at/(this.mode==='portrait'?9:15));if(page!==this.commandPage){this.commandPage=page;this.update();}});
  new ResizeObserver(()=>this.update()).observe(parent);
 }
 private clearPress(){if(this.press)clearTimeout(this.press.timer);this.press=null;}
 private turnPage(delta:number){this.page=Math.max(0,Math.min(Math.ceil(this.rows.length/this.pageSize)-1,this.page+delta));this.pageAnchor=this.page*this.pageSize;this.update();}
 update(visible=this.visible,blocked=this.blocked){
  const w=this.world;this.visible=visible;this.blocked=blocked;this.root.hidden=!visible;this.root.dataset.race=w.expedition.race;this.root.classList.toggle('touch-console',this.mobile);document.body.classList.toggle('has-battle-console',visible);this.root.parentElement!.classList.toggle('packed-mobile',this.mobile);if(!visible){this.clearPress();return;}
  if(this.run!==w.runId){this.run=w.runId??'';this.page=0;this.pageAnchor=0;this.commandPage=0;this.selected='';this.detailOpen=false;this.tab='stats';this.expanded.clear();}
  const mode=this.mode,skin=activeSkin(w.permanentProfile,w.expedition.race),skinKey=mode+'/'+skin.id;this.root.parentElement!.dataset.hudMode=mode;
  if(skinKey!==this.skinKey){this.skinKey=skinKey;this.root.querySelector('.native-army-frame')!.innerHTML=armyFrame(skin,mode);this.root.querySelector('.native-command-frame')!.innerHTML=commandFrame(skin,mode);this.foldHTML='';}
  this.rows=packedSeats(w);const content=this.root.querySelector<HTMLElement>('#army-hud')!,width=content.clientWidth,height=content.clientHeight,gap=mode==='portrait'?innerWidth*.0075:innerWidth*.0024;
  this.columns=mode==='portrait'?1:mode==='pc'?10:Math.max(1,Math.ceil((width+gap)/(Math.max(20,Math.min(30,(height-gap)/2))+gap)));
  const rows=mode==='portrait'?Math.max(1,Math.floor((height+gap)/(width+gap))):2;this.pageSize=this.columns*rows;
  const pages=Math.max(1,Math.ceil(this.rows.length/this.pageSize));this.page=Math.max(0,Math.min(pages-1,Math.floor(this.pageAnchor/this.pageSize)));const shown=this.rows.slice(this.page*this.pageSize,(this.page+1)*this.pageSize),folded=this.preferences.armyCollapsed;
  this.root.classList.toggle('army-collapsed',folded);const fold=this.root.querySelector<HTMLButtonElement>('#army-toggle')!;fold.hidden=false;const foldHTML=controlFrame(skin,mode==='portrait')+arrow(folded);if(this.foldHTML!==foldHTML){this.foldHTML=foldHTML;fold.innerHTML=foldHTML;}attr(fold,'aria-expanded',String(!folded));attr(fold,'aria-label',folded?'展开部队':'收起部队');content.inert=folded;this.pager.inert=folded;
  style(this.grid,'--roster-columns',String(this.columns));style(this.grid,'--roster-rows',String(rows));
  const structure=shown.map(s=>s.key+'/'+s.image+'/'+s.bodies.map(u=>u.id).join(',')).join('|');if(structure!==this.structure){this.structure=structure;const active=(document.activeElement as HTMLElement)?.dataset.seat;reconcile(this.grid,shown.map(s=>s.key+'/'+s.image),key=>{const s=shown.find(s=>s.key+'/'+s.image===key)!;const holder=document.createElement('div');holder.innerHTML=`<button class="packed-seat ${s.hero?'hero-seat':''}" data-seat="${s.key}">${image(s.unit&&assetUrl('wireframe.'+s.unit.unitType)?'wireframe.'+s.unit.unitType:s.image,s.name)}<span class="seat-name">${esc(s.name)}</span><span class="seat-rank"></span><span class="seat-vitals"></span><span class="seat-health"><i></i></span><span class="seat-shield"><i></i></span><span class="seat-timer"></span></button>`;return holder.firstElementChild as HTMLElement;});if(active)this.grid.querySelector<HTMLButtonElement>(`[data-seat="${active}"]`)?.focus({preventScroll:true});}
  for(const s of shown){const b=this.grid.querySelector<HTMLElement>(`[data-seat="${s.key}"]`)!,u=s.unit,action=s.family?familyAction(w,s.family):undefined,state=action?battleActionState(w,action):undefined,hp=s.bodies.reduce((n,u)=>n+u.hp,0),max=s.bodies.reduce((n,u)=>n+u.maxHp,0),shield=s.bodies.reduce((n,u)=>n+(u.shield??0),0),maxShield=s.bodies.reduce((n,u)=>n+(u.maxShield??0),0);b.classList.toggle('is-selected',s.key===this.selected);attr(b,'aria-pressed',String(s.key===this.selected));b.classList.toggle('skill-ready',!!state?.enabled);text(b.querySelector('.seat-rank')!,u?rankLabel(u.rank):'');text(b.querySelector('.seat-vitals')!,u?number(hp)+'/'+number(max):'阵亡');attr(b,'aria-label',s.name+(u?' · 军衔 '+rankLabel(u.rank)+' · 生命 '+Math.ceil(hp)+' / '+Math.ceil(max):' · 阵亡')+' · 点击选中');attr(b,'title',b.getAttribute('aria-label')!+' · 右键或长按详情');style(b.querySelector('.seat-health i') as HTMLElement,'width',(max?hp/max*100:0)+'%');const sh=b.querySelector<HTMLElement>('.seat-shield')!;sh.hidden=!maxShield;style(sh.firstElementChild as HTMLElement,'width',(maxShield?shield/maxShield*100:0)+'%');text(b.querySelector('.seat-timer')!,s.regrowAt?Math.max(0,Math.ceil((s.regrowAt-w.tick)/60))+'s':'');}
  this.pager.hidden=pages===1;attr(this.pager,'aria-label',`部队第 ${this.page+1} 页，共 ${pages} 页`);const pageHTML=`<button data-page="-1" aria-label="上一页部队" ${this.page===0?'disabled':''}>${glyph('back')}</button><span>${this.page+1} / ${pages}</span><button data-page="1" aria-label="下一页部队" ${this.page===pages-1?'disabled':''}>${glyph('next')}</button>`;if(this.pageHTML!==pageHTML){this.pageHTML=pageHTML;this.pager.innerHTML=pageHTML;}

  const heroes=[...w.heroes.keys()].slice(0,3),commands=[...heroes.map((hero,i)=>({id:`hero-slot-${i}` as BattleActionId,hero,index:i})),...[...new Set([...globals,...this.rows.flatMap(s=>{const a=s.family?familyAction(w,s.family):undefined;return a?[a]:[];})])].map(id=>({id,hero:undefined,index:-1}))].filter(c=>battleActionState(w,c.id).visible);this.commandIds=commands.map(c=>c.id);const commandCapacity=mode==='portrait'?9:15,commandPages=Math.max(1,Math.ceil(commands.length/commandCapacity));this.commandPage=Math.min(this.commandPage,commandPages-1);const visibleCommands=commands.slice(this.commandPage*commandCapacity,(this.commandPage+1)*commandCapacity),commandKey=w.expedition.race+'/'+mode+'/'+visibleCommands.map(c=>c.id+'/'+c.hero).join('|');
  if(commandKey!==this.commandStructure){this.commandStructure=commandKey;reconcile(this.commands,[...visibleCommands.map(c=>w.expedition.race+'/'+c.id+'/'+c.hero),...Array.from({length:commandCapacity-visibleCommands.length},(_,i)=>'empty:'+i)],key=>{if(key.startsWith('empty:')){const empty=document.createElement('span');empty.className='native-empty-command';empty.setAttribute('aria-hidden','true');return empty;}const c=visibleCommands.find(c=>w.expedition.race+'/'+c.id+'/'+c.hero===key)!;const meta=COMMAND_ACTIONS.find(a=>a.id===c.id),name=c.hero?HEROES[c.hero].name:'',native=commandArt(c.id,w.expedition.race),art=c.hero?image('hero.'+c.hero,name):native?`<img src="${native}" alt="" draggable="false">`:meta&&'icon'in meta?image(meta.icon):hudGlyph(meta&&'glyph'in meta?meta.glyph:'scan');const holder=document.createElement('div');holder.innerHTML=`<button class="packed-command ${c.hero?'hero-skill':''}" id="${c.id}" data-command="${c.id}" data-battle-action="${c.id}" ${c.hero?`data-hero-seat="hero:${c.index}"`:''}>${art}<span class="command-copy"><b>${esc(name)}</b><small></small></span><span class="command-cooldown"></span><kbd>${c.hero?c.index+1:meta?.key??''}</kbd></button>`;return holder.firstElementChild as HTMLElement;});}
  for(const c of visibleCommands){const b=this.commands.querySelector<HTMLButtonElement>(`[data-command="${c.id}"]`)!,s=battleActionState(w,c.id);b.disabled=!c.hero&&(!s.enabled||blocked);attr(b,'aria-disabled',String(!s.enabled||blocked));b.classList.toggle('skill-ready',s.enabled&&!blocked);b.classList.toggle('cooling',s.remaining>0);text(b.querySelector('b')!,c.hero?HEROES[c.hero].name:this.mobile&&c.id==='dash'?'加速':this.mobile&&c.id==='detection'?'探测':s.name);text(b.querySelector('small')!,c.hero?HEROES[c.hero].skill:'');text(b.querySelector('.command-cooldown')!,s.count!==undefined?String(s.count):s.remaining>0?String(Math.ceil(s.remaining)):'');attr(b,'title',s.name+(s.reason?' · '+s.reason:''));attr(b,'aria-label',b.title);}
  const commandPager=this.root.querySelector<HTMLElement>('#native-command-pages')!;commandPager.hidden=commandPages===1;const commandsHTML=`<button data-command-page="-1" aria-label="上一页技能" ${this.commandPage===0?'disabled':''}>‹</button><span>${this.commandPage+1} / ${commandPages}</span><button data-command-page="1" aria-label="下一页技能" ${this.commandPage===commandPages-1?'disabled':''}>›</button>`;if(commandPager.dataset.html!==commandsHTML){commandPager.dataset.html=commandsHTML;commandPager.innerHTML=commandsHTML;}
  const selected=this.rows.find(s=>s.key===this.selected),selection=this.root.querySelector<HTMLElement>('#native-selection')!;selection.hidden=!selected;if(selected){const key=selected.key+'/'+selected.image+'/'+!!selected.unit?.maxShield+'/'+!!selected.unit?.maxEnergy+'/'+skin.race;if(key!==this.selectionKey){this.selectionKey=key;selection.innerHTML=selectionFrame(selected,skin.race);}updateSelection(selection,selected);}

  this.root.parentElement!.style.setProperty('--packed-army-height',this.root.querySelector<HTMLElement>('.army-row')!.offsetHeight+'px');
  this.detail.hidden=!this.detailOpen;const seat=this.rows.find(s=>s.key===this.selected);if(this.detailOpen&&!seat){this.detailOpen=false;this.detail.hidden=true;}const html=this.detailOpen&&seat?renderUnitInspector(w,seat,this.rows,this.tab,this.expanded):'';if(html!==this.detailHTML){this.detailHTML=html;updateLiveInspector(this.detail,html);}
 }
 selectEntity(id:number){const seat=packedSeats(this.world).find(s=>s.bodies.some(u=>u.id===id));if(!seat)return false;this.selected=seat.key;this.update();return true;}
 private open(key:string){if(!this.rows.some(s=>s.key===key))return;this.selected=key;this.detailOpen=true;this.tab='stats';this.expanded.clear();document.dispatchEvent(new CustomEvent('sc2-inspection-open',{detail:'unit'}));this.update();this.detail.querySelector<HTMLButtonElement>('[data-inspect-close]')?.focus({preventScroll:true});}
 close(){if(!this.detailOpen)return false;this.detailOpen=false;this.update();this.grid.querySelector<HTMLButtonElement>(`[data-seat="${this.selected}"]`)?.focus({preventScroll:true});return true;}
 private setTab(tab:InspectorTab){this.tab=tab;this.expanded.clear();if(tab==='abilities'){const s=this.rows.find(s=>s.key===this.selected);this.expanded.add(s?.hero?'active':s?.unit?.eliteId?'elite':'native');}this.update();}
 private select(key?:string){if(!key)return;this.selected=key;this.setTab(this.tab==='army'?'stats':this.tab);}
}
