import type {World} from '../../simulation/world';import type {TelemetryClient} from '../../services/telemetry-client';import type {GameObserver} from '../../services/game-observer';import {CONSENT_VERSION} from '../../../tools/backend/contracts.mjs';
import './player-services.css';
const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
type Receipt={id:string;receipt:string;at:number};type FeedbackDraft={category:string;text:string;contact:string;summary:boolean;pending?:Record<string,unknown>};
const categories={problem:'问题',performance:'性能',balance:'平衡',suggestion:'建议',other:'其他'};
export class PlayerServices {
 readonly dialog=document.createElement('dialog');private footer=document.createElement('div');private previousFocus:HTMLElement|null=null;private wasPaused=true;private mode='privacy';private receipts:Receipt[]=[];private draft:FeedbackDraft={category:'problem',text:'',contact:'',summary:true};
 constructor(readonly world:World,readonly client:TelemetryClient,readonly observer:GameObserver,readonly resetInput:()=>void,readonly updateHud:()=>void,readonly currentSummary:()=>Record<string,unknown>,private storage?:Storage){
  this.dialog.className='player-services-dialog';this.dialog.setAttribute('aria-label','玩家数据与反馈');document.body.append(this.dialog);this.footer.className='player-services-links';this.footer.innerHTML='<button type="button" data-player-service="feedback">反馈</button><span>·</span><button type="button" data-player-service="privacy">玩家数据与隐私</button>';
  this.footer.addEventListener('click',e=>{const b=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-player-service]');if(b)this.open(b.dataset.playerService!);});this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});
  document.addEventListener('keydown',e=>{if(!this.blocking)return;if(e.key==='Escape'){e.preventDefault();this.close();}e.stopImmediatePropagation();},true);document.addEventListener('keyup',e=>{if(this.blocking)e.stopImmediatePropagation();},true);
  this.dialog.addEventListener('click',e=>{const action=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-service-action]')?.dataset.serviceAction;if(action==='close')this.close();else if(action==='privacy'||action==='feedback'){this.mode=action;this.render();}else if(action==='allow')void this.consent(true);else if(action==='withdraw')void this.consent(false);else if(action==='delete')void this.removeData();else if(action==='retry-privacy')void this.retryPrivacy();else if(action==='view-feedback'||action==='delete-feedback')void this.receipt((e.target as HTMLElement).closest<HTMLElement>('[data-id]')!.dataset.id!,action==='delete-feedback');else if(action==='new-feedback'){this.draft={category:'problem',text:'',contact:'',summary:true};this.saveDraft();this.render();}});
  this.dialog.addEventListener('input',()=>this.captureDraft());this.dialog.addEventListener('change',()=>this.captureDraft());this.dialog.addEventListener('submit',e=>{e.preventDefault();void this.submit();});
  try{const list=JSON.parse(storage?.getItem('sc2.feedback.receipts')??'[]');this.receipts=Array.isArray(list)?list.filter(r=>r&&typeof r.id==='string'&&typeof r.receipt==='string').slice(-10):[];const d=JSON.parse(sessionStorage.getItem('sc2.feedback.draft')??'null');if(d&&typeof d.text==='string'&&d.text.length<=2000)this.draft=d;}catch{}
 }
 get blocking(){return this.dialog.open;}
 mount(root:HTMLElement){if(this.world.phase==='battle'&&!this.world.paused&&!this.world.requiresPlayerDecision||this.world.phase==='battle'&&document.body.dataset.battleActionsReady!=='true'){this.footer.remove();return;}const target=root.querySelector<HTMLElement>('#overlay .m3-menu,#overlay .end-screen,#overlay .reward-screen');if(target&&!target.contains(this.footer))target.append(this.footer);}
 open(mode:string){if(this.world.phase==='battle'&&!this.world.paused&&!this.world.requiresPlayerDecision){this.wasPaused=false;this.world.paused=true;}else this.wasPaused=this.world.paused;this.mode=mode;this.previousFocus=document.activeElement as HTMLElement;this.resetInput();this.render();if(!this.dialog.open)this.dialog.showModal();this.updateHud();}
 close(){if(!this.blocking)return false;this.captureDraft();this.dialog.close();if(!this.wasPaused&&this.world.phase==='battle'&&!this.world.requiresPlayerDecision&&!document.hidden)this.world.paused=false;this.resetInput();this.updateHud();if(this.previousFocus?.isConnected)this.previousFocus.focus();return true;}
 refresh(){if(this.blocking&&this.mode==='privacy')this.render();}
 private shell(title:string,content:string){this.dialog.innerHTML=`<header><span>SC2 SURVIVORS / PLAYER SERVICES</span><button type="button" data-service-action="close" aria-label="关闭窗口">×</button><h2>${title}</h2></header><nav aria-label="玩家服务"><button type="button" data-service-action="feedback" ${this.mode==='feedback'?'aria-current="page"':''}>反馈</button><button type="button" data-service-action="privacy" ${this.mode==='privacy'?'aria-current="page"':''}>玩家数据与隐私</button></nav><p class="service-status" role="status" id="service-status"></p>${content}`;}
 private render(){if(this.mode==='privacy'){const c=this.client.config,enabled=c.enabled&&!this.client.offline,active=this.client.active;this.shell('由你选择分享哪些数据',`<p class="service-lead">统计当前${active?'已开启':'关闭'}。关闭统计也可以完整游玩、保存进度或单独提交反馈。</p>${!enabled?'<p class="service-unavailable">'+(this.client.offline?'离线版本不连接统计或反馈服务，不生成统计标识。':'此版本的统计与反馈服务尚未启用或暂不可用。')+'</p>':''}<section><h3>可选的游戏统计</h3><p>仅在明确同意之后生成本域随机浏览器标识，记录版本、种族、难度、关卡、构筑、卡牌交易、实际战斗摘要和加载／帧时。标识可区分浏览器，并不等于自然人数。</p><p>不上传完整存档、截图、回放、键盘或触摸轨迹；不采集设备指纹、完整 User-Agent、GPU 型号或精确位置。应用统计库不保留 IP；托管平台的网络日志由部署方说明。</p><p>开始采集之前的游戏历史不会补传。上传失败不会影响战斗或本地保存。</p></section><details><summary>保存期限与管理方</summary><p>原始事件90天；可关联战局与关卡180天；浏览器索引在最后活跃365天后删除；不含标识的汇总730天；反馈和选填联系方式180天；管理员审计90天。</p><p>管理方：${escape(c.operator||'未配置')}<br>联系渠道：${escape(c.contact||'未配置')}<br>备份最长保留：${c.backupDays===null?'未配置':c.backupDays+'天'}。删除将登记至独立删除清单；恢复备份前重放清单。已汇总且无法关联你的汇总不作个人识别。</p><p>声明版本 ${CONSENT_VERSION}。若内容更新，需重新同意。</p></details><div class="service-actions">${active?'<button type="button" data-service-action="withdraw">撤回统计授权</button>':`<button type="button" class="service-primary" data-service-action="allow" ${enabled?'':'disabled'}>同意并启用统计</button>`}<button type="button" data-service-action="close">${active?'返回游戏':'保持关闭 · 返回游戏'}</button></div>${this.client.identity?'<section class="service-delete"><h3>删除我的统计数据</h3><p>删除此浏览器可关联的统计记录，同时停止统计。本地存档、永久成长和资源缓存保持可用。反馈按下方反馈凭据单独管理。</p><button type="button" data-service-action="delete">删除我的统计数据</button></section>':''}${this.client.pendingPrivacy?'<p class="service-unavailable">本机已停止采集。服务器撤回／删除尚未确认，将保留隐私凭据重试。</p><button type="button" data-service-action="retry-privacy">重试隐私请求</button>':''}`);return;}
  const enabled=this.client.config.enabled&&!this.client.offline,pending=!!this.draft.pending,summary=this.currentSummary();this.shell('把这次体验告诉我们',`<p class="service-lead">反馈独立于统计授权。只提交你在此处选择的内容。</p>${!enabled?'<p class="service-unavailable">'+(this.client.offline?'离线版本不能发送反馈。正文可暂存在当前页面，供你复制。':'反馈服务暂不可用。正文保留在当前标签页，稍后可以重试。')+'</p>':''}<form id="player-feedback"><label>分类<select name="category" ${pending?'disabled':''}>${Object.entries(categories).map(([k,v])=>`<option value="${k}" ${this.draft.category===k?'selected':''}>${v}</option>`).join('')}</select></label><label>反馈内容 <small>10—2000字</small><textarea name="text" minlength="10" maxlength="2000" rows="6" required ${pending?'readonly':''}>${escape(this.draft.text)}</textarea></label><label>联系方式 <small>选填，仅用于处理本次反馈</small><input name="contact" maxlength="200" value="${escape(this.draft.contact)}" ${pending?'readonly':''}></label><label class="service-check"><input type="checkbox" name="summary" ${this.draft.summary?'checked':''} ${pending?'disabled':''}>附上以下版本与关卡摘要</label><p class="service-summary">${escape(({terran:"人族",zerg:"虫族",protoss:"神族"} as Record<string,string>)[String(summary.race)])} · ${escape(({easy:"简单",normal:"普通",hard:"困难",hell:"地狱"} as Record<string,string>)[String(summary.difficulty)])} · ${summary.stage?"第"+summary.stage+(summary.mode==="endless"?"轮无尽":"关"):"标题页"} · 版本 ${escape(String(summary.build).slice(0,12))}</p><details><summary>查看完整版本摘要</summary><p class="service-summary">${escape(JSON.stringify(summary))}</p></details><label class="service-check"><input type="checkbox" name="consent" required>我同意提交本次正文、选填联系方式和所选摘要。</label><div class="service-actions"><button type="submit" class="service-primary" ${enabled?'':'disabled'}>${pending?'重试发送同一条反馈':'发送反馈'}</button><button type="button" data-service-action="close">保存草稿 · 返回游戏</button></div>${pending?'<p class="service-hint">此条反馈已固定编号和内容，重试不会重复入库。服务器确认后可开始下一条。</p>':''}</form><section class="service-receipts"><h3>本机反馈凭据</h3><p class="service-hint">本机只保存最近10条查看／删除凭据；服务端只保存其哈希。清理浏览器数据后无法恢复凭据。反馈不自动发送邮件。</p>${this.receipts.length?this.receipts.map(r=>`<div><code>${escape(r.id)}</code><button type="button" data-service-action="view-feedback" data-id="${escape(r.id)}" ${enabled?'':'disabled'}>查看</button><button type="button" data-service-action="delete-feedback" data-id="${escape(r.id)}" ${enabled?'':'disabled'}>删除</button></div>`).join(''):'<p>还没有已提交的反馈。</p>'}</section>`);
 }
 private status(text:string){const p=this.dialog.querySelector('#service-status');if(p){p.textContent=text;this.dialog.scrollTop=0;}}
 private busy(value:boolean){this.dialog.querySelectorAll<HTMLButtonElement>('[data-service-action="allow"],[data-service-action="withdraw"],[data-service-action="delete"],[type="submit"]').forEach(b=>b.disabled=value);}
 private async consent(allow:boolean){this.busy(true);try{if(allow)await this.client.allow();else await this.client.withdraw();this.observer.syncConsent();this.render();this.status(allow?'已启用统计，从现在开始记录。':this.client.pendingPrivacy?'本机已停止，等待服务器确认撤回。':'已撤回统计授权，未发送队列已清空。');}catch{this.status('尚未启用。请求未完成，请稍后重试。');}finally{this.busy(false);}}
 private async removeData(){this.busy(true);await this.client.withdraw(true);this.observer.syncConsent();this.render();this.status(this.client.pendingPrivacy?'本机已停止，服务器删除尚未确认。':'你的可关联统计记录已删除。本地游戏进度保持可用。');}
 private async retryPrivacy(){await this.client.retryPrivacy();this.render();this.status(this.client.pendingPrivacy?'服务器暂未确认，请稍后重试。':'服务器已确认隐私请求。');}
 private captureDraft(){if(this.mode!=='feedback'||this.draft.pending)return;const form=this.dialog.querySelector<HTMLFormElement>('#player-feedback');if(!form)return;const d=new FormData(form);this.draft={category:String(d.get('category')??'problem'),text:String(d.get('text')??'').slice(0,2000),contact:String(d.get('contact')??'').slice(0,200),summary:d.has('summary')};this.saveDraft();}
 private saveDraft(){try{sessionStorage.setItem('sc2.feedback.draft',JSON.stringify(this.draft));}catch{}}
 private saveReceipts(){try{this.storage?.setItem('sc2.feedback.receipts',JSON.stringify(this.receipts.slice(-10)));}catch{}}
 private async submit(){const form=this.dialog.querySelector<HTMLFormElement>('#player-feedback');if(!form?.reportValidity())return;this.captureDraft();if(this.draft.text.trim().length<10){this.status('请填写至少10字的反馈内容。');return;}if(!this.draft.pending){const bytes=crypto.getRandomValues(new Uint8Array(32)),receipt=btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');this.draft.pending={id:crypto.randomUUID(),receipt,category:this.draft.category,text:this.draft.text.trim(),contact:this.draft.contact.trim(),summary:this.draft.summary?this.currentSummary():null,consentVersion:CONSENT_VERSION};this.saveDraft();}this.busy(true);this.status('正在发送…');try{const p=this.draft.pending;await this.client.api('/api/feedback',p);this.receipts.push({id:String(p.id),receipt:String(p.receipt),at:Date.now()});this.receipts=this.receipts.slice(-10);this.saveReceipts();this.draft={category:'problem',text:'',contact:'',summary:true};this.saveDraft();this.render();this.status('已收到。反馈编号 '+p.id+'，查看和删除凭据已保存在本机。');}catch{this.render();this.status('未确认发送，内容已保留。重试沿用同一编号，不会重复入库。');}}
 private async receipt(id:string,remove:boolean){const r=this.receipts.find(r=>r.id===id);if(!r)return;try{const result=await this.client.api('/api/feedback/'+(remove?'delete':'receipt'),{id:r.id,receipt:r.receipt});if(remove){this.receipts=this.receipts.filter(r=>r.id!==id);this.saveReceipts();this.render();this.status('该条反馈和联系方式已删除。');}else{const statuses:Record<string,string>={new:'待处理',reviewing:'处理中',planned:'已计划',resolved:'已解决',closed:'暂不处理'};this.status('反馈 '+id+' · '+(statuses[result.status]??result.status)+'\n'+result.text);}}catch{this.status('请求未完成，或该反馈已到期／删除。');}}
}
