import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {groups} from '../visual-plan-validation-20261009/catalog.ts';
const root='reports/local/lighting-batch3-20261010';
const settled=new Set(['zergling','baneling','roach','ravager','hydralisk','lurker','mutalisk','corruptor','ultralisk','zealot','heroes-terran-1','heroes-zerg-0','heroes-zerg-1','heroes-protoss-0']);
const rows=groups.flatMap(group=>group.identities.map(identity=>({id:identity.id,name:identity.name??identity.id,group:group.id,beforeNear:'before-r5-portraits/'+identity.id+'-near.png',afterNear:'after-r6-portraits/'+identity.id+'-near.png',beforeMaps:settled.has(group.id)?'before-r5-settled':'before-r5-maps',afterMaps:settled.has(group.id)?'after-r6-settled':'after-r6-maps',beforeMobile:settled.has(group.id)?'before-r5-settled':'before-r5-mobile',afterMobile:settled.has(group.id)?'after-r6-settled':'after-r6-mobile',settled:settled.has(group.id)})));
assert.equal(rows.length,138);const pairs=[];for(const row of rows){pairs.push([row.beforeNear,row.afterNear]);for(const theme of ['industrial','mar-sara','char','ice','frontier'])pairs.push([row.beforeMaps+'/'+row.group+'-'+theme+'-far.png',row.afterMaps+'/'+row.group+'-'+theme+'-far.png']);for(const layout of ['landscape','portrait','small'])pairs.push([row.beforeMobile+'/'+row.group+'-'+layout+'.png',row.afterMobile+'/'+row.group+'-'+layout+'.png']);}for(const file of new Set(pairs.flat()))assert.ok((await fs.stat(root+'/'+file)).isFile(),file);
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>第三批视觉 · 138 身份对照</title><style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#111820;color:#e0e8ee}body{margin:0;padding:24px}h1{font-size:24px;margin:0 0 8px}p{color:#adbdc7;line-height:1.6}nav{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin:20px 0}select,button{background:#1f2e3a;color:inherit;border:1px solid #60717c;border-radius:5px;padding:10px;font:inherit;max-width:100%}button{cursor:pointer}main{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0;min-width:0;background:#080d12;border:1px solid #34434e}figcaption{padding:12px}img{width:100%;display:block}#detail{font-size:14px;line-height:1.7;max-width:1100px;overflow-wrap:anywhere}a{color:#9ccffd}@media(max-width:750px){body{padding:14px}main{grid-template-columns:1fr}}
</style><h1>第三批视觉 · 前后对照</h1><p>30 普通 · 90 精英 · 18 英雄。相同原生场景、tick、视口和存档；原模型与材质资源不变。<a href="stage-gallery.html">分步效果</a> · <a href="sequence-gallery.html">连续动作诊断帧</a> · <a href="realtime-gallery.html">三族实际墙钟录像</a>。这些证据不替代自然战役、原版 SC2 客户端或真机验收。</p>
<nav><button id="previous" aria-label="上一个身份">←</button><select id="identity" aria-label="单位身份"></select><button id="next" aria-label="下一个身份">→</button><select id="view" aria-label="场景"><option value="near">完整身体近景 · tick 600</option><option value="industrial">工业区</option><option value="mar-sara">玛萨拉</option><option value="char">查尔</option><option value="ice">冰原</option><option value="frontier">边境</option><option value="landscape">横屏 844×390</option><option value="portrait">竖屏 390×844</option><option value="small">小屏 320×568</option></select><span id="count"></span></nav>
<main><figure><figcaption>修复前 · ab1ce01</figcaption><a id="beforeLink"><img id="before" alt="修复前截图"></a></figure><figure><figcaption>第三批 · 最终组合 · candidate-r4</figcaption><a id="afterLink"><img id="after" alt="修复后截图"></a></figure></main><p id="detail"></p>
<script type="application/json" id="data">${JSON.stringify(rows).replaceAll('<','\\u003c')}</script><script>
const rows=JSON.parse(document.querySelector('#data').textContent),select=document.querySelector('#identity'),view=document.querySelector('#view');rows.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.name+' · '+r.id;select.append(o)});
function show(){const r=rows[Number(select.value)],v=view.value,mobile=['landscape','portrait','small'].includes(v),paths=v==='near'?[r.beforeNear,r.afterNear]:mobile?[r.beforeMobile+'/'+r.group+'-'+v+'.png',r.afterMobile+'/'+r.group+'-'+v+'.png']:[r.beforeMaps+'/'+r.group+'-'+v+'-far.png',r.afterMaps+'/'+r.group+'-'+v+'-far.png'];['before','after'].forEach((id,i)=>{document.querySelector('#'+id).src=paths[i];document.querySelector('#'+id+'Link').href=paths[i]});document.querySelector('#count').textContent=(Number(select.value)+1)+' / '+rows.length;document.querySelector('#detail').textContent='组：'+r.group+'。'+(v==='near'||r.settled?'此视图从原生 tick 300 再推进 300 步，实际采样于 tick 600／10 秒，使出生动作完成。':'此视图保留原矩阵起始 tick 300／5 秒。')+' 文件：'+paths.join(' ↔ ')+'。阴影为 1024 PCF；接触遮蔽为半分辨率、12 样本、强度 0.5。';location.hash=r.id;}
select.onchange=view.onchange=show;for(const [id,delta]of [['previous',-1],['next',1]])document.querySelector('#'+id).onclick=()=>{select.value=(Number(select.value)+delta+rows.length)%rows.length;show()};const initial=rows.findIndex(r=>r.id===decodeURIComponent(location.hash.slice(1)));if(initial>=0)select.value=initial;show();</script></html>`;
await fs.writeFile(root+'/comparison-gallery.html',html);console.log(JSON.stringify({identities:rows.length,images:new Set(pairs.flat()).size}));
