import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {configurePlatformAssetUrl,assetUrl} from '../../src/assets/manifest';
import {checksum,encodeGraph} from '../../src/persistence/graph-codec';
import {scenario,prepareTargets,prepareCastTargets,activateMode,resolveActors,destroyActors,type Scenario} from '../visual-plan-validation-20261009/scenario';
import {groups,modeGroups,actorGroups,enemyGroups,identities,type Group,themes} from '../visual-plan-validation-20261009/catalog';
import {modelPresentationScale} from '../../src/data/combat-presentation';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {AIR_HEIGHT} from '../../src/data/terrain';
import {captureBattleView} from '../../src/render/input/battle-view';
import type {HeroId} from '../../src/data/heroes';
import {FixedStepper} from '../../src/simulation/fixed-stepper';

const canvas=document.querySelector<HTMLCanvasElement>('#battle')!,errors:string[]=[];
let s:Scenario,r:BattleRenderer,initial:ReturnType<Scenario['world']['captureRun']>,profile='',viewHeight=19,build:unknown,renderQuality:'native'|'balanced'|'performance'='native',fixedPixelRatio:number|null=1;
const status=(text:string)=>document.querySelector('#status')!.textContent=text;
const frame=()=>new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));
const state=()=>checksum(JSON.stringify(encodeGraph({run:s.world.captureRun(),profile:s.world.permanentProfile.exportJSON()})));
function size(){r.setQuality(renderQuality);if(fixedPixelRatio!==null)r.renderer.setPixelRatio(fixedPixelRatio);r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);r.camera.top=viewHeight;r.camera.bottom=-viewHeight;r.camera.left=-viewHeight*canvas.clientWidth/canvas.clientHeight;r.camera.right=-r.camera.left;r.camera.updateProjectionMatrix();}
function draw(){const before=state();size();r.render(0,1);if(before!==state())throw Error('Rendering mutated World/Profile/RNG');return report();}
function report(){const q={build,group:s?.group.id,theme:s?.theme,state:s?state():null,time:s?.world.time,tick:s?.world.tick,phase:s?.world.phase,subjects:s?.subjects.map(({identity,entity})=>{const u=s.world.entities.get(entity.id)??entity;return {identity:identity.id,entityId:u.id,hp:u.hp,barrier:u.barrier??0,barrierReady:u.barrierReady,deadAt:u.deadAt,x:u.x,z:u.z,action:u.action,shots:u.shotSequence};}),runtime:r?.report(),surfaces:r?[...r.gpu].filter(([,b])=>b.materialSurfaces?.length).map(([key,b])=>({key,count:b.count,capacity:1024,bytes:b.materialSurfaces.reduce((n,m)=>n+m.data.byteLength,0),materials:b.materialSurfaces.map(m=>({name:m.prepared.source.name,hash:m.prepared.profile.glbSha256,slots:Array.from({length:Math.min(b.count,20)},(_,i)=>({alpha:m.data[(10*1024+i)*4],emission:m.data[(2*1024+i)*4],opacityMultiply:m.data[(6*1024+i)*4],opacityAdd:m.data[(6*1024+i)*4+1],emissionUV:[m.data[(3*1024+i)*4],m.data[(3*1024+i)*4+1]]}))}))})):[],errors:[...errors,...(r?.report().errors??[])]};document.querySelector('#report')!.textContent=JSON.stringify(q);return q;}
async function assets(){r.prepareRosterAssets();for(const u of s.world.entities.values())if(u.hp>0)await r.ensureUnitVariant(u.modelKey??u.unitType,u.unitType);await r.prepareCurrentAssets();if(s.group.actors)await r.prepareEndlessAssets();await r.waitForPendingAssets();}
async function settle(){await assets();for(let i=0;i<3;i++){draw();await frame();}if(report().errors.length)throw Error(JSON.stringify(report().errors));}
function selectGroup(id:string):Group {if(id==='mixed-fleet')return {id,name:'原生旗舰与精英航母同场',race:'protoss',identities:[...groups.find(g=>g.id==='carrier')!.identities.filter(i=>i.kind==='elite'),identities.find(i=>i.hero==='purifier_flagship')!]};const found=[...groups,...modeGroups,...actorGroups,...enemyGroups].find(g=>g.id===id);if(found)return found;const hero=identities.find(i=>i.hero===id as HeroId);if(!hero)throw Error('Unknown fixture '+id);return {id,name:hero.name,race:hero.race,identities:[hero]};}
async function load(group='immortal',theme:typeof themes[number]='industrial'){
 document.body.dataset.ready='false';const next=scenario(selectGroup(group),theme,1);
 next.world.runId='lighting-batch3-fixture:'+group+':'+theme;
 // Fixed native bodies and native hit/order entry points; no synthetic visual events.
 for(const u of next.world.entities.values())u.stoppedUntil=u.nextShotAt=u.specialReady=1e9;
 if(!r){s=next;r=new BattleRenderer(canvas,s.world);await r.load(status,s.group.race);}
 else{const world=s.world;world.permanentProfile.importJSON(next.world.permanentProfile.exportJSON());world.restoreRun(next.world.captureRun());s={...next,world,subjects:next.subjects.map(x=>({...x,entity:world.entities.get(x.entity.id)!}))};r.resetRun();await r.prepareCampaignAssets(world.captureRun().config.campaignMap!);}
 viewHeight=19;await settle();initial=structuredClone(s.world.captureRun());profile=s.world.permanentProfile.exportJSON();document.body.dataset.ready='true';status(group+' · '+theme);return report();
}
async function reset(){s.world.permanentProfile.importJSON(profile);s.world.restoreRun(structuredClone(initial));s.subjects=s.subjects.map(x=>({...x,entity:s.world.entities.get(x.entity.id)!}));r.resetRun();await settle();return report();}
async function ticks(count:number){s.world.paused=false;for(let i=0;i<count;i++){s.world.step();r.render(1/60,1);if(i%12===11)await frame();}s.world.paused=true;await settle();return report();}
async function hit(index:number,amount:number){const u=s.subjects[index]?.entity;if(!u)throw Error('Missing subject');s.world.hit(u,amount,[],1,u.owner==='terran'?'zerg':'terran');return draw();}
async function reload(){const run=s.world.captureRun(),before=state();s.world.restoreRun(structuredClone(run));s.subjects=s.subjects.flatMap(x=>{const entity=s.world.entities.get(x.entity.id);return entity?[{...x,entity}]:[];});r.resetRun();await settle();if(before!==state())throw Error('Current save changed after restore');return report();}
async function move(){for(const {entity:u} of s.subjects)u.stoppedUntil=u.nextShotAt=u.specialReady=0;s.world.paused=false;if(!s.world.issueMove({x:0,z:9}))throw Error('Native move order refused');s.world.paused=true;return ticks(30);}
async function attack(){const before=s.subjects.map(x=>x.entity.shotSequence??0);for(const {entity:u} of s.subjects){u.stoppedUntil=u.nextShotAt=u.specialReady=0;const p=s.world.freePosition('roach',{x:u.x,z:u.z-3},0,4);if(!p)throw Error('No native target position');const t=s.world.addUnit('roach','zerg',p.x,p.z);t.hp=t.maxHp=1e6;t.stoppedUntil=t.nextShotAt=t.specialReady=1e9;}s.world.hash.rebuild(s.world.entities.values());for(let i=0;i<180;i++){await ticks(1);if(s.subjects.every((x,n)=>(x.entity.shotSequence??0)>before[n]))return report();}throw Error('Native attacks did not fire');}
async function reorder(){const before=state();s.world.entities=new Map([...s.world.entities].reverse());draw();return {before,after:state(),report:report()};}
async function view(height:number,index?:number){viewHeight=height;if(index!==undefined){const u=s.subjects[index].entity;s.world.anchor.x=u.x;s.world.anchor.z=u.z;(r as any).cameraTarget.set(u.x,r.ground(u),u.z);}else{s.world.anchor.x=s.world.anchor.z=0;(r as any).cameraTarget.set(0,r.ground({x:0,z:0}),0);}return draw();}
async function hero(id:HeroId,alive:boolean){if(alive){if(!s.world.acquireHero(id))throw Error('Hero unavailable');const u=s.world.heroEntity(id)!;let p:{x:number;z:number}|null=null;const edge=s.world.mapHalf-4;for(let z=-edge;z<=edge&&!p;z+=3)for(let x=-edge;x<=edge&&!p;x+=3){const q=s.world.freePosition(u.unitType,{x,z},0,.1);if(q&&!(r as any).visible(q)&&s.world.terrain!.canOccupy(q,u.unitRadius))p=q;}if(!p)throw Error('No legal off-camera hero position');u.x=p.x;u.z=p.z;u.prev={...p};u.stoppedUntil=u.nextShotAt=u.specialReady=1e9;await settle();}else{const u=s.world.heroEntity(id);if(!u)throw Error('Hero missing');s.world.hit(u,1e8,[],1,'zerg');if(u.hp>0)throw Error('Native hero death did not occur');draw();}return report();}
function deathStatus(){return s.subjects.map(({entity:u})=>{const key=(r as any).modelKey(u),b=r.gpu.get(key+'.death')??r.gpu.get(key),duration=b?.pose('dead')?.duration??1.5;return {id:u.id,key,clip:b?.actions.dead?.name,duration,life:Math.min(5,Math.max(1.5,duration)),count:b?.count,retained:(r as any).corpses.has(u.id)};});}
function textureFiltering(){const before=state(),rows:unknown[]=[];for(const quality of ['native','balanced','performance'] as const){r.setQuality(quality);const expected=Math.min(r.renderer.capabilities.getMaxAnisotropy(),quality==='native'?8:quality==='balanced'?4:1);for(const [key,b]of r.gpu)for(const surface of b.materialSurfaces??[])for(const [role,texture]of Object.entries(surface.prepared.textures)){if(texture.anisotropy!==expected)throw Error('Source sampler missed existing quality: '+key+'/'+role+'/'+quality);rows.push({key,role,quality,actual:texture.anisotropy,expected});}}draw();if(state()!==before)throw Error('Texture filtering changed simulation');return rows;}
function pipeline(){const composer=(r as any).heroComposer;return {toneMapping:r.renderer.toneMapping,exposure:r.renderer.toneMappingExposure,output:r.renderer.outputColorSpace,targetType:composer.renderTarget1.texture.type,targetColorSpace:composer.renderTarget1.texture.colorSpace,passes:composer.passes.map((p:any)=>({type:p.constructor.name,enabled:p.enabled,strength:p.strength,radius:p.radius,threshold:p.threshold,defines:p.material?.defines}))};}
async function pixels(){draw();const gl=r.renderer.getContext(),x=Math.floor(canvas.width*.25),y=Math.floor(canvas.height*.38),width=40,height=40,data=new Uint8Array(width*height*4);gl.readPixels(x,y,width,height,gl.RGBA,gl.UNSIGNED_BYTE,data);return {region:{x,y,width,height},checksum:checksum(Array.from(data).join(',')),rgb:Array.from(data.slice(0,12)),pipeline:pipeline(),state:state()};}
async function cost(seconds=5){await settle();const before=state(),frames:number[]=[],submits:number[]=[],drawCalls:number[]=[],triangles:number[]=[],visibility:string[]=[],focused:boolean[]=[],start=performance.now();let previous=start;r.renderer.info.autoReset=false;while(performance.now()-start<seconds*1000){await frame();const now=performance.now();frames.push(now-previous);previous=now;r.renderer.info.reset();const at=performance.now();r.render(0,1);submits.push(performance.now()-at);drawCalls.push(r.renderer.info.render.calls);triangles.push(r.renderer.info.render.triangles);visibility.push(document.visibilityState);focused.push(document.hasFocus());}const gl=r.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');return {seconds:(performance.now()-start)/1000,frames,submits,drawCalls,triangles,visibility:[...new Set(visibility)],focused:[...new Set(focused)],unchanged:before===state(),gpu:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):null,browser:navigator.userAgent,report:report(),method:'Short paused rendering cost record, not stable-FPS or natural performance acceptance'};}
addEventListener('error',e=>errors.push(e.message));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));addEventListener('resize',()=>{if(r)draw();});
const sourcePoseBounds=new Map<string,THREE.Box3>();
async function focus(index:number){
 const subject=s.subjects[index],u=subject.entity,key=(r as any).modelKey(u),b=r.gpu.get(key);if(!b)throw Error('Missing focus model');
 const instance=new THREE.Matrix4(),point=new THREE.Vector3();let slot=0,best=Infinity;
 for(let i=0;i<b.count;i++){b.meshes[0].getMatrixAt(i,instance);point.setFromMatrixPosition(instance);const d=(point.x-u.x)**2+(point.z-u.z)**2;if(d<best){best=d;slot=i;}}
 const pose=b.attributes[0],frame=pose.getX(slot),clip=[...b.clips].find(([,p])=>frame>=p.offset&&frame<p.offset+p.frames),seconds=clip?(frame-clip[1].offset+pose.getZ(slot))/(clip[1].frames-1)*clip[1].duration:0;
 const visible=new Map(b.meshes.flatMap(mesh=>(Array.isArray(mesh.material)?mesh.material:[mesh.material]).map(m=>[m.name,m.visible]as const)));
 const cacheKey=subject.identity.model+'|'+clip?.[0]+'|'+seconds.toFixed(4)+'|'+[...visible].join(',');let source=sourcePoseBounds.get(cacheKey);
 if(!source){
  const url=assetUrl('model.'+subject.identity.model);if(!url)throw Error('Missing portrait source model');
  const g=await new GLTFLoader().loadAsync(url),mixer=new THREE.AnimationMixer(g.scene),action=g.animations.find(a=>a.name===clip?.[0]);if(action){const track=mixer.clipAction(action).setLoop(THREE.LoopOnce,1);track.clampWhenFinished=true;track.play();mixer.setTime(seconds);}g.scene.updateMatrixWorld(true);
  source=new THREE.Box3();g.scene.traverse(node=>{if(!(node instanceof THREE.Mesh)||node.userData.sc2Role!=='body')return;if(!(Array.isArray(node.material)?node.material:[node.material]).some(m=>visible.get(m.name)!==false))return;source!.union(new THREE.Box3().setFromObject(node,true));});
  if(source.isEmpty())throw Error('Missing physical portrait bounds');sourcePoseBounds.set(cacheKey,source.clone());
  mixer.stopAllAction();mixer.uncacheRoot(g.scene);const textures=new Set<THREE.Texture>();g.scene.traverse(node=>{if(!(node instanceof THREE.Mesh))return;node.geometry.dispose();for(const material of Array.isArray(node.material)?node.material:[node.material]){for(const value of Object.values(material))if(value instanceof THREE.Texture)textures.add(value);material.dispose();}});for(const texture of textures)texture.dispose();
 }
 const transform=new THREE.Object3D();transform.position.set(u.x,u.flying?AIR_HEIGHT:r.ground(u),u.z);transform.rotation.y=u.facing;transform.scale.setScalar(modelPresentationScale(u));transform.updateMatrix();
 const bounds=source.clone().applyMatrix4(b.normalization).applyMatrix4(transform.matrix),center=bounds.getCenter(new THREE.Vector3());
 s.world.anchor.x=u.x;s.world.anchor.z=u.z;(r as any).cameraTarget.copy(center);r.camera.position.copy(center).add(new THREE.Vector3(0,34,26));r.camera.lookAt(center);r.camera.updateMatrixWorld();
 let horizontal=0,vertical=0;for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){point.set(x,y,z).applyMatrix4(r.camera.matrixWorldInverse);horizontal=Math.max(horizontal,Math.abs(point.x));vertical=Math.max(vertical,Math.abs(point.y));}
 viewHeight=Math.max(.35,vertical*1.18,horizontal*canvas.clientHeight/canvas.clientWidth*1.18);const q=draw();
 const projected=[];for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z])projected.push(new THREE.Vector3(x,y,z).project(r.camera).toArray());
 if(projected.some(([x,y])=>Math.abs(x)>.85||Math.abs(y)>.85))throw Error('Portrait physical bounds are clipped');
 return {...q,portraitBounds:{model:subject.identity.model,clip:clip?.[0],seconds,world:[bounds.min.toArray(),bounds.max.toArray()],projected}};
}
async function combat(){prepareTargets(s);for(const {entity:u}of s.subjects)u.stoppedUntil=u.nextShotAt=u.specialReady=0;await settle();return ticks(60);}
async function cast(){prepareCastTargets(s);s.world.paused=false;const outcomes=s.subjects.filter(x=>x.identity.hero).map(x=>({hero:x.identity.hero,accepted:s.world.castHero(x.identity.hero!,captureBattleView(canvas,r.camera))}));await ticks(12);return {outcomes,report:report()};}
async function mode(){const outcome=activateMode(s);await ticks(60);return {outcome,report:report()};}
async function actorLifecycle(phase:'open'|'destroy'){if(!s.group.actors)throw Error('Actor fixture required');if(phase==='open')resolveActors(s);else destroyActors(s);await settle();return report();}
function materialState(){draw();return [...r.gpu].filter(([,b])=>b.count).map(([key,b])=>({key,count:b.count,height:b.bodyHeight,scale:b.scale,hash:checksum(b.materialSurfaces.map(m=>Array.from({length:b.count},(_,i)=>Array.from({length:m.texture.image.height},(_,row)=>Array.from(m.data.slice((row*1024+i)*4,(row*1024+i)*4+4))))).flat(5).join(','))}));}
function models(){return s.subjects.map(({identity,entity:u})=>{const key=(r as any).modelKey(u),b=r.gpu.get(key),base=r.gpu.get(u.unitType);return {identity:identity.id,key,ordinaryHeight:base?.bodyHeight,bodyHeight:b?.bodyHeight,displayScale:modelPresentationScale(u),flying:u.flying,hero:u.heroId,elite:u.eliteId,unitType:u.unitType};});}
const catalog=()=>({groups:groups.map(g=>({id:g.id,identities:g.identities.map(i=>i.id)})),modes:modeGroups.map(g=>g.id),actors:actorGroups.map(g=>g.id),enemies:enemyGroups.map(g=>g.id),themes,identities});
async function blink(){const u=s.subjects.find(x=>x.identity.id==='stalker.2')!.entity;s.world.expedition.tech.blink=1;s.world.paused=false;let accepted=false;for(const [dx,dz]of [[0,2],[2,0],[-2,0],[0,-2]])if(s.world.castFamilyAbility('stalker',{x:u.x+dx,z:u.z+dz})){accepted=true;break;}s.world.paused=true;await settle();return {accepted,report:report()};}
function blinkState(){return s.subjects.map(({identity,entity})=>{const u=s.world.entities.get(entity.id)!,key=(r as any).modelKey(u),b=r.gpu.get(key),matrix=new THREE.Matrix4(),point=new THREE.Vector3();let slot=0,best=Infinity;if(b)for(let i=0;i<b.count;i++){b.meshes[0].getMatrixAt(i,matrix);point.setFromMatrixPosition(matrix);const distance=(point.x-u.x)**2+(point.z-u.z)**2;if(distance<best){best=distance;slot=i;}}return {identity:identity.id,hp:u.hp,native:u.protossEliteCombat,activities:(b?.materialSurfaces??[]).map(m=>m.data[((m.texture.image.height-1)*1024+slot)*4+3])};});}
let acidSubject=0,acidSource=0;
async function acidSetup(theme:typeof themes[number]='industrial'){
 await load('thor',theme);const w=s.world,ally=s.subjects[0].entity;s.subjects=s.subjects.slice(0,1);w.entities=new Map([[ally.id,ally]]);
 let boss;for(let i=0;i<16;i++){const p={x:ally.x+Math.sin(i*Math.PI/8)*5,z:ally.z+Math.cos(i*Math.PI/8)*5};if(w.terrain?.lineOfFire(p,ally,true,false)){boss=w.spawnSpecial('corruptor','boss',p);if(boss)break;}}
 if(!boss)throw Error('No acid caster site');boss.specialDamageMultiplier=1;boss.specialReady=0;boss.nextShotAt=1e9;boss.moveSpeed=0;w.hash.rebuild(w.entities.values());w.enemySpecials.act(boss,1/60);if(w.enemySpecials.casts[0]?.kind!=='acid')throw Error('Native acid did not cast');
 acidSubject=ally.id;acidSource=boss.id;s.world.anchor.x=ally.x;s.world.anchor.z=ally.z;(r as any).cameraTarget.set(ally.x,r.ground(ally),ally.z);viewHeight=8;await settle();return acidState();
}
function acidState(){return {state:state(),time:s.world.time,tick:s.world.tick,hp:s.world.entities.get(acidSubject)?.hp,sourceHp:s.world.entities.get(acidSource)?.hp,zones:structuredClone(s.world.enemySpecials.acidZones),visual:(r.report().nonHeroes as any).acidGround,report:report()};}
async function acidKill(){const source=s.world.entities.get(acidSource)!;s.world.hit(source,1e9,[],1,'terran');await settle();return acidState();}
function markerState(){const q=draw();return {state:q.state,anchor:{...s.world.anchor},order:q.runtime.order,destinationVisible:(r as any).destinationMarker?.visible,anchorMeshPresent:!!(r as any).anchor,lineVertices:(r as any).lines.geometry.drawRange.count,blobInstances:(r as any).shadows.count};}
async function markers(phase:'move'|'target'|'clear'){
 if(phase==='move'){s.world.paused=false;const p=s.world.freePosition('marine',{x:2,z:7},0,4);if(!p||!s.world.issueMove(p))throw Error('Move failed');s.world.paused=true;}
 r.targetPreview=phase==='target'?{x:2,z:4}:null;return markerState();
}
function poseAudit(){const registry=(r as any).sceneShadows?.depth;if(!registry)return [];const rows:unknown[]=[];r.scene.traverseVisible(node=>{
 if(!(node instanceof THREE.InstancedMesh)||!node.count||!node.geometry.hasAttribute('unitPose'))return;
 const sources=Array.isArray(node.material)?node.material:[node.material],depth=registry.prepare(node).depth;
 for(let i=0;i<sources.length;i++){if(!depth[i].visible)continue;const color={uniforms:{},vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader},shadow={uniforms:{},vertexShader:THREE.ShaderLib.depth.vertexShader,fragmentShader:THREE.ShaderLib.depth.fragmentShader};sources[i].onBeforeCompile(color,r.renderer);depth[i].onBeforeCompile(shadow,r.renderer);
 const uniforms=['unitBoneAtlas','unitBind','unitAsset','turretPivot','unitAccentRange',...((color.uniforms as any).umState?['umState']:[])];for(const name of uniforms)if((color.uniforms as any)[name]?.value!==(shadow.uniforms as any)[name]?.value)throw Error('Depth pose uniform differs: '+name);
 rows.push({name:node.name,material:sources[i].name,count:node.count,uniforms,geometryShared:true,shadow:node.castShadow,receive:node.receiveShadow});}
 });return rows;}
function offsetView(x:number,z:number){s.world.anchor.x+=x;s.world.anchor.z+=z;(r as any).cameraTarget.x+=x;(r as any).cameraTarget.z+=z;return draw();}
function resolution(quality:'native'|'balanced'|'performance',ratio:number|null=null){renderQuality=quality;fixedPixelRatio=ratio;return draw();}
let hiddenSubject=0;
async function hiddenCaster(phase:'setup'|'reveal'|'expire'){
 const w=s.world;if(phase==='setup'){await load('marine');const u=w.spawnSpecial('lurker','boss',{x:0,z:0})!;if(!u)throw Error('Missing native hidden caster');hiddenSubject=u.id;u.nextShotAt=u.specialReady=u.stoppedUntil=1e9;await settle();}
 else if(phase==='reveal'){w.paused=false;const accepted=w.castDetection();w.paused=true;if(!accepted)throw Error('Detection refused');await settle();}
 else await ticks(900);
 const q=draw(),u=w.entities.get(hiddenSubject);return {state:q.state,visible:!!u&&w.visibleTo(u,'terran'),rendered:r.gpu.get('lurker')?.count??0,report:q};
}
async function contextRestore(){const gl=r.renderer.getContext(),extension=gl.getExtension('WEBGL_lose_context');if(!extension)throw Error('Context restore test unavailable');const before=state();await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Restore timeout')),30000);canvas.addEventListener('webglcontextrestored',()=>{clearTimeout(timer);resolve();},{once:true});canvas.addEventListener('webglcontextlost',()=>setTimeout(()=>extension.restoreContext(),200),{once:true});extension.loseContext();});await settle();return {before,after:state(),report:report()};}
async function realtime(seconds:number){
 if(seconds<1||seconds>60)throw Error('Bounded recording required');const start=performance.now(),startTick=s.world.tick;let previous=start,frames=0;const gaps:number[]=[];s.world.paused=false;
 const stepper=new FixedStepper(1/60,()=>{if(s.world.phase!=='battle'||s.world.paused||s.world.requiresPlayerDecision)return false;s.world.step();return true;});
 while(performance.now()-start<seconds*1000){await frame();const now=performance.now(),dt=(now-previous)/1000;previous=now;gaps.push(dt*1000);const alpha=stepper.advance(dt);r.render(dt,alpha);frames++;}
 const wallSeconds=(performance.now()-start)/1000;s.world.paused=true;await settle();gaps.sort((a,b)=>a-b);return {wallSeconds,simulationTicks:s.world.tick-startTick,frames,backlogSeconds:stepper.accumulator,discardedSeconds:stepper.discardedBacklogSeconds,rafP95:gaps[Math.floor(gaps.length*.95)],visible:document.visibilityState,focus:document.hasFocus(),state:state(),report:report(),method:'Visible wall-clock recording of a controlled native fixture with native FixedStepper; not natural campaign or stable-FPS acceptance'};
}
(window as any).materialLab={load,reset,ticks,hit,reload,move,attack,reorder,view,hero,cost,draw,report,pixels,pipeline,deathStatus,textureFiltering,focus,combat,cast,mode,actorLifecycle,catalog,materialState,models,blink,blinkState,acidSetup,acidState,acidKill,markers,markerState,poseAudit,offsetView,resolution,hiddenCaster,contextRestore,realtime};
try{build=await(await fetch('./build.json')).json();const manifest=await(await fetch('./asset-manifest.json')).json();configurePlatformAssetUrl(id=>manifest.assets[id]?.url?'/'+manifest.assets[id].url:null);await load();}catch(e){errors.push(String(e));status('失败 '+e);document.body.dataset.ready='true';report();}
