import * as THREE from 'three';
import {World} from '../../src/simulation/world';
import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {FixedStepper} from '../../src/simulation/fixed-stepper';
import {HEROES,type HeroId} from '../../src/data/heroes';
import {ASSETS,assetUrl} from '../../src/assets/manifest';
import {loadEmbeddedAssets,prepareEmbeddedAssetIds} from '../../src/assets/offline-pack';
import {captureBattleView} from '../../src/render/input/battle-view';
import {bindBattleView,activateBattleAction} from '../../src/ui/controls/battle-actions';
import {groundHeroBuff} from '../../src/simulation/combat/hero-ground-auras';
import {terranHeroGrowth} from '../../src/data/terran-heroes';
import type {Entity} from '../../src/simulation/types';
const ids=['raynor','tychus','nova','swann','tosh','yamato_battlecruiser'] as const;
type Mode='battle'|'attack'|'skill'|'aura'|'boss12'|'boss3';
const $=(id:string)=>document.getElementById(id)!;
const selected=new Set<string>(JSON.parse($('demo-assets').textContent!));for(const id of ASSETS.keys())if(!selected.has(id))ASSETS.delete(id);
const world=new World({race:'terran',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10505});
const canvas=$('battle') as HTMLCanvasElement,view=new BattleRenderer(canvas,world);view.fx.heroQuality='full';view.cameraShake=false;bindBattleView(world,()=>captureBattleView(canvas,view.camera));
let hero:typeof ids[number]='raynor',rank=5,mode:Mode='battle',ready=false,spawnAt=0,wave=0,previous=performance.now(),zoom='close',boss:number|null=null,bossHp=0,bossAt=0,bossResult='';
const keys=new Set<string>(),baseline=new Map<number,number>();
function resize(){view.resize();view.camera.zoom=canvas.clientWidth<canvas.clientHeight?1.05:zoom==='close'?1.65:1.18;view.camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function dummy(x:number,z:number,air=false){const e=world.addUnit(air?'mutalisk':'roach','zerg',x,z,1,'regular',13);e.hp=e.maxHp=2000000;e.armor=0;e.moveSpeed=0;e.stoppedUntil=1e9;e.specialReady=1e9;baseline.set(e.id,e.hp);return e;}
function spawn(){wave++;for(let i=0;i<5;i++){const a=world.time*.21+i*.65;world.addUnit(i%3===2?'zergling':'roach','zerg',world.anchor.x+6.5+Math.cos(a)*2,world.anchor.z+Math.sin(a)*4,1,'regular',13);}if(hero==='yamato_battlecruiser'&&wave%2===1)world.addUnit('mutalisk','zerg',world.anchor.x+7,world.anchor.z-3,1,'regular',13);}
function choose(id:typeof ids[number]){
 hero=id;view.resetRun();world.resetRun();world.start();world.entities.clear();world.heroes.clear();world.pods=[];world.hive=null;world.expansionHives.clear();world.economicTargets.clear();world.fortifications.clear();world.pickups=[];world.rewardDrops=[];world.stage=mode==='boss12'||mode==='boss3'?12:13;world.difficulty=mode==='boss12'||mode==='boss3'?'easy':'normal';world.stageElapsed=0;baseline.clear();boss=null;bossResult='';
 for(const plan of Object.values(world.expedition.production))plan.enabled={};world.acquireHero(id);const u=world.heroEntity(id)!;u.rank=rank;world.heroes.get(id)!.rank=rank;world.refreshStats(u,true);u.x=-1.5;u.z=0;u.prev={x:u.x,z:u.z};world.anchor.x=world.anchor.z=0;spawnAt=0;wave=0;world.paused=false;keys.clear();world.resetDirectionalInput();
 if(mode==='attack'||mode==='skill'){for(const [x,z] of [[3,0],[5,0],[7,0],[4,1.6],[6,-1.6],[7,3]])dummy(x,z);if(id==='yamato_battlecruiser')dummy(5,-3,true);}
 if(id==='swann'||mode==='aura'){for(let i=0;i<7;i++){const a=world.addUnit(i%2?'hellion':'tank','terran',1+(i%4)*1.4,-2+Math.floor(i/4)*3);if(mode!=='battle')a.stoppedUntil=1e9;if(id==='swann'){a.hp=Math.max(1,a.maxHp*.2);baseline.set(a.id,a.hp);}}}
 if(id==='swann'&&mode==='skill'){const last=world.allies().filter(a=>!a.heroId).at(-1)!;world.entities.delete(last.id);baseline.delete(last.id);world.acquireHero('yamato_battlecruiser');const ally=world.heroEntity('yamato_battlecruiser')!;ally.rank=rank;world.heroes.get('yamato_battlecruiser')!.rank=rank;world.refreshStats(ally,true);ally.x=3;ally.z=2;ally.prev={x:3,z:2};ally.hp=ally.maxHp*.2;ally.stoppedUntil=1e9;baseline.set(ally.id,ally.hp);}
 if(mode==='aura'){dummy(4,0);dummy(5,2);}
 if(mode==='skill'||mode==='boss12'||mode==='boss3')u.stoppedUntil=1e9;
 if(mode==='boss12'||mode==='boss3'){
  // The same public factory as campaign/endless. No weakened HP or armor.
  if(mode==='boss3'){world.stage=18;world.endless={round:3,startedAt:world.time,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=world.spawnSpecial('queen','boss',{x:12,z:0})!;world.entities.delete(first.id);}
  const e=world.spawnSpecial(mode==='boss3'?'lurker':'ravager','boss',{x:5,z:0})!;e.moveSpeed=0;e.stoppedUntil=1e9;e.specialReady=1e9;if(mode==='boss3')world.castDetection();boss=e.id;bossHp=Math.round(e.hp);bossAt=world.time;baseline.set(e.id,e.hp);bossResult=`Boss ${Math.ceil(e.hp)} HP · 护甲 ${e.armor}`;
 }
 world.hash.rebuild(world.entities.values());for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.setAttribute('aria-pressed',String(b.dataset.hero===id));$('name').textContent=HEROES[id].name;$('pause').textContent='暂停';$('portrait').innerHTML=assetUrl('hero.'+id)?`<img src="${assetUrl('hero.'+id)}" alt="${HEROES[id].name}">`:'';resize();world.changed();
}
function cast(){const u=world.heroEntity(hero);if(!u)return;const stopped=u.stoppedUntil;u.stoppedUntil=0;const ok=activateBattleAction(world,'hero-slot-0');u.stoppedUntil=stopped;if(ok&&(mode==='boss12'||mode==='boss3'))bossAt=world.time;}
const stepper=new FixedStepper(1/60,()=>{if(!ready||world.paused||world.phase!=='battle')return false;world.stageElapsed=0;world.rewardDrops=[];if(mode==='battle'&&world.time>=spawnAt&&world.enemyCount()<24){spawn();spawnAt=world.time+1.25;}world.input.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);world.input.z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(mode==='boss3'&&world.endless)world.endless.startedAt=world.time;world.step();return true;},()=>performance.now(),8);
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-previous)/1000);previous=now;const alpha=ready&&!world.paused?stepper.advance(dt):0;view.render(dt,alpha);if(ready){const u=world.heroEntity(hero),hp=Math.max(0,u?.hp??0),max=u?.maxHp??1;$('vital-fill').style.width=hp/max*100+'%';$('health').textContent=Math.ceil(hp)+' / '+Math.ceil(max);$('kills').textContent=String(world.stats.kills);$('time').textContent=Math.floor(world.time/60).toString().padStart(2,'0')+':'+Math.floor(world.time%60).toString().padStart(2,'0');$('enemies').textContent=String(world.enemyCount());
  const record=world.heroes.get(hero),remaining=Math.max(0,(record?.skillReady??0)-world.time);($('cast') as HTMLButtonElement).disabled=remaining>0||world.paused;$('cast').textContent=remaining>0?`${HEROES[hero].skill} · ${Math.ceil(remaining)}s`:'释放技能 · 空格';if(boss&&!world.entities.get(boss)?.hp&&bossResult.includes('Boss '))bossResult=`一发击杀 · ${bossHp} HP · ${(world.time-bossAt).toFixed(2)} 秒`;else if(boss&&world.entities.get(boss)?.hp&&world.time-bossAt>HEROES[hero].delay)bossResult=`Boss 剩余 ${Math.ceil(world.entities.get(boss)!.hp)} / ${bossHp}`;$('boss-result').textContent=bossResult;
 }}
for(const id of ids){const b=document.createElement('button');b.dataset.hero=id;b.textContent=HEROES[id].name;b.disabled=true;b.onclick=()=>{choose(id);stepper.reset();};$('heroes').append(b);}
$('cast').onclick=cast;$('pause').onclick=()=>{world.paused=!world.paused;$('pause').textContent=world.paused?'继续':'暂停';stepper.reset();};$('restart').onclick=()=>{choose(hero);stepper.reset();};$('rank').onchange=()=>{rank=Number(($('rank') as HTMLSelectElement).value);choose(hero);stepper.reset();};$('mode').onchange=()=>{mode=($('mode') as HTMLSelectElement).value as Mode;if(mode==='boss12'||mode==='boss3'){rank=mode==='boss12'?1:5;($('rank') as HTMLSelectElement).value=String(rank);choose('yamato_battlecruiser');}else choose(hero);stepper.reset();};$('zoom').onclick=()=>{zoom=zoom==='close'?'battle':'close';$('zoom').textContent=zoom==='close'?'战场视角':'近景视角';resize();};
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLSelectElement)return;const k=e.key.toLowerCase();if(e.code==='Space'){e.preventDefault();cast();}if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);}});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();world.resetDirectionalInput();});canvas.addEventListener('pointerdown',e=>{if(!ready||world.paused)return;const p=view.pickMove(e.clientX,e.clientY);if(p)world.issueMove(p.point);});canvas.addEventListener('contextmenu',e=>e.preventDefault());
async function load(){await loadEmbeddedAssets();await prepareEmbeddedAssetIds(selected,(d,t)=>{$('interface').textContent=`准备战场 ${d}/${t}`;});await view.fx.load();await view.confirmedHeroes.prepare();for(const type of ['roach','zergling','mutalisk','ravager','lurker','hellion','tank'] as const)if(!await view.ensureUnitVariant(type,type))throw Error(view.modelErrors.join(';'));for(const id of ids)if(!await view.ensureUnitVariant(HEROES[id].model,HEROES[id].baseFamily))throw Error(view.modelErrors.join(';'));
 const texture=await new THREE.TextureLoader().loadAsync(assetUrl('map.terrain.diffuse')!);texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(30,30);const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),new THREE.MeshStandardMaterial({map:texture,color:0x829199,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.025;view.scene.add(floor);view.initialAssetsLoaded=false;choose(hero);await view.warmPresentationBatches();ready=true;$('interface').hidden=true;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.disabled=false;previous=performance.now();}
requestAnimationFrame(frame);load().catch(e=>{$('interface').textContent='载入失败：'+e.message;console.error(e);});
(window as any).__INTEGRATED_HERO_REPORT__=()=>({ready,hero,rank,mode,paused:world.paused,phase:world.phase,time:world.time,shots:world.stats.shots,kills:world.stats.kills,damage:world.stats.damage,healed:world.stats.healed,boss:{id:boss,originalHp:bossHp,hp:boss?world.entities.get(boss)?.hp??0:null,result:bossResult},modelErrors:view.modelErrors,fxErrors:view.fx.errors,render:view.confirmedHeroes.report(),packets:world.heroAttacks.packets.map(p=>({id:p.id,hero:p.hero,kind:p.kind,target:p.target,primaryTarget:p.primaryTarget,damage:p.damage,hits:p.hits,hop:p.hop})),dots:world.heroAttacks.dots.map(d=>({target:d.target,remaining:d.remaining,damage:d.damage})),lines:world.heroAttacks.lines.length,source:world.heroEntity(hero),targets:[...baseline].map(([id,hp])=>({id,hpBefore:hp,hp:world.entities.get(id)?.hp??0})),buffs:world.allies().map(u=>({id:u.id,...groundHeroBuff(world,u)}))});
