import fs from 'node:fs/promises';import {createHash} from 'node:crypto';
import {decodeDds,rgbaToPng} from './dds-png.mjs';import {convertMaterialPixels} from './m3-materials.mjs';
const extracted=JSON.parse(await fs.readFile('assets/private/maps/map-extracted.json','utf8')),runtime=JSON.parse(await fs.readFile('assets/private/maps/map-runtime.json','utf8'));
const folder='public/assets/map';await fs.mkdir(folder,{recursive:true});const manifest=[];const hash=b=>createHash('sha256').update(b).digest('hex');
async function asset(id,kind,name,bytes,extra={}){const packedFile=folder+'/'+name;await fs.writeFile(packedFile,bytes);manifest.push({id,kind,packedFile,required:true,source:extracted.source.source,sourceSha256:extracted.source.sha256,sha256:hash(bytes),...extra});}
// Preserve every original DDS pixel: layers are packed at the largest native side, never downsampled.
for(const role of ['diffuse','normal']){const images=[];for(const layer of extracted.textures){const name=layer[role].replaceAll('\\','/').split('/').at(-1).toLowerCase(),decoded=decodeDds(await fs.readFile('assets/private/dds/'+name));images.push(role==='normal'?convertMaterialPixels(decoded,{normal:true}):decoded);}
 const side=Math.max(...images.map(i=>Math.max(i.width,i.height))),width=side*2,height=side*4,rgba=Buffer.alloc(width*height*4);
 for(let layer=0;layer<8;layer++){const im=images[layer];for(let y=0;y<side;y++)for(let x=0;x<side;x++){const src=(Math.floor(y/side*im.height)*im.width+Math.floor(x/side*im.width))*4,dst=((Math.floor(layer/2)*side+y)*width+layer%2*side+x)*4;im.rgba.copy(rgba,dst,src,src+4);}}
 await asset('map.terrain.'+role,'texture','terrain-'+role+'.png',rgbaToPng({width,height,rgba}),{layerDimensions:images.map(i=>[i.width,i.height]),tileSize:side});
}
const mask=await fs.readFile('assets/private/maps/KairosJunctionLE/t3TextureMasks');if(mask.subarray(0,4).toString()!=='MASK'||mask.readUInt32LE(4)!==102)throw Error('Unsupported original terrain mask');const mw=mask.readUInt32LE(12),mh=mask.readUInt32LE(16),tx=mw/64,ty=mh/64,layerBytes=mw*mh/2;if(mask.length!==64+8*layerBytes)throw Error('Truncated mask');
for(let group=0;group<2;group++){const rgba=Buffer.alloc(mw*mh*4);for(let layer=0;layer<4;layer++)for(let y=0;y<mh;y++)for(let x=0;x<mw;x++){const offset=64+(group*4+layer)*layerBytes+(Math.floor(y/64)*tx+Math.floor(x/64))*2048+(y%64)*32+Math.floor((x%64)/2),v=(mask[offset]>>(x%2?0:4))&15;rgba[(y*mw+x)*4+layer]=v*17;}await asset('map.terrain.mask'+group,'texture','mask'+group+'.png',rgbaToPng({width:mw,height:mh,rgba}));}
const imageIds=new Set(),models=new Set([...runtime.placements,...runtime.cliffs].filter(p=>p.assetId).map(p=>p.assetId));
for(const id of models){const file='public/assets/animated/'+id+'.glb',b=await fs.readFile(file);if(b.subarray(0,4).toString()!=='glTF'||b.readUInt32LE(8)!==b.length)throw Error('Invalid map GLB '+id);const len=b.readUInt32LE(12),j=JSON.parse(b.subarray(20,20+len)),bin=b.subarray(28+len);const removed=new Set();
 for(const im of j.images??[]){if(im.bufferView===undefined)throw Error('Unexpected external source image');const old=im.bufferView,v=j.bufferViews[old],bytes=bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength),digest=hash(bytes),imageId='map.image.'+digest;
  if(!imageIds.has(imageId)){await asset(imageId,'texture',digest+'.png',bytes);imageIds.add(imageId);}im.uri='sc2asset:'+imageId;delete im.bufferView;removed.add(old);}
 const views=[],chunks=[],lookup=new Map();let offset=0;for(let i=0;i<(j.bufferViews??[]).length;i++){if(removed.has(i))continue;const v=j.bufferViews[i],data=bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength),pad=Buffer.alloc(Math.ceil(data.length/4)*4);data.copy(pad);lookup.set(i,views.length);views.push({...v,byteOffset:offset});chunks.push(pad);offset+=pad.length;}
 for(const a of j.accessors??[]){if(a.bufferView!==undefined)a.bufferView=lookup.get(a.bufferView);if(a.sparse)for(const k of ['indices','values'])a.sparse[k].bufferView=lookup.get(a.sparse[k].bufferView);}
 j.bufferViews=views;j.buffers=[{byteLength:offset,uri:'data:application/octet-stream;base64,'+Buffer.concat(chunks).toString('base64')}];await asset(id,'map-model',id+'.gltf',Buffer.from(JSON.stringify(j)),{originalGlbBytes:b.length,animations:(j.animations??[]).map(a=>a.name)});
}
await asset('map.kairos','map-data','kairos.json',Buffer.from(JSON.stringify(runtime)));await fs.writeFile('assets/private/map-pack.json',JSON.stringify({manifest,failures:[]},null,2));console.log(JSON.stringify({models:models.size,sharedImages:imageIds.size,assets:manifest.length}));
