import fs from 'node:fs/promises';
import path from 'node:path';
import {RUNTIME_ASSETS,filename} from './runtime-catalog.mjs';
import {inspectGlb} from './glb-inspect.mjs';
import './generate-audio.mjs';
const records=[];
for(const a of RUNTIME_ASSETS){const ext=a.kind==='model'?'.glb':a.kind==='icon'?'.png':'.jpg',file=filename(a,ext);let record={id:a.id,kind:a.kind,status:'missing',url:file.replace('public/',''),packedFile:file,required:a.required,animations:[],bytes:0};
 try{const bytes=await fs.readFile(file);record.bytes=bytes.length;
 if(a.kind==='model'){
  const info=inspectGlb(bytes);if(info.externalResources.length)throw Error('External GLB dependencies are unsupported; provide a self-contained GLB');
  record.animations=info.animationNames;const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());let bin;let offset=12;
  while(offset<bytes.length){const length=bytes.readUInt32LE(offset),kind=bytes.readUInt32LE(offset+4);if(kind===0x004e4942)bin=bytes.subarray(offset+8,offset+8+length);offset+=length+8;}
  const stem=path.basename(file,'.glb');await fs.mkdir('public/assets/textures',{recursive:true});
  if(bin){await fs.writeFile(`public/assets/models/${stem}.bin`,bin);json.buffers[0].uri=`${stem}.bin`;}
  for(let i=0;i<(json.images??[]).length;i++){const image=json.images[i];if(image.bufferView!==undefined){const v=json.bufferViews[image.bufferView],extension=image.mimeType==='image/jpeg'?'jpg':'png';const imageName=`${stem}-${i}.${extension}`;await fs.writeFile(`public/assets/textures/${imageName}`,bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength));image.uri=`../textures/${imageName}`;delete image.bufferView;}}
  const gltf=file.replace(/\.glb$/,'.gltf');await fs.writeFile(gltf,JSON.stringify(json));record.url=gltf.replace('public/','');record.glb=info;
 }else if(ext==='.png'&&bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Invalid image magic');
 record.status='available';
 }catch(e){record.error=e.message;}
 records.push(record);
}
for(const name of ['shot','blast','alert']){const file=`public/assets/audio/${name}.wav`;const bytes=await fs.readFile(file);records.push({id:'audio.'+name,kind:'audio',status:'available',url:file.replace('public/',''),packedFile:file,required:true,animations:[],bytes:bytes.length});}
await fs.mkdir('src/assets',{recursive:true});await fs.writeFile('src/assets/runtime.generated.ts','// Generated by tools/prepare-assets.mjs. Local assets are never committed.\nexport const RUNTIME_ASSETS = '+JSON.stringify(records,null,2)+';\n');
await fs.mkdir('reports/local',{recursive:true});await fs.writeFile('reports/local/runtime-assets.json',JSON.stringify(records,null,2));
console.log(`Prepared ${records.filter(r=>r.status==='available').length}/${records.length} assets; ${records.filter(r=>r.required&&r.status==='missing').length} required missing.`);
