import fs from 'node:fs/promises';
import path from 'node:path';
import {RUNTIME_ASSETS,filename} from './runtime-catalog.mjs';
import {inspectGlb} from './glb-inspect.mjs';
import './generate-audio.mjs';
import {SC2_AUDIO} from './sc2-audio-catalog.mjs';
const records=[];
let imported=[];try{imported=JSON.parse(await fs.readFile('assets/private/m3-pack.json','utf8')).manifest;}catch{}
const importedById=new Map(imported.map(a=>[a.id,a]));
const assets=[...RUNTIME_ASSETS.map(a=>({...a,...importedById.get(a.id),required:a.required})),...imported.filter(a=>!RUNTIME_ASSETS.some(b=>b.id===a.id))];
for(const a of assets){const ext=a.kind==='model'?'.glb':a.kind==='icon'||a.kind==='effect-texture'?'.png':'.jpg',file=a.packedFile??filename(a,ext);let record={...a,id:a.id,kind:a.kind,status:'missing',url:file.replace('public/',''),packedFile:file,required:a.required,animations:[],bytes:0};
 try{const bytes=await fs.readFile(file);record.bytes=bytes.length;
 if(a.kind==='model'){
  const info=inspectGlb(bytes);if(info.externalResources.length)throw Error('External GLB dependencies are unsupported; provide a self-contained GLB');
  record.animations=info.animationNames;const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12)).toString());let bin;let offset=12;
  while(offset<bytes.length){const length=bytes.readUInt32LE(offset),kind=bytes.readUInt32LE(offset+4);if(kind===0x004e4942)bin=bytes.subarray(offset+8,offset+8+length);offset+=length+8;}
  const stem=path.basename(file,'.glb');await fs.mkdir('public/assets/textures',{recursive:true});
  if(bin){await fs.writeFile(path.join(path.dirname(file),`${stem}.bin`),bin);json.buffers[0].uri=`${stem}.bin`;}
  for(let i=0;i<(json.images??[]).length;i++){const image=json.images[i];if(image.bufferView!==undefined){const v=json.bufferViews[image.bufferView],extension=image.mimeType==='image/jpeg'?'jpg':'png';const imageName=`${stem}-${i}.${extension}`;await fs.writeFile(`public/assets/textures/${imageName}`,bin.subarray(v.byteOffset??0,(v.byteOffset??0)+v.byteLength));image.uri=`../textures/${imageName}`;delete image.bufferView;}}
  const gltf=file.replace(/\.glb$/,'.gltf');await fs.writeFile(gltf,JSON.stringify(json));record.url=gltf.replace('public/','');record.glb=info;
 }else if(ext==='.png'&&bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw Error('Invalid image magic');
 record.status='available';
 }catch(e){record.error=e.message;}
 records.push(record);
}
for(const name of ['shot','blast','alert']){const file=`public/assets/audio/${name}.wav`;const bytes=await fs.readFile(file);records.push({id:'audio.'+name,kind:'audio',status:'available',url:file.replace('public/',''),packedFile:file,required:true,animations:[],bytes:bytes.length});}
for(const [id,sourcePath] of SC2_AUDIO){const packedFile=`public/assets/audio/sc2/${path.basename(sourcePath)}`;const record={id,kind:'audio',status:'missing',url:packedFile.replace('public/',''),packedFile,sourcePath,required:false,animations:[],bytes:0};try{const b=await fs.readFile(packedFile);if(b.subarray(0,4).toString()!=='RIFF'||b.subarray(8,12).toString()!=='WAVE')throw Error('Invalid WAV header');record.status='available';record.bytes=b.length;}catch{}records.push(record);}
await fs.mkdir('src/assets',{recursive:true});await fs.writeFile('src/assets/runtime.generated.ts','// Generated by tools/prepare-assets.mjs. Local assets are never committed.\nexport const RUNTIME_ASSETS = '+JSON.stringify(records,null,2)+';\n');
await fs.mkdir('reports/local',{recursive:true});await fs.writeFile('reports/local/runtime-assets.json',JSON.stringify(records,null,2));
console.log(`Prepared ${records.filter(r=>r.status==='available').length}/${records.length} assets; ${records.filter(r=>r.required&&r.status==='missing').length} required missing.`);
