import fs from 'node:fs/promises';
import {createHash} from 'node:crypto';
const root='https://raw.githubusercontent.com/sc2-arcade-watcher/asset-explorer/main/site/list/';
const base='https://dist.sc2arcade.com/star-assets/';
const out='reports/local'; await fs.mkdir(out,{recursive:true});
const report={checkedAt:new Date().toISOString(),provider:base,catalogs:{},models:[],reference:{},disclaimer:'Index identity, binary validity, visual authenticity and reuse permission are separate checks.'};
async function get(url,max=30000000){const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error(`HTTP ${r.status}: ${url}`);const a=Buffer.from(await r.arrayBuffer());if(a.length>max)throw Error('Response too large');return a;}
const filters={buttons:/marine|hellion|siegetank|medivac|zergling|roach|baneling|ravager|barracks|factory|starport|spawningpool|roachwarren|banelingnest|stimpack|combatshield|infernal|medivacheal|metabolic|centrifugal/i,ui:/starcraft|sc2logo|logo.*sc2|console.*terran|terran.*console|resource.*(mineral|vespene)|minimap/i,icons:/mineral|vespene|terran|zerg|starcraft/i,consoles:/terran/i,'terrain-tilesets':/mar.sara.*(dirt|sand|rock)|char.*(ash|lava)|korhal.*(concrete|panel)|creep/i,'terrain-doodads':/mineral|vespene|rock|debris/i,art:/starcraft|logo|mar.sara|char/i,models:/^(marine|hellionex1|siegetank|medivacex1|zergling|roach|banelingex1|ravager|barracks|factory|starport|spawningpool|roachwarren|banelingnest)$|droppod|drop.pod/i};
const catalogData={};
for(const [category,filter]of Object.entries(filters)){try{const b=await get(root+category+'.json',8000000);const j=JSON.parse(b);if(!Array.isArray(j.items))throw Error('Unexpected catalog schema');catalogData[category]=j;const matches=j.items.filter(x=>filter.test(x.name));report.catalogs[category]={count:j.items.length,sha256:createHash('sha256').update(b).digest('hex'),matches:matches.slice(0,240),totalMatches:matches.length};console.log(`CATALOG ${category} ${j.items.length} items / ${matches.length} matches`);}catch(e){report.catalogs[category]={error:e.message};console.log(`CATALOG_ERROR ${category}: ${e.message}`);}}
for(const name of ['marine','hellionex1','siegetank','medivacex1','zergling','roach','banelingex1','ravager']){const item=catalogData.models?.items.find(x=>x.name===name);const row={name,indexFound:!!item};try{if(!item)throw Error('No exact index match');row.url=base+item.download.split('/').map(encodeURIComponent).join('/');const b=await get(row.url);if(b.toString('ascii',0,4)!=='glTF'||b.readUInt32LE(4)!==2||b.readUInt32LE(8)!==b.length)throw Error('Invalid GLB header');const n=b.readUInt32LE(12);if(b.readUInt32LE(16)!==0x4e4f534a||20+n>b.length)throw Error('Invalid JSON chunk');const doc=JSON.parse(b.subarray(20,20+n).toString().trim());row.bytes=b.length;row.sha256=createHash('sha256').update(b).digest('hex');row.meshes=doc.meshes?.length??0;row.skins=doc.skins?.length??0;row.images=doc.images?.length??0;row.materials=doc.materials?.length??0;row.animations=(doc.animations??[]).map(x=>x.name??'unnamed');row.externalResources=[...(doc.images??[]),...(doc.buffers??[])].filter(x=>x.uri&&!x.uri.startsWith('data:')).map(x=>x.uri);row.structurallyReadable=true;row.visualVerified=false;row.blenderVerified=false;}catch(e){row.error=e.message;row.structurallyReadable=false;}report.models.push(row);console.log('MODEL '+JSON.stringify(row));}
const target='https://starcraft-shooter-2026.pages.dev/';
try{const html=(await get(target,2000000)).toString();report.reference={url:target,htmlRetrieved:true,title:html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]??null,fontDeclarations:[...html.matchAll(/font-family\s*:\s*([^;}]+)/gi)].map(x=>x[1]),stylesheets:[...html.matchAll(/<link[^>]+href=["']([^"']+\.css[^"']*)["']/gi)].map(x=>new URL(x[1],target).href),images:[...html.matchAll(/<img[^>]+src=["']([^"']+)["']/gi)].map(x=>new URL(x[1],target).href),visualVerified:false};for(const url of report.reference.stylesheets.slice(0,8)){try{const css=(await get(url,2000000)).toString();report.reference.fontDeclarations.push(...[...css.matchAll(/font-family\s*:\s*([^;}]+)/gi)].map(x=>x[1]));}catch{}}report.reference.fontDeclarations=[...new Set(report.reference.fontDeclarations)].slice(0,30);}catch(e){report.reference={url:target,htmlRetrieved:false,error:e.message,visualVerified:false};}
await fs.writeFile(out+'/probe.json',JSON.stringify(report,null,2));console.log('REFERENCE '+JSON.stringify(report.reference));
