import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';
import {World} from '../src/simulation/world';import {campaignTerrain,MAP_THEMES} from '../src/data/campaign-map';
import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';
import {buySupport} from '../src/simulation/combat/shop-support';import {tacticalCard} from '../src/data/unique-support';
import {writeArchive,readArchive} from '../src/persistence/archive';import {shopProgress} from '../src/ui/presentation/shop-progress';
import {minimapFrame} from '../src/ui/hud/minimap';import {commandPositions} from '../src/ui/hud/command-layout';
import type {ExpeditionReward} from '../src/simulation/progression/expedition-drafts';import type {CampaignTheme} from '../src/data/campaign-landscape';
import {createGameServer} from './coze-web-server.mjs';
const out=process.env.SC2_BATTLE_QA_DIR??'reports/local/battle-ui-integration-20261008/browser';await fs.mkdir(out,{recursive:true});
const profile=new PermanentProfile(500),levels=Object.fromEntries(MVP_TALENTS.filter(t=>t.race==='terran'&&t.line==='micro'&&t.tier<=4).map(t=>[t.id,t.maxRank]));assert.ok(profile.savePresetBlueprint('terran',0,levels));assert.ok(profile.activatePreset('terran',0));
const fixtures=[];
for(const theme of Object.keys(MAP_THEMES)as CampaignTheme[]){
 const w=new World({permanentProfile:new PermanentProfile(),seed:10812,waves:false,terrain:campaignTerrain({version:3,seed:10812,theme})});assert.ok(w.permanentProfile.importJSON(profile.exportJSON()));assert.ok(w.start());shopProgress(w).observe();w.wallet={minerals:1e6,gas:1e6};w.expedition.familySlots=['medivac','marine','hellion','tank','marauder'];w.upgrades.set('stim',1);for(const f of w.expedition.familySlots){w.expedition.tech['unlock.'+f]=1;for(let n=w.familyUnits(f).length;n<5;n++)w.addFamilyMember(f,{x:(n-2)*1.5,z:0},1);}
 for(const hero of ['raynor','tychus','nova']as const)assert.ok(w.acquireHero(hero));assert.ok(buySupport(w,tacticalCard('terran')));assert.ok(buySupport(w,'strategic'));for(const plan of Object.values(w.expedition.production))plan.enabled={};w.paused=true;
 if(process.env.SC2_BATTLE_QA_STATIONARY_TARGETS==='1')for(const hero of ['raynor','tychus','nova']as const){const u=w.heroEntity(hero)!,p=w.freePosition('roach',u,2.5,4);assert.ok(p);const target=w.addUnit('roach','zerg',p.x,p.z);target.hp=target.maxHp=1e9;target.moveSpeed=0;target.nextShotAt=target.specialReady=1e9;}
 const file=path.resolve(out,theme+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun(),shopProgress:shopProgress(w).snapshot()}));fixtures.push({theme,file,frame:minimapFrame(w.terrain!.definition!,w.terrainStage)});
 if(theme==='industrial'){
  w.paused=false;w.endStage();w.skipReward();let buys=0;for(let n=0;n<200;n++){for(const r of [...w.rewards]as ExpeditionReward[]){if(buys<4&&['card','teamCard'].includes(r.expeditionEffect.kind)&&w.canChooseReward(r)){assert.ok(w.choose(r.offerId));shopProgress(w).observe();buys++;}}const effects=(w.rewards as ExpeditionReward[]).map(r=>r.expeditionEffect);if(buys===4&&effects.some(e=>e.kind==='teamCard')&&effects.some(e=>e.kind==='card'))break;assert.ok(w.reroll());}assert.equal(buys,4);await fs.writeFile(path.resolve(out,'shop.json'),writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun(),shopProgress:shopProgress(w).snapshot()}));
 }
}
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding']});
const report:any={stationaryDiagnosticTargets:process.env.SC2_BATTLE_QA_STATIONARY_TARGETS==='1',at:new Date().toISOString(),appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],captures:[],errors:[],method:'Production UI, real five-map diagnostic archives and native actions. Browser touch is not physical-device acceptance.'};let page:any,context:any;
const shot=async(name:string)=>{const file=out+'/'+name+'.png';await page.waitForTimeout(700);await page.screenshot({path:file});report.captures.push(file);};
const ready=async()=>{for(let i=0;i<10;i++){try{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:30000});break;}catch{console.log('Preparing '+(await page.evaluate(()=>window.__SC2_REPORT__().readiness)).label);}}assert.equal((await page.evaluate(()=>window.__SC2_REPORT__().readiness)).phase,'ready');};
const load=async(file:string)=>{await page.goto(url,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('.main-actions [data-action=menu-load]').click();const pick=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await pick).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();};
const click=async(selector:string)=>{const b=page.locator(selector);if(context._mobile)await b.tap();else await b.click();};
const panelClose=()=>click('.modal-footer [data-action=battle-panel-close]');
const mapCheck=async(name:string,frame:any)=>{
 const m=await page.locator('#minimap').boundingBox(),toggle=await page.locator('#map-toggle').boundingBox(),bar=await page.locator('#topbar').boundingBox(),army=await page.locator('.army-row').boundingBox();assert.ok(m&&toggle);assert.ok(Math.abs(m.width-m.height)<.5);assert.ok(m.y>=bar.y+bar.height);assert.ok(m.y+m.height<army.y);assert.equal(toggle.width,22);assert.equal(toggle.height,22);
 const pixels=await page.locator('#minimap-canvas').evaluate((c:HTMLCanvasElement)=>{const d=c.getContext('2d')!.getImageData(0,0,c.width,c.height).data,colors=new Set();for(let i=0;i<d.length;i+=4)colors.add(d[i]+','+d[i+1]+','+d[i+2]);return {colors:colors.size,frame:JSON.parse(c.dataset.mapFrame!)};});assert.ok(pixels.colors>5);assert.deepEqual(pixels.frame,frame);assert.equal(await page.locator('#map-toggle').innerText(),'−');await shot(name+'-map');await click('#map-toggle');assert.equal(await page.locator('#minimap-canvas').isVisible(),false);assert.equal(await page.locator('#map-toggle').innerText(),'+');assert.equal((await page.locator('#minimap').boundingBox()).width,28);await shot(name+'-map-folded');await click('#map-toggle');report.checks.push(name+' original map pixels/frame, compact independent fold');
};
try{
 for(const mobile of [true,false]){
  context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},isMobile:mobile,hasTouch:mobile,acceptDownloads:true});context._mobile=mobile;page=await context.newPage();page.on('pageerror',(e:any)=>report.errors.push(e.message));page.on('console',(m:any)=>{if(m.type()==='error')report.errors.push(m.text());});
  for(const f of fixtures){if(!mobile&&f.theme!=='industrial')continue;console.log('LOAD '+mobile+' '+f.theme);await load(f.file);await page.locator('.pause-actions [data-action=pause]').click();await mapCheck((mobile?'mobile':'desktop')+'-'+f.theme,f.frame);if(f.theme!=='industrial')continue;
   for(const size of mobile?[{width:390,height:844},{width:320,height:700},{width:844,height:390}]:[{width:1440,height:900}]){
    await page.setViewportSize(size);await page.waitForTimeout(350);const name=size.width+'x'+size.height;await mapCheck(name,f.frame);
    const positions=await page.locator('#console-commands>button').evaluateAll((ns:HTMLButtonElement[])=>ns.map(n=>{const b=n.getBoundingClientRect();return {id:n.id,x:b.x,y:b.y,width:b.width,height:b.height};}));assert.equal(positions.length,8);assert.equal(await page.locator('#unit-operations,#commands-toggle').count(),0);assert.equal(await page.locator('.empty-seat').count(),0);
    if(mobile){const d=positions.find((p:any)=>p.id==='detection')!,expected=commandPositions(positions.map((p:any)=>p.id));for(const b of positions){const p=expected.find(e=>e.id===b.id)!.point;assert.equal(b.width,44);assert.equal(b.height,44);assert.ok(Math.abs(b.x-d.x-(p[0]-50))<.5);assert.ok(Math.abs(b.y-d.y-(p[1]-50))<.5);}const joy=await page.locator('#joystick').boundingBox();assert.ok(Math.abs(joy.y+joy.height/2-d.y-22)<2);assert.equal(await page.locator('#army-toggle').evaluate((n:HTMLElement)=>getComputedStyle(n,'::before').display),'none');assert.equal(await page.locator('#army-toggle').evaluate((n:HTMLElement)=>getComputedStyle(n).clipPath),'none');assert.equal(await page.locator('#army-toggle').evaluate((n:HTMLElement)=>getComputedStyle(n.querySelector('svg')!).transform),'none');assert.equal(await page.locator('#army-toggle').evaluate((n:HTMLElement)=>getComputedStyle(n).borderRadius),'50%');}
    else assert.ok(positions.every((p:any)=>p.y===positions[0].y));
    if(mobile){for(const b of await page.locator('#roster button').all()){const r=await b.boundingBox();assert.ok(r.width>=44&&r.width<=48.1);assert.equal(r.height,30);}if(size.width>size.height)assert.ok((await page.locator('.army-row').boundingBox()).height<=47);}const expanded=await page.locator('#army-toggle').getAttribute('aria-expanded');await shot(name+'-roster-'+(expanded==='true'?'expanded':'folded'));await click('#army-toggle');assert.equal(await page.locator('#army-toggle').getAttribute('aria-expanded'),expanded==='true'?'false':'true');await shot(name+'-roster-'+(expanded==='true'?'folded':'expanded'));await click('#army-toggle');assert.equal(await page.locator('#army-toggle').getAttribute('aria-expanded'),expanded);report.checks.push(name+' clockwise mobile / horizontal desktop skills, roster follows fold');if(mobile){const unit=page.locator('#roster [data-battle-action=hellion-mode]').first(),b=await unit.boundingBox(),cdp=await context.newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await page.waitForTimeout(550);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(150);await cdp.detach();await page.locator('.ui12-window[data-unit-identity=hellion]').waitFor();await shot(name+'-ordinary-release');await click('.ui12-close');report.checks.push(name+' long-press release stays on the intended ordinary unit');}
   }
   if(mobile)await page.setViewportSize({width:390,height:844});
   if(process.env.SC2_BATTLE_QA_STATIONARY_TARGETS==='1'){await load(fixtures[0].file);await click('.pause-actions [data-action=pause]');}
   await click('#topbar [data-action=battle-base]');assert.deepEqual(await page.locator('[data-action=ui-production-tab]').allTextContents(),['设施','训练','当前科技']);assert.equal(await page.locator('.feedback-facility-card').count(),3);await shot((mobile?'mobile':'desktop')+'-facilities');await click('[data-action=ui-production-tab][data-tab=technology]');assert.ok(await page.locator('[data-unlocked=false]').count());await shot((mobile?'mobile':'desktop')+'-technology');await click('[data-action=ui-production-tab][data-tab=production]');assert.equal(await page.locator('[data-setting=development-target]').count(),0);await shot((mobile?'mobile':'desktop')+'-training');await panelClose();
   const stim=page.locator('#roster [data-battle-action=stim]').first();assert.ok((await stim.getAttribute('class')).includes('skill-ready'));if(mobile)await stim.tap();else await stim.click();await page.waitForFunction(()=>![...document.querySelectorAll('#roster [data-battle-action=stim]')].some(n=>n.classList.contains('skill-ready')));assert.equal(await page.locator('.ui12-window').count(),0);
   const ordinary=page.locator('#roster [data-battle-action=hellion-mode]').first();if(mobile){const cdp=await context.newCDPSession(page),b=await ordinary.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+b.width/2,y:b.y+b.height/2}]});await page.waitForTimeout(550);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else await ordinary.click({button:'right'});await page.locator('.ui12-window[data-unit-identity=hellion]').waitFor();await shot((mobile?'mobile':'desktop')+'-ordinary-detail');await click('.ui12-close');
   if(mobile){await page.evaluate(()=>{(window as any).__QA_POINTERS=[];for(const name of ['pointerdown','pointermove','pointerup','pointercancel','lostpointercapture'])document.addEventListener(name,(e:Event)=>{const p=e as PointerEvent;(window as any).__QA_POINTERS.push({type:p.type,id:p.pointerId,x:p.clientX,y:p.clientY,target:(p.target as HTMLElement).closest('[data-seat]')?.getAttribute('data-seat')});},true);});const before=await page.locator('#roster button').evaluateAll((ns:HTMLElement[])=>ns.map(n=>n.dataset.seat)),b=await page.locator('#roster').boundingBox(),cdp=await context.newCDPSession(page);const swipe=async(reverse=false)=>{const seat=await page.locator('#roster button').nth(reverse?0:4).boundingBox(),x=seat.x+seat.width/2,end=x+(reverse?120:-120),y=seat.y+22;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:end,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(600);};await swipe();assert.notDeepEqual(await page.locator('#roster button').evaluateAll((ns:HTMLElement[])=>ns.map(n=>n.dataset.seat)),before);assert.equal(await page.locator('.ui12-window').count(),0);await shot('mobile-roster-next-page');await swipe(true);assert.deepEqual(await page.locator('#roster button').evaluateAll((ns:HTMLElement[])=>ns.map(n=>n.dataset.seat)),before);await cdp.detach();}report.checks.push((mobile?'mobile':'desktop')+' ordinary native shared skill and details'+(mobile?', swipe pages':''));
   const hero=page.locator('#hero-slot-0');if(mobile){const cdp=await context.newCDPSession(page),b=await hero.boundingBox();await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:b.x+22,y:b.y+22}]});await page.waitForTimeout(550);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else await hero.click({button:'right'});await page.locator('.ui12-window[data-unit-identity=raynor]').waitFor();await shot((mobile?'mobile':'desktop')+'-hero-detail');await click('.ui12-close');await click('#hero-slot-0');assert.ok((await page.locator('#hero-slot-0 .command-cooldown').innerText()).length>0);report.checks.push((mobile?'mobile':'desktop')+' hero detail and native cast');
  }
  await load(path.resolve(out,'shop.json'));await page.locator('#reward-cards').waitFor();await page.waitForTimeout(900);
  assert.ok(await page.locator('#reward-cards .im-card-progress').count()>=2);for(const c of await page.locator('#reward-cards .im-card').all()){const txt=await c.innerText();assert.doesNotMatch(txt,/不解锁持续生产|已付批次|保持原进度/);const progress=c.locator('.im-card-progress');if(await progress.count()){const a=await progress.boundingBox(),b=await c.locator('.im-card-price').boundingBox();const copy=await c.locator('.im-card-copy').boundingBox(),bottom=await c.locator('.im-card-bottom').boundingBox();assert.ok(a.y+a.height<=copy.y+copy.height+1,JSON.stringify({a,copy}));assert.ok(copy.y+copy.height<=bottom.y+1,JSON.stringify({copy,bottom}));assert.ok(a.y+a.height+6<=bottom.y+1,JSON.stringify({a,bottom}));assert.equal(await c.locator('.painted-art').count(),1);}}
  const researchButton=await page.locator('.feedback-progress-strip [data-action=battle-research]').boundingBox(),progressButton=await page.locator('.feedback-progress-strip [data-action=battle-progress]').boundingBox(),strip=await page.locator('.feedback-progress-strip').boundingBox();assert.ok(progressButton.x-researchButton.x-researchButton.width<12);assert.equal(researchButton.y,progressButton.y);assert.ok(strip.x+strip.width-progressButton.x-progressButton.width<20);assert.equal(await page.locator('.feedback-progress-strip').evaluate((n:HTMLElement)=>getComputedStyle(n).borderTopWidth),'0px');await shot((mobile?'mobile':'desktop')+'-shop-card-progress');await click('.feedback-progress-strip [data-action=battle-progress]');await click('[data-action=battle-progress-tab][data-tab=sources]');assert.equal(await page.locator('.feedback-source-card').count(),4);await shot((mobile?'mobile':'desktop')+'-purchases');await panelClose();await click('.feedback-progress-strip [data-action=battle-research]');assert.equal(await page.locator('.feedback-source-card').count(),0);assert.equal(await page.locator('.feedback-research-line').count(),3);await shot((mobile?'mobile':'desktop')+'-separate-research');await panelClose();report.checks.push((mobile?'mobile':'desktop')+' card copy/count/art, original purchased receipts and separate research');await context.close();context=null;
 }
 assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.pointers=await page.evaluate(()=>(window as any).__QA_POINTERS);report.html=await page.locator('body').innerText();await shot('failure');}}
finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await context?.close();await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks.length,captures:report.captures.length,errors:report.errors,failure:report.failure??null}));}
