import {ELITES} from '../src/data/elites';
import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {createGameServer} from './coze-web-server.mjs';
import {RUN_SCHEMA} from '../src/simulation/persistence/run-snapshot';
import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {FAMILIES_BY_RACE,type Race} from '../src/data/races';import {HERO_IDS_BY_RACE} from '../src/data/heroes';
import {buySupport,type SupportCard} from '../src/simulation/combat/shop-support';import {UNIQUE_SUPPORT} from '../src/data/unique-support';import {initializeCarrierSubsystem} from '../src/simulation/combat/carriers';
const offline=process.argv.includes('--offline'),inspectAll=process.env.SC2_UI_INSPECT_ALL==='1';
const out=(process.env.SC2_QA_DIR??'reports/local/current-logic-20261006')+'/'+(offline?'offline':'web');await fs.mkdir(out,{recursive:true});
const fixtures=[];
for(const race of ['terran','zerg','protoss'] as Race[])for(let group=0;group<(inspectAll&&race==='terran'?3:2);group++){
 const w=new World({race,seed:10607,waves:false,terrain:campaignTerrain(chooseCampaignMap(10607))});w.start();if(inspectAll){for(let i=1;i<16;i++){w.endStage();assert.ok(w.skipReward());assert.ok(w.skipReward());}}w.entities.clear();w.heroes.clear();w.pods=[];w.expedition.ledger=[];w.expedition.zerglingPairs=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.time=10;w.tick=600;w.wallet={minerals:10000,gas:10000};for(const p of Object.values(w.expedition.production))p.enabled={};
 const families=group===2?['reaper'] as typeof FAMILIES_BY_RACE[typeof race][number][]:FAMILIES_BY_RACE[race].slice(group*5,group*5+5),heroes=HERO_IDS_BY_RACE[race].slice(group*3,group*3+3);w.expedition.familySlots=[...families];
 for(const key of ['storm','charge','blink'])w.expedition.tech[key]=1;
 for(const family of families){w.expedition.tech['unlock.'+family]=1;const p=w.freePosition(family,w.anchor,1,6);assert.ok(p);const u=w.addFamilyMember(family,p,3);if(family==='lurker'){u.nativeMode=u.desiredNativeMode='lurker_burrowed';w.refreshStats(u,true);}u.energy=u.maxEnergy;u.hp*=.65;if(u.shield)u.shield*=.6;const air=['viking','phoenix','corruptor'].includes(family),q=w.freePosition(air?'mutalisk':'roach',u,1.5,6);assert.ok(q);const target=w.addUnit(air?'mutalisk':'roach','zerg',q.x,q.z);target.hp=target.maxHp=2e6;target.armor=0;target.specialReady=target.nextShotAt=1e9;target.moveSpeed=0;}
 for(const hero of heroes)assert.ok(w.acquireHero(hero));
 if(inspectAll)for(const elite of Object.values(ELITES).filter(e=>families.includes(e.family as never)&&!(group===2&&e.id==='reaper.3')))for(let rank=1;rank<=3;rank++)assert.ok(w.acquireElite(elite.id),elite.id);
 if(!inspectAll&&race==='terran')for(const id of ['hellion.3','medivac.2','science_vessel.1'] as const)if(families.includes(id.split('.')[0] as never))assert.ok(w.acquireElite(id));
 for(const id of ['mines','bombardment','strategic',...Object.entries(UNIQUE_SUPPORT).filter(([,v])=>v.race===race).map(([id])=>id)]as SupportCard[])for(let i=0;i<3;i++)buySupport(w,id);
 if(families.includes(race==='terran'?'marine':race==='zerg'?'hydralisk':'stalker'))for(let i=0;i<3;i++)assert.ok(buySupport(w,'mutation'));
 initializeCarrierSubsystem(w);w.hash.rebuild(w.entities.values());w.stageStartedAt=w.time;for(let i=0;i<30;i++){w.stageElapsed=0;w.step();}w.paused=true;
 const before=w.captureRun(),clone=new World({race});clone.restoreRun(before);const name=race+'-'+group,file=path.resolve(out,name+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:before}));const oldFile=path.resolve(out,name+'-unsupported-schema23.json');await fs.writeFile(oldFile,writeArchive({profile:w.permanentProfile.exportJSON(),run:{...before,schema:23} as typeof before}));fixtures.push({race,group,families,heroes,name,file,oldFile,before});
}
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=offline?null:await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files','--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding']});
const report:any={method:(inspectAll?'All-identity inspector diagnostics use original stage16 duration through scripted public World transitions, not natural campaign acceptance. ':'')+(offline?'Offline checks use a fresh normal Chrome profile per group; earlier private-context Blob failures remain recorded. ':'')+'Production UI imports six diagnostic World archives covering all30 ordinary families/all18 heroes, real support and actual child identities; export/save/reload/local-load. Browser keyboard, touch and virtual gamepad are engineering checks, not physical device acceptance.',offline,appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],errors:[]};let page:any,activeOfflineContext:any=null;
const state=(s:any)=>encodeGraph({time:s.time,wallet:s.wallet,units:s.entities,heroes:s.heroes,flights:s.weaponFlights,support:s.expedition.support,spells:s.expedition.spells,ledger:s.expedition.ledger,pairs:s.expedition.zerglingPairs,terran:s.terranElites,zerg:s.zergElites,protoss:s.protossElites,auras:s.teamAuras,eliteSupport:s.eliteSupport});
const ready=async()=>{const started=Date.now();for(;;){try{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:30000});break;}catch(error){console.log('readiness progress '+JSON.stringify((await page.evaluate(()=>window.__SC2_REPORT__())).readiness));if(Date.now()-started>=240000)throw error;}}const r=(await page.evaluate(()=>window.__SC2_REPORT__())).readiness;assert.equal(r.phase,'ready',r.error??r.label);};
const exported=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
try{for(const f of fixtures){if(process.env.SC2_UI_GROUP&&f.name!==process.env.SC2_UI_GROUP)continue;const mobile=f.race==='zerg',options={viewport:mobile?{width:390,height:844}:{width:1440,height:900},hasTouch:mobile,isMobile:mobile,acceptDownloads:true},profile=offline?await fs.mkdtemp(path.resolve('.cache/ui-offline-final-')):null,context=offline?await chromium.launchPersistentContext(profile!,{...options,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files','--disable-background-timer-throttling','--disable-backgrounding-occluded-windows','--disable-renderer-backgrounding']}):await browser!.newContext(options);if(profile){report.profiles??=[];report.profiles.push(profile);activeOfflineContext=context;}if(offline)await context.setOffline(true);
 await context.addInitScript({content:`const pad={id:'P4 QA standard controller',index:0,mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({value:0,pressed:false,touched:false}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[pad]});window.__P4_PAD__=pad;`});page=offline?(context.pages()[0]??await context.newPage()):await context.newPage();await page.bringToFront();page.on('request',(r:any)=>{if(offline&&r.url().includes('/api/'))report.errors.push('Unexpected offline API request');});page.on('pageerror',(e:any)=>report.errors.push(e.message));page.on('requestfailed',(r:any)=>{report.networkFailures??=[];report.networkFailures.push({url:r.url().slice(0,180),failure:r.failure()?.errorText});});
 await page.goto(offline?pathToFileURL(path.resolve('dist/SC2-Survivors-Current-20261006.html')).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');assert.equal(await page.evaluate(()=>localStorage.getItem('sc2.telemetry.identity.v1')),null);
 if(f.group===0){
  await page.locator('[data-action=menu-new]').click();await page.locator('[data-action=menu-race][data-race='+f.race+']').click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();await page.locator('[data-action=menu-start]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().time>.2);await page.locator('#topbar [data-action=pause]').click();const fresh=await exported();assert.equal(fresh.schema,RUN_SCHEMA);assert.equal(fresh.config.race,f.race);assert.equal(fresh.config.frozenTalents.allocated,0);await page.screenshot({path:out+'/'+f.race+'-new-game.png'});await page.locator('[data-action=restart]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='menu');
 }
 await page.locator('.main-actions [data-action=menu-load]').click();const rejected=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await rejected).setFiles(f.oldFile);await page.locator('[role=alert]').filter({hasText:'续局版本不兼容'}).waitFor();assert.equal(await page.locator('[data-action=menu-load-ready]').count(),0);assert.equal(await page.evaluate(()=>window.__SC2_REPORT__().phase),'menu');assert.equal(await page.locator('[data-action*=legacy]').count(),0);
 const picker=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await picker).setFiles(f.file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 const initial=await exported();assert.equal(initial.schema,RUN_SCHEMA);assert.deepEqual(state(initial.state),state(f.before.state));let r=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(r.nonHeroes.ready);assert.deepEqual(r.errors,[]);
 await page.locator('.pause-actions [data-action=pause]').click();const t=r.time;let control='buttons';
 if(f.race==='terran'){control='keyboard';await page.keyboard.down('w');}
 if(f.race==='protoss'){control='virtual standard gamepad';await page.evaluate(()=>{(window as any).__P4_PAD__.axes[0]=.8;});}
 if(mobile){control='browser touch';const b=await page.locator('#joystick').boundingBox();assert.ok(b);const cdp=await context.newCDPSession(page),x=b.x+b.width/2,y=b.y+b.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+24,y:y-10}]});await page.waitForTimeout(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
 await page.waitForFunction((t:number)=>window.__SC2_REPORT__().time>t+1.5,t,{timeout:30000});await page.keyboard.up('w');await page.evaluate(()=>{(window as any).__P4_PAD__.axes[0]=0;});await page.screenshot({path:out+'/'+(offline?'offline-':'')+f.name+'-battle.png',fullPage:true});
 if(inspectAll){
  const identities=new Set<string>();await page.locator('[data-seat]').first().click();await page.locator('[data-inspect-tab=army]').click();const keys=await page.locator('.ui12-full-roster [data-inspect-seat]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.inspectSeat!));
  for(const key of keys){await page.locator('[data-inspect-tab=army]').click();await page.locator(`.ui12-full-roster [data-inspect-seat="${key}"]`).click();await page.locator('.ui12-tabs [data-inspect-tab=abilities]').click();const identity=await page.locator('.ui12-window[data-unit-identity]').getAttribute('data-unit-identity'),rank=await page.locator('.ui12-window[data-unit-rank]').getAttribute('data-unit-rank');if(rank!=='0'&&identity)identities.add(identity);assert.ok(!(await page.locator('#unit-inspector').innerText()).includes('NaN'));}
  for(const e of Object.values(ELITES).filter(e=>f.families.includes(e.family as never)&&!(f.group===2&&e.id==='reaper.3')&&!(f.group!==2&&['reaper.1','reaper.2'].includes(e.id))))assert.ok(identities.has(e.id),'Inspector missing '+e.id);for(const id of f.heroes)assert.ok(identities.has(id));await page.locator('.ui12-close[data-inspect-close]').click();report.inspections??=[];report.inspections.push({group:f.name,identities:[...identities]});
 }
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=pause-saves]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exported();assert.ok(after.state.time>f.before.state.time);assert.ok(after.state.stats.damage>f.before.state.stats.damage||after.state.stats.healed>f.before.state.stats.healed);
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('.main-actions [data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exported();assert.deepEqual(state(loaded.state),state(after.state));assert.equal(loaded.state.paused,true);
 report.checks.push({race:f.race,group:f.group,families:f.families,heroes:f.heroes,control,schema:loaded.schema,damage:after.state.stats.damage-f.before.state.stats.damage,healed:after.state.stats.healed-f.before.state.stats.healed,saveRestored:true,worldPreserved:true,unsupportedSaveRejected:true,newGameChecked:f.group===0,debugApi:false});console.log(f.name+': production UI passed');await context.close();activeOfflineContext=null;}if(inspectAll){const ids=new Set(report.inspections.flatMap((i:any)=>i.identities));for(const id of Object.keys(ELITES))assert.ok(ids.has(id),'Missing global inspector identity '+id);report.eliteCoverage=90;}assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/'+(offline?'offline-':'')+'failure.png'}).catch(()=>{});}}
finally{await fs.writeFile(out+'/'+(offline?'offline':'web')+'.json',JSON.stringify(report,null,2));await activeOfflineContext?.close();await browser?.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks.length,errors:report.errors,failure:report.failure??null}));}
