import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';
import {World} from '../src/simulation/world';import {campaignTerrain,MAP_THEMES} from '../src/data/campaign-map';import {campaign18Schedule,campaign18StageConfig} from '../src/data/campaign18';
import {openTalentLoot} from '../src/simulation/expedition-economy';import {writeArchive} from '../src/persistence/archive';import {createGameServer} from './coze-web-server.mjs';
const out=process.env.SC2_SCENARIOS_QA_DIR??'reports/local/entry-fixes-20261009/scenarios-r6';await fs.mkdir(out,{recursive:true});
const make=(theme='industrial')=>{const w=new World({race:'terran',waves:false,seed:41,terrain:campaignTerrain({version:3,seed:41,theme:theme as never})});assert.ok(w.start());for(const p of Object.values(w.expedition.production))p.enabled={};return w;};
const files:Record<string,string>={};async function save(name:string,w:World){w.paused=true;const file=path.resolve(out,name+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));files[name]=file;}
for(const theme of Object.keys(MAP_THEMES))await save('map-'+theme,make(theme));
const talent=make();talent.expedition.talentLootReceipts.push('entry-layout:talent');assert.ok(openTalentLoot(talent,'entry-layout:talent','orange'));await save('talent-loot',talent);
const win=make();win.stage=18;win.prepareStage();win.hive!.hp=0;const event=campaign18Schedule(campaign18StageConfig(18,win.difficulty),41).specials[0],boss=(win as any).spawnCampaignSpecial(event);assert.ok(boss);win.hit(boss,1e9,[],1,'terran');win.stageElapsed=win.duration;win.endStage();assert.equal(win.phase,'won');await save('won',win);
const lost=make();for(const u of lost.allies())lost.hit(u,1e9,[],1,'zerg');lost.step();assert.equal(lost.phase,'lost');await save('lost',lost);
const server=createGameServer({webRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();page.setDefaultTimeout(25000);
const report:any={build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Current-schema generated five-map/final-boss/decision fixtures, native UI entry and transitions. Not natural campaigns or performance acceptance.',checks:[],screens:[],records:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
async function shot(name:string){await page.waitForTimeout(300);const geometry=await page.locator('#overlay button:visible').evaluateAll(es=>es.map(e=>({text:e.textContent,action:e.getAttribute('data-action'),r:e.getBoundingClientRect().toJSON()})));report.records.push({name,geometry});await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);console.log(name);}
async function ready(){await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness.phase),null,{timeout:300000});const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.readiness.phase,'ready',JSON.stringify(r.readiness));assert.deepEqual(r.errors,[]);assert.equal(r.assetsPending,0);await page.locator('[data-action=flow-continue]').click();}
async function load(name:string){await page.setViewportSize({width:1440,height:900});await page.goto('http://127.0.0.1:'+(server.address()as any).port,{timeout:300000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:300000});await page.locator('.main-actions [data-action=menu-load]').click();const c=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await c).setFiles(files[name]);await page.locator('[data-action=menu-load-ready]').click();await ready();}
async function matrix(name:string){for(const [width,height]of [[1440,900],[844,390],[320,640]]){await page.setViewportSize({width,height});await page.evaluate(()=>document.documentElement.style.setProperty('--text-scale','1.5'));await page.waitForTimeout(300);for(const e of await page.locator('#overlay [data-action]:visible').all()){await e.scrollIntoViewIfNeeded();const b=await e.boundingBox();assert.ok(b&&b.x>=-.6&&b.x+b.width<=width+.6&&b.y>=-.6&&b.y+b.height<=height+.6,name+': reachable action '+await e.getAttribute('data-action'));}await shot(name+'-'+width);}await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>document.documentElement.style.setProperty('--text-scale','1'));}
try{
 for(const theme of Object.keys(MAP_THEMES)){await load('map-'+theme);assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).phase,'battle');await page.locator('.pause-actions [data-action=pause]').click();await shot('map-'+theme);const r=await page.evaluate(()=>window.__SC2_REPORT__());report.checks.push({map:theme,rendered:r.map,errors:r.errors,pending:r.assetsPending});assert.deepEqual(r.errors,[]);assert.equal(r.assetsPending,0);}
 await load('talent-loot');await matrix('talent-loot');assert.ok(await page.locator('[data-action=talent-loot]:visible').count());report.checks.push('Free talent decision content and actions reachable');
 await load('lost');await matrix('lost');report.checks.push('Defeat actions reachable');
 await load('won');await matrix('won');await page.locator('[data-action=endless]:visible').click();await matrix('endless-construction');await page.locator('.reward-actions [data-action=skip]').click();await matrix('endless-shop');await page.locator('.reward-actions [data-action=skip]').click();await matrix('endless-ready');
 await page.locator('[data-action=endless-prepare]:visible').click();await ready();const endless=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(endless.phase,'battle');assert.ok(endless.endless);assert.deepEqual(endless.errors,[]);assert.equal(endless.assetsPending,0);await shot('endless-entered');report.checks.push('Native won → endless preparation → shop → original flat battlefield');
 await load('won');await page.locator('[data-action=evacuate]:visible').click();await matrix('finished');report.checks.push('Evacuation ending reachable');assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{report.finalBuild=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8'));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks.length,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
