import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';import {writeArchive} from '../src/persistence/archive';
const baseline=process.argv.includes('--baseline'),offline=process.argv.includes('--offline'),out=process.env.SC2_ENTRY_QA_DIR??`reports/local/entry-fixes-20261009/${baseline?'baseline':offline?'offline':'web'}`;await fs.mkdir(out,{recursive:true});
const races=baseline||offline?['terran']:['terran','zerg','protoss'];const fixtures:any={};
for(const race of races){const w=new World({race:race as any,seed:529,waves:false,terrain:campaignTerrain({version:3,seed:529,theme:'industrial'})});assert.ok(w.start());for(const plan of Object.values(w.expedition.production))plan.enabled={};
 const family=w.allies()[0].unitType,pod=w.spawnPod(family,{x:6,z:0});w.landPod(pod);pod.hp=pod.maxHp*.55;for(const e of [...w.entities.values()])if(e.owner==='zerg')w.entities.delete(e.id);
 fixtures[race]={};for(const mode of ['pod','building','shop']){if(mode==='building')w.endStage();if(mode==='shop')w.skipReward();const file=path.resolve(out,`${race}-${mode}.json`);await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));fixtures[race][mode]=file;}
}
const server=offline?null:createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});if(server)await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const file=process.env.SC2_ENTRY_HTML??'dist/SC2-Survivors-Entry-Fixes-20261009.html',url=offline?pathToFileURL(path.resolve(file)).href:'http://127.0.0.1:'+(server!.address()as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files','--disable-background-timer-throttling','--disable-renderer-backgrounding']});const context=await browser.newContext({viewport:{width:1440,height:900}});if(offline)await context.setOffline(true);const page=await context.newPage();page.setDefaultTimeout(30000);
const report:any={build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),baseline,offline,method:'Current-schema native fixtures; Chrome headless diagnostic wall-clock measurements, not natural/physical/performance acceptance.',checks:[],screens:[],geometry:[],loads:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
async function shot(name:string){await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);}
async function load(race:string,mode:string,reload=true){if(reload){await page.goto(url,{timeout:300000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:300000});}
 await page.locator('.main-actions [data-action=menu-load]').click();const pick=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await pick).setFiles(fixtures[race][mode]);
 await page.evaluate(`(()=>{window.__entrySamples=[];const start=performance.now();window.__entryTimer=setInterval(()=>{const r=window.__SC2_REPORT__?.(),s=r?.readiness;if(!s?.kind)return;const percent=Number(document.querySelector('.loading-progress')?.getAttribute('aria-valuenow'));const stage=[...document.querySelectorAll('.load-stages>span')].map(e=>e.className).join('|');const a=window.__entrySamples,last=a.at(-1);if(!last||last.phase!==s.phase||last.percent!==percent||last.stage!==stage)a.push({ms:performance.now()-start,phase:s.phase,stage,percent,prepared:r.embeddedAssets?.prepared,downloadBytes:r.embeddedAssets?.downloadBytes});},25)})()`);
 await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:300000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready',JSON.stringify((await page.evaluate(()=>window.__SC2_REPORT__())).readiness));
 const samples=await page.evaluate(`(()=>{clearInterval(window.__entryTimer);return window.__entrySamples})()`);report.loads.push({race,mode,reload,samples,report:await page.evaluate(()=>window.__SC2_REPORT__())});
 if(!baseline){const visible=samples.filter((s:any)=>s.stage);for(let i=1;i<visible.length;i++)assert.ok(visible[i].percent>=visible[i-1].percent,'loading percent must not retreat');const steps=visible.map((s:any)=>s.stage.split('|').filter((c:string)=>c==='done').length);for(let i=1;i<steps.length;i++)assert.ok(steps[i]>=steps[i-1],'completed loading stages must not retreat');}
 await page.locator('[data-action=flow-continue]').click();await page.waitForTimeout(250);
}
const sizes=[[1440,900],[1194,985],[390,844],[844,390],[320,640]];
try{
 for(const race of races){await load(race,'building');for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.evaluate(()=>{document.documentElement.style.setProperty('--text-scale','1.5');document.querySelector('#overlay')!.scrollTop=0;});await page.waitForTimeout(150);
  const geo=await page.locator('.reward-actions [data-action=skip]').evaluate(e=>({bounds:e.getBoundingClientRect().toJSON(),viewport:[innerWidth,innerHeight],text:e.textContent}));report.geometry.push({race,mode:'building',...geo});if(!baseline)assert.ok(geo.bounds.top>=0&&geo.bounds.bottom<=height+.5);await shot(`${race}-building-${width}`);}
 await page.locator('.reward-actions [data-action=skip]').click();await page.locator('[aria-label="商店选项"]').waitFor();
 for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.evaluate(()=>{document.querySelector('#overlay')!.scrollTop=0;});await page.waitForTimeout(150);const geo=await page.locator('.reward-actions [data-action=skip]').evaluate(e=>({bounds:e.getBoundingClientRect().toJSON(),viewport:[innerWidth,innerHeight],text:e.textContent}));report.geometry.push({race,mode:'shop',...geo});if(!baseline){assert.ok(geo.bounds.top>=0&&geo.bounds.bottom<=height+.5);assert.match(geo.text??'',/返回前线/);}await shot(`${race}-shop-${width}`);}
 await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>document.documentElement.style.setProperty('--text-scale','1'));await page.locator('.reward-actions [data-action=skip]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().stage===2&&window.__SC2_REPORT__?.().phase==='battle',null,{timeout:300000});report.checks.push(race+': native construction → shop → stage 2');
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=restart]').click();await page.locator('[data-action=menu-new]').click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();
 for(const [width,height]of sizes){await page.setViewportSize({width,height});await page.locator('.departure-notice').scrollIntoViewIfNeeded();await shot(`${race}-save-notice-${width}`);if(!baseline){assert.match(await page.locator('.departure-notice').innerText(),/新游戏将覆盖当前续局/);const e=await page.locator('.departure-notice').evaluate(e=>({x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right,scroll:e.scrollWidth,client:e.clientWidth}));assert.ok(e.x>=0&&e.right<=width+.5&&e.scroll<=e.client+1);}}
 await page.setViewportSize({width:1440,height:900});await load(race,'pod');if(await page.locator('.pause-actions [data-action=pause]').isVisible())await page.locator('.pause-actions [data-action=pause]').click();await page.locator('.pod-world-label:visible').first().waitFor();
 const health=await page.locator('.pod-world-label:visible .carrier-vital').first().evaluate(e=>{const r=e.getBoundingClientRect(),i=e.querySelector('i')!,b=i.getBoundingClientRect();return {outer:r.toJSON(),inner:b.toJSON(),margin:getComputedStyle(i).marginTop,label:e.getAttribute('aria-label')};});report.geometry.push({race,health});if(!baseline){assert.ok(health.inner.y>=health.outer.y&&health.inner.bottom<=health.outer.bottom+.5);assert.ok(health.inner.width>0&&health.inner.width<health.outer.width);assert.match(health.label??'',/生命/);}await shot(race+'-pod-health');report.checks.push(race+': carrier health and formal save notice');
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=restart]').click();await load(race,'shop',false);report.checks.push(race+': repeat readiness');
 }
 assert.deepEqual(report.errors,[]);assert.deepEqual((await page.evaluate(()=>window.__SC2_REPORT__())).errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{report.final=await page.evaluate(()=>window.__SC2_REPORT__?.()).catch(()=>null);await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();if(server)await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
