import {chromium} from '@playwright/test';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {readArchive} from '../src/persistence/archive';
const out='reports/local/qa-feedback-offline';await fs.mkdir(out,{recursive:true});
const report:any={at:new Date().toISOString(),scope:'Synthetic current-schema fixture exported by the development UI, then actual offline shipping UI. Not natural campaign or human acceptance.',checks:[],errors:[],network:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const source=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true}),dev=await source.newPage();
 dev.on('pageerror',e=>report.errors.push(String(e)));await dev.goto('http://127.0.0.1:5173/');await dev.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});
 for(const action of ['menu-new','menu-race-next','menu-difficulty-next','menu-start'])await dev.locator(`[data-action=${action}]`).click();await dev.waitForFunction(()=>window.__SC2_REPORT__().readiness.phase==='ready',null,{timeout:240000});await dev.locator('[data-action=flow-continue]').click();
 await dev.evaluate(()=>{const w=window.__SC2_DEBUG__.world;window.__SC2_DEBUG__.speed=0;w.autoWaves=false;w.wallet={minerals:20000,gas:20000};w.stage=3;w.prepareStage();const boss=w.spawnCampaignSpecial(w.specialPlan[0]);const random=w.random;w.random=()=>.5;w.hit(boss,1e9,[],1,'terran');w.random=random;w.stageElapsed=w.duration;w.endStage();w.closeBossLoot();w.setDevelopmentDirection('barracks');w.skipReward();});
 const [download]=await Promise.all([dev.waitForEvent('download'),dev.locator('[data-action=save-export]').click()]);await download.saveAs(out+'/fixture.json');const before=readArchive(await fs.readFile(out+'/fixture.json','utf8')).bundle.run!;assert.equal(before.schema,7);assert.equal(before.state.expedition.bossLootQueue.length,1);await source.close();
 const offline=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,acceptDownloads:true,offline:true}),page=await offline.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('request',r=>{if(/^https?:/.test(r.url()))report.network.push(r.url());});
 await page.goto(pathToFileURL(path.resolve('dist/SC2-Survivors-Demo.html')).href,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await page.locator('[data-action=menu-load]').tap();const [chooser]=await Promise.all([page.waitForEvent('filechooser'),page.locator('[data-action=menu-load-file]').tap()]);await chooser.setFiles(out+'/fixture.json');await page.locator('[data-action=menu-load-ready]').tap();await page.waitForFunction(()=>window.__SC2_REPORT__().readiness.phase==='ready',null,{timeout:240000});await page.locator('[data-action=flow-continue]').tap();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='reward');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');
 const [loaded]=await Promise.all([page.waitForEvent('download'),page.locator('[data-action=save-export]').tap()]);await loaded.saveAs(out+'/loaded.json');const restored=readArchive(await fs.readFile(out+'/loaded.json','utf8')).bundle.run!;assert.deepEqual(restored.state.rewards,before.state.rewards);assert.deepEqual(restored.state.expedition.bossLootQueue,before.state.expedition.bossLootQueue);report.checks.push('offline import preserves paid quotes, discount and single Boss receipt at narrow viewport');
 await page.locator('[data-action=boss-loot-open]').tap();await page.locator('[data-action=boss-loot-variant]:not(:disabled)').first().tap();await page.locator('[data-action=boss-loot-claim]:not(:disabled)').first().tap();
 await page.locator('#reward-cards [data-action=reward]:not(:disabled)').first().tap();await page.locator('[data-action=reroll]').tap();await page.screenshot({path:out+'/shop-after-boss.png'});
 const [afterDownload]=await Promise.all([page.waitForEvent('download'),page.locator('[data-action=save-export]').tap()]);await afterDownload.saveAs(out+'/roundtrip.json');const after=readArchive(await fs.readFile(out+'/roundtrip.json','utf8')).bundle.run!;assert.equal(after.state.expedition.bossLootQueue.length,0);assert.equal(after.state.expedition.bossLootClaimed.length,1);assert.equal(after.state.expedition.draftClaims.length,1);assert.equal(after.state.expedition.refreshCount,1);assert.deepEqual(report.network,[]);assert.deepEqual(report.errors,[]);report.checks.push('offline original-model Boss claim, paid purchase, refresh and export settle once without network or debug API');await offline.close();
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{await browser.close();await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}
