import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';
import {encodeGraph} from '../src/persistence/graph-codec';
import {heroState} from '../src/simulation/combat/terran-hero-passives';
import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';
import {HEROES,type HeroId} from '../src/data/heroes';
import {HERO_GROUND_AURAS} from '../src/data/hero-upgrades';
const out=process.env.QA_OUT??'reports/local/hero-aura-correction-20261005/production-terran';await fs.mkdir(out,{recursive:true});
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8'));
const report:any={method:'Diagnostic snapshots created by actual World are imported through the production file-import UI in an isolated browser profile. Three simultaneous heroes per case, actual save/export/reload/load; no production debug API or live-state mutation. Separate from natural acquisition/campaign/human acceptance.',appBuildId:release.appBuildId,checks:[],errors:[]};
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});report.browser=browser.version();let page:any;
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.readiness.phase,'ready',JSON.stringify(r.readiness));};
const exportRun=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
try{
 for(const heroes of [['raynor','tychus','nova'],['swann','tosh','yamato_battlecruiser']] as HeroId[][]){
  const w=new World({race:'terran',seed:10505,waves:false,terrain:campaignTerrain(chooseCampaignMap(10505))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.time=10;w.tick=600;
  for(const p of Object.values(w.expedition.production))p.enabled={};
  for(const id of heroes){assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!;u.rank=5;w.heroes.get(id)!.rank=5;w.refreshStats(u,true);const p=w.freePosition('roach',u,3,5)!;assert.ok(p);const e=w.addUnit('roach','zerg',p.x,p.z);e.hp=e.maxHp=2e6;e.armor=0;e.stoppedUntil=1e9;e.specialReady=1e9;w.hash.rebuild(w.entities.values());if(id==='tychus')heroState(u).cycles=4;w.fire(u,e);u.stoppedUntil=1e9;}
  w.time+=.05;w.tick+=3;w.paused=true;const before=w.captureRun(),fixture=path.resolve(out,heroes[0]+'.json');await fs.writeFile(fixture,writeArchive({profile:w.permanentProfile.exportJSON(),run:before}));
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',(e:any)=>report.errors.push(e.message));
  await page.goto(`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(fixture);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
  const restored=await exportRun();assert.equal(restored.schema,18);assert.deepEqual(encodeGraph(restored.state.heroAttacks),encodeGraph(before.state.heroAttacks));assert.equal(restored.state.time,before.state.time);assert.equal(restored.state.paused,true);
  const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(r.confirmedHeroes.ready);assert.equal(r.confirmedHeroes.auras.heroes,3);assert.equal(r.confirmedHeroes.auras.textLabels,0);assert.equal(r.zergHeroes.auraDisplays,0);assert.deepEqual(r.errors,[]);for(const id of heroes.filter(id=>id==='raynor'||id==='nova'))assert.equal(r.confirmedHeroes.gunPoses[id].skill,r.confirmedHeroes.gunPoses[id].attack);
  await page.locator('.end-screen [data-action=pause]').click();await page.waitForTimeout(600);await page.screenshot({path:out+'/'+heroes[0]+'.png'});
  await page.locator('[data-seat="hero:0"]').click();const details=await page.locator('#unit-inspector').innerText();assert.ok(details.includes(HEROES[heroes[0]].skill));for(const aura of Object.values(HERO_GROUND_AURAS))assert.ok(!details.includes(aura.name),'aura text visible: '+aura.name);await page.screenshot({path:out+'/'+heroes[0]+'-details.png'});await page.locator('[data-inspect-close]').click();
  await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exportRun();assert.ok(after.state.stats.damage>before.state.stats.damage);
  await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exportRun();assert.deepEqual(loaded.state.heroAttacks,after.state.heroAttacks);assert.equal(loaded.state.time,after.state.time);assert.equal(loaded.state.paused,true);const loadedView=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(loadedView.confirmedHeroes.auras.heroes,3);assert.equal(loadedView.confirmedHeroes.auras.textLabels,0);report.checks.push({heroes,schema:loaded.schema,importedPackets:before.state.heroAttacks.packets.length,remainingPackets:loaded.state.heroAttacks.packets.length,dots:loaded.state.heroAttacks.dots.length,damage:after.state.stats.damage-before.state.stats.damage,auras:r.confirmedHeroes.auras.heroes,auraTextVisible:false,aurasRestored:loadedView.confirmedHeroes.auras.heroes,gunPoses:r.confirmedHeroes.gunPoses,saveRestored:true,debugApi:false});await context.close();console.log(heroes.join('/')+': production integration passed');
 }
 assert.deepEqual(report.errors,[]);assert.equal(JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,report.appBuildId);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/failure.png'});}}
finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,errors:report.errors,failure:report.failure??null}));}
