import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {createGameServer} from './coze-web-server.mjs';import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {ELITES} from '../src/data/elites';
const mode=process.env.QA_OFFLINE_HTML?'hellbat':'hellion',out='reports/local/hellion-knight-correction-20261005/'+(process.env.QA_OFFLINE_HTML?'production-offline':'production');await fs.mkdir(out,{recursive:true});
const w=new World({race:'terran',seed:10530,waves:false,terrain:campaignTerrain(chooseCampaignMap(10530))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.expedition.ledger=[];for(const p of Object.values(w.expedition.production))p.enabled={};w.expedition.familySlots=['hellion'];w.expedition.tech['unlock.hellion']=1;w.time=10;w.tick=600;w.stageStartedAt=w.time;
const source=w.freePosition('hellion',w.anchor,2,5);assert.ok(source);const u=w.addUnit('hellion','terran',source.x,source.z,5);u.eliteId='hellion.2';u.modelKey=ELITES['hellion.2'].model;u.nativeMode=mode;w.refreshStats(u,true);const point=w.freePosition('roach',u,2.2,3.5);assert.ok(point);const t=w.addUnit('roach','zerg',point.x,point.z);t.hp=t.maxHp=1e6;t.armor=0;t.weaponDamage=0;t.stoppedUntil=t.nextShotAt=t.specialReady=1e9;t.moveSpeed=0;w.hash.rebuild(w.entities.values());w.fire(u,t);assert.ok(t.hp<1e6);w.paused=true;const before=w.captureRun(),file=path.resolve(out,mode+'.json');const fixtureRestore=new World({race:'terran'});fixtureRestore.restoreRun(before);await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:before}));
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),report:any={mode,method:'Actual normal production file import/export/save/reload/local-load. Fixture is a genuine schema21 World attack with original body and resource keys. Pause overlay is hidden only for one screenshot and restored. No production debug API or live-state mutation.',appBuildId:release.appBuildId,errors:[]};
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']}),page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',e=>report.errors.push(e.message));
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes((window as any).__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});assert.equal((await page.evaluate(()=>(window as any).__SC2_REPORT__())).readiness.phase,'ready');};
const exported=async()=>{const promise=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile((await(await promise).path())!,'utf8')).bundle.run!;};
const mechanism=(state:any)=>encodeGraph({time:state.time,effects:state.effects,flights:state.weaponFlights,elites:state.terranElites,wallet:state.wallet,ledger:state.expedition.ledger,units:[...state.entities.values()].map((u:any)=>({id:u.id,eliteId:u.eliteId,x:u.x,z:u.z,hp:u.hp,maxHp:u.maxHp,range:u.attackRange,mode:u.nativeMode,combat:u.eliteCombat,next:u.nextShotAt}))});
try{await page.goto(process.env.QA_OFFLINE_HTML?pathToFileURL(path.resolve(process.env.QA_OFFLINE_HTML)).href:'http://127.0.0.1:'+(server.address() as any).port+'/',{timeout:240000});await page.waitForFunction(()=>(window as any).__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof(window as any).__SC2_DEBUG__),'undefined');await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().terranElites?.materials?.flameFan?.layers===2);
 const imported=await exported();assert.deepEqual(mechanism(imported.state),mechanism(before.state));assert.equal(imported.schema,21);const r=await page.evaluate(()=>(window as any).__SC2_REPORT__());assert.equal(r.terranElites.flameFans[0].radius,mode==='hellbat'?4:10);assert.equal(r.terranElites.materials.flameFan.arcDegrees,150);assert.equal(r.terranElites.materials.flameFan.filled,true);const mask=await page.addStyleTag({content:'#overlay {display:none!important;}'});await page.screenshot({path:out+'/visible-fan.png'});await mask.evaluate(el=>el.remove());assert.equal((await page.evaluate(()=>(window as any).__SC2_REPORT__())).time,r.time);assert.equal(await page.locator('.end-screen:visible').count(),1);
 await page.locator('.end-screen [data-action=pause]').click();await page.waitForFunction(damage=>(window as any).__SC2_REPORT__().stats.damage>damage,before.state.stats.damage,{timeout:30000});await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().save.message.includes('已保存'));const after=await exported();assert.equal(after.schema,21);assert.ok(after.state.stats.damage>before.state.stats.damage);await page.reload({timeout:240000});await page.waitForFunction(()=>(window as any).__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exported();assert.deepEqual(mechanism(loaded.state),mechanism(after.state));assert.equal(loaded.state.paused,true);assert.deepEqual(report.errors,[]);report.schema=loaded.schema;report.fan=r.terranElites.flameFans;report.material=r.terranElites.materials.flameFan;report.saveRestored=true;report.damage=after.state.stats.damage-before.state.stats.damage;report.debugApi=false;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;report.last=await page.evaluate(()=>(window as any).__SC2_REPORT__?.()).catch(()=>null);await page.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify(report));}
