import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium,type Page} from '@playwright/test';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';
import {RACES,FAMILIES_BY_RACE} from '../src/data/races';import {PRODUCTION_LINES} from '../src/data/expedition-buildings';
import {writeArchive} from '../src/persistence/archive';import {createGameServer} from './coze-web-server.mjs';
const out=process.env.SC2_INTERMISSION_QA_DIR??'reports/local/intermission-integration-20261009/browser';await fs.mkdir(out,{recursive:true});
// Fresh current-build diagnostic scenes only. No old-save matching, migration, or save acceptance.
const fixtures:Record<string,string>={};
for(const race of RACES){
 const w=new World({race,seed:100927,waves:false,terrain:campaignTerrain({version:3,seed:100927,theme:'industrial'})});assert.ok(w.start());w.wallet={minerals:10000,gas:10000};w.stage=6;
 for(const [id,d]of Object.entries(PRODUCTION_LINES).filter(([,d])=>d.race===race)){if(!w.expedition.facilities.some(f=>f.line===id))w.expedition.facilities.push({id:w.expedition.nextFacility++,kind:race==='zerg'?'hatchery':id,line:id as never,techLab:false});w.expedition.tech[race==='zerg'?'hatchery':id]=1;w.expedition.tech['system.'+id]=1;w.expedition.tech['research.'+id+'.weapon']=1;w.expedition.tech['research.'+id+'.defense']=1;}
 const first=Object.entries(PRODUCTION_LINES).find(([,d])=>d.race===race)!,target=first[1].families[1];w.expedition.developmentTarget='unlock.'+target;for(const p of Object.values(w.expedition.production))p.enabled={};w.endStage();w.setDevelopmentDirection(first[0]as never);
 const file=path.resolve(out,race+'-building.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));fixtures[race]=file;
 w.skipReward();for(let n=0;n<200&&!w.rewards.some(r=>(r as any).expeditionEffect.kind==='teamCard');n++)w.reroll();w.wallet={minerals:0,gas:0};const poor=path.resolve(out,race+'-poor.json');await fs.writeFile(poor,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));fixtures[race+'-poor']=poor;
}
const arrival=new World({seed:100927,waves:false,terrain:campaignTerrain({version:3,seed:100927,theme:'industrial'})});arrival.start();for(const p of Object.values(arrival.expedition.production))p.enabled={};for(const isHero of [false,true]){arrival.random=()=>isHero?.1:.5;const b=arrival.spawnSpecial('zergling','boss',arrival.anchor)!;arrival.hit(b,1e9,[],1,'terran');}for(const d of arrival.rewardDrops)if(d.bossLootReceipt&&(d.reward as any).expeditionEffect.kind==='elite')d.bossLootVariant='marine.2';arrival.paused=true;fixtures.arrival=path.resolve(out,'arrival.json');await fs.writeFile(fixtures.arrival,writeArchive({profile:arrival.permanentProfile.exportJSON(),run:arrival.captureRun()}));
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{enabled:false}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true,acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(25000);
const report:any={build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Actual production Web build; fresh diagnostic scenes for UI and current native actions, not save compatibility or physical/natural acceptance.',checks:[],screens:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
const shot=async(name:string)=>{if(!name.startsWith('arrival-'))await page.waitForTimeout(650);await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);};
async function load(file:string){await page.goto(url,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await page.locator('.main-actions [data-action=menu-load]').click();const q=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await q).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});await page.locator('[data-action=flow-continue]').click();await page.waitForTimeout(150);}
const wallet=()=>page.evaluate(()=>window.__SC2_REPORT__().wallet);
const offers=()=>page.locator('#reward-cards>.im-card').evaluateAll(ns=>ns.map(n=>n.getAttribute('data-card-id')));
async function fit(){await page.waitForTimeout(400);const bad=await page.locator('.feedback-progress-strip,.im-card,.modal-window,.modal-footer').evaluateAll(ns=>ns.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.left<-.6||r.right>innerWidth+.6)}).map(n=>({class:n.className,text:n.textContent?.slice(0,40),bounds:n.getBoundingClientRect().toJSON(),viewport:innerWidth})));assert.deepEqual(bad,[]);}
try{
 for(const race of RACES){await load(fixtures[race]);const ids=await offers(),before=await wallet();await page.locator('#overlay.imx .imx-copy').first().waitFor();
  const services=page.locator('.feedback-progress-strip button');assert.deepEqual(await services.allTextContents(),['设施调整','武器与防护研究','强化一览','休整']);assert.equal(await page.locator('[data-action=ui-menu],[data-page=catalog],[data-action^=boss-loot]').count(),0);
  await page.locator('.im-heading [data-action=settings]').click();assert.deepEqual(await page.locator('[data-action=settings-tab]').allTextContents(),['操作','画质']);await page.locator('[data-tab=graphics]').click();await shot(race+'-settings');await page.keyboard.press('Escape');assert.deepEqual(await offers(),ids);assert.deepEqual(await wallet(),before);
  await page.locator('.feedback-progress-strip [data-action=battle-base]').click();assert.equal(await page.locator('.feedback-facility-card').count(),3);assert.ok(await page.locator('.facility-unit[data-unlocked=false]').count()>0);if(race==='zerg')assert.equal(await page.locator('[data-setting=hatchery-sequence]').count(),3);await shot(race+'-facilities');await fit();await page.keyboard.press('Escape');
  await page.locator('[data-action=battle-research]').click();assert.equal(await page.locator('.imx-research-art').count(),6);const art=await page.locator('.imx-research-art').evaluateAll(ns=>ns.map(n=>getComputedStyle(n).backgroundPosition));assert.equal(new Set(art).size,6);await shot(race+'-research');await page.keyboard.press('Escape');
  await page.locator('.feedback-progress-strip [data-action=battle-progress]').click();await page.locator('[data-tab=sources]').click();await shot(race+'-enhancements');await page.keyboard.press('Escape');
  await page.locator('[data-page=rest]').click();await shot(race+'-rest');await page.locator('[data-action=ui-rest-repair]').click();await page.keyboard.press('Escape');assert.equal(await page.locator('[data-ui-route=rest]').count(),1);await page.keyboard.press('Escape');assert.deepEqual(await offers(),ids);assert.deepEqual(await wallet(),before);
  const copy=page.locator('.imx-copy').first(),a=await copy.boundingBox();await copy.click();const b=await copy.boundingBox();assert.ok(Math.abs(a!.height-b!.height)<.25);assert.ok(Math.abs(a!.width-b!.width)<.25);await shot(race+'-building-detail');await copy.click();
  await page.locator('#reward-cards .im-card-action:not(:disabled)').first().click();await page.waitForFunction(()=>document.querySelector('.im-heading h1')?.textContent==='战备补给');const shop=await offers();await shot(race+'-shop');await fit();
  const ordinary=page.locator('#reward-cards .im-card-action[data-action=reward]:not(:disabled)').first();if(await ordinary.count()){await ordinary.click();assert.deepEqual(await offers(),shop);assert.ok(await page.locator('.im-card.im-sold').count()>0);}
  for(const [w,h]of [[390,844],[844,390],[320,700]]){await page.setViewportSize({width:w,height:h});await fit();await shot(race+'-shop-'+w);await page.locator('[data-action=battle-research]').click();await fit();await shot(race+'-research-'+w);await page.keyboard.press('Escape');}
  await page.setViewportSize({width:1440,height:900});report.checks.push(race+': four services, settings/back preserve quotes/wallet, facilities, six research art cells, totals/sources, rest/back, equal copy areas, native construction/shop, four sizes');
 }
 await load(fixtures['terran-poor']);for(const card of await page.locator('.im-card.im-short').all())assert.match(await card.innerText(),/资源不足/);await shot('insufficient');report.checks.push('Discounted and standard cards retain insufficient-resource status');
 await page.locator('[data-action=skip]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle',null,{timeout:240000});await page.locator('#minimap-canvas').waitFor({state:'visible'});await shot('return-battle-map');report.checks.push('Return to real battlefield and minimap');
 await load(fixtures.arrival);if(await page.locator('.pause-actions [data-action=pause]').isVisible())await page.locator('.pause-actions [data-action=pause]').click();await page.locator('.arrival-card.elite').waitFor();
 for(const [w,h]of [[1440,900],[390,844],[844,390],[320,700]]){await page.setViewportSize({width:w,height:h});const g=await page.locator('.arrival-body').evaluate(e=>[...e.children].map(n=>({w:(n as HTMLElement).offsetWidth,h:(n as HTMLElement).offsetHeight,r:getComputedStyle(n).borderRadius})));assert.deepEqual(g[0],g[1]);}
 await page.setViewportSize({width:1440,height:900});await page.locator('.arrival-card').evaluate(e=>{for(const a of e.getAnimations({subtree:true})){a.pause();a.currentTime=500;}});await shot('arrival-back');await page.locator('.arrival-card').evaluate(e=>{for(const a of e.getAnimations({subtree:true}))a.currentTime=1300;});await shot('arrival-elite');await page.locator('.arrival-card.hero').waitFor();await page.waitForTimeout(1200);await shot('arrival-hero');assert.equal(await page.locator('#arrival-layer').evaluate(e=>getComputedStyle(e).pointerEvents),'none');assert.equal(await page.locator('[data-action^=boss-loot]').count(),0);report.checks.push('Arrival card shared new front/back frame, four-size equal bounds, elite/hero native queue, no claim UI/input capture');assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String((e as Error).stack);await shot('failure').catch(()=>{});process.exitCode=1;}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
