import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';
import {campaign18Schedule,campaign18StageConfig} from '../src/data/campaign18';
import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';
import {readArchive,writeArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
const out=process.argv[2];assert.ok(out?.startsWith('reports/local/lighting-batch3-20261010/'));await fs.mkdir(out,{recursive:true});
await fs.access(out+'/result.json').then(()=>{throw Error('Evidence exists');},e=>{if(e.code!=='ENOENT')throw e;});
await fs.copyFile(new URL(import.meta.url),path.join(out,'runner.mts'));
const profile=new PermanentProfile();profile.award('lighting-input-fixture',1000,'terran');profile.selectRace('terran');
assert.ok(profile.savePresetBlueprint('terran',0,Object.fromEntries(MVP_TALENTS.filter(n=>n.race==='terran'&&n.line==='micro'&&n.tier<=4).map(n=>[n.id,n.maxRank]))));
const world=new World({race:'terran',seed:529,waves:false,terrain:campaignTerrain({version:3,seed:529,theme:'industrial'}),permanentProfile:profile});assert.ok(world.start());for(const plan of Object.values(world.expedition.production))plan.enabled={};
// Isolate timed rescue/reward decisions while exercising the original input routes.
world.economicTargets.clear();world.pods=[];world.pickups=[];world.rewardDrops=[];(world as any).eventPlan=[];(world as any).nextEvent=0;world.nextFreePodAt=world.nextEliteGrowthAt=world.nextMercenaryAt=world.nextTankSupportAt=1e9;
world.paused=true;const fixture=path.resolve(out,'input-fixture.json');await fs.writeFile(fixture,writeArchive({profile:profile.exportJSON(),run:world.captureRun()}));
const victory=new World({race:'terran',seed:41,waves:false,terrain:campaignTerrain({version:3,seed:41,theme:'industrial'})});assert.ok(victory.start());for(const plan of Object.values(victory.expedition.production))plan.enabled={};victory.stage=18;victory.prepareStage();victory.hive!.hp=0;const finalEvent=campaign18Schedule(campaign18StageConfig(18,victory.difficulty),41).specials[0],finalBoss=(victory as any).spawnCampaignSpecial(finalEvent);assert.ok(finalBoss);victory.hit(finalBoss,1e9,[],1,'terran');victory.stageElapsed=victory.duration;victory.endStage();assert.equal(victory.phase,'won');victory.paused=true;const victoryFile=path.resolve(out,'victory-fixture.json');await fs.writeFile(victoryFile,writeArchive({profile:victory.permanentProfile.exportJSON(),run:victory.captureRun()}));
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true}),page=await context.newPage();await context.addInitScript('window.__name=(value)=>value;');
await context.addInitScript(()=>{(window as any).__LIGHTING_INPUT_EVENTS=[];for(const type of ['pointerdown','pointerup','pointercancel','gotpointercapture','lostpointercapture'])addEventListener(type,(event)=>{const e=event as PointerEvent;if(!(e.target instanceof Element)||!e.target.closest('#minimap'))return;const report=(window as any).__SC2_REPORT__?.();(window as any).__LIGHTING_INPUT_EVENTS.push({type,stamp:e.timeStamp,now:performance.now(),pointerType:e.pointerType,pointerId:e.pointerId,primary:e.isPrimary,x:e.clientX,y:e.clientY,target:e.target.id,phase:report?.phase,time:report?.time,order:report?.order,controls:report?.controls});},true);});page.setDefaultTimeout(120000);
const report:any={build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Actual production keyboard, mouse and CDP touch inputs; native archive exports verify World.anchor, orders and dash state. Every viewport starts by importing the same native fixture through the original menu, retaining renderer caches. Timed rescue/reward decisions are isolated in the diagnostic fixture. Browser geometry does not establish physical-device acceptance.',records:[],errors:[],screens:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
const read=()=>page.evaluate(()=>(window as any).__SC2_REPORT__());
async function screenshot(name:string){await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);}
let exportIndex=0;
async function exported(){const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();const raw=await fs.readFile(await(await d).path(),'utf8'),file='export-'+String(++exportIndex).padStart(3,'0')+'.json';await fs.writeFile(path.join(out,file),raw);(report.exports??=[]).push(file);return readArchive(raw).bundle;}
async function snapshot(){await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=pause-saves]').click();const saved=await exported();await page.locator('[data-action=archives-back]').last().click();await page.locator('.pause-actions [data-action=pause]').click();return saved.run!;}
async function preferences(desktop:string,touch:string){await page.locator('.native-map-utilities [data-action=settings]').click();await page.locator('[data-action=settings-tab][data-tab=controls]').click();await page.locator('[data-setting=desktop]').selectOption(desktop);await page.locator('[data-setting=touch]').selectOption(touch);await page.locator('[data-action=settings-back]').last().click();}
async function elapsed(seconds:number){const t=(await read()).time;await page.waitForFunction((goal:number)=>(window as any).__SC2_REPORT__().time>=goal,t+seconds,{timeout:120000});}
const distance=(a:any,b:any)=>Math.hypot(a.x-b.x,a.z-b.z);
async function loadFixture(file=fixture,resume=true){await page.locator('.main-actions [data-action=menu-load]').click();const f=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await f).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes((window as any).__SC2_REPORT__?.().readiness?.phase),null,{timeout:900000});assert.equal((await read()).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();if(resume)await page.locator('.pause-actions [data-action=pause]').click();}
try{
 await page.goto('http://127.0.0.1:'+(server.address() as any).port,{timeout:600000});await page.waitForFunction(()=>(window as any).__SC2_REPORT__?.().phase==='menu',null,{timeout:900000});
 const selectedWidth=Number(process.argv.find(v=>v.startsWith('--width='))?.split('=')[1]??0);
 for(const [width,height]of [[1440,900],[844,390],[390,844],[320,568]].filter(([width])=>!selectedWidth||width===selectedWidth)){
  if(report.records.length){await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=restart]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().phase==='menu');}
  await loadFixture();await page.setViewportSize({width,height});await preferences('keyboard','joystick');let before=await snapshot();
  await page.locator('#battle').focus();await page.keyboard.down('d');await elapsed(.6);await page.keyboard.up('d');let after=await snapshot();assert.ok(distance(before.state.anchor,after.state.anchor)>.1,'keyboard must move real anchor');const keyboard={before:before.state.anchor,after:after.state.anchor};
  const dash=page.locator('[data-command=dash]');if(!await dash.isVisible()){const back=page.locator('[data-command-page="-1"]');if(await back.isEnabled())await back.click();}await dash.waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector<HTMLButtonElement>('[data-command=dash]')?.disabled);before=await snapshot();await dash.click();after=await snapshot();assert.ok(after.state.dashReady>before.state.dashReady);assert.ok(after.state.dashUntil>before.state.time);const boost={before:before.state.dashReady,after:after.state.dashReady};
  const stick=await page.locator('#joystick').boundingBox();assert.ok(stick);before=await snapshot();const cdp=await context.newCDPSession(page),x=stick.x+stick.width/2,y=stick.y+stick.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+stick.width*.3,y:y-stick.height*.1}]});await elapsed(.6);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();after=await snapshot();assert.ok(distance(before.state.anchor,after.state.anchor)>.1);const joystick={before:before.state.anchor,after:after.state.anchor};
  await preferences('mouse','tap');const canvas=await page.locator('#battle').boundingBox();assert.ok(canvas);const point={x:canvas.x+canvas.width*.56,y:Math.min(canvas.y+canvas.height*.35,height*.35)};await page.mouse.click(point.x,point.y,{button:'right'});await page.waitForFunction(()=>(window as any).__SC2_REPORT__().order?.kind==='move');const clickOrder=(await read()).order;await elapsed(.4);await screenshot(width+'-click-move');
  await page.touchscreen.tap(canvas.x+canvas.width*.44,point.y);await page.waitForFunction((old:any)=>{const r=(window as any).__SC2_REPORT__().order;return r?.kind==='move'&&Math.hypot(r.point.x-old.x,r.point.z-old.z)>.1;},clickOrder.point);const touchOrder=(await read()).order;await screenshot(width+'-touch-move');
  const map=page.locator('#minimap-canvas'),box=await map.boundingBox();assert.ok(box);const frame=JSON.parse((await map.getAttribute('data-map-frame'))!);before=await snapshot();const target={x:before.state.anchor.x-4,z:before.state.anchor.z+2},px=Math.max(.08,Math.min(.92,(target.x-frame.left)/frame.size)),py=Math.max(.08,Math.min(.92,(target.z-frame.top)/frame.size));await page.mouse.click(box.x+box.width*px,box.y+box.height*py);await page.waitForFunction((old:any)=>{const r=(window as any).__SC2_REPORT__().order;return r?.kind==='move'&&Math.hypot(r.point.x-old.x,r.point.z-old.z)>.1;},touchOrder.point);const minimapOrder=(await read()).order;assert.ok(distance(touchOrder.point,minimapOrder.point)>.1);assert.equal(await map.getAttribute('data-threat-count'),'0');await screenshot(width+'-minimap-move');
  // Chrome's native touch adjustment can retarget a point near the upper-right
  // corner to the collapse button even when elementFromPoint returns the canvas.
  // Exercise movement in the map interior, away from all native utility buttons.
  const qx=.42,qy=.58,touchPoint={x:box.x+box.width*qx,y:box.y+box.height*qy};
  (report.minimapTouches??=[]).push({width,height,frame,box,touchPoint,target:await page.evaluate(p=>{const n=document.elementFromPoint(p.x,p.y);return {id:n?.id,tag:n?.tagName};},touchPoint),before:await read()});
  await page.touchscreen.tap(touchPoint.x,touchPoint.y);await page.waitForFunction((old:any)=>{const r=(window as any).__SC2_REPORT__().order;return r?.kind==='move'&&Math.hypot(r.point.x-old.x,r.point.z-old.z)>.1;},minimapOrder.point,{timeout:15000});const minimapTouchOrder=(await read()).order;
  const touchEvents=await page.evaluate(()=>(window as any).__LIGHTING_INPUT_EVENTS.filter((e:any)=>e.pointerType==='touch').slice(-4));assert.ok(touchEvents.some((e:any)=>e.type==='pointerdown'&&e.target==='minimap-canvas'));assert.ok(touchEvents.some((e:any)=>e.type==='pointerup'&&e.target==='minimap-canvas'));await screenshot(width+'-minimap-touch');
  await page.locator('#battle').focus();await page.keyboard.press('f');await page.waitForFunction(()=>document.body.dataset.targetFamily==='transfer');await page.mouse.move(point.x,point.y);await screenshot(width+'-target');await page.keyboard.press('Escape');assert.equal(await page.locator('body').getAttribute('data-target-family'),null);assert.equal(await page.locator('#transfer-picker').isVisible(),false);
  const runtime=await read();for(const key of ['shadows','contact']){assert.equal(runtime[key].enabled,true);assert.equal(runtime[key].ready,true);assert.equal(runtime[key].fallback,null);}assert.deepEqual(runtime.errors,[]);report.records.push({width,height,keyboard,boost,joystick,clickOrder,touchOrder,minimapOrder,minimapTouchOrder,touchEvents,selectionCancelled:true,runtime});await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));
 }
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=pause-saves]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().save.message.includes('已保存'));const saved=await exported();
 await page.reload({timeout:600000});await page.waitForFunction(()=>(window as any).__SC2_REPORT__?.().phase==='menu');await page.locator('.main-actions [data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().readiness.phase==='ready',null,{timeout:900000});await page.locator('[data-action=flow-continue]').click();await page.locator('[data-action=pause-saves]').click();const restored=await exported();assert.deepEqual(encodeGraph(restored.run),encodeGraph(saved.run));report.exactRecovery=true;
 // Exercise the actual campaign victory -> native endless preparation route on the final build.
 await page.locator('[data-action=archives-back]').last().click();await page.locator('[data-action=restart]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().phase==='menu');await page.setViewportSize({width:1440,height:900});await loadFixture(victoryFile,false);
 await page.locator('[data-action=endless]:visible').click();await page.locator('.reward-actions [data-action=skip]').click();await page.locator('.reward-actions [data-action=skip]').click();await page.locator('[data-action=endless-prepare]:visible').click();await page.waitForFunction(()=>['ready','error'].includes((window as any).__SC2_REPORT__().readiness.phase),null,{timeout:900000});assert.equal((await read()).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().phase==='battle');
 const endless=await read();assert.ok(endless.endless);assert.equal(endless.lighting.theme,'char');for(const key of ['shadows','contact']){assert.equal(endless[key].enabled,true);assert.equal(endless[key].ready,true);assert.equal(endless[key].fallback,null);}assert.deepEqual(endless.errors,[]);assert.equal(endless.assetsPending,0);await screenshot('endless-entered');
 if(!await page.locator('[data-action=pause-saves]').isVisible())await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=pause-saves]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>(window as any).__SC2_REPORT__().save.message.includes('已保存'));const endlessSaved=await exported();
 await page.reload({timeout:600000});await page.waitForFunction(()=>(window as any).__SC2_REPORT__?.().phase==='menu');await page.locator('.main-actions [data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes((window as any).__SC2_REPORT__().readiness.phase),null,{timeout:900000});assert.equal((await read()).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();await page.locator('[data-action=pause-saves]').click();const endlessRestored=await exported();assert.deepEqual(encodeGraph(endlessRestored.run),encodeGraph(endlessSaved.run));const endlessAfter=await read();assert.equal(endlessAfter.lighting.theme,'char');for(const key of ['shadows','contact']){assert.equal(endlessAfter[key].ready,true);assert.equal(endlessAfter[key].fallback,null);}await page.locator('[data-action=archives-back]').last().click();await screenshot('endless-restored');report.endless={before:endless,after:endlessAfter,exactRecovery:true,method:'Generated current-schema native final-boss victory, original endless entry buttons and original local-save restoration; not natural campaign acceptance'};
 report.passed=true;assert.deepEqual(report.errors,[]);
}catch(e){report.passed=false;report.failure=String((e as Error).stack??e);await screenshot('failure').catch(()=>{});process.exitCode=1;}
finally{report.final=await read().catch(()=>null);report.inputEvents=await page.evaluate(()=>(window as any).__LIGHTING_INPUT_EVENTS??[]).catch(()=>[]);await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await context.close();await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({passed:report.passed,records:report.records.length,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
