import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';

const out='reports/local/qa-m2';
await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const watch=page=>{page.on('pageerror',error=>report.errors.push(error.message));page.on('console',message=>{if(message.type()==='error')report.errors.push(message.text());});};
const ready=page=>page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});
const battleReady=page=>page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});
const saved=page=>page.waitForFunction(()=>window.__SC2_REPORT__?.().save?.message?.includes('已保存')&&!window.__SC2_REPORT__().save.busy,null,{timeout:30000});

try{
 const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true});
 const page=await context.newPage();watch(page);
 await page.goto(process.env.SC2_QA_URL??'http://127.0.0.1:5173/');await ready(page);
 await page.evaluate(()=>{if(!window.__SC2_DEBUG__.world.permanentProfile.award('qa-m2-resources',300))throw Error('Fixture resource receipt failed');});
 await page.locator('[data-action=talents]').click();
 await page.locator('[data-action=mvp-talent-select][data-id=T-R01]').click();
 await page.locator('[data-action=mvp-talent-buy][data-id=T-R01]').click();
 assert.deepEqual(await page.evaluate(()=>{const p=window.__SC2_DEBUG__.world.permanentProfile;return [p.playerLevel,p.balance,p.levels['T-R01']];}),[1,299,1]);
 await page.locator('[data-action=mvp-talent-copy]').click();
 await page.locator('[data-action=mvp-talent-preset][data-slot="1"]').click();
 await page.locator('[data-action=mvp-talent-respec][data-line=resources]').click();
 assert.deepEqual(await page.evaluate(()=>{const p=window.__SC2_DEBUG__.world.permanentProfile;return [p.playerLevel,p.balance,p.getPreset('terran',0).levels['T-R01']];}),[0,300,1]);
 await page.locator('[data-action=mvp-talent-preset][data-slot="0"]').click();
 assert.deepEqual(await page.evaluate(()=>{const p=window.__SC2_DEBUG__.world.permanentProfile;return [p.playerLevel,p.balance,p.levels['T-R01']];}),[1,299,1]);
 await page.locator('[data-action=mvp-talent-race][data-race=protoss]').click();
 await page.evaluate(()=>{if(!window.__SC2_DEBUG__.world.permanentProfile.award('qa-m2-protoss-resources',300,'protoss'))throw Error('Protoss resource receipt failed');});
 await page.locator('[data-action="mvp-talent-buy"][data-id="P-R01"]').click();
 assert.deepEqual(await page.evaluate(()=>{const p=window.__SC2_DEBUG__.world.permanentProfile;return [p.activeRace,p.playerLevel,p.balance,p.levels['P-R01']];}),['protoss',1,299,1]);
 await page.evaluate(async()=>{const {MVP_TALENTS}=await import('/src/data/mvp-talents.ts'),p=window.__SC2_DEBUG__.world.permanentProfile,levels=Object.fromEntries(MVP_TALENTS.filter(node=>node.race==='protoss'&&node.line==='resources').map(node=>[node.id,node.maxRank]));const quote=p.previewTalentAllocation('protoss',0,levels);if(!quote||quote.allocated!==41||!p.commitTalentAllocation(quote,quote.expectedRevision))throw Error('41-point fixture failed');});
 assert.match(await page.locator('.mvp-talent-summary').innerText(),/神族等级 41 \/ 80/);
 await page.screenshot({path:out+'/talents-protoss.png'});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:out+'/talents-protoss-narrow.png'});
 await page.setViewportSize({width:1440,height:900});
 report.checks.push('Actual talent UI buys, copies, refunds, activates and switches race with one active investment');

 await page.locator('[data-action=talents-back]').click();
 await page.locator('[data-action=menu-new]').click();
 await page.locator('[data-action=menu-race][data-race=protoss]').click();
 await page.locator('[data-action=menu-race-next]').click();
 await page.locator('[data-action=menu-difficulty][data-difficulty=hard]').click();
 await page.locator('[data-action=menu-difficulty-next]').click();
 await page.getByLabel('开局英雄').selectOption('zeratul');
 await page.locator('[data-action=menu-start]').click();
 await battleReady(page);
 await page.locator('[data-action=flow-continue]').click();
 await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 await page.locator('#topbar [data-action=pause]').click();
 const before=await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {race:w.runConfig.race,difficulty:w.runConfig.difficulty,level:w.runConfig.frozenTalents.levels['P-R01'],allocated:w.runConfig.frozenTalents.allocated,hero:[...w.heroes.keys()][0],time:w.time,paused:w.paused};});
 assert.deepEqual(before,{race:'protoss',difficulty:'hard',level:3,allocated:41,hero:'zeratul',time:before.time,paused:true});
 await page.locator('[data-action=save-now]').click();await saved(page);
 const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();const download=await downloadPromise;
 const archive=out+'/m2-frozen-save.json';await download.saveAs(archive);
 await page.reload();await ready(page);
 await page.locator('[data-action=menu-new]').click();
 await page.locator('[data-action=menu-race][data-race=terran]').click();
 await page.locator('[data-action=menu-race-next]').click();
 await page.locator('[data-action=menu-difficulty][data-difficulty=easy]').click();
 await page.locator('[data-action=menu-back]').click();
 await page.locator('[data-action=menu-back]').click();
 await page.locator('[data-action=menu-load]').click();
 await page.locator('[data-action=menu-load-local]').click();
 await page.locator('[data-action=menu-load-ready]').click();
 await battleReady(page);
 await page.locator('[data-action=flow-continue]').click();
 const after=await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {race:w.runConfig.race,difficulty:w.runConfig.difficulty,level:w.runConfig.frozenTalents.levels['P-R01'],allocated:w.runConfig.frozenTalents.allocated,hero:[...w.heroes.keys()][0],time:w.time,paused:w.paused};});
 assert.deepEqual(after,before);
 await page.evaluate(()=>{const p=window.__SC2_DEBUG__.world.permanentProfile;if(!p.respec('all'))throw Error('Post-start respec fixture failed');});
 assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.runConfig.frozenTalents.levels['P-R01']),3);
 report.checks.push('Browser save/reload preserves Protoss/Hard, 41 frozen points and selected R16 starter hero despite opposite menu defaults and later profile changes');

 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.paused=false;w.runConfig.frozenTalents.levels['P-M04']=1;w.changed();document.dispatchEvent(new CustomEvent('sc2-target-family',{detail:'transfer'}));});
 await page.locator('#transfer-picker [data-transfer-id]').first().waitFor();
 const member=page.locator('#transfer-picker [data-transfer-id]').first();
 const original=await member.getAttribute('aria-pressed');
 await page.evaluate(()=>document.dispatchEvent(new Event('sc2-target-member-toggle')));
 assert.notEqual(await member.getAttribute('aria-pressed'),original);
 const sameNode=await page.evaluate(()=>{const panel=document.querySelector('#transfer-picker');const member=panel.querySelector('[data-transfer-id]');document.dispatchEvent(new CustomEvent('sc2-target-nudge',{detail:{x:.5,z:0}}));return member===panel.querySelector('[data-transfer-id]');});
 assert.equal(sameNode,true);
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:out+'/transfer-narrow.png'});
 await page.locator('#transfer-picker [data-transfer-cancel]').click();
 assert.equal(await page.locator('#transfer-picker').isHidden(),true);
 await page.screenshot({path:out+'/battle-transfer-closed.png'});
 report.checks.push('Transfer roster toggles and cancels in browser without rebuilding member controls on aim changes');
 await context.close();

 const offline=await browser.newContext({viewport:{width:1440,height:900},offline:true});
 const file=await offline.newPage(),network=[];watch(file);file.on('request',request=>{if(/^https?:/i.test(request.url()))network.push(request.url());});
 await file.goto(pathToFileURL(process.cwd()+'/dist/SC2-Survivors-Demo.html').href,{timeout:180000});await ready(file);
 await file.locator('[data-action=menu-load]').click();
 const chooser=file.waitForEvent('filechooser');await file.locator('[data-action=menu-load-file]').click();await (await chooser).setFiles(archive);
 await file.locator('[data-action=menu-load-ready]').waitFor();
 await file.locator('[data-action=menu-load-ready]').click();
 await battleReady(file);
 await file.locator('[data-action=flow-continue]').click();
 await file.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='battle',null,{timeout:30000});
 const frozen=await file.evaluate(()=>{const state=window.__SC2_REPORT__();return {race:state.expedition.race,level:state.expedition.frozenTalents.levels['P-R01'],allocated:state.expedition.frozenTalents.allocated,phase:state.phase};});
 assert.deepEqual(frozen,{race:'protoss',level:3,allocated:41,phase:'battle'});
 assert.deepEqual(network,[]);assert.equal(await file.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');
 report.checks.push('Offline standalone imports a nonzero-talent M2 archive and resumes without network or debug controls');
 await offline.close();
 assert.deepEqual(report.errors,[]);
}catch(error){report.failure=String(error?.stack??error);console.error(report.failure);process.exitCode=1;}
finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
