import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const out='reports/local/qa-v12-map';await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),method:'Desktop Chrome actual pointer/touch commands and WebGL render diagnostics. Screenshots stay local; no human visual approval, phone test or difficulty playthrough is implied.',errors:[],viewports:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
async function boot(p,url='http://127.0.0.1:5173/'){p.on('pageerror',e=>report.errors.push(e.message));p.on('console',e=>{if(e.type()==='error')report.errors.push(e.text());});await p.goto(url);await p.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:120000});await p.getByRole('button',{name:/部署小队/}).click();}
async function setup(p){await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.autoWaves=false;w.eventPlan=[];w.nextWave=Infinity;w.buildings.clear();w.entities.clear();w.economicTargets.clear();w.pods=[];w.pickups=[];w.phase='battle';w.paused=false;w.anchor={x:0,z:0,facing:0};w.cancelOrder();w.addUnit('marine','terran',0,0);w.changed();});}
async function pixel(p,point){return p.evaluate(point=>{const e=document.querySelector('#minimap-canvas'),r=e.getBoundingClientRect(),f=JSON.parse(e.dataset.mapFrame);return {x:r.left+(point.x-f.left)/f.size*r.width,y:r.top+(point.z-f.top)/f.size*r.height};},point);}
try{
 for(const [width,height,touch]of [[1440,900,false],[390,844,true],[844,390,true]]){const c=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch}),p=await c.newPage();await boot(p);await setup(p);
  const goal=await pixel(p,{x:8,z:0});if(touch)await p.touchscreen.tap(goal.x,goal.y);else await p.mouse.click(goal.x,goal.y,{button:'right'});
  const before=await p.evaluate(()=>window.__SC2_DEBUG__.world.order);assert.equal(before.kind,'move');assert.ok(Math.abs(before.point.x-8)<1);await p.waitForTimeout(1000);assert.ok(await p.evaluate(()=>window.__SC2_DEBUG__.world.anchor.x)>1);
  await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world,e=w.addUnit('roach','zerg',10,0);e.hp=e.maxHp=10000;e.moveSpeed=e.weaponDamage=0;window.__qaEnemy=e.id;w.changed();});const enemy=await pixel(p,{x:10,z:0});if(touch)await p.touchscreen.tap(enemy.x,enemy.y);else await p.mouse.click(enemy.x,enemy.y,{button:'left'});await p.waitForTimeout(2000);assert.ok(await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return w.order?.targetId===window.__qaEnemy&&w.entities.get(window.__qaEnemy).hp<10000;}));
  const layout=await p.evaluate(()=>{const rect=id=>{const r=document.querySelector(id).getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {minimap:rect('#minimap'),joystick:rect('#joystick'),roster:rect('#roster'),skills:rect('#skills'),scroll:[scrollX,scrollY],selection:String(getSelection()),scrollWidth:document.documentElement.scrollWidth,renderer:window.__SC2_REPORT__()};});
  const overlap=(a,b)=>a.w>0&&b.w>0&&a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;for(const name of ['joystick','roster','skills'])assert.equal(overlap(layout.minimap,layout[name]),false,name+' overlaps minimap');assert.deepEqual(layout.scroll,[0,0]);assert.equal(layout.selection,'');assert.ok(layout.scrollWidth<=width);await p.screenshot({path:out+`/minimap-${width}x${height}.png`});
  await p.keyboard.press('Escape');assert.equal(await p.locator('#minimap').isVisible(),false);await p.keyboard.press('Escape');
  if(!touch){report.surface=await p.evaluate(()=>{const {world:w,view}=window.__SC2_DEBUG__,g=view.scene.getObjectByName('char-traversable-ground').geometry;let invalid=0;for(const attr of Object.values(g.attributes))for(const n of attr.array)if(!Number.isFinite(n))invalid++;return {vertices:g.attributes.position.count,triangles:g.index.count/3,invalid,webglError:view.renderer.getContext().getError(),map:window.__SC2_REPORT__().map};});assert.equal(report.surface.invalid,0);assert.equal(report.surface.webglError,0);
   const ramps=await p.evaluate(()=>window.__SC2_DEBUG__.world.terrain.definition.ramps.map(r=>{const v=r.mid.match(/[-+]?(?:\d*\.)?\d+(?:[eE][-+]?\d+)?/g).map(Number),d=window.__SC2_DEBUG__.world.terrain.definition;return {x:v[4]-d.origin[0],z:d.origin[1]-v[5]};}));
   for(let i=0;i<ramps.length;i++){await p.evaluate(point=>{const w=window.__SC2_DEBUG__.world;w.stage=12;w.prepareStage();w.cancelOrder();w.entities.clear();w.economicTargets.clear();w.hive=null;w.anchor={...point,facing:0};w.addUnit('marine','terran',point.x,point.z);w.changed();},ramps[i]);await p.waitForTimeout(180);await p.screenshot({path:out+`/ramp-${String(i+1).padStart(2,'0')}.png`});}report.rampScreenshots=ramps.length;
  }report.viewports.push({width,height,touch,minimapMove:true,minimapFocus:true,...layout});await c.close();console.log('Map UI',width,height,'passed');
 }
 if(process.env.SC2_QA_OFFLINE==='1'){const c=await browser.newContext({viewport:{width:1440,height:900},offline:true}),p=await c.newPage(),requests=[];p.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await boot(p,pathToFileURL(process.cwd()+'/dist/SC2-Survivors-Demo.html').href);const goal=await pixel(p,{x:8,z:0});await p.mouse.click(goal.x,goal.y,{button:'right'});assert.equal(await p.evaluate(()=>window.__SC2_REPORT__().order?.kind),'move');await p.waitForTimeout(800);await p.screenshot({path:out+'/offline-file.png'});report.offline={requests,report:await p.evaluate(()=>window.__SC2_REPORT__())};assert.deepEqual(requests,[]);await c.close();}
 assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e.stack??e);process.exitCode=1;console.error(report.failure);}finally{await fs.writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}
