import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';import {encodeGraph} from '../src/persistence/graph-codec';import {writeArchive,readArchive} from '../src/persistence/archive';
import {PermanentProfile} from '../src/simulation/progression/permanent-profile';
import {HERO_IDS_BY_RACE} from '../src/data/heroes';import {tacticalCard} from '../src/data/unique-support';
import {MVP_TALENTS} from '../src/data/mvp-talents';
const out=process.env.SC2_NATIVE_QA_DIR??'reports/local/native-hud-integration-20261010/browser-r1';await fs.mkdir(out,{recursive:true});
const touch=process.argv.includes('--touch'),offline=process.argv.includes('--offline'),offlineFile=path.resolve(process.env.SC2_QA_OFFLINE_HTML??'dist/SC2-Survivors-Native-HUD-20261010.html');
const full=process.argv.includes('--full'),races=full?['terran','protoss','zerg'] as const:['terran'] as const,fixtures:Record<string,string>={};
for(const race of races){const profile=new PermanentProfile();profile.award('diagnostic-profile',1000,race);profile.selectRace(race);
 const allocation=Object.fromEntries(MVP_TALENTS.filter(n=>n.race===race&&(n.line==='army'||touch&&n.line==='micro'&&n.tier<=4)).map(n=>[n.id,n.maxRank]));assert.ok(profile.savePresetBlueprint(race,0,allocation));profile.recordHardCampaignClear(race);
 const w=new World({race,seed:529,waves:false,terrain:campaignTerrain({version:3,seed:529,theme:'industrial'}),permanentProfile:profile});assert.ok(w.start());for(const plan of Object.values(w.expedition.production))plan.enabled={};
 const families=({terran:['marine','marauder','tank','medivac','banshee'],protoss:['zealot','stalker','immortal','colossus','sentry'],zerg:['zergling','roach','hydralisk','ultralisk','lurker']} as const)[race];w.expedition.familySlots=[...families];for(const u of [...w.entities.values()])w.entities.delete(u.id);w.expedition.zerglingPairs=[];for(const family of families){w.expedition.tech['unlock.'+family]=1;for(let i=0;i<7;i++)w.addFamilyMember(family,{x:(i%3-1)*2,z:Math.floor(i/3)*2-4},i%3+1);}w.upgrades.set('stim',1);w.expedition.tech.blink=1;w.expedition.tech.cloak=1;
 if(touch){for(const id of HERO_IDS_BY_RACE[race].slice(0,3))assert.ok(w.acquireHero(id));w.expedition.support.unique.levels[tacticalCard(race)]=1;w.expedition.support.ammo=2;}
 w.paused=true;w.restoreRun(w.captureRun(),true);fixtures[race]=path.resolve(out,race+'.json');await fs.writeFile(fixtures[race],writeArchive({profile:profile.exportJSON(),run:w.captureRun()}));
}
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const browser=offline?null:await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const profilePath=offline?await fs.mkdtemp(path.resolve('.cache/native-hud-offline-')):null;const context=offline?await chromium.launchPersistentContext(profilePath!,{executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,viewport:{width:1440,height:900},hasTouch:touch,args:['--allow-file-access-from-files','--disable-background-timer-throttling','--disable-renderer-backgrounding']}):await browser!.newContext({viewport:{width:1440,height:900},hasTouch:touch}),page=await context.newPage();if(offline)await context.setOffline(true);page.setDefaultTimeout(25000);await context.addInitScript('window.__name=(value)=>value;');
const report:any={offline,profilePath,...(offline?{offlineSha256:createHash('sha256').update(await fs.readFile(offlineFile)).digest('hex')}:{ }),build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Native current-schema diagnostic archives and browser controls; not natural campaign, physical device or performance acceptance.',checks:[],geometry:[],screens:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
async function shot(name:string){await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);}
async function load(race:string){await page.goto(offline?pathToFileURL(offlineFile).href:url,{timeout:600000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:300000});await page.locator('.main-actions [data-action=menu-load]').click();const f=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await f).setFiles(fixtures[race]);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:300000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();await page.locator('.pause-actions [data-action=pause]').click();}
try{
 for(const race of races){await load(race);for(const[width,height]of (touch?[[844,390],[390,844],[320,568]]:[[1440,900],[844,390],[390,844],[320,568]])){await page.setViewportSize({width,height});await page.waitForTimeout(350);if(await page.locator('#army-toggle').getAttribute('aria-expanded')==='false')await page.locator('#army-toggle').click();await page.locator('#roster [data-seat]').first().click();await page.waitForTimeout(100);
 const geometry=await page.evaluate(()=>{const q=(s:string)=>{const e=document.querySelector<HTMLElement>(s)!;return {rect:e.getBoundingClientRect().toJSON(),style:{position:getComputedStyle(e).position,display:getComputedStyle(e).display,grid:getComputedStyle(e).gridTemplateColumns,top:getComputedStyle(e).top,height:getComputedStyle(e).height,area:getComputedStyle(e).gridArea}};};return {mode:document.querySelector<HTMLElement>('#interface')!.dataset.hudMode,roster:q('#roster'),army:q('.army-row'),commands:q('.command-row'),map:q('#minimap'),selection:q('#native-selection'),top:q('#topbar'),canvas:q('#battle'),seats:document.querySelectorAll('#roster [data-seat]').length,utilities:[...document.querySelectorAll('.native-map-utilities button')].map(e=>({label:e.getAttribute('aria-label'),rect:e.getBoundingClientRect().toJSON()}))};});report.geometry.push({race,width,height,...geometry});await shot(`${race}-${width}-open`);
 assert.ok(geometry.seats>0);assert.ok(geometry.selection.rect.y<40,'selected soldier belongs at top right');for(const item of [geometry.roster,geometry.commands,geometry.map,geometry.selection])assert.ok(item.rect.x>=-.6&&item.rect.y>=-.6&&item.rect.right<=width+.6&&item.rect.bottom<=height+.6,JSON.stringify(item));
 const next=page.locator('#army-pages [data-page="1"]');if(await next.isVisible()&&await next.isEnabled())await next.click();const before=await page.locator('#army-pages').textContent(),selected=await page.locator('#native-selection .native-unit-name').textContent();await page.locator('#army-toggle').click();await shot(`${race}-${width}-closed`);assert.equal(await page.locator('#roster').isVisible(),false);await page.locator('#army-toggle').click();assert.equal(await page.locator('#army-pages').textContent(),before);assert.equal(await page.locator('#native-selection .native-unit-name').textContent(),selected);report.checks.push(`${race}/${width}: select, fold, page retention`);
 if(touch){
  const seats=new Set<string>();const previous=page.locator('#army-pages [data-page="-1"]');while(await previous.isVisible()&&await previous.isEnabled())await previous.click();
  while(true){for(const key of await page.locator('#roster [data-seat]').evaluateAll(es=>es.map(e=>e.getAttribute('data-seat')!)))seats.add(key);if(!await next.isVisible()||!await next.isEnabled())break;await next.click();}assert.equal(seats.size,38);
  const skills=new Set<string>();const forward=page.locator('[data-command-page="1"]');while(true){for(const id of await page.locator('[data-command]').evaluateAll(es=>es.map(e=>e.getAttribute('data-command')!)))skills.add(id);if(!await forward.isVisible()||!await forward.isEnabled())break;await forward.click();}
  assert.ok(skills.has('hero-slot-2')&&skills.has('strategic')&&skills.has('tactical')&&skills.has('airlift'));if(race==='terran'&&width<500)assert.ok(skills.size>9,'Terran command page overflow exercised');
  await page.locator('#detection').isVisible().then(async yes=>{if(!yes){const back=page.locator('[data-command-page="-1"]');if(await back.isEnabled())await back.click();}});
  if(await page.locator('#detection').isEnabled())await page.locator('#detection').tap();
  for(const [id,target]of [['airlift','transfer'],['strategic','strategic'],...(race==='protoss'?[['stalker-blink','stalker'],['tactical','tactical']]:[])]){const button=page.locator('[data-command="'+id+'"]');if(!await button.isVisible()){const forward=page.locator('[data-command-page="1"]');if(await forward.isEnabled())await forward.click();}assert.ok(await button.isEnabled(),id);await button.tap();assert.equal(await page.locator('body').getAttribute('data-target-family'),target);await page.locator('[data-transfer-cancel]').tap();assert.equal(await page.locator('body').getAttribute('data-target-family'),null);}
  assert.ok(await page.locator('#joystick').isVisible());const stick=await page.locator('#joystick').boundingBox();assert.ok(stick&&stick.x>=0&&stick.y>=0&&stick.x+stick.width<=width+.5&&stick.y+stick.height<=height+.5);
  const cdp=await context.newCDPSession(page),x=stick!.x+stick!.width/2,y=stick!.y+stick!.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+stick!.width*.3,y}]});await page.waitForTimeout(200);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();
  report.checks.push({race,width,touch:true,allSeats:seats.size,skills:[...skills],joystick:stick});await shot(`${race}-${width}-touch`);
 }

 }
 await page.setViewportSize({width:1440,height:900});await page.locator('.native-map-utilities [data-action=settings]').click();await page.locator('[data-action=settings-tab][data-tab=skins]').click();await shot(`${race}-skins`);assert.equal(await page.locator('.hud-skin-option').count(),6);await page.locator(`[data-action=hud-skin-select][data-race=${race}][data-variant="2"]`).click();await page.locator('[data-action=settings-back]').last().click();await page.waitForTimeout(100);assert.equal(await page.locator('#interface').getAttribute('data-hud-skin'),race+'-02');await shot(`${race}-skin2`);for(const [width,height]of [[844,390],[390,844],[320,568]]){await page.setViewportSize({width,height});await page.waitForTimeout(250);await shot(`${race}-skin2-${width}`);}await page.setViewportSize({width:1440,height:900});
 for(const action of ['battle-progress','battle-base','battle-talents']){await page.locator(`.native-map-utilities [data-action=${action}]`).click();await shot(race+'-'+action);await page.locator('[data-action=battle-panel-close]').last().click();}
 report.checks.push(race+': skin selection and four native utilities');
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=pause-saves]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));
 const exported=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle;};const saved=await exported();const profile=PermanentProfile.parseJSON(saved.profile)!;assert.equal(profile.hudSkin(race),2);assert.ok(profile.hasVeteranHud(race));
 await page.reload({timeout:600000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:600000});await page.locator('.main-actions [data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:600000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();await page.locator('[data-action=pause-saves]').click();const restored=await exported();assert.deepEqual(encodeGraph(restored.run),encodeGraph(saved.run));assert.equal(PermanentProfile.parseJSON(restored.profile)!.hudSkin(race),2);report.checks.push(race+': exact local reload and exported skin');

 }
 assert.deepEqual(report.errors,[]);assert.deepEqual((await page.evaluate(()=>window.__SC2_REPORT__())).errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{report.final=await page.evaluate(()=>window.__SC2_REPORT__?.()).catch(()=>null);await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await context.close();await browser?.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
