import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const url=process.env.SC2_QA_URL??'http://127.0.0.1:5175',out='reports/local/next-p2-20261003';await fs.mkdir(out,{recursive:true});const report={checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let page;
const settle=()=>page.waitForTimeout(230),shown=selector=>page.locator(selector).isVisible();
async function start(race){await page.locator('[data-action=menu-new]').click();await page.locator(`[data-action=menu-race][data-race=${race}]`).click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();await page.locator('[data-action=menu-start]').click();assert.equal(await shown('#minimap'),false);await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});assert.equal(await page.evaluate(()=>window.__SC2_REPORT__().readiness.phase),'ready');await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='battle');await page.evaluate(async()=>{const {world:w,view:v}=window.__SC2_DEBUG__;window.__SC2_DEBUG__.speed=0;w.autoWaves=false;w.wallet={minerals:1000000,gas:1000000};for(const plan of Object.values(w.expedition.production))plan.enabled={};const {HERO_IDS_BY_RACE}=await import('/src/data/heroes.ts'),{FAMILIES_BY_RACE}=await import('/src/data/races.ts');w.expedition.familySlots=FAMILIES_BY_RACE[w.expedition.race].slice(0,5);for(const family of w.expedition.familySlots)if(!w.familyUnits(family).length)w.addUnit(family,'terran',0,1);for(const id of HERO_IDS_BY_RACE[w.expedition.race].slice(0,3))w.acquireHero(id);w.changed();await v.prepareRosterAssets();w.changed();});await settle();}

try{
 page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});page.on('pageerror',e=>report.errors.push(e.message));
 await page.addInitScript(()=>{const pad={id:'P2 virtual standard',index:0,mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({value:0}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[pad]});window.__P2_PAD__=pad;});
 await page.goto(url);await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await start('terran');
 await page.evaluate(async()=>{const {world:w,view:v}=window.__SC2_DEBUG__;w.expedition.tech['unlock.hellion']=w.expedition.tech.cloak=w.expedition.tech.blink=1;w.upgrades.set('stim',1);w.runConfig.frozenTalents.levels['T-M04']=1;w.expedition.support.ammo=2;for(const f of ['viking','thor','lurker','banshee','stalker'])w.addUnit(f,'terran',w.anchor.x+2,w.anchor.z+2);w.changed();await v.prepareRosterAssets();w.changed();});await settle();
 await page.waitForFunction(()=>document.body.dataset.battleActionsReady==='true');await page.locator('#map-toggle').focus();await page.keyboard.press('v');assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.expedition.familyModes.viking),'viking_assault');await page.keyboard.press('v');assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.expedition.familyModes.viking),'viking');report.checks.push('V works with minimap focus; second edge cancels pending landing');
 await page.locator('[data-action=viking-mode]').focus();const before=await page.evaluate(()=>window.__SC2_DEBUG__.world.dashReady);await page.keyboard.press('Space');assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.dashReady),before);assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.expedition.familyModes.viking),'viking_assault');report.checks.push('Space on focused command invokes only that button');
 await page.keyboard.press('g');await page.keyboard.press('e');assert.ok(await page.evaluate(()=>window.__SC2_DEBUG__.world.familyBodies('marine').some(u=>u.stimUntil>0)));await page.evaluate(()=>window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyV',repeat:true,bubbles:true})));assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.expedition.familyModes.viking),'viking_assault');report.checks.push('different consecutive shortcuts both execute; auto-repeat does not toggle');
 // Two real synthesized touch clicks must not share a global suppression timer.
 await page.locator('[data-action=viking-mode]').tap();await page.locator('[data-action=thor-mode]').tap();assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.expedition.familyModes.thor),'thor_high_impact');report.checks.push('consecutive touch clicks on different commands are both applied');
 await page.locator('#map-toggle').focus();await page.keyboard.press('b');await page.keyboard.press('Enter');assert.equal(await shown('#transfer-picker'),false);assert.ok(await page.evaluate(()=>window.__SC2_DEBUG__.world.familyBodies('stalker').some(u=>u.abilityReady>0)));await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;for(const u of w.familyBodies('stalker'))u.abilityReady=0;w.changed();});report.checks.push('Enter confirms blink target exactly once and starts its existing cooldown');
 await page.keyboard.press('b');await page.locator('#transfer-picker [data-transfer-cancel]').focus();await page.keyboard.press('Enter');assert.equal(await shown('#transfer-picker'),false);assert.ok(await page.evaluate(()=>window.__SC2_DEBUG__.world.familyBodies('stalker').every(u=>u.abilityReady===0)));report.checks.push('Enter on focused target cancel cancels without casting');
 for(const key of ['b','f','x']){await page.keyboard.press(key);assert.equal(await shown('#transfer-picker'),true);assert.equal(await page.locator('#transfer-picker [data-transfer-cancel]').count(),1);await page.keyboard.press('Escape');assert.equal(await shown('#transfer-picker'),false);}report.checks.push('blink, transfer and strategic target panels expose cancel; Esc leaves them without commit');
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.expedition.race='protoss';w.changed();});
 // Use the actual tactical card identity, without inventing a runtime alias.
 await page.evaluate(async()=>{const w=window.__SC2_DEBUG__.world,{tacticalCard}=await import('/src/data/unique-support.ts');w.expedition.support.unique.levels[tacticalCard('protoss')]=1;w.changed();});await page.keyboard.press('q');assert.equal(await shown('#transfer-picker'),true);await page.locator('[data-transfer-cancel]').click();report.checks.push('Protoss tactical targeting has visible confirm and cancel');
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.expedition.race='terran';w.changed();});await page.keyboard.press('o');assert.ok(await page.evaluate(()=>window.__SC2_DEBUG__.world.paused));await page.locator('[data-action=unit-mode][data-family=viking][data-mode=viking]').click();assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.paused),false);report.checks.push('operations pauses and valid explicit mode resumes');
 for(const [width,height] of [[1440,900],[390,844],[844,390],[667,375]])for(const scale of [1,1.5]){await page.setViewportSize({width,height});await page.evaluate(async scale=>(await import('/src/ui/text-scale.ts')).setTextScale(scale),scale);await settle();const metrics=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,buttons:[...document.querySelectorAll('#skills button:not([hidden])')].map(b=>{const r=b.getBoundingClientRect();return [r.width,r.height];})}));assert.ok(metrics.scroll<=width+1);assert.ok(metrics.buttons.every(([w,h])=>w>=43.5&&h>=43.5));await page.screenshot({path:`${out}/commands-${width}x${height}-${scale}.png`});}report.checks.push('8 viewport/text-scale states retain 44px command buttons without document overflow');
 await page.setViewportSize({width:1440,height:900});await settle();await page.evaluate(()=>{window.__P2_PAD__.buttons[7].value=1;});await page.waitForFunction(()=>window.__SC2_REPORT__().gamepad.skillPage===1);await page.evaluate(()=>window.__P2_PAD__.buttons[7].value=0);await settle();await page.evaluate(()=>window.__P2_PAD__.buttons[6].value=1);await page.waitForFunction(()=>window.__SC2_REPORT__().gamepad.skillPage===0);await page.evaluate(()=>window.__P2_PAD__.buttons[6].value=0);report.checks.push('virtual standard LT/RT flips six-sector pages without automatic cast');
 await page.evaluate(()=>{window.__P2_PAD__.axes[2]=Math.sqrt(3)/2;window.__P2_PAD__.axes[3]=.5;});await page.waitForFunction(()=>window.__SC2_REPORT__().gamepad.selectedSkill==='detection');await page.waitForFunction(()=>document.querySelector('#pad-skill-picker strong')?.textContent.includes('冷却'));assert.ok(!(await page.locator('#pad-skill-picker strong').innerText()).includes('未获得'));report.checks.push('gamepad cooling action displays the shared cooldown reason');
 assert.deepEqual(report.errors,[]);
}catch(error){report.failure=String(error.stack??error);process.exitCode=1;if(page)await page.screenshot({path:out+'/failure.png'});}
finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
