import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const url=process.env.SC2_QA_URL??'http://127.0.0.1:5175',out=process.env.QA_OUT??'reports/local/next-p1-20261003-r3';await fs.mkdir(out,{recursive:true});
const report={method:'Local Chrome viewport/touch emulation with actual UI and World; debug fixtures freeze combat for layout checks. No physical phone, Coze host, human acceptance or natural combat evidence.',layouts:[],checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});let page;
const settle=()=>page.waitForTimeout(230);
const shown=async selector=>page.locator(selector).isVisible();
async function start(race){await page.locator('[data-action=menu-new]').click();await page.locator(`[data-action=menu-race][data-race=${race}]`).click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();await page.locator('[data-action=menu-start]').click();assert.equal(await shown('#minimap'),false);await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});assert.equal(await page.evaluate(()=>window.__SC2_REPORT__().readiness.phase),'ready');await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='battle');await page.evaluate(async()=>{const {world:w,view:v}=window.__SC2_DEBUG__;window.__SC2_DEBUG__.speed=0;w.autoWaves=false;w.wallet={minerals:1000000,gas:1000000};for(const plan of Object.values(w.expedition.production))plan.enabled={};const {HERO_IDS_BY_RACE}=await import('/src/data/heroes.ts'),{FAMILIES_BY_RACE}=await import('/src/data/races.ts');w.expedition.familySlots=FAMILIES_BY_RACE[w.expedition.race].slice(0,5);for(const family of w.expedition.familySlots)if(!w.familyUnits(family).length)w.addUnit(family,'terran',0,1);for(const id of HERO_IDS_BY_RACE[w.expedition.race].slice(0,3))w.acquireHero(id);w.changed();await v.prepareRosterAssets();});await settle();}
async function fold(id,collapsed){const button=page.locator(id);if(await button.getAttribute('aria-expanded')===String(collapsed))await button.click();await settle();}
async function layout(race,scale,width,height){const row=await page.evaluate(()=>{
 const r=id=>{const el=document.querySelector(id),b=el.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height,right:b.right,bottom:b.bottom};};const buttons=[...document.querySelectorAll('#console-commands button:not([hidden]),#map-toggle,#army-toggle')].filter(el=>el.getBoundingClientRect().height>0);
 return {root:r('#game-root'),canvas:r('#battle'),console:r('#battle-console'),header:r('#topbar'),mission:r('#mission'),map:r('#minimap'),minimapCanvas:r('#minimap-canvas'),heroes:r('#hero-skills'),commands:r('#skills'),scroll:document.documentElement.scrollWidth,paused:window.__SC2_DEBUG__.world.paused,folds:[document.querySelector('#map-toggle').getAttribute('aria-expanded'),document.querySelector('#army-toggle').getAttribute('aria-expanded')],buttons:buttons.map(el=>({id:el.id,w:el.getBoundingClientRect().width,h:el.getBoundingClientRect().height})),cameraAspect:(window.__SC2_DEBUG__.view.camera.right-window.__SC2_DEBUG__.view.camera.left)/(window.__SC2_DEBUG__.view.camera.top-window.__SC2_DEBUG__.view.camera.bottom)};
 });assert.ok(row.scroll<=width+1,JSON.stringify(row));assert.ok(Math.abs(row.root.w-width)<1&&Math.abs(row.root.h-height)<1,JSON.stringify(row));assert.ok(Math.abs(row.canvas.bottom-row.console.y)<2,JSON.stringify(row));assert.ok(row.canvas.h>70,JSON.stringify(row));assert.ok(row.map.right<=row.header.x+1,JSON.stringify(row));assert.ok(row.mission.y>=row.header.bottom+7,JSON.stringify(row));assert.ok(Math.abs(row.cameraAspect-row.canvas.w/row.canvas.h)<.02,JSON.stringify(row));assert.ok(row.heroes.w>=100&&row.commands.w>=100,JSON.stringify(row));assert.ok(row.heroes.bottom<=height+1&&row.commands.bottom<=height+1,JSON.stringify(row));assert.equal(row.paused,false);for(const b of row.buttons)assert.ok(b.w>=43.5&&b.h>=43.5,JSON.stringify(b));report.layouts.push({race,scale,width,height,...row});}
try{
 page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true});page.on('pageerror',e=>report.errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await shown('#minimap'),false);assert.equal(await shown('#battle-console'),false);
 await page.locator('[data-action=fullscreen]').click();report.fullscreen={entered:await page.evaluate(()=>!!document.fullscreenElement)};if(report.fullscreen.entered)await page.evaluate(()=>document.exitFullscreen());await settle();report.fullscreen.exited=await page.evaluate(()=>!document.fullscreenElement);
 for(const race of ['terran','zerg','protoss']){
  await start(race);const runBefore=await page.evaluate(()=>JSON.stringify(window.__SC2_DEBUG__.world.captureRun()));await page.locator('#map-toggle').focus();await page.keyboard.press('Space');await settle();await page.keyboard.press('Enter');await settle();assert.equal(await page.evaluate(()=>JSON.stringify(window.__SC2_DEBUG__.world.captureRun())),runBefore);report.checks.push(race+': keyboard folding changes no battle snapshot or skill cooldown');
  for(const [width,height] of [[1440,900],[390,844],[844,390],[667,375]])for(const scale of [1,1.5]){
   await page.setViewportSize({width,height});await page.evaluate(async scale=>(await import('/src/ui/text-scale.ts')).setTextScale(scale),scale);await settle();
   for(const [map,army] of [[false,false],[true,false],[false,true],[true,true]]){await fold('#map-toggle',map);await fold('#army-toggle',army);await layout(race,scale,width,height);if(!map&&!army&&scale===1)await page.screenshot({path:`${out}/${race}-${width}x${height}-expanded.png`});}
   await page.screenshot({path:`${out}/${race}-${width}x${height}-${scale}-folded.png`});
  }
  console.log(`${race}: 32 layout states checked`);await page.evaluate(async()=>(await import('/src/ui/text-scale.ts')).setTextScale(1));await page.setViewportSize({width:390,height:844});await fold('#map-toggle',false);await fold('#army-toggle',false);
  if(race==='terran'){const pinch=await page.context().newCDPSession(page);await pinch.send('Input.synthesizePinchGesture',{x:250,y:300,scaleFactor:1.25,gestureSourceType:'touch'});await settle();const viewport=await page.evaluate(()=>{const r=document.querySelector('#game-root').getBoundingClientRect(),labels=document.querySelector('#pod-labels').getBoundingClientRect();return {root:[r.x,r.y,r.width,r.height],labels:[labels.x,labels.y],visual:[visualViewport.offsetLeft,visualViewport.offsetTop,visualViewport.width,visualViewport.height]};});for(let i=0;i<4;i++)assert.ok(Math.abs(viewport.root[i]-viewport.visual[i])<1,JSON.stringify(viewport));assert.ok(Math.abs(viewport.labels[0]-viewport.root[0])<1&&Math.abs(viewport.labels[1]-viewport.root[1])<1,JSON.stringify(viewport));report.checks.push({pinchViewport:viewport});await pinch.send('Emulation.setPageScaleFactor',{pageScaleFactor:1});await pinch.detach();await settle();}
  // A captured touch must not issue a stale move when geometry changes.
  const point=await page.locator('#joystick').boundingBox(),cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:77,x:point.x+point.width*.8,y:point.y+point.height*.5}]});await page.waitForFunction(()=>window.__SC2_DEBUG__.world.input.x>.1);
  await page.setViewportSize({width:844,height:390});await settle();const input=await page.evaluate(()=>({input:window.__SC2_DEBUG__.world.input,stick:getComputedStyle(document.querySelector('#joystick')).getPropertyValue('--stick-x'),paused:window.__SC2_DEBUG__.world.paused}));assert.deepEqual(input.input,{x:0,z:0});assert.equal(parseFloat(input.stick),0);assert.equal(input.paused,false);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();report.checks.push({race,rotation:input});
  await page.locator('#topbar [data-action=pause]').click();await settle();assert.equal(await shown('#minimap'),false);const paused=await page.evaluate(()=>window.__SC2_DEBUG__.world.paused);await page.setViewportSize({width:390,height:844});await settle();assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.paused),paused);await page.locator('.end-screen [data-action=pause]').click();await settle();
  // Fold/unfold preserves inspection and the selected roster page.
  await page.evaluate(()=>{const {world:w}=window.__SC2_DEBUG__;const families=w.expedition.race==='terran'?['marauder','reaper']:w.expedition.race==='zerg'?['roach','baneling']:['stalker','adept'];for(const family of families)if(!w.expedition.familySlots.includes(family)&&w.expedition.familySlots.length<5){w.expedition.familySlots.push(family);w.addUnit(family,'terran',0,1);}w.changed();});await settle();
  await page.locator('#army-pages [data-page="1"]').click();await page.locator('.squad-seat:not(.empty-seat)').first().click();const selected=await page.locator('.squad-seat[aria-pressed=true]').getAttribute('data-seat'),pager=await page.locator('#army-pages span').innerText();await fold('#army-toggle',true);assert.equal(await shown('#unit-inspector'),false);await fold('#army-toggle',false);assert.equal(await page.locator('.squad-seat[aria-pressed=true]').getAttribute('data-seat'),selected);assert.equal(await page.locator('#army-pages span').innerText(),pager);assert.equal(await shown('#unit-inspector'),true);await page.locator('[data-inspect-close]').click();
  // Real intermission generation; rendering changes must not reroll paid goods or prices.
  await page.evaluate(()=>window.__SC2_DEBUG__.world.endStage());await page.locator('[data-action=development-direction]').first().click();await page.locator('[data-action=skip]').click();await page.waitForFunction(()=>window.__SC2_DEBUG__.world.rewardRound==='random');
  const offers=await page.evaluate(()=>JSON.stringify(window.__SC2_DEBUG__.world.rewards));
  for(const [width,height] of [[1440,900],[390,844],[844,390],[667,375]]){
   await page.setViewportSize({width,height});await settle();assert.equal(await shown('#minimap'),false);assert.equal(await shown('#battle-console'),false);
   for(const expanded of [false,true]){
    if(expanded)await page.locator('.offer-details summary').first().click();
    const shop=await page.evaluate(()=>{const r=el=>{const b=el.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height,right:b.right,bottom:b.bottom};};const cards=[...document.querySelectorAll('#reward-cards .reward-card')];return {wallet:r(document.querySelector('#topbar')),overlay:r(document.querySelector('#overlay')),content:r(document.querySelector('.intermission-content')),actions:r(document.querySelector('.reward-actions')),continue:r(document.querySelector('[data-action=skip]')),cards:cards.map(c=>({number:r(c.querySelector('.card-number')),title:r(c.querySelector('h3')),price:r(c.querySelector('strong'))})),scroll:document.documentElement.scrollWidth};});
    assert.ok(shop.scroll<=width+1,JSON.stringify(shop));assert.ok(shop.overlay.y>=shop.wallet.bottom-1,JSON.stringify(shop));assert.ok(shop.content.bottom<=shop.actions.y+1,JSON.stringify(shop));assert.ok(shop.continue.bottom<=height+1&&shop.continue.h>=44,JSON.stringify(shop));for(const c of shop.cards)assert.ok(c.number.bottom<=c.title.y+1,JSON.stringify(c));assert.equal(await page.evaluate(()=>JSON.stringify(window.__SC2_DEBUG__.world.rewards)),offers);report.checks.push({race,width,height,expanded,shop});await page.screenshot({path:`${out}/${race}-shop-${width}x${height}-${expanded}.png`});if(expanded)await page.locator('.offer-details summary').first().click();
   }
  }
  await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.phase='battle';w.paused=true;w.changed();});await page.locator('[data-action=restart]').click();await settle();
 }
 // Preferences survive a page reload, independently of loading/starting another battle.
 await start('terran');await fold('#map-toggle',true);await fold('#army-toggle',true);const saved=await page.evaluate(()=>localStorage.getItem('sc2.hud.v1'));await page.reload();await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>localStorage.getItem('sc2.hud.v1')),saved);await start('terran');assert.equal(await page.locator('#map-toggle').getAttribute('aria-expanded'),'false');assert.equal(await page.locator('#army-toggle').getAttribute('aria-expanded'),'false');report.checks.push('independent folds survive title, next battle and page reload');
 const host=await browser.newPage({viewport:{width:844,height:650}});host.on('pageerror',e=>report.errors.push('iframe: '+e.message));await host.route('**/p1-iframe-host',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><body style="margin:0"><iframe title="game" src="${url}" style="border:0;width:390px;height:600px;margin:20px" allow="fullscreen"></iframe></body></html>`}));await host.goto(url+'/p1-iframe-host');const frame=host.frames().find(f=>f.parentFrame());await frame.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:120000});const metrics=await frame.evaluate(()=>{const r=document.querySelector('#game-root').getBoundingClientRect();return {inner:[innerWidth,innerHeight],root:[r.x,r.y,r.width,r.height],visual:[visualViewport.width,visualViewport.height]};});assert.deepEqual(metrics.inner,[390,600]);assert.deepEqual(metrics.root,[0,0,390,600]);report.iframe={...metrics,hostMargin:'Intentional 20px host margin remains outside the game; local fixture, not Coze.'};await host.screenshot({path:out+'/iframe.png'});await host.close();assert.deepEqual(report.errors,[]);
}catch(error){report.failure=String(error.stack??error);process.exitCode=1;if(page){await page.screenshot({path:out+'/failure.png'});report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());}}
finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({layouts:report.layouts.length,checks:report.checks.length,fullscreen:report.fullscreen,iframe:report.iframe,failure:report.failure??null,errors:report.errors}));}
