import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {createGameServer} from './coze-web-server.mjs';import {World} from '../src/simulation/world';import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {writeArchive,readArchive} from '../src/persistence/archive';import {ELITES} from '../src/data/elites';
import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';import {HERO_IDS_BY_RACE,HEROES} from '../src/data/heroes';
const out='reports/local/opening-cover-flame-20261007/browser';await fs.mkdir(out,{recursive:true});
const server=createGameServer({webRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const url='http://127.0.0.1:'+(server.address() as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const report:any={at:new Date().toISOString(),appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],screens:[],errors:[],method:'Production Web, isolated preference state and diagnostic archives; not earned campaigns or physical-device acceptance.'};
let active:any;
const shot=async(page:any,name:string)=>{await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);};
const ready=async(page:any)=>{const start=Date.now();for(;;){try{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:30000});break;}catch(e){console.log('preparation '+JSON.stringify((await page.evaluate(()=>window.__SC2_REPORT__())).readiness));if(Date.now()-start>240000)throw e;}}assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');};
try{
 for(const [width,height]of [[1280,720],[390,844],[844,390],[883,850]]){
  const context=await browser.newContext({viewport:{width,height},hasTouch:width===390,reducedMotion:'reduce'});active=context;const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
  let release!:()=>void;const held=new Promise<void>(r=>{release=r;});await page.route('**/assets/index-*.js',async route=>{await held;await route.continue();});await page.goto(url,{waitUntil:'commit'});
  await page.locator('#scs-opening-visual .scs-title img').waitFor();await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('#scs-opening-visual img')].every(i=>i.complete&&i.naturalWidth>0));
  const geometry=await page.locator('#scs-opening-visual').evaluate(root=>{const image=root.querySelector('.scs-title')!.getBoundingClientRect(),loader=root.querySelector('.scs-loader')!.getBoundingClientRect(),b=root.getBoundingClientRect();return {viewport:[b.width,b.height],logo:[image.x,image.y,image.width,image.height],loader:[loader.x,loader.y,loader.width,loader.height],portrait:root.querySelector('.scs-screen')!.classList.contains('scs-portrait'),images:[...root.querySelectorAll<HTMLImageElement>('img')].map(i=>i.naturalWidth),reduced:[...root.querySelectorAll<HTMLElement>('.scs-orbit,.scs-background')].every(i=>getComputedStyle(i).animationName==='none')};});
  assert.deepEqual(geometry.viewport,[width,height]);assert.equal(geometry.portrait,height>width);assert.equal(geometry.reduced,true);assert.ok(geometry.logo[1]+geometry.logo[3]<geometry.loader[1]);assert.ok(geometry.loader[1]+geometry.loader[3]<=height);await shot(page,'opening-'+width+'x'+height);report.checks.push({opening:width+'x'+height,geometry});
  await page.evaluate(()=>document.dispatchEvent(new CustomEvent('sc2-opening-progress',{detail:{value:68,phase:'loading'}})));assert.equal(await page.locator('.scs-percent').innerText(),'68%');await shot(page,'opening-progress-'+width+'x'+height);
  release();await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('#scs-opening-visual').waitFor({state:'detached'});assert.equal(await page.locator('#game-root').getAttribute('inert'),null);
  assert.equal(await page.locator('[data-action=cover-prev],[data-action=cover-next],[data-action=cover-select],[data-action=cover-auto],.cover-controls').count(),0);assert.equal(await page.locator('.game-brand-logo').count(),1);assert.equal(await page.locator('.home-profile,.signal-readout').count(),0);
  let src=await page.locator('.home-brand-logo').getAttribute('src');await shot(page,'home-'+width+'x'+height);
  for(const race of ['terran','zerg','protoss']){await page.locator('[data-action=cover-race][data-race='+race+']').click();assert.equal(await page.locator('[data-action=cover-race][data-race='+race+']').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#interface').getAttribute('data-race'),race);}
  await page.reload();await page.locator('#scs-opening-visual').waitFor({state:'detached'});src=await page.locator('.home-brand-logo').getAttribute('src');assert.equal(await page.locator('#interface').getAttribute('data-race'),'protoss');await page.locator('[data-action=cover-race][data-race=protoss]').click();assert.equal(await page.locator('#interface').getAttribute('data-race'),'terran');
  await page.locator('[data-action=menu-new]').click();assert.equal(await page.locator('.masthead .game-brand-logo').getAttribute('src'),src);await shot(page,'race-logo-'+width+'x'+height);
  const initialTroops=[];
  for(const [race,family,bodies]of [['zerg','zergling',2],['protoss','zealot',1],['terran','marine',1]]as const){
   await page.locator('[data-action=menu-race][data-race='+race+']').click();await page.locator('[data-action=menu-race-next]').click();assert.equal(await page.locator('.game-brand-logo').count(),1);assert.equal(await page.locator('.masthead .game-brand-logo').getAttribute('src'),src);await page.locator('[data-action=menu-difficulty-next]').click();assert.equal(await page.locator('.game-brand-logo').count(),1);assert.equal(await page.locator('.masthead .game-brand-logo').getAttribute('src'),src);
   assert.equal(await page.locator('.starting-roster>img').count(),0);const art=page.locator('.starting-art .im-unit-painting');assert.equal(await art.getAttribute('data-art-key'),family);assert.equal(await art.getAttribute('data-body-count'),String(bodies));assert.equal(await art.locator('image').count(),bodies);
   const geometry=await page.locator('.starting-roster').evaluate(root=>{const art=root.querySelector('.starting-art')!.getBoundingClientRect(),copy=root.querySelector(':scope>div:last-child')!.getBoundingClientRect(),panel=root.closest('.config-panel')!.getBoundingClientRect();return {art:[art.x,art.y,art.width,art.height],copy:[copy.x,copy.y,copy.width,copy.height],panel:[panel.x,panel.y,panel.width,panel.height]};});assert.ok(geometry.art[2]>0&&geometry.art[3]>0);assert.ok(geometry.art[0]+geometry.art[2]<=geometry.copy[0]);assert.ok(geometry.copy[0]+geometry.copy[2]<=geometry.panel[0]+geometry.panel[2]);initialTroops.push({race,family,bodies,geometry});await shot(page,race==='terran'?'deployment-logo-'+width+'x'+height:'deployment-'+race+'-'+width+'x'+height);
   if(race!=='terran'){await page.locator('[data-action=menu-back]').click();await page.locator('[data-action=menu-back]').click();}
  }
  report.checks.push({menu:width+'x'+height,controlsRemoved:true,homeAuxiliaryRowRemoved:true,oneLogoPerPage:true,initialTroops,lockSurvivesReload:true,allMenuLogosMatch:true});await context.close();active=null;
 }
 const context=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true});active=context;const page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 await context.addInitScript(()=>localStorage.setItem('sc2.cover-preference.v1',JSON.stringify({version:1,starts:{terran:1,zerg:4,protoss:2},lastRace:'protoss',lockedRace:null})));
 await page.goto(url);await page.locator('#scs-opening-visual').waitFor({state:'detached'});assert.equal(await page.locator('#interface').getAttribute('data-race'),'zerg');report.checks.push('Most-used race selected independently of current profile race');
 const first=await page.locator('.cover-layer.is-active').getAttribute('data-cover-id');await page.waitForTimeout(18500);const rotated=await page.locator('.cover-layer.is-active').getAttribute('data-cover-id');assert.notEqual(rotated,first);await page.locator('[data-action=cover-race][data-race=zerg]').click();await page.mouse.move(0,0);await page.waitForTimeout(18500);assert.equal(await page.locator('.cover-layer.is-active').getAttribute('data-cover-id'),rotated);report.checks.push('Idle cover rotates automatically; upper race lock stops rotation');
 const w=new World({race:'terran',seed:10707,waves:false,terrain:campaignTerrain(chooseCampaignMap(10707))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.expedition.familySlots=['hellion'];w.expedition.tech['unlock.hellion']=1;w.wallet={minerals:10000,gas:10000};for(const p of Object.values(w.expedition.production))p.enabled={};
 const ordinary=w.addFamilyMember('hellion',{x:0,z:2},1)!;const knight=w.addUnit('hellion','terran',0,0);knight.eliteId='hellion.2';knight.modelKey=ELITES['hellion.2'].model;w.refreshStats(knight,true);const target=w.addUnit('roach','zerg',2,0);target.hp=target.maxHp=100000;target.armor=0;target.nextShotAt=target.specialReady=1e9;target.moveSpeed=0;w.hash.rebuild(w.entities.values());w.fire(knight,target);w.paused=true;
 const fixture=path.resolve(out,'hellion.json');await fs.writeFile(fixture,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));
 await page.locator('.main-actions [data-action=menu-load]').click();const picker=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await picker).setFiles(fixture);await page.locator('[data-action=menu-load-ready]').click();await ready(page);await page.locator('[data-action=flow-continue]').click();
 const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();const loaded=readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;assert.ok(Math.abs(loaded.state.entities.get(knight.id)!.attackRange-10/3)<1e-8);await shot(page,'knight-flame-paused');
 await page.locator('.pause-actions [data-action=pause]').click();await page.locator('#unit-operations').click();await page.locator('[data-action=unit-mode][data-family=hellion][data-mode=hellbat]').click();await page.waitForFunction(()=>document.getElementById('hellion-mode')?.dataset.actionState==='active',null,{timeout:60000});await page.locator('#topbar [data-action=pause]').click();
 const switched=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();const after=readArchive(await fs.readFile(await(await switched).path(),'utf8')).bundle.run!;const k=after.state.entities.get(knight.id)!,normal=after.state.entities.get(ordinary.id)!;assert.equal(k.nativeMode,'hellbat');assert.ok(Math.abs(k.attackRange-4/3)<1e-8);assert.equal(normal.nativeMode,'hellbat');assert.equal(normal.attackRange,2);await shot(page,'hellbat-mode');report.checks.push('Actual ordinary/elite mode command retained; ordinary range2, knight range4/3 after switching; current save exports correctly');
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('sc2.cover-preference.v1')!).starts),{terran:1,zerg:4,protoss:2});
 await page.locator('[data-action=restart]').click();const profile=new PermanentProfile(200);for(const race of ['terran','zerg','protoss']as const){if(race!=='terran')assert.equal(profile.award('qa-opening-'+race,200,race),true);const levels=Object.fromEntries(MVP_TALENTS.filter(t=>t.race===race&&t.line==='resources').map(t=>[t.id,t.maxRank]));assert.equal(profile.savePresetBlueprint(race,0,levels),true);}assert.equal(profile.selectRace('terran'),true);
 const heroArchive=path.resolve(out,'heroes-profile.json');await fs.writeFile(heroArchive,writeArchive({profile:profile.exportJSON(),run:null}));await page.locator('.main-actions [data-action=menu-load]').click();const heroPicker=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await heroPicker).setFiles(heroArchive);await page.locator('[data-action=menu-load-ready]').click();await ready(page);await page.locator('[data-action=flow-continue]').click();await page.locator('.load-modal .modal-footer [data-action=menu-back]').click();await page.locator('[data-action=menu-back]').click();await page.locator('[data-action=menu-new]').click();const heroes=[];
 for(const race of ['terran','zerg','protoss']as const){await page.locator('[data-action=menu-race][data-race='+race+']').click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();for(const hero of HERO_IDS_BY_RACE[race]){await page.locator('[data-setting=menu-hero]').scrollIntoViewIfNeeded();await page.locator('[data-setting=menu-hero]').selectOption(hero);assert.equal(await page.locator('.starter-hero-roster b').innerText(),HEROES[hero].name+' Ⅱ');assert.equal(await page.locator('.starter-unit-roster').count(),1);assert.equal(await page.locator('.starter-hero-roster').count(),1);const portrait=page.locator('.starter-hero-roster .starting-art');assert.equal(await portrait.locator('.painted-art').count(),1);assert.ok(await portrait.locator('img,image').count()>0);heroes.push(hero);}await shot(page,'deployment-hero-'+race);await page.locator('[data-action=menu-back]').click();await page.locator('[data-action=menu-back]').click();}
 assert.equal(heroes.length,18);report.checks.push({heroChoices:heroes,usesExistingPaintedArt:true,actualProfileImport:true,ordinaryCountAndHeroSelectionPreserved:true});assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{if(active)await active.close().catch(()=>{});await browser.close();await new Promise<void>(r=>server.close(()=>r()));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
