import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';import {createGameServer} from './coze-web-server.mjs';import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';import {tickHeroAttacks} from '../src/simulation/combat/hero-attack-upgrades';import {tickProtossHero,tickProtossHeroState,protossState} from '../src/simulation/combat/protoss-hero-passives';import {initializeCarrierSubsystem,ownedInterceptors} from '../src/simulation/combat/carriers';import {HEROES,type HeroId} from '../src/data/heroes';import {HERO_GROUND_AURAS} from '../src/data/hero-upgrades';import type {Entity} from '../src/simulation/types';
const out=process.env.QA_OUT??'reports/local/protoss-effects-correction-20261005/production';await fs.mkdir(out,{recursive:true});
const groups:HeroId[][]=process.env.QA_OFFLINE_HTML?[['fenix','vorazun','purifier_flagship']]:[['artanis','zeratul','alarak'],['fenix','vorazun','purifier_flagship']];
function advance(w:World,n:number){for(let i=0;i<n;i++){w.time+=1/60;w.tick++;resolveExpeditionHeroCasts(w);tickHeroAttacks(w);tickProtossHeroState(w);}}
function fixture(heroes:HeroId[]){const w=new World({race:'protoss',seed:10507,waves:false,terrain:campaignTerrain(chooseCampaignMap(10507))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.time=10;w.tick=600;w.wallet.minerals=0;for(const p of Object.values(w.expedition.production))p.enabled={};const enemies=new Map<HeroId,Entity>();
 for(const id of heroes){assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!;u.rank=5;w.heroes.get(id)!.rank=5;w.refreshStats(u,true);const p=w.freePosition('roach',u,['artanis','zeratul','alarak','vorazun'].includes(id)?1.3:3,['artanis','zeratul','alarak','vorazun'].includes(id)?1.8:4.8);assert.ok(p,'legal target '+id);const e=w.addUnit('roach','zerg',p.x,p.z);e.hp=e.maxHp=2e6;e.armor=0;e.stoppedUntil=1e9;e.specialReady=1e9;e.moveSpeed=0;e.nextShotAt=1e9;enemies.set(id,e);}
 w.expedition.familySlots=['stalker','zealot'];const center=w.heroEntity(heroes[0])!;for(let i=0;i<4;i++){const p=w.freePosition('stalker',center,1,5.3);assert.ok(p);const a=w.addUnit('stalker','terran',p.x,p.z,3);a.shield=0;a.stoppedUntil=1e9;}
 w.hash.rebuild(w.entities.values());
 if(heroes.includes('artanis')){const a=w.heroEntity('artanis')!;a.shield!-=a.maxShield!*.6;assert.ok(w.castHero('artanis'));const al=w.heroEntity('alarak')!,target=enemies.get('alarak')!;target.enemyTier='boss';for(let i=0;i<3;i++){w.fire(al,target);advance(w,9);}assert.ok(protossState(al).power>0);const z=w.heroEntity('zeratul')!;for(let i=0;i<4;i++){w.fire(z,enemies.get('zeratul')!);advance(w,9);}assert.ok(w.protossHeroes.echoes.length>0);assert.ok(w.castHero('alarak'));}
 else{initializeCarrierSubsystem(w);const f=w.heroEntity('fenix')!,v=w.heroEntity('vorazun')!,flag=w.heroEntity('purifier_flagship')!;w.hit(f,f.maxShield!+100,[],1,'zerg',0,1,enemies.get('fenix')!.id);w.hit(flag,500,[],1,'zerg',0,1,enemies.get('purifier_flagship')!.id);assert.ok(protossState(f).overdriveUntil>w.time);assert.ok(protossState(flag).overdriveUntil>w.time);for(const a of w.allies())if(!a.heroId&&!a.summonKind)tickProtossHero(w,a,0);assert.ok(w.allies().some(a=>a.protossCombat?.veilUntil));assert.ok(w.castHero('vorazun'));assert.ok(w.castHero('purifier_flagship'));assert.ok(w.castHero('fenix'));for(const child of ownedInterceptors(w,flag.id))w.fire(child,enemies.get('purifier_flagship')!);assert.equal(ownedInterceptors(w,flag.id).length,12);}
 if(heroes.includes('purifier_flagship')){advance(w,66);const carrier=w.heroEntity('purifier_flagship')!;w.fire(ownedInterceptors(w,carrier.id)[0],enemies.get('purifier_flagship')!);}
 for(const id of heroes){const u=w.heroEntity(id)!;if(id!=='purifier_flagship')w.fire(u,enemies.get(id)!);u.stoppedUntil=1e9;}w.time+=3/60;w.tick+=3;w.paused=true;const before=w.captureRun();assert.equal(before.schema,21);assert.ok(before.state.heroAttacks.packets.length>=3);return {w,before};}
const fixtures=[];for(const heroes of groups){const f=fixture(heroes),file=path.resolve(out,heroes[0]+'.json');await fs.writeFile(file,writeArchive({profile:f.w.permanentProfile.exportJSON(),run:f.before}));fixtures.push({...f,heroes,file});}
if(process.argv.includes('--fixtures-only')){console.log(JSON.stringify(fixtures.map(f=>({heroes:f.heroes,file:f.file,packets:f.before.state.heroAttacks.packets.length}))));process.exit(0);}
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8'));const report:any={method:'Actual production World-built schema21 diagnostic archives with genuine pending flights, native-shield window/echo/power and real carrier children/overdrive. Production file-import UI followed by save/export/reload/local-load in isolated contexts. No production debug API or live-state mutation; separate from natural acquisition, human/performance acceptance.',appBuildId:release.appBuildId,checks:[],errors:[]};const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});report.browser=browser.version();let page:any;
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.readiness.phase,'ready',JSON.stringify(r.readiness));};
const exportRun=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
const mechanisms=(state:any)=>encodeGraph({heroAttacks:state.heroAttacks,heroCasts:state.heroCasts,protossHeroes:state.protossHeroes,combat:[...state.entities.values()].filter((u:Entity)=>u.heroId||u.summonKind||u.protossCombat).map((u:Entity)=>({id:u.id,bornAt:u.bornAt,combat:u.protossCombat,hangar:u.carrierHangar,hp:u.hp,shield:u.shield,owner:u.summonOwnerId,weaponCooldown:u.weaponCooldown,nextShotAt:u.nextShotAt}))});
try{for(const {heroes,before,file} of fixtures){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',(e:any)=>report.errors.push(e.message));await page.goto(process.env.QA_OFFLINE_HTML?pathToFileURL(path.resolve(process.env.QA_OFFLINE_HTML)).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 const restored=await exportRun();assert.equal(restored.schema,21);assert.deepEqual(mechanisms(restored.state),mechanisms(before.state));assert.equal(restored.state.time,before.state.time);assert.equal(restored.state.paused,true);const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(r.protossHeroes.ready);assert.equal(r.protossHeroes.healingLinks,0);if(heroes.includes('purifier_flagship')){assert.equal(r.protossHeroes.fleet.convergence,12);assert.equal(r.protossHeroes.fleet.beams,1);assert.equal(r.protossHeroes.fleet.width,2.6);}assert.equal(r.protossHeroes.auras.heroes,3);assert.equal(r.protossHeroes.auras.textLabels,0);assert.equal(r.confirmedHeroes.auras.heroes,0);assert.equal(r.zergHeroes.auras.heroes,0);assert.deepEqual(r.errors,[]);for(const id of heroes)assert.ok(r.protossHeroes.actions[id][id==='purifier_flagship'?'skill':'attack'],'available original action '+id);await page.screenshot({path:out+'/'+heroes[0]+'-import-paused.png'});
 await page.locator('.end-screen [data-action=pause]').click();await page.waitForFunction(time=>window.__SC2_REPORT__().time>time+1.4,before.state.time,{timeout:30000});await page.screenshot({path:out+'/'+heroes[0]+'.png'});await page.locator('[data-seat="hero:0"]').click();const details=await page.locator('#unit-inspector').innerText();assert.ok(details.includes(HEROES[heroes[0]].skill));for(const aura of Object.values(HERO_GROUND_AURAS))assert.ok(!details.includes(aura.name),'aura text '+aura.name);await page.screenshot({path:out+'/'+heroes[0]+'-details.png'});await page.locator('[data-inspect-close]').click();
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exportRun();assert.ok(after.state.stats.damage>before.state.stats.damage);assert.equal(after.schema,21);if(heroes.includes('purifier_flagship')){const owner=[...after.state.entities.values()].find(u=>u.heroId==='purifier_flagship')!;assert.equal([...after.state.entities.values()].filter(u=>u.summonOwnerId===owner.id&&u.hp>0).length,12);}else assert.ok(after.state.protossHeroes.shields.length>0);
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exportRun();assert.deepEqual(mechanisms(loaded.state),mechanisms(after.state));assert.equal(loaded.state.time,after.state.time);assert.equal(loaded.state.paused,true);assert.deepEqual(encodeGraph(loaded.state.wallet),encodeGraph(after.state.wallet));assert.deepEqual(encodeGraph(loaded.state.expedition.ledger),encodeGraph(after.state.expedition.ledger));report.checks.push({heroes,schema:loaded.schema,importedPackets:before.state.heroAttacks.packets.length,pendingCasts:before.state.heroCasts.length,shieldWindows:before.state.protossHeroes.shields.length,echoes:before.state.protossHeroes.echoes.length,children:[...before.state.entities.values()].filter(u=>u.summonKind==='interceptor'&&u.hp>0).length,damage:after.state.stats.damage-before.state.stats.damage,auras:3,auraTextVisible:false,effects:r.protossHeroes,actions:r.protossHeroes.actions,saveRestored:true,mechanismsPreserved:true,debugApi:false});await context.close();console.log(heroes.join('/')+': production integration passed');}assert.deepEqual(report.errors,[]);assert.equal(JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,report.appBuildId);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/failure.png'});}}finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,errors:report.errors,failure:report.failure??null}));}
