import fs from 'node:fs/promises';import {createReadStream} from 'node:fs';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {HEROES,HERO_IDS_BY_RACE} from '../src/data/heroes';import {HEROES as BEFORE} from '../.cache/protoss-heroes-20261005/before/src/data/heroes';
import {HERO_GROUND_AURAS,ATTACK_DEMO_TUNING} from '../src/data/hero-upgrades';import {HERO_GROUND_AURAS as OLD_AURAS,ATTACK_DEMO_TUNING as OLD_ATTACKS} from '../.cache/protoss-heroes-20261005/before/src/data/hero-upgrades';
const root='reports/local/protoss-heroes-20261005';const read=async(p:string)=>JSON.parse(await fs.readFile(p,'utf8'));async function fingerprint(path:string){const h=createHash('sha256');let bytes=0;for await(const chunk of createReadStream(path)){bytes+=chunk.length;h.update(chunk);}return {path,bytes,sha256:h.digest('hex')};}
const [baseline,prior,priorZ,browser,prod,saves,strength,web,test]=await Promise.all([read(root+'/baseline.json'),read('reports/local/hero-aura-correction-20261005/delivery.json'),read('reports/local/zerg-heroes-20261005/delivery.json'),read(root+'/demo/browser.json'),read(root+'/production-heroes/report.json'),read(root+'/production-save/report.json'),read(root+'/strength.json'),read('dist/web/web-release.json'),fs.readFile(root+'/tests-r3.log','utf8')]);
const tests={tests:Number(test.match(/ℹ tests (\d+)/)?.[1]),passed:Number(test.match(/ℹ pass (\d+)/)?.[1]),failed:Number(test.match(/ℹ fail (\d+)/)?.[1])};assert.deepEqual(tests,{tests:917,passed:917,failed:0});for(const p of ['typecheck-final.log','docs-check-final.log'])assert.ok(!(await fs.readFile(root+'/'+p,'utf8')).includes('error TS'));
const artifacts=[];for(const old of baseline.artifacts){const current=await fingerprint(old.path);assert.equal(current.sha256,old.sha256,'preserve '+old.path);assert.equal(current.bytes,old.bytes);artifacts.push({...current,originalPreserved:true});}assert.equal(artifacts.length,8);for(const p of ['dist/Six-Protoss-Heroes-Integrated-Game-Demo.html','dist/SC2-Survivors-Protoss-Heroes-20261005.html','dist/SC2-Survivors-Demo.html'])artifacts.push({...await fingerprint(p),newDelivery:true});assert.equal(artifacts.at(-1)!.sha256,artifacts.at(-2)!.sha256);
assert.equal(browser.sha256,artifacts.find(a=>a.path===browser.html)!.sha256);assert.equal(browser.failure??null,null);assert.deepEqual(browser.errors,[]);assert.deepEqual(browser.remoteRequests,[]);assert.equal(browser.attacks.length,18);assert.equal(browser.skills.length,6);assert.equal(browser.bosses.length,2);assert.equal(browser.layouts.length,12);assert.ok(browser.attacks.every((x:any)=>x.auras.heroes===1&&x.auras.layers===2&&x.auras.textLabels===0));
assert.equal(prod.appBuildId,web.appBuildId);assert.equal(prod.failure??null,null);assert.deepEqual(prod.errors,[]);assert.equal(prod.checks.length,2);assert.ok(prod.checks.every((x:any)=>x.saveRestored&&x.mechanismsPreserved&&x.schema===19&&x.auras===3&&!x.auraTextVisible));assert.equal(saves.failure??null,null);assert.deepEqual(saves.errors,[]);assert.equal(saves.checks.filter((x:any)=>x.saveFieldsPreserved).length,2);assert.equal(web.runSchema,19);assert.equal(web.release,baseline.web.release);assert.equal(web.assetBytes,baseline.web.assetBytes);assert.equal(web.assetCount,baseline.web.assetCount);
const preservedProfiles=[];for(const id of [...HERO_IDS_BY_RACE.terran,...HERO_IDS_BY_RACE.zerg]){assert.deepEqual(HEROES[id],BEFORE[id],'hero profile '+id);assert.deepEqual(HERO_GROUND_AURAS[id],OLD_AURAS[id],'hero aura '+id);preservedProfiles.push(id);}assert.deepEqual(ATTACK_DEMO_TUNING,OLD_ATTACKS);
const source=[],frozen=['src/data/terran-heroes.ts','src/simulation/combat/terran-hero-passives.ts','src/data/zerg-heroes.ts','src/simulation/combat/zerg-hero-passives.ts','src/simulation/combat/zerg-hero-revival.ts','src/render/effects/zerg-hero-effects.ts','src/render/effects/confirmed-hero/approved-gun-effects.ts','src/render/effects/confirmed-hero/skill-effects.ts','src/render/effects/confirmed-hero/attack-effects.ts','src/render/effects/confirmed-hero/upgrade-materials.ts','preview/hero-integrated-demo/app.ts','preview/hero-integrated-demo/shell.html','preview/zerg-hero-integrated-demo/app.ts','preview/zerg-hero-integrated-demo/shell.html'];for(const p of frozen){const old=[...prior.source,...priorZ.source].find((x:any)=>x.path===p),current=await fingerprint(p);if(old)assert.equal(current.sha256,old.sha256,'frozen '+p);source.push({...current,previousEvidenceMatched:!!old});}
for(const p of ['src/data/protoss-heroes.ts','src/simulation/combat/protoss-hero-passives.ts','src/render/effects/protoss-hero-effects.ts','src/render/effects/confirmed-hero/hero-aura-effects.ts','src/render/scene/battle-renderer.ts','src/simulation/world.ts','src/simulation/combat/carriers.ts','src/simulation/combat/hero-attack-upgrades.ts','src/simulation/persistence/run-fields.ts','src/simulation/persistence/run-snapshot.ts','preview/protoss-hero-integrated-demo/app.ts','preview/protoss-hero-integrated-demo/shell.html'])source.push(await fingerprint(p));
assert.ok(strength.comparisons.every((x:any)=>x.ratioI>=1.25));assert.ok(strength.durability.every((x:any)=>x.ratioI>=1.25));assert.ok(strength.heals[0].ratio>=1.25);assert.ok(strength.control[0].ratio>=1.25);assert.ok(strength.bosses.every((x:any)=>x.id==='zeratul'?x.remaining===0:x.fraction>=.5));const provenance=(await read(root+'/demo/build.json')).provenance;for(const old of provenance){const current=await fingerprint(old.file);assert.equal(current.sha256,old.sha256);}
const delivery={scope:'Formal six Protoss heroes at confirmed Terran standard. All eighteen visible foot auras without aura text; unchanged twelve confirmed Terran/Zerg profiles and previous eight HTMLs. Schema19/profile v5. No cleanup, upload, push or deployment. Full P3/M6/M7, physical-device, human/source-clip acceptance remains open.',tests,browser:{sha256:browser.sha256,attacks:browser.attacks.length,skills:browser.skills.length,bosses:browser.bosses.length,layouts:browser.layouts.length,controls:browser.controls.length,errors:browser.errors.length,remoteRequests:browser.remoteRequests.length},strength:{comparisons:strength.comparisons,durability:strength.durability,heals:strength.heals,control:strength.control,bosses:strength.bosses},production:prod.checks,productionSaves:saves.checks,artifacts,web,source,preservedProfiles,provenance,visualReview:{screenshots:'demo/ + material-review/ + production-heroes/',fenixOriginalEmission:7.5,fenixRendererEmissionCap:.85,sourceTextureBytesUnchanged:true,sourceActions:{artanis:'Attack/Spell A',zeratul:'Attack/Spell A',alarak:'Attack/Spell A',fenix:'Attack reused for skill',vorazun:'Attack/Spell C',purifier_flagship:'Stand mother; real owned interceptor attacks'}}};await fs.writeFile(root+'/delivery.json',JSON.stringify(delivery,null,2));console.log(JSON.stringify({tests,browser:delivery.browser,preservedOriginals:8,preservedHeroProfiles:12,productionGroups:2,artifacts:artifacts.filter((a:any)=>a.newDelivery),web},null,2));
