import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {HEROES,type HeroId} from '../src/data/heroes';import {PROTOSS_HERO_IDS} from '../src/data/protoss-heroes';import {ELITES} from '../src/data/elites';import {familyRace} from '../src/data/races';
import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';import {tickProtossHero} from '../src/simulation/combat/protoss-hero-passives';import {initializeCarrierSubsystem} from '../src/simulation/combat/carriers';
const setup=(id:HeroId,rank:number)=>{const w=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10507});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.wallet.minerals=0;for(const p of Object.values(w.expedition.production))p.enabled={};assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!;u.rank=rank;w.heroes.get(id)!.rank=rank;u.x=u.z=0;u.prev={x:0,z:0};return {w,u,record:w.heroes.get(id)!};};
const rows=[];for(const id of PROTOSS_HERO_IDS)for(let rank=1;rank<=5;rank++){const {w,u,record}=setup(id,rank);w.heroes.clear();w.refreshStats(u,true);initializeCarrierSubsystem(w);const initialHp=u.maxHp,initialShield=u.maxShield??0,target=w.addUnit('roach','zerg',HEROES[id].range<3?1.45:3,0);target.enemyTier='boss';target.hp=target.maxHp=1e9;target.armor=0;target.stoppedUntil=1e9;target.specialReady=1e9;target.moveSpeed=0;w.hash.rebuild(w.entities.values());for(let tick=0;tick<3600;tick++){if(id!=='artanis'&&w.time>=record.skillReady){w.heroes.set(id,record);w.castHero(id);w.heroes.clear();}w.step();}rows.push({id,rank,dps:w.stats.damage/60,damage:w.stats.damage,shots:w.stats.shots,hp:initialHp,shield:initialShield,finalHp:u.maxHp,weapon:u.weaponDamage,period:u.attackPeriod,aurasExcluded:true});}
const comparators={zeratul:1955.184,alarak:4499.145,fenix:4499.145,purifier_flagship:4799.088};
const comparisons=Object.entries(comparators).map(([id,upper])=>{const a=rows.find(r=>r.id===id&&r.rank===1)!,b=rows.find(r=>r.id===id&&r.rank===5)!;return {id,approvedVEliteUpper:upper,heroI:a.dps,heroV:b.dps,ratioI:a.dps/upper,ratioV:b.dps/upper};});
const spec=JSON.parse(await fs.readFile('docs/project/NEXT_ITERATION_P0_VALUES_20261003.json','utf8')).eliteHeroRedesign;
const durability=spec.heroes.filter((h:any)=>PROTOSS_HERO_IDS.includes(h.id)).map((h:any)=>{const candidates=h.peerIds.map((id:keyof typeof ELITES)=>{const elite=spec.elites.find((x:any)=>x.id===id),family=ELITES[id].family,w=new World({race:familyRace(family),sandbox:true,waves:false,terrain:false,obstacles:[]});w.start();w.entities.clear();const unit=w.addUnit(family,'terran',0,0,5);if(family==='lurker')unit.nativeMode='lurker_burrowed';w.refreshStats(unit,true);const p=spec.bodyPresets[elite.body];return {id,hp:(unit.maxHp*p.hp+(unit.maxShield??0)*p.shield)*spec.eliteGrowth.hp[4]*(1+(elite.parameters.allyHpIncrease??elite.parameters.familyAttributeIncrease??0))};}).sort((a:any,b:any)=>b.hp-a.hp);const base=rows.find(r=>r.id===h.id&&r.rank===1)!;return {id:h.id,heroI:base.hp+base.shield,eliteV:candidates[0],ratioI:(base.hp+base.shield)/candidates[0].hp};});
const heals=[];for(const rank of [1,3,5]){const {w,u}=setup('artanis',rank);w.heroes.clear();w.refreshStats(u,true);for(let i=0;i<7;i++){const a=w.addUnit('stalker','terran',2+i*.2,0);a.shield=0;a.maxShield=1e7;}w.time=1;tickProtossHero(w,u,1);heals.push({rank,actualPerSecond:w.stats.healed,targets:u.healTargets?.length,approvedVEliteUpper:3024,ratio:w.stats.healed/3024,aurasExcluded:true});}
const control=[];for(const rank of [1,5]){const {w,u}=setup('vorazun',rank);const e=w.addUnit('roach','zerg',4,0);w.hash.rebuild(w.entities.values());assert.ok(w.castHero('vorazun'));w.heroes.clear();w.time=.25;resolveExpeditionHeroCasts(w);const duration=e.stoppedUntil!-w.time,rate=duration/HEROES.vorazun.cooldown;control.push({rank,duration,rate,approvedVEliteUpper:.1786,ratio:rate/.1786,actualDamage:w.stats.damage,aurasExcluded:true});}
const bosses=[];for(const id of ['zeratul','alarak','fenix','purifier_flagship'] as const)for(const rank of [1,5]){const {w}=setup(id,rank);w.difficulty='easy';w.stage=rank===1?12:18;let target;if(rank===5){w.endless={round:3,startedAt:0,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=w.spawnSpecial('queen','boss',{x:12,z:0})!;w.entities.delete(first.id);target=w.spawnSpecial('lurker','boss',{x:id==='zeratul'?1.5:5,z:0})!;w.castDetection();}else target=w.spawnSpecial('ravager','boss',{x:id==='zeratul'?1.5:5,z:0})!;const hp=target.hp;w.hash.rebuild(w.entities.values());assert.ok(w.castHero(id));w.heroes.clear();let firstDamage:number|null=null;for(let tick=0;tick<180;tick++){w.time+=1/60;resolveExpeditionHeroCasts(w);if(firstDamage===null&&target.hp<hp)firstDamage=w.time;}const dealt=hp-target.hp;bosses.push({id,rank,hp:Math.round(hp),armor:target.armor,damage:dealt,fraction:dealt/hp,remaining:target.hp,firstDamage,shots:w.stats.shots,aurasExcluded:true});}
const report={method:'Actual 60s production World.step, 60Hz; one high-HP zero-armor Boss-class diagnostic target; aura registry empty, no talents/cards. Target stopped to isolate incoming damage and preserve melee access; Vorazun controlled-target damage in rows is diagnostic, role comparison uses separate actual ordinary stop/CD. Actual public Boss factory with unchanged HP/armor and no basic shots. QA alone reads approved future elite proposal.',rows,comparisons,durability,heals,control,bosses};await fs.mkdir('reports/local/protoss-heroes-20261005',{recursive:true});await fs.writeFile('reports/local/protoss-heroes-20261005/strength.json',JSON.stringify(report,null,2));console.log(JSON.stringify({comparisons,durability,heals,control,bosses},null,2));assert.ok(comparisons.every(r=>r.ratioI>=1.25));assert.ok(durability.every((r:any)=>r.ratioI>=1.25));assert.ok(heals[0].ratio>=1.25&&heals.every(x=>x.targets===7));assert.ok(control.every(x=>x.ratio>=1.25&&x.actualDamage===0));assert.ok(bosses.every(b=>b.id==='zeratul'?b.remaining===0:b.fraction>=.5));
