import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {FAMILIES_BY_RACE,type Race} from '../src/data/races';import {HERO_IDS_BY_RACE} from '../src/data/heroes';
import {buySupport,type SupportCard} from '../src/simulation/combat/shop-support';import {UNIQUE_SUPPORT} from '../src/data/unique-support';import {initializeCarrierSubsystem} from '../src/simulation/combat/carriers';
const out='reports/local/p5-backend-20261006/offline';await fs.mkdir(out,{recursive:true});
const offline=true,fixtures=[];
for(const race of ['terran','zerg','protoss'] as Race[])for(let group=0;group<2;group++){
 if(offline&&(race!=='terran'||group))continue;
 const w=new World({race,seed:10607,waves:false,terrain:campaignTerrain(chooseCampaignMap(10607))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.expedition.ledger=[];w.expedition.zerglingPairs=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.time=10;w.tick=600;w.wallet={minerals:10000,gas:10000};for(const p of Object.values(w.expedition.production))p.enabled={};
 const families=FAMILIES_BY_RACE[race].slice(group*5,group*5+5),heroes=HERO_IDS_BY_RACE[race].slice(group*3,group*3+3);w.expedition.familySlots=[...families];
 for(const key of ['storm','charge','blink'])w.expedition.tech[key]=1;
 for(const family of families){w.expedition.tech['unlock.'+family]=1;const p=w.freePosition(family,w.anchor,1,6);assert.ok(p);const u=w.addFamilyMember(family,p,3);if(family==='lurker'){u.nativeMode=u.desiredNativeMode='lurker_burrowed';w.refreshStats(u,true);}u.energy=u.maxEnergy;u.hp*=.65;if(u.shield)u.shield*=.6;const air=['viking','phoenix','corruptor'].includes(family),q=w.freePosition(air?'mutalisk':'roach',u,1.5,6);assert.ok(q);const target=w.addUnit(air?'mutalisk':'roach','zerg',q.x,q.z);target.hp=target.maxHp=2e6;target.armor=0;target.specialReady=target.nextShotAt=1e9;target.moveSpeed=0;}
 for(const hero of heroes)assert.ok(w.acquireHero(hero));
 for(const id of ['mines','bombardment','strategic',...Object.entries(UNIQUE_SUPPORT).filter(([,v])=>v.race===race).map(([id])=>id)]as SupportCard[])for(let i=0;i<3;i++)buySupport(w,id);
 if(families.includes(race==='terran'?'marine':race==='zerg'?'hydralisk':'stalker'))for(let i=0;i<3;i++)assert.ok(buySupport(w,'mutation'));
 initializeCarrierSubsystem(w);w.hash.rebuild(w.entities.values());w.stageStartedAt=w.time;for(let i=0;i<30;i++){w.stageElapsed=0;w.step();}w.paused=true;
 const before=w.captureRun(),clone=new World({race});clone.restoreRun(before);const name=race+'-'+group,file=path.resolve(out,name+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:before}));fixtures.push({race,group,families,heroes,name,file,before});
}
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});
const report:any={method:'Production UI imports diagnostic World archives covering all30 ordinary families/all18 heroes, real support and actual child identities; export/save/reload/local-load. Browser keyboard, touch and virtual gamepad are engineering checks, not physical device acceptance.',offline,appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],errors:[]};let page:any;
const state=(s:any)=>encodeGraph({time:s.time,wallet:s.wallet,units:s.entities,heroes:s.heroes,flights:s.weaponFlights,support:s.expedition.support,spells:s.expedition.spells,ledger:s.expedition.ledger,pairs:s.expedition.zerglingPairs,terran:s.terranElites,zerg:s.zergElites,protoss:s.protossElites,auras:s.teamAuras});
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');};
const exported=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
try{for(const f of fixtures){const mobile=f.race==='zerg',context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:900},hasTouch:mobile,isMobile:mobile,acceptDownloads:true});if(offline)await context.setOffline(true);
 await context.addInitScript({content:`const pad={id:'P4 QA standard controller',index:0,mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({value:0,pressed:false,touched:false}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[pad]});window.__P4_PAD__=pad;`});page=await context.newPage();page.on('request',(r:any)=>{if(r.url().includes('/api/'))report.errors.push('Unexpected offline API request');});page.on('pageerror',(e:any)=>report.errors.push(e.message));
 await page.goto(offline?pathToFileURL(path.resolve('dist/SC2-Survivors-P5-20261006.html')).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');assert.equal(await page.evaluate(()=>localStorage.getItem('sc2.telemetry.identity.v1')),null);
 await page.locator('[data-action=menu-load]').click();const picker=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await picker).setFiles(f.file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 const initial=await exported();assert.equal(initial.schema,23);assert.deepEqual(state(initial.state),state(f.before.state));let r=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(r.nonHeroes.ready);assert.deepEqual(r.errors,[]);
 await page.locator('.end-screen [data-action=pause]').click();const t=r.time;let control='buttons';
 if(f.race==='terran'){control='keyboard';await page.keyboard.down('w');}
 if(f.race==='protoss'){control='virtual standard gamepad';await page.evaluate(()=>{(window as any).__P4_PAD__.axes[0]=.8;});}
 if(mobile){control='browser touch';const b=await page.locator('#joystick').boundingBox();assert.ok(b);const cdp=await context.newCDPSession(page),x=b.x+b.width/2,y=b.y+b.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+24,y:y-10}]});await page.waitForTimeout(350);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}
 await page.waitForFunction((t:number)=>window.__SC2_REPORT__().time>t+1.5,t,{timeout:30000});await page.keyboard.up('w');await page.evaluate(()=>{(window as any).__P4_PAD__.axes[0]=0;});await page.screenshot({path:out+'/'+(offline?'offline-':'')+f.name+'-battle.png',fullPage:true});
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exported();assert.ok(after.state.time>f.before.state.time);assert.ok(after.state.stats.damage>f.before.state.stats.damage||after.state.stats.healed>f.before.state.stats.healed);
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exported();assert.deepEqual(state(loaded.state),state(after.state));assert.equal(loaded.state.paused,true);
 report.checks.push({race:f.race,group:f.group,families:f.families,heroes:f.heroes,control,schema:loaded.schema,damage:after.state.stats.damage-f.before.state.stats.damage,healed:after.state.stats.healed-f.before.state.stats.healed,saveRestored:true,worldPreserved:true,debugApi:false});console.log(f.name+': production UI passed');await context.close();}assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/'+(offline?'offline-':'')+'failure.png'}).catch(()=>{});}}
finally{await fs.writeFile(out+'/'+(offline?'offline':'web')+'.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks.length,errors:report.errors,failure:report.failure??null}));}
