import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='reports/local/qa-v5-assets';await fs.mkdir(out,{recursive:true});
const report={scope:'Local diagnostic presentation fixtures. No human visual approval.',checkpoints:[],errors:[]};
const browser=await chromium.launch({executablePath:process.env.SC2_CHROME??'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:90000});await page.getByRole('button',{name:/部署小队/}).click();
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.step=()=>{};w.autoWaves=false;w.buildings.clear();w.pods=[];for(const [i,type] of ['marine','hellion','tank','medivac'].entries())w.spawnPod(type,{x:i*4-6,z:1});w.changed();});
 const checkpoint=async name=>{await page.waitForTimeout(100);const r=await page.evaluate(async()=>{const d=window.__SC2_DEBUG__,w=d.world,v=d.view;return {time:w.time,pods:w.pods.map(p=>{const pv=v.podViews.get(p.id),point=v.camera.position.clone(),box={min:point.clone().set(Infinity,Infinity,Infinity),max:point.clone().set(-Infinity,-Infinity,-Infinity)};let meshes=0,unsafeCulling=0;pv.root.updateMatrixWorld(true);pv.root.traverse(m=>{if(!m.isMesh)return;meshes++;if(m.frustumCulled)unsafeCulling++;for(let i=0;i<m.geometry.attributes.position.count;i+=19){m.getVertexPosition(i,point);m.localToWorld(point);box.min.min(point);box.max.max(point);}});return {id:p.id,unit:p.unitType,status:p.status,visible:pv.root.visible,animation:pv.state,meshes,unsafeCulling,bounds:{min:box.min.toArray(),max:box.max.toArray()},doors:pv.doors.map(d=>d.node.quaternion.toArray()),label:v.podLabels.get(p.id)?.textContent,labelHidden:v.podLabels.get(p.id)?.hidden};}),drawCalls:v.renderer.info.render.calls};});report.checkpoints.push({name,...r});assert.equal(r.pods.length,4);assert.ok(r.pods.every(p=>p.visible&&p.meshes>0&&p.unsafeCulling===0));await page.screenshot({path:out+'/pods-'+name+'.png'});return r;};
 await checkpoint('falling');await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.time+=3.3;for(const p of w.pods)w.landPod(p);w.changed();});const landed=await checkpoint('landed');assert.ok(landed.pods.every(p=>p.animation==='stand'&&!p.labelHidden&&p.label.includes('新增队员')&&p.label.includes('HP')));assert.equal(new Set(landed.pods.map(p=>p.label)).size,4);
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;for(let i=0;i<4;i++)w.addUnit('marine','terran',i,4);w.changed();});const promoted=await checkpoint('promotion-label');assert.ok(promoted.pods[0].label.includes('晋升最低军衔'));
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;for(const p of w.pods){p.status='opening';p.resolvedAt=w.time;}w.time+=1;w.changed();});const opened=await checkpoint('opening');assert.notDeepEqual(opened.pods[0].doors,landed.pods[0].doors);
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;for(const p of w.pods){p.status='destroyed';p.resolvedAt=w.time;p.hp=0;}w.time+=.5;w.changed();});const dead=await checkpoint('destroyed');assert.ok(dead.pods.every(p=>p.animation==='death'));assert.deepEqual(report.errors,[]);console.log('Pod falling/landed/opening/death and four identities passed.');
}catch(e){report.failure=String(e.stack??e);process.exitCode=1;console.error(report.failure);}finally{await fs.writeFile(out+'/PODS.json',JSON.stringify(report,null,2));await browser.close();}
