import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {createGameServer} from './coze-web-server.mjs';import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {ELITES} from '../src/data/elites';import type {Entity} from '../src/simulation/types';import type {ProtossEliteId} from '../src/data/protoss-elites';import {protossEliteCombat,protossEliteAbility,tickProtossElite} from '../src/simulation/combat/protoss-elite-runtime';import {initializeCarrierSubsystem} from '../src/simulation/combat/carriers';
const out=process.env.QA_OUT??'reports/local/protoss-elites-auras-20261005/production';await fs.mkdir(out,{recursive:true});
const allGroups:ProtossEliteId[][]=[['zealot.1','zealot.2','zealot.3','adept.1','adept.2','adept.3'],['stalker.1','stalker.2','stalker.3','sentry.1','sentry.2','sentry.3'],['immortal.1','immortal.2','immortal.3','colossus.1','colossus.2','colossus.3'],['high_templar.1','high_templar.2','high_templar.3','phoenix.1','phoenix.2','phoenix.3'],['void_ray.1','void_ray.2','void_ray.3','carrier.1','carrier.2','carrier.3']];
const groups=process.env.QA_OFFLINE_HTML?[allGroups[1]]:allGroups;
function fixture(ids:ProtossEliteId[]){const w=new World({race:'protoss',seed:10577,waves:false,terrain:campaignTerrain(chooseCampaignMap(10577))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.expedition.ledger=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.time=10;w.tick=600;w.wallet={minerals:10000,gas:10000};for(const p of Object.values(w.expedition.production))p.enabled={};w.expedition.tech.storm=1;w.expedition.tech.charge=1;w.expedition.tech.blink=1;w.expedition.familySlots=[...new Set([...ids.map(id=>ELITES[id].family),'stalker','sentry'])];const units:Entity[]=[],targets=new Map<number,Entity>();
for(const id of ids){const family=ELITES[id].family,p=w.freePosition(family,w.anchor,1.5,7);assert.ok(p);const u=w.addUnit(family,'terran',p.x,p.z,5);u.eliteId=id;u.modelKey=ELITES[id].model;w.expedition.tech['unlock.'+family]=1;w.refreshStats(u,true);u.energy=u.maxEnergy!;units.push(u);const air=u.flying&&id!=='phoenix.2',q=w.freePosition(air?'mutalisk':'roach',u,1.5,5);assert.ok(q);const e=w.addUnit(air?'mutalisk':'roach','zerg',q.x,q.z);e.hp=e.maxHp=2e6;e.armor=0;e.specialReady=e.nextShotAt=1e9;e.moveSpeed=0;e.energy=50;targets.set(u.id,e);}
if(ids.includes('sentry.1')||ids.includes('high_templar.3'))for(let i=0;i<7;i++){const p=w.freePosition('stalker',units[0],1,7);assert.ok(p);const u=w.addUnit('stalker','terran',p.x,p.z,5);u.shield=0;u.stoppedUntil=u.nextShotAt=1e9;}
if(ids.includes('zealot.1')){for(const id of ['artanis','fenix','purifier_flagship']as const)assert.ok(w.acquireHero(id));}if(ids.includes('stalker.1')){for(const id of ['zeratul','alarak','vorazun']as const)assert.ok(w.acquireHero(id));}
initializeCarrierSubsystem(w);w.hash.rebuild(w.entities.values());for(const u of units){if(u.eliteId==='phoenix.3')protossEliteCombat(u).charge=1;if(u.eliteId==='zealot.2'||u.eliteId==='sentry.3')w.hit(u,(u.shield??0)+200,[],1,'zerg',0,1,targets.get(u.id)!.id);if(u.unitType==='sentry'||u.unitType==='high_templar')protossEliteAbility(w,u);}
w.stageStartedAt=w.time;for(let i=0;i<20;i++){w.stageElapsed=0;w.step();}for(const u of units)w.fire(u,targets.get(u.id)!);w.paused=true;const before=w.captureRun();assert.equal(before.schema,23);const clone=new World({race:'protoss'});clone.restoreRun(before);return {w,before};}
const fixtures=[];for(const ids of groups){const f=fixture(ids),file=path.resolve(out,ids[0]+'.json');await fs.writeFile(file,writeArchive({profile:f.w.permanentProfile.exportJSON(),run:f.before}));fixtures.push({...f,ids,file});}if(process.argv.includes('--fixtures-only')){console.log(fixtures.map(f=>f.file));process.exit(0);}
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8'));const report:any={method:'Actual production World-built schema23 diagnostic archives covering all thirty Protoss elites and revised team auras: saved charge/cycles, primary and derived flights, delayed echoes, thermal/piercing lines, finite energy fields, native shield windows, actual lifts and team barriers. Production file-import UI followed by save/export/reload/local-load in isolated contexts. No production debug API or live-state mutation; separate from natural acquisition, human/performance acceptance.',appBuildId:release.appBuildId,checks:[],errors:[]};const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});report.browser=browser.version();let page:any;
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.readiness.phase,'ready',JSON.stringify(r.readiness));};
const exportRun=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
const mechanisms=(state:any)=>encodeGraph({protossElites:state.protossElites,teamAuras:state.teamAuras,zergElites:state.zergElites,terranElites:state.terranElites,p4Samples:state.p4Samples,weaponFlights:state.weaponFlights,pairs:state.expedition.zerglingPairs,combat:[...state.entities.values()].filter((u:Entity)=>u.team==='player').map((u:Entity)=>({id:u.id,bornAt:u.bornAt,eliteId:u.eliteId,combat:u.protossEliteCombat,hp:u.hp,maxHp:u.maxHp,armor:u.armor,moveSpeed:u.moveSpeed,auraFactor:u.teamAuraFactors,heroId:u.heroId,shield:u.shield,energy:u.energy,nativeMode:u.nativeMode,desiredNativeMode:u.desiredNativeMode,nativeModeUntil:u.nativeModeUntil,weaponCooldown:u.weaponCooldown,nextShotAt:u.nextShotAt,recoveryUntil:u.recoveryUntil}))});
try{for(const {ids,before,file} of fixtures){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',(e:any)=>report.errors.push(e.message));await page.goto(process.env.QA_OFFLINE_HTML?pathToFileURL(path.resolve(process.env.QA_OFFLINE_HTML)).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 const restored=await exportRun();assert.equal(restored.schema,23);assert.deepEqual(mechanisms(restored.state),mechanisms(before.state));assert.equal(restored.state.time,before.state.time);assert.equal(restored.state.paused,true);const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(r.protossElites.ready);if(ids.includes('zealot.1')){assert.ok(r.protossHeroes.auras.heroes>0);assert.equal(r.protossHeroes.auras.textLabels,0);}assert.deepEqual(r.errors,[]);await page.screenshot({path:out+'/'+ids[0]+'-import-paused.png'});
 await page.locator('.end-screen [data-action=pause]').click();await page.waitForFunction(time=>window.__SC2_REPORT__().time>time+3.6,before.state.time,{timeout:30000});await page.screenshot({path:out+'/'+ids[0]+'.png'});await page.locator(`[data-seat="${ELITES[ids[0]].family}:0"]`).first().click();await page.screenshot({path:out+'/'+ids[0]+'-details.png'});await page.locator('[data-inspect-close]').click();
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exportRun();assert.ok(after.state.stats.damage>before.state.stats.damage||after.state.stats.healed>before.state.stats.healed);assert.equal(after.schema,23);assert.equal(after.state.p4Samples.enabled,false);
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exportRun();assert.deepEqual(mechanisms(loaded.state),mechanisms(after.state));assert.equal(loaded.state.time,after.state.time);assert.equal(loaded.state.paused,true);assert.deepEqual(encodeGraph(loaded.state.wallet),encodeGraph(after.state.wallet));assert.deepEqual(encodeGraph(loaded.state.expedition.ledger),encodeGraph(after.state.expedition.ledger));report.checks.push({ids,schema:loaded.schema,importedPackets:before.state.weaponFlights.length,echoes:before.state.protossElites.echoes.length,lines:before.state.protossElites.lines.length,fields:before.state.protossElites.fields.length,lifts:before.state.protossElites.lifts.length,pairs:before.state.expedition.zerglingPairs.length,heroAura:[...loaded.state.entities.values()].filter(u=>u.heroId).map(u=>({id:u.heroId,maxHp:u.maxHp,hp:u.hp,armor:u.armor,auraFactor:u.teamAuraFactors})),damage:after.state.stats.damage-before.state.stats.damage,healed:after.state.stats.healed-before.state.stats.healed,saveRestored:true,mechanismsPreserved:true,debugApi:false});await context.close();console.log(ids.join('/')+': production integration passed');}assert.deepEqual(report.errors,[]);assert.equal(JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,report.appBuildId);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/failure.png'});}}finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,errors:report.errors,failure:report.failure??null}));}
