import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {HEROES,type HeroId} from '../src/data/heroes';import {PROTOSS_HERO_IDS} from '../src/data/protoss-heroes';import {ELITES} from '../src/data/elites';
import {PROTOSS_ELITE_IDS,type ProtossEliteId} from '../src/data/protoss-elites';import {unitData,expeditionWeaponBonuses,selectWeapon} from '../src/simulation/combat/expedition-combat';
import {initializeCarrierSubsystem,ownedInterceptors} from '../src/simulation/combat/carriers';import {protossEliteCombat,protossEliteBonuses} from '../src/simulation/combat/protoss-elite-runtime';import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';import {tickProtossHero} from '../src/simulation/combat/protoss-hero-passives';
const out='reports/local/protoss-elites-auras-20261005';const spec=JSON.parse(await fs.readFile('docs/project/NEXT_ITERATION_P0_VALUES_20261003.json','utf8')).eliteHeroRedesign,approved=JSON.parse(await fs.readFile('docs/project/NEXT_ITERATION_P4_VALUES_20261005.json','utf8')).approved.elites;
function setup(){const w=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10577});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.wallet.minerals=0;for(const p of Object.values(w.expedition.production))p.enabled={};return w;}
const eliteProfiles=[];for(const id of PROTOSS_ELITE_IDS){const row=approved.find((r:any)=>r.id===id),probes=[];let hp=0;for(const scenario of ['light','armored','air-armored']){const w=setup(),u=w.addUnit(ELITES[id].family,'terran',0,0,5);u.eliteId=id;const t=w.addUnit(scenario.startsWith('air')?'mutalisk':'roach','zerg',3,0);t.attributes=scenario==='light'?['Light']:['Armored'];const allies=w.allies.bind(w);w.allies=()=>[];selectWeapon(w,u,t);w.refreshStats(u,true);hp=u.maxHp+(u.maxShield??0);initializeCarrierSubsystem(w);const child=ownedInterceptors(w,u.id);let base=(u.weaponDamage+protossEliteBonuses(u,expeditionWeaponBonuses(w,u).bonuses).filter(b=>t.attributes.includes(b.attribute)).reduce((n,b)=>n+b.amount,0))*unitData(u).attacks/u.attackPeriod,peak=base*row.primaryEnvelope;
 if(u.unitType==='carrier'){base=child.reduce((n,c)=>n+c.weaponDamage*unitData(c).attacks/c.attackPeriod,0);peak=base*(id==='carrier.1'?2:id==='carrier.2'?(scenario==='light'?2:3.6):2);}
 // The approved envelope already includes its strongest target multiplier.

 const fixed=id==='zealot.3'?4320/10:id==='sentry.3'?(u.maxShield??0)*2/3:id==='high_templar.1'?7200/12:id==='high_templar.2'?3840/12:id==='high_templar.3'?2880/12:id==='colossus.1'?528:0;peak+=fixed;probes.push({scenario,base,envelope:row.primaryEnvelope,fixed,peak,weapon:u.weaponDamage,period:u.attackPeriod,realChildren:child.length});w.allies=allies;}eliteProfiles.push({id,hp,peak:Math.max(...probes.map(p=>p.peak)),probes});}
const rows=[];for(const id of PROTOSS_HERO_IDS)for(const rank of [1,5]){const w=setup();assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!,record=w.heroes.get(id)!;u.rank=record.rank=rank;u.x=u.z=0;w.heroes.clear();w.refreshStats(u,true);initializeCarrierSubsystem(w);const pools=u.maxHp+(u.maxShield??0),e=w.addUnit('roach','zerg',HEROES[id].range<3?1.45:3,0);e.enemyTier='boss';e.hp=e.maxHp=1e9;e.armor=0;e.stoppedUntil=e.specialReady=e.nextShotAt=1e9;e.moveSpeed=0;w.hash.rebuild(w.entities.values());for(let i=0;i<3600;i++){if(id!=='artanis'&&w.time>=record.skillReady){w.heroes.set(id,record);w.castHero(id);w.heroes.clear();}w.step();}rows.push({id,rank,dps:w.stats.damage/60,hp:pools,shots:w.stats.shots});}
const role=spec.heroes.filter((h:any)=>PROTOSS_HERO_IDS.includes(h.id)),comparisons=role.filter((h:any)=>!['artanis','vorazun'].includes(h.id)).map((h:any)=>{const upper=Math.max(...h.peerIds.map((id:string)=>eliteProfiles.find(e=>e.id===id)!.peak)),hero=rows.find(r=>r.id===h.id&&r.rank===1)!;return {id:h.id,heroI:hero.dps,eliteV:upper,ratio:hero.dps/upper};}),durability=role.map((h:any)=>{const upper=Math.max(...h.peerIds.map((id:string)=>eliteProfiles.find(e=>e.id===id)!.hp)),hero=rows.find(r=>r.id===h.id&&r.rank===1)!;return {id:h.id,heroI:hero.hp,eliteV:upper,ratio:hero.hp/upper};});
const healing=(()=>{const w=setup();w.acquireHero('artanis');const u=w.heroEntity('artanis')!;u.x=u.z=0;w.heroes.clear();w.refreshStats(u,true);for(let i=0;i<7;i++){const b=w.addUnit('stalker','terran',2+i*.2,0);b.shield=0;b.maxShield=1e7;}w.time=1;tickProtossHero(w,u,1);return {heroI:w.stats.healed,eliteV:180*2.4*7,ratio:w.stats.healed/(180*2.4*7)};})();
const bosses=[];for(const id of ['zeratul','alarak','fenix','purifier_flagship']as const)for(const rank of [1,5]){const w=setup();w.acquireHero(id);const u=w.heroEntity(id)!,record=w.heroes.get(id)!;u.x=u.z=0;u.rank=record.rank=rank;w.difficulty='easy';w.stage=rank===1?12:18;let e;if(rank===5){w.endless={round:3,startedAt:0,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=w.spawnSpecial('queen','boss',{x:12,z:0})!;w.entities.delete(first.id);e=w.spawnSpecial('lurker','boss',{x:id==='zeratul'?1.5:5,z:0})!;w.castDetection();}else e=w.spawnSpecial('ravager','boss',{x:id==='zeratul'?1.5:5,z:0})!;const hp=e.hp;w.hash.rebuild(w.entities.values());assert.ok(w.castHero(id));w.heroes.clear();for(let i=0;i<180;i++){w.time+=1/60;resolveExpeditionHeroCasts(w);}bosses.push({id,rank,hp,remaining:e.hp,fraction:(hp-e.hp)/hp});}
const report={method:'Current production intrinsic V elite profiles with all team auras excluded; approved conditional cycle envelopes, actual owned child packets and finite spell budgets. Actual 60-second hero simulations with empty aura registry, and authentic Easy stage12/endless3 Boss factories. Isolated budget check, not natural campaign or device acceptance.',eliteProfiles,rows,comparisons,durability,healing,bosses};await fs.writeFile(out+'/strength.json',JSON.stringify(report,null,2));console.log(JSON.stringify({comparisons,durability,healing,bosses},null,2));assert.ok(comparisons.every(r=>r.ratio>=1.25));assert.ok(durability.every(r=>r.ratio>=1.25));assert.ok(healing.ratio>=1.25);assert.ok(bosses.every(b=>b.id==='zeratul'?b.remaining===0:b.fraction>=.5));
