import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {readArchive} from '../src/persistence/archive';
const root='reports/local/p6-20261006',sha=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex');
const report:any={at:new Date().toISOString(),method:'Index of actual P6 records; original failed runs and provenance are retained. Archived run contents determine talent points and format. Controller outcomes are diagnostics, not human win rates.',natural:[],checkpoints:[],performance:[]};
for(const entry of await fs.readdir(root,{withFileTypes:true})){
 if(!entry.isDirectory())continue;const dir=path.join(root,entry.name);
 if(entry.name.startsWith('natural-')){
  for(const name of await fs.readdir(dir)){if(!name.endsWith('.json')||name.startsWith('summary'))continue;const file=path.join(dir,name),text=await fs.readFile(file,'utf8'),r=JSON.parse(text);if(!r.build)continue;report.natural.push({file,sha256:sha(text),race:r.race,build:r.build,seed:r.seed,talents:r.frozenTalents?.allocated??r.talentPoints??0,resume:r.resume,difficulty:r.difficulty,completed:r.completed,stage:r.stage,phase:r.phase,combatSeconds:r.time,endlessSeconds:r.endlessSeconds,peakBodies:r.peakBodies,issue:r.issue,developmentEvents:r.events?.filter((e:any)=>e.kind==='development').length});}
  const checkpoints=path.join(dir,'checkpoints');for(const name of await fs.readdir(checkpoints).catch(()=>[])){if(!name.endsWith('.json')||name.endsWith('.provenance.json'))continue;const file=path.join(checkpoints,name),text=await fs.readFile(file,'utf8'),bundle=readArchive(text).bundle,r=bundle.run!;assert.ok(r);const provenance=JSON.parse(await fs.readFile(file+'.provenance.json','utf8'));assert.equal(sha(text),provenance.archiveHash);assert.equal(provenance.diagnosticHealthLock,false);assert.equal(provenance.diagnosticOneHit,false);report.checkpoints.push({file,sha256:sha(text),schema:r.schema,race:r.config.race,seed:r.seed,stage:r.state.stage,phase:r.state.phase,combatSeconds:r.state.time,talents:r.config.frozenTalents.allocated,difficulty:r.config.difficulty,provenance});}
 }
 if(entry.name.startsWith('perf-')){const file=path.join(dir,'results.json'),text=await fs.readFile(file,'utf8').catch(()=>null);if(!text)continue;const r=JSON.parse(text);report.performance.push({file,sha256:sha(text),method:r.method,checkpoint:r.checkpoint?.path,failure:r.failure??null,host:r.host,chrome:r.chrome,runs:r.runs.map((s:any)=>({race:s.race,trial:s.trial,stage:s.stage,time:s.time,phase:s.phase,frames:s.frames,steps:s.steps,renders:s.renders,gpuTimes:s.gpuTimes,gpu:s.gpu,peakBodies:s.peakBodies,peakEntities:s.peakEntities,maxDebt:s.maxDebt,finalDebt:s.finalDebt,discardedDebt:s.discardedDebt,errors:s.errors,frameGate:s.frames.p95<=16.900001&&s.frames.p99<=20.000001&&s.frames.over20Percent<=1,debtGate:s.maxDebt<=.100001&&s.discardedDebt<=.100001}))});}
}
report.campaign18ZeroTalentRaces=[...new Set(report.natural.filter((r:any)=>r.talents===0&&r.difficulty==='normal'&&r.completed===18&&r.endlessSeconds>0&&!r.issue).map((r:any)=>r.race))];
report.naturalAttempts=report.natural.length;report.checkpointCount=report.checkpoints.length;
await fs.writeFile(root+'/evidence-index.json',JSON.stringify(report,null,2));console.log(JSON.stringify({naturalAttempts:report.naturalAttempts,checkpoints:report.checkpointCount,completed18Races:report.campaign18ZeroTalentRaces,performanceGroups:report.performance.length}));
