import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createGameServer} from './coze-web-server.mjs';
const out='reports/local/opening-cover-flame-20261007/rendered-flame';await fs.mkdir(out,{recursive:true});
const server=createGameServer({webRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({viewport:{width:1280,height:720}}),page=await context.newPage();
const report:any={at:new Date().toISOString(),appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,errors:[],fans:[],method:'Production renderer reads actual frozen effects from an isolated archive; pause overlay hidden by diagnostic CSS for screenshots only. No World or renderer mutation.'};page.on('pageerror',e=>report.errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:'+(server.address() as any).port);await page.locator('#scs-opening-visual').waitFor({state:'detached'});await page.locator('.main-actions [data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(path.resolve('reports/local/opening-cover-flame-20261007/browser/hellion.json'));await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});await page.locator('[data-action=flow-continue]').click();
 await page.waitForFunction(()=>window.__SC2_REPORT__?.().terranElites?.flameFans?.some((f:any)=>Math.abs(f.radius-10/3)<1e-8),null,{timeout:15000});report.fans.push(await page.evaluate(()=>window.__SC2_REPORT__().terranElites.flameFans));
 const css=await page.addStyleTag({content:'#overlay{display:none!important}'});await page.screenshot({path:out+'/hellion-fan.png'});await css.evaluate(n=>n.remove());
 await page.locator('.pause-actions [data-action=pause]').click();await page.locator('#unit-operations').click();await page.locator('[data-action=unit-mode][data-family=hellion][data-mode=hellbat]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().terranElites?.flameFans?.some((f:any)=>Math.abs(f.radius-4/3)<1e-8),null,{timeout:30000});report.fans.push(await page.evaluate(()=>window.__SC2_REPORT__().terranElites.flameFans));await page.screenshot({path:out+'/hellbat-fan.png'});
 for(const group of report.fans)for(const fan of group)assert.equal(fan.arcDegrees,150);assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));}
