import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {createGameServer} from './coze-web-server.mjs';import {World} from '../src/simulation/world';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {ELITES} from '../src/data/elites';import type {Entity} from '../src/simulation/types';import {TERRAN_ELITE_IDS,type TerranEliteId} from '../src/data/terran-elites';
import {updateExpeditionProduction,releasePaidPassenger,productionQuote} from '../src/simulation/expedition-production';import {eliteCombat} from '../src/simulation/combat/terran-elite-runtime';
const out=process.env.QA_OUT??'reports/local/terran-elites-20261005/production';await fs.mkdir(out,{recursive:true});
const groups:TerranEliteId[][]=process.env.QA_OFFLINE_HTML?[['science_vessel.3','hellion.3','reaper.3']]:[['marine.1','marauder.3','reaper.2'],['tank.3','thor.3','viking.3'],['medivac.2','science_vessel.1','science_vessel.2'],['science_vessel.3','hellion.3','reaper.3'],['medivac.1','thor.1','banshee.3']];
function fixture(ids:TerranEliteId[]){
 const w=new World({race:'terran',seed:10530,waves:false,terrain:campaignTerrain(chooseCampaignMap(10530))});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.expedition.ledger=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();w.fortifications.clear();w.pickups=[];w.rewardDrops=[];w.time=10;w.tick=600;w.wallet={minerals:10000,gas:10000};for(const p of Object.values(w.expedition.production))p.enabled={};
 w.expedition.familySlots=[...new Set([...ids.map(id=>ELITES[id].family),'tank','marauder'])].slice(0,5);const units:Entity[]=[],targets=new Map<number,Entity>();
 for(const id of ids){const q=w.freePosition(id.startsWith('viking.')?'thor':ELITES[id].family,w.anchor,2,6);assert.ok(q,'legal source '+id);const u=w.addUnit(ELITES[id].family,'terran',q.x,q.z,5);u.eliteId=id;u.modelKey=ELITES[id].model;w.expedition.tech['unlock.'+u.unitType]=1;w.refreshStats(u,true);u.energy=u.maxEnergy;units.push(u);
 const p=w.freePosition('roach',u,3.5,5.5);assert.ok(p,'legal enemy '+id);const e=w.addUnit('roach','zerg',p.x,p.z);e.hp=e.maxHp=2e6;e.armor=0;e.stoppedUntil=e.specialReady=e.nextShotAt=1e9;e.moveSpeed=0;if(id==='science_vessel.3'){e.shield=e.maxShield=10000;e.shieldArmor=1;e.shieldRegen=0;e.energy=100;}targets.set(u.id,e);}
 if(ids.some(id=>id.startsWith('science_vessel')||id.startsWith('medivac'))){for(let i=0;i<7;i++){const type=ids.includes('medivac.2')?'marauder':'tank',p=w.freePosition(type,units[0],1,6);assert.ok(p,'legal patient');const u=w.addUnit(type,'terran',p.x,p.z,5);u.hp=u.maxHp*.15;u.stoppedUntil=u.nextShotAt=1e9;u.lastDamagedAt=w.time;}}
 if(ids.includes('medivac.1')){assert.ok(w.acquireHero('yamato_battlecruiser'));const h=w.heroEntity('yamato_battlecruiser')!;h.x=units[0].x;h.z=units[0].z;w.refreshStats(h,true);h.hp=h.maxHp*.4;h.stoppedUntil=1e9;assert.equal(h.eliteHpAuraFactor,1.35);}
 w.hash.rebuild(w.entities.values());if(ids.includes('tank.3'))assert.ok(w.setFamilyMode('tank','siege'));if(ids.includes('viking.3'))assert.ok(w.setFamilyMode('viking','viking_assault'));
 if(ids.includes('reaper.3')){const s=w.expedition;s.facilities.push({id:s.nextFacility++,kind:'barracks',line:'barracks',techLab:true});s.production.barracks.outputs=['reaper'];s.production.barracks.enabled={reaper:true};const wallet={...w.wallet},quote=productionQuote(w,'reaper');updateExpeditionProduction(w,0);assert.ok(s.ledger.length);assert.equal(wallet.minerals-w.wallet.minerals,quote.minerals*s.ledger[0].passengers.length);assert.equal(wallet.gas-w.wallet.gas,quote.gas*s.ledger[0].passengers.length);s.production.barracks.enabled={};w.time+=quote.seconds;w.tick+=Math.round(quote.seconds*60);updateExpeditionProduction(w,quote.seconds,false);const job=s.ledger[0],pod=w.pods.find(p=>p.id===job.podId);assert.ok(pod);const q=w.freePosition('reaper',units[2],1.5,5);assert.ok(q);releasePaidPassenger(w,pod,0,q);assert.equal(w.terranElites.absorptions.length,1);}
 w.stageStartedAt=w.time;for(let i=0;i<(ids.includes('tank.3')?250:30);i++){w.stageElapsed=0;w.step();}
 for(const u of units){if(u.unitType==='tank')assert.equal(u.mode,'siege');if(u.unitType==='viking')assert.equal(u.desiredNativeMode,'viking_assault');if(!['science_vessel','medivac'].includes(u.unitType))w.fire(u,targets.get(u.id)!);u.stoppedUntil=1e9;}
 w.time+=3/60;w.tick+=3;w.paused=true;const before=w.captureRun();assert.equal(before.schema,21);assert.equal(before.state.phase,'battle');const test=new World({race:'terran'});test.restoreRun(before);return {w,before};
}
const fixtures=[];for(const ids of groups){const f=fixture(ids),file=path.resolve(out,ids[0]+'.json');await fs.writeFile(file,writeArchive({profile:f.w.permanentProfile.exportJSON(),run:f.before}));fixtures.push({...f,ids,file});}
if(process.argv.includes('--fixtures-only')){console.log(JSON.stringify(fixtures.map(f=>({ids:f.ids,file:f.file,packets:f.before.state.weaponFlights.length,areas:f.before.state.terranElites.areas.length,mines:f.before.state.p4Samples.mines.length,fires:f.before.state.p4Samples.fires.length,deploy:f.before.state.p4Samples.deploy,absorptions:f.before.state.terranElites.absorptions.length}))));process.exit(0);}
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8'));const report:any={method:'Actual production World-built schema21 diagnostic archives with genuine delayed primary/derived elite flights, native transitions, radiation/EMP, mine deployment and one original paid Reaper absorption receipt. Production file-import UI followed by save/export/reload/local-load in isolated contexts. No production debug API or live-state mutation; separate from natural acquisition, human/performance acceptance.',appBuildId:release.appBuildId,checks:[],errors:[]};const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});report.browser=browser.version();let page:any;
const ready=async()=>{await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:240000});const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.readiness.phase,'ready',JSON.stringify(r.readiness));};
const exportRun=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
const mechanisms=(state:any)=>encodeGraph({terranElites:state.terranElites,p4Samples:state.p4Samples,weaponFlights:state.weaponFlights,combat:[...state.entities.values()].filter((u:Entity)=>u.team==='player').map((u:Entity)=>({id:u.id,bornAt:u.bornAt,eliteId:u.eliteId,combat:u.eliteCombat,hp:u.hp,maxHp:u.maxHp,armor:u.armor,moveSpeed:u.moveSpeed,auraFactor:u.eliteHpAuraFactor,heroId:u.heroId,shield:u.shield,energy:u.energy,nativeMode:u.nativeMode,desiredNativeMode:u.desiredNativeMode,mode:u.mode,weaponCooldown:u.weaponCooldown,nextShotAt:u.nextShotAt}))});
try{for(const {ids,before,file} of fixtures){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});page=await context.newPage();page.on('pageerror',(e:any)=>report.errors.push(e.message));await page.goto(process.env.QA_OFFLINE_HTML?pathToFileURL(path.resolve(process.env.QA_OFFLINE_HTML)).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle');
 const restored=await exportRun();assert.equal(restored.schema,21);assert.deepEqual(mechanisms(restored.state),mechanisms(before.state));assert.equal(restored.state.time,before.state.time);assert.equal(restored.state.paused,true);const r=await page.evaluate(()=>window.__SC2_REPORT__());assert.equal(r.terranElites.medical.beams,ids.includes('medivac.2')?5:ids.includes('medivac.1')?1:0);assert.deepEqual(r.errors,[]);await page.screenshot({path:out+'/'+ids[0]+'-import-paused.png'});
 await page.locator('.end-screen [data-action=pause]').click();await page.waitForFunction(time=>window.__SC2_REPORT__().time>time+1.4,before.state.time,{timeout:30000});await page.screenshot({path:out+'/'+ids[0]+'.png'});await page.locator(`[data-seat="${ELITES[ids[0]].family}:0"]`).first().click();await page.screenshot({path:out+'/'+ids[0]+'-details.png'});await page.locator('[data-inspect-close]').click();
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const after=await exportRun();assert.ok(after.state.stats.damage>before.state.stats.damage);assert.equal(after.schema,21);assert.equal(after.state.p4Samples.enabled,false);
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();const loaded=await exportRun();assert.deepEqual(mechanisms(loaded.state),mechanisms(after.state));assert.equal(loaded.state.time,after.state.time);assert.equal(loaded.state.paused,true);assert.deepEqual(encodeGraph(loaded.state.wallet),encodeGraph(after.state.wallet));assert.deepEqual(encodeGraph(loaded.state.expedition.ledger),encodeGraph(after.state.expedition.ledger));report.checks.push({ids,schema:loaded.schema,importedPackets:before.state.weaponFlights.length,areas:before.state.terranElites.areas.length,mines:before.state.p4Samples.mines.length,barriers:before.state.p4Samples.barriers.length,absorptions:before.state.terranElites.absorptions.length,heroAura:ids.includes('medivac.1')?[...loaded.state.entities.values()].filter(u=>u.heroId).map(u=>({id:u.heroId,maxHp:u.maxHp,hp:u.hp,armor:u.armor,auraFactor:u.eliteHpAuraFactor})):[],damage:after.state.stats.damage-before.state.stats.damage,healed:after.state.stats.healed-before.state.stats.healed,saveRestored:true,mechanismsPreserved:true,debugApi:false});await context.close();console.log(ids.join('/')+': production integration passed');}assert.deepEqual(report.errors,[]);assert.equal(JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,report.appBuildId);
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;if(page&&!page.isClosed()){report.last=await page.evaluate(()=>window.__SC2_REPORT__?.());await page.screenshot({path:out+'/failure.png'});}}finally{await fs.writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,errors:report.errors,failure:report.failure??null}));}
