import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';import {openTalentLoot} from '../src/simulation/expedition-economy';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
const out='reports/local/opening-cover-flame-20261007/archive-actions';await fs.mkdir(out,{recursive:true});const fixtures=[];
const army=()=>{const p=new PermanentProfile(59);assert.ok(p.savePresetBlueprint('terran',0,Object.fromEntries(MVP_TALENTS.filter(n=>n.race==='terran'&&n.line==='army').map(n=>[n.id,n.maxRank]))));return p;};
const make=(seed:number,profile?:PermanentProfile)=>new World({seed,waves:false,permanentProfile:profile,terrain:campaignTerrain(chooseCampaignMap(seed))});
const add=async(w:World,name:string,save=true)=>{w.paused=true;const file=path.resolve(out,name+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));fixtures.push({name,file,save});};
const talent=make(73);talent.start();talent.expedition.talentLootReceipts.push('archive-audit:talent');assert.ok(openTalentLoot(talent,'archive-audit:talent','orange'));await add(talent,'talent');
const rescue=make(75,army());rescue.start();for(let i=0;i<100&&!rescue.eliteRescueChoice;i++){const egg=rescue.spawnEconomic('egg',{x:3,z:0});rescue.hit(egg,egg.maxHp+20,[],1,'terran');}assert.ok(rescue.eliteRescueChoice);await add(rescue,'rescue');
const full=make(21,army());full.start();while(full.familySeatCount('marine')<full.rosterCap)full.addFamilyMember('marine',full.freePosition('marine',full.anchor,1,7)!,1);for(let i=1;i<3;i++){full.endStage();full.skipReward();full.skipReward();}full.endStage();full.skipReward();full.wallet={minerals:10000,gas:10000};assert.ok(full.buyEliteContract(full.expedition.eliteContracts[0].id,'marine.2'));assert.ok(full.expedition.pendingShopElite);await add(full,'paid-promotion');
const free=make(76,army());free.start();while(free.familySeatCount('marine')<free.rosterCap)free.addFamilyMember('marine',free.freePosition('marine',free.anchor,1,7)!,1);assert.ok(free.acquireElite('marine.2'));assert.ok(free.eliteChoice);await add(free,'free-promotion');
const wonFile=path.resolve('reports/local/ui-fidelity-round-20261006/fixtures/won.json');readArchive(await fs.readFile(wonFile,'utf8'));fixtures.push({name:'won',file:wonFile,save:true});
const endlessSource=readArchive(await fs.readFile('reports/local/ui-fidelity-round-20261006/fixtures/endless.json','utf8')).bundle,endless=make(77);assert.ok(endless.permanentProfile.importJSON(endlessSource.profile));endless.restoreRun(endlessSource.run!);assert.equal(endless.phase,'reward');assert.ok(endless.skipReward());assert.ok(endless.skipReward());assert.equal(endless.phase,'endless-ready');await add(endless,'endless',false);
if(process.argv.includes('--fixtures-only')){console.log(JSON.stringify({validatedFixtures:fixtures.map(f=>f.name)}));process.exit(0);}
const server=createGameServer({webRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),c=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true,reducedMotion:'reduce'}),p=await c.newPage();
const report:any={at:new Date().toISOString(),appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],screens:[],errors:[],method:'Current validated diagnostic decision archives, actual save/export/local-reload controls; no paid claim, decline or phase advance occurs during archive tests. Not natural campaigns or physical-device acceptance.'};p.on('pageerror',e=>report.errors.push(e.message));
const hash=(s:any)=>createHash('sha256').update(JSON.stringify(encodeGraph(s))).digest('hex');const exported=async()=>{const [d]=await Promise.all([p.waitForEvent('download',{timeout:60000}),p.locator('[data-action=save-export]:visible').click()]);return readArchive(await fs.readFile(await d.path(),'utf8')).bundle;};
const ready=async()=>{const start=Date.now();for(;;){try{await p.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness?.phase),null,{timeout:30000});break;}catch(e){if(Date.now()-start>240000)throw e;}}assert.equal((await p.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await p.locator('[data-action=flow-continue]').click();};
try{for(const f of fixtures){console.log('Archive case '+f.name);await p.setViewportSize({width:1280,height:720});await p.goto(url);await p.locator('#scs-opening-visual').waitFor({state:'detached'});await p.locator('.main-actions [data-action=menu-load]').click();const chooser=p.waitForEvent('filechooser');await p.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(f.file);await p.locator('[data-action=menu-load-ready]').click();await ready();console.log('Loaded '+f.name+' '+JSON.stringify((await p.evaluate(()=>window.__SC2_REPORT__())).save));const before=await exported();
 for(const [width,height]of [[1280,720],[390,844],[844,390],[844,350]]){await p.setViewportSize({width,height});for(const action of f.save?['save-now','save-export']:['save-export','restart']){const b=p.locator('[data-action='+action+']:visible');assert.equal(await b.count(),1);await b.scrollIntoViewIfNeeded();const box=(await b.boundingBox())!;assert.ok(box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1,f.name+' '+action+' '+width+'x'+height);}const name=f.name+'-'+width+'x'+height;await p.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);}
 await p.setViewportSize({width:1280,height:720});if(f.save){await p.locator('[data-action=save-now]:visible').click();await p.waitForFunction(()=>!window.__SC2_REPORT__().save.busy);}assert.equal(hash(await exported()),hash(before),'Save/export must preserve complete World/profile');
 await p.reload();await p.locator('#scs-opening-visual').waitFor({state:'detached'});await p.locator('.main-actions [data-action=menu-load]').click();await p.locator('[data-action=menu-load-local]').click();await p.locator('[data-action=menu-load-ready]').click();await ready();const after=await exported();assert.equal(hash(after.run),hash(before.run),'Saved pending decision must survive exact reload');const expected=PermanentProfile.parseJSON(before.profile)!;assert.ok(expected.importJSON(before.profile));assert.equal(after.profile,expected.exportJSON());report.checks.push({decision:f.name,sizes:4,saveRestored:f.save,exportRestored:true,fullArchiveUnchangedBySaveExport:true,fullRunUnchangedByReload:true,profileMatchesNativeImport:true});}
assert.deepEqual(report.errors,[]);report.passed=true;}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;await p.screenshot({path:out+'/failure.png'}).catch(()=>{});}finally{await browser.close();await new Promise<void>(r=>server.close(()=>r()));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,captures:report.screens.length,errors:report.errors,failure:report.failure}));}
