import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';import {openTalentLoot} from '../src/simulation/expedition-economy';import {receiptNeeded} from '../src/simulation/expedition-production';
import {readArchive,writeArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
const out=process.env.SC2_QA_DIR??'reports/local/ui-fidelity-round-20261006/extra',url=process.env.SC2_UI_URL??'http://127.0.0.1:4190/';await fs.mkdir(out,{recursive:true});
const make=(seed=21,profile?:PermanentProfile)=>new World({seed,waves:false,permanentProfile:profile,terrain:campaignTerrain({version:3,seed,theme:'industrial'})});
const archive=async(w:World,name:string)=>{w.paused=true;const file=path.resolve(out,name+'.json'),raw=writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()});const clone=make();clone.permanentProfile.importJSON(w.permanentProfile.exportJSON());clone.restoreRun(readArchive(raw).bundle.run!);await fs.writeFile(file,raw);return file;};
const profile=new PermanentProfile(59),levels=Object.fromEntries(MVP_TALENTS.filter(n=>n.race==='terran'&&n.line==='army').map(n=>[n.id,n.maxRank])),q=profile.previewTalentAllocation('terran',0,levels)!;assert.ok(profile.commitTalentAllocation(q,q.expectedRevision));
const elite=make(21,profile);elite.start();while(elite.familySeatCount('marine')<elite.rosterCap){const p=elite.freePosition('marine',elite.anchor,1,7)!;elite.addFamilyMember('marine',p,1);}for(let i=1;i<3;i++){elite.endStage();elite.skipReward();elite.skipReward();}elite.endStage();elite.skipReward();elite.wallet={minerals:10000,gas:10000};assert.ok(elite.expedition.eliteContracts.length);const eliteFile=await archive(elite,'full-elite');
const talent=make(73);talent.start();talent.expedition.talentLootReceipts.push('ui-fidelity:talent:1');assert.ok(openTalentLoot(talent,'ui-fidelity:talent:1','orange'));const talentFile=await archive(talent,'talent-loot');
const boss=make(73);boss.start();while(boss.familySeatCount('marine')<boss.rosterCap)boss.addFamilyMember('marine',boss.freePosition('marine',boss.anchor,1,7)!,1);const enemy=boss.spawnSpecial('zergling','boss',boss.freePosition('zergling',boss.anchor,6,12)!)!;boss.hit(enemy,1e9,[],1,'terran');assert.ok(boss.collectRewardDrop(boss.rewardDrops.find(d=>d.bossLootReceipt)!.id));const bossFile=await archive(boss,'boss-loot');
const family=make(74);family.start();family.expedition.familySlots=['marine','marauder','reaper','hellion','tank'];family.expedition.tech.starport=family.expedition.tech.factory=family.expedition.tech.starport_lab=1;const pod=family.spawnPod('viking',family.freePosition('viking',family.anchor,6,12)!,99,1);pod.status='opening';pod.resolvedAt=0;pod.guardianIds.clear();family.expedition.ledger.push({id:99,family:'viking',line:'starport',facilityIds:[1],remaining:0,state:'risk',podId:pod.id,passengers:[{paid:{minerals:125,gas:75},status:'waiting',entityId:null,purpose:'body'}]});assert.ok(receiptNeeded(family,pod,0));const familyFile=await archive(family,'family-receipt');
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),ctx=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true}),page=await ctx.newPage();
const report:any={method:'Isolated current-map engineering fixtures, native quotes/receipts, public UI operations; complete run and profile equality against the same native command. No natural campaign/device claim.',checks:[],screens:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
const tap=async(s:string)=>page.locator(s+':visible:not(:disabled)').last().click();
const shot=async(name:string)=>{await page.screenshot({path:out+'/'+name+'.png',animations:'disabled'});report.screens.push(name);console.log(name);};
const load=async(file:string)=>{await page.goto(url,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await tap('.main-actions [data-action=menu-load]');await page.locator('input[type=file]').setInputFiles(file);await tap('[data-action=menu-load-ready]');await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness.phase),null,{timeout:240000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await tap('[data-action=flow-continue]');};
const exported=async()=>{if(await page.locator('[data-action=ui-menu]:visible').count()){await tap('[data-action=ui-menu]');await tap('[data-action=settings]');await tap('[data-action=settings-tab][data-tab=saves]');}const pending=page.waitForEvent('download');await tap('[data-action=save-export]');const b=readArchive(await fs.readFile(await(await pending).path()!,'utf8')).bundle;if(await page.locator('[data-action=settings-back]:visible').count())await tap('[data-action=settings-back]');if(await page.locator('[data-ui-route=menu] .pause-modal').count())await tap('[data-action=ui-back]');return b;};
const snapshot=(w:World)=>JSON.stringify(encodeGraph({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));
const expected=(bundle:any,imports=0)=>{const p=PermanentProfile.parseJSON(bundle.profile)!;for(let i=0;i<imports;i++)p.importJSON(p.exportJSON());const w=make(21,p);w.restoreRun(bundle.run);return w;};
const equal=async(actual:any,w:World)=>{const expected={profile:w.permanentProfile.exportJSON(),run:w.captureRun()};await fs.writeFile(out+'/last-actual.json',writeArchive({profile:actual.profile,run:actual.run}));await fs.writeFile(out+'/last-expected.json',writeArchive(expected));const a=JSON.stringify(encodeGraph({profile:actual.profile,run:actual.run})),b=snapshot(w);if(a!==b)throw Error('Complete state differs: compare last-actual.json and last-expected.json');};
try{
 if(process.env.SC2_UI_EXTRA!=='fonts'){await load(eliteFile);const initial=await exported(),native=expected(initial);await tap('[data-action=ui-menu]');await tap('[data-action=ui-page][data-page=contracts]');await tap('[data-action=ui-contract]');assert.equal(await page.locator('.im-elite-choice').count(),3);await tap('[data-action=ui-variant-select][data-variant="marine.2"]');
 for(const [width,height]of [[1280,720],[390,844],[844,390]]){await page.setViewportSize({width,height});await shot('elite-variants-'+width+'x'+height);}
 await page.setViewportSize({width:1280,height:720});await tap('[data-action=elite-contract]');await page.locator('[data-action=shop-elite-confirm]:not(:disabled)').waitFor({timeout:240000});await shot('elite-full-confirm');await tap('[data-action=shop-elite-cancel]');await page.keyboard.press('Escape');await page.keyboard.press('Escape');await equal(await exported(),native);report.checks.push('Canceled full-roster contract preserves entire run and profile');
 await tap('[data-action=ui-menu]');await tap('[data-action=ui-page][data-page=contracts]');await tap('[data-action=ui-contract]');await tap('[data-action=ui-variant-select][data-variant="marine.2"]');await tap('[data-action=elite-contract]');const confirmation=page.locator('[data-action=shop-elite-confirm]:not(:disabled)');await confirmation.waitFor({timeout:240000});const target=Number(await confirmation.getAttribute('data-id')),contract=native.expedition.eliteContracts[0];assert.ok(native.buyEliteContract(contract.id,'marine.2'));assert.ok(native.confirmShopElite(target));await confirmation.dblclick();await equal(await exported(),native);report.checks.push('Double click produces exactly one native paid elite transaction');
 await load(talentFile);for(const [width,height]of [[1280,720],[390,844],[844,390]]){await page.setViewportSize({width,height});await shot('talent-loot-'+width+'x'+height);}await page.setViewportSize({width:1280,height:720});const gift=page.locator('.im-card-bottom [data-action=talent-loot]:not(:disabled)').first();assert.ok(await gift.count());const receipt=(await gift.getAttribute('data-receipt'))!,offer=(await gift.getAttribute('data-id'))!,variant=await gift.getAttribute('data-variant');const tn=expected(readArchive(await fs.readFile(talentFile,'utf8')).bundle,1);assert.ok(tn.claimTalentLoot(receipt,offer,variant as never));await gift.click();const b=await page.evaluate(()=>window.__SC2_REPORT__());assert.ok(b);if(!(await page.locator('.pause-modal:visible').count()))await tap('#topbar [data-action=pause]');await equal(await exported(),tn);report.checks.push('Actual free talent gift stays available outside shop and equals native claim');
 await load(bossFile);for(const [width,height]of [[1280,720],[390,844],[844,390]]){await page.setViewportSize({width,height});await shot('boss-loot-'+width+'x'+height);}await page.setViewportSize({width:1280,height:720});await tap('[data-action=boss-loot-close]');const bn=expected(readArchive(await fs.readFile(bossFile,'utf8')).bundle,1);assert.ok(bn.closeBossLoot());await equal(await exported(),bn);report.checks.push('Deferring real boss loot preserves reward, funds and explicit pause state');
 await load(familyFile);for(const [width,height]of [[1280,720],[390,844],[844,390]]){await page.setViewportSize({width,height});await shot('family-receipt-'+width+'x'+height);}await page.setViewportSize({width:1280,height:720});await page.keyboard.press('Escape');await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='menu');await tap('.main-actions [data-action=menu-load]');await tap('[data-action=menu-load-local]');await tap('[data-action=menu-load-ready]');await page.waitForFunction(()=>window.__SC2_REPORT__().readiness.phase==='ready',null,{timeout:240000});await tap('[data-action=flow-continue]');await tap('[data-action=family-reject]');const fn=expected(readArchive(await fs.readFile(familyFile,'utf8')).bundle,2),request=fn.expedition.pendingReceipt!;assert.ok(fn.rejectIncomingBatch(request.id,fn.revision));if(!(await page.locator('.pause-modal:visible').count()))await tap('#topbar [data-action=pause]');await equal(await exported(),fn);report.checks.push('Escape retains mandatory family choice through save/load; rejection equals original command');
 await tap('[data-action=restart]');}else{await page.goto(url);await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');}
 for(const [width,height]of [[320,568],[390,844],[844,390]])for(const scale of ['1.25','1.5']){await page.setViewportSize({width,height});await tap('[data-action=settings]');await tap('[data-action=settings-tab][data-tab=graphics]');await page.locator('[data-setting=text-scale]').selectOption(scale);await shot('text-settings-'+width+'x'+height+'-'+scale);await tap('[data-action=settings-back]');await tap('[data-action=talents]');await tap('[data-action=mvp-talent-race][data-race=terran]');await tap('[data-action=talent-line][data-line=resources]');await shot('text-talents-'+width+'x'+height+'-'+scale);await tap('[data-action=talent-exit]');}
 report.checks.push('125% and 150% actual font setting across minimum portrait, portrait and short landscape');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;await shot('failure').catch(()=>{});}
finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({passed:report.passed,checks:report.checks,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
