import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
const out='reports/local/opening-cover-flame-20261007/text-scale';await fs.mkdir(out,{recursive:true});
const candidates=[['before','dist/UI-Coze-Main-Application-20261007/public'],['after','dist/web']]as const,servers=[];
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const report:any={at:new Date().toISOString(),viewport:[883,850],checks:[],errors:[],screens:[]};
try{for(const [name,root]of candidates){const server=createGameServer({webRoot:path.resolve(root),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});servers.push(server);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
 for(const scale of [1,1.5]){const c=await browser.newContext({viewport:{width:883,height:850},reducedMotion:'reduce'});await c.addInitScript(value=>localStorage.setItem('sc2.text-scale',String(value)),scale);const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto('http://127.0.0.1:'+(server.address()as any).port);await p.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');if(await p.locator('#scs-opening-visual').count())await p.locator('#scs-opening-visual').waitFor({state:'detached'});await p.locator('[data-action=menu-new]').click();await p.locator('[data-action=menu-race-next]').click();await p.locator('[data-action=menu-difficulty-next]').click();
  const layout=await p.locator('.confirm-layout').evaluate(root=>{const boxes=(selector:string)=>[...root.querySelectorAll<HTMLElement>(selector)].map(el=>{const b=el.getBoundingClientRect();return {rect:[b.x,b.y,b.width,b.height],font:getComputedStyle(el).fontSize,text:el.innerText};});return {panels:boxes('.config-panel'),headings:boxes('.config-panel h2'),roster:boxes('.starting-roster b'),resources:boxes('.starting-resource'),presets:boxes('.preset-tabs button')};});assert.equal(layout.panels.length,2);assert.equal(layout.presets.length,3);assert.ok(layout.roster[0].text.includes('陆战队员 ×1'));await p.screenshot({path:out+'/'+name+'-'+scale+'.png'});report.screens.push(name+'-'+scale);report.checks.push({name,scale,appBuildId:JSON.parse(await fs.readFile(root+'/web-release.json','utf8')).appBuildId,layout});await c.close();
 }}for(const scale of [1,1.5]){const before=report.checks.find((r:any)=>r.name==='before'&&r.scale===scale),after=report.checks.find((r:any)=>r.name==='after'&&r.scale===scale);assert.deepEqual(after.layout.headings.map((h:any)=>h.font),before.layout.headings.map((h:any)=>h.font));assert.deepEqual(after.layout.roster.map((h:any)=>h.font),before.layout.roster.map((h:any)=>h.font));assert.deepEqual(after.layout.presets.map((h:any)=>h.font),before.layout.presets.map((h:any)=>h.font));}
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{await browser.close();for(const server of servers)await new Promise<void>(r=>server.close(()=>r()));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
