import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
import {World} from '../src/simulation/world';import {campaignTerrain} from '../src/data/campaign-map';import {campaign18Schedule,campaign18StageConfig} from '../src/data/campaign18';import {ENDLESS} from '../src/data/endless';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';import {createGameServer} from './coze-web-server.mjs';
const offline=process.argv.includes('--offline'),out='reports/local/ui-integration-20261006/endless-'+(offline?'offline':'web');await fs.mkdir(out,{recursive:true});
// A diagnostic victory state using the genuine final Boss and end-stage rules; no natural-play claim.
const w=new World({race:'terran',waves:false,seed:41,terrain:campaignTerrain({version:3,seed:41,theme:'industrial'})});w.start();w.stage=18;w.prepareStage();w.hive!.hp=0;const event=campaign18Schedule(campaign18StageConfig(18,w.difficulty),41).specials[0],boss=(w as any).spawnCampaignSpecial(event);assert.ok(boss);w.hit(boss,1e9,[],1,'terran');w.stageElapsed=w.duration;w.endStage();assert.equal(w.phase,'won');w.closeBossLoot();
const fixture=path.resolve(out,'victory.json');await fs.writeFile(fixture,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--allow-file-access-from-files']});const context=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true});if(offline)await context.setOffline(true);
await context.addInitScript({content:`const pad={id:'UI return verification',index:0,mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array.from({length:16},()=>({value:0,pressed:false,touched:false}))};Object.defineProperty(navigator,'getGamepads',{configurable:true,value:()=>[pad]});window.__UI_PAD__=pad;`});const page=await context.newPage();page.setDefaultTimeout(30000);const report:any={offline,appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,method:'Diagnostic final-Boss victory fixture; public UI only after archive import. No natural-campaign claim.',checks:[],screens:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(offline&&r.url().includes('/api/'))report.errors.push('offline API request');});
const shot=async(n:string)=>{await page.screenshot({path:out+'/'+n+'.png'});report.screens.push(n);};
const ready=()=>page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness.phase==='ready',null,{timeout:240000});
const exported=async()=>{const d=page.waitForEvent('download');await page.locator('[data-action=save-export]:visible').click();return readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle.run!;};
const key=(r:any)=>JSON.stringify(encodeGraph({config:r.config,map:r.map,time:r.state.time,wallet:r.state.wallet,entities:r.state.entities,pods:r.state.pods,ledger:r.state.expedition.ledger,endless:r.state.endless,battlefield:r.state.battlefield,auras:r.state.teamAuras,flights:r.state.weaponFlights,casts:r.state.heroCasts,rng:r.state.rngState}));
try{
 await page.goto(offline?pathToFileURL(path.resolve('dist/SC2-Survivors-Current-20261006.html')).href:`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await page.locator('[data-action=menu-load]').click();const c=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await c).setFiles(fixture);await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();assert.match(await page.locator('.end-screen').innerText(),new RegExp('无尽每轮'+ENDLESS.roundDuration+'秒'));await shot('victory');
 await page.locator('[data-action=endless]').click();await page.locator('[data-action=ui-page][data-page=catalog]').click();await page.locator('[data-action=ui-catalog-detail]').first().click();
 const back=async()=>{await page.waitForTimeout(120);await page.evaluate(()=>{(window as any).__UI_PAD__.buttons[1]={value:1,pressed:true,touched:true};});await page.waitForTimeout(100);await page.evaluate(()=>{(window as any).__UI_PAD__.buttons[1]={value:0,pressed:false,touched:false};});await page.waitForTimeout(120);};
 await back();assert.equal(await page.locator('[data-ui-route=catalog]').count(),1);await back();assert.equal(await page.locator('[data-ui-route=root]').count(),1);await shot('preparation');await back();assert.equal(await page.locator('[data-action=endless]').count(),1);report.checks.push('virtual gamepad B pops catalogue detail, catalogue and endless preparation one level at a time');
 await page.locator('[data-action=endless]').click();await page.locator('[data-action=skip]').click();await page.locator('[data-action=skip]').click();await page.locator('[data-action=endless-prepare]').waitFor();const prepared=await exported();await page.locator('[data-action=endless-back]').click();await page.locator('[data-action=endless]').click();const restored=await exported();assert.equal(restored.state.endlessEntry!.revision,prepared.state.endlessEntry!.revision);assert.deepEqual(restored.state.wallet,prepared.state.wallet);await shot('preparation-complete');
 report.checks.push('completed preparation survives return and re-entry without repeated payment');
 await page.locator('[data-action=endless-prepare]').click();await ready();await page.locator('[data-action=flow-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().phase==='battle'&&window.__SC2_REPORT__().time>.2);await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('已保存'));const saved=await exported();assert.equal(saved.state.battlefield.mode,'endless');assert.equal(saved.state.endless!.round,1);await shot('endless-saved');
 await page.reload({timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await page.locator('[data-action=menu-load]').click();await page.locator('[data-action=menu-load-local]').click();await page.locator('[data-action=menu-load-ready]').click();await ready();await page.locator('[data-action=flow-continue]').click();assert.equal(key(await exported()),key(saved));report.checks.push('public ready commit enters original endless map and exact save state survives reload');assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack);process.exitCode=1;await shot('failure').catch(()=>{});}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify(report));}
