import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import assert from 'node:assert/strict';
const out=process.env.SC2_QA_DIR??'reports/local/ui-fidelity-round-20261006/aux',url=process.env.SC2_UI_URL??'http://127.0.0.1:4190/';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),context=await browser.newContext({viewport:{width:1280,height:720}}),page=await context.newPage();
const report:any={screens:[],checks:[],errors:[],posts:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(r.method()==='POST')report.posts.push(r.url());});
const click=async(s:string)=>page.locator(s+':visible:not(:disabled)').last().click();
const shot=async(name:string)=>{await page.screenshot({path:out+'/'+name+'.png',animations:'disabled'});report.screens.push(name);};
try{await page.goto(url);await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await click('[data-action=settings]');await click('[data-action=settings-tab][data-tab=saves]');
 for(const [width,height]of [[1280,720],[390,844],[844,390]]){await page.setViewportSize({width,height});await click('[data-action=resource-downloads]');assert.ok(await page.locator('#resource-downloads[open]').count());await shot('resources-'+width+'x'+height);await click('#resource-downloads [data-close]');
  await click('[data-player-service=privacy]');assert.ok(await page.locator('#player-services-dialog[open]').count());await shot('privacy-'+width+'x'+height);assert.ok(await page.locator('[data-service-action=allow]').isDisabled());await click('[data-service-action=feedback]');await page.locator('textarea[name=text]').fill('本地 UI 验证草稿，不发送。');assert.ok(await page.locator('#player-feedback button[type=submit]').isDisabled());await shot('feedback-'+width+'x'+height);await click('[data-service-action=close]');await click('[data-player-service=feedback]');assert.equal(await page.locator('textarea[name=text]').inputValue(),'本地 UI 验证草稿，不发送。');await page.keyboard.press('Escape');assert.equal(await page.locator('#player-services-dialog[open]').count(),0);
 }
 await click('[data-action=settings-tab][data-tab=controls]');await click('[data-action=controller]');await shot('controller-calibration');await page.keyboard.press('Escape');assert.ok(await page.locator('#gamepad-calibration').isHidden());
 assert.equal(await page.evaluate(()=>localStorage.getItem('sc2.telemetry.identity.v1')),null);assert.deepEqual(report.posts,[]);assert.deepEqual(report.errors,[]);report.checks=['Native resource window at three sizes','Privacy and feedback use current disabled backend facts','Feedback draft retained without submission','No statistics identity or POST request','Controller calibration returns one level'];report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;await shot('failure').catch(()=>{});}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
