/** Final shared progress-row correction, paired against the original card pages. */
import {chromium,type Page} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const out='reports/local/ui-fidelity-round-20261006/cards-final',url='http://127.0.0.1:4192/',ref='http://127.0.0.1:4191/reports/local/ui-fidelity-round-20261006/reference-frame.html';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),report:any={captures:[],errors:[]};
const click=async(p:Page,s:string)=>p.locator(s+':visible:not(:disabled)').last().click();
const capture=async(p:Page,name:string)=>{await p.waitForFunction(()=>document.getAnimations().filter(a=>Number.isFinite(a.effect?.getTiming().iterations)).every(a=>a.playState!=='running'));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].filter(i=>i.currentSrc&&i.getBoundingClientRect().width).map(i=>i.decode().catch(()=>{})));});const parts=await p.evaluate(()=>['.im-heading','.im-steps','.im-caption','.im-choice-grid','.im-card','.im-footer'].flatMap(selector=>[...document.querySelectorAll<HTMLElement>(selector)].filter(e=>e.getBoundingClientRect().width).map((e,index)=>({selector,index,rect:e.getBoundingClientRect().toJSON(),font:getComputedStyle(e).font,color:getComputedStyle(e).color}))));await p.screenshot({path:out+'/'+name+'.png',animations:'disabled'});report.captures.push({name,parts});};
try{for(const [view,width,height,touch]of [['desktop',1280,720,false],['portrait',390,844,true],['minimum',320,568,true],['short-landscape',844,390,true],['narrow-desktop',1024,768,false]]as const){
 const ctx=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch}),p=await ctx.newPage();await p.bringToFront();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(url,{timeout:120000});await p.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await click(p,'.main-actions [data-action=menu-load]');await p.locator('input[type=file][accept*=json]').setInputFiles(path.resolve('reports/local/ui-fidelity-round-20261006/fixtures/terran-development.json'));await click(p,'[data-action=menu-load-ready]');await p.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness.phase),null,{timeout:240000});assert.equal(await p.evaluate(()=>window.__SC2_REPORT__().readiness.phase),'ready');await click(p,'[data-action=flow-continue]');if(await p.locator('[data-action=development-direction]').count())await p.locator('[data-action=development-direction]').first().click();await capture(p,'runtime-development-'+view);
 for(const route of ['heroes','rest']){await click(p,'[data-action=ui-menu]');await click(p,'[data-action=ui-page][data-page='+route+']');await capture(p,'runtime-'+route+'-'+view);await click(p,'[data-action=ui-back]');}await ctx.close();
 const rc=await browser.newContext({viewport:{width,height}}),rp=await rc.newPage();for(const route of ['development','heroes','rest']){await rp.goto(ref+'?device='+(touch?'mobile':'desktop')+'#'+route,{timeout:120000});await rp.waitForFunction((route:string)=>(window as any).__UI_PREVIEW__?.getState().page===route,route);await capture(rp,'reference-'+route+'-'+view);}await rc.close();await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(view+' final cards paired');
}assert.deepEqual(report.errors,[]);}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({captures:report.captures.length,errors:report.errors,failure:report.failure??null}));}
