import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {chromium} from '@playwright/test';import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {campaignTerrain,chooseCampaignMap} from '../src/data/campaign-map';
import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';
import {HEROES,type HeroId} from '../src/data/heroes';import {PAINTED_CARDS} from '../src/assets/ui-art.generated';
import {ELITES} from '../src/data/elites';import {SC2_UNITS} from '../src/data/sc2-units';
const out='reports/local/opening-cover-flame-20261007/art-flow';await fs.mkdir(out,{recursive:true});
const release=JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),manifest=JSON.parse(await fs.readFile('dist/web/'+release.manifest,'utf8'));
const fixtures=[];
for(const race of ['terran','zerg','protoss']as const){
 const w=new World({race,seed:10708,waves:false,terrain:campaignTerrain(chooseCampaignMap(10708))});assert.ok(w.start());
 for(let i=1;i<16;i++){w.endStage();assert.ok(w.skipReward());assert.ok(w.skipReward());}w.wallet={minerals:1000000,gas:1000000};w.endStage();assert.ok(w.skipReward());
 let rerolls=0;while(!w.rewards.some(r=>(r as any).expeditionEffect?.kind==='hero')&&rerolls<200){assert.ok(w.reroll());rerolls++;}
 const offer=w.rewards.find(r=>(r as any).expeditionEffect?.kind==='hero');assert.ok(offer,'Real random hero offer required: '+race);w.wallet={minerals:10000,gas:10000};w.paused=true;
 const file=path.resolve(out,race+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));fixtures.push({race,file,offerId:offer.offerId,hero:(offer as any).expeditionEffect.heroId as HeroId,price:{minerals:offer.minerals,gas:offer.gas},rerolls});
}
const server=createGameServer({webRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),url='http://127.0.0.1:'+(server.address()as any).port;
const report:any={at:new Date().toISOString(),appBuildId:release.appBuildId,checks:[],screens:[],errors:[],method:'Production UI, actual seeded World stage transitions and random offers with a diagnostic wallet. Catalogue and detail navigation compare the entire exported run/profile. Not earned campaigns or physical-device acceptance.'};let active:any;
const shot=async(p:any,name:string)=>{await p.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);};
const archiveHash=(bundle:any)=>createHash('sha256').update(JSON.stringify(encodeGraph(bundle))).digest('hex');
const exported=async(p:any)=>{await p.locator('[data-action=ui-menu]').click();assert.equal(await p.locator('[data-action=ui-page][data-page=heroes]').count(),0);await p.locator('.pause-modal [data-action=settings]').click();await p.locator('[data-action=settings-tab][data-tab=saves]').click();const d=p.waitForEvent('download');await p.locator('[data-action=save-export]:visible').click();const bundle=readArchive(await fs.readFile(await(await d).path(),'utf8')).bundle;await p.locator('.settings-modal .modal-footer [data-action=settings-back]').click();await p.locator('.pause-modal .modal-footer [data-action=ui-back]').click();return bundle;};
async function inspectArt(p:any,root:any,id:string){
 assert.equal(await root.locator('.painted-art').getAttribute('data-art-key'),id);const plate=(PAINTED_CARDS as any)[id],expected=manifest.assets[plate?'ui.paint.'+plate.assetKey:'ui.cover.'+id].url;
 const figure=root.locator(plate?'.im-unit-painting image':'.hero-cover img').first(),src=await figure.getAttribute(plate?'href':'src'),asset=manifest.assets[plate?'ui.paint.'+plate.assetKey:'ui.cover.'+id];
 const loaded=await p.evaluate(async(url:string)=>{const bytes=await(await fetch(url)).arrayBuffer(),hash=await crypto.subtle.digest('SHA-256',bytes),img=new Image();img.src=url;await img.decode();return {sha256:[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join(''),bytes:bytes.byteLength,width:img.naturalWidth,height:img.naturalHeight};},src);assert.equal(loaded.sha256,asset.sha256,id+' source identity');assert.equal(loaded.bytes,asset.bytes);assert.ok(loaded.width>0&&loaded.height>0);
 const geometry=await root.locator('.painted-art').evaluate((el:any)=>{const frame=el.getBoundingClientRect(),img=el.querySelector('img'),b=img?.getBoundingClientRect();return {frame:[frame.x,frame.y,frame.width,frame.height],image:b?[b.x,b.y,b.width,b.height]:null,fit:img?getComputedStyle(img).objectFit:null,position:img?getComputedStyle(img).position:null};});assert.ok(geometry.frame[2]>0&&geometry.frame[3]>0);
 if(!plate){assert.equal(geometry.fit,'cover');assert.equal(geometry.position,'absolute');assert.ok(Math.abs(geometry.image[2]-geometry.frame[2])<1);assert.ok(Math.abs(geometry.image[3]-geometry.frame[3])<1);}return {id,source:expected,geometry};
}
try{
 for(const [width,height]of [[1280,720],[390,844],[844,390]])for(const f of fixtures){
  const c=await browser.newContext({viewport:{width,height},hasTouch:width===390,reducedMotion:'reduce',acceptDownloads:true});active=c;const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(url);await p.locator('#scs-opening-visual').waitFor({state:'detached'});
  await p.locator('.main-actions [data-action=menu-load]').click();const picker=p.waitForEvent('filechooser');await p.locator('[data-action=menu-load-file]').click();await(await picker).setFiles(f.file);await p.locator('[data-action=menu-load-ready]').click();await p.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});await p.locator('[data-action=flow-continue]').click();
  const before=await exported(p),offer=p.locator('[data-card-id="'+f.offerId+'"]');assert.equal(await offer.locator('h2').innerText(),HEROES[f.hero].name);await inspectArt(p,offer,f.hero);await shot(p,'real-offer-'+f.race+'-'+width+'x'+height);
  await offer.locator('.im-card-face').click();await inspectArt(p,p.locator('.im-detail-art'),f.hero);assert.equal(await p.locator('.im-detail-dialog [data-action=reward]').count(),1);await p.locator('.im-detail-dialog .modal-footer [data-action=ui-back]').click();
  await p.locator('[data-action=ui-menu]').click();assert.equal(await p.locator('[data-page=heroes]').count(),0);await shot(p,'services-'+f.race+'-'+width+'x'+height);await p.locator('[data-action=ui-page][data-page=catalog]').click();await p.locator('[data-action=ui-catalog-race][data-race='+f.race+']').click();
  const art=[];for(const [group,total]of [['ordinary',10],['elite',30],['hero',6]]as const){await p.locator('[data-catalog-filter=group]').selectOption(group);const size=width>900?6:3,entries=[];for(let page=0;page<Math.ceil(total/size);page++){
   const cards=p.locator('.im-catalogue-grid .im-card'),n=await cards.count();for(let i=0;i<n;i++){const card=cards.nth(i),id=(await card.getAttribute('data-card-id')).split(':')[1],name=(HEROES as any)[id]?.name??(ELITES as any)[id]?.name??(SC2_UNITS as any)[id]?.zh;assert.equal(await card.locator('h2').innerText(),name);if(group==='hero')assert.equal(await card.locator('.im-card-meta>span').innerText(),'英雄');const item=await inspectArt(p,card,id),count=await card.locator('.painted-art').getAttribute('data-body-count');assert.equal(count,id.split('.')[0]==='zergling'?'2':'1');entries.push({...item,bodies:Number(count)});}
   await shot(p,'catalog-'+group+'-'+f.race+'-'+width+'x'+height+'-'+page);await cards.first().locator('.im-card-face').click();const id=entries[entries.length-n].id;await inspectArt(p,p.locator('.im-detail-art'),id);assert.equal(await p.locator('.im-detail-dialog [data-action=reward]').count(),0);if(page===0)await shot(p,'detail-'+group+'-'+f.race+'-'+width+'x'+height);await p.locator('.im-detail-dialog .modal-footer [data-action=ui-back]').click();if(page+1<Math.ceil(total/size))await p.locator('[data-action=ui-catalog-next]').click();
  }assert.equal(entries.length,total);assert.equal(new Set(entries.map(h=>h.id)).size,total);art.push({group,entries});}
  await p.locator('[data-action=ui-back]').first().click();const after=await exported(p);assert.equal(archiveHash(after),archiveHash(before),'Catalogue and art inspection must preserve full World/profile');
  report.checks.push({view:width+'x'+height,race:f.race,art,realRandomOffer:{hero:f.hero,price:f.price,rerolls:f.rerolls},independentHeroRouteRemoved:true,allCatalogueCardsReadOnly:true,completeArchiveUnchanged:true});await c.close();active=null;
 }assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{if(active)await active.close().catch(()=>{});await browser.close();await new Promise<void>(r=>server.close(()=>r()));await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,captures:report.screens.length,errors:report.errors,failure:report.failure}));}
