import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';import {campaignTerrain} from '../src/data/campaign-map';import {writeArchive,readArchive} from '../src/persistence/archive';import {encodeGraph} from '../src/persistence/graph-codec';import {createGameServer} from './coze-web-server.mjs';
const out=process.env.SC2_UI_QA_DIR??'reports/local/ui-integration-20261006/contracts-first';await fs.mkdir(out,{recursive:true});
const profile=new PermanentProfile(59),levels=Object.fromEntries(MVP_TALENTS.filter(n=>n.race==='terran'&&n.line==='army').map(n=>[n.id,n.maxRank])),quote=profile.previewTalentAllocation('terran',0,levels)!;assert.ok(profile.commitTalentAllocation(quote,quote.expectedRevision));
const world=new World({race:'terran',permanentProfile:profile,seed:21,waves:false,terrain:campaignTerrain({version:3,seed:21,theme:'industrial'})});world.start();
while(world.familySeatCount('marine')<world.rosterCap){const pos=world.freePosition('marine',world.anchor,1,7);assert.ok(pos);world.addFamilyMember('marine',pos,1);}
world.stage=3;world.endStage();assert.ok(world.skipReward());world.wallet={minerals:10000,gas:10000};assert.equal(world.expedition.eliteContracts[0].family,'marine');
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});const context=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true});const page=await context.newPage();page.setDefaultTimeout(30000);
const report:any={appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,checks:[],errors:[],screens:[]};page.on('pageerror',e=>report.errors.push(e.message));const shot=async(n:string)=>{await page.screenshot({path:out+'/'+n+'.png'});report.screens.push(n);};const state=(run:any)=>JSON.stringify(encodeGraph(run));
const exportRun=async()=>{await page.locator('[data-action=ui-page][data-page=rest]').click();const p=page.waitForEvent('download');await page.locator('[data-action=save-export]:visible').click();const run=readArchive(await fs.readFile(await(await p).path(),'utf8')).bundle.run!;await page.locator('[data-action=ui-back]').click();return run;};
async function load(poor=false){const run=world.captureRun();if(poor)run.state.wallet={minerals:0,gas:0};const file=path.resolve(out,poor?'poor.json':'full-roster.json');await fs.writeFile(file,writeArchive({profile:profile.exportJSON(),run}));await page.goto(`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await page.locator('[data-action=menu-load]').click();const p=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await p).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness.phase==='ready',null,{timeout:240000});await page.locator('[data-action=flow-continue]').click();}
async function variant(){await page.locator('[data-action=ui-page][data-page=contracts]').click();await page.locator('[data-action=ui-contract]').first().click();await page.locator('[data-action=ui-elite][data-variant="marine.2"]').click();}
try{
 await load();const before=await exportRun();await variant();await shot('elite-detail');await page.keyboard.press('Escape');assert.equal(await page.locator('[data-ui-route=contract]').count(),1);await shot('variants');await page.keyboard.press('Escape');assert.equal(await page.locator('[data-ui-route=contracts]').count(),1);await page.keyboard.press('Escape');assert.equal(state(await exportRun()),state(before));report.checks.push('contract → variants → detail → two back levels preserve complete archive');
 await variant();await page.locator('[data-action=elite-contract]').click();await page.locator('[data-action=shop-elite-confirm]').first().waitFor({state:'visible',timeout:240000});await shot('replacement');await page.locator('[data-action=shop-elite-cancel]').click();assert.equal(await page.locator('[data-ui-route=elite]').count(),1);for(let i=0;i<3;i++)await page.keyboard.press('Escape');const cancelled=await exportRun();assert.deepEqual(cancelled.state.wallet,before.state.wallet);assert.equal(cancelled.state.rngState,before.state.rngState);assert.deepEqual(cancelled.state.expedition.eliteContracts,before.state.expedition.eliteContracts);report.checks.push('full-roster pending purchase cancellation preserves funds, RNG and contract');
 await variant();await page.locator('[data-action=elite-contract]').click();const target=page.locator('[data-action=shop-elite-confirm]').first();await target.waitFor({timeout:240000});await page.waitForFunction(()=>!(document.querySelector('[data-action=shop-elite-confirm]') as HTMLButtonElement)?.disabled,null,{timeout:240000});const id=Number(await target.getAttribute('data-id')),expected=new World();expected.restoreRun(cancelled);const contract=expected.expedition.eliteContracts[0];assert.ok(expected.buyEliteContract(contract.id,'marine.2'));assert.ok(expected.confirmShopElite(id));await target.dblclick();assert.equal(state(await exportRun()),state(expected.captureRun()));report.checks.push('replacement double click equals exactly one original contract purchase');
 await page.locator('[data-action=ui-page][data-page=contracts]').click();await page.locator('[data-action=ui-contract]').first().click();await page.locator('[data-action=ui-elite][data-variant="marine.2"]').click();assert.equal(await page.locator('[data-action=elite-contract]').isDisabled(),true);await shot('sold-out');report.checks.push('sold contract cannot be purchased again');
 await load(true);const poor=await exportRun();await variant();assert.equal(await page.locator('[data-action=elite-contract]').isDisabled(),true);await shot('insufficient');for(let i=0;i<3;i++)await page.keyboard.press('Escape');assert.equal(state(await exportRun()),state(poor));report.checks.push('insufficient funds show a disabled confirmation without mutation');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack);process.exitCode=1;await shot('failure').catch(()=>{});}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify(report));}
