import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {createGameServer} from './coze-web-server.mjs';
import {World} from '../src/simulation/world';import {writeArchive} from '../src/persistence/archive';
import {campaignTerrain} from '../src/data/campaign-map';
const out=process.env.SC2_UI_QA_DIR??'reports/local/ui-integration-20261006/first-web';await fs.mkdir(out,{recursive:true});
const w=new World({terrain:campaignTerrain({version:3,seed:10608,theme:'industrial'}),waves:false});w.start();w.paused=true;
const fixture=path.resolve(out,'battle.json');await fs.writeFile(fixture,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun()}));
const server=createGameServer({webRoot:path.resolve('dist/web')});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const context=await browser.newContext({viewport:{width:1280,height:720}}),page=await context.newPage();page.setDefaultTimeout(20000);
const report:any={appBuildId:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')).appBuildId,at:new Date().toISOString(),errors:[],screens:[],checks:[]};page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
const shot=async(name:string)=>{await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);};
try{
 await page.goto(`http://127.0.0.1:${(server.address() as any).port}/`,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});await shot('home');
 await page.locator('[data-action=talents]').click();await page.locator('[data-action=mvp-talent-race][data-race=protoss]').click();await shot('talent-lines');
 await page.locator('[data-action=talent-line][data-line=army]').click();await shot('talent-tree');await page.locator('[data-action=mvp-talent-select]').first().click();await shot('talent-node');
 for(let i=0;i<4;i++)await page.locator('[data-action=talents-back]').last().click();assert.equal(await page.locator('.formal-home').count(),1);report.checks.push('four-level talent back');
 await page.locator('[data-action=menu-load]').click();const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await chooser).setFiles(fixture);
 await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>['ready','error'].includes(window.__SC2_REPORT__?.().readiness.phase),null,{timeout:240000});assert.equal((await page.evaluate(()=>window.__SC2_REPORT__())).readiness.phase,'ready');await page.locator('[data-action=flow-continue]').click();await page.locator('.end-screen [data-action=pause]').click();await shot('battle');
 await page.locator('#topbar [data-action=pause]').click();await page.locator('[data-action=settings]').click();await page.locator('[data-action=settings-tab][data-tab=graphics]').click();assert.equal(await page.evaluate(()=> (document.activeElement as HTMLElement)?.dataset.tab),'graphics');await page.keyboard.press('Escape');assert.equal(await page.locator('.control-settings').count(),0);await page.locator('.end-screen [data-action=pause]').click();report.checks.push('settings tab focus and one-level Escape');
 const fullHeight=(await page.locator('#battle-console').boundingBox())!.height;await page.locator('#army-toggle').click();await page.waitForFunction(()=>document.querySelector('#battle-console')!.getBoundingClientRect().height<80);await shot('commands-only');await page.locator('#commands-toggle').click();assert.ok((await page.locator('#battle-console').boundingBox())!.height<80);await shot('both-folded');await page.locator('#army-toggle').click();assert.ok((await page.locator('#battle-console').boundingBox())!.height<80);await page.locator('#commands-toggle').click();assert.ok((await page.locator('#battle-console').boundingBox())!.height>=fullHeight-2);report.checks.push('two independent rows collapse into one row and restore canvas bounds');
 await page.locator('[data-seat="marine:0"]').click();await shot('inspector');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('#unit-inspector')),true);await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>!!document.activeElement?.closest('#unit-inspector')),true);const time=await page.evaluate(()=>window.__SC2_REPORT__().time);await page.waitForFunction(t=>window.__SC2_REPORT__().time>t+.2,time);report.checks.push('inspection does not pause');
 await page.locator('[data-inspect-tab=abilities]').click();await shot('inspector-abilities');await page.keyboard.press('Escape');assert.equal(await page.locator('#unit-inspector').isVisible(),false);report.checks.push('Escape closes only inspector');
 for(const [width,height] of [[540,900],[844,390],[667,375],[390,844],[320,568]]){await page.setViewportSize({width,height});assert.equal(await page.locator('#joystick').isVisible(),false);await page.locator('[data-seat="marine:0"]').click();await shot(`inspector-${width}x${height}`);await page.locator('[data-inspect-close]').click();await shot(`battle-${width}x${height}`);}
 const seats=new Set<string>();for(let i=0;i<10;i++){for(const key of await page.locator('[data-seat]').evaluateAll(nodes=>nodes.map(n=>(n as HTMLElement).dataset.seat!)))seats.add(key);const next=page.locator('#army-pages [data-page="1"]');if(await next.isDisabled())break;await next.click();}assert.equal(seats.size,8);report.checks.push('all seats reachable at 320px; narrow desktop never shows joystick; inspector traps Tab');
 assert.deepEqual(report.errors,[]);report.passed=true;
}catch(e){report.failure=String((e as Error).stack);process.exitCode=1;await shot('failure').catch(()=>{});}
finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify(report));}
