/** Isolated checks for retained operations and target selection, using current rules. */
import {chromium} from '@playwright/test';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {PermanentProfile} from '../src/simulation/progression/permanent-profile';import {MVP_TALENTS} from '../src/data/mvp-talents';import {campaignTerrain} from '../src/data/campaign-map';import {writeArchive,readArchive} from '../src/persistence/archive';import {buySupport} from '../src/simulation/combat/shop-support';import {tacticalCard} from '../src/data/unique-support';
const out=process.env.SC2_QA_DIR??'reports/local/ui-fidelity-round-20261006/targets',url=process.env.SC2_UI_URL??'http://127.0.0.1:4192/';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true}),report:any={method:'Current-map diagnostic archives, real frozen talents and support state; public operations/target UI only. Not natural earned campaigns or physical inputs.',checks:[],screens:[],errors:[]};
try{for(const race of ['terran','zerg','protoss']as const){
 const profile=new PermanentProfile();assert.ok(profile.award('ui-targets:'+race,80,race));const levels=Object.fromEntries(MVP_TALENTS.filter(t=>t.race===race&&t.line==='micro').map(t=>[t.id,t.maxRank])),plan=profile.previewTalentAllocation(race,0,levels);assert.ok(plan);assert.ok(profile.commitTalentAllocation(plan,plan.expectedRevision));
 const w=new World({race,seed:81,waves:false,terrain:campaignTerrain({version:3,theme:'industrial',seed:81}),permanentProfile:profile});w.start();for(const line of Object.values(w.expedition.production))line.enabled={};w.time=10;w.tick=600;w.wallet={minerals:10000,gas:10000};w.expedition.tech.blink=1;
 const family=race==='terran'?'tank':race==='zerg'?'lurker':'stalker';w.expedition.tech['unlock.'+family]=1;w.expedition.familySlots.push(family);const pos=w.freePosition(family,w.anchor,2,6);assert.ok(pos);w.addFamilyMember(family,pos,2);assert.ok(buySupport(w,'strategic'));assert.ok(buySupport(w,tacticalCard(race)));w.paused=true;
 const file=path.resolve(out,race+'.json');await fs.writeFile(file,writeArchive({profile:profile.exportJSON(),run:w.captureRun()}));
 const ctx=await browser.newContext({viewport:{width:1280,height:720},acceptDownloads:true}),p=await ctx.newPage();p.on('pageerror',e=>report.errors.push(race+': '+e.message));const click=async(s:string)=>p.locator(s+':visible:not(:disabled)').last().click();const shot=async(name:string)=>{await p.screenshot({path:out+'/'+name+'.png',animations:'disabled'});report.screens.push(name);};
 await p.goto(url,{timeout:120000});await p.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu');await click('.main-actions [data-action=menu-load]');await p.locator('input[type=file][accept*=json]').setInputFiles(file);await click('[data-action=menu-load-ready]');await p.waitForFunction(()=>window.__SC2_REPORT__?.().readiness.phase==='ready',null,{timeout:240000});await click('[data-action=flow-continue]');await click('.pause-actions [data-action=pause]');
 for(const [width,height]of [[1280,720],[390,844],[844,390]]){
  await p.setViewportSize({width,height});await p.keyboard.press('o');await p.locator('.unit-operations').waitFor();assert.equal(await p.evaluate(()=>document.body.dataset.uiPhase),'pause');await shot(race+'-operations-'+width);await click('[data-action=unit-operations-close]');assert.equal(await p.evaluate(()=>document.body.dataset.uiPhase),'battle');
  await p.keyboard.press('f');await p.locator('#transfer-picker:not([hidden]) .transfer-members').waitFor();const labels=await p.locator('#transfer-picker .transfer-members').innerText();assert.ok(!/#[0-9]|marine|zergling|zealot|tank|lurker|stalker/.test(labels));assert.ok(await p.locator('#transfer-picker [data-transfer-id]').count());await shot(race+'-transfer-'+width);await click('#transfer-picker [data-transfer-cancel]');assert.ok(await p.locator('#transfer-picker').isHidden());
  await p.keyboard.press('x');await p.locator('#transfer-picker:not([hidden]) [data-transfer-confirm]').waitFor();await shot(race+'-strike-'+width);await click('#transfer-picker [data-transfer-cancel]');assert.ok(await p.locator('#transfer-picker').isHidden());
  if(race==='protoss'){await p.keyboard.press('b');await p.locator('#transfer-picker:not([hidden]) [data-transfer-confirm]').waitFor();await shot('protoss-blink-'+width);await click('#transfer-picker [data-transfer-cancel]');await p.keyboard.press('q');await p.locator('#transfer-picker:not([hidden]) [data-transfer-confirm]').waitFor();await shot('protoss-sweep-'+width);await click('#transfer-picker [data-transfer-cancel]');}
 }
 await p.keyboard.press('Escape');const pending=p.waitForEvent('download');await click('[data-action=save-export]');const saved=readArchive(await fs.readFile(await(await pending).path()!,'utf8')).bundle.run!;assert.ok(saved.state.wallet.minerals>=w.wallet.minerals&&saved.state.wallet.gas>=w.wallet.gas);assert.equal(saved.state.expedition.support.ammo,1);assert.equal(saved.state.talentTransferPlan,null);assert.equal(saved.state.expedition.support.unique.levels[tacticalCard(race)],w.expedition.support.unique.levels[tacticalCard(race)]);
 report.checks.push({race,operationsPausedAndReturned:true,targetCancellationPreservesAmmoAndNoTransferPlan:true,noWalletSpendingWithProductionDisabled:true,playerLabels:true,views:3});await ctx.close();console.log(race+' target UI passed');
}assert.deepEqual(report.errors,[]);report.passed=true;}catch(e){report.failure=String((e as Error).stack??e);process.exitCode=1;}finally{await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({passed:report.passed,checks:report.checks.length,screens:report.screens.length,errors:report.errors,failure:report.failure??null}));}
