import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {chromium,type Page} from '@playwright/test';
import {World} from '../src/simulation/world';
import {campaignTerrain,MAP_THEMES} from '../src/data/campaign-map';
import {RACES} from '../src/data/races';
import {writeArchive} from '../src/persistence/archive';
import {shopProgress} from '../src/ui/presentation/shop-progress';
import {createGameServer} from './coze-web-server.mjs';
const out=process.env.SC2_FEEDBACK_QA_DIR??'reports/local/ui-battle-feedback-20261009/browser-r1';await fs.mkdir(out,{recursive:true});
function scene(race='terran',theme='industrial'){const w=new World({race:race as never,seed:529,waves:false,terrain:campaignTerrain({version:3,seed:529,theme:theme as never})});assert.ok(w.start());for(const p of Object.values(w.expedition.production))p.enabled={};return w;}
async function fixture(name:string,w:World){const file=path.resolve(out,name+'.json');await fs.writeFile(file,writeArchive({profile:w.permanentProfile.exportJSON(),run:w.captureRun(),shopProgress:shopProgress(w).snapshot()}));return file;}
const fixtures:Record<string,string>={};
for(const race of RACES){const w=scene(race);w.wallet={minerals:100000,gas:100000};shopProgress(w).observe();w.endStage();w.skipReward();
 let id='';for(let i=0;i<600;i++){const r=w.rewards.find(r=>(r as any).expeditionEffect.kind==='teamCard'&&(!id||r.id===id));if(r){id=r.id;assert.ok(w.choose(r.offerId));shopProgress(w).observe();if(shopProgress(w).snapshot().entries.filter(r=>r.id===id).length>=2)break;}w.reroll();}
 assert.equal(shopProgress(w).snapshot().entries.filter(r=>r.id===id).length,2);fixtures[race]=await fixture(race+'-shop',w);w.allies()[0].hp=1;w.wallet={minerals:0,gas:0};fixtures[race+'-poor']=await fixture(race+'-poor',w);
}
for(const theme of Object.keys(MAP_THEMES)){const w=scene('terran',theme);w.spawnSpecial('zergling','boss',{x:8,z:1});w.spawnSpecial('roach','elite',{x:10,z:1});w.effects.push({id:w.nextId++,kind:'scan-warning',source:99,owner:'zerg',x:3,z:3,end:{x:3,z:3},radius:12,until:120});w.paused=true;fixtures[theme]=await fixture('map-'+theme,w);}
const combat=scene();combat.wallet={minerals:500,gas:500};const victim=combat.allies()[0];victim.hp=1;const other=combat.addFamilyMember('marine',{x:1,z:1},1);assert.ok(other);const enemy=combat.addUnit('zergling','zerg',victim.x+.8,victim.z,1);enemy.weaponCooldown=.6;enemy.nextShotAt=.6;
(combat as any).autoWaves=true;(combat as any).specialPlan=[{at:1.5,type:'zergling',tier:'boss',role:'boss',budget:100}];(combat as any).nextSpecial=0;fixtures.combat=await fixture('combat',combat);
const server=createGameServer({webRoot:path.resolve('dist/web'),assetRoot:path.resolve('dist/web'),backendOptions:{config:{enabled:false}}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+(server.address()as any).port;
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--disable-background-timer-throttling','--disable-renderer-backgrounding']});const context=await browser.newContext({viewport:{width:1440,height:900},hasTouch:true});const page=await context.newPage();page.setDefaultTimeout(25000);
const report:any={build:JSON.parse(await fs.readFile('dist/web/web-release.json','utf8')),method:'Production Web build, native UI actions and current diagnostic fixtures only. No old-save compatibility or natural/device/performance acceptance.',checks:[],screens:[],geometry:[],errors:[]};page.on('pageerror',e=>report.errors.push(e.message));
const sizes=[['desktop',1440,900],['portrait',390,844],['landscape',844,390],['narrow',320,640]]as const;
async function shot(name:string){if(!name.startsWith('combat-'))await page.waitForTimeout(350);await page.screenshot({path:out+'/'+name+'.png'});report.screens.push(name);}
async function resized(width:number,height:number){await page.setViewportSize({width,height});await page.waitForTimeout(300);}
async function fit(label:string,selector='.modal-window,.feedback-source-card,.config-panel,.loading-actions,.im-card'){
 const bad=await page.locator(selector).evaluateAll(ns=>ns.filter(n=>{const r=n.getBoundingClientRect();return r.width>0&&(r.left<-.6||r.right>innerWidth+.6||n.scrollWidth>n.clientWidth+3)}).map(n=>({class:n.className,text:n.textContent?.slice(0,50),bounds:n.getBoundingClientRect().toJSON(),scroll:n.scrollWidth,client:n.clientWidth,viewport:innerWidth})));
 report.geometry.push({label,bad});assert.deepEqual(bad,[],label);
}
async function menu(){await page.goto(url,{timeout:240000});await page.waitForFunction(()=>window.__SC2_REPORT__?.().phase==='menu',null,{timeout:240000});}
async function load(file:string){await menu();await page.locator('.main-actions [data-action=menu-load]').click();const pick=page.waitForEvent('filechooser');await page.locator('[data-action=menu-load-file]').click();await(await pick).setFiles(file);await page.locator('[data-action=menu-load-ready]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});await page.locator('[data-action=flow-continue]').click();await page.waitForTimeout(200);}
try{
 await menu();await page.locator('[data-action=menu-new]').click();await page.locator('[data-action=menu-race-next]').click();await page.locator('[data-action=menu-difficulty-next]').click();
 for(const [name,width,height]of sizes){await resized(width,height);await fit('deployment-'+name);await shot('deployment-'+name);}
 await resized(1440,900);await page.locator('[data-action=menu-start]').click();await page.waitForFunction(()=>window.__SC2_REPORT__?.().readiness?.phase==='ready',null,{timeout:240000});
 for(const [name,width,height]of sizes){await resized(width,height);const b=await page.locator('[data-action=flow-continue]').boundingBox();assert.ok(b);assert.ok(Math.abs(b.x+b.width/2-width/2)<2,'readiness action centered');assert.equal(await page.locator('[data-action=flow-continue]').isEnabled(),true);assert.match(await page.locator('[data-action=flow-continue]').evaluate(e=>getComputedStyle(e).boxShadow),/rgba/);await shot('ready-'+name);}
 report.checks.push('Deployment and completed readiness: four sizes, action centered and highlighted');
 for(const race of RACES){await resized(1440,900);await load(fixtures[race]);await page.locator('.imx-copy').first().waitFor();await fit(race+'-shop');await shot(race+'-shop');await page.locator('#overlay [data-action=battle-progress]').click();
  for(const [name,width,height]of sizes){await resized(width,height);await page.locator('[data-tab=summary]').click();await fit(race+'-summary-'+name);await shot(race+'-summary-'+name);await page.locator('[data-tab=sources]').click();assert.equal(await page.locator('.feedback-source-card').count(),1);assert.equal(await page.locator('.source-count').textContent(),'×2');await fit(race+'-sources-'+name);await shot(race+'-sources-'+name);}
  report.checks.push(race+': cumulative summary and grouped purchased enhancement at four sizes');
 }
 await resized(390,844);await load(fixtures['terran-poor']);await page.locator('.imx-copy').first().waitFor();await shot('poor-shop');assert.ok(await page.locator('.im-refresh .purchase-shortfall').count());await page.locator('[data-page=rest]').click();await page.locator('.imx-service-detail').click();assert.match(await page.locator('.repair-services').innerText(),/资源不足/);await shot('poor-repairs');await page.keyboard.press('Escape');await page.keyboard.press('Escape');
 await page.locator('#overlay [data-action=battle-base]').click();await fit('facilities');await shot('portrait-facilities');await page.keyboard.press('Escape');await page.locator('[data-action=battle-research]').click();await fit('research');await shot('portrait-research');await page.keyboard.press('Escape');
 await page.locator('.im-heading [data-action=settings]').click();await page.locator('[data-tab=graphics]').click();await shot('portrait-settings');await page.keyboard.press('Escape');
 report.checks.push('Peer services, settings and poor-resource shop/repair states');
 await page.evaluate(()=>{document.documentElement.style.setProperty('--text-scale','1.5');});for(const[name,width,height]of sizes){await resized(width,height);await fit('large-shop-'+name);await shot('large-shop-'+name);}await page.locator('#overlay [data-action=battle-progress]').click();for(const[name,width,height]of sizes){await resized(width,height);await fit('large-text-'+name);await shot('large-text-'+name);}await page.evaluate(()=>document.documentElement.style.setProperty('--text-scale','1'));report.checks.push('Enhancement panel at 150% font on four sizes');
 for(const theme of Object.keys(MAP_THEMES)){await resized(844,390);await load(fixtures[theme]);if(await page.locator('.pause-actions [data-action=pause]').isVisible())await page.locator('.pause-actions [data-action=pause]').click();await page.waitForTimeout(150);await shot('map-'+theme);assert.ok(await page.locator('#minimap-canvas').isVisible());assert.ok(Number(await page.locator('#minimap-canvas').getAttribute('data-threat-count'))>0);assert.ok((await page.evaluate(()=>window.__SC2_REPORT__())).errors.length===0);await page.locator('#map-toggle').click();assert.equal(await page.locator('#map-toggle').textContent(),'+');await page.locator('#map-toggle').click();assert.equal(await page.locator('#map-toggle').textContent(),'−');}report.checks.push('Five minimaps retain terrain/enemy telegraphs and collapse/expand');
 await resized(1440,900);await load(fixtures.combat);if(await page.locator('.pause-actions [data-action=pause]').isVisible())await page.locator('.pause-actions [data-action=pause]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().distress.boss,null,{timeout:15000});await shot('combat-boss');await page.waitForFunction(()=>window.__SC2_REPORT__().distress.casualty,null,{timeout:15000});await shot('combat-casualty');const state=await page.evaluate(()=>window.__SC2_REPORT__());report.battle=state.distress;assert.ok(state.distress.opacity>0);assert.equal(await page.locator('#battle-distress').evaluate(e=>getComputedStyle(e).pointerEvents),'none');assert.ok(await page.evaluate(()=>Number(getComputedStyle(document.getElementById('battle-distress')!).zIndex)<Number(getComputedStyle(document.getElementById('interface')!).zIndex)));await page.locator('#topbar [data-action=pause]').click();assert.equal(await page.locator('#battle-distress').isVisible(),false);report.checks.push('Real attacks trigger casualty edge, native scheduled Boss adds pressure, pause hides feedback');
}catch(e){report.failure=String((e as Error).stack??e);await shot('failure').catch(()=>{});process.exitCode=1;}
finally{report.final=await page.evaluate(()=>window.__SC2_REPORT__?.()).catch(()=>null);await fs.writeFile(out+'/result.json',JSON.stringify(report,null,2));await browser.close();await new Promise<void>(r=>server.close(()=>r()));console.log(JSON.stringify({checks:report.checks,screens:report.screens.length,errors:report.errors,failure:report.failure}));}
