import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const mode=process.argv[2]??'--development',out='reports/local/qa-v23';await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),mode,checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const ready=page=>page.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:240000});
const settled=page=>page.waitForFunction(()=>{const s=window.__SC2_REPORT__?.().save;return s&&!s.busy&&s.savedAt>0;},null,{timeout:30000});
const fingerprint=()=>{const w=window.__SC2_DEBUG__.world;return {time:w.time,tick:w.tick,phase:w.phase,stage:w.stage,difficulty:w.difficulty,wallet:{...w.wallet},runId:w.runId,entities:[...w.entities.values()].map(u=>({id:u.id,type:u.unitType,hp:u.hp,cd:u.weaponCooldown,next:u.nextShotAt,shot:u.shotSequence??0})),pods:w.pods.map(p=>({id:p.id,status:p.status,passengers:p.passengers,guards:[...p.guardianIds]})),heroes:[...w.heroes],rewards:w.rewards,rerolls:w.rerolls,profile:w.talentProfile.exportJSON(),threeRaceProfile:w.threeRaceTalentProfile.exportJSON(),expedition:w.expedition,statuses:w.statuses.snapshot(),map:w.terrain?.definition?.source.sha256,forts:[...w.fortifications].map(([id,f])=>[id,f.kind,f.hp]),endless:w.endless};};
function errors(page){page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});}
try{
 if(mode==='--development'){
  const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1,acceptDownloads:true}),page=await context.newPage();errors(page);
  await page.goto(process.env.SC2_QA_URL??'http://127.0.0.1:5173/');await ready(page);await page.locator('[data-action=start]').click();await page.locator('#topbar [data-action=pause]').click();
  const animation=await page.evaluate(async()=>{const {world:w,view:v}=window.__SC2_DEBUG__;await v.ensureUnitVariant('marauder','marauder');await v.ensureUnitVariant('roach','roach');const first=w.allies()[0],m=w.addUnit('marauder','terran',first.x,first.z),target=w.addUnit('roach','zerg',first.x+2,first.z);target.hp=target.maxHp=10000;target.moveSpeed=0;const model=v.gpu.get('marauder');
   const poses=[];for(let i=0;i<2;i++){w.fire(m,target);m.action='attack';v.render(0,1);poses.push({sequence:m.shotSequence,frame:model.blendAttributes[0].getX(0),weight:model.blendAttributes[0].getW(0)});if(i===0){m.action='move';v.render(0,1);poses.push({walkCleared:model.blendAttributes[0].getW(0)});}}
   const left=model.weaponAt('attackLeft',.2),right=model.weaponAt('attackRight',.2);w.changed();return {poses,leftClip:model.actions.attackLeft.name,rightClip:model.actions.attackRight.name,ready:model.actions.ready.name,tracks:[...model.weaponTracks.keys()],leftOffset:model.clips.get('Attack Left').offset,rightOffset:model.clips.get('Attack Right').offset,muzzleSeparation:left.distanceTo(right)};
  });
  report.animation=animation;assert.equal(animation.poses[0].sequence,1);assert.equal(animation.poses[0].frame,animation.rightOffset);assert.equal(animation.poses[1].walkCleared,0);assert.equal(animation.poses[2].sequence,2);assert.equal(animation.poses[2].frame,animation.leftOffset);assert.ok(animation.muzzleSeparation>.1);report.animation=animation;report.checks.push('actual GLB right/left skeletal poses, original sockets, Ready and Walk clearing');
  await page.screenshot({path:out+'/marauder-original-clips.png'});
  await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world,u=w.allies()[0];u.hp=18.75;u.weaponCooldown=.73;w.wallet={minerals:333.25,gas:88.5};w.statuses.apply(u.id,900,'bleed',.2,3,w.time);w.spawnPod('marauder',{x:w.anchor.x+6,z:w.anchor.z});w.threeRaceTalentProfile.award('qa-v23-permanent',17);w.changed();});
  await settled(page);await page.locator('[data-action=save-now]').click();await settled(page);const before=await page.evaluate(fingerprint);
  const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=save-export]').click();const download=await downloadPromise;await download.saveAs(out+'/campaign-save.json');report.exportBytes=(await fs.stat(out+'/campaign-save.json')).size;
  await page.reload();await ready(page);assert.equal(await page.locator('[data-action=save-continue]').count(),1);assert.equal(await page.evaluate(()=>document.activeElement?.dataset.action),'save-continue');await page.locator('[data-action=save-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().assetsPending===0);assert.deepEqual(await page.evaluate(fingerprint),before);assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.paused),true);report.checks.push('browser reload restores campaign HP, cooldowns, pod passengers, statuses, wallet, profile and original World state');
  await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.stage=3;w.prepareStage();w.endStage();});await settled(page);await page.locator('[data-action=save-now]').click();await settled(page);const reward=await page.evaluate(fingerprint);await page.reload();await ready(page);await page.locator('[data-action=save-continue]').click();assert.deepEqual(await page.evaluate(fingerprint),reward);report.checks.push('reward round resumes identical offers, receipts and permanent points');
  await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.stage=w.expedition?18:12;w.prepareStage();w.hive.hp=0;w.phase='won';w.startEndless();w.paused=true;w.changed();});await page.waitForFunction(()=>window.__SC2_REPORT__().map?.name==='Acropolis LE'&&window.__SC2_REPORT__().assetsPending===0,null,{timeout:240000});await settled(page);await page.locator('[data-action=save-now]').click();await settled(page);const endless=await page.evaluate(fingerprint);assert.equal(endless.forts.length,5);
  await page.reload();await ready(page);await page.locator('[data-action=save-continue]').click();await page.waitForFunction(()=>window.__SC2_REPORT__().map?.name==='Acropolis LE'&&window.__SC2_REPORT__().assetsPending===0,null,{timeout:240000});assert.deepEqual(await page.evaluate(fingerprint),endless);report.checks.push('Acropolis resume retains map, endless clocks and five fortifications');await page.screenshot({path:out+'/endless-resumed.png'});
  await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.phase='lost';w.changed();});await settled(page);await page.reload();await ready(page);assert.equal(await page.locator('[data-action=save-continue]').count(),0);report.checks.push('saved defeat cannot be continued');
  const chooserPromise=page.waitForEvent('filechooser');await page.locator('[data-action=save-import]').click();await (await chooserPromise).setFiles(out+'/campaign-save.json');await page.waitForSelector('[data-action=save-continue]');await settled(page);
  const secondChooser=page.waitForEvent('filechooser');await page.locator('[data-action=save-import]').click();await (await secondChooser).setFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{broken')});await page.waitForFunction(()=>window.__SC2_REPORT__().save.message.includes('JSON')||window.__SC2_REPORT__().save.message.includes('Unexpected')||window.__SC2_REPORT__().save.message.includes('Expected'));assert.equal(await page.locator('[data-action=save-continue]').count(),1);report.checks.push('portable import restores the selected archive; corrupt import leaves it intact');
  await page.setViewportSize({width:390,height:844});await page.locator('[data-action=save-continue]').scrollIntoViewIfNeeded();const layout=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,button:document.querySelector('[data-action=save-continue]').getBoundingClientRect().toJSON()}));assert.ok(layout.scrollWidth<=layout.width);assert.ok(layout.button.width<=layout.width);report.mobileLayout=layout;await page.screenshot({path:out+'/save-menu-narrow.png'});report.checks.push('narrow menu fits width and Continue is keyboard focusable');
  await context.close();
 }else{
  report.offline=[];
  for(const race of ['terran','zerg','protoss']){
   const context=await browser.newContext({viewport:{width:1440,height:900},offline:true}),page=await context.newPage(),requests=[];errors(page);page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
   await page.goto(pathToFileURL(process.cwd()+'/dist/SC2-Survivors-Demo.html').href,{timeout:180000});await ready(page);assert.equal(await page.evaluate(()=>typeof window.__SC2_DEBUG__),'undefined');await page.getByLabel('开局种族').selectOption(race);await page.waitForFunction(()=>!window.__SC2_REPORT__().assetsPending,null,{timeout:240000});
   await page.locator('[data-action=start]').click();await page.locator('#topbar [data-action=pause]').click();await settled(page);
   const fingerprint=()=>{const r=window.__SC2_REPORT__();return {time:r.time,stage:r.stage,stats:r.stats,expedition:r.expedition,wallet:r.wallet};};
   const before=await page.evaluate(fingerprint);assert.equal(before.expedition.race,race);assert.equal(before.expedition.rules,'three-race-18-v1');
   await page.locator('[data-action=save-now]').click();await settled(page);await page.reload({timeout:180000});await ready(page);await page.locator('[data-action=save-continue]').click();await page.waitForFunction(()=>!window.__SC2_REPORT__().assetsPending,null,{timeout:240000});assert.deepEqual(await page.evaluate(fingerprint),before);assert.deepEqual(requests,[]);
   report.offline.push({race,requests,before,save:await page.evaluate(()=>window.__SC2_REPORT__().save)});await page.screenshot({path:out+`/offline-${race}-resumed.png`});report.checks.push(`${race}: offline file:// HTML saves and resumes race, families, frozen talents, wallet and battle time without HTTP requests or mutation debug API`);await context.close();
  }
 }
 assert.deepEqual(report.errors,[]);
}catch(e){report.failure=String(e.stack??e);console.error(report.failure);process.exitCode=1;}finally{await fs.writeFile(out+'/'+(mode==='--development'?'development':'offline')+'.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
