import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {createHash} from 'node:crypto';
const out=process.env.SC2_QA_OUT??'reports/local/qa-v16';await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),method:'Local Chrome desktop and viewport fixtures; original images remain local. DOM, rendering errors, positions and asset byte hashes checked; not human visual approval or a human campaign playthrough.',errors:[],checks:[],viewports:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const track=p=>{p.on('pageerror',e=>report.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});};
try{
 const p=await browser.newPage({viewport:{width:1440,height:900}});track(p);await p.goto('http://127.0.0.1:5173/');await p.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:240000});await p.locator('[data-action=start]').click();
 await p.evaluate(async()=>{const {world:w,view:v}=window.__SC2_DEBUG__;w.paused=true;w.autoWaves=false;w.eventPlan=[];w.buildings.clear();w.entities.clear();w.economicTargets.clear();w.pods=[];w.rewardDrops=[];
  const u=w.addUnit('marine','terran',-3,1);w.acquireElite('marine.1');w.replaceWithElite('marine.1',u.id);await v.ensureUnitVariant(u.modelKey,'marine');
  for(const [i,id] of ['raynor','tychus','nova'].entries()){w.acquireHero(id);await v.ensureUnitVariant('hero.'+id,'marine');const h=w.heroEntity(id);h.x=-1+i*2;h.z=1;h.prev={x:h.x,z:h.z};}w.heroEntity('raynor').hp=120;
  w.anchor={x:0,z:0,facing:0};w.updateUnit=()=>{};w.paused=false;w.changed();
 });
 await p.waitForTimeout(500);
 for(const [width,height] of [[1440,900],[390,844],[844,390]]){
  await p.setViewportSize({width,height});await p.waitForTimeout(300);
  const result=await p.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {heroes:[...document.querySelectorAll('.hero-world-label:not([hidden])')].map(e=>({id:e.dataset.hero,text:e.textContent,rect:rect(e),ratio:e.querySelector('i').style.width,hp:e.querySelector('[role=meter]').getAttribute('aria-valuenow')})),elite:[...document.querySelectorAll('.elite-world-label:not([hidden])')].map(e=>e.textContent),hud:[...document.querySelectorAll('.hero-status')].map(e=>({id:e.dataset.hero,text:e.textContent,opacity:getComputedStyle(e.querySelector('button')).opacity,rect:rect(e)})),skills:rect(document.querySelector('#skills')),scrollWidth:document.documentElement.scrollWidth,selection:String(getSelection()),errors:window.__SC2_REPORT__().errors};});
  assert.equal(result.heroes.length,3);assert.match(result.elite.join(' '),/突击枪兵/);const raynor=result.heroes.find(h=>h.id==='raynor');assert.equal(raynor.hp,'120');assert.equal(raynor.ratio,'24%');assert.match(result.hud.find(h=>h.id==='raynor').text,/120 \/ 500/);
  for(const h of result.hud){assert.equal(h.opacity,'1');assert.ok(h.rect.x>=0&&h.rect.x+h.rect.w<=width);assert.ok(h.rect.y+h.rect.h<=result.skills.y,'hero health must not cover tactical skills');}
  for(let i=0;i<result.heroes.length;i++)for(let j=i+1;j<result.heroes.length;j++){const a=result.heroes[i].rect,b=result.heroes[j].rect;assert.ok(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'hero labels overlap');}
  assert.ok(result.scrollWidth<=width);assert.deepEqual(result.errors,[]);await p.screenshot({path:`${out}/identity-${width}x${height}.png`});report.viewports.push({width,height,...result});
 }
 report.checks.push('all three heroes: on-field names, non-overlapping HP bars, constant HUD HP at full/no-target/wounded states; elite name visible at three sizes');
 await p.setViewportSize({width:1440,height:900});await p.evaluate(async()=>{const w=window.__SC2_DEBUG__.world,{rewardPool}=await import('/src/simulation/progression/rewards.ts');w.wallet={minerals:10000,gas:10000};w.endStage();w.skipReward();w.rewards=['elite.marine.1','elite.marine.2','hero.raynor'].map((id,i)=>({...rewardPool(w).find(r=>r.id===id),offerId:'qa-'+i}));w.changed();});
 assert.match(await p.locator('[data-ownership=elite][data-unit="marine.1"]').innerText(),/已拥有 · Rank 1 → 2/);assert.match(await p.locator('[data-ownership=elite][data-unit="marine.2"]').innerText(),/未拥有/);await p.locator('[data-action=reward][data-id=qa-0]').click();assert.match(await p.locator('[data-ownership=elite][data-unit="marine.1"]').innerText(),/Rank 2 → 3/);await p.screenshot({path:out+'/elite-owned-offers.png'});report.checks.push('purple cards identify owned and unowned variants; buying same card refreshes rank immediately');
 await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.hit(w.heroEntity('raynor'),999999);w.changed();});assert.match(await p.locator('.hero-status[data-hero=raynor]').innerText(),/阵亡/);assert.equal(await p.locator('.hero-status[data-hero=raynor] [role=meter]').getAttribute('aria-valuenow'),'0');assert.equal(await p.locator('.hero-world-label[data-hero=raynor]:not([hidden])').count(),0);report.checks.push('dead hero HP becomes zero, field name is removed, HUD and revival remain');
 await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.stage=12;w.prepareStage();w.autoWaves=false;w.eventPlan=[];w.phase='battle';w.hive.hp=0;w.endStage();});assert.equal(await p.locator('[data-action=endless]').count(),1);
 const before=await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {wallet:{...w.wallet},units:w.allies().map(u=>[u.id,u.hp]),hive:w.hive.id,map:window.__SC2_REPORT__().map};});await p.locator('[data-action=endless]').click();
 const after=await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {phase:w.phase,round:w.endless.round,stage:w.stage,units:w.allies().map(u=>[u.id,u.hp]),hive:w.hive.id,map:window.__SC2_REPORT__().map};});assert.equal(after.phase,'battle');assert.equal(after.stage,12);assert.equal(after.round,1);assert.deepEqual(after.units,before.units);assert.equal(after.hive,before.hive);assert.deepEqual(after.map,before.map);
 await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.paused=true;w.tick+=6000;w.time=w.tick/60;w.stageElapsed=100;w.autoWaves=true;w.endless.progress={wave:1,elite:1,boss:1};w.paused=false;w.step();w.autoWaves=false;w.changed();});await p.waitForTimeout(200);
 const spawned=await p.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {state:window.__SC2_REPORT__().endless,elites:[...w.entities.values()].filter(u=>u.endlessLevel).map(u=>({tier:u.enemyTier,level:u.endlessLevel,hp:u.maxHp,damage:u.weaponDamage,period:u.attackPeriod})),hud:document.querySelector('#stage').textContent};});assert.equal(spawned.elites.length,2);assert.match(spawned.hud,/ENDLESS/);await p.screenshot({path:out+'/endless.png'});
 await p.evaluate(()=>window.__SC2_DEBUG__.world.endStage());await p.locator('[data-action=skip]').click();await p.locator('[data-action=skip]').click();assert.equal(await p.evaluate(()=>window.__SC2_DEBUG__.world.endless.round),2);report.endless={before,after,spawned};report.checks.push('campaign victory enters endless on same map and squad; reinforced elite/Boss plus wave spawn; two-round intermission continues at round 2');await p.close();
 const context=await browser.newContext({offline:true,viewport:{width:1440,height:900}}),file=await context.newPage();track(file);const requests=[];file.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});const start=performance.now();await file.goto(pathToFileURL(process.cwd()+'/dist/SC2-Survivors-Demo.html').href,{timeout:180000});await file.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:240000});report.offline={readySeconds:(performance.now()-start)/1000,requests,runtime:await file.evaluate(()=>window.__SC2_REPORT__()),debug:await file.evaluate(()=>typeof window.__SC2_DEBUG__)};
 const records=JSON.parse(await fs.readFile('reports/local/runtime-assets.json','utf8')).filter(r=>r.status==='available'),expected=[];for(const r of records){const bytes=await fs.readFile(r.packedFile);expected.push({id:r.id,sha:createHash('sha256').update(bytes).digest('hex')});}
 report.offline.bytes=await file.evaluate(async expected=>{for(const {id,sha} of expected){const url=window.__SC2_EMBEDDED__[id];if(!url?.startsWith('blob:'))throw Error('Asset not local Blob: '+id);const bytes=await (await fetch(url)).arrayBuffer(),digest=await crypto.subtle.digest('SHA-256',bytes),actual=[...new Uint8Array(digest)].map(n=>n.toString(16).padStart(2,'0')).join('');if(actual!==sha)throw Error('Source bytes differ: '+id);}return {verified:expected.length,sha256Equal:true};},expected);
 assert.deepEqual(requests,[]);assert.equal(report.offline.debug,'undefined');assert.deepEqual(report.offline.runtime.errors,[]);assert.equal(report.offline.bytes.verified,647);await file.locator('[data-action=start]').click();await file.mouse.click(920,430,{button:'right'});await file.waitForTimeout(700);assert.equal(await file.evaluate(()=>window.__SC2_REPORT__().phase),'battle');await file.screenshot({path:out+'/offline.png'});await context.close();report.checks.push('offline file:// start/move, zero network requests, all 647 restored asset SHA256 hashes equal their source files');assert.deepEqual(report.errors,[]);
}catch(error){report.failure=String(error.stack??error);console.error(report.failure);process.exitCode=1;}finally{await fs.writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}console.log(JSON.stringify({checks:report.checks,errors:report.errors,offline:report.offline&&{readySeconds:report.offline.readySeconds,bytes:report.offline.bytes},failure:report.failure}));
