import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const out='reports/local/qa-v24';await fs.mkdir(out,{recursive:true});
const report={at:new Date().toISOString(),checks:[],errors:[]};
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1}),page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text());});
 await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:240000});
 await page.locator('[data-action=start]').click();
 const acquired=await page.evaluate(()=>{const {world:w}=window.__SC2_DEBUG__;w.paused=true;const hero=w.acquireHero('nova'),elite=w.acquireElite('marine.1');return {hero,elite};});assert.deepEqual(acquired,{hero:true,elite:true});
 await page.waitForFunction(()=>{const v=window.__SC2_DEBUG__.view;return v.assetsPending===0&&v.gpu.has('hero.nova')&&v.gpu.has('elite.marine.1');},null,{timeout:240000});
 const identity=await page.evaluate(()=>{const {world:w,view:v}=window.__SC2_DEBUG__,hero=v.gpu.get('hero.nova'),elite=v.gpu.get('elite.marine.1');v.render(0,1);const labels=[...document.querySelectorAll('.friendly-unit-label')].map(el=>({type:el.className,text:el.textContent,shadow:getComputedStyle(el).boxShadow,hidden:el.hidden}));return {novaMeshes:hero.meshes.length,novaAttack:hero.actions.attack.name,novaMuzzle:hero.weaponAt('attack',.1).toArray(),heroTier:hero.tierAttributes[0].getX(0),eliteTier:elite.tierAttributes[0].getX(0),labels,errors:v.modelErrors};});
 assert.equal(identity.novaMeshes,3);assert.equal(identity.novaAttack,'Attack A');assert.equal(identity.heroTier,3);assert.equal(identity.eliteTier,4);assert.ok(identity.labels.some(x=>x.type.includes('hero-world-label')&&x.shadow!=='none'));assert.ok(identity.labels.some(x=>x.type.includes('elite-world-label')&&x.shadow!=='none'));assert.deepEqual(identity.errors,[]);report.identity=identity;
 await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.paused=false;w.changed();});await page.waitForFunction(()=>[...document.querySelectorAll('.friendly-unit-label.hero-world-label,.friendly-unit-label.elite-world-label')].filter(el=>!el.hidden&&el.textContent?.trim()).length>=2);report.identity.visibleLabels=await page.evaluate(()=>[...document.querySelectorAll('.friendly-unit-label.hero-world-label,.friendly-unit-label.elite-world-label')].filter(el=>!el.hidden).map(el=>({type:el.className,text:el.textContent})));report.checks.push('Nova uses corrected rifle assembly and nearby muzzle; hero/elite use separate glow tiers and visible labels');await page.screenshot({path:out+'/special-units-desktop.png'});await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.paused=true;w.stage=3;w.prepareStage();w.endStage();w.unlockMarauder();const f=w.addBuilding('factory');w.upgradeFactory(f.id);w.addBuilding('starport');w.changed();});
 await page.locator('.production-choice').waitFor();const before=await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;return {phase:w.phase,round:w.rewardRound,groups:[...document.querySelectorAll('.production-choice-group')].map(el=>({label:el.querySelector('b')?.textContent,selected:el.querySelectorAll('.production-option[aria-pressed="true"]').length,options:el.querySelectorAll('.production-option').length})),width:document.documentElement.scrollWidth,viewport:innerWidth};});assert.equal(before.phase,'reward');assert.equal(before.round,'building');assert.deepEqual(before.groups.map(g=>g.selected),[2,2,1]);assert.ok(before.groups.every(g=>g.selected<=2));assert.ok(before.width<=before.viewport);report.building=before;report.checks.push('building choice displays Barracks 2, Factory 2 and Starport 1 without a third alternating type');
 await page.screenshot({path:out+'/building-choice-desktop.png'});await page.locator('[data-action=production-toggle][data-group=barracks][data-id=marauder]').click();assert.equal(await page.locator('[data-action=production-toggle][data-group=barracks][data-id=marauder]').getAttribute('aria-pressed'),'false');assert.equal(await page.evaluate(()=>document.activeElement?.dataset.id),'marauder');
 await page.waitForFunction(()=>{const r=window.__SC2_REPORT__().save;return r&&!r.busy&&r.savedAt>0;},null,{timeout:30000});await page.locator('[data-action=save-now]').click();await page.waitForFunction(()=>!window.__SC2_REPORT__().save.busy);await page.reload();await page.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,null,{timeout:240000});await page.locator('[data-action=save-continue]').click();assert.deepEqual(await page.evaluate(()=>window.__SC2_DEBUG__.world.productionChoices.barracks),['marine']);report.checks.push('production toggle keeps keyboard focus and survives browser reload');
 await page.setViewportSize({width:390,height:844});await page.locator('.production-choice').waitFor();const narrow=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,groupWidths:[...document.querySelectorAll('.production-choice-group')].map(el=>el.getBoundingClientRect().width),panelWidth:document.querySelector('.production-choice').getBoundingClientRect().width}));assert.ok(narrow.scrollWidth<=narrow.width);assert.ok(narrow.groupWidths.every(x=>x<=narrow.width));report.narrow=narrow;await page.screenshot({path:out+'/building-choice-narrow.png'});report.checks.push('390x844 building production panel fits the viewport without horizontal overflow');
 assert.deepEqual(report.errors,[]);await context.close();
}catch(e){report.failure=String(e.stack??e);process.exitCode=1;}finally{await fs.writeFile(out+'/development.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report));}
