import fs from 'node:fs/promises';import assert from 'node:assert/strict';
import {World} from '../src/simulation/world';import {HEROES,type HeroId} from '../src/data/heroes';import {ZERG_HERO_IDS} from '../src/data/zerg-heroes';import {ELITES} from '../src/data/elites';import {familyRace} from '../src/data/races';
import {resolveExpeditionHeroCasts} from '../src/simulation/combat/expedition-heroes';import {tickZergHero} from '../src/simulation/combat/zerg-hero-passives';
const setup=(id:HeroId,rank:number)=>{const w=new World({race:'zerg',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10506});w.start();w.entities.clear();w.heroes.clear();w.pods=[];w.hive=null;w.expansionHives.clear();w.economicTargets.clear();for(const p of Object.values(w.expedition.production))p.enabled={};assert.ok(w.acquireHero(id));const u=w.heroEntity(id)!;u.rank=rank;w.heroes.get(id)!.rank=rank;u.x=u.z=0;u.prev={x:0,z:0};return {w,u,record:w.heroes.get(id)!};};
const rows=[];for(const id of ZERG_HERO_IDS)for(let rank=1;rank<=5;rank++){const {w,u,record}=setup(id,rank);w.heroes.clear();w.refreshStats(u,true);const initialHp=u.maxHp,initialShield=u.maxShield??0,target=w.addUnit('roach','zerg',HEROES[id].range<3?1.45:3,0);target.enemyTier='boss';target.hp=target.maxHp=1e9;target.armor=0;target.stoppedUntil=1e9;target.specialReady=1e9;target.moveSpeed=0;w.hash.rebuild(w.entities.values());for(let tick=0;tick<3600;tick++){if(id!=='niadra'&&w.time>=record.skillReady){w.heroes.set(id,record);w.castHero(id);w.heroes.clear();}w.step();}rows.push({id,rank,dps:w.stats.damage/60,damage:w.stats.damage,shots:w.stats.shots,hp:initialHp,shield:initialShield,finalHp:u.maxHp,weapon:u.weaponDamage,period:u.attackPeriod,aurasExcluded:true});}
const comparators={kerrigan:6510.3907,zagara:4480.9412,dehaka:6510.3907,stukov:1839.924,hots_leviathan:2999.43};
const comparisons=Object.entries(comparators).map(([id,upper])=>{const a=rows.find(r=>r.id===id&&r.rank===1)!,b=rows.find(r=>r.id===id&&r.rank===5)!;return {id,approvedVEliteUpper:upper,heroI:a.dps,heroV:b.dps,ratioI:a.dps/upper,ratioV:b.dps/upper};});
const spec=JSON.parse(await fs.readFile('docs/project/NEXT_ITERATION_P0_VALUES_20261003.json','utf8')).eliteHeroRedesign;
const durability=spec.heroes.filter((h:any)=>ZERG_HERO_IDS.includes(h.id)).map((h:any)=>{const candidates=h.peerIds.map((id:keyof typeof ELITES)=>{const elite=spec.elites.find((x:any)=>x.id===id),family=ELITES[id].family,w=new World({race:familyRace(family),sandbox:true,waves:false,terrain:false,obstacles:[]});w.start();w.entities.clear();const unit=w.addUnit(family,'terran',0,0,5);if(family==='lurker')unit.nativeMode='lurker_burrowed';w.refreshStats(unit,true);const p=spec.bodyPresets[elite.body];return {id,hp:(unit.maxHp*p.hp+(unit.maxShield??0)*p.shield)*spec.eliteGrowth.hp[4]*(1+(elite.parameters.allyHpIncrease??elite.parameters.familyAttributeIncrease??0))};}).sort((a:any,b:any)=>b.hp-a.hp);const base=rows.find(r=>r.id===h.id&&r.rank===1)!;return {id:h.id,heroI:base.hp+base.shield,eliteV:candidates[0],ratioI:(base.hp+base.shield)/candidates[0].hp};});
const heals=[];for(const rank of [1,3,5]){const {w,u}=setup('niadra',rank);w.heroes.clear();w.refreshStats(u,true);for(let i=0;i<7;i++){const a=w.addUnit('roach','terran',2+i*.2,0);a.hp=a.maxHp=1e7;a.hp-=1e6;}w.time=1;tickZergHero(w,u,1);heals.push({rank,actualPerSecond:w.stats.healed,targets:u.healTargets?.length,approvedVEliteUpper:2880,ratio:w.stats.healed/2880,aurasExcluded:true});}
const bosses=[];for(const id of ['kerrigan','zagara','dehaka','stukov','hots_leviathan'] as const)for(const rank of [1,5]){const {w,u}=setup(id,rank);w.difficulty='easy';w.stage=rank===1?12:18;let target;if(rank===5){w.endless={round:3,startedAt:0,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=w.spawnSpecial('queen','boss',{x:12,z:0})!;w.entities.delete(first.id);target=w.spawnSpecial('lurker','boss',{x:id==='dehaka'?1.5:5,z:0})!;w.castDetection();}else target=w.spawnSpecial('ravager','boss',{x:id==='dehaka'?1.5:5,z:0})!;const hp=target.hp;w.hash.rebuild(w.entities.values());assert.ok(w.castHero(id));w.heroes.clear();for(let tick=0;tick<360;tick++){w.time+=1/60;resolveExpeditionHeroCasts(w);}const dealt=hp-target.hp;bosses.push({id,rank,hp:Math.round(hp),armor:target.armor,damage:dealt,fraction:dealt/hp,remaining:target.hp,shots:w.stats.shots,aurasExcluded:true});}
const report={method:'Actual 60s production World.step, 60Hz; one high-HP zero-armor Boss-class diagnostic target; aura registries empty; no talents/cards. Separate actual public Boss factory, original HP/armor, skill-only cast and resolver. Approved future elite proposal read in QA only.',rows,comparisons,durability,heals,bosses};await fs.mkdir('reports/local/zerg-heroes-20261005',{recursive:true});await fs.writeFile('reports/local/zerg-heroes-20261005/strength.json',JSON.stringify(report,null,2));console.log(JSON.stringify({comparisons,durability,heals,bosses},null,2));assert.ok(comparisons.every(r=>r.ratioI>=1.25));assert.ok(durability.every((r:any)=>r.ratioI>=1.25));assert.ok(heals[0].ratio>=1.25&&heals.every(x=>x.targets===7));assert.ok(bosses.every(b=>b.id==='dehaka'?b.remaining===0:b.fraction>=.5));
