import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const out='reports/local/qa-v4';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:process.env.SC2_CHROME??'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const report={date:new Date().toISOString(),screenshots:'Local disk only; no upload or human visual approval.',desktop:{},mobile:[],offline:{},errors:[]};
const assertOpening=async page=>{const s=await page.evaluate(()=>({report:window.__SC2_REPORT__(),counts:[...document.querySelectorAll('#roster .unit-status')].map(el=>el.querySelectorAll('.soldier:not(.empty)').length)}));assert.equal(s.report.phase,'menu');assert.deepEqual(s.counts,[1,0,0,0]);assert.equal(s.report.economicModels,3);assert.ok(s.report.podModel);};
const newPage=async(size={width:1440,height:900},mobile=false)=>{const ctx=await browser.newContext({viewport:size,isMobile:mobile,hasTouch:mobile,deviceScaleFactor:mobile?3:1});const page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404'))report.errors.push(m.text());});await page.goto('http://127.0.0.1:5173/');await page.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,{timeout:60000});await assertOpening(page);await page.getByRole('button',{name:/部署小队/}).click();return {ctx,page};};
try{
 if(process.env.SC2_QA_SKIP_DESKTOP==='1'){report.desktop=JSON.parse(await fs.readFile(out+'/REPORT.json','utf8')).desktop;report.desktop.reusedEvidence=true;}
 else{
 const {ctx,page}=await newPage();await page.evaluate(async()=>{const {PlayPolicy}=await import('/tools/play-policy.ts');window.__QA_POLICY__=new PlayPolicy();});
 const held=new Set();let lastShot=0;
 while(true){const state=await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;if(w.phase==='battle')window.__QA_POLICY__.update(w);return {phase:w.phase,time:w.time,input:{...w.input}};});if(state.phase!=='battle')break;
  const wanted=new Set();if(state.input.x>.28)wanted.add('ArrowRight');if(state.input.x<-.28)wanted.add('ArrowLeft');if(state.input.z>.28)wanted.add('ArrowDown');if(state.input.z<-.28)wanted.add('ArrowUp');
  for(const key of held)if(!wanted.has(key)){await page.keyboard.up(key);held.delete(key);}for(const key of wanted)if(!held.has(key)){await page.keyboard.down(key);held.add(key);}
  if(state.time>lastShot+35){lastShot=state.time;await page.screenshot({path:out+'/desktop-battle-'+Math.floor(state.time)+'.png'});console.log('Desktop first stage',state.time.toFixed(1));}await page.waitForTimeout(150);
 }
 for(const key of held)await page.keyboard.up(key);const first=await page.evaluate(()=>window.__SC2_REPORT__());report.desktop.firstStage={...first,input:'Actual keyboard events at normal speed; no health/resources/clock overrides. Automation chooses directions.'};assert.equal(first.phase,'reward');assert.equal(first.time,120);assert.ok(first.stats.rescued>0);await page.screenshot({path:out+'/desktop-reward.png'});
 const before=await page.evaluate(()=>({m:window.__SC2_DEBUG__.world.wallet.minerals,ids:window.__SC2_DEBUG__.world.rewards.map(r=>r.id).sort()}));await page.locator('[data-action=reroll]').click();const after=await page.evaluate(()=>({m:window.__SC2_DEBUG__.world.wallet.minerals,ids:window.__SC2_DEBUG__.world.rewards.map(r=>r.id).sort()}));assert.equal(before.m-after.m,50);assert.notDeepEqual(before.ids,after.ids);report.desktop.reroll=true;
 const can=page.locator('[data-action=reward]:not(:disabled)');if(await can.count()){report.desktop.purchase={label:await can.first().innerText(),before:await page.evaluate(()=>({...window.__SC2_DEBUG__.world.wallet}))};await can.first().click();report.desktop.purchase.after=await page.evaluate(()=>({...window.__SC2_DEBUG__.world.wallet}));}else {await page.locator('[data-action=skip]').click();report.desktop.skipped=true;}assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.stage),2);report.desktop.reward=true;
 // Separate bounded presentation/edge-case fixtures. Never recorded as a balance victory.
 report.desktop.fixtures=await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.paused=true;const pod=w.spawnPod('marine',{x:w.anchor.x+3,z:w.anchor.z});w.landPod(pod);w.hit(pod,pod.hp+pod.armor);w.updatePods();const failed=pod.status;
  const egg=w.spawnEconomic('egg',{x:w.anchor.x+2,z:w.anchor.z+2}),scvs=w.scvs;w.hit(egg,100);const once=w.scvs===scvs+1;w.hit(egg,100);const twice=w.scvs===scvs+1;
  const late=w.spawnEconomic('egg',{x:w.anchor.x-3,z:w.anchor.z});late.expiresAt=w.time;w.updateEconomy(0);w.changed();return {podFailure:failed,scvRescue:egg.status,scvOnce:once&&twice,scvExpiry:late.status};});assert.equal(report.desktop.fixtures.podFailure,'destroyed');assert.equal(report.desktop.fixtures.scvExpiry,'expired');assert.ok(report.desktop.fixtures.scvOnce);
 await page.keyboard.press('Escape');await page.waitForTimeout(700);await page.screenshot({path:out+'/desktop-rescue-fixtures.png'});
 report.desktop.icons=await page.evaluate(async()=>{const {ASSETS,assetUrl}=await import('/src/assets/manifest.ts');const result=[];for(const a of ASSETS.values()){if(a.kind!=='icon')continue;const ok=await new Promise(resolve=>{const im=new Image();im.onload=()=>resolve(im.naturalWidth>0);im.onerror=()=>resolve(false);im.src=assetUrl(a.id);});result.push({id:a.id,ok});}return result;});assert.equal(report.desktop.icons.filter(x=>x.ok).length,23);await ctx.close();
 }
 for(const viewport of [{width:390,height:844},{width:844,height:390}]){
  const {ctx,page}=await newPage(viewport,true),cdp=await ctx.newCDPSession(page);
  const stick=await page.locator('#joystick').boundingBox(),dash=await page.locator('#dash').boundingBox();const x=stick.x+stick.width/2,y=stick.y+stick.height/2;
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+45,y,id:1}]});await page.waitForTimeout(100);
  const moved=await page.evaluate(()=>window.__SC2_DEBUG__.world.input.x);assert.ok(moved>.5);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x+45,y,id:1},{x:dash.x+dash.width/2,y:dash.y+dash.height/2,id:2}]});
  await page.waitForTimeout(100);const multi=await page.evaluate(()=>({input:window.__SC2_DEBUG__.world.input.x,dash:window.__SC2_DEBUG__.world.dashReady,time:window.__SC2_DEBUG__.world.time}));assert.ok(multi.input>.5&&multi.dash>multi.time);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:viewport.width-15,y:viewport.height/2,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.waitForTimeout(120);assert.equal(await page.evaluate(()=>window.__SC2_DEBUG__.world.input.x),0);
  await page.screenshot({path:out+`/mobile-${viewport.width}x${viewport.height}-battle.png`});
  const layout=await page.evaluate(()=>({selection:String(getSelection()),scroll:[scrollX,scrollY],width:document.documentElement.scrollWidth,viewport:innerWidth,joystickStyle:getComputedStyle(document.querySelector('#joystick')).touchAction,canvasStyle:getComputedStyle(document.querySelector('canvas')).userSelect}));assert.equal(layout.selection,'');assert.deepEqual(layout.scroll,[0,0]);assert.ok(layout.width<=layout.viewport);assert.equal(layout.joystickStyle,'none');
  await page.evaluate(()=>window.__SC2_DEBUG__.world.endStage());await page.locator('[data-action="reroll"]').click();await page.screenshot({path:out+`/mobile-${viewport.width}x${viewport.height}-reward.png`});
  const rewardLayout=await page.locator('#overlay').evaluate(el=>({client:el.clientHeight,scroll:el.scrollHeight,touchAction:getComputedStyle(el).touchAction}));assert.equal(rewardLayout.touchAction,'pan-y');if(rewardLayout.scroll>rewardLayout.client){await page.locator('#overlay').evaluate(el=>el.scrollTop=100);assert.ok(await page.locator('#overlay').evaluate(el=>el.scrollTop)>0);}
  if(await page.locator('[data-action="reward"]:not(:disabled)').count())await page.locator('[data-action="reward"]:not(:disabled)').first().click();else await page.locator('[data-action=skip]').click();
  // Stress load bypasses the normal roster cap only through development API; no production rule change.
  await page.evaluate(()=>{const w=window.__SC2_DEBUG__.world;w.entities.clear();w.input={x:0,z:0};w.anchor.x=0;w.anchor.z=0;const types=['marine','hellion','tank','medivac'];for(let i=0;i<25;i++){const u=w.addUnit(types[i%4],'terran',(i%5-2)*1.8,Math.floor(i/5)*1.7);u.hp=u.maxHp=100000;}
   for(let i=0;i<300;i++){const a=i/300*Math.PI*2,r=10+i%8;const u=w.addUnit(['zergling','roach','baneling','ravager'][i%4],'zerg',Math.cos(a)*r,Math.sin(a)*r);u.hp=u.maxHp=100000;u.weaponDamage=0;u.bileCooldown=1000;}w.phase='battle';w.paused=false;});
  // Maintain the advertised load despite Baneling self-destruction and tank mode stat refreshes.
  await page.evaluate(()=>{let serial=0;const keepLoad=()=>{const w=window.__SC2_DEBUG__.world;for(const u of w.allies())u.hp=u.maxHp=100000;
   while(w.allies().length<25){const n=serial++,u=w.addUnit(['marine','hellion','tank','medivac'][n%4],'terran',(n%5-2)*1.8,3);u.hp=u.maxHp=100000;}
   while(w.enemyCount()<300){const n=serial++,a=n*2.399,u=w.addUnit(['zergling','roach','baneling','ravager'][n%4],'zerg',Math.cos(a)*14,Math.sin(a)*14);u.hp=u.maxHp=100000;u.weaponDamage=0;u.bileCooldown=1000;}};
   window.__SC2_STRESS_KEEP__=keepLoad;window.__SC2_STRESS_TIMER__=setInterval(keepLoad,200);keepLoad();});
  await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await page.evaluate(()=>{const d=window.__SC2_DEBUG__,step=d.world.step.bind(d.world),render=d.view.render.bind(d.view);window.__CPU_TIMES__={step:0,steps:0,render:0,frames:0};d.world.step=()=>{const t=performance.now();step();window.__CPU_TIMES__.step+=performance.now()-t;window.__CPU_TIMES__.steps++;};d.view.render=(...a)=>{const t=performance.now();render(...a);window.__CPU_TIMES__.render+=performance.now()-t;window.__CPU_TIMES__.frames++;};});await page.waitForTimeout(6000);await page.evaluate(()=>{window.__SC2_DEBUG__.view.frameTimes.length=0;});await page.waitForTimeout(10000);
  const perf=await page.evaluate(()=>{window.__SC2_STRESS_KEEP__();clearInterval(window.__SC2_STRESS_TIMER__);const d=window.__SC2_DEBUG__,a=d.view.frameTimes.slice().sort((a,b)=>a-b),gl=d.view.renderer.getContext(),extension=gl.getExtension('WEBGL_debug_renderer_info');return {...d.view.report(),cpu:window.__CPU_TIMES__,deviceDpr:devicePixelRatio,renderDpr:d.view.renderer.getPixelRatio(),gpu:extension?gl.getParameter(extension.UNMASKED_RENDERER_WEBGL):'unavailable',sampleFrames:a.length,averageFps:1000/(a.reduce((n,f)=>n+f,0)/a.length),p50FrameMs:a[Math.floor(a.length*.5)],p95FrameMs:a[Math.floor(a.length*.95)],friendly:d.world.allies().length,enemies:d.world.enemyCount()};});await page.screenshot({path:out+`/mobile-${viewport.width}x${viewport.height}-stress.png`});report.mobile.push({viewport,multiTouch:true,releaseOutside:true,layout,rewardLayout,performance:{...perf,environment:'Desktop Chrome with mobile viewport/touch emulation, device DPR 3 / render DPR capped at 1.5, and 4x CPU throttle; six-second warmup followed by ten-second load, final 240 frames; diagnostic respawns maintain 25 friendly / 300 enemy actors; not a physical phone.'}});console.log('Mobile QA',viewport,JSON.stringify(perf));await ctx.close();
 }
 const offline=await browser.newContext({viewport:{width:1440,height:900}});await offline.setOffline(true);const pageOffline=await offline.newPage(),network=[];pageOffline.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await pageOffline.goto(pathToFileURL(process.cwd()+'/dist/SC2-Survivors-Demo.html').href);await pageOffline.waitForFunction(()=>window.__SC2_REPORT__?.().assetsReady,{timeout:60000});await assertOpening(pageOffline);await pageOffline.getByRole('button',{name:/部署小队/}).click();await pageOffline.keyboard.press('F1');await pageOffline.waitForTimeout(1000);report.offline={...await pageOffline.evaluate(()=>window.__SC2_REPORT__()),requests:network,debugExposed:await pageOffline.evaluate(()=>typeof window.__SC2_DEBUG__!=='undefined')};assert.equal(network.length,0);assert.equal(report.offline.debugExposed,false);assert.equal(report.offline.models,8);await pageOffline.screenshot({path:out+'/offline-final.png'});await offline.close();
 assert.equal(report.errors.length,0);console.log('QA complete.');
}catch(error){report.failure=String(error.stack??error);console.error(report.failure);process.exitCode=1;}finally{await fs.writeFile(out+'/REPORT.json',JSON.stringify(report,null,2));await browser.close();}
