import {EventCollector} from './events';
import * as THREE from 'three';
import {captureBattleView} from '../../src/render/input/battle-view';
import {World} from '../../src/simulation/world';
import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {ASSETS,configurePlatformAssetUrl} from '../../src/assets/manifest';
import {checksum,encodeGraph} from '../../src/persistence/graph-codec';
import {groups,modeGroups,densityGroups,actorGroups,enemyGroups,themes,type Group} from './catalog';
import {scenario,prepareTargets,prepareCastTargets,activateMode,resolveActors,destroyActors,type Scenario} from './scenario';
import {CandidateView} from './view';
const allGroups=[...groups,...modeGroups,...densityGroups,...actorGroups,...enemyGroups],el=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T,groupSelect=el<HTMLSelectElement>('group'),themeSelect=el<HTMLSelectElement>('theme'),modeSelect=el<HTMLSelectElement>('mode');
groupSelect.innerHTML=allGroups.map(g=>'<option value="'+g.id+'">'+g.name+' · '+g.id+'</option>').join('');themeSelect.innerHTML=themes.map(t=>'<option>'+t+'</option>').join('');
const query=new URLSearchParams(location.search);groupSelect.value=query.get('group')??'marine';themeSelect.value=query.get('theme')??'industrial';modeSelect.value=query.get('mode')??'baseline';
configurePlatformAssetUrl(id=>{const a=ASSETS.get(id);return a?.status==='available'?'/'+a.url.replace(/^\//,''):null;});
const collector=new EventCollector();const errors:string[]=[],checks:any[]=[],measurements:any[]=[],history=collector.history;let baseline:any,s:Scenario,r!:BattleRenderer,view!:CandidateView,busy=true,continuous=false,last=performance.now(),debt=0,discarded=0,prepared=false,action='initial',initial:any,initialProfile='',seq=0,lastFrame=0,measure:any=null;
let assetRequests=0;const canvas=el<HTMLCanvasElement>('battle'),labels=el('identities'),state=()=>checksum(JSON.stringify(encodeGraph({run:s.world.captureRun(),profile:s.world.permanentProfile.exportJSON()})));
canvas.addEventListener('webglcontextlost',()=>errors.push('WebGL context lost'));addEventListener('error',e=>errors.push(String(e.message)));addEventListener('unhandledrejection',e=>errors.push(String(e.reason)));
function status(text:string){el('status').textContent=text;}
function setBusy(value:boolean){busy=value;document.body.dataset.ready=String(!value);for(const n of document.querySelectorAll<HTMLButtonElement|HTMLSelectElement>('button,select'))n.disabled=value;}
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null,percentile=(a:number[],p:number)=>a.length?[...a].sort((x,y)=>x-y)[Math.min(a.length-1,Math.floor(a.length*p))]:null;
function subjectReport(){return s.subjects.map(x=>{const u=s.world.entities.get(x.entity.id)??x.entity,key=(r as any).modelKey(u),b=r.gpu.get(key),pose=(r as any).animationStates.get(u.id);return {identity:x.identity,id:u.id,hp:u.hp,rank:u.rank,modelKey:key,loaded:r.gpu.has(key),deathModel:r.gpu.has((u.modelKey??u.unitType)+'.death')?(u.modelKey??u.unitType)+'.death':r.gpu.has(u.unitType+'.death')?u.unitType+'.death':null,action:u.action,presentation:pose?.sampled,position:{x:u.x,z:u.z},moved:Math.hypot(u.x-x.initial.x,u.z-x.initial.z),flying:u.flying,mode:u.nativeMode??u.mode,shots:u.shotSequence??0,energy:u.energy,healTarget:u.healTarget,healTargets:u.healTargets??[],healRate:u.healRate,barrier:u.barrier??0,bodyHeight:b?.bodyHeight,events:[...(collector.kinds.get(u.id)??[])]};});}
function report(){if(!r||!s)return;const native=r.report(),gl=r.renderer.getContext(),ext=gl.getExtension('WEBGL_debug_renderer_info');const q={baseline,revision:'plan-validation-v12',sequence:seq,group:s.group.id,theme:s.theme,action,ready:!busy,continuous,time:s.world.time,tick:s.world.tick,phase:s.world.phase,paused:s.world.paused,state:state(),resolution:native.resolution,hardware:{renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),userAgent:navigator.userAgent},view:view.report(),subjects:subjectReport(),children:[...s.world.entities.values()].filter(u=>u.summonKind||u.temporaryKind).map(u=>({id:u.id,type:u.unitType,kind:u.summonKind??u.temporaryKind,model:u.modelKey,owner:u.summonOwnerId,hp:u.hp})),events:history.slice(-240),checks,measurements,lab:{identityLabels:!labels.hidden,contextLost:gl.isContextLost(),visibility:document.visibilityState,focused:document.hasFocus(),eventCollector:'monotonic serial cursor and per-entity kind index; bounded 10000 history',recordedSerial:collector.lastSerial,retainedEvents:history.length},terrain:{definition:s.world.terrain!.definition!.source.sha256,rootVisible:r.scene.getObjectByName(s.world.terrain!.definition!.source.sha256)?.visible??false,map:native.map},fixture:{density:s.group.density??null,actors:!!s.group.actors,enemyType:s.group.enemyType??null,economic:[...s.world.economicTargets.values()],pods:s.world.pods,forts:[...s.world.fortifications.values()],hive:s.world.hive,pickups:s.world.pickups},runtime:native,nativeStats:s.world.stats,assetRequests,fixtureGuard:[...s.world.entities.values()].filter(u=>u.stoppedUntil===1e9&&u.owner==='terran'&&u.maxHp===2e6).map(u=>({id:u.id,type:u.unitType,x:u.x,z:u.z})),errors:[...errors,...native.errors],timing:{debt,discarded},method:'All identities individually inventoried. Native World diagnostic fixtures and actions. Prototype render switches preserve World. Synthetic targets; not natural campaign or physical-device acceptance.'};el('report').textContent=JSON.stringify(q,null,2);el('summary').textContent=s.group.id+' · '+s.theme+' · '+action+' · '+s.world.time.toFixed(2)+'s · '+q.errors.length+' errors';}
function remember(){collector.record(s.world.visualEvents);}
function updateLabels(){if(labels.hidden)return;for(const n of labels.children){const id=Number((n as HTMLElement).dataset.id),u=s.world.entities.get(id);if(!u||u.hp<=0){(n as HTMLElement).style.display='none';continue;}const point=new THREE.Vector3(u.x,s.world.terrain!.height(u)-.3,u.z+1.2).project(r.camera);(n as HTMLElement).style.left=(point.x*.5+.5)*100+'%';(n as HTMLElement).style.top=(.5-point.y*.5)*100+'%';}}
function rebuildLabels(){el<HTMLSelectElement>('focus').innerHTML='<option value="">整组战场视距</option>'+s.subjects.map(x=>'<option value="'+x.entity.id+'">近景 · '+x.identity.id+'</option>').join('');view.focusId=null;labels.innerHTML=s.subjects.map(x=>'<span class="identity-label" data-id="'+x.entity.id+'"><b>'+x.identity.name+'</b> '+x.identity.id+'</span>').join('');}
async function assets(){r.prepareRosterAssets();for(const u of s.world.entities.values())if(u.hp>0&&!r.gpu.has(u.modelKey??u.unitType)){assetRequests++;await r.ensureUnitVariant(u.modelKey??u.unitType,u.unitType);}await r.prepareCurrentAssets();await r.waitForPendingAssets();}
async function load(warmFrames=8){
 setBusy(true);continuous=false;status('载入 '+groupSelect.value);const group=allGroups.find(g=>g.id===groupSelect.value)!;const next=scenario(group,themeSelect.value as typeof themes[number]);
 if(!r){s=next;r=new BattleRenderer(canvas,s.world);await r.load(label=>status(label),group.race);view=new CandidateView(r);}
 else{const world=s.world;world.permanentProfile.importJSON(next.world.permanentProfile.exportJSON());world.restoreRun(next.world.captureRun());s={...next,world,subjects:next.subjects.map(x=>({...x,entity:world.entities.get(x.entity.id)!}))};r.resetRun();await r.prepareCampaignAssets(world.captureRun().config.campaignMap!);}
 await assets();if(group.actors)await r.prepareEndlessAssets();initial=structuredClone(s.world.captureRun());initialProfile=s.world.permanentProfile.exportJSON();prepared=false;collector.reset();checks.length=0;seq++;action='idle';debt=0;
 r.setQuality(el<HTMLSelectElement>('render-quality').value as never);r.fx.heroQuality=el<HTMLSelectElement>('effect-quality').value as never;r.renderer.setPixelRatio(Number(el<HTMLSelectElement>('render-ratio').value));r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);view.height=group.density?30:20;view.set(modeSelect.value,s.theme);rebuildLabels();
 for(let i=0;i<warmFrames;i++){r.render(1/60,1);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}if(!r.scene.getObjectByName(s.world.terrain!.definition!.source.sha256)?.visible)throw Error('Diagnostic terrain root is not visible');setBusy(false);status('就绪 · '+s.group.id);report();
}
async function ticks(count:number){const w=s.world,startTick=w.tick;w.paused=false;for(let i=0;i<count&&w.phase==='battle';i++){w.step();remember();r.prepareRosterAssets();r.render(1/60,1);if(r.assetsPending)await r.waitForPendingAssets();if(i%6===5)await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}w.paused=true;checks.push({kind:'ticks',requested:count,actual:w.tick-startTick,phase:w.phase});if(w.tick-startTick!==count)throw Error('Tick advancement incomplete '+(w.tick-startTick)+'/'+count+' phase '+w.phase);await assets();r.render(0,1);}
async function run(name:string,fn:()=>Promise<void>|void){if(busy)return;setBusy(true);continuous=false;action=name;status('执行 '+name);try{await fn();seq++;checks.push({kind:name,time:s.world.time,errors:r.report().errors.length});}catch(e){errors.push(String(e));status('失败 '+String(e));}setBusy(false);report();}
async function prepare(){if(prepared)return;prepareTargets(s);prepared=true;await assets();}
function reset(){s.world.permanentProfile.importJSON(initialProfile);s.world.restoreRun(initial);s.subjects=s.subjects.map(x=>({...x,entity:s.world.entities.get(x.entity.id)!}));r.resetRun();r.prepareRosterAssets();prepared=false;collector.reset();rebuildLabels();r.render(0,1);checks.push({kind:'reset-exact',sameRun:checksum(JSON.stringify(encodeGraph(s.world.captureRun())))===checksum(JSON.stringify(encodeGraph(initial)))});}
el('load').onclick=()=>void load().catch(e=>{errors.push(String(e));setBusy(false);status('载入失败');report();});
el('reset').onclick=()=>void run('reset',reset);
el('next').onclick=()=>{groupSelect.selectedIndex=(groupSelect.selectedIndex+1)%allGroups.length;void load();};
el('idle').onclick=()=>void run('held-idle-1s',async()=>{for(const x of s.subjects){x.entity.action='idle';x.entity.stoppedUntil=s.world.time+1.01;}checks.push({kind:'diagnostic-held-idle',method:'Fixture holds positions via native stoppedUntil; original idle animation and World clock advance.'});await ticks(60);for(const x of s.subjects)x.entity.stoppedUntil=0;});
el('move').onclick=()=>void run('move-1s',async()=>{s.world.paused=false;checks.push({kind:'move-order',accepted:s.world.issueMove({x:0,z:4})});await ticks(60);});
el('prepare').onclick=()=>void run('prepare-targets',prepare);
el('combat').onclick=()=>void run('combat-1s',async()=>{await prepare();s.world.cancelOrder();await ticks(60);});
el('cast').onclick=()=>void run('cast-mode',async()=>{await prepare();prepareCastTargets(s);await assets();s.world.paused=false;const mode=activateMode(s);if(mode)checks.push({kind:'native-mode',...mode});for(const x of s.subjects)if(x.identity.hero)checks.push({kind:'native-cast',id:x.identity.id,accepted:s.world.castHero(x.identity.hero,captureBattleView(canvas,r.camera))});await ticks(12);});
el('actors').onclick=()=>void run('actors-resolve',async()=>{resolveActors(s);remember();await ticks(12);});
el('actors-death').onclick=()=>void run('actors-destroy',async()=>{destroyActors(s);remember();await ticks(12);});
el('hit').onclick=()=>void run('native-hit',async()=>{for(const x of s.subjects)if(x.entity.hp>0)s.world.hit(x.entity,Math.max(1,x.entity.maxHp*.15),[],1,'zerg');remember();await ticks(12);});
el('death').onclick=()=>void run('death-0.2s',async()=>{for(const x of s.subjects){const u=s.world.entities.get(x.entity.id);if(u&&u.hp>0)s.world.hit(u,1e8,[],1,'zerg',0,1,undefined,true);}remember();await ticks(12);});
for(const [id,n] of [['step12',12],['step60',60],['step300',300]] as const)el(id).onclick=()=>void run('step-'+n,()=>ticks(n));
modeSelect.onchange=()=>void run('view-switch',()=>{const before=state();view.set(modeSelect.value,s.theme);r.render(0,1);checks.push({kind:'view-world-unchanged',mode:modeSelect.value,unchanged:state()===before});});
el<HTMLSelectElement>('focus').onchange=()=>{const before=state(),value=el<HTMLSelectElement>('focus').value;view.focusId=value?Number(value):null;r.render(0,1);checks.push({kind:'camera-focus',unchanged:state()===before,id:view.focusId});report();};
el('clean').onclick=()=>{document.body.classList.toggle('clean');r.resize();r.renderer.setPixelRatio(Number(el<HTMLSelectElement>("render-ratio").value));r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);report();};
el('label-toggle').onclick=()=>void run('label-toggle',()=>{const before=state();labels.hidden=!labels.hidden;checks.push({kind:'labels-world-unchanged',unchanged:state()===before});});el('back').onclick=()=>el('clean').click();for(const id of ['render-quality','render-ratio','effect-quality'])el<HTMLSelectElement>(id).onchange=()=>void run('graphics-tier',()=>{const before=state();r.setQuality(el<HTMLSelectElement>('render-quality').value as never);r.fx.heroQuality=el<HTMLSelectElement>('effect-quality').value as never;r.renderer.setPixelRatio(Number(el<HTMLSelectElement>('render-ratio').value));r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);r.render(0,1);checks.push({kind:'graphics-tier-world-unchanged',unchanged:state()===before,quality:r.quality,ratio:r.renderer.getPixelRatio(),effects:r.fx.heroQuality});});el('play').onclick=()=>{if(busy)return;continuous=!continuous;s.world.paused=!continuous;last=performance.now();el('play').textContent=continuous?'暂停运行':'连续运行';report();};
el('bench').onclick=()=>{if(busy||continuous)return;setBusy(true);measure={start:performance.now(),previous:0,frames:[],submit:[],draws:[],triangles:[],gpu:[],state:state(),mode:view.mode,group:s.group.id,theme:s.theme,live:false};status('测量 10 秒');};
el('bench-live').onclick=()=>{if(busy)return;setBusy(true);continuous=true;s.world.paused=false;last=performance.now();measure={start:last,previous:0,frames:[],submit:[],draws:[],triangles:[],gpu:[],state:state(),mode:view.mode,group:s.group.id,theme:s.theme,live:true,startTick:s.world.tick};status('测量真实连续运行 10 秒');};
let suiteActive=false,suiteResolve:((v:any)=>void)|null=null;const suiteRecords:any[]=[];const suiteCaseSeconds=5;
let timer:any,gl:WebGL2RenderingContext,pending:{query:WebGLQuery;id:number}[]=[];
function frame(now:number){
 const elapsed=(now-last)/1000;last=now;let simulationMs=0,collectorMs=0;if(r&&view&&s&&(!busy||measure)){
  if(continuous&&(!busy||measure?.live)){const accepted=Math.min(.25,elapsed);discarded+=Math.max(0,elapsed-accepted);debt+=accepted;let n=0;const simBegan=performance.now();while(debt>=1/60&&n++<15){s.world.step();const collectBegan=performance.now();remember();collectorMs+=performance.now()-collectBegan;debt-=1/60;}simulationMs=performance.now()-simBegan-collectorMs;if(s.world.phase!=='battle'){continuous=false;s.world.paused=true;report();}}
  if(timer)for(let i=pending.length-1;i>=0;i--){const p=pending[i];if(gl.getQueryParameter(p.query,gl.QUERY_RESULT_AVAILABLE)){if(!gl.getParameter(timer.GPU_DISJOINT_EXT)&&measure?.start===p.id)measure.gpu.push(gl.getQueryParameter(p.query,gl.QUERY_RESULT)/1e6);gl.deleteQuery(p.query);pending.splice(i,1);}}
  const q=measure&&timer&&pending.length<8?gl.createQuery():null;if(q)gl.beginQuery(timer.TIME_ELAPSED_EXT,q);
  r.renderer.info.reset();const start=performance.now();r.render(Math.min(.1,elapsed),1);const submit=performance.now()-start;if(q){gl.endQuery(timer.TIME_ELAPSED_EXT);pending.push({query:q,id:measure.start});}updateLabels();
  if(measure){(measure.simulation??=[]).push(simulationMs);(measure.collection??=[]).push(collectorMs);(measure.visibility??=new Set<string>()).add(document.visibilityState);if(measure.previous)measure.frames.push(now-measure.previous);measure.previous=now;measure.submit.push(submit);measure.draws.push(r.renderer.info.render.calls);measure.triangles.push(r.renderer.info.render.triangles);if(now-measure.start>=(measure.secondsTarget??10)*1000){measurements.push({...measure,start:undefined,previous:undefined,seconds:(now-measure.start)/1000,frameMeanMs:mean(measure.frames),p95:percentile(measure.frames,.95),p99:percentile(measure.frames,.99),maxMs:Math.max(...measure.frames),over20:measure.frames.filter((x:number)=>x>20).length/measure.frames.length,submitMeanMs:mean(measure.submit),simulationMeanMs:mean(measure.simulation??[]),collectorMeanMs:mean(measure.collection??[]),reportMeanMs:mean(measure.reports??[]),visibility:[...measure.visibility??[]],gpuMeanMs:mean(measure.gpu),drawMean:mean(measure.draws),trianglesMean:mean(measure.triangles),endTick:s.world.tick,actualTicks:measure.live?s.world.tick-measure.startTick:null,unchanged:state()===measure.state});measure=null;continuous=false;s.world.paused=true;setBusy(false);status('测量完成');report();if(suiteResolve){const done=suiteResolve;suiteResolve=null;done(measurements.at(-1));}}}
  if(continuous&&now-lastFrame>1000){lastFrame=now;const began=performance.now();report();if(measure)(measure.reports??=[]).push(performance.now()-began);}
 }requestAnimationFrame(frame);
}

async function graphicsSuite(allMaps:boolean,visualOnly=false){
 if(busy||suiteActive)return;suiteActive=true;suiteRecords.length=0;continuous=false;
 const cases=[...['baseline','lighting','shadow','contact','surface','atmosphere','composition','combined','fxaa','msaa4'].map(mode=>({mode,quality:'native',ratio:1,effects:'full'})),{mode:'baseline',quality:'performance',ratio:.75,effects:'low'},{mode:'baseline',quality:'balanced',ratio:1,effects:'balanced'},{mode:'combined',quality:'native',ratio:1.5,effects:'full'},{mode:'baseline',quality:'native',ratio:1,effects:'full'}];
 try{
  for(const theme of allMaps?themes:[themeSelect.value]){
   themeSelect.value=theme;modeSelect.value='baseline';el<HTMLSelectElement>('render-quality').value='native';el<HTMLSelectElement>('render-ratio').value='1';el<HTMLSelectElement>('effect-quality').value='full';
   await load();labels.hidden=true;setBusy(true);action='suite-native-prepare';await prepare();prepareCastTargets(s);await assets();s.world.paused=false;
   for(const x of s.subjects)if(x.identity.hero)checks.push({kind:'suite-native-cast',id:x.identity.id,accepted:s.world.castHero(x.identity.hero,captureBattleView(canvas,r.camera))});
   await ticks(72);const frozen=state();
   for(const c of cases){
    setBusy(true);modeSelect.value=c.mode;view.set(c.mode,s.theme);el<HTMLSelectElement>('render-quality').value=c.quality;el<HTMLSelectElement>('render-ratio').value=String(c.ratio);el<HTMLSelectElement>('effect-quality').value=c.effects;r.setQuality(c.quality as never);r.fx.heroQuality=c.effects as never;r.renderer.setPixelRatio(c.ratio);r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);
    for(let i=0;i<(visualOnly?1:12);i++){r.render(0,1);await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));}
    if(state()!==frozen)throw Error('Suite view changed World');action='suite-'+c.mode;status('图形批次 '+s.theme+' · '+c.mode+' · '+(suiteRecords.length+1));report();
    const started=performance.now();const metrics=visualOnly?{visualOnly:true,unchanged:state()===frozen}:await new Promise<any>(resolve=>{suiteResolve=resolve;measure={start:started,previous:0,frames:[],submit:[],draws:[],triangles:[],gpu:[],state:frozen,mode:c.mode,group:s.group.id,theme:s.theme,live:false,secondsTarget:suiteCaseSeconds,quality:c.quality,ratio:c.ratio,effects:c.effects};});
    r.renderer.info.reset();r.render(0,1);const image=canvas.toDataURL('image/png');suiteRecords.push({name:s.group.id+'-'+s.theme+'-'+c.mode+'-'+c.quality+'-'+c.ratio+'-'+c.effects+'-'+suiteRecords.length,metrics,source:baseline,revision:'plan-validation-v12',hardware:(JSON.parse(el('report').textContent!)).hardware,resolution:r.report().resolution,worldSame:state()===frozen,contextLost:r.renderer.getContext().isContextLost(),subjects:subjectReport(),view:view.report(),runtime:r.report(),nativeStats:{...s.world.stats},image});
   }
  }
  el('suite-report').textContent=JSON.stringify({method:visualOnly?'Visual-only frozen World comparison after one warm frame; no timing or performance conclusion. Actual canvas PNG at completion.':'5-second paused graphics trials after 12 warm frames; actual canvas PNG at completion; separate from natural performance.',records:suiteRecords},null,2);status('图形批次完成 · '+suiteRecords.length+' 条');action='suite-complete';
 }catch(e){errors.push(String(e));status('图形批次失败 · '+String(e));}
 finally{suiteActive=false;suiteResolve=null;setBusy(false);report();}
}

async function rosterSuite(){
 if(busy||suiteActive)return;suiteActive=true;suiteRecords.length=0;continuous=false;document.body.classList.add('clean');
 try{for(const group of groups){
  groupSelect.value=group.id;modeSelect.value='baseline';el<HTMLSelectElement>('render-quality').value='native';el<HTMLSelectElement>('render-ratio').value='1';el<HTMLSelectElement>('effect-quality').value='full';await load(1);labels.hidden=true;setBusy(true);const frozen=state();
  for(const mode of ['baseline','composition']){view.set(mode,s.theme);r.resize();r.renderer.setPixelRatio(1);r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);r.renderer.info.reset();r.render(0,1);if(state()!==frozen)throw Error('Roster view changed World');report();const image=canvas.toDataURL('image/png');suiteRecords.push({name:'roster-'+s.group.id+'-'+s.theme+'-'+mode,metrics:{visualOnly:true,unchanged:true},source:baseline,revision:'plan-validation-v12',resolution:r.report().resolution,worldSame:true,contextLost:r.renderer.getContext().isContextLost(),subjects:subjectReport(),view:view.report(),runtime:r.report(),image});}
  status('全身份画面 '+s.group.id+' · '+suiteRecords.length);
 }
 el('suite-report').textContent=JSON.stringify({method:'All 138 identities in 36 groups, baseline and composition; scene-only responsive screenshots at current viewport, no timing. Warm frame then immediate native render before capture. World unchanged.',records:suiteRecords});action='roster-suite-complete';status('全身份画面完成 · '+suiteRecords.length);
 }catch(e){errors.push(String(e));status('全身份画面失败 · '+String(e));}
 finally{suiteActive=false;document.body.classList.remove('clean');r.resize();setBusy(false);report();}
}
el('roster-suite').onclick=()=>void rosterSuite();

el('capture-frame').onclick=()=>{const before=state();r.renderer.info.reset();r.render(0,1);el('capture-report').textContent=JSON.stringify({report:JSON.parse(el('report').textContent!),worldSame:state()===before,image:canvas.toDataURL('image/png')});};
el('suite-visual').onclick=()=>void graphicsSuite(true,true);el('suite-visual-one').onclick=()=>void graphicsSuite(false,true);el('suite').onclick=()=>void graphicsSuite(true);el('suite-one').onclick=()=>void graphicsSuite(false);

try{baseline=await(await fetch('./baseline.json')).json();await load();gl=r.renderer.getContext() as WebGL2RenderingContext;timer=gl.getExtension('EXT_disjoint_timer_query_webgl2');r.renderer.info.autoReset=false;last=performance.now();requestAnimationFrame(frame);}
catch(e){errors.push(String(e));setBusy(false);status('启动失败 '+String(e));el('report').textContent=JSON.stringify({errors});console.error(e);}
addEventListener('resize',()=>{if(r){r.renderer.setPixelRatio(Number(el<HTMLSelectElement>("render-ratio").value));r.renderer.setSize(canvas.clientWidth,canvas.clientHeight,false);report();}});
