import type {World} from '../world';
import type {Entity,Body,Point} from '../types';
import {SC2_UNITS,FASTER,HEAL,SIEGE,type UnitType,type CombatUnitType,type UnitData} from '../../data/sc2-units';
import {SOURCE_UNIT_DETAILS,SOURCE_UNIT_MODES,SOURCE_ABILITIES} from '../../data/expansion-units';
import {aggregateMvpTalentEffects,type MvpTalentEffects} from '../progression/mvp-talent-effects';
import {familyRace,type FamilyId} from '../../data/races';
import {distance,blocked} from '../movement/steering';
import {HEROES} from '../../data/heroes';
import {TUNING} from '../../data/game';
import {CAMPAIGN_SCIENCE_VESSEL} from '../../data/campaign-science-vessel';
import {isInterceptor,interceptorUnitData} from './carriers';
import {eliteEffect} from './expedition-elites';
import {SOURCE_PRIMARY_DAMAGE_EFFECT,SOURCE_WEAPON_UPGRADE_STEPS,SOURCE_RESEARCH_EFFECTS,sourceWeaponUpgradeDelta} from '../../data/expansion-upgrades';
export function sourceDetails(type:CombatUnitType){const s=SOURCE_UNIT_DETAILS[type as FamilyId];if(s)return s;if(type==='hots_leviathan')return {shields:0,shieldArmor:0,shieldRegen:0,shieldDelay:0,energy:250,energyStart:250,energyRegen:1.5/FASTER,creep:1,lifeRegen:2,lifeDelay:0};const c=CAMPAIGN_SCIENCE_VESSEL;return {shields:c.maxShields,shieldArmor:c.shieldArmor,shieldRegen:c.shieldRegenPerSecond/FASTER,shieldDelay:c.shieldRegenDelay*FASTER,energy:c.maxEnergy,energyStart:c.startEnergy,energyRegen:c.energyRegenPerSecond/FASTER,creep:c.creepSpeedMultiplier,lifeRegen:c.hpRegenPerSecond/FASTER,lifeDelay:c.hpRegenDelay*FASTER};}
import {SOURCE_WEAPONS,sourceWeaponsForUnit,SOURCE_UNIT_WEAPON_IDS,type VerifiedAddedUnitType} from '../../data/expansion-units';

const NO_TALENT_EFFECTS:Readonly<MvpTalentEffects>=Object.freeze({});
export function talentModifiers(w:World,u:Entity,ability?:string):MvpTalentEffects{
 const config=w.runConfig;
 if(!config||!w.expedition||u.team!=='player'||u.race!==config.race||u.temporary||u.summonKind)return NO_TALENT_EFFECTS;
 const levels=config.frozenTalents.levels;
 if(!u.tacticalTier&&Object.keys(levels).length===0)return NO_TALENT_EFFECTS;
 return aggregateMvpTalentEffects(levels,config.race,{team:u.team,race:u.race,kind:u.heroId?'hero':u.eliteId?'elite':'ordinary',familyId:u.unitType,attributes:u.attributes,mode:u.unitType==='tank'?u.mode:u.nativeMode,freeConscript:u.freeConscript,tacticalTier:u.tacticalTier,tacticalDirection:u.tacticalDirection,ability,manualAbility:ability==='blink'||ability==='hero'});
}
export function unitData(u:Entity):UnitData {if(isInterceptor(u))return interceptorUnitData();if(u.heroId){const h=HEROES[u.heroId];return {...SC2_UNITS[u.unitType],attackDamage:h.damage,attacks:h.attacks,attackPeriod:h.period,attackRange:h.range,targetType:h.target,bonusDamage:[],splash:[],attributes:[...h.attributes],flying:!!h.flying};}if(u.unitType==='tank'&&u.mode==='siege')return {...SC2_UNITS.tank,attackDamage:SIEGE.damage,attacks:1,attackPeriod:SIEGE.period,attackRange:SIEGE.range,bonusDamage:SIEGE.bonus.map(b=>({...b})),splash:SIEGE.splash.map(b=>({...b}))};const key=u.nativeMode as keyof typeof SOURCE_UNIT_MODES,m=key&&SOURCE_UNIT_MODES[key];if(!m){const d=SC2_UNITS[u.unitType],weapon=u.activeWeapon?SOURCE_WEAPONS[u.activeWeapon]:null;return weapon?{...d,...weapon}:d;}const weapon=u.activeWeapon?SOURCE_WEAPONS[u.activeWeapon]??m.weapon:m.weapon;return {...SC2_UNITS[u.unitType],...m,attributes:[...m.attributes],...(weapon?{attackDamage:weapon.attackDamage,attacks:weapon.attacks,attackPeriod:weapon.attackPeriod,attackRange:weapon.attackRange,targetType:weapon.targetType,damagePoint:weapon.damagePoint,bonusDamage:weapon.bonusDamage.map(b=>({...b})),splash:(weapon.splash as readonly {radius:number;fraction:number}[]).map(b=>({...b}))}:{attackDamage:0,targetType:'none'})};}
/** Only the active source effect determines its additive weapon upgrade track. */
export function expeditionWeaponEffect(u:Entity){if(u.heroId||isInterceptor(u))return null;if(u.unitType==='tank'&&u.mode==='siege')return 'CrucioShockCannonBlast';if(u.unitType==='lurker'&&u.nativeMode!=='lurker_burrowed')return null;const mode=SOURCE_UNIT_MODES[u.nativeMode as keyof typeof SOURCE_UNIT_MODES];return (u.activeWeapon?SOURCE_WEAPONS[u.activeWeapon]?.effectId:null)??mode?.weapon.effectId??SOURCE_PRIMARY_DAMAGE_EFFECT[u.unitType as UnitType];}
export function expeditionWeaponUpgrade(w:World,u:Entity,effect:string|null=expeditionWeaponEffect(u)){const key=effect?SOURCE_WEAPON_UPGRADE_STEPS[effect]?.upgradeKey:undefined;return sourceWeaponUpgradeDelta(effect,u.owner==='terran'&&key?w.expedition!.tech[key]??0:0);}
export function expeditionWeaponScale(w:World,u:Entity){if(u.owner==='terran')return w.growth(u).damage*(1+(talentModifiers(w,u).weaponDamagePct??0))*(1+(w.expedition!.cardTotals['weapon.'+u.unitType]??0));const base=unitData(u).attackDamage;return base>0?u.weaponDamage/base:u.nativeStatScale?.damage??1;}
/** Bonus and shield-only damage use the same rank/talent/card scale exactly once. */
export function expeditionWeaponBonuses(w:World,u:Entity){
 const d=unitData(u),delta=expeditionWeaponUpgrade(w,u),factor=expeditionWeaponScale(w,u),values=new Map(d.bonusDamage.map(b=>[b.attribute,b.amount]));
 for(const [attribute,amount] of Object.entries(delta.bonusDamage))values.set(attribute,(values.get(attribute)??0)+amount);
 if(!u.heroId&&u.owner==='terran'&&u.unitType==='hellion'&&w.expedition!.tech.infernal)values.set('Light',(values.get('Light')??0)+(u.nativeMode==='hellbat'?SOURCE_RESEARCH_EFFECTS.infernal.hellbatLightBonus:SOURCE_RESEARCH_EFFECTS.infernal.hellionLightBonus));
 const effect=expeditionWeaponEffect(u),source=effect?Object.values(SOURCE_WEAPONS).find(weapon=>weapon.effectId===effect):undefined;
 const bonusFactor=1+(talentModifiers(w,u).bonusDamagePct??0);
 return {bonuses:[...values].map(([attribute,amount])=>({attribute,amount:amount*factor*bonusFactor*eliteEffect(u,attribute==='Light'?'lightBonusMultiplier':attribute==='Armored'?'armoredBonusMultiplier':'none')})),shieldBonus:((source?.shieldBonus??0)+delta.shieldBonus)*factor};
}
function preserveEnemyScale(u:Entity){if(u.owner!=='zerg')return;const d=unitData(u),previous=u.nativeStatScale;u.nativeStatScale={hp:u.maxHp/d.maxHp,damage:d.attackDamage>0?u.weaponDamage/d.attackDamage:previous?.damage??1,period:u.attackPeriod/d.attackPeriod,move:d.movementSpeed>0?u.moveSpeed/d.movementSpeed:previous?.move??1,armor:u.armor-d.armor};}
/** Rebuild the base range from source, talent, research and elite modifiers; never from the previous frame. */
export function expeditionAttackRange(w:World,u:Entity,d=unitData(u),t=talentModifiers(w,u)){
 const tech=u.owner==='terran'?w.expedition!.tech:{};
 return d.attackRange*(1+(t.rangePct??0))+(u.unitType==='hydralisk'&&tech.hydra_range?SOURCE_RESEARCH_EFFECTS.hydra_range.rangeAdd:0)+(u.unitType==='colossus'&&tech.colossus_range?SOURCE_RESEARCH_EFFECTS.colossus_range.rangeAdd:0)+eliteEffect(u,'attackRangeAdd',0)+(!u.flying||u.unitType==='banshee'?eliteEffect(u,'groundAttackRangeAdd',0):0)+(u.unitType==='viking'&&u.nativeMode==='viking_assault'?eliteEffect(u,'assaultGroundRangeAdd',0):0)+(u.unitType==='lurker'&&u.nativeMode==='lurker_burrowed'?eliteEffect(u,'burrowedRangeAdd',0):0);
}
export function refreshExpeditionStats(w:World,u:Entity,fill=false){const d=unitData(u),source=sourceDetails(u.unitType),r=w.growth(u),t=talentModifiers(w,u),s=w.expedition!,friendly=u.owner==='terran',card=(key:string)=>friendly?s.cardTotals[key+'.'+u.unitType]??0:0,oldHp=u.maxHp,oldShield=u.maxShield??0,oldEnergy=u.energy,lost=oldHp-u.hp;
 const tech=friendly?s.tech:{},race=familyRace(u.unitType as FamilyId),mechanical=d.attributes.includes('Mechanical'),air=d.flying,terranAir=['viking','banshee','medivac','science_vessel'].includes(u.unitType);
 const armorKey=race==='terran'?(terranAir?'air_armor':mechanical?'vehicle_armor':'infantry_armor'):race==='zerg'?(air?'flyer_armor':'carapace'):(air?'air_armor':'ground_armor');
 const delta=expeditionWeaponUpgrade(w,u);u.attributes=[...d.attributes];if(u.flying!==d.flying)w.hash.invalidatePlanes();u.flying=d.flying;u.unitRadius=d.unitRadius*TUNING.unitScale;u.race=race;u.team=friendly?'player':'enemy';
 const hpAdd=u.unitType==='marine'&&tech.shield?SOURCE_RESEARCH_EFFECTS.shield.maxHpAdd:u.unitType==='baneling'&&tech.bane_speed?SOURCE_RESEARCH_EFFECTS.bane_speed.maxHpAdd:0;
 u.maxHp=(d.maxHp+hpAdd)*r.health*(1+(t.maxHpPct??0))*(1+card('vitality'))*eliteEffect(u,'maxHealthMultiplier');u.hp=fill?u.maxHp:Math.min(u.maxHp,Math.max(0,u.maxHp-lost));
 u.armor=(d.armor+r.armor+(tech[race+'.'+armorKey]??0))*(1+(t.armorPct??0))+(t.armorFlat??0)+card('armor')+eliteEffect(u,'lifeArmorAdd',0);
 const speedAdd=u.unitType==='zergling'&&tech.ling_speed?SOURCE_RESEARCH_EFFECTS.ling_speed.speedAdd:u.unitType==='baneling'&&tech.bane_speed?SOURCE_RESEARCH_EFFECTS.bane_speed.speedAdd:u.unitType==='roach'&&tech.roach_speed?SOURCE_RESEARCH_EFFECTS.roach_speed.speedAdd:u.unitType==='zealot'&&tech.charge?SOURCE_RESEARCH_EFFECTS.charge.speedAdd:u.unitType==='lurker'&&u.nativeMode!=='lurker_burrowed'&&tech.lurker_deploy?SOURCE_RESEARCH_EFFECTS.lurker_deploy.speedAdd:0;
 u.moveSpeed=(d.movementSpeed+speedAdd)*r.movement*(1+(t.moveSpeedPct??0))*(race==='zerg'?source.creep:1)*eliteEffect(u,'movementSpeedMultiplier');
 u.weaponDamage=(d.attackDamage+delta.damage)*r.damage*(1+(t.weaponDamagePct??0))*(1+card('weapon'));
 u.attackRange=expeditionAttackRange(w,u,d,t);
 u.attackPeriod=d.attackPeriod/r.attackSpeed/(1+(t.attackSpeedPct??0))/(u.unitType==='adept'&&tech.glaives?1+SOURCE_RESEARCH_EFFECTS.glaives.attackSpeedAdd:1)*(u.eliteId==='lurker.3'&&u.nativeMode!=='lurker_burrowed'?1:eliteEffect(u,'attackPeriodMultiplier'));
 u.maxShield=(source.shields*r.health*(1+(t.maxShieldPct??0))+(race==='protoss'?u.maxHp*(t.shieldFromHpPct??0):0))*eliteEffect(u,'maxShieldMultiplier');u.shield=fill?u.maxShield:Math.min(u.maxShield,Math.max(0,u.maxShield-(oldShield-(u.shield??0))));u.shieldArmor=(source.shieldArmor+(tech['protoss.shields']??0))*(1+(t.shieldArmorPct??0))+(t.shieldArmorFlat??0);u.shieldRegen=source.shieldRegen*FASTER*(1+(t.shieldRegenPct??0))*(1+card('recovery'));u.shieldDelay=Math.max(1,source.shieldDelay/FASTER-(t.shieldDelayReductionSeconds??0));
 const oldTalentShield=u.maxTalentShield??0,lostTalentShield=oldTalentShield-(u.talentShield??0);u.maxTalentShield=u.attributes.includes('Biological')&&race!=='protoss'?u.maxHp*(t.shieldFromHpPct??0):0;u.talentShield=fill?u.maxTalentShield:Math.min(u.maxTalentShield,Math.max(0,u.maxTalentShield-lostTalentShield));
 u.maxEnergy=source.energy*r.energy*eliteEffect(u,'maxEnergyMultiplier')+(t.maxEnergyFlat??0);u.energy=fill?source.energyStart:Math.min(u.maxEnergy,oldEnergy);u.energyRegen=source.energyRegen*FASTER*r.energy*(1+(t.energyRegenPct??0))*(1+card('energy'));
 u.healRate=HEAL.hpPerSecond*r.healing*(1+(t.healingPct??0))*(1+card('recovery'))*(tech.support_efficiency?1.15:1)*(u.eliteId==='medivac.3'?1.25:1)*eliteEffect(u,'recoveryMultiplier');
 if(!friendly&&u.nativeStatScale){const scale=u.nativeStatScale;u.maxHp=d.maxHp*scale.hp;u.hp=fill?u.maxHp:Math.max(0,u.maxHp-lost);u.weaponDamage=d.attackDamage*scale.damage;u.attackPeriod=d.attackPeriod*scale.period;u.moveSpeed=d.movementSpeed*scale.move;u.armor=d.armor+scale.armor;}
}
export function visibleTo(w:World,target:Body,owner:Body['owner']){if(!w.expedition||target.owner===owner)return true;const u=w.entities.get(target.id);if(!u?.cloaked)return true;return w.expedition.detectionFields.some(f=>f.team===(owner==='terran'?'player':'enemy')&&f.until>w.time&&distance(f,target)<=f.radius+target.unitRadius);}
export function validAttackTarget(w:World,u:Entity,b:Body){if(b.hp<=0||b.owner===u.owner||!visibleTo(w,b,u.owner))return false;const target=w.entities.get(b.id),planes=target?.unitType==='colossus'?['ground','air']:[b.flying?'air':'ground'];if(u.heroId==='purifier_flagship')return true;const weapons=!u.heroId&&u.unitType in SOURCE_UNIT_WEAPON_IDS?sourceWeaponsForUnit(u.unitType as VerifiedAddedUnitType,u.nativeMode as keyof typeof SOURCE_UNIT_MODES):[unitData(u)];return weapons.some(data=>data.targetType==='both'||planes.includes(data.targetType));}
export function selectWeapon(w:World,u:Entity,target:Body){if(u.heroId||isInterceptor(u)||!(u.unitType in SOURCE_UNIT_WEAPON_IDS))return;const candidates=sourceWeaponsForUnit(u.unitType as VerifiedAddedUnitType,u.nativeMode as keyof typeof SOURCE_UNIT_MODES),air=target.flying||w.entities.get(target.id)?.unitType==='colossus',range=w.edgeDistance(u,target),weapon=candidates.find(a=>(a.targetType==='both'||a.targetType==='air'&&air||a.targetType==='ground'&&!target.flying)&&range>=a.minimumRange&&range<=a.attackRange)??candidates.find(a=>a.targetType==='both'||a.targetType==='air'&&air||a.targetType==='ground'&&!target.flying);if(!weapon||u.activeWeapon===weapon.weaponId)return;preserveEnemyScale(u);u.activeWeapon=weapon.weaponId;refreshExpeditionStats(w,u);}
export function castDetection(w:World){const s=w.expedition;if(!s||w.phase!=='battle'||w.paused||w.requiresPlayerDecision||w.time+1e-8<s.detectionReady)return false;const t=aggregateMvpTalentEffects(w.runConfig?.frozenTalents.levels??{},s.race,{team:'player',race:s.race,kind:'raceAbility',ability:'detection',manualAbility:true});s.detectionFields.push({id:w.nextId++,...w.anchor,radius:12*(1+(t.detectionRadiusPct??0)),until:w.time+8+(t.detectionDurationFlat??0),team:'player'});s.detectionReady=w.time+20*(1-(t.abilityCooldownReductionPct??0));w.changed();return true;}
export function tickDetection(w:World){const s=w.expedition!;s.detectionFields=s.detectionFields.filter(f=>f.until>w.time);const detectors:Body[]=[...(w.hive&&w.hive.hp>0?[w.hive]:[]),...w.expansionHives.values(),...[...w.entities.values()].filter(u=>u.hp>0&&u.owner==='zerg'&&(u.enemyTier==='boss'||u.enemyTier==='lord'||w.stage>=4&&u.detector))];for(const d of detectors){const next=s.enemyScanReady[d.id]??(s.enemyScanReady[d.id]=w.time+1);if(w.time>=next){s.detectionFields.push({id:w.nextId++,x:d.x,z:d.z,radius:12,until:w.time+6,team:'enemy'});s.enemyScanReady[d.id]=w.time+18;}else if(next-w.time<=1&&!w.effects.some(f=>f.source===d.id&&f.kind==='scan-warning'))w.effects.push({id:w.nextId++,kind:'scan-warning',x:d.x,z:d.z,end:{x:d.x,z:d.z},until:next,radius:12,owner:'zerg',source:d.id});}}
const MODES:Partial<Record<FamilyId,readonly string[]>>={hellion:['hellion','hellbat'],viking:['viking','viking_assault'],thor:['thor','thor_high_impact'],lurker:['lurker','lurker_burrowed']};
export function setFamilyMode(w:World,family:FamilyId,mode:string){const s=w.expedition;if(!s||w.phase!=='battle'||w.paused||w.requiresPlayerDecision)return false;if(family==='tank'){if(!['tank','siege'].includes(mode))return false;const units=w.familyUnits('tank');if(!units.length)return false;for(const u of units)u.desiredMode=mode as 'tank'|'siege';w.tankCommand=mode as 'tank'|'siege';w.changed();return true;}
 if(!MODES[family]?.includes(mode)||family==='hellion'&&mode==='hellbat'&&!s.tech.armory)return false;const units=w.allies().filter(u=>u.unitType===family&&!u.heroId);if(!units.length)return false;for(const u of units){u.desiredNativeMode=mode;}s.familyModes[family]=mode;w.changed();return true;}
function transformSeconds(u:Entity,mode:string){const t=SOURCE_ABILITIES.transformations;return u.unitType==='hellion'?(mode==='hellbat'?t.hellbat:t.hellion).seconds:u.unitType==='viking'?(mode==='viking_assault'?t.vikingAssault:t.vikingFighter).seconds:u.unitType==='thor'?(mode==='thor_high_impact'?t.thorHighImpact:t.thorExplosive).seconds:(mode==='lurker_burrowed'?t.lurkerBurrow:t.lurkerUnburrow).seconds;}
export function tickNativeMode(w:World,u:Entity){if(u.heroId)return false;if(u.nativeModeUntil){if(w.time<u.nativeModeUntil)return true;const mode=u.desiredNativeMode??u.unitType;if(u.unitType==='viking'&&mode!=='viking'&&(w.terrain&&!w.terrain.canOccupy(u,u.unitRadius)||blocked(u,u.unitRadius,w.obstacles)||[...w.entities.values(),...w.pods].some(b=>b.id!==u.id&&b.hp>0&&!b.flying&&distance(b,u)<b.unitRadius+u.unitRadius)))return true;
 preserveEnemyScale(u);u.nativeMode=mode;u.activeWeapon=undefined;u.nativeModeUntil=undefined;u.cloaked=mode==='lurker_burrowed';refreshExpeditionStats(w,u);return mode==='lurker_burrowed';}
 if(u.desiredNativeMode&&(u.nativeMode??u.unitType)!==u.desiredNativeMode){const t=talentModifiers(w,u),research=u.owner==='terran'&&u.unitType==='lurker'&&u.desiredNativeMode==='lurker_burrowed'&&w.expedition!.tech.lurker_deploy?SOURCE_RESEARCH_EFFECTS.lurker_deploy.burrowSecondsSubtract:0;u.nativeModeUntil=w.time+Math.max(.25,(transformSeconds(u,u.desiredNativeMode)-research)*(1-(t.transformTimeReductionPct??0))*eliteEffect(u,'transformTimeMultiplier'));u.velocity={x:0,z:0};u.action='sieging';return true;}return false;}
export function castFamilyAbility(w:World,family:FamilyId,target?:Point){const s=w.expedition;if(!s||w.phase!=='battle'||w.paused||w.requiresPlayerDecision)return false;const units=w.allies().filter(u=>u.unitType===family&&!u.heroId);let used=false;
 if(family==='banshee'&&s.tech.cloak){const on=units.some(u=>!u.cloaked);for(const u of units){if(!on){u.cloaked=false;used=true;}else if(!u.cloaked&&u.energy>=SOURCE_ABILITIES.bansheeCloak.startEnergy){u.energy-=SOURCE_ABILITIES.bansheeCloak.startEnergy;u.cloaked=true;used=true;}}}
 if(family==='stalker'&&s.tech.blink&&target&&Number.isFinite(target.x)&&Number.isFinite(target.z)){for(const u of units){if(w.time<(u.abilityReady??0)||distance(u,target)>SOURCE_ABILITIES.blink.range)continue;const p=w.freePosition(u.unitType,target,0,2);if(!p||distance(u,p)>SOURCE_ABILITIES.blink.range||w.terrain&&!w.terrain.canOccupy(p,u.unitRadius))continue;u.x=p.x;u.z=p.z;u.prev={...p};u.abilityReady=w.time+SOURCE_ABILITIES.blink.cooldown*(1-(talentModifiers(w,u,'blink').abilityCooldownReductionPct??0))*eliteEffect(u,'blinkCooldownMultiplier');used=true;}}
 if(used)w.changed();return used;}
export function tickExpeditionRecovery(w:World,u:Entity,dt:number){const source=sourceDetails(u.unitType),t=talentModifiers(w,u),recovery=1+(u.owner==='terran'&&!u.heroId?w.expedition!.cardTotals['recovery.'+u.unitType]??0:0);u.energy=Math.min(u.maxEnergy,u.energy+u.energyRegen*dt);if(u.unitType==='banshee'&&u.cloaked){u.energy=Math.max(0,u.energy-SOURCE_ABILITIES.bansheeCloak.energyDrainPerSecond*eliteEffect(u,'cloakEnergyMultiplier')*dt);if(u.energy<=0)u.cloaked=false;}
 if(u.lastStandUntil&&u.lastStandUntil>w.time)return;
 if(u.maxTalentShield&&w.time-(u.lastDamagedAt??-Infinity)>=5)u.talentShield=Math.min(u.maxTalentShield,(u.talentShield??0)+u.maxTalentShield*.03*dt);
 if(w.time-(u.lastDamagedAt??-Infinity)>=u.shieldDelay!&&u.maxShield)u.shield=Math.min(u.maxShield,(u.shield??0)+(u.shieldRegen??0)*dt);
 const native=(!u.heroId||u.heroId==='hots_leviathan')&&w.time-(u.lastDamagedAt??-Infinity)>=source.lifeDelay/FASTER*eliteEffect(u,'regenDelayMultiplier')?source.lifeRegen*FASTER*eliteEffect(u,'innateRegenMultiplier'):0;u.hp=Math.min(u.maxHp,u.hp+(native+u.maxHp*(t.regenMaxHpPerSecond??0))*recovery*dt);
}
/** Shield armor and life armor are applied to their own portion of each hit. */
export function expeditionDamage(w:World,target:Body,raw:number,hits:number,minimum:number,penetration:number,sourceOwner:Body['owner'],armor:number,sourceId?:number,shieldBonus=0){const u=w.entities.get(target.id),attacker=sourceId===undefined?undefined:w.entities.get(sourceId);let healthDamage=0;if(u&&target.owner!==sourceOwner)u.lastDamagedAt=w.time;
 if(u&&!u.heroId&&u.unitType==='immortal'&&raw>0&&target.owner!==sourceOwner&&w.time>=(u.barrierReady??0)){u.barrier=SOURCE_ABILITIES.immortalBarrier.absorption*eliteEffect(u,'barrierAbsorptionMultiplier');u.barrierReady=w.time+SOURCE_ABILITIES.immortalBarrier.cooldown;w.visual('barrier-start',u);}
 for(let i=0;i<hits;i++){let amount=raw;if(attacker&&attacker.attackRange>1&&w.expedition!.spells.some(s=>s.kind==='guardian'&&s.owner===target.owner&&s.until>w.time&&distance(s,target)<=s.radius+target.unitRadius))amount=Math.max(minimum,amount-SOURCE_ABILITIES.guardianShield.rangedDamageReduction);
  if(u?.barrier){const absorbed=Math.min(u.barrier,amount);u.barrier-=absorbed;amount-=absorbed;}
  if(u?.talentShield&&amount>0){const absorbed=Math.min(u.talentShield,amount);u.talentShield-=absorbed;amount-=absorbed;}
  if(u?.shield&&amount>0){const shieldHit=Math.max(minimum,amount+shieldBonus-(u.shieldArmor??0)*(1-penetration)),absorbed=Math.min(u.shield,shieldHit);u.shield-=absorbed;amount=Math.max(0,shieldHit-absorbed-shieldBonus);}
  if(amount>0)healthDamage+=Math.max(minimum,amount-armor*(1-penetration));
 }return Math.min(target.hp,healthDamage);}
export function tickAutoAbilities(w:World,u:Entity){if(u.unitType!=='queen'&&u.unitType!=='sentry'&&u.unitType!=='high_templar')return;const s=w.expedition!;if(u.heroId||w.time<(u.abilityReady??0)||u.nativeModeUntil||(u.stoppedUntil??0)>w.time)return;const t=talentModifiers(w,u,u.unitType==='high_templar'?'storm':u.unitType==='queen'?'transfusion':'guardianShield'),costFactor=1-(t.abilityEnergyReductionPct??0);
 if(u.unitType==='queen'){const a=SOURCE_ABILITIES.transfusion,cost=a.energy*costFactor*eliteEffect(u,'transfusionEnergyMultiplier');if(u.energy<cost)return;const p=[...w.entities.values()].filter(p=>p.owner===u.owner&&p.id!==u.id&&p.hp>0&&p.maxHp-p.hp>=a.instantHealing*.5&&p.attributes.includes('Biological')&&!p.attributes.includes('Structure')&&w.edgeDistance(u,p)<=a.range&&w.hasAttackLine(u,p)&&!s.spells.some(f=>f.kind==='transfusion'&&f.target===p.id&&f.until>w.time)).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.id-b.id)[0];if(p&&u.energy>=cost){const healing=eliteEffect(u,'transfusionHealingMultiplier');const gain=Math.min(p.maxHp-p.hp,a.instantHealing*u.healRate/HEAL.hpPerSecond*healing);p.hp+=gain;u.energy-=cost;u.abilityReady=w.time+a.cooldown;s.spells.push({id:w.nextId++,kind:'transfusion',source:u.id,target:p.id,x:p.x,z:p.z,owner:u.owner,radius:0,next:w.time+a.tickPeriod,until:w.time+a.duration,period:a.tickPeriod,amount:a.tickHealing*u.healRate/HEAL.hpPerSecond*healing});w.stats.healed+=gain;w.effect('heal',u,p,.4,.5);}}
 if(u.unitType==='sentry'){const a=SOURCE_ABILITIES.guardianShield,cost=a.energy*costFactor,shieldRadius=a.radius*eliteEffect(u,'guardianShieldRadiusMultiplier');if(u.energy<cost)return;const threat=[...w.entities.values()].some(e=>e.owner!==u.owner&&e.hp>0&&e.attackRange>1&&visibleTo(w,e,u.owner)&&distance(e,u)<10);if(threat&&u.energy>=cost&&!s.spells.some(f=>f.kind==='guardian'&&f.owner===u.owner&&distance(f,u)<shieldRadius&&f.until>w.time)){u.energy-=cost;u.abilityReady=w.time+a.cooldown;s.spells.push({id:w.nextId++,kind:'guardian',source:u.id,target:null,x:u.x,z:u.z,owner:u.owner,radius:shieldRadius,next:Infinity,until:w.time+a.duration*eliteEffect(u,'guardianShieldDurationMultiplier'),period:1,amount:2});}}
 if(u.unitType==='high_templar'&&(u.owner==='zerg'||s.tech.storm)){const a=SOURCE_ABILITIES.psiStorm,cost=a.energy*costFactor*eliteEffect(u,'stormEnergyMultiplier');if(u.energy<cost)return;const candidates=[...w.entities.values()].filter(e=>e.owner!==u.owner&&e.hp>0&&visibleTo(w,e,u.owner)&&w.edgeDistance(u,e)<=a.range&&w.hasAttackLine(u,e)&&!s.spells.some(f=>f.kind==='storm'&&f.owner===u.owner&&distance(f,e)<a.radius*1.5&&f.until>w.time));candidates.sort((x,y)=>candidates.filter(e=>distance(e,y)<a.radius).length-candidates.filter(e=>distance(e,x)<a.radius).length||x.id-y.id);const target=candidates[0];if(target&&u.energy>=cost){u.energy-=cost;u.abilityReady=w.time+a.cooldown;s.spells.push({id:w.nextId++,kind:'storm',source:u.id,target:null,x:target.x,z:target.z,owner:u.owner,radius:a.radius,next:w.time+a.damagePeriod,until:w.time+a.searchPeriods*a.damagePeriod,period:a.damagePeriod,amount:a.damagePerTick*(1+(t.abilityDamagePct??0))*eliteEffect(u,'stormDamageMultiplier')});u.lastSkillAt=w.time;w.visual('storm-start',u,target);}}
}
export function tickAreaSpells(w:World){const s=w.expedition!;for(const spell of s.spells){if(spell.kind==='guardian'){const source=w.entities.get(spell.source);if(!source||source.hp<=0){spell.until=w.time;continue;}spell.x=source.x;spell.z=source.z;}
  while(spell.next<=w.time+1e-8&&spell.next<=spell.until+1e-8){if(spell.kind==='transfusion'){const target=spell.target===null?undefined:w.entities.get(spell.target);if(target&&target.hp>0){const gain=Math.min(target.maxHp-target.hp,spell.amount);target.hp+=gain;w.stats.healed+=gain;}}
   else if(spell.kind==='storm'){let impacted=false;for(const target of w.entities.values())if(target.hp>0&&target.owner!==spell.owner&&distance(target,spell)<=spell.radius+target.unitRadius){w.hit(target,spell.amount,[],1,spell.owner,0,1,spell.source);impacted=true;}const source=w.entities.get(spell.source);if(impacted&&source)w.visual('skill-impact',source,spell);}spell.next+=spell.period;}
 }s.spells=s.spells.filter(spell=>spell.until>w.time+1e-8);}
/** Sequential simulation updates reserve only HP that was actually restored. */
export function healExpedition(w:World,u:Entity,dt:number){const previous=u.healTarget,candidates=[...w.entities.values()].filter(p=>p.owner===u.owner&&p.id!==u.id&&p.hp>0&&p.hp<p.maxHp&&!p.attributes.includes('Structure')&&(p.attributes.includes('Biological')||p.attributes.includes('Mechanical'))&&w.edgeDistance(u,p)<=HEAL.range+eliteEffect(u,'healingRangeAdd',0)&&w.hasAttackLine(u,p)).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.id-b.id);const retained=candidates.findIndex(p=>p.id===previous);if(retained>0&&candidates[retained].hp/candidates[retained].maxHp<=candidates[0].hp/candidates[0].maxHp+.08)candidates.unshift(candidates.splice(retained,1)[0]);u.healTarget=null;u.healTargets=[];const p=candidates[0];if(!p||u.energy<=0)return p;
 for(const [i,patient] of candidates.slice(0,u.eliteId==='medivac.2'?3:1).entries()){const primary=patient.attributes.includes(u.unitType==='science_vessel'?'Mechanical':'Biological'),ratio=primary?1:1/3,suppression=Math.min(.5,Math.max(w.statuses.value(patient.id,'bleed',w.time),w.statuses.value(patient.id,'corruption',w.time))),amount=Math.min(patient.maxHp-patient.hp,u.healRate*ratio*(i===0?1:.5)*(1-suppression)*dt,u.energy/HEAL.energyPerHp);if(amount<=0)continue;patient.hp+=amount;u.energy-=amount*HEAL.energyPerHp;u.healTarget??=patient.id;u.healTargets.push(patient.id);u.action='heal';w.stats.healed+=amount;}return p;}
