import type {World} from '../world';
import type {Entity,Body,Point} from '../types';
import {UNIQUE_SUPPORT,tacticalCard,type UniqueSupportId} from '../../data/unique-support';
import {validCarrierLanding} from '../movement/carrier-landing';

export interface SupportPacket {id:number;kind:'ricochet'|'missile'|'echo'|'bunker';from:Point;point:Point;at:number;start:number;damage:number;source:number;target:number;left?:number;seen?:number[];air?:boolean;groundOnly?:boolean;}
export interface UniqueSupportState {
 levels:Partial<Record<UniqueSupportId,number>>;ready:number;activeUntil:number;activeRank:number;
 cycles:Record<number,number>;echoCounts:Record<number,number>;counterReady:Record<number,number>;
 reserves:Record<number,{amount:number;until:number}>;parasites:Record<number,{damage:number;until:number}>;
 kills:number;consumeReady:number;missilesReady:number;bunkerReady:number;retryAt:number;
 landing:null|{id:number;point:Point;at:number;rank:number};
 packets:SupportPacket[];orbs:{id:number;point:Point;origin:Point;until:number;amount:number;target:number|null}[];
 prism:null|{id:number;origin:Point;direction:Point;next:number;remaining:number;damage:number};
}
export const newUniqueSupport=():UniqueSupportState=>({levels:{},ready:0,activeUntil:0,activeRank:0,cycles:{},echoCounts:{},counterReady:{},reserves:{},parasites:{},kills:0,consumeReady:0,missilesReady:0,bunkerReady:0,retryAt:0,landing:null,packets:[],orbs:[],prism:null});
export function validateUniqueSupport(s:UniqueSupportState,race:string){
 if(!s||!s.levels||!s.cycles||!s.echoCounts||!s.counterReady||!s.reserves||!s.parasites||Object.entries(s.levels).some(([id,n])=>!(id in UNIQUE_SUPPORT)||UNIQUE_SUPPORT[id as UniqueSupportId].race!==race||!Number.isInteger(n)||n<0||n>3)||![s.ready,s.activeUntil,s.consumeReady,s.missilesReady,s.bunkerReady,s.retryAt].every(Number.isFinite)||!Number.isInteger(s.kills)||s.kills<0||s.kills>12||!Number.isInteger(s.activeRank)||s.activeRank<0||s.activeRank>3||!Array.isArray(s.packets)||!Array.isArray(s.orbs))throw Error('独有趣味卡状态无效');
 const point=(p:Point)=>p&&Number.isFinite(p.x)&&Number.isFinite(p.z);
 if(Object.values(s.cycles).some(n=>!Number.isSafeInteger(n)||n<0)||Object.values(s.echoCounts).some(n=>!Number.isSafeInteger(n)||n<0)||Object.values(s.counterReady).some(n=>!Number.isFinite(n))||Object.values(s.reserves).some(r=>!Number.isFinite(r.amount)||r.amount<0||!Number.isFinite(r.until))||Object.values(s.parasites).some(r=>!Number.isFinite(r.damage)||r.damage<0||!Number.isFinite(r.until)))throw Error('支援实体状态无效');
 if(s.packets.some(p=>!Number.isSafeInteger(p.id)||!point(p.from)||!point(p.point)||![p.at,p.start,p.damage].every(Number.isFinite)||p.damage<0||!['ricochet','missile','echo','bunker'].includes(p.kind))||s.orbs.length>2||s.orbs.some(o=>!point(o.point)||!point(o.origin)||!Number.isFinite(o.until)||!Number.isFinite(o.amount))||s.landing&&(!point(s.landing.point)||!Number.isFinite(s.landing.at)||s.landing.rank<1||s.landing.rank>3)||s.prism&&(!point(s.prism.origin)||!point(s.prism.direction)||!Number.isInteger(s.prism.remaining)||s.prism.remaining<1||s.prism.remaining>10||!Number.isFinite(s.prism.next)||!Number.isFinite(s.prism.damage)))throw Error('支援在途状态无效');
}
const state=(w:World)=>w.expedition.support.unique;
export const supportRank=(w:World,id:UniqueSupportId)=>state(w).levels[id]??0;
const dist=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.z-b.z);
const enemy=(w:World)=>[...w.entities.values()].filter(e=>e.hp>0&&e.team==='enemy');
const usable=(u:Entity)=>u.team==='player'&&!u.temporary&&!u.summonKind;
const firing=(u:Entity)=>usable(u)&&!u.heroId;
const line=(w:World,a:Point,b:Body,air=false)=>!w.terrain||w.terrain.lineOfFire(a,b,air,b.flying);
function event(w:World,kind:'support-impact'|'support-flight'|'support-pulse',p:Point,end:Point=p){w.visual(kind,{...p,id:0,hp:1,maxHp:1,armor:0,owner:'terran',race:w.expedition.race,unitRadius:0,flying:false,attributes:[]},end);}
function area(w:World,p:Point,damage:number,radius:number,slow=0){for(const e of enemy(w))if(dist(e,p)<=radius+e.unitRadius){w.hit(e,damage,[],1,'terran',0);if(slow&&e.hp>0){e.slowUntil=w.time+2;e.slowFactor=1-(e.enemyTier==='boss'||e.enemyTier==='lord'?slow/2:slow);}}event(w,'support-impact',p);}
export function uniqueLegal(w:World,id:UniqueSupportId){if(UNIQUE_SUPPORT[id].race!==w.expedition.race||supportRank(w,id)>=3)return false;if(id==='terran.ricochet')return w.allies().some(u=>firing(u)&&['marine','marauder','reaper'].includes(u.unitType));return true;}
export function buyUnique(w:World,id:UniqueSupportId){if(!uniqueLegal(w,id))return false;const s=state(w);s.levels[id]=supportRank(w,id)+1;if(id==='terran.missiles'&&s.levels[id]===1)s.missilesReady=w.time+24;return true;}

/** Only called by a real primary weapon hit; saved shot sequence prevents multi-hit recursion. */
export function uniquePrimary(w:World,u:Entity,target:Body,damage:number){if(!firing(u))return;const s=state(w),cycle=u.shotSequence??0,first=s.cycles[u.id]!==cycle;s.cycles[u.id]=cycle;
 const parasite=supportRank(w,'zerg.parasite'),victim=w.entities.get(target.id);
 if(parasite&&victim&&victim.hp>0&&victim.team==='enemy'&&!victim.summonKind&&!['boss','lord'].includes(victim.enemyTier??''))s.parasites[victim.id]={damage:[0,80,120,160][parasite],until:w.time+4};
 if(!first)return;
 const ric=supportRank(w,'terran.ricochet');if(ric&&['marine','marauder','reaper'].includes(u.unitType)&&w.random()<[0,.25,.35,.45][ric])jump(w,{id:w.nextId++,kind:'ricochet',from:{x:target.x,z:target.z},point:{x:target.x,z:target.z},start:w.time,at:w.time,damage:damage*.4,source:u.id,target:target.id,left:ric,seen:[target.id],air:u.flying,groundOnly:u.unitType!=='marine'});
 const echo=supportRank(w,'protoss.echo');if(echo){const n=s.echoCounts[u.id]=(s.echoCounts[u.id]??0)+1;if(n%3===0&&target.hp>0){s.packets.push({id:w.nextId++,kind:'echo',from:{x:u.x,z:u.z},point:{x:target.x,z:target.z},start:w.time,at:w.time+.6,damage:damage*[0,.35,.5,.65][echo],source:u.id,target:target.id,air:u.flying});event(w,'support-pulse',target);}}
}
function jump(w:World,p:SupportPacket){if(!p.left)return;const source=w.entities.get(p.source),target=enemy(w).filter(e=>!p.seen!.includes(e.id)&&(!p.groundOnly||!e.flying)&&dist(e,p.point)<=3&&w.visibleTo(e,'terran')&&line(w,p.point,e,p.air)&&(!source||w.targetAllowed(source,e))).sort((a,b)=>dist(a,p.point)-dist(b,p.point)||a.id-b.id)[0];if(!target)return;const from={...p.point},point={x:target.x,z:target.z};state(w).packets.push({...p,id:w.nextId++,from,point,start:w.time,at:w.time+dist(from,point)/20,target:target.id,left:p.left-1,seen:[...p.seen!,target.id]});}
export function uniqueDeath(w:World,victim:Entity,sourceId?:number){const s=state(w),mark=s.parasites[victim.id];delete s.parasites[victim.id];if(mark&&mark.until>=w.time)area(w,victim,mark.damage,2.5);
 if(victim.team!=='enemy'||victim.summonKind||victim.temporary||dist(victim,w.anchor)>12)return;const source=sourceId===undefined?undefined:w.entities.get(sourceId);if(source?.temporary||source?.summonKind)return;
 if(supportRank(w,'zerg.hatch'))s.kills=Math.min(12,s.kills+1);
 const rank=supportRank(w,'zerg.consume');if(rank&&w.time>=s.consumeReady&&s.orbs.length<2&&w.visibleTo(victim,'terran')){s.orbs.push({id:w.nextId++,point:{x:victim.x,z:victim.z},origin:{x:victim.x,z:victim.z},until:w.time+6,amount:[0,40,60,80][rank],target:null});s.consumeReady=w.time+3;}
}
export function uniqueShieldTick(w:World,u:Entity,dt:number){const s=state(w),rank=supportRank(w,'protoss.reserve');if(!rank||!usable(u)||!u.maxShield)return;const r=s.reserves[u.id]??={amount:0,until:0},overflow=Math.max(0,(u.shield??0)+(u.shieldRegen??0)*dt-u.maxShield);if(w.time-(u.lastDamagedAt??-Infinity)>=(u.shieldDelay??0)){r.amount=Math.min(u.maxShield*[0,.15,.225,.3][rank],r.amount+overflow);r.until=w.time+6;}else if(w.time>=r.until)r.amount=0;}
export function absorbReserve(w:World,u:Entity,amount:number){const r=state(w).reserves[u.id];if(!r||r.until<w.time)return amount;const n=Math.min(r.amount,amount);r.amount-=n;return amount-n;}
export function uniqueShieldBreak(w:World,u:Entity){const s=state(w),rank=supportRank(w,'protoss.counter');if(!rank||!usable(u)||w.time<(s.counterReady[u.id]??0))return;s.counterReady[u.id]=w.time+12;area(w,u,[0,120,180,240][rank],3,.25);}
export function uniqueActiveStats(w:World,u:Entity){const s=state(w),on=s.activeUntil>w.time&&u.team==='player';return {speed:on&&w.expedition.race==='terran'?[0,.2,.3,.4][s.activeRank]:0,move:on&&w.expedition.race==='terran'?.15:0,armor:on&&w.expedition.race==='zerg'&&u.attributes.includes('Biological')?[0,2,3,4][s.activeRank]:0};}
export function previewTactical(w:World,p?:Point){const s=state(w);if(w.phase!=='battle'||w.paused||w.requiresPlayerDecision||!supportRank(w,tacticalCard(w.expedition.race))||w.time<s.ready||s.prism)return false;if(w.expedition.race!=='protoss')return w.allies().some(u=>u.hp>0&&(w.expedition.race!=='zerg'||u.attributes.includes('Biological')));return !!p&&Number.isFinite(p.x)&&Number.isFinite(p.z)&&dist(p,w.anchor)>.01&&(w.terrain?w.terrain.isOpen?.(p)??w.terrain.canOccupy(p,0):Math.abs(p.x)<=76&&Math.abs(p.z)<=76);}
export function castTactical(w:World,p?:Point){if(!previewTactical(w,p))return false;const s=state(w),race=w.expedition.race,rank=supportRank(w,tacticalCard(race));s.ready=w.time+60*Math.max(.5,1-.10*w.talent('skill_recovery'));s.activeRank=rank;
 if(race==='protoss'){const length=dist(p!,w.anchor);s.prism={id:w.nextId++,origin:{x:w.anchor.x,z:w.anchor.z},direction:{x:(p!.x-w.anchor.x)/length,z:(p!.z-w.anchor.z)/length},next:w.time+.7,remaining:10,damage:[0,800,1100,1400][rank]/10};}
 else {s.activeUntil=w.time+8;for(const u of w.entities.values()){if(u.team!=='player'||u.hp<=0)continue;if(race==='zerg'&&u.attributes.includes('Biological'))u.hp=Math.min(u.maxHp,u.hp+u.maxHp*[0,.15,.225,.3][rank]);w.refreshStats(u);event(w,'support-pulse',u);}}w.changed();return true;}

function bunkerPoint(w:World,p:Point){return validCarrierLanding(w,'marine',p,undefined,1.6)&&!w.allies().some(u=>!u.flying&&dist(u,p)<1.6+u.unitRadius)&&!enemy(w).some(u=>!u.flying&&dist(u,p)<1.6+u.unitRadius);}
export function tickUnique(w:World,dt=1/60){const s=state(w);
 if(s.activeUntil&&s.activeUntil<=w.time){s.activeUntil=0;for(const u of w.entities.values())if(u.team==='player'&&u.hp>0)w.refreshStats(u);}
 const due=s.packets.filter(p=>p.at<=w.time+1e-8);s.packets=s.packets.filter(p=>p.at>w.time+1e-8);
 for(const p of due){if(p.kind==='bunker'&&!w.fortifications.has(p.source))continue;const target=w.entities.get(p.target);if(p.kind==='missile'){area(w,p.point,p.damage,1.2);continue;}if(target?.hp&&w.visibleTo(target,'terran')&&line(w,p.from,target,p.air)&&(p.kind!=='echo'||dist(target,p.point)<=1.5)&&(p.kind!=='bunker'||dist(target,p.from)<=8+target.unitRadius)){w.hit(target,p.damage,[],1,'terran',0);event(w,'support-impact',target);if(p.kind==='ricochet')jump(w,{...p,point:{x:target.x,z:target.z}});}}
 for(const orb of s.orbs){if(orb.target===null){const t=w.allies().filter(u=>u.hp>0&&u.hp<u.maxHp&&u.attributes.includes('Biological')&&dist(u,orb.origin)<=6).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp||a.id-b.id)[0];if(t)orb.target=t.id;}
  if(orb.target!==null){const target=w.entities.get(orb.target);if(!target?.hp){orb.until=0;continue;}const d=dist(orb.point,target);if(d<=8*dt){const gain=Math.min(target.maxHp-target.hp,orb.amount);target.hp+=gain;w.stats.healed+=gain;orb.until=0;event(w,'support-pulse',target);}else{orb.point.x+=(target.x-orb.point.x)/d*8*dt;orb.point.z+=(target.z-orb.point.z)/d*8*dt;}}}s.orbs=s.orbs.filter(o=>o.until>w.time);
 for(const [id,mark] of Object.entries(s.parasites))if(mark.until<w.time||!w.entities.get(+id)?.hp)delete s.parasites[+id];
 const hatch=supportRank(w,'zerg.hatch');if(hatch&&s.kills>=12&&w.time>=s.retryAt){s.retryAt=w.time+1;const count=hatch+1,alive=w.allies().filter(u=>u.temporaryKind==='fun-brood').length;if(alive+count<=2*count){const points:Point[]=[];for(let i=0;i<count;i++){let p:Point|null=null;for(let a=0;a<16&&!p;a++){const t=(i*7+a)*Math.PI/8,origin={x:w.anchor.x+Math.sin(t)*(1+i*.5),z:w.anchor.z+Math.cos(t)*(1+i*.5)},q=w.freePosition('zergling',origin,0,.7);if(q&&points.every(old=>dist(old,q)>.6))p=q;}if(p)points.push(p);}if(points.length===count){s.kills=0;for(const p of points){const u=w.addUnit('zergling','terran',p.x,p.z,1);u.temporary=true;u.temporaryKind='fun-brood';u.temporaryUntil=w.time+12;w.refreshStats(u,true);event(w,'support-pulse',p);}}}}
 const missile=supportRank(w,'terran.missiles');if(missile&&w.time>=s.missilesReady){const targets=enemy(w).filter(e=>dist(e,w.anchor)<=14&&w.visibleTo(e,'terran')).sort((a,b)=>dist(a,w.anchor)-dist(b,w.anchor)||a.id-b.id);if(targets.length){s.missilesReady=w.time+24;for(let i=0;i<2+missile*2;i++){const t=targets[i%targets.length],point={x:t.x,z:t.z};s.packets.push({id:w.nextId++,kind:'missile',from:{x:w.anchor.x,z:w.anchor.z},point,start:w.time+i*.2,at:w.time+i*.2+.6,damage:60,source:0,target:t.id});}}}
 for(const fort of [...w.fortifications.values()])if(fort.supportUntil!==undefined){if(fort.supportUntil<=w.time){w.fortifications.delete(fort.id);continue;}if(fort.nextActionAt<=w.time){const target=enemy(w).filter(e=>dist(e,fort)<=8+e.unitRadius&&w.visibleTo(e,'terran')&&line(w,fort,e)).sort((a,b)=>dist(a,fort)-dist(b,fort)||a.id-b.id)[0];if(target){fort.nextActionAt=w.time+.5;const damage=[0,12,16,20][fort.supportRank!];w.hit(target,damage,[],1,'terran',0);event(w,'support-flight',fort,target);s.packets.push({id:w.nextId++,kind:'bunker',from:{x:fort.x,z:fort.z},point:{x:target.x,z:target.z},start:w.time,at:w.time+.08,source:fort.id,target:target.id,damage});}}}
 const bunker=supportRank(w,'terran.bunker');if(s.landing&&s.landing.at<=w.time){const l=s.landing;s.landing=null;if(bunkerPoint(w,l.point)){const hp=[0,1200,1800,2400][l.rank];w.fortifications.set(l.id,{id:l.id,...l.point,hp,maxHp:hp,armor:2,unitRadius:1.6,flying:false,attributes:['Armored','Mechanical','Structure'],owner:'terran',race:'terran',team:'player',kind:'bunker',nextActionAt:w.time,supportUntil:w.time+30,supportRank:l.rank});s.bunkerReady=w.time+35;event(w,'support-impact',l.point);}else s.bunkerReady=w.time+1;}
 if(bunker&&!s.landing&&s.bunkerReady<=w.time&&![...w.fortifications.values()].some(f=>f.supportUntil!==undefined)){s.bunkerReady=w.time+1;for(let i=0;i<48;i++){const a=i*Math.PI/8,r=4+Math.floor(i/16),p={x:w.anchor.x+Math.sin(a)*r,z:w.anchor.z+Math.cos(a)*r};if(bunkerPoint(w,p)){s.landing={id:w.nextId++,point:p,at:w.time+1.5,rank:bunker};break;}}}
 if(s.prism){const beam=s.prism;while(beam.remaining>0&&beam.next<=w.time+1e-8){for(const e of enemy(w)){const dx=e.x-beam.origin.x,dz=e.z-beam.origin.z,along=dx*beam.direction.x+dz*beam.direction.z,across=Math.abs(dx*beam.direction.z-dz*beam.direction.x);if(along>=0&&along<=14+e.unitRadius&&across<=1+e.unitRadius&&line(w,beam.origin,e))w.hit(e,beam.damage,[],1,'terran',0);}event(w,'support-flight',beam.origin,{x:beam.origin.x+beam.direction.x*14,z:beam.origin.z+beam.direction.z*14});beam.remaining--;beam.next+=.2;}if(!beam.remaining)s.prism=null;}
 for(const dict of [s.cycles,s.echoCounts,s.counterReady,s.reserves])for(const id of Object.keys(dict))if(!w.entities.has(+id))delete dict[+id];
}
