const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let csrf=sessionStorage.getItem('sc2.admin.csrf')??'',user=null,tab='overview',report=null,feedback=[],feedbackCategory='',feedbackStatus='',busy=false;
const number=n=>Number(n??0).toLocaleString('zh-CN',{maximumFractionDigits:1}),date=n=>new Date(n).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}),query=()=>new URLSearchParams(new FormData($('#filters'))).toString();
const families=['陆战队员','劫掠者','死神','恶火','攻城坦克','雷神','维京','女妖','医疗运输机','科学船','跳虫','爆虫','蟑螂','破坏者','刺蛇','虫后','潜伏者','飞龙','腐化者','雷兽','狂热者','使徒','追猎者','哨兵','不朽者','巨像','高阶圣堂武士','凤凰','虚空辉光舰','航母'],ids=['marine','marauder','reaper','hellion','tank','thor','viking','banshee','medivac','science_vessel','zergling','baneling','roach','ravager','hydralisk','queen','lurker','mutalisk','corruptor','ultralisk','zealot','adept','stalker','sentry','immortal','colossus','high_templar','phoenix','void_ray','carrier'];
const heroes={raynor:'雷诺',tychus:'泰凯斯',nova:'诺娃',swann:'斯旺',tosh:'托什',yamato_battlecruiser:'大和战列巡航舰',kerrigan:'凯瑞甘',zagara:'扎加拉',dehaka:'德哈卡',stukov:'斯托科夫',niadra:'尼雅德拉',hots_leviathan:'利维坦',artanis:'阿塔尼斯',zeratul:'泽拉图',alarak:'阿拉纳克',fenix:'菲尼克斯',vorazun:'沃拉尊',purifier_flagship:'净化者旗舰',unattributed:'来源未识别',natural_regeneration:'自然恢复'};
const label=id=>heroes[id]??(ids.includes(id.split('.')[0])?families[ids.indexOf(id.split('.')[0])]+(id.includes('.')?' · 精英 '+id.split('.')[1]:'' ):id),races={terran:'人族',zerg:'虫族',protoss:'神族'},diff={easy:'简单',normal:'普通',hard:'困难',hell:'地狱'},status={new:'待处理',reviewing:'处理中',planned:'已计划',resolved:'已解决',closed:'暂不处理'},cats={problem:'问题',performance:'性能',balance:'平衡',suggestion:'建议',other:'其他'};
function error(message=''){ $('#error').hidden=!message;$('#error').textContent=message;}
async function api(url,body){const res=await fetch(url,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-SC2-Client':'1','X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)});if(!res.ok){const e=await res.json().catch(()=>({}));if(res.status===401&&user)loggedOut();throw Error(({service_unavailable:'统计服务尚未配置或暂不可用，游戏不受影响。',login_failed:'名称或密码不正确。',login_limited:'登录尝试过多，请15分钟后重试。',contact_export_forbidden:'此账号没有联系方式导出权限。',credential_invalid:'会话已过期，请重新登录。',csrf_invalid:'页面凭据已失效，请重新登录。',range_must_be_1_to_90_days:'请选择1至90天的明细区间。',range_must_be_1_to_730_days:'请选择1至730天的历史汇总区间。'})[e.error]??'请求未完成，请稍后重试。');}return res;}
function loggedOut(){user=null;csrf='';sessionStorage.removeItem('sc2.admin.csrf');$('#login-panel').hidden=false;$('#workspace').hidden=true;$('#logout').hidden=true;$('#account').textContent='尚未登录';$('#content').replaceChildren();}
function loggedIn(u){user=u;$('#login-panel').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;$('#account').textContent=u.username;}
function table(columns,rows){if(!rows.length)return '<div class="empty">当前筛选没有已授权的观测样本。</div>';return `<div class="table-wrap"><table><thead><tr>${columns.map(c=>'<th>'+escape(c[0])+'</th>').join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+columns.map(c=>'<td'+(c[2]?' class="text"':'')+'>'+c[1](r)+'</td>').join('')+'</tr>').join('')}</tbody></table></div>`;}
const metric=(name,value,note)=>`<div class="metric"><span>${escape(name)}</span><strong>${number(value)}</strong><small>${escape(note)}</small></div>`;
function chart(rows){if(!rows.length)return '<p>尚无每日样本。</p>';const width=640,height=180,max=Math.max(1,...rows.map(r=>r.browsers)),points=rows.map((r,i)=>`${20+i*(width-40)/Math.max(1,rows.length-1)},${height-20-r.browsers/max*(height-40)}`).join(' ');return `<svg class="chart" viewBox="0 0 ${width} ${height}" role="img" aria-label="每日授权浏览器样本，最高${max}"><path d="M20 20V160H620" stroke="#bacbd6" fill="none"/><polyline points="${points}" fill="none" stroke="#277e7e" stroke-width="3"/>${rows.map((r,i)=>`<circle cx="${20+i*(width-40)/Math.max(1,rows.length-1)}" cy="${height-20-r.browsers/max*(height-40)}" r="3" fill="#a46a25"><title>${escape(r.day)}：${r.browsers}</title></circle>`).join('')}</svg><div class="chart-labels"><span>${escape(rows[0].day)}</span><span>${escape(rows.at(-1).day)}</span></div>`;}
function render(){if(!report)return;const s=report.summary;$('#scope').textContent=`授权浏览器样本 · ${report.sampleRuns}个有阶段摘要的战局 · ${report.partialStages}条不完整观察区间`;
 if(tab==='overview')$('#content').innerHTML=`<div class="metrics">${metric('日活跃浏览器',s.dau,'区间最后一天')}${metric('7日活跃浏览器',s.wau,'在所选区间内去重')}${metric('30日活跃浏览器',s.mau,'在所选区间内去重')}${metric('访问会话',s.sessions,'已同意统计的访问')}</div><div class="split"><section class="panel"><h3>每日授权样本</h3>${chart(report.daily)}</section><section class="panel"><h3>战局观察</h3><p>新开局 <b>${s.starts}</b>　已结束 <b>${s.ended}</b></p><p>未完成 <b>${s.unfinished}</b>　这些战局累计观察 <b>${number(s.observed_seconds/60)}</b> 分钟</p><p>新增浏览器 ${s.new_browsers} · 回访 ${s.returning_browsers}</p><small>战局指标为区间内有活动战局的累计值。保留中的浏览器索引用于区分新增与回访。</small></section></div><section class="panel"><h3>同期群留存</h3>${table([['观察日',r=>'D'+r.days],['已成熟样本',r=>number(r.eligible)],['回访样本',r=>number(r.returned)],['留存率',r=>r.rate===null?'—':(r.rate*100).toFixed(1)+'%']],report.retention)}<p class="note">仅纳入已完整到达相应观察日的新增浏览器；没有成熟样本时不显示比例。</p></section>`;
 else if(tab==='funnel')$('#content').innerHTML=table([['场景',r=>r.mode==='endless'?'无尽':'战役'],['关 / 轮',r=>r.stage],['种族',r=>races[r.race]],['难度',r=>diff[r.difficulty]],['到达样本',r=>number(r.samples)],['完成',r=>number(r.cleared)],['失败',r=>number(r.failed)],['未完成',r=>number(r.unfinished)]],report.funnel);
 else if(tab==='usage')$('#content').innerHTML='<p class="note">每种身份显示使用战局数及分母。输出包含实际生命与原生护盾扣除；护甲、减速与增益不被虚构为伤害。零样本不会生成强弱排名。</p>'+table([['部队 / 来源',r=>escape(label(r.id))+'<small>'+escape(r.id)+'</small>'],['使用战局 / 样本',r=>r.runs+' / '+r.denominator],['最高军衔',r=>r.maxRank||'—'],['到达战役 / 无尽',r=>r.highestCampaign+' / '+r.highestEndless],['实际伤害',r=>number(r.damage)],['治疗',r=>number(r.healed)],['回盾',r=>number(r.shieldRestored)],['死亡',r=>number(r.deaths)],['复生',r=>number(r.revivals)],['观察阶段',r=>number(r.observedStages)]],[...report.usage].sort((a,b)=>b.runs-a.runs||b.damage-a.damage))+'<section class="panel"><h3>阶段搭配、天赋与路线科技</h3><p class="note">搭配表示同一观察阶段出现，未断言同时在场或带来胜利。各行按战局去重，最多显示500组；到达关卡只计含该组合的阶段。</p><button data-export="builds">导出构筑样本 CSV</button>'+table([['类型',r=>({pair:'阶段搭配',talents:'天赋',research:'路线科技'})[r.kind]],['身份 / 语义ID',r=>escape(r.kind==='pair'?r.id.split(' + ').map(label).join(' + '):r.id),true],['级数',r=>r.level||'—'],['战局 / 样本',r=>r.runs+' / '+r.denominator],['战役 / 无尽最高到达',r=>r.highestCampaign+' / '+r.highestEndless]],report.builds)+'</section>';
 else if(tab==='cards')$('#content').innerHTML=table([['卡牌 / 交易ID',r=>escape(r.id)],['动作',r=>escape(r.action)],['品质',r=>escape(r.quality)],['当时层数 / 军衔',r=>r.level??'—'],['记录数',r=>number(r.samples)],['矿物',r=>number(r.minerals)],['瓦斯',r=>number(r.gas)]],report.cards);
 else if(tab==='performance')$('#content').innerHTML='<section class="panel"><h3>资源准备</h3>'+table([['缓存状态',r=>r.cold?'有网络请求':'缓存或已准备'],['样本',r=>number(r.samples)],['平均耗时 ms',r=>number(r.mean_ms)],['下载 MiB',r=>number(r.network_bytes/1048576)],['命中 / 未命中',r=>number(r.cache_hits)+' / '+number(r.cache_misses)],['失败',r=>number(r.failures)],['平均累积解析 ms',r=>number(r.parse_ms)],['平均累积编译 ms',r=>number(r.gpu_ms)]],report.load)+'</section><section class="panel"><h3>关卡帧时</h3>'+table([['场景',r=>r.mode==='endless'?'无尽':'战役'],['阶段样本',r=>number(r.samples)],['平均P95 ms',r=>number(r.mean_stage_p95)],['平均P99 ms',r=>number(r.mean_stage_p99)],['最差P99 ms',r=>number(r.worst_stage_p99)],['长帧 / 帧数',r=>number(r.long_frames)+' / '+number(r.frames)],['单位峰值',r=>number(r.peak_units)],['最大欠账增量 s',r=>number(r.backlog_delta)]],report.performance)+'<p class="note">每关P95/P99的汇总不等于所有帧合并后的分位数。只观察可见、正常运行的战斗帧。</p></section>';
}
async function load(){if(!user||busy)return;busy=true;error();try{if(tab==='feedback')await loadFeedback();else if(tab==='archive'){const result=await(await api('/api/admin/archive?'+query())).json();$('#scope').textContent='不含浏览器标识的历史日汇总 · 最多730天';$('#content').innerHTML='<p class="note">此页仅应用日期、版本与诊断筛选，其他筛选不适用于日汇总。每行在当日、该版本内去重；跨日或跨版本相加不能得到独立浏览器数。后台每小时更新，原始明细到期后仍保留本表。</p>'+table([['日期',r=>escape(r.day)],['版本',r=>escape(r.build),true],['样本组',r=>r.diagnostic?'诊断':'一般'],['浏览器',r=>number(r.browsers)],['会话',r=>number(r.sessions)],['新开局',r=>number(r.starts)]],result.rows);}else{report=await(await api('/api/admin/metrics?'+query())).json();render();}$('#updated').textContent='ASIA/SHANGHAI\n'+date(Date.now());}catch(e){error(e.message);}finally{busy=false;}}
async function loadFeedback(){const p=new URLSearchParams(query());if(feedbackCategory)p.set('category',feedbackCategory);if(feedbackStatus)p.set('status',feedbackStatus);feedback=(await(await api('/api/admin/feedback?'+p)).json()).rows;$('#scope').textContent=`反馈 ${feedback.length} 条 · 按日期、版本、分类和处理状态筛选，最多显示500条`;$('#content').innerHTML=`<div class="feedback-toolbar"><label>分类<select id="feedback-category"><option value="">全部分类</option>${Object.entries(cats).map(([k,v])=>`<option value="${k}" ${k===feedbackCategory?'selected':''}>${v}</option>`).join('')}</select></label><label>处理状态<select id="feedback-status"><option value="">全部状态</option>${Object.entries(status).map(([k,v])=>`<option value="${k}" ${k===feedbackStatus?'selected':''}>${v}</option>`).join('')}</select></label>${user.canExportContacts?'<button id="contacts">单独导出本筛选联系方式</button>':''}</div>`+table([['提交时间',r=>escape(date(r.created_at))],['分类',r=>cats[r.category]],['正文',r=>escape(r.body.slice(0,100)),true],['状态',r=>status[r.status]],['优先级',r=>r.priority],['操作',r=>`<button data-feedback="${r.id}">查看 / 处理</button>`]],feedback);$('#feedback-category').onchange=e=>{feedbackCategory=e.target.value;void load();};$('#feedback-status').onchange=e=>{feedbackStatus=e.target.value;void load();};$('#contacts')?.addEventListener('click',()=>void download('contacts'));}
function detail(id){const r=feedback.find(f=>f.id===id);if(!r)return;$('#feedback-fields').innerHTML=`<span class="eyebrow">FEEDBACK / ${escape(r.id)}</span><h2>${cats[r.category]} · ${status[r.status]}</h2><p class="feedback-body">${escape(r.body)}</p><p class="note">${escape(date(r.created_at))} · ${r.has_contact?'已留联系方式，可由具备权限的账号单独导出':'未留联系方式'}</p><p class="note">${escape(JSON.stringify(r.summary))}</p><form id="edit-feedback"><label>状态<select name="status">${Object.entries(status).map(([k,v])=>`<option value="${k}" ${k===r.status?'selected':''}>${v}</option>`).join('')}</select></label><label>优先级（0最高 / 3最低）<select name="priority">${[0,1,2,3].map(n=>`<option ${n===r.priority?'selected':''}>${n}</option>`).join('')}</select></label><label>标签（最多8个，以逗号分隔）<input name="tags" maxlength="247" value="${escape(r.tags.join(','))}"></label><label>管理员备注<textarea name="note" rows="4" maxlength="2000">${escape(r.admin_note)}</textarea></label><button class="primary">保存处理结果</button><p id="edit-status" role="status"></p></form>`;$('#edit-feedback').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target),b=e.target.querySelector('button');b.disabled=true;try{await api('/api/admin/feedback',{id,status:d.get('status'),priority:Number(d.get('priority')),tags:d.get('tags').split(',').map(s=>s.trim()).filter(Boolean),note:d.get('note')});$('#feedback-detail').close();await load();}catch(e){$('#edit-status').textContent=e.message;}finally{b.disabled=false;}};$('#feedback-detail').showModal();}
async function download(kind){try{const params=new URLSearchParams(query());if(kind==='feedback'){if(feedbackCategory)params.set('category',feedbackCategory);if(feedbackStatus)params.set('status',feedbackStatus);}const res=await api('/api/admin/export',{kind,filters:params.toString(),...(kind==='contacts'?{ids:feedback.map(f=>f.id)}:{})}),blob=await res.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='sc2-'+kind+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){error(e.message);}}
$('#login').onsubmit=async e=>{e.preventDefault();error();const b=e.target.querySelector('button'),d=new FormData(e.target);b.disabled=true;$('#login-status').textContent='正在验证…';try{const r=await(await api('/api/admin/login',{username:d.get('username'),password:d.get('password')})).json();csrf=r.csrf;sessionStorage.setItem('sc2.admin.csrf',csrf);e.target.reset();loggedIn(r.user);await load();}catch(e){error(e.message);}finally{b.disabled=false;$('#login-status').textContent='';}};
$('#logout').onclick=async()=>{try{await api('/api/admin/logout',{});loggedOut();}catch(e){error(e.message);}};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#heading').textContent=b.textContent.slice(3).trim();void load();});
$('#filters').onsubmit=e=>{e.preventDefault();void load();};$('#export').onclick=()=>void download(tab==='overview'?'daily':tab);$('#content').onclick=e=>{const b=e.target.closest('[data-feedback]');if(b)detail(b.dataset.feedback);const exportButton=e.target.closest('[data-export]');if(exportButton)void download(exportButton.dataset.export);};
const day=ms=>new Date(ms+8*3600000).toISOString().slice(0,10);$('#filters [name=from]').value=day(Date.now()-29*86400000);$('#filters [name=to]').value=day(Date.now());
setInterval(()=>{if(!document.hidden&&!$('#feedback-detail').open)void load();},30000);
if(csrf)api('/api/admin/me').then(r=>r.json()).then(r=>{loggedIn(r.user);void load();}).catch(()=>loggedOut());
