import * as THREE from 'three';
import {World} from '../../src/simulation/world';
import {BattleRenderer} from '../../src/render/scene/battle-renderer';
import {FixedStepper} from '../../src/simulation/fixed-stepper';
import {HEROES} from '../../src/data/heroes';
import {PROTOSS_HERO_IDS as ids,type ProtossHeroId,PROTOSS_HERO_PASSIVE_DESCRIPTIONS as description} from '../../src/data/protoss-heroes';
import {ASSETS,assetUrl} from '../../src/assets/manifest';
import {loadEmbeddedAssets,prepareEmbeddedAssetIds} from '../../src/assets/offline-pack';
import {captureBattleView} from '../../src/render/input/battle-view';
import {bindBattleView,activateBattleAction} from '../../src/ui/controls/battle-actions';
import {terrainArray} from '../../src/render/terrain/map-surface';
import {initializeCarrierSubsystem,ownedInterceptors} from '../../src/simulation/combat/carriers';
import {RUN_SCHEMA} from '../../src/simulation/persistence/run-snapshot';
import {encodeGraph,decodeGraph} from '../../src/persistence/graph-codec';
type Mode='battle'|'attack'|'skill'|'shield'|'boss12'|'boss3';
const $=(id:string)=>document.getElementById(id)!;
const selected=new Set<string>(JSON.parse($('demo-assets').textContent!));for(const id of ASSETS.keys())if(!selected.has(id))ASSETS.delete(id);
const world=new World({race:'protoss',sandbox:true,waves:false,terrain:false,obstacles:[],seed:10507}),canvas=$('battle') as HTMLCanvasElement,view=new BattleRenderer(canvas,world);view.fx.heroQuality='full';view.cameraShake=false;bindBattleView(world,()=>captureBattleView(canvas,view.camera));
let hero:ProtossHeroId='artanis',rank=5,mode:Mode='battle',ready=false,spawnAt=0,previous=performance.now(),zoom='close',boss:number|null=null,bossHp=0,bossAt=0,bossResult='',observer:number|null=null,observerAt=1.2;
const keys=new Set<string>(),baseline=new Map<number,number>(),patients:number[]=[];
function resize(){view.resize();view.camera.zoom=canvas.clientWidth<canvas.clientHeight?1.04:zoom==='close'?1.65:1.18;view.camera.updateProjectionMatrix();}new ResizeObserver(resize).observe(canvas);
function dummy(x:number,z:number,air=false){const e=world.addUnit(air?'mutalisk':'roach','zerg',x,z,1,'regular',13);e.hp=e.maxHp=2e6;e.armor=0;e.moveSpeed=0;e.nextShotAt=1e9;e.specialReady=1e9;baseline.set(e.id,e.hp);return e;}
function support(){world.expedition.familySlots=['zealot','stalker'];for(let i=0;i<7;i++){const a=world.addUnit(i<5?'zealot':'stalker','terran',.4+(i%3)*1.25,-2+Math.floor(i/3)*2,3);a.shield=a.maxShield!*.08;a.stoppedUntil=1e9;patients.push(a.id);}}
function choose(id:ProtossHeroId){if((id==='artanis'||id==='vorazun')&&(mode==='boss12'||mode==='boss3')){mode='skill';($('mode') as HTMLSelectElement).value=mode;}
 hero=id;view.resetRun();world.resetRun();world.start();world.entities.clear();world.heroes.clear();world.pods=[];world.hive=null;world.expansionHives.clear();world.economicTargets.clear();world.fortifications.clear();world.pickups=[];world.rewardDrops=[];world.stage=mode==='boss12'?12:13;world.difficulty=mode==='boss12'||mode==='boss3'?'easy':'normal';world.stageElapsed=0;baseline.clear();patients.length=0;boss=null;bossResult='';observer=null;observerAt=1.2;
 for(const p of Object.values(world.expedition.production))p.enabled={};world.acquireHero(id);const u=world.heroEntity(id)!;u.rank=rank;world.heroes.get(id)!.rank=rank;world.refreshStats(u,true);u.x=-1.5;u.z=0;u.prev={x:u.x,z:u.z};world.anchor.x=world.anchor.z=0;world.wallet.minerals=0;initializeCarrierSubsystem(world);spawnAt=0;world.paused=false;keys.clear();world.resetDirectionalInput();
 if(mode==='attack'||mode==='skill'||mode==='shield'){const melee=['artanis','zeratul','alarak','vorazun'].includes(id),fleetSkill=id==='purifier_flagship'&&mode==='skill';for(const [x,z]of(melee?[[.3,0],[.8,.8],[1.7,0],[3,0],[2,-.8]]:fleetSkill?[[8,0],[9,0],[10,0],[8,1.2],[9,-1.3]]:[[3,0],[5,0],[7,0],[4,1.2],[6,-1.3]]))dummy(x,z);if(id==='fenix'||id==='purifier_flagship')dummy(fleetSkill?9:5,-3,true);}
 if(id==='artanis'||id==='purifier_flagship')support();
 if(mode==='skill'||mode==='shield'||mode==='boss12'||mode==='boss3'){u.stoppedUntil=1e9;for(const child of ownedInterceptors(world,u.id)){child.nextShotAt=1e9;child.pendingTarget=null;}}
 if((mode==='attack'||mode==='shield')&&(id==='fenix'||id==='purifier_flagship')){const e=[...world.entities.values()].find(a=>a.owner==='zerg')!;e.weaponDamage=id==='fenix'?Math.ceil(u.maxShield!*1.04):1200;e.attackRange=12;observer=e.id;}
 if(mode==='boss12'||mode==='boss3'){if(mode==='boss3'){world.stage=18;world.endless={round:3,startedAt:world.time,elites:0,bosses:0,progress:{wave:0,elite:0,boss:0},retry:{elite:1e9,boss:1e9},last:{}};const first=world.spawnSpecial('queen','boss',{x:12,z:0})!;world.entities.delete(first.id);}const e=world.spawnSpecial(mode==='boss3'?'lurker':'ravager','boss',{x:id==='zeratul'?.5:5,z:0})!;e.moveSpeed=0;e.stoppedUntil=1e9;e.specialReady=1e9;if(mode==='boss3')world.castDetection();boss=e.id;bossHp=Math.round(e.hp);baseline.set(e.id,e.hp);bossResult=`Boss ${bossHp} HP · 护甲 ${e.armor}`;}
 world.hash.rebuild(world.entities.values());for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.setAttribute('aria-pressed',String(b.dataset.hero===id));$('name').textContent=HEROES[id].name;$('description').textContent=description[id];$('pause').textContent='暂停';$('portrait').innerHTML=`<img src="${assetUrl('hero.'+id)}" alt="${HEROES[id].name}">`;$('state').textContent='';resize();world.changed();
}
function cast(){const u=world.heroEntity(hero);if(!u)return;const stopped=u.stoppedUntil;u.stoppedUntil=0;const ok=activateBattleAction(world,'hero-slot-0');u.stoppedUntil=stopped;if(ok)bossAt=world.time;}
const stepper=new FixedStepper(1/60,()=>{if(!ready||world.paused||world.phase!=='battle')return false;world.stageElapsed=0;world.rewardDrops=[];if(mode==='battle'&&world.time>=spawnAt&&world.enemyCount()<24){for(let i=0;i<5;i++)world.addUnit(i%3?'roach':'zergling','zerg',world.anchor.x+5+i*.6,world.anchor.z+(i-2)*1.3,1,'regular',13);spawnAt=world.time+1.6;}if(observer&&world.time>=observerAt){const e=world.entities.get(observer),u=world.heroEntity(hero);if(e&&u){world.fire(e,u);e.stoppedUntil=1e9;e.nextShotAt=1e9;}observer=null;}world.input.x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0);world.input.z=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(mode==='boss3'&&world.endless)world.endless.startedAt=world.time;world.step();return true;},()=>performance.now(),8);
function frame(now:number){requestAnimationFrame(frame);const dt=Math.min(.05,(now-previous)/1000);previous=now;const alpha=ready&&!world.paused?stepper.advance(dt):0;view.render(dt,alpha);if(!ready)return;const u=world.heroEntity(hero),hp=Math.max(0,u?.hp??0);$('vital-fill').style.width=hp/(u?.maxHp??1)*100+'%';$('health').textContent=`生命 ${Math.ceil(hp)} / ${Math.ceil(u?.maxHp??0)} · 护盾 ${Math.ceil(u?.shield??0)} / ${Math.ceil(u?.maxShield??0)}`;$('kills').textContent=String(world.stats.kills);$('time').textContent=Math.floor(world.time/60).toString().padStart(2,'0')+':'+Math.floor(world.time%60).toString().padStart(2,'0');$('enemies').textContent=String(world.enemyCount());const left=Math.max(0,(world.heroes.get(hero)?.skillReady??0)-world.time);($('cast') as HTMLButtonElement).disabled=left>0||world.paused;$('cast').textContent=left>0?`${HEROES[hero].skill} · ${Math.ceil(left)}s`:'释放技能 · 空格';if(boss&&!world.entities.get(boss)?.hp&&!bossResult.startsWith('一发击杀'))bossResult=`一发击杀 · ${bossHp} HP · ${(world.time-bossAt).toFixed(2)} 秒`;else if(boss&&world.entities.get(boss)?.hp)bossResult=`Boss 剩余 ${Math.ceil(world.entities.get(boss)!.hp)} / ${bossHp}`;$('boss-result').textContent=bossResult;if(($('details') as HTMLDetailsElement).open)$('state').textContent=hero==='alarak'?`权势 ${u?.protossCombat?.power??0} / 20`:hero==='purifier_flagship'?`现存截击机 ${u?ownedInterceptors(world,u.id).length:0} / 12`:hero==='artanis'?`实际回盾 ${Math.ceil(world.stats.healed)}`:'';}
for(const id of ids){const b=document.createElement('button');b.dataset.hero=id;b.textContent=HEROES[id].name;b.disabled=true;$('heroes').append(b);}
for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.onclick=()=>choose(b.dataset.hero as ProtossHeroId);
($('mode') as HTMLSelectElement).onchange=()=>{mode=($('mode') as HTMLSelectElement).value as Mode;if(mode==='boss12')rank=1;if(mode==='boss3')rank=5;if(mode==='boss12'||mode==='boss3')hero='zeratul';($('rank') as HTMLSelectElement).value=String(rank);choose(hero);};($('rank') as HTMLSelectElement).onchange=()=>{rank=Number(($('rank') as HTMLSelectElement).value);choose(hero);};($('quality') as HTMLSelectElement).onchange=()=>view.fx.heroQuality=($('quality') as HTMLSelectElement).value as any;
$('cast').onclick=cast;$('pause').onclick=()=>{world.paused=!world.paused;$('pause').textContent=world.paused?'继续':'暂停';keys.clear();world.resetDirectionalInput();stepper.reset();};$('restart').onclick=()=>choose(hero);$('zoom').onclick=()=>{zoom=zoom==='close'?'battle':'close';resize();};
addEventListener('keydown',e=>{if((e.target as HTMLElement).matches('button,select')&&e.code!=='Space')return;if(e.code==='Space'){e.preventDefault();if(!e.repeat)cast();}else keys.add(e.key.toLowerCase());});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();world.resetDirectionalInput();});
canvas.addEventListener('pointerdown',e=>{if(!ready)return;const rect=canvas.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),view.camera);const p=new THREE.Vector3();if(ray.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),0),p))world.issueMove({x:p.x,z:p.z});});
(window as any).__PROTOSS_HERO_ADVANCE__=(seconds:number)=>{if(!Number.isFinite(seconds)||seconds<0||seconds>30)throw Error('Invalid observation interval');const paused=world.paused;world.paused=false;for(let i=0;i<Math.round(seconds*60);i++){stepper.advance(1/60);view.protossHeroes.beginFrame();}world.paused=paused;view.render(0,1);};
(window as any).__PROTOSS_HERO_SAVE__=()=>encodeGraph(world.captureRun());
(window as any).__PROTOSS_HERO_RESTORE__=(snapshot:ReturnType<typeof encodeGraph>)=>{world.restoreRun(decodeGraph(snapshot) as ReturnType<World['captureRun']>);view.resetRun();stepper.reset();keys.clear();view.render(0,1);};
(window as any).__PROTOSS_HERO_REPORT__=()=>({ready,hero,rank,mode,time:world.time,paused:world.paused,phase:world.phase,quality:view.fx.heroQuality,shots:world.stats.shots,damage:world.stats.damage,healed:world.stats.healed,boss:{id:boss,originalHp:bossHp,hp:boss?world.entities.get(boss)?.hp??0:null,result:bossResult},render:view.protossHeroes.report(),modelErrors:view.modelErrors,fxErrors:view.fx.errors,source:world.heroEntity(hero),state:world.protossHeroes,targets:[...baseline].map(([id,before])=>({id,before,hp:world.entities.get(id)?.hp,stoppedUntil:world.entities.get(id)?.stoppedUntil,slow:world.entities.get(id)?.attackSlowFactor})),children:world.heroEntity(hero)?ownedInterceptors(world,world.heroEntity(hero)!.id).map(u=>({id:u.id,hp:u.hp,damage:u.weaponDamage,period:u.attackPeriod,owner:u.summonOwnerId})):[],schema:RUN_SCHEMA});
async function load(){await loadEmbeddedAssets();await prepareEmbeddedAssetIds(selected,(d,t)=>{$('interface').textContent=`准备神族 ${d}/${t}`;});await view.fx.load();await view.confirmedHeroes.prepare();await view.zergHeroes.prepare();view.protossHeroes.prepare();for(const type of ['roach','zealot','stalker','interceptor','mutalisk','ravager','lurker','baneling','hydralisk'] as const)if(!await view.ensureUnitVariant(type,type))throw Error(view.modelErrors.join(';'));for(const id of ids)if(!await view.ensureUnitVariant(HEROES[id].model,HEROES[id].baseFamily))throw Error(view.modelErrors.join(';'));
 const texture=await new THREE.TextureLoader().loadAsync(assetUrl('map.terrain.diffuse')!);texture.colorSpace=THREE.SRGBColorSpace;const layers=terrainArray(texture),material=new THREE.MeshStandardMaterial({map:texture,color:0xa0a69a,roughness:1});material.onBeforeCompile=s=>{s.uniforms.groundLayers={value:layers};s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nuniform highp sampler2DArray groundLayers;');s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','float groundPatch=sin(vMapUv.x*27.0)*sin(vMapUv.y*31.0);vec3 ground=texture(groundLayers,vec3(vMapUv*32.0,4.0)).rgb;ground=mix(ground,texture(groundLayers,vec3(vMapUv*32.0,5.0)).rgb,smoothstep(-.5,.6,groundPatch)*.25);diffuseColor.rgb*=ground;');};material.customProgramCacheKey=()=> 'protoss-demo-original-terrain-layers-v1';const floor=new THREE.Mesh(new THREE.PlaneGeometry(100,100),material);floor.rotation.x=-Math.PI/2;floor.position.y=-.025;view.scene.add(floor);view.initialAssetsLoaded=false;choose(hero);await view.warmPresentationBatches();ready=true;$('interface').hidden=true;for(const b of document.querySelectorAll<HTMLButtonElement>('[data-hero]'))b.disabled=false;previous=performance.now();}
requestAnimationFrame(frame);load().catch(e=>{$('interface').textContent='载入失败：'+e.message;console.error(e);});
