// Generated by tools/material-batch2-elites.mjs; explicit render-only identity choices.
import type {EliteId} from './elites';
export type EliteMaterialActivity='native-effects'|'warmup'|'overload'|'transform-boost'|'terran-charge'|'acid-pressure'|'regeneration'|'zerg-boost'|'psionic-stacks'|'psionic-boost'|'blink-barrier'|'judgment'|'beam-lock'|'carrier-overdrive';
export const ELITE_VISUAL_PROFILES:Record<EliteId,{model:string;forms:Record<string,string>;teamColor:number;activity:EliteMaterialActivity;groundScale:number;flyingScale:number}> = {
  "marine.1": {
    "model": "elite.marine.1",
    "forms": {},
    "teamColor": 13671011,
    "activity": "warmup",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "marine.2": {
    "model": "elite.marine.2",
    "forms": {},
    "teamColor": 7780311,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "marine.3": {
    "model": "elite.marine.3",
    "forms": {},
    "teamColor": 12828066,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "marauder.1": {
    "model": "elite.marauder.1",
    "forms": {},
    "teamColor": 8563388,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "marauder.2": {
    "model": "elite.marauder.2",
    "forms": {},
    "teamColor": 7641292,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "marauder.3": {
    "model": "elite.marauder.3",
    "forms": {},
    "teamColor": 11833966,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hellion.1": {
    "model": "elite.hellion.1",
    "forms": {
      "hellbat": "hellion.hellbat"
    },
    "teamColor": 13605730,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hellion.2": {
    "model": "elite.hellion.2",
    "forms": {
      "hellbat": "hellion.hellbat"
    },
    "teamColor": 12480596,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hellion.3": {
    "model": "elite.hellion.3",
    "forms": {
      "hellbat": "hellion.hellbat"
    },
    "teamColor": 9939083,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "tank.1": {
    "model": "elite.tank.1",
    "forms": {},
    "teamColor": 10134666,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "tank.2": {
    "model": "elite.tank.2",
    "forms": {},
    "teamColor": 9870245,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "tank.3": {
    "model": "elite.tank.3",
    "forms": {},
    "teamColor": 12158313,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "medivac.1": {
    "model": "elite.medivac.1",
    "forms": {},
    "teamColor": 12241849,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "medivac.2": {
    "model": "elite.medivac.2",
    "forms": {},
    "teamColor": 7388330,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "medivac.3": {
    "model": "elite.medivac.3",
    "forms": {},
    "teamColor": 9091536,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "reaper.1": {
    "model": "elite.reaper.1",
    "forms": {},
    "teamColor": 8886952,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "thor.1": {
    "model": "elite.thor.1",
    "forms": {},
    "teamColor": 11056284,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "viking.1": {
    "model": "elite.viking.1",
    "forms": {
      "viking_assault": "elite.viking.1.assault"
    },
    "teamColor": 8695241,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "banshee.1": {
    "model": "elite.banshee.1",
    "forms": {},
    "teamColor": 10193576,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "science_vessel.1": {
    "model": "elite.science_vessel.1",
    "forms": {},
    "teamColor": 8173712,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "zergling.1": {
    "model": "elite.zergling.1",
    "forms": {},
    "teamColor": 12032628,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "baneling.1": {
    "model": "elite.baneling.1",
    "forms": {},
    "teamColor": 9551715,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "roach.1": {
    "model": "elite.roach.1",
    "forms": {},
    "teamColor": 10786686,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "ravager.1": {
    "model": "elite.ravager.1",
    "forms": {},
    "teamColor": 11966322,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hydralisk.1": {
    "model": "elite.hydralisk.1",
    "forms": {},
    "teamColor": 12364417,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "lurker.1": {
    "model": "elite.lurker.1",
    "forms": {},
    "teamColor": 12233603,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "queen.1": {
    "model": "elite.queen.1",
    "forms": {},
    "teamColor": 9549466,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "mutalisk.1": {
    "model": "elite.mutalisk.1",
    "forms": {},
    "teamColor": 12229505,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "corruptor.1": {
    "model": "elite.corruptor.1",
    "forms": {},
    "teamColor": 10992503,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "ultralisk.1": {
    "model": "elite.ultralisk.1",
    "forms": {},
    "teamColor": 11772024,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "zealot.1": {
    "model": "elite.zealot.1",
    "forms": {},
    "teamColor": 13543283,
    "activity": "psionic-stacks",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "adept.1": {
    "model": "elite.adept.1",
    "forms": {},
    "teamColor": 10071497,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "stalker.1": {
    "model": "elite.stalker.1",
    "forms": {},
    "teamColor": 10463429,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "sentry.1": {
    "model": "elite.sentry.1",
    "forms": {},
    "teamColor": 8960943,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "immortal.1": {
    "model": "elite.immortal.1",
    "forms": {},
    "teamColor": 12754036,
    "activity": "judgment",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "colossus.1": {
    "model": "elite.colossus.1",
    "forms": {},
    "teamColor": 12818540,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "high_templar.1": {
    "model": "elite.high_templar.1",
    "forms": {},
    "teamColor": 10198731,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "phoenix.1": {
    "model": "elite.phoenix.1",
    "forms": {},
    "teamColor": 9156304,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "void_ray.1": {
    "model": "elite.void_ray.1",
    "forms": {},
    "teamColor": 11182286,
    "activity": "beam-lock",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "carrier.1": {
    "model": "elite.carrier.1",
    "forms": {},
    "teamColor": 12168065,
    "activity": "carrier-overdrive",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "viking.2": {
    "model": "elite.viking.1",
    "forms": {
      "viking_assault": "elite.viking.1.assault"
    },
    "teamColor": 11902333,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "viking.3": {
    "model": "elite.viking.1",
    "forms": {
      "viking_assault": "elite.viking.1.assault"
    },
    "teamColor": 10398157,
    "activity": "transform-boost",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "ravager.2": {
    "model": "elite.ravager.1",
    "forms": {},
    "teamColor": 10731124,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "ravager.3": {
    "model": "elite.ravager.1",
    "forms": {},
    "teamColor": 7975051,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "high_templar.2": {
    "model": "elite.high_templar.1",
    "forms": {},
    "teamColor": 9680074,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "high_templar.3": {
    "model": "elite.high_templar.1",
    "forms": {},
    "teamColor": 8762543,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "reaper.2": {
    "model": "elite.reaper.1",
    "forms": {},
    "teamColor": 11639414,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "reaper.3": {
    "model": "elite.reaper.1",
    "forms": {},
    "teamColor": 9349788,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "thor.2": {
    "model": "elite.thor.1",
    "forms": {},
    "teamColor": 8758467,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "thor.3": {
    "model": "elite.thor.1",
    "forms": {},
    "teamColor": 12883561,
    "activity": "overload",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "banshee.2": {
    "model": "elite.banshee.1",
    "forms": {},
    "teamColor": 10268023,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "banshee.3": {
    "model": "elite.banshee.1",
    "forms": {},
    "teamColor": 7713715,
    "activity": "terran-charge",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "science_vessel.2": {
    "model": "elite.science_vessel.1",
    "forms": {},
    "teamColor": 11842164,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "science_vessel.3": {
    "model": "elite.science_vessel.1",
    "forms": {},
    "teamColor": 8236497,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "zergling.2": {
    "model": "elite.zergling.1",
    "forms": {},
    "teamColor": 9746039,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "zergling.3": {
    "model": "elite.zergling.1",
    "forms": {},
    "teamColor": 11827331,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "baneling.2": {
    "model": "elite.baneling.1",
    "forms": {},
    "teamColor": 9218913,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "baneling.3": {
    "model": "elite.baneling.1",
    "forms": {},
    "teamColor": 12821110,
    "activity": "acid-pressure",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "roach.2": {
    "model": "elite.roach.1",
    "forms": {},
    "teamColor": 10204270,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "roach.3": {
    "model": "elite.roach.1",
    "forms": {},
    "teamColor": 7974811,
    "activity": "regeneration",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hydralisk.2": {
    "model": "elite.hydralisk.1",
    "forms": {},
    "teamColor": 10725526,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "hydralisk.3": {
    "model": "elite.hydralisk.1",
    "forms": {},
    "teamColor": 9679725,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "lurker.2": {
    "model": "elite.lurker.1",
    "forms": {},
    "teamColor": 10593921,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "lurker.3": {
    "model": "elite.lurker.1",
    "forms": {},
    "teamColor": 9873066,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "queen.2": {
    "model": "elite.queen.1",
    "forms": {},
    "teamColor": 7648924,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "queen.3": {
    "model": "elite.queen.1",
    "forms": {},
    "teamColor": 10730102,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "mutalisk.2": {
    "model": "elite.mutalisk.1",
    "forms": {},
    "teamColor": 11444357,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "mutalisk.3": {
    "model": "elite.mutalisk.1",
    "forms": {},
    "teamColor": 12352903,
    "activity": "zerg-boost",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "corruptor.2": {
    "model": "elite.corruptor.1",
    "forms": {},
    "teamColor": 8563621,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "corruptor.3": {
    "model": "elite.corruptor.1",
    "forms": {},
    "teamColor": 10005352,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "ultralisk.2": {
    "model": "elite.ultralisk.1",
    "forms": {},
    "teamColor": 9285530,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "ultralisk.3": {
    "model": "elite.ultralisk.1",
    "forms": {},
    "teamColor": 12161649,
    "activity": "zerg-boost",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "zealot.2": {
    "model": "elite.zealot.1",
    "forms": {},
    "teamColor": 8567499,
    "activity": "psionic-boost",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "zealot.3": {
    "model": "elite.zealot.1",
    "forms": {},
    "teamColor": 12040608,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "adept.2": {
    "model": "elite.adept.1",
    "forms": {},
    "teamColor": 13348227,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "adept.3": {
    "model": "elite.adept.1",
    "forms": {},
    "teamColor": 11836863,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "stalker.2": {
    "model": "elite.stalker.1",
    "forms": {},
    "teamColor": 11901124,
    "activity": "blink-barrier",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "stalker.3": {
    "model": "elite.stalker.1",
    "forms": {},
    "teamColor": 7910601,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "sentry.2": {
    "model": "elite.sentry.1",
    "forms": {},
    "teamColor": 10136784,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "sentry.3": {
    "model": "elite.sentry.1",
    "forms": {},
    "teamColor": 10721994,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "immortal.2": {
    "model": "elite.immortal.1",
    "forms": {},
    "teamColor": 8763851,
    "activity": "psionic-boost",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "immortal.3": {
    "model": "elite.immortal.1",
    "forms": {},
    "teamColor": 10790608,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "colossus.2": {
    "model": "elite.colossus.1",
    "forms": {},
    "teamColor": 9680321,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "colossus.3": {
    "model": "elite.colossus.1",
    "forms": {},
    "teamColor": 10984646,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "phoenix.2": {
    "model": "elite.phoenix.1",
    "forms": {},
    "teamColor": 10788038,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "phoenix.3": {
    "model": "elite.phoenix.1",
    "forms": {},
    "teamColor": 11123144,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "void_ray.2": {
    "model": "elite.void_ray.1",
    "forms": {},
    "teamColor": 9420496,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "void_ray.3": {
    "model": "elite.void_ray.1",
    "forms": {},
    "teamColor": 8435632,
    "activity": "native-effects",
    "groundScale": 1.25,
    "flyingScale": 1.15
  },
  "carrier.2": {
    "model": "elite.carrier.1",
    "forms": {},
    "teamColor": 8891077,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  },
  "carrier.3": {
    "model": "elite.carrier.1",
    "forms": {},
    "teamColor": 9551284,
    "activity": "native-effects",
    "groundScale": 1.12,
    "flyingScale": 1.15
  }
};
